### ISSUE TITLE
Eloquent: firstOrFail has unspecific return type

### ISSUE THREAD

**Issue by ntzm** [nunomaduro/larastan#100]
- Larastan Version: 0.2.4
- `--level` used: 5

### Description:

`Model::where('foo', 'bar')->firstOrFail()` has a return type of `Illuminate\Database\Eloquent\Model` instead of the correct model like `first` does

### Laravel code where the issue was found:

`Model::where('foo', 'bar')->firstOrFail()`

**Comment by mr-feek** [comment]
I can confirm I'm still seeing this on 0.3.13

**Comment by mr-feek** [comment]
Actually, this seems fixed now. However, I am running into https://github.com/nunomaduro/larastan/issues/255

**Comment by szepeviktor** [comment]
@nunomaduro Hello!
On a _special day_ could you help us to support Eloquent? There are ~5 open issues when chaining Eloquent methods misleads Larastan.

**Comment by canvural** [comment]
Related to #324 

So, #325 should also fix this :+1:

**Comment by szepeviktor** [comment]
Finally. 🚀

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?
