### ISSUE TITLE
Php 8 strict types

### ISSUE THREAD

**Issue by emreakay** [nunomaduro/larastan#1000]
Hi,

how can i check php's strict types?

Thanks.

**Comment by canvural** [comment]
Hi,

What do you mean exactly? Can you give some examples?

**Comment by emreakay** [comment]
@canvural i mean, i want larastan check if i use  - all the php strict types for varibles, function paramters and functions return types - or not.

**Comment by canvural** [comment]
That's actually the PHPStan's job. But yes, it already does all of that.

**Comment by szepeviktor** [comment]
# Issue number One Thousand
