### ISSUE TITLE
Custom builders break model methods return type inference

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1001]
- Larastan Version: 1.0.0
- `--level` used: 2
- Pull request with failing test: https://github.com/MatanYadaev/larastan/pull/1

### Description
When using custom builders with models, Larastan doesn't infer correctly the model methods' return type, for example, Larastan infers `User::first()` or `User::create($data)` return `Model` instead of `User`.
When you remove the `newEloquentBuilder` method - this issue is gone. The issue is 100% because of the custom builder.

### Laravel code where the issue was found

```php
/**
 * @extends Builder<User>
 */
class UserBuilder extends Builder
{
  //
}
```
```php
class User extends Model
{
  /**
   * @param  \Illuminate\Database\Query\Builder  $query
   * @return UserBuilder<User>
   */
  public function newEloquentBuilder($query): UserBuilder
  {
    return new UserBuilder($query);
  }

  public function doSomething(): void
  {
    //
  }
}
```
```php
$user = User::first();
$user->doSomething(); // Call to an undefined method Illuminate\Database\Eloquent\Model::doSomething().
```

**Comment by szepeviktor** [comment]
Hello Matan! 👋 
Thank you for your report.

Our secret upgrade guide comes to the rescue.
https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders

**Comment by szepeviktor** [comment]
> `--level` used: 2

I encourage you to reach level 4 which is - in Viktor terms - _the healthy application_.

**Comment by MatanYadaev** [comment]
Hi @szepeviktor, thanks for the super quick response. I read the upgrade guide, it didn't help, but I realize what causes my issue. My custom builder is actually extending another custom builder - I updated my PR so you could check it. My custom builder extends `\Grimzy\LaravelMysqlSpatial\Eloquent\Builder`.

> I encourage you to reach level 4 which is - in Viktor terms - the healthy application.
I really wish to reach that, my project is currently on level 1 with a massive amount PHPStan issue, I try to tackle them one by one until I'll reach level 3 or 4. Thanks for the tip.

**Comment by canvural** [comment]
Hi,

Like the upgrade guide says you need mark your as generic.

```php
/**
 * @template TModelClass of \Illuminate\Database\Eloquent\Model
 * @extends Builder<TModelClass>
 */
class UserBuilder extends Builder
```

> My custom builder extends \Grimzy\LaravelMysqlSpatial\Eloquent\Builder.

In this case you have 2 options:
- Ask the maintainers of that package to add the same generic docblocks to that class
- Use stub files to override it yourself

**Comment by szepeviktor** [comment]
> I try to tackle them one by one

Try [Rector](https://github.com/rectorphp), it has a Laravel-specific packages.

**Comment by MatanYadaev** [comment]
@canvural The package is completely abandoned, so a PR is not a question. About the second option, I added a stub, but it still doesn't work. Maybe I did it wrong? https://github.com/MatanYadaev/larastan/pull/1/files#diff-38519629a21b200bd3a828240670ceab018dca68c0da27e906554053114f3503

**Comment by MatanYadaev** [comment]
NVM. Managed to fix it. This is my final stub:
```php
<?php

namespace Grimzy\LaravelMysqlSpatial\Eloquent;

use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialExpression;
use Grimzy\LaravelMysqlSpatial\Types\GeometryInterface;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

/**
 * @template TModelClass of \Illuminate\Database\Eloquent\Model
 * @extends EloquentBuilder<TModelClass>
 */
class Builder extends EloquentBuilder
{
}
```
Thanks for the help!
