### ISSUE TITLE
\Illuminate\Http\Request::validate() should throw exception

### ISSUE THREAD

**Issue by mirucon** [nunomaduro/larastan#1004]
- Larastan Version: 1.0.0
- `--level` used: 8
- Pull request with failing test: N/A

### Description

When using the code below, PHPStan generates the following error:

```
Call to static method Illuminate\Http\Request::validate() on a separate line has no effect.
```

Since Request::validate() throws `\Illuminate\Validation\ValidationException` when validation fails, using the method without any assignment should be a valid usage.

I think the problem occurs because larastan doesn't define that Request::validate throws an exception?

### Laravel code where the issue was found

```php
public function method(\Illuminate\Http\Request $request)
{
    $request->validate([
        'key' => ['string'],
    ]);
}
```

**Comment by mabasic** [comment]
I think that it has nothing to do with throwing an exception. Here is the same issue: https://github.com/nunomaduro/larastan/issues/995

**Comment by canvural** [comment]
Hi,

Thank you for the report. I think you are right Larastan doesn't know that `validate` can throw exception. I'll see what we can do.

@mabasic They are not the same issue. Completely different.

**Comment by mabasic** [comment]
This

```
Call to static method Illuminate\Http\Request::validate() on a separate line has no effect.
```

is not the same as this:

```
Dynamic call to static method Illuminate\\Http\\Request::validate().
```

The same code triggers it:

```
$request->validate();
```

**Comment by canvural** [comment]
Yes, they are literally different error messages.

**Comment by mabasic** [comment]
Aha, I see now. This issue has to do with `$request->validate()` (where there is nothing passed to the validate function) and the issue that I have linked has to do with treating `$request->validate([])` as a static method call.

My bad, sorry.

**Comment by szepeviktor** [comment]
> But isn't it wrong that `$request->validate()` is treated as a static method?

Please continue in #995
