### ISSUE TITLE
Unrecognized model property with custom cast when generating external model ide helper

### ISSUE THREAD

**Issue by lloricode** [nunomaduro/larastan#1007]
- Larastan Version: 1.0.0
- `--level` used: 7
- Pull request with failing test:

### Description

We use barryvdh/laravel-ide-helper with v2.10.0 and [andriichuk/laracash v2.0.0](https://github.com/andriichuk/laracash/releases/tag/v2.0.0)

in model have
```php
# model

use Andriichuk\Laracash\Casts\MoneyCast;

    protected $casts = [
        'price_amount' => MoneyCast::class,
   ];

```

generating ide helper model useing `php artisan ide-helper:models --reset --write` will generate docs in file model

```php
/**
 * @property \Money\Money $price_amount
 * @mixin \Eloquent
 */
class Product extends Model

```

that was working fine,
but we plan to extract ide model helper to external file using `php artisan ide-helper:models -N`, and remove all doc block in file in `Product` model, 

```php

# in root folder file `_ide_helper_models.php`
namespace App\Models\Product{
/**
 * @property \Money\Money $price_amount manage 
 */
class Product extends \Eloquent {}
}
```

running again phpstan will produce this

![Screenshot from 2021-11-04 09-15-33](https://user-images.githubusercontent.com/8251344/140241008-a11faffa-7823-4573-a14d-2ee9d8c3f09e.png)

### Laravel code where the issue was found

```php
    public function transform(Product $product): array
    {
        return [
            'amount' => $product->price_amount,
        ];
    }
```

Thank you

**Comment by szepeviktor** [comment]
Hello Lloric! 👋 
Thank you for your issue.

Larastan takes Model peoperties from (proper) migrations.
https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md#databasemigrationspath

> remove all doc block in file in Product model

Very, very, very good!!

**Comment by lloricode** [comment]
> Hello Lloric! wave Thank you for your issue.
> 
> Larastan takes Model peoperties from (proper) migrations. https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md#databasemigrationspath
> 
> > remove all doc block in file in Product model
> 
> Very, very, very good!!

Hi, thank for the response, we do not move migration file and its already in default path

thank you

**Comment by szepeviktor** [comment]
Using `barryvdh/laravel-ide-helper` and Larastan together result in an unstable operation.

**Comment by lloricode** [comment]
> Using `barryvdh/laravel-ide-helper` and Larastan together results in an unstable operation.

i see, maybe should report this to larastan, since other custom cast work well,

thank you @szepeviktor

**Comment by lloricode** [comment]
@szepeviktor thanks for the information
