### ISSUE TITLE
pluck()->toArray() warning

### ISSUE THREAD

**Issue by shemgp** [nunomaduro/larastan#1018]
- Larastan Version: 1.0.1
- `--level` used: 0

### Description

I have:
```php
            $return = DB::table('acad_chsh')
                    ->get('id_people')->pluck('id_people')->toArray();
```
Which gives me warning of:
```
Called 'pluck' on Laravel collection, but could have been retrieved as a query.
```
I think it's a bug since i'm going to convert it to an array.

If it's not, can you please point me to how to make a pluck()->toArray() as a query? Thanks.

I see you're using it [here](https://github.com/nunomaduro/larastan/blob/c4081aa5806ecbc56b22cce042560685b9c459db/tests/Application/app/Thread.php#L34)

**Comment by szepeviktor** [comment]
Hello Shem! 👋 

I'm not a developer but have you tried `->pluck('id_people')->get('id_people')->toArray();` ?

**Comment by shemgp** [comment]
@szepeviktor nope. didn't do it. Thanks for your input anyway.

**Comment by szepeviktor** [comment]
@shemgp I've found our secret docs for you.
https://github.com/nunomaduro/larastan/blob/master/docs/rules.md#nounnecessarycollectioncall

**Comment by stein-j** [comment]
Hello @shemgp,

The change that LaraStan is telling you to do it to remove the `->get()` and directly call pluck:

```php
$return = DB::table('acad_chsh')->pluck('id_people')->toArray();
```

**Comment by shemgp** [comment]
Thanks @stein-j 

I didn't even notice the `->get('id_people')` there. Sorry for the noise. Thanks for your help.
