### ISSUE TITLE
Issue with mapWithKeys

### ISSUE THREAD

**Issue by underdpt** [nunomaduro/larastan#1021]
- Larastan Version: 1.0.1
- `--level` used: 7
- Pull request with failing test: I'm sorry I'm currently unable to submit a PR

### Description

Using a Collection `mapWithKeys` which return a string key, I get the error:

```
Parameter #1 $callback of method Illuminate\Support\Collection<int,string|false>::mapWithKeys() 
expects callable(string|false, int): array, 
Closure(string): non-empty-array<string, string> given.
```

It expects an array, and it receives an non-empty-array, so there should be no error if I'm not mistaken.

### Laravel code where the issue was found

```php
        $names= $files->mapWithKeys(function (string $path) {
            return [basename($path) => $path];
        });
```

**Comment by szepeviktor** [comment]
Hello David!
Thank you for your report.

I think this is a PHPStan issue: a non-empty-array doe not suffice a general array.

**Comment by underdpt** [comment]
For reference, the question and answer on PHPStan: https://github.com/phpstan/phpstan/discussions/5967

**Comment by szepeviktor** [comment]
I was looking for the word: contravariant.
