### ISSUE TITLE
Inheritance for Model ID type is being ignored

### ISSUE THREAD

**Issue by danilopolani** [nunomaduro/larastan#1022]
- Larastan Version: 1.0.1
- `--level` used: 5

### Description
Partially related to https://github.com/nunomaduro/larastan/issues/536, it seems that class inheritance for Model ID is being ignored when defining class properties, also with usage of `{inheritDoc}`. I found this [old issue from PHPStan](https://github.com/phpstan/phpstan/issues/671) where they make `inheritDoc` automatic for classes definition, but it does not seem to apply for this scenario. 

**TL;DR** my models use UUID as id instead of `int`, so they cast to `string`. if you define a base model with the given property type and write regular models to extend it, the `id` is always casted to `int`, the only working fix is to use `@mixin` but it's redundant since they made also the usage of `inheritDoc` redundant.

If this can help, [here's a repository](https://github.com/danilopolani/larastan-id-string-inheritance) to reproduce the bug, the "main" code is inside the [`TestController`](https://github.com/danilopolani/larastan-id-string-inheritance/blob/master/app/Http/Controllers/TestController.php).

### Laravel code where the issue was found

**❌ Fails (no PHPDoc on child)**

```php
// App\Models\Model.php

/**
 * @property-read string $id
 */
class Model extends \Illuminate\Database\Eloquent\Model
{
    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The data type of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';
}
```

```php
// App\Models\Post.php

class Post extends \App\Models\Model
{
    
}
```

```php
$post = new Post();

foo($post->id); // ❌ Parameter #1 $id of function foo() expects string, int given.

function foo(string $id) {
  //
}
```

----

**❌ Fails (`inheritDoc`)**

```php
// App\Models\Post.php

/**
 * {@inheritDoc}
 */
class Post extends \App\Models\Model
{
    
}
```

```php
$post = new Post();

foo($post->id); // ❌ Parameter #1 $id of function foo() expects string, int given.

function foo(string $id) {
  //
}
```

----

**✅ Passes (`mixin`)**

```php
// App\Models\Post.php

/**
 * @mixin \App\Models\Model
 */
class Post extends \App\Models\Model
{
    
}
```

```php
$post = new Post();

foo($post->id); // ✅ [OK] No errors
function foo(string $id) {
  //
}
```

**Comment by szepeviktor** [comment]
Hello @danilopolani!
This is highly non-official: Could be. Seems to be trivial to fix.

**Comment by canvural** [comment]
Hi,

Looks like you don't have migration for `posts` table in the example repo. If you create a migration, something like this,
```php
Schema::create('posts', function (Blueprint $table) {
    $table->uuid('id');
    $table->timestamps();
});
```

it'll work.

**Comment by danilopolani** [comment]
> Hi,
> 
> Looks like you don't have migration for `posts` table in the example repo. If you create a migration, something like this,
> 
> ```
> Schema::create('posts', function (Blueprint $table) {
>     $table->uuid('id');
>     $table->timestamps();
> });
> ```
> 
> it'll work.

Thank you both for replies, maybe this is the solution: I mean, obviously I have migrations in my real project, but I think the issue was that I was using a macro on `Blueprint` to generate primary UUID (idk why). Replacing the macro with a simple `->uuid('id')->primary()` directly in the migration file seems to solve the issue indeed.

Thank you :)
