### ISSUE TITLE
Eloquent and Regular collection generic types

### ISSUE THREAD

**Issue by vanyamil** [nunomaduro/larastan#1026]
- Larastan Version: 1.0.1
- `--level` used: 3
- Pull request with failing test: ?

### Description

When calling the method `keyBy` on an instance of `Illuminate\Database\Eloquent\Collection` and then attempting to access this collection with a string offset, the analysis complains that
"Cannot assign offset string to Illuminate\Database\Eloquent\Collection<CustomModel>"
This is due to the method returning `new static()`.
However, since the type arguments differ on both classes' stubs (Key and Value types on Support\Collection,  only value on Eloquent\Collection), cannot use `@var \Illuminate\Support\Collection<string, CustomModel>` as a forced type-cast.

I understand that I can use `@var \Illuminate\Support\Collection` but I would like to be able to strongly type this.

### Laravel code where the issue was found

Using any CustomModel, do a query, then call ->keyBy('attr'). Then, access the result with any string.
```php
$keyed_col = CustomModel::get()->keyBy('name');
if(isset($keyed_col["abc"])) {}
```

**Comment by szepeviktor** [comment]
Thank you for reporting this!

This is what we have for `keyBy`
https://github.com/nunomaduro/larastan/blob/f74befd87b7278285cbf6f1597509cbfaca46bf8/src/Support/HigherOrderCollectionProxyHelper.php#L84-L90
