### ISSUE TITLE
Defining keyType outside of migrations

### ISSUE THREAD

**Issue by WesleyKlop** [nunomaduro/larastan#1029]
- Larastan Version: 1.0.1
- `--level` used: 5
- Pull request with failing test: n/a (not a bug)

### Description

Hey! I'm currently in the process of upgrading to the latest larastan version and I'm running into the issue where phpstan thinks all our models use int keys while in fact we use `string` uuids. 
I noticed #1022 but the provided solution does not work for us as the database our application uses predates the laravel application and is unfortunately missing the required migrations :( 
For our application it's also non-trivial to create these migrations after the fact so I was wondering if it could be possible to define the key type a different way? It used to work with the annotation on the parent class. I have the following proposed solutions:

* Allow inherited property type to work again
* Add phpstan.neon parameter like `defaultModelKeyType`

I'm not really familiar with the inner workings of this project if accepted I'd be fine with making the required changes myself :)

Have a nice day and thanks for maintaining this awesome project!

**Comment by szepeviktor** [comment]
> unfortunately missing the required migrations

No problem Wesley!
You can set a custom location
https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md#databasemigrationspath
where your proper migrations reside without Laravel executing it.
What do you think?

**Comment by WesleyKlop** [comment]
I don't think I like that. That would still require me to write A LOT of migrations. Did it have a particular reason that larastan does not look at the $keyType of model?

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/pull/1037

**Comment by WesleyKlop** [comment]
Just upgraded and everything works fine again!! Amazing thank you <3 <3 :)
