### ISSUE TITLE
`tap` helper closure enforces void return type

### ISSUE THREAD

**Issue by tpetry** [nunomaduro/larastan#1030]
- Larastan Version: 1.0.1
- `--level` used: 5

### Description
The `tap()` helper incorrectly specifies a void return type for the closure. The correct one should be of type any as it does not care on the return type. It needs to be any because arrow functions have automatically a return type which is not controllable.

### Laravel code where the issue was found

```php
return tap($user->isDirty(), fn () => $user->save());
```

**Comment by nunomaduro** [comment]
Can you pull request a fix for your issue?

**Comment by tpetry** [comment]
Sure, should it be `mixed|void` or `mixed`? What's your style used in larastan for this case?

**Comment by szepeviktor** [comment]
`mixed` includes everything!
