### ISSUE TITLE
Timestamp properties for eloquent models

### ISSUE THREAD

**Issue by tpetry** [nunomaduro/larastan#1033]
- Larastan Version: 1.0.1
- `--level` used: 5

### Description

Custom model properties need to be defined for phpstan to know of their existence. But if `$timestamps = true` is set or the `SoftDeletes` trait is used some properties are _definitely_ available on the model. At the moment larastan does pretend these properties do not exist. It'll be nice if the created and updated columns for timestampable models and deleted column for soft deletes would be added to the model properties by larastan.

### Laravel code where the issue was found

```php
class Test extends Model
{
}

$x = new Test();

dump($model->created_at); // Access to an undefined property App\Scratch\Scratch01\Test::$created_at.
// $model->{$model->getCreatedAtColumn()} is available!
```

**Comment by szepeviktor** [comment]
Hello Tobias! 👋 
Thank you for opening the issue.

Could you make sure you have this line in your migrations?
https://github.com/nunomaduro/larastan/blob/19098c78b33fc25ba6289d12538729a58cd60678/tests/Application/database/migrations/2020_01_30_000000_create_users_table.php#L28

**Comment by tpetry** [comment]
Timestamps are set in the migration, but i am using `timestampsTz` as it is an PostgreSQL application.

Is larastan parsing the migrations to decide whether timestamps are available?

**Comment by szepeviktor** [comment]
AFAIK yes. Please see in our source code.
https://github.com/nunomaduro/larastan/blob/19098c78b33fc25ba6289d12538729a58cd60678/src/Properties/SchemaAggregator.php#L185-L213

**Comment by tpetry** [comment]
Dumb question: Wouldn't it make sense for the timestamps to rely on the model?

```php
if ($model->timestamps) {
   $availableColumns = array_merge($availableColumns, [$model->getCreatedAtColumn(), $model->getUpdatedAtColumn()]);
}
if (trait_uses_recursive (SoftDeletes::class, $model)) {
   $availableColumns = array_merge($availableColumns, [$model->getDeletedAtColumn()]);
}
```

**Comment by szepeviktor** [comment]
Many users are protesting against migrations.
Let's see what project leaders say.

**Comment by canvural** [comment]
Hi,

Like @szepeviktor said, if you have the correct timestamps in the migrations Larastan will recognize it. `timestampsTz` is also supported.

If you don't have migrations, all the property accesses to models will produce error. So there is no point for making exception just for timestamps.

If you have the correct migrations, please give more detailed example with migrations, code producing error. Also does any other property access produces error?

**Comment by tpetry** [comment]
Migrations for adding these columns are available. But i am not allowed to share any code and small reproducible examples don't show the same problem.

**Comment by canvural** [comment]
Sounds like a problem with your setup then. Sorry, if I can't reproduce it I can't help.

**Comment by szepeviktor** [comment]
> small reproducible examples don't show the same problem

I have an idea for that. Try shrinking your code until won't show the same problem. Than you have the root cause!
