### ISSUE TITLE
whereRaw() method marked as undefined method within custom query builder

### ISSUE THREAD

**Issue by stevenrombauts** [nunomaduro/larastan#1034]
- Larastan Version: 1.0.1
- `--level` used: 1
- Pull request with failing test: n/a

### Description

phpstan will throw an error for any call to `whereRaw()` inside a customer builder class. Even after marking the builder class as a generic according to the [notes here](https://github.com/nunomaduro/larastan/blob/19866e06d5846f8c17460ce1c1808da8166d3747/UPGRADE.md#custom-eloquent-builders).

No errors are throw for a `where()` or `orWhere()` method for example. 

The exact error thrown from the code I'm working with (see below):

>   Call to an undefined method App\QueryBuilders\ProductQueryBuilder<TModelClass of Illuminate\Database\Eloquent\Model>::whereRaw().

Any pointers in the right direction much appreciated :)

### Laravel code where the issue was found

As an example, here is my model's `newEloquentBuilder()` method definition:

```php
namespace App\Models;

use App\QueryBuilders\ProductQueryBuilder;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
   /**
     * Create a new Product query builder for the model.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return \App\QueryBuilders\ProductQueryBuilder<Product>
     */
    public function newEloquentBuilder($query): ProductQueryBuilder
    {
        return new ProductQueryBuilder($query);
    }
}
```

The custom builder looks like this:

```php 
namespace App\QueryBuilders;

use Illuminate\Database\Eloquent\Builder;

/**
 * @template TModelClass of \Illuminate\Database\Eloquent\Model
 * @extends Builder<TModelClass>
 */
class ProductQueryBuilder extends Builder
{
/**
     * Select any unmatched rows
     *
     * @param string $value
     * @return $this
     */
    public function whereUnmatched()
    {
           return $this->whereRaw(DB::raw('products.sku = products.title'));
    }
}
```

**Comment by canvural** [comment]
Hi,

The issue comes from the docblocks of your custom builder. It should be:

```php
/**
 * @template TModelClass of \App\Models\Post
 * @extends Builder<TModelClass>
 */
```

Larastan needs to know the specific model type.

**Comment by stevenrombauts** [comment]
@canvural Thank you, that solved it right away.  

Do you know why this solves the problem? The model itself is just a class that extends `\Illuminate\Database\Eloquent\Model`, so I would expect it to find the `::whereRaw()` method anyway? I'm not sure I understand I understand the difference in this context.
