### ISSUE TITLE
Error in factories after enabling `checkModelProperties`

### ISSUE THREAD

**Issue by bram-pkg** [nunomaduro/larastan#1038]
- Larastan Version: 1.0.1
- `--level` used: 8

### Description

When enabling the `checkModelProperties` check, all factories give an error about the return type of the `definition()` method.

```
Return type (array<string, mixed>) of method Database\Factories\UserFactory::definition() 
should be compatible with return type (array<string, mixed>) 
of method Illuminate\Database\Eloquent\Factories\Factory<Illuminate\Database\Eloquent\Model>::definition()
```

### Laravel code where the issue was found

```php
/**
 * Define the model's default state.
 *
 * @return array<string, mixed>
 * @noinspection PhpArrayShapeAttributeCanBeAddedInspection
 */
public function definition(): array
{
    return [
        'name'              => $this->faker->name,
        'email'             => $this->faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password'          => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'remember_token'    => Str::random(10),
    ];
}
```

**Comment by szepeviktor** [comment]
`(array<string, mixed>) != (array<string, mixed>)`

Very trick problem.

**Comment by canvural** [comment]
Hi,

This is expected. Although I agree that error message is confusing.

When you enable `checkModelProperties` you enable a new type called `model-property` And the generic `model-property<Model>` is not the same type as `string` It's a subtype that only accepts the model property names of a specific model.

So first of all, if you didn't do it yet, add `@extends` tags to tour factories. It's explained [here.](https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#laravel-8-model-factory-support) 

Then you have couple of options:
- You can delete the return typehint from your `definition` method. PHPStan will get the correct type from the parent class.
- You can change it to `@return array<model-property<TModel>, mixed>`

**Comment by bram-pkg** [comment]
Thanks @canvural 

I have added your recommended `@extends` PHPdoc and removed the return types.
