### ISSUE TITLE
Relations count & sync fail

### ISSUE THREAD

**Issue by Krato** [nunomaduro/larastan#104]
- Larastan Version: 0.2.4
- `--level` used: default

### Description:

Relation count and sync are failing. 

### Laravel code where the issue was found:

```php
$tag = Tag::find(1);
$tag->posts()->count()

//Method in Tag
/**
  * The posts
  *
  * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
  */
 public function posts(): BelongsToMany
 {
     return $this->belongsToMany(Post::class, 'post_tag', 'tag_id', 'post_id');
 }

```

Error: 
    `Call to an undefined method (Illuminate\Database\Eloquent\Collection&iterable<App\Blog\Models\Tag>)|Illuminate\Database\Eloquent\Model::posts()`.

```php
$post = Post::find(1);
$post->tags()->sync($tags);


//Method in post
/**
  * Get all tags for the post.
  *
  * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
  */
 public function tags(): BelongsToMany
 {
     return $this->belongsToMany(Tag::class, 'post_tag', 'post_id', 'tag_id');
 }
```

Error: 
    `Call to an undefined method (Illuminate\Database\Eloquent\Collection&iterable<App\Blog\Models\Post>)|Illuminate\Database\Eloquent\Model::tags()`.

No error for count if I use:

```php
$tag = Tag::find(1);
$tag->posts->count()
```

**Comment by Krato** [comment]
Ok. I detected that only happens with model Injected in the constructor.

That fails:

```php
public function __construct(Post $post, Tag $tag)
{
	$this->post = $post;
	$this->tag = $tag;
}

$tag = $this->tag->find(1);
$tag->posts()->count();


$post = $this->post->find(1);
$post->tags()->sync($tags);
```


But this works:

```php
public function __construct()
{
	//
}

$tag = Tag::find(1);
$tag->posts()->count();


$post = Post::find(1);
$post->tags()->sync($tags);
```


Why? Thanks for this amazing package! :)

**Comment by nunomaduro** [comment]
@Krato I think I know why, give me a couple days.

**Comment by canvural** [comment]
This has nothing to do with `count ` or `sync`. Error was because of the return type of a `first` call. This is fixed now in the latest releases.
