### ISSUE TITLE
Call to an undefined method Eloquent\Builder::restore

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1040]
- Larastan Version: 8.6.7
- `--level` used: max
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/1039

### Description
Larastan finds an issue when calling the method `Illuminate\Database\Eloquent\Builder::restore` of models that have the `SoftDeletes` trait.

### Laravel code where the issue was found

```php
<?php

class User extends Model
{
    use SoftDeletes;

    // ...
}

User::query()->onlyTrashed()->restore(); // Call to an undefined method Illuminate\Database\Eloquent\Builder<App\User>::restore().
```

**Comment by szepeviktor** [comment]
```php
User::query()->onlyTrashed()->where('id', $userId)->restore();
```

Maybe Laravel wants to restore 1 user at a time.

**Comment by MatanYadaev** [comment]
@szepeviktor You mentioned the `Model::restore`, I was talking about `Builder::restore`: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L70
