### ISSUE TITLE
There's no option to configure multiple `MorphTo` related models

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1041]
I have a model with a `MorphTo` relation to multiple models.

```php
<?php

class Image extends Model
{
  public function imageable(): MorphTo
  {
    return $this->morphTo();
  }
}

class Post extends Model
{
  public function image(): MorphOne
  {
    return $this->morphOne(Image::class, 'imageable');
  }
}

class User extends Model
{
  public function image(): MorphOne
  {
    return $this->morphOne(Image::class, 'imageable');
  }
}
```

I want to be able to tell PhpStan which models `Image` is "morphing to", currently there's an option to choose only **one** model but not **multiple** models:

```php
<?php

class Image extends Model
{
  /**
   * @return MorphTo<Post, Image>
   */  
  public function imageable(): MorphTo
  {
    return $this->morphTo();
  }
}
```

This is my expected behavior:

```php
<?php

class Image extends Model
{
  /**
   * @return MorphTo<Post | User, Image>
   */  
  public function imageable(): MorphTo
  {
    return $this->morphTo();
  }
}

// Or

class Image extends Model
{
  /**
   * @return MorphTo<Post, Image> | MorphTo<User, Image>
   */  
  public function imageable(): MorphTo
  {
    return $this->morphTo();
  }
}
```

Currently when I run one of these two examples, PHPStan throws this error message: `Internal error: Internal error: Call to undefined method PHPStan\Type\UnionType::getClassName() in file ...`

**Comment by szepeviktor** [comment]
We currently have RelatedModel and ChildModel for MorphTo generics.

https://github.com/nunomaduro/larastan/blob/19098c78b33fc25ba6289d12538729a58cd60678/stubs/MorphTo.stub#L5-L10

**Comment by MatanYadaev** [comment]
@szepeviktor Can we have multiple `TRelatedModel`? Currently it's limited to only one `TRelatedModel`.

**Comment by szepeviktor** [comment]
> Can we have multiple TRelatedModel? Currently it's limited to only one TRelatedModel.

I'm just a janitor without any Laravel knowledge. Maybe @canvural can answer that.

**Comment by canvural** [comment]
Hi,

This is not possible, and I don't think it will be possible to do either.

If you have a proposal about how to solve this you can open a PR 👍🏽

**Comment by MatanYadaev** [comment]
@canvural There's a workaround you suggest using?
