### ISSUE TITLE
Model traits are not recognized in static analysis

### ISSUE THREAD

**Issue by Daespinosag** [nunomaduro/larastan#1046]
- Larastan Version: 1.0
- `--level` used: 5
- Pull request with failing test:

### Description

I have a trait included in the user model that I try to execute once I have a model diucho object; however there is an error in the static analysis.

### Laravel code where the issue was found

Call to an undefined method Illuminate\Database\Eloquent\Model::createToken()

In my model:

```

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens;
```

Al momento de usarlo en una clase: 

`new TokenData(token: $user->createToken('auth-token')->plainTextToken);
`

The error:

`Call to an undefined method Illuminate\Database\Eloquent\Model::createToken().
`
```php

```

**Comment by canvural** [comment]
Hi,

The issue is not about traits. The type of `$user` is  inferred as `Model` and not `User` in the example.

Can you show how the `$user` variable is constructed in your code?

**Comment by Daespinosag** [comment]
Sure, it is the result of a simple query

`$user = User::whereEmail($credentialData->email)->firstOrFail();`

It happens in other scenarios and other models

`Call to an undefined static method Company::join().`

`Call to an undefined method Illuminate\Database\Eloquent\Model::hasVerifiedEmail().  `   

`Call to an undefined method Illuminate\Database\Eloquent\Model::markEmailAsVerified(). `

```
Call to an undefined method                                                                                         
         Illuminate\Database\Eloquent\Collection<Illuminate\Database\Eloquent\Model>|Illuminate\Database\Eloquent\Model::sy  
         ncRoles(). 
```
```
Call to an undefined method                                                                                         
         Illuminate\Database\Eloquent\Collection<Illuminate\Database\Eloquent\Model>|Illuminate\Database\Eloquent\Model::sy  
         ncPermissions()
```

**Comment by canvural** [comment]
I think this related to your other issue. Because of the custom builder. If you follow that guide that I posted on the other issue, it'll be fixed.

**Comment by Daespinosag** [comment]
Thank you !!! it finally worked. We leave this here in case someone else has the same problem.

Lugar de la solución: https://github.com/nunomaduro/larastan/issues/1045
