### ISSUE TITLE
Adding a rule to disallow debug-related code.

### ISSUE THREAD

**Issue by mad-briller** [nunomaduro/larastan#1047]
Leaving a `dd()` in production code can happen to the best of us. However ideally this does not happen, and if our tooling could alert us to this mistake we would likely all be better off.

I was going to attempt to write a phpstan plugin to check for atleast `dd()` and `dump()` to use in my own projects. However i thought i'd ask if Larastan would like a pr for this rule to be implemented? 

If so, is there any other debug-related code you'd consider for the list of things to check for?

Thanks for the great work on Larastan, it is a great extension to an already great tool.

**Comment by canvural** [comment]
Hi,

This kind if stuff is more suited to code style tools. For example PHP_CodeSniffer has a rule (Generic.PHP.ForbiddenFunctions) to forbid the use of functions. I'm sure other tools have similar stuff.

If you are looking for a PHPStan rule, you can check this one: https://github.com/spaze/phpstan-disallowed-calls

Also, thanks for the kind words!

**Comment by mad-briller** [comment]
Ah i was not aware of the phpstan-disallowed-calls extension. Saved me an afternoon of head scratching there, thank you!
