### ISSUE TITLE
EloquentBuilder is missing `whereBetween` and `orWhereBetween` methods

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1048]
- Larastan Version: latest
- `--level` used: max

### Description

EloquentBuilder is missing `whereBetween` and `orWhereBetween` methods.

### Laravel code where the issue was found

```php
<?php

// Call to an undefined method Builder::whereBetween().
$user = User::whereBetween('created_at', [now()->subDay(), now()])->first();
```

**Comment by szepeviktor** [comment]
How about this?

```php
$user = User::query()->whereBetween('created_at', [now()->subDay(), now()])->first();
```

**Comment by canvural** [comment]
Hi,

I can't reproduce this. Are you using custom builder for `User` model? Did you set it up correctly?

**Comment by MatanYadaev** [comment]
Sorry, I had an edge case in my app. Nothing to fix from your end.
