### ISSUE TITLE
Support macros on custom Eloquent builders

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1050]
- Larastan Version: 8.6.7
- `--level` used: max
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/1049/

### Description
Larastan alerts that Carbon macro methods are parent's private methods when using:
1. Laravel's date helper functions
2. `Date` facade
3. `Illuminate\Support\Carbon`

The problem is that `Support\Carbon` assumes that macro methods are private methods of `Carbon\Carbon` (its parent).

### Laravel code where the issue was found

```php
Carbon::macro('foo', static function (): string {
    return 'foo';
});

// Call to private method foo() of parent class Carbon\Carbon.

now()->foo();
\Illuminate\Support\Facades\Date::now()->foo();
\Illuminate\Support\Carbon::now()->foo();
```

BTW, I have the same issue with `EloquentBuilder` macro methods and I use custom builders.

**Comment by canvural** [comment]
Hi,

Carbon has its own PHPStan [extension.](https://github.com/briannesbitt/Carbon/blob/master/extension.neon) Try including this or install `phpstan/extension-installer`, and try again. Maybe it resolves it.

**Comment by MatanYadaev** [comment]
@canvural Cool, thanks for the help, it fixed it. But, the issue still exists with custom Eloquent Builders:

```php
Builder::macro('last', function () {
  /** @var Builder<Model> $this */
  return $this->latest('id')->first();
});
```
```php
class User extends Authenticatable
{
  /**
    * @param \Illuminate\Database\Query\Builder $query
    * @return UserBuilder<User>
    */
  public function newEloquentBuilder($query): UserBuilder
  {
    return new UserBuilder($query);
  }
}
```
```php
// Call to private method last() of parent class Illuminate\Database\Eloquent\Builder<TModelClass of App\Models\User>.
User::last();
```

**Comment by ju5t** [comment]
I had the same issue with Carbon. Didn't notice it before we use the macro a lot in blade views.

Just wanted to say @canvural comment fixed it for me too.

**Comment by joelharkes** [comment]
For those coming here for Carbon issue, you can add the extension this way in your `phpstan.neon` file:

```yaml
includes:
    - ./vendor/nesbot/carbon/extension.neon
```
