### ISSUE TITLE
With SoftDeletes `deleted_at` is a Carbon instance, not a string

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#1051]
Larastan Version: 8.6.7
- `--level` used: max
- Pull request with failing test: https://github.com/MatanYadaev/larastan/pull/2

### Description

Larastan infers that `deleted_at` is a string and not a Carbon.

### Laravel code where the issue was found

```php
class User extends Authenticatable
{
  use SoftDeletes;

   // ...
}
```

```php
// Cannot call method addDay() on string|null.
User::onlyTrashed()->firstOrFail()->deleted_at->addDay();
```

BTW, when you add `$casts = ['deleted_at' => 'datetime'];` the issue is gone - but I believe it's not an ideal solution.

**Comment by szepeviktor** [comment]
> Pull request with failing test:

Thank you for your report.
You do not need to open a PR for your issues.

**Comment by szepeviktor** [comment]
Do you suggest that `onlyTrashed()` prevents `deleted_at` from being null?

**Comment by MatanYadaev** [comment]
@szepeviktor 
> You do not need to open PR-s for your issues.
Sorry, what do you mean?
> Do you suggest that `onlyTrashed()` prevents `deleted_at` from being null?
It is, but it's unrelated to the issue. The issue is that Larastan doesn't cast `deleted_at` to `Carbon` by default. And in my opinion, it should do it. 

Laravel casts `created_at` and `updated_at`  to `Carbon` by default. It does the same thing to `deleted_at` (`SoftDeletes::initializeSoftDeletes`), but for some reason, Larastan doesn't understand it.

**Comment by szepeviktor** [comment]
> I don't have to create a PR with failing tests when I open an issue?

Oh yess!!

**Comment by szepeviktor** [comment]
Maybe here it is
https://github.com/nunomaduro/larastan/blob/7d6e564144b2f9c231d0331d4083905a1b3e872b/src/Properties/SchemaAggregator.php#L372-L378
