### ISSUE TITLE
Modifying collection's shape with combine() seems not supported

### ISSUE THREAD

**Issue by underdpt** [nunomaduro/larastan#1053]
- Larastan Version: 1.0.2
- `--level` used: 8
- Pull request with failing test: none

### Description

Running the code below, I get:

```
Parameter #1 $callback of method Illuminate\Support\Collection<int,string>::mapWithKeys() 
expects callable(string, int): array, 
Closure(stdClass, string): non-empty-array<string, stdClass> given.
```

I think this is because the `combine()` method changes the shape of the collection. I didn't find that method on the stubs, so maybe this is too much magic for larastan.

I tried adding a phpdoc after the combine() method to inform larastan about the new shape, but it's not working, is there any way to inform phpstan about the new shape of the collection?

```php
public function test(): void
{
    $row = [new \stdClass(), new \stdClass()];

    $new = collect(['key1', 'key2'])
        ->combine($row)
        /** @var \Illuminate\Support\Collection<\stdClass, int> $row */
        ->mapWithKeys(fn (\stdClass $value, string $key) => [$key => $value]);
}
```

### Laravel code where the issue was found

```php
public function test(): void
{
    $row = [new \stdClass(), new \stdClass()];

    $new = collect(['key1', 'key2'])
        ->combine($row)
        ->mapWithKeys(fn (\stdClass $value, string $key) => [$key => $value]);
}
```

**Comment by szepeviktor** [comment]
Hallo David! 👋 
Larastan infers closure parameters from the collection. `combine` is not taken into consideration.
https://github.com/nunomaduro/larastan/blob/695d005f56d2fd71876d604e78708ad1acc96781/stubs/Enumerable.stub#L28

```php
    $combined = collect(['key1', 'key2'])->combine($row);
    /** @var \Illuminate\Support\Collection<string, \stdClass> $new */
    $new = $combined->mapWithKeys(fn (\stdClass $value, string $key) => [$key => $value]);
```

How about something like this? I may have had a mistake!

**Comment by underdpt** [comment]
Hello and thanks for your answer!

Will use that as a workaround, better than ignoring the line. It would be good that Larastan could understand `combine` so we could maintain the fluent syntax. Do you think this can be done? I have not enough knowledge but if this is doable, I can put this into my TODO list (no promises, sorry!)

**Comment by szepeviktor** [comment]
> Do you think this can be done?

Definitely. Larastan does it with few dozen methods.

**Comment by canvural** [comment]
Hi,

As of Larastan 2 all the collection related stubs are moved to Laravel core. So please test this with Laravel 9 and Larastan 2, and if the error still happens please open an issue on Laravel repo. Thanks.
