### ISSUE TITLE
union() does not accept Eloquent\Builder

### ISSUE THREAD

**Issue by a-h-abid** [nunomaduro/larastan#1055]
- Larastan Version: 1.0.2
- `--level` used: 5
- Pull request with failing test: none
- Laravel Version: 6.20.41
- PHP Version: 7.4

### Description

I have a query where select emails from both users & admins tables. When I run analyse on that part of code, I get this error below:

```
Parameter #1 $query of method Illuminate\Database\Eloquent\Builder<App\Models\User>::union() 
expects Closure|Illuminate\Database\Query\Builder, 
Illuminate\Database\Eloquent\Builder<App\Models\Admin> given.
 ```

I'm unsure how to resolve this or is it a bug. Or is it because I'm using Laravel v6 ?

Do let know if you need for details.

### Laravel code where the issue was found

```php
$uQuery = User::select('email');
$aQuery = Admin::select('email');
$emails = $uQuery->union($aQuery)->pluck('email')->toArray();
```

**Comment by canvural** [comment]
Hi,

Yeah looks like this is a bug in parameter types. You can try to send a PR to Laravel that adds `Illuminate\Database\Eloquent\Builder` to the `union` method's param type.
