### ISSUE TITLE
Table in migration is not recognized if Schema facade starts specifying the connection

### ISSUE THREAD

**Issue by lsalazarm99** [nunomaduro/larastan#1058]
- Larastan Version: 1.0.2
- `--level` used: 9

### Description
In the migration files, if we need to specify a connection for a specific schema operation, Laravel proposes `Schema::connection('connection')->create('table', ...)` ([reference](https://laravel.com/docs/8.x/migrations#database-connection-table-options)). If this is the case, the table is not being recognized by Larastan.

### Laravel code where the issue was found

```php
Schema::connection('connection')->create('table', ...)
```

**Comment by szepeviktor** [comment]
Hello Leonardo! 👋
Larastan recognizes simple migration.
https://github.com/nunomaduro/larastan/blob/7d6e564144b2f9c231d0331d4083905a1b3e872b/src/Properties/SchemaAggregator.php#L62-L80

**Comment by jamespavett** [comment]
Yea I've just realised I have the same issue. Would be nice feature to have.

**Comment by tyler36** [comment]
Not sure if it's related but I'm getting a ` Access to an undefined property` for 2 models; both of which have the following

```php
    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);

        // Dynamically set default database 'connection' from config
        $this->setConnection(config('client-admin.database'));
        // Dynamically set default database 'table' from config
        $this->setTable(config('client-admin.table.clients'));
    }
```

The project is locked to Laravel 7 due to PHP 7.2 restrictions.

**Comment by szepeviktor** [comment]
Hello @tyler36 !
PHPStan does not recognize dynamic properties. I think having dynamic properties is a bad part of PHP.

**Comment by tyler36** [comment]
@szepeviktor Thanks for the feedback. I have it set this way so I can dynamically change the database during testing.

**Comment by szepeviktor** [comment]
I see! So your class property is not dynamic but the table name is.

**Comment by tyler36** [comment]
@szepeviktor yes. I've replicated an external database locally so I don't hit it during testing.  Would this be considered a bug in how Larastan processes files? Do you want me to open a new issue?

**Comment by szepeviktor** [comment]
> Would this be considered a bug in how Larastan processes files?

Larastan understands only simple migrations.
https://github.com/nunomaduro/larastan/blob/965a451948e3034693be7ca683c28b9db97e9711/tests/Application/database/migrations/2020_01_30_000000_create_users_table.php#L18-L31

**Comment by tyler36** [comment]
> Larastan understands only simple migrations.

I see. So Larastan does not support `Schema::connection($this->connection)` migrations. Thanks for clarifing.

**Comment by jamespavett** [comment]
Could Larastan not just ignore the connection definition when scanning migrations? Just if the underlying migration is valid, the connection property could just be disregarded.

**Comment by szepeviktor** [comment]
Yes it could.
PR-s are welcome!

**Comment by canvural** [comment]
> Could Larastan not just ignore the connection definition when scanning migrations? Just if the underlying migration is valid, the connection property could just be disregarded.

Yes, this issue is just about that. That's why it's open.
