### ISSUE TITLE
🚨 Incompatible Symfony Translation version

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1059]
Latest scheduled CI runs [started to fail](https://github.com/nunomaduro/larastan/runs/4414352457?check_suite_focus=true).

> Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string 
> in /home/runner/work/larastan/larastan/vendor/symfony/translation/TranslatorInterface.php on line 69

When running PHPStan: `Test Laravel from other working directories`

**Comment by canvural** [comment]
This no longer happens.

**Comment by HenkPoley** [comment]
Ah. There used to be a file /path/to/laravel/vendor/symfony/translation/TranslatorInterface.php

It no longer exists in symfony/translation. So if you have a lame deployment, that only unpacks over the existing directory, you get this error.

**Comment by SMTAF** [comment]
> Ah. There used to be a file /path/to/laravel/**vendor/symfony/translation/TranslatorInterface.php**
> 
> It no longer exists in symfony/translation. So if you have a lame deployment, that only unpacks over the existing directory, you get this error.

only rename TranslatorInterface.php to TranslatorInterface_.php and it's working thank you.
