### ISSUE TITLE
Does not support dynamic type

### ISSUE THREAD

**Issue by phh** [nunomaduro/larastan#106]
- Larastan Version: v0.2.4
- `--level` used: default

### Description:

```
Parameter #1 ...$patterns of method Illuminate\Http\Request::is() expects Illuminate\Http\dynamic, string given.
```

I have this helper function:

```php
/**
 * Check if navigation item active.
 *
 * @param  string $path
 * @param  bool   $wildcard
 * @return string
 */
function isNavItemActive($path, $wildcard = false)
{
    if ($wildcard) {
        $path .= '*';
    }

    return request()->is($path) ? 'true' : 'false';
}
```

### Laravel code where the issue was found:

```php
/**
 * Determine if the current request URI matches a pattern.
 *
 * @param  dynamic  $patterns
 * @return bool
 */
public function is(...$patterns)
{
    foreach ($patterns as $pattern) {
        if (Str::is($pattern, $this->decodedPath())) {
            return true;
        }
    }

    return false;
}
```

**Comment by ondrejmirtes** [comment]
BTW: This will be possible to solve in a clean way in PHPStan 0.10.3 with `PHPStan\PhpDoc\TypeNodeResolverExtension`.

**Comment by carusogabriel** [comment]
Laravel is the ONLY PHP basecode that uses `dynamic` instead of `mixed`. IMHO that must be fixed there, not supporting it.

**Comment by hailwood** [comment]
@deleugpn is correct that this is a Laravel issue, rather than Laravel magic...
It's fine though ,it's in the process of being fixed, this was merged 4 days ago :) https://github.com/laravel/framework/pull/26164

**Comment by szepeviktor** [comment]
@phh Could you try with laravel master?

**Comment by phh** [comment]
Have not gotten the error since I posted this issues, so closing.

**Comment by danijelk** [comment]
Sorry to reopen old issue, but since it's related I thought it might be better than to open a new one.

     133    Function cache invoked with 1 parameter, 0 required.
     160    Function cache invoked with 2 parameters, 0 required.

There is a dynamic definition for the cache helper

     * @param  dynamic  key|key,default|data,expiration|null

     * @return mixed|\Illuminate\Cache\CacheManager

Which side would be the best place to fix something liket his?

**Comment by szepeviktor** [comment]
Please consider opening a new issue.

https://github.com/laravel/framework/blob/db794ceea6734cc90286e04a8a2a48e5b4cd4130/src/Illuminate/Foundation/helpers.php#L225-L235
