### ISSUE TITLE
"scopeUnverified" returns Call to an undefined method \HasMany::verified() in Larastan

### ISSUE THREAD

**Issue by ahoiroman** [nunomaduro/larastan#1060]
- Larastan Version: 1.0.2
- `--level` used: 5

### Description

I am working with Larastan; at the moment, I am facing a little problem: Larastan throws out the following error:

```
  137    Call to an undefined method Illuminate\Database\Eloquent\Relations\HasMany::verified().  
```

Alright, so I had a look at it.

I defined a scope like this:

```
 /**
     * @param $query
     *
     * @return mixed
     */
    public function scopeVerified($query): mixed
    {
        return $query->where('verified', 1);
    }
```

This is the relation:

```php

/**
 * @return HasMany
 */
public function images(): HasMany
{
    return $this->hasMany(Image::class);
}
```

### Laravel code where the issue was found

```php
$verified_images = $images->verified()->count();
```

**Comment by canvural** [comment]
Hi,

Your docblock for the `images` method is the problem.

You can update it to `@return HasMany<Image>` or you can remove it, and Larastan can handle it.

**Comment by ahoiroman** [comment]
Hm, this did not help in this case.

Is it important to know that 

```
$verified_images = $images->verified()->count();
```

is being called in a Trait and the scope is defined in the Images-model?

**Comment by canvural** [comment]
How is the `$images` variable initialized?

**Comment by ahoiroman** [comment]
I just got the problem:

The method where `$verified_images = $images->verified()->count();` was called, also got a docblock. As the method received the `$images`-var with a declaration of `HasMany $images` as `@param` in the docblock, I needed to replace it with `@param HasMany<Image> $images`.


Thanks for your help - I would not have figured it out without your hint :-)
