### ISSUE TITLE
Issue using a Custom Cast

### ISSUE THREAD

**Issue by ahoiroman** [nunomaduro/larastan#1063]
- Larastan Version: 1.0.2
- `--level` used: 5

### Description

Maybe this issue would be better off in a discussion, but those are not active here.

To the topic:

I am using https://github.com/mewebstudio/Purifier to make sure that certain user inputs, which are stored in the database, do not contain any unwanted tags (e.g. `<script>`).

To do so, I added the provided `CleanHtmlOutput`-cast to my model's `$casts`-array:

```php
/**
 * @var string[]
 */
protected $casts = [
    'uuid'          => 'string',
    'lastname'      => CleanHtmlOutput::class,
    'firstname'     => CleanHtmlOutput::class,
    'created_at'    => 'datetime',
    'updated_at'    => 'datetime',
];
```

This works fine, but Larastan throws a lot of warnings, as I am using this `CleanHtmlOutput::class` custom cast quite a lot.

Larastan reports:

>  Part $this->name (Mews\Purifier\Casts\CleanHtmlOutput) of encapsed string cannot be cast to string. 

### Laravel code where the issue was found

Larastan refers to a line like this:

```php
/**
 * @return string
 */
public function getFullNameAttribute(): string
{
    return "{$this->firstname} {$this->lastname}";
}
```

**Comment by 18635657419** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by canvural** [comment]
Hi,

There is already a feature request for that: https://github.com/nunomaduro/larastan/issues/890

**Comment by ahoiroman** [comment]
Did not see that, I am very sorry. Glad to see that I'm not just too stupid ;-)
