### ISSUE TITLE
PDOException thrown

### ISSUE THREAD

**Issue by DM-la** [nunomaduro/larastan#1064]
- Larastan Version: 1.0.1
- `--level` used: max

### Description

```
PDOException thrown in /src/Illuminate/Database/Connectors/Connector.php on line 70 
while loading bootstrap file ./vendor/nunomaduro/larastan/bootstrap.php: 
SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: YES)
```

### Laravel code where the issue was found

```php
    DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
```

Issue occurs only when I adding this line to phpstan.neon:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
```

**Comment by szepeviktor** [comment]
Hello @DM-la! 👋 
Thank you for your report.

Larastan boots up Laravel. AFAIK there is no work-around.

**Comment by szepeviktor** [comment]
PLEASE DO NOT READ THIS.

```
if (! defined('__PHPSTAN_RUNNING__')) {
    DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
}
```

This is very dirty.

**Comment by DM-la** [comment]
It's working,  thanks a lot! If somebody knows a better way how to fix it, please let me know.

**Comment by canvural** [comment]
Hi,

As @szepeviktor said Larastan boots your Laravel app. So either you need to run the static analysis in an environment that has correct database config (like `.env.testing`) or you shouldn't put any code that connects to database in service providers.
