### ISSUE TITLE
Make models relationship check work without giving it a type

### ISSUE THREAD

**Issue by crissi** [nunomaduro/larastan#1066]
- Larastan Version: 1.0.2
- `--level` used: 6
- Pull request with failing test: 

### Description

Was playing with this new awesome feature https://github.com/nunomaduro/larastan/pull/985/files:

Can this be done so it works without giving it a type to relationship method?

This works fine:
```
public function users(): HasMany
{
    return $this->hasMany(User::class);
}

```
but if this is given
```
public function users()
{
    return $this->hasMany(User::class);
}

```
It will fail to discover the relationship and give the error: **Relation 'users' is not found in ...**

**Comment by canvural** [comment]
Hi,

No, unfortunately return type is necessary.

**Comment by crissi** [comment]
damn

**Comment by szepeviktor** [comment]
Every coat needs a hanger.

**Comment by canvural** [comment]
If you don't want to add the return type maybe you can try this:

```php
/** @return HasMany<User> */
public function users()
{
    return $this->hasMany(User::class);
}
```
