### ISSUE TITLE
Illuminate\Support\Carbon does not accept Carbon\Carbon with ide-helper

### ISSUE THREAD

**Issue by Sergiobop** [nunomaduro/larastan#1067]
- Larastan Version: #.#.#
- `--level` used: 5
- Pull request with failing test:

### Description
I don't know if i'm doing something wrong or i have a missing configuration, but running larastan on my project with the laravel-ide-helper package makes this error to appear in every single date from my models.

**Comment by szepeviktor** [comment]
Hello @Sergiobop!

Could you please add some sample code of yours?

**Comment by Sergiobop** [comment]
Hey @szepeviktor. I have a fresh laravel + ide-helper + larastan install and some models which looks like this:
```
<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Carbon;

/**
 * App\Models\Test
 *
 * @property int $id
 * @property string $name
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 *
 * @method static \Illuminate\Database\Eloquent\Builder|Zone newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Zone newQuery()
 * @method static Builder|Zone onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Zone query()
 * @method static \Illuminate\Database\Eloquent\Builder|Zone whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Zone whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Zone whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Zone whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Zone whereUpdatedAt($value)
 * @method static Builder|Zone withTrashed()
 * @method static Builder|Zone withoutTrashed()
 *
 * @mixin Eloquent
 */
class Test extends Model
{
    use SoftDeletes;
....
``` 

Running
`./vendor/bin/phpstan analyse `
Makes the error appear.

Bonus:
If i do:
```
$now = CarbonInmutable::now();
$model = new Test();
$model->created_at = $now->addDay();
```

The error transforms to:

`Illuminate\Support\Carbon does not accept Carbon\CarbonInmutable`

**Comment by szepeviktor** [comment]
I see! If you remove all work of ide-helper it'll be okay.

**Comment by Sergiobop** [comment]
What do you mean? I want to use both packages (which are awesome) in my development environment. Maybe the problem is that the ide-helper (and other Laravel internal files) use the Illuminate\Support\Carbon instead of Carbon\Carbon.

I think the Illuminate\Support\Carbon is not necessary now since Carbon is macroable itself, but i don't know for sure

**Comment by szepeviktor** [comment]
> What do you mean?

Remove all comments by ide-helper.

There are many issues regarding ide-helper: https://github.com/nunomaduro/larastan/issues?q=is%3Aissue+sort%3Aupdated-desc+ide-helper+is%3Aclosed

These two packages are not compatible.

**Comment by szepeviktor** [comment]
Try using a Laravel-compatible IDE!

**Comment by Sergiobop** [comment]
I use PhpStorm. If PHPStorm is not Laravel-compatible, let me know 😨

**Comment by szepeviktor** [comment]
Try https://plugins.jetbrains.com/plugin/13441-laravel-idea
It costs one 🍔 each quarter.

**Comment by Sergiobop** [comment]
Ok thank you for your time and your fast responses @szepeviktor 👍

**Comment by simplyandyg** [comment]
I know this issue is closed, but I wanted to add a solution to the thread in case someone else runs into this and like me, they're working at a company and changing the package may be a bit more difficult.

You can still use ide-helper. Instead, you need to make sure the ide-helper config is published (see their github page for instructions) and then add an override to the config file under `type_overrides` for `\Carbon\Carbon => \Carbon\CarbonInterface`
