### ISSUE TITLE
->first()  produces "If condition is always true." when using conditional if

### ISSUE THREAD

**Issue by Sergiobop** [nunomaduro/larastan#1068]
- Larastan Version: 1.0.2
- `--level` used: 5
- Pull request with failing test:

### Description

Using first() like this:
```
$test = DB::table('tests')->where('name', 'Test')->first();

if($test) {
...
}
```
Makes this one appear:
`If condition is always true.`

But that's not true, since it can be null.

**Comment by szepeviktor** [comment]
Try adding `\PHPStan\dumpType($test);' before `if`.

**Comment by Sergiobop** [comment]
That returns:
`Dumped type: App\Models\Test`

But i don't have a Test with 'Test' name in the database. Doing dd($test) returns null.

**Comment by canvural** [comment]
Hi,

The code snippet you shared and the result of your `dumpType` doesn't make sense. Larastan does not infer types from `DB` facade. So the dumped type should actually be `object|null`

Can you post a new snippet or a test case for this?
