### ISSUE TITLE
JSON column casted as object throws undefined property error

### ISSUE THREAD

**Issue by WillyReyno** [nunomaduro/larastan#1069]
- Larastan Version: 1.0.2
- `--level` used: 7

### Description

I have a JSON column `settings` on my users table, containing the following data : 
```json
{
	"api": {
		"expireDate": "2021-12-27 19:19:49"
	},
}
```

`settings` is then casted as object in my User model: 
```php 
    protected $casts = [
        'settings' => 'object',
    ];
```

### Laravel code where the issue was found

```php
$user = User::find(1);
$userExpires = $user->settings->api->expireDate;
```

The following error is thrown by PHPStan/Larastan : 
```
 Access to an undefined property object::$api
```

Thanks for your help

**Comment by szepeviktor** [comment]
Hello @WillyReyno!
This is not official support but my opinion.

Creating structures without a class (arrays, raw objects) makes programming much harder.

**Comment by szepeviktor** [comment]
There are many projects out there putting your JSON data into tamable objects.

**Comment by canvural** [comment]
Hi,

There is really no way to know what properties does an `object` have via static analysis.

If you want to have type safety for your `settings` try to cast to a custom class and have the properties there. Otherwise you can ignore this error.
