### ISSUE TITLE
Suggestion: collection()->each must contain callback returning void

### ISSUE THREAD

**Issue by joelharkes** [nunomaduro/larastan#1070]
- Larastan Version: 1.0.2
- `--level` used: should be disabled by default as it is something that can be used on purpose.
- Pull request with failing test: would like to contribute but might need some direction where to start

### Description

Laravel `each()` methods stops when `false` is returned. this leads to many issues, where iterations are not finished by mistake.

To avoid this issue there could be a rule checking that `bool` return type is never used as callback return type.

### Laravel code where the issue was found

```php
    public function each(callable $callback)
    {
        foreach ($this as $key => $item) {
            if ($callback($item, $key) === false) {
                break;
            }
        }

        return $this;
    }
```

this stops after second item:

```php
collect([1,2,3])
  ->each(fn($item) => $item == 2 ? false : doSomething()); 
```

**Comment by szepeviktor** [comment]
Hello Joël! 👋 
We have https://github.com/nunomaduro/larastan/blob/d2cd3368a758f531feace4c22b087772e570f186/stubs/Collection.stub#L70-L74


Try a normal `function` as callback and `--level max`

**Comment by szepeviktor** [comment]
...I mean `bool` is a possible return type to stop iteration.

**Comment by joelharkes** [comment]
@szepeviktor  yes i know, this is actually very counterintuitive (actually comes from jQuery but no one else uses it) and leads to many errors.

**Comment by szepeviktor** [comment]
Maybe you could override our built-in stubs in your PHPStan config!

**Comment by joelharkes** [comment]
@szepeviktor  thanks for the input :)

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by JeffreyDavidson** [comment]
@szepeviktor I'm still thinking this is an issue on version `dev-master`. 

When I run `./vendor/bin/phpstan analyse --memory-limit=2G app/Repositories` I returns 

```
Parameter #1 $callback of method Illuminate\Support\Collection<(int|string),Illuminate\Database\Eloquent\Model>::each() expects  
         callable(Illuminate\Database\Eloquent\Model, (int|string)): bool|void, Closure(App\Models\TeamMember): void given.
```

```
$manager->currentTeamMembers->each(function (TeamMember $member) use ($manager) {
    $manager->currentTeamMembers()->updateExistingPivot($membre->id, [
        'left_at' => now()->toDateTimeString(),
    ]);
});
```

**Comment by szepeviktor** [comment]
I think you're using an older version of Larastan.

https://github.com/nunomaduro/larastan/blob/08c4f4f4c714b4adaa4fa2bc944db88d2d20471e/stubs/Collection.stub#L70-L74

**Comment by JeffreyDavidson** [comment]
@szepeviktor That is the exact same method signature I have in that file. 

```
/**
     * @param callable(TValue, TKey): (void|bool) $callable
     * @return static<TValue>
     */
    public function each($callable) {}
```

**Comment by szepeviktor** [comment]
Maybe you override that https://github.com/nunomaduro/larastan/issues/1070#issuecomment-1002649833
Or PHPStan cached something.
I may be wrong too!

**Comment by JeffreyDavidson** [comment]
I added that override as suggested, then ran the `vendor/bin/phpstan clear-result-cache` command, then ran the `./vendor/bin/phpstan analyse` and then it reported. 

```
Method Illuminate\Support\Collection::each() has parameter $callable with no type specified.
```

**Comment by szepeviktor** [comment]
Try adding it: `->each(function (TeamMember $member) use ($manager) : void {`
