### ISSUE TITLE
Detect missing or not correctly named route parameters

### ISSUE THREAD

**Issue by williamdes** [nunomaduro/larastan#1076]
- Larastan Version: 8.77
- `--level` used: max

### Description

```
Missing required parameter for [Route: my_route_named] [URI: foo/{param1}/download-report/{param2}] 
```

### Laravel code where the issue was found

```php
route('my_route_named',
   ['param1' => $this->resource->getKey(), 'paramMisnamed' => $this->resource->getOtherId()]
);
```

**Comment by canvural** [comment]
Hi,

This is not really doable with static analysis.

**Comment by szepeviktor** [comment]
@williamdes There is something for your: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/Commands/RouteCheckCommand.php
