### ISSUE TITLE
Squashed migrations

### ISSUE THREAD

**Issue by sdapkus** [nunomaduro/larastan#1080]
- Larastan Version: 1.3.3
- `--level` used: 5

### Description
I've read documentation and some forum posts, and I saw that Larastan looks thru migration files and understands database structure. In my project some of migrations are [squashed](https://laravel.com/docs/8.x/migrations#squashing-migrations) and it looks like, that Larastan is unable to figure out structure from this. I couldn't find anything about squashed migrations in this repo or in google, so I'm opening issue / question about this.

I'm not using `barryvdh/laravel-ide-helper` instead I'm using Laravel idea plugin for PhpStorm. My models do not have any PhpDocs at them and I'm not keen of adding them there.

```
 ------ --------------------------------------------------------------------- 
  Line   Http/Controllers/UserController.php                                  
 ------ --------------------------------------------------------------------- 
  26     Access to an undefined property App\Models\User::$name.        
```

**Comment by szepeviktor** [comment]
Hello Simonas!

Yes, you're right. Larastan understands simple migrations only.
https://github.com/nunomaduro/larastan/tree/master/tests/Application/database/migrations

**Comment by szepeviktor** [comment]
I know it is additional work but you can add fake migrations temporarily.

**Comment by sdapkus** [comment]
Thinking, short term solution, might be not using built in squashing mechanism, but instead use something like [this](https://laravel-news.com/migration-generator-for-laravel). Never used this package, but looks like if I would not be squashing to schema, but instead squash to normal migrations, then Larastan would get structure.

Maybe will try this solution later this month, but still a bit sad, that built-in squashing does not work 😕

**Comment by sdapkus** [comment]
Today tried package, that I mentioned in a last comment. I have now mixed feelings about it.

In one way it is possible to use package, but it is really hard (especially on large DB). You get new migration class per table, so it `atrisan migrate` will try to build your database in production from scratch! It is possible to change names, in order to skip these new migrations. It is possible to make it work, but it's just not one command thing 😕

I haven't seen, but maybe it is possible for Larastan to provide custom folder for migrations? Then it might be possible to squash main migrations for all environments, but create migrations from existing database just for Larastan?

**Comment by canvural** [comment]
@sdapkus Yes it is possible to provide path for database migrations. See here: https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md

**Comment by sdapkus** [comment]
Oh, nice! Looks like it worked, at least for now. That package by default created db schema under `tests/database/migrations` so all those migrations are ignored in prod/dev environments. So I just added these lines to `phpstan.neon`:

```yaml
  databaseMigrationsPath:
    - tests/database/migrations
    - database/migrations
```

Not fully sure how this will work later, when I add some new real migrations, fingers crossed that this will work 🤞

**Comment by haringsrob** [comment]
I know not everything is supported, but could it be possible to do an SQLite migration then read data from there?

**Comment by canvural** [comment]
If anyone is interested in this feature, you can try https://github.com/nunomaduro/larastan/tree/feat/schema-parser branch now!

By default it looks at `database/schema` folder for the database dumps. But you can configure it with `squashedMigrationsPath` configuration option.

It'd be great if you can and give some feedback if there are any issues.

@haringsrob I don't understand your question. What exactly do you mean by `do a SQLite migration`?

**Comment by haringsrob** [comment]
@canvural I was thinking to run the application migrations using sqlite, then reading the tables/columns from there instead of parsing migrations themself.

**Comment by canvural** [comment]
@mreduar No. We don't plan to add new features to version 1 anymore. Apart from critical bug fixes. I would suggest to upgrade to Laravel 9 and Larastan 2.

**Comment by mreduar** [comment]
For now I can't upgrade to Laravel 9, I have a critical module that is [not compatible with V9 yet](https://github.com/archtechx/tenancy/pull/802). But they are in the final stages of verification, hopefully soon. Thanks @canvural
