### ISSUE TITLE
Property $fillable & $guarded is not covariant with PHPDoc type array<string>

### ISSUE THREAD

**Issue by rognales** [nunomaduro/larastan#1083]
- Larastan Version: 1.0.2
- `--level` used: 5
- Pull request with failing test: none

### Description

Standard Laravel property is throwing errors once i migrated to PHPStan 1.*

### Laravel code where the issue was found

There's two locations:-

1.  ````Exceptions\Handler.php```` 

```ssh
 Line   Exceptions\Handler.php
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  15     PHPDoc type array of property App\Exceptions\Handler::$dontReport is not covariant with PHPDoc type array<string> of overridden property Illuminate\Foundation\Exceptions\Handler::$dontReport.
         💡 You can fix 3rd party PHPDoc types with stub files:
            https://phpstan.org/user-guide/stub-files
  24     PHPDoc type array of property App\Exceptions\Handler::$dontFlash is not covariant with PHPDoc type array<string> of overridden property Illuminate\Foundation\Exceptions\Handler::$dontFlash.
         💡 You can fix 3rd party PHPDoc types with stub files:
            https://phpstan.org/user-guide/stub-files
```
2.  Any Eloquent models with ````$fillable```` or ````$guarded````

```ssh
 17     PHPDoc type array of property App\Models\Activation::$fillable is not covariant with PHPDoc type array<string> of overridden property Illuminate\Database\Eloquent\Model::$fillable.
         💡 You can fix 3rd party PHPDoc types with stub files:
            https://phpstan.org/user-guide/stub-files
```

**Comment by szepeviktor** [comment]
Thank you for your report @rognales! 👋 

What is Your PHP and Laravel version?

**Comment by szepeviktor** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/Handler.php#L57
versus
https://github.com/laravel/laravel/blob/8.x/app/Exceptions/Handler.php#L13

**Comment by canvural** [comment]
Hi,

You need to have same PHPDoc as Laravel has. So you need to change for example `$dontReport` PHPDoc to `string[]`

Also, you can just delete it, and PHPStan will use the type from Laravel.

**Comment by szepeviktor** [comment]
You can also a send a PR to Laravel to synchronize them.

**Comment by rognales** [comment]
My PHP is 7.4, Laravel on v8.78.1

You're a right. Referring to [Laravel source](https://github.com/laravel/framework/blob/55ea49b4f49269b3ea78415f106b308ef8d7ce71/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L12), they typehinted as ```String[]```. However [Docs](https://laravel.com/docs/8.x/eloquent#mass-assignment-json-columns) type-hinted as ````array````

I just need to update all references at my Models

**Comment by rognales** [comment]
As for ```` Exceptions\Handler.php````, i just need to pull latest version from ````laravel/laravel````. I believe they started type-hinted everywhere.

**Comment by Estigy** [comment]
There still is a difference between the actual Laravel code for `$fillable` and the larastan stub:

Laravel 13 (and also former versions 12, 11, and 10) defines `$fillable` as `@var array<int, string>` while the larastan stub wants to see `@var list<string>`.

It would be really nice if the larastan stub could reflect the actual Laravel code. Is there a good reason for larastan to use its own definitions that differ from the Laravel source code?

(Please pardon my ignorance, I really don't know. I'm using larastan for the first time and I just want to know why it criticises those property definitions when they have been coded to the best of my knowledge. I override a property with the very same definition of the property it was inherited from, and now this is wrong for some reason I don't understand.)
