### ISSUE TITLE
False positive: collect()->isNotEmpty() - If condition is always false

### ISSUE THREAD

**Issue by Jellyfrog** [nunomaduro/larastan#1092]
- Larastan Version: 1.0.2
- `--level` used: 6
- Pull request with failing test:

### Description
The following code produces `If condition is always false.`, which is not true :)
It seems it's the "return" part that confuses it

### Laravel code where the issue was found

```php
$c = collect();

if ($c->isNotEmpty()) {
    return $c;
}

$c->push(1);

// \PHPStan\dumpType($c) = Dumped type: Illuminate\Support\Collection
if ($c->isNotEmpty()) { // If condition is always false.
    return $c;
}
```

**Comment by szepeviktor** [comment]
Hello @Jellyfrog! 👋 
AFAIK Larastan does not track the contents of a collection.

**Comment by szepeviktor** [comment]
The first `if` makes it sure for PHPStan that `$c->isNotEmpty()` is not true afterwards.
So in the second `if` it is false for sure: thus not linked to the push.

**Comment by szepeviktor** [comment]
One solution can be to flag `isNotEmpty` method in our stubs are _impure function_.

**Comment by Jellyfrog** [comment]
Ah, I guessed then!

Adding this;
```
    /**
     * Determine if the collection is not empty.
     * @phpstan-impure
     * @return bool
     */
    public function isNotEmpty() {}
```
Solves the problem, should I submit a PR?

**Comment by canvural** [comment]
Hi,

Yes as @szepeviktor suggested using the impure annotation is the way to go. But we are close to releasing Larastan 2.0 and we will not maintain any collection stubs here, since they all migrated to Laravel core. So I think you can go ahead and try to send PR to Laravel directly. Thanks.
