### ISSUE TITLE
Eloquent "When" call returning mixed

### ISSUE THREAD

**Issue by liamh101** [nunomaduro/larastan#1099]
- Larastan Version: 1.0.2
- `--level` used: 9

### Description

It might not be a PHPStan issue and more a Laravel qwerk. When using Eloquent, there's a `when` function that can make life a lot easier by adding your business logic conditionals into your Elqoquent logic itself through a callable instead of abstracting it into an additional `if` statement. 

However, this function can return mixed. This means you can't join this function call into another Eloquent call without PHPStan throwing a warning. I don't really want to add these warnings to my ignore list. Is there a solution to this without either adding to the ignore list or doing an additional check after the `when` call? 

### Laravel code where the issue was found

```php
Model::with('additional')->when(
	$this->logicCheck(),
	static function (Query $q) {
		$q->where('rating', '=', 6)->orderBy('name');
```

If equivalent

```php
$query = Model::with('additional');

if ($this->logicCheck()) {
     $query ->where('rating', '=', 6);
}

$query->orderBy('name');
```

**Comment by szepeviktor** [comment]
> I don't really want to add these warnings to my ignore list.

Very well done, Liam! 😍

**Comment by canvural** [comment]
Hi,

There is already an issue for this. https://github.com/nunomaduro/larastan/issues/915

Right now we don't have a solution for this. Probably it'll need a separate extension.
