### ISSUE TITLE
model property error inside Middleware

### ISSUE THREAD

**Issue by vishytk** [nunomaduro/larastan#1102]
- Larastan Version: 1.0.3
- `--level`: 5

### Description
Working on a package and following error throws when I run phpstan analyser

```
22     Property 'username' does not exist in Vendor\Package\Models\User model.  
24     Access to an undefined property Vendor\Package\Models\Role::$slug.       
```

### Laravel code where the issue was found

```php
namespace Vendor\Package\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Vendor\Package\Models\User;
use Symfony\Component\HttpFoundation\Response;

class ManagerMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param Request $request
     * @param Closure $next
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next): mixed
    {
        $user = User::where('username', $request->user()->username)->first();  // line 22

        if ($user->role->slug !== 'manager') {    // line 24
```

`phpstan.neon.config`

```neon
includes:
    - phpstan-baseline.neon

parameters:
    level: 5
    paths:
        - src
        - config
        - database
    tmpDir: build/phpstan
    checkOctaneCompatibility: true
    checkModelProperties: true
    checkMissingIterableValueType: false
```

**Comment by szepeviktor** [comment]
@vishytk Thank you for your report.
Larastan read model properties from migrations.
Do you have that in place for `User` and `Role` tables?

**Comment by vishytk** [comment]
Hmm... in my application, the ``User`` and ``Role`` migrations belongs to a different package and are loaded from tests/TestCase.php

**Comment by szepeviktor** [comment]
If you have it in `database/migrations/` Larastan will read it.
https://github.com/nunomaduro/larastan/blob/master/tests/Application/database/migrations/2020_03_25_000000_create_roles_table.php#L20

**Comment by vishytk** [comment]
Oh... like I mentioned, the migrations my case belongs to a different package. 

I guess, I can simply ignore the error.

**Comment by szepeviktor** [comment]
> I guess, I can simply ignore the error.

If this is a Composer package for Laravel it should care about its data structures.
Please add migration here or temporarily copy migrations to aid static analysis.

**Comment by vishytk** [comment]
I have copied the migrations for now.

**Comment by vishytk** [comment]
thanks
