### ISSUE TITLE
What do we need to run test on Lumen?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1105]
Was removed in https://github.com/nunomaduro/larastan/commit/067d1e040b4067bb85fc1732a652fd48ac8db2ef

https://github.com/laravel/lumen/tags

Maybe dev-master if Laravel 9 compatible...

**Comment by nunomaduro** [comment]
@szepeviktor I've removed lumen from the script, because Lumen (for Laravel 9 components) only starts its development a week after Laravel 9's stable release.

**Comment by szepeviktor** [comment]
By closing this we may forget about Lumen compatibility.
