### ISSUE TITLE
`route()` on Request not recognized

### ISSUE THREAD

**Issue by fragkp** [nunomaduro/larastan#1112]
- Larastan Version: 1.0.3
- `--level` used: 6
- Pull request with failing test: /

### Description

I was wondering how do you handle that case the best. I know, you could always check with `instanceof` (https://phpstan.org/writing-php-code/narrowing-types), but it blows the could heavily up. Have you any tips?

![Unbenannt](https://user-images.githubusercontent.com/6986565/152782150-ef208286-11ab-412b-889c-baf859a6f967.jpg)

**Comment by szepeviktor** [comment]
Hello @fragkp !

`route` method may return these: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Request.php#L558

**Comment by fragkp** [comment]
Hey @szepeviktor!

So, Larastan/PHPstan can not handle that case and I need always check the result of `route()` to fix the type problem?

**Comment by szepeviktor** [comment]
What do you mean by _that case_? What makes you sure the return value is more narrow than `\Illuminate\Routing\Route|object|string|null`?

**Comment by fragkp** [comment]
When no parameters are given, then always the route object is returned (or null).
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Request.php#L564

**Comment by szepeviktor** [comment]
I think Larastan has that for `request()->route()`

**Comment by canvural** [comment]
Hi,

I think it's possible to write an extension for this. You can read more about it here: https://phpstan.org/developing-extensions/dynamic-return-type-extensions

And here is an example extension for `$request->file()`: https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/RequestExtension.php It'd be similar to this.

Feel free to send a PR 👍🏽

**Comment by fragkp** [comment]
@szepeviktor Will test that out, thx!

@canvural Cool, didn't know that. Later I will create a merge request 🚀
