### ISSUE TITLE
Multiple include files error

### ISSUE THREAD

**Issue by rcerljenko** [nunomaduro/larastan#1114]
- Larastan Version: 2.0.0
- `--level` used: 6
- Pull request with failing test:

### Description

Hi guys,

Anybody getting this error after upgrading to v2 ?:

```sh
This file is included multiple times:
- <my-project-path>\vendor\nunomaduro\larastan\extension.neon

It can lead to unexpected results. If you're using phpstan/extension-installer, make sure you have removed corresponding neon files from your project config file.
```

**Comment by lukasleitsch** [comment]
Were you asked to install the `"phpstan/extension-installer`?

```
Do you trust "phpstan/extension-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

After accepting this question I'm also getting this error. 

I guess we have two ways. Remove `phpstan/extension-installer` in your `composer.json` or remove the including of `./vendor/nunomaduro/larastan/extension.neon` in your config file.

After installing `phpstan/extension-installer` as composer plugin PHPStan loads the larastan config automatically. https://phpstan.org/user-guide/extension-library

**Comment by rcerljenko** [comment]
Hi @lukasleitsch . I don't have that package in my composer.json. Should I have it? I just flipped the version from v1 to v2 as I'm currently porting my project to Laravel 9.

**Comment by lukasleitsch** [comment]
Good question. I have `phpstan/phpstan?  in my `composer.json`. But I don't know if this is necessary. I added it to update phpstan independent of larastan.

**Comment by szepeviktor** [comment]
It is very simple to solve: just comment out the reference in your config file and see static analysis results.

**Comment by rcerljenko** [comment]
yes that's correct.. should be stated also in the docs tho..
