### ISSUE TITLE
Unable to resolve template types when calling function `collect` without parameters

### ISSUE THREAD

**Issue by rcerljenko** [nunomaduro/larastan#1115]
- Larastan Version: 2.0.0
- `--level` used: 6
- Pull request with failing test:

### Description
Calling `collect()` complains for return type:
```
Unable to resolve the template type TKey in call to function collect
Unable to resolve the template type TValue in call to function collect
```

### Laravel code where the issue was found

```php
$value = collect();
```

**Comment by szepeviktor** [comment]
Hello @rcerljenko !
Please use generics in your source code.
https://phpstan.org/blog/generics-in-php-using-phpdocs

**Comment by rcerljenko** [comment]
@szepeviktor can you explain how exactly? I just wan't an empty collection object here

**Comment by szepeviktor** [comment]
```php
/* Collection<YourItemType> *=
$value = collect();
```

**Comment by markdwhite** [comment]
Should that be as it is or with @var as I still cannot avoid the same error message, even with all-encompassing key and value types:

/** @var \Illuminate\Support\Collection<int|string, mixed> */
/** \Illuminate\Support\Collection<int|string, mixed> */
/** @var \Illuminate\Support\Collection<int, mixed> */
/** \Illuminate\Support\Collection<int, mixed> */
/** Collection<int|string, mixed> */
/** Collection<int, mixed> */

So can you give one example that works that we can extrapolate from?

**Comment by mad-briller** [comment]
The issue lies here that the first argument to the `collect()` method is inspected to determine the key type and value type, adding a comment above the `collect()` method will not solve it as the issue lies within the scope of the collect() method

one possible workaround is to define the types on an empty array and pass that:

```
/** @var array<string, string> $array */
$array = [];

$collection = collect($array);
```
This allows phpstan to determine the TKey and TValue values that are intended for the collection.

i don't think template types can have "default" values so to speak, so it may require larastan adding a plugin to inform phpstan that it should be `<int|string, mixed>` when there is no first arg?

**Comment by eleftrik** [comment]
> looked into it a little further and the issue is with the `collect()` method specifically.
> 
> [...]
> 
> therefor a nicer workaround is to avoid the `collect()` method and call `new Collection()` directly

Thank you!

**Comment by canvural** [comment]
Looks like there is nothing we can do about it in Larastan. Using `new Collection` is a valid solution.

If you want, you can either create an issue about this in Laravel core or PHPStan.

**Comment by kobeyy** [comment]
Using `Collection::empty()` also resolves this.

**Comment by antonioribeiro** [comment]
Because `new Collection($mixed)` will also not work, because you are supposed to pass an array of mixed, and also when you are trying to chain things right away on your collections the code becomes a bit harder to look at:

```php
(new Collection([$mixed]))->map(fn($value) => $value->first());
```

I just wrote a helper that fixes it for me:

```php
<?php declare(strict_types=1);

namespace App\Support;

use Illuminate\Support\Collection;

class Helpers
{
    public static function collect(mixed $var = []): Collection
    {
        if ($var instanceof Collection) {
            return $var;
        }

        if (is_array($var)) {
            return collect($var);
        }

        if (is_null($var)) {
            return collect();
        }

        return collect([$var]);
    }
}
```

**Comment by szepeviktor** [comment]
In a normal world it should be `collect(array|Collection $var = []): Collection`,
any other type should cause a fatal error.

**Comment by antonioribeiro** [comment]
@szepeviktor , Laravel's `collect()` method supports mixed, you can pass a string or an object and it makes a Collection from it, if we do what you are saying we cannot use this functionality anymore. Looks like we cannot really live on a normal world 😆
