### ISSUE TITLE
symfony/console and composer/composer dependancy conflict on Larastan 2.0.0

### ISSUE THREAD

**Issue by lasselehtinen** [nunomaduro/larastan#1117]
- Larastan Version: 2.0.0

### Description

When trying to install 2.0.0 with `composer require nunomaduro/larastan:^2.0` you get the following error. The issue is with illuminate packages requiring symfony/console ^6.0 where as [composer is still limited to ^5.0](https://github.com/composer/composer/blob/2.2.6/composer.json#L35). Any way around this?

```
composer/composer[2.2.4, ..., 2.2.6] require symfony/console ^2.8.52 || ^3.4.35 || ^4.4 || ^5.0 -> satisfiable by symfony/console[v2.8.52, v3.4.35, ..., v3.4.47, v4.4.0, ..., v4.4.37, v5.0.0, ..., v5.4.3].
    - You can only install one version of a package, so only one of these can be installed: symfony/console[v5.3.0, ..., v5.4.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3].
    - illuminate/database v9.0.0 requires symfony/console ^6.0 -> satisfiable by symfony/console[v6.0.0, v6.0.1, v6.0.2, v6.0.3].
```

**Comment by szepeviktor** [comment]
Hello Lasse!
I think this is a Laravel versus Composer problem.
What do you think?

**Comment by canvural** [comment]
Hi,

Yes I saw similar issue on Twitter. Composer 2.3 will support Symfony 6 but I don't think there is release date yet.

Maybe you can try to use dev version of Composer as a workaround. 

Anyway, we only need Composer for the `ClassMapGenerator` So we can do something like [this,](https://github.com/barryvdh/laravel-ide-helper/commit/3b03e4055daee6736de0cab801a8be1a3586a9b6) until Composer [separates](https://github.com/composer/composer/discussions/10527) it to another package.

Would be great if you can send a PR!

**Comment by szepeviktor** [comment]
I see!
In our CI:

> Locking composer/composer (dev-main ae68ada)

and https://github.com/composer/composer/blob/ae68ada127afc705111f3269f14abe468e152e41/composer.json#L35-L38

**Comment by lasselehtinen** [comment]
Yes indeed, you need to allow the dev version of composer by adding the `"minimum-stability": "dev"` in your composer.json. Then it works just fine.
