### ISSUE TITLE
Callable of generic collection always and only expects int

### ISSUE THREAD

**Issue by dennisprudlo** [nunomaduro/larastan#1121]
- Larastan Version: 2.0.1
- `--level` used: 7
- Pull request with failing test:

### Description

I am not sure if I am doing something wrong here so I don't really know if this is a larastan issue, but I couldn't find a discussion section, so here we go: Since the Laravel 9 upgrade I get a lot of larastan errors where I apparently pass the wrong parameters to closures on collection functions.

### First example
This example case is about a class to format numbers. There is a `format(array $attributes = []) : string` function that will eventually generate the formatted string and you can add `NumberFormatter`-attributes as options. This `$attributes`-array has the type `array<int, mixed>` because the NumberFormatter constants are integers and the value can be different things, therefore `mixed`. A simple call would look like this:
```php
number(12)->format([
    NumberFormatter::MIN_FRACTION_DIGITS => 2,
    NumberFormatter::MAX_FRACTION_DIGITS => 2
])

// 12.00
```

This is the actual format function
```php
/**
 * Formats the number to a readable text
 *
 * @param array<int, mixed> $attributes Additional attributes to append to the number formatter
 * @return string
 */
public function format (array $attributes = []) : string {
    $formatter  = new NumberFormatter($this->locale(), NumberFormatter::DECIMAL);

    collect($attributes)->each(fn (mixed $value, int $attribute) => $formatter->setAttribute($attribute, $value));

    return (string) $formatter->format($this->get());
}
```

And I get the following error:
```
Parameter #1 $callback of method Illuminate\Support\Collection<int,mixed>::each() expects 
  callable(int): mixed,
  Closure(mixed, int): bool given.
```

The collection figures out the generics correctly (`Collection<int,mixed>::each()`), however, why does the each-function expects a callable with the type `int`?

### Second example
I get similar errors with a handful of collection functions that iterate over the items using a closure:
```php
// Parameter #1 $callback of method Illuminate\Support\Collection<int,App\Models\Activity>::each() expects callable(int): mixed, Closure(App\Models\Activity): void given.

$user->activities()->with('something')->get()->each(function (Activity $activity) {
   // ...
});
```

### Laravel code where the issue was found

This is the each function in `\Illuminate\Support\Traits\EnumeratesValues` which expects the $callback to have the type `callable(TValue)`. Shouldn't this be something like `callable(TValue, TKey)` as you can pass the key as the second parameter? Still TValue is specified as the first parameter and the collection knows TValue is \App\Models\Activity as seen in the error message of the second example (`Collection<int,App\Models\Activity>`) but then expects `callable(int): mixed` where the type is defined as `callable(TValue): mixed`?
```php
/**
 * Execute a callback over each item.
 *
 * @param  callable(TValue): mixed  $callback
 * @return $this
 */
public function each(callable $callback)
{
    foreach ($this as $key => $item) {
        if ($callback($item, $key) === false) {
            break;
        }
    }

    return $this;
}
```

I am sure I am missing something here but I really can't figure it out :D

**Comment by szepeviktor** [comment]
Hello Dennis! 👋 

I do not know what is going on.

> This is the each function in `\Illuminate\Support\Traits\EnumeratesValues`

Laravel 9 does not have that.
https://github.com/laravel/framework/tree/v9.0.1/src/Illuminate/Support/Traits

**Comment by dennisprudlo** [comment]
@szepeviktor Yep laravel 9 with larastan 2. The namespace is off in this file. It actually is in here:
https://github.com/laravel/framework/tree/v9.0.1/src/Illuminate/Collections/Traits

**Comment by szepeviktor** [comment]
`each` was recently fixed https://github.com/laravel/framework/commit/23a2675cdf35c7def5a7c6f78f02baebd7473a53

**Comment by dennisprudlo** [comment]
@szepeviktor Ah nice, yeah that fixed it :D

One more thing: What exactly is the reason, that the "belongs to" relationship requires a TChildModel type which is the type of the class the relationship is defined in, while other relationship types only require the TRelatedModel? Just out of curiosity.

**Comment by szepeviktor** [comment]
> What exactly is the reason, that the "belongs to" relationship requires a TChildModel type

For a human it is so simple.
It is much easier to write it in PHPDoc block than develop an extension for that.
Being explicit is better.

**Comment by dennisprudlo** [comment]
@szepeviktor Yes I'm all for explicit typing, but why doesn't has many have a TChildModel?

**Comment by canvural** [comment]
@dennisprudlo Because only BelongsTo relations have child model. See: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L23
