### ISSUE TITLE
Access to an undefined property on adding dynamic value to Model inside array

### ISSUE THREAD

**Issue by bernardwiesner** [nunomaduro/larastan#1122]
- Larastan Version: 1.0.3
- `--level` used: 3

### Description
When adding a dynamic value to a Model inside an array, `Access to an undefined property` error happens. However if I add a dynamic value to a Model outside of an array the error does not happen. (`foo` does not exist in DB, its just added dynamically on runtime.)

### Laravel code where the issue was found

```php
// Error occurs
$users = User::all();
$users[0]->foo = '123';

// No error
$user = User::first();
$user->foo = '123';
```

**Comment by szepeviktor** [comment]
Hello Bernard!

> `$user[0]->foo = '123';`

Could `$user` be an empty array?

**Comment by bernardwiesner** [comment]
Sorry I fixed a typo above.
$user => $users

And no, it's not an empty array, actual error happens inside foreach loop, if I try to set a non existing column on the model.

```php

foreach($users as $i => $user) {
   $users[$i]->foo = 'bar'; // error
   $user->foo = 'bar';  // no error
}
```

**Comment by szepeviktor** [comment]
PHPStan is a strict tool. It is not advised _to add aliens to your family_.

I think there will be a solution.

**Comment by bernardwiesner** [comment]
I noticed this error also happens on $user->foo, not only inside array, my bad.

Either ignore these type of errors, or add them on the model as a @property
