### ISSUE TITLE
State method in a factory is not compatible with declaration

### ISSUE THREAD

**Issue by lukasleitsch** [nunomaduro/larastan#1125]
- Larastan Version: v2.0.1
- `--level` used: 5

### Description

After install Larastan in a fresh Laravel 9 and add the `database/factories` folder to the `phpstan.neon.dist` file larastan throws following error:

```php
 ------ ----------------------------------------------------------------------------------------------------------------
  Line   database/factories/UserFactory.php
 ------ ----------------------------------------------------------------------------------------------------------------
  36     Parameter #1 $state of method Illuminate\Database\Eloquent\Factories\Factory<App\Models\User>::state() expects
         array<string, mixed>|(callable(): array<string, mixed>), Closure(array): array{email_verified_at: null} given.
 ------ ----------------------------------------------------------------------------------------------------------------
```

What's the best way to fix this issue? I hope excluding these files or ignore this error are not the only way.

### Laravel code where the issue was found

```php
// database/factories/UserFactory.php

/**
 * Indicate that the model's email address should be unverified.
 *
 * @return \Illuminate\Database\Eloquent\Factories\Factory
 */
public function unverified()
{
    return $this->state(function (array $attributes) {
        return [
            'email_verified_at' => null,
        ];
    });
}
```

**Comment by szepeviktor** [comment]
Hello Lukas!
I've just met with the very same problem.
https://github.com/szepeviktor/larastan-issue/commit/89c9992bc4505b7150d6407cbad91f76b827f9bc#diff-0db00302e9c3c5ad4fd47629fe517d343a414c5667b897b5ae2caa6dc2e37692

**Comment by canvural** [comment]
Hi,

This is fixed in Laravel: https://github.com/laravel/framework/pull/40902

**Comment by lukasleitsch** [comment]
Awesome. Thanks.
