### ISSUE TITLE
Return correct types for `Enumerable` methods like `min()` and `max()` when a key is supplied

### ISSUE THREAD

**Issue by totov** [nunomaduro/larastan#1127]
- Larastan Version: dev-master
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/1128

### Description

When using `min()` and `max()` (and maybe other `Enumerable` methods) only the `TValue` is returned, even when a key or callback is provided as a parameter.

When no parameter is provided, I think this should be `TValue|null`, and when a parameter is provided, it should be `float|int|null`.

Because the `Collection` class inherits from `Enumerable`, this causes collection methods to suffer this problem. 

### Laravel code where the issue was found

```php
// should return int|null
// actually returns int
$result = collect([1, 2, 3, 4, 5])->max();

// should return float|int|null
// actually returns non-empty-array<string, int>
$result = collect([['id' => 1], ['id' => 2], ['id' => 3]])->max('id');

// should return float|int|null
// actually returns non-empty-array<string, int>
$result = collect([['id' => 1], ['id' => 2], ['id' => 3]])->max(function($object) { return $object['id']; });

```

This is because of the docblocks on the `Illuminate\Support\Enumerable` class in Laravel:

```php
    /**
     * Get the max value of a given key.
     *
     * @param  (callable(TValue):mixed)|string|null  $callback
     * @return TValue
     */
    public function max($callback = null);

```

Is there something we can do in Larastan to overwrite this (i.e. the `Enumerable.stub` file) or does this need to be done in Laravel? If someone can give me some pointers then I'd be happy to try and fix this in the PR I've submitted to show this issue.

**Comment by szepeviktor** [comment]
Hello Stephen!

```php
// should return int|null
// actually returns int
$result = collect([1, 2, 3, 4, 5])->max();
```

Which is said by PHPStan? What is the error message?

**Comment by szepeviktor** [comment]
I see. What is the downside of PHPStan saying `int`?

**Comment by canvural** [comment]
Hi,

Yes this should be fixed in Laravel. All the Collection types are now moved to the core.

And I agree, the return type can be `TValue|null` So please send a PR to Laravel. You can link this issue or my comment.

**Comment by szepeviktor** [comment]
> And I agree, the return type can be `TValue|null`

@canvural Could you help me understand how `null` comes in?

**Comment by canvural** [comment]
@szepeviktor If there is no element in the collection, or the given key does not exist, it'd return null.

**Comment by canvural** [comment]
@totov Actually even `TValue|null` is not enough. Because when you do `collect([['id' => 1], ['id' => 2], ['id' => 3]])` the items of the collection are `array<string, int>` So we'd assume `max` returns  `array<string, int>`

So I guess return type should be `mixed` And we'd need a new extension here to support the specific types. If it's possible to do so.

**Comment by totov** [comment]
> @totov Actually even `TValue|null` is not enough. Because when you do `collect([['id' => 1], ['id' => 2], ['id' => 3]])` the items of the collection are `array<string, int>` So we'd assume `max` returns `array<string, int>`
> 
> So I guess return type should be `mixed` And we'd need a new extension here to support the specific types. If it's possible to do so.

When specifying a key, it doesn't return the TValue, it returns the max value of the key you specify.

`collect([['id' => 1], ['id' => 2], ['id' => 3]])->max();`  returns `['id' => 3]`

`collect([['id' => 1], ['id' => 2], ['id' => 3]])->max('id');`  returns `3`

**Comment by canvural** [comment]
@totov Yes. That's why I suggested `mixed` Cause type wise we can't know what is the type of the maximum element.
