### ISSUE TITLE
Return enums as collection requires all individual cases

### ISSUE THREAD

**Issue by phh** [nunomaduro/larastan#1129]
- Larastan Version: 9.0.2
- `--level` used: 6
- Pull request with failing test:

### Description

When adding enums to my project, I'd like to return all the cases as a collection.

I kinda would expect this return type would work:

```php
/** @return Collection<int, Role:> */
```

Since the returned value of `Role::cases()[0]` is `Role`.

However, it requires all possible cases set:

```php
/** @return Collection<int, Role::Admin|Role::Supporter|Role::User> */
```

So I'm getting this error:

```
Method App\Enums\Role::toCollection() should return Illuminate\Support\Collection<int, App\Enums\Role>
    but returns Illuminate\Support\Collection<int, App\Enums\Role::Admin|App\Enums\Role::Supporter|App\Enums\Role::User>
```

Is this the intended behavior?

### Laravel code where the issue was found

```php
enum Role: int
{
    case Admin = 1;
    case Supporter = 2;
    case User = 3;

    /** @return Collection<int, Role:> */
    public static function toCollection(): Collection
    {
        return collect(self::cases());
    }
}
```

**Comment by phh** [comment]
Mainly wondering if this is the expected behavior or not. If not I would love to come up with a suggestion for a fix!

**Comment by phh** [comment]
> Hi,
> 
> I don't understand the issue.
> 
> > I kinda would expect this return type would work:
> 
> What is the error you are getting?

Sorry, forgot the error. Added to the description as well:

```
Method App\Enums\Role::toCollection() return type with generic class Illuminate\Support\Collection does not specify its
         types: TKey, TValue
```

**Comment by canvural** [comment]
Ok, this looks like a PHPStan issue. Here is a simple reproduction: https://phpstan.org/r/e7c7fd51-04fc-4f4f-a63e-3794812f3065

Feel free to create an issue there with the playground link I gave.

**Comment by phh** [comment]
@canvural Thanks for reproducing the error in phpstan.org 🙏

**Comment by phh** [comment]
Fixed here https://github.com/phpstan/phpstan/issues/6695 / https://github.com/phpstan/phpstan-src/commit/9e428966d8f985db3199a234406c6799abd18617

Thank you again.
