### ISSUE TITLE
False positive on Laravel 9 collections with each, map, flatMap closure signature

### ISSUE THREAD

**Issue by pyrou** [nunomaduro/larastan#1130]
- Larastan Version: 2.0.1
- PHPStan Version: 1.4.6
- PHP Version: 8.0.15
- `--level` used: 5
- Pull request with failing test: N/A

### Description

Using each, flatMap, map method on Laravel 9 collections, phpstan always fail with following error :

```
Parameter #1 $callback of method Illuminate\Support\Collection<int,App\Models\User>::each() expects 
    callable(int, TKey of (int|string)): mixed, 
    Closure(App\Models\User): mixed given.
```

For an unknown reason, TValue looks resolved to int instead of my Model 

### Laravel code where the issue was found

```php
User::all()->each(fn (User $user) => dump($user->id));
```

**Comment by pyrou** [comment]
You mean #1121 would fix the issue or cause it ?

I'm already using Laravel v9.0.2

**Comment by szepeviktor** [comment]
I thought it would have fixed it.

**Comment by pyrou** [comment]
With `--debug` option no error. So it as to be something wrong in my cache. After running `phpstan clear-result-cache` error is gone. 🥺

I never suspected cache issue because, according to [phpstan documentation](https://phpstan.org/user-guide/result-cache#result-cache-contents), `composer.lock` is part of the cache key. Anyway, everything is fine now
