### ISSUE TITLE
Rate Limiter in Fresh Laravel 9 Project Throws Error

### ISSUE THREAD

**Issue by mdavis1982** [nunomaduro/larastan#1132]
- Larastan Version: 2.0.1
- `--level` used: max

### Description
In a fresh Laravel 9 project, I get an error in the `RouteServiceProvider` on the line regarding rate limiting.

The error is:
```
Cannot access property $id on mixed.
```

### Laravel code where the issue was found

```php
protected function configureRateLimiting(): void
{
    RateLimiter::for('api', function (Request $request) {
        return Limit::perMinute(60)->by($request->user()?->id 👈 ?: $request->ip());
    });
}
```

Is there a way to remove this error?

**Comment by szepeviktor** [comment]
Hello Matthew! 👋 

https://github.com/laravel/framework/blob/8ac224f61fb6ff8aa57d405b7c1f1390a6944bb1/src/Illuminate/Http/Request.php#L547

Types got into Laravel 9. So currently it is `mixed`.

**Comment by BertvanHoekelen** [comment]
You can add type hint for the user.
``` php
RateLimiter::for('login', function (Request $request) {
    /** @var \App\Models\User $user */
    $user = $request->user();

    return Limit::perMinute(60)->by($user->id ?: $request->ip());
});
```

**Comment by szepeviktor** [comment]
This is the very same problem.

Please see https://github.com/laravel/framework/blob/ef7f80a0c574b84c05305de7aee5d8103b97218a/src/Illuminate/Http/Request.php#L285

**Comment by szepeviktor** [comment]
@PiousVenom This is my non-official [policy](https://gist.github.com/szepeviktor/6c5b75f84e5c999eb8232cd963c8e6f5):

> Avoiding installation of new major version releases of any software in production, letting others test it first

So Laravel 9 makes you work a more than in 2 months.

**Comment by szepeviktor** [comment]
Please wait for others to chime in.
