### ISSUE TITLE
Defining Typed Collection that starts Empty

### ISSUE THREAD

**Issue by jamespavett** [nunomaduro/larastan#1138]
- Larastan Version: 2.0.1
- `--level` used: 6

### Description

Basically I am typehinting a Support Collection as containing <int, DummyType>

However in the constructor I want to initialise this to an empty collection, and then add DummyType elements to it late on. Is there a way to probably typehint this to Larastan / PHPStan doesn't throw errors.

Currently I am getting:

`phpstan: Property App\Services\DummyType Service::$generatedData (Illuminate\Support\Collection<int, App\Services\DummyType>) does not accept Illuminate\Support\Collection<*NEVER*, *NEVER*>.`

Or (when initialising collection via collect helper):

`phpstan: Unable to resolve the template type TKey in call to function collect`
`phpstan: Unable to resolve the template type TValue in call to function collect`

Not sure if I am trying to do something wrong here, or there is another way to achieve what I am after

### Laravel code where the issue was found

```php
    /**
     * The retrieved query data
     *
     * @var \Illuminate\Support\Collection<int, object>
     */
    private Collection $queryData;

    /**
     * The generated combined data
     *
     * @var \Illuminate\Support\Collection<int, DummyType>
     */
    private Collection $generatedData;

    /**
     * Constructor.
     */
    public function __construct()
    {

        $this->generatedData = new Collection();

       //or

       $this->generatedData = collect();
    }
```

**Comment by canvural** [comment]
Hi,

As of Larastan 2 and Laravel 9, all collection types are moved to Laravel core. So please open an issue there.

**Comment by jamespavett** [comment]
Sorry am I missing something. In my phpstan.neon folder aren't I referencing the extension.neon file which contains a stub for Collection

**Comment by canvural** [comment]
Yes, but if you look at that file you'd see the stub file is empty.

Type for the constructor is coming from [here,](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Collection.php#L37) not from stub file.

**Comment by jamespavett** [comment]
Sorry I must be being an idiot, but I swear on latest it still contains definition? Unless thats not what you mean

https://github.com/nunomaduro/larastan/blob/master/stubs/Collection.stub

![image](https://user-images.githubusercontent.com/10764464/155716429-8d80c7d4-d6f5-4483-adcd-8e70f7530c06.png)

**Comment by canvural** [comment]
Yes it contains definition. But that is not related to your issue. Your issue is with the type [here.](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Collection.php#L37) Which is defined in Laravel, not Larastan stub.
