### ISSUE TITLE
Model Properties not detected if a custom Schema facade is used

### ISSUE THREAD

**Issue by Riley19280** [nunomaduro/larastan#1146]
- Larastan Version: 2.0.1
- `--level` used: 7
- Pull request with failing test:

### Description
I am using a custom schema and custom blueprint that extend the existing Laravel Facades.
Due to the class name check [here](https://github.com/nunomaduro/larastan/blob/6caf3f9d3efede8ab873ecf88b24e9af7e6aca95/src/Properties/SchemaAggregator.php#L62), my model properties are not being picked up, resulting in ` Access to an undefined property App\Models\MyModel::$name.`

I'll gladly put together a PR for the fix, but I am wondering what the recommended direction is for the fix. A few possibilities I thought of are removing the class check, or making it configurable in the config. I am also open to other suggestions as well.

### Laravel code where the issue was found

Model Usage (in controller)
```php
public function update(UpdateMyModelRequest $request, MyModel $myModel): JsonResponse {
 $myModel->name = $request->input('name');
}
```
Migration Definition
```php
use Library\Database\Blueprint; // Instead of \Illuminate\Database\Schema\Blueprint
use Library\Database\Schema; // Instead of \Illuminate\Support\Facades\Schema

return new class extends Migration
{
   public function up()
    {
        Schema::create('mymodel', function (Blueprint $table) {
            $table->id();
            $table->string('name');
  });
}

```

**Comment by szepeviktor** [comment]
> I'll gladly put together a PR for the fix

Thank you! :)

**Comment by canvural** [comment]
It's been 2 weeks with no further info. As I said please send a PR if you can. Otherwise there is no point of keeping this open.
