### ISSUE TITLE
whereHas, orWhereHas do not recognize relations

### ISSUE THREAD

**Issue by abrampl** [nunomaduro/larastan#1157]
- Larastan Version: 2.1.1
- `--level` used: 5
- Pull request with failing test:

### Description

After update to 2.1.1 whereHas do not recognize relations. 

 Relation 'members' is not found in App\Models\Dossier model.

### Laravel code where the issue was found

```php
$q->orWhereHas('members', function ($q) {
    $q->where('name', '=', 'test');
});
```

**Comment by canvural** [comment]
If you can create a small repository where you can reproduce this, I can take a look and figure out whats going on.

**Comment by szepeviktor** [comment]
> a small repository

You may start from https://github.com/szepeviktor/larastan-issue

**Comment by abrampl** [comment]
Hi,
I was able to check what happend

I mark in my relationship custom eloquent builder

```php

class Member extends Model
{
    /**
     * @param Illuminate\Database\Query\Builder $query
     * @return MemberQueryBuilder<Member>
     */
    public function newEloquentBuilder($query): MemberQueryBuilder
    {
        return new MemberQueryBuilder($query);
    }
}

class Company extends Model
{
   public function members(): BelongsToMany | MemberQueryBuilder
    {
        return $this->belongsToMany(Member::class);
    }
}


/**
 * @template TModelClass of \App\Models\Member
 * @extends Builder<TModelClass>
 */
class MemberQueryBuilder extends Builder
{
    public function generalSearch($sentence): self
    {
        $this->where(function (Builder $q) use ($sentence) {
            $q->where('name', $sentence);

            $q->orWhereHas('companies', function ($q) use ($sentence) {
                $q->where('name', 'like', $sentence);
                $q->orWhere('address', $sentence);
            });
        });

        return $this;
    }
}
```

So when i use $company->members()->...., in my IDE, i have type hint for my function generalSearch

When i remove from my relationship info about custom query builder

```php

class Company extends Model
{
   public function members(): BelongsToMany
    {
        return $this->belongsToMany(Member::class);
    }
}
```

Larastan do not show anymore error  "Relation 'members' is not found in App\Models\Company model."

But IDE do not show type hints for function generalSearch()

**Comment by canvural** [comment]
Well, `BelongsToMany | MemberQueryBuilder` is definitely the wrong return type. `members` never returns `MemberQueryBuilder`

I don't know what would be the solution for your IDE unfortunately.

**Comment by abrampl** [comment]
So, when you have custom Builder, how you mark in your IDE  MemberQueryBuilder, to have type hint ??

**Comment by szepeviktor** [comment]
e.g. use a temporary variable and add `/** @var Type... */`
