### ISSUE TITLE
Can't install Larastan on a project that has Enlightn

### ISSUE THREAD

**Issue by fylzero** [nunomaduro/larastan#1165]
- Larastan Version: 2.1.2
- `--level` used: 5
- Pull request with failing test: N/A

### Description
- Install a fresh copy of Laravel 9
- Install https://github.com/enlightn/enlightn via `composer require enlightn/enlightn`
- Install https://github.com/nunomaduro/larastan via `composer require nunomaduro/larastan:^2.0 --dev`
- You'll receive the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nunomaduro/larastan ^2.0, found nunomaduro/larastan[dev-master, 2.0.0, ..., v2.1.2] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - enlightn/enlightn is locked to version v1.25.0 and an update of this package was not requested.
    - enlightn/enlightn v1.25.0 requires nunomaduro/larastan ^0.6.11|^0.7|^1.0.0 -> found nunomaduro/larastan[v0.6.11, ..., v0.7.15, 1.0.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Laravel code where the issue was found

```php

```

**Comment by canvural** [comment]
Looks like that package is [not compatible](https://github.com/enlightn/enlightn/blob/master/composer.json#L43) with Larastan 2. There is nothing we can do here.

**Comment by fylzero** [comment]
@canvural Thanks for letting me know!  Wasn't sure where the problem was.  I'll bug them to support it!  👍🏻
