### ISSUE TITLE
Custom eloquent builders won't work with `where` & `orWhere` since 2.1.0

### ISSUE THREAD

**Issue by fragkp** [nunomaduro/larastan#1173]
- Larastan Version: 2.1.2
- `--level` used: 6
- Pull request with failing test: -

Related PR: https://github.com/nunomaduro/larastan/pull/1144

`where`: https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L222
`orWhere`: https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L233

### Description
Hey!

Since version 2.1.0 we encountered an issue with `where` and `orWhere` when custom eloquent builder is as first parameter.

```
Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<App\Models\User>::where() expects 
  array<int|string, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<App\Models\User>): void)|Illuminate\Database\Query\Expression|string,          
  Closure(App\Models\Builders\UserBuilder): App\Models\Builders\UserBuilder given.
```

### Laravel code where the issue was found

```php
class User extends Model
{
    /**
     * @return UserBuilder<\App\Models\User>
     */
    public static function query(): UserBuilder
    {
        return parent::query();
    }

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return UserBuilder<\App\Models\User>
     */
    public function newEloquentBuilder($query): UserBuilder
    {
        return new UserBuilder($query);
    }
}
```
```php
/**
 * @template TModelClass of \App\Models\User
 * @extends Builder<TModelClass>
 */
class UserBuilder extends Builder
{
	//
}
```
```php
class TestController
{
    public function __invoke()
    {
        User::query()
            ->where(fn (UserBuilder $query) => $query
                ->where('email', 'some@test.com')
                ->orWhere('username', 'some-test')
            )
            ->get();
    }
}
```

**Comment by canvural** [comment]
Hi,

Can you test if it works when you change the `static<TModelClass>` to just `static` [here?](https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L222)

**Comment by fragkp** [comment]
@canvural Hey,

slightly different error:
```
Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<App\Models\User>::where() expects array<int|string,
mixed>|(Closure(App\Models\Builders\UserBuilder<App\Models\User>): void)|Illuminate\Database\Query\Expression|string,
Closure(App\Models\Builders\UserBuilder): App\Models\Builders\UserBuilder given.
```

**Comment by mabdullahsari** [comment]
Can confirm. I'm also getting lots of errors due to custom query builders even though the annotations are set correctly.

**Comment by canvural** [comment]
@fragkp and @mabdullahsari, can you test `dev-master` and check if it's fixed for you? Thanks.

**Comment by fragkp** [comment]
@canvural
I identified 3 errors:

---

```php
$this->hasOne(CompanyGoal::class)->where(fn (CompanyGoalBuilder $query) ...);
```

PHPStan Error:
_Parameter #1 $column of method Illuminate\Database\Eloquent\Relations\HasOne<App\Models\CompanyGoal>::where() expects array<int|string, mixed>|(Closure(Illuminate\Database\Eloquent\Relations\HasOne<App\Models\CompanyGoal>): void)|(Closure(Illuminate\Database\Eloquent\Relations\HasOne<App\Models\CompanyGoal>): Illuminate\Database\Eloquent\Relations\HasOne<App\Models\CompanyGoal>)|Illuminate\Database\Query\Expression|string, Closure(App\Models\Builders\CompanyGoalBuilder): App\Models\Builders\CompanyGoalBuilder given._


---

```php
$this->where(fn (CompanyGoalBuilder $query) => $query->whereNotNull('column'));
```

`whereDate` and other where* methods also not recognized.

PHPStan Error:
_Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<TModelClass of App\Models\CompanyGoal>::where() expects array<int|string, mixed>|(Closure(App\Models\Builders\CompanyGoalBuilder<TModelClass of App\Models\CompanyGoal>): void)|(Closure(App\Models\Builders\CompanyGoalBuilder<TModelClass of App\Models\CompanyGoal>): App\Models\Builders\CompanyGoalBuilder<TModelClass of App\Models\CompanyGoal>)|Illuminate\Database\Query\Expression|string, Closure(App\Models\Builders\CompanyGoalBuilder): App\Models\Builders\CompanyGoalBuilder<App\Models\CompanyGoal> given._

---

```php
User::query()->first()->load([
	'employee' => fn (HasOne $query) => $query
		->where(fn (EmployeeBuilder $query) => $query
			->where('email', 'test@test.com')
		)
]);
```

PHPStan Error:
_Parameter #1 $column of method Illuminate\Database\Eloquent\Relations\HasOne<Illuminate\Database\Eloquent\Model>::where() expects array<int|string, mixed>|(Closure(Illuminate\Database\Eloquent\Relations\HasOne): void)|(Closure(Illuminate\Database\Eloquent\Relations\HasOne): Illuminate\Database\Eloquent\Relations\HasOne)|Illuminate\Database\Query\Expression|string, Closure(App\Models\Builders\EmployeeBuilder): App\Models\Builders\EmployeeBuilder given._

**Comment by canvural** [comment]
Hi @fragkp 

All your errors are valid, but currently not possible to fix because PHPStan does not support a way to do it.

#1144 and #1178 fixed issues about this code:
```php
User::query()->where(function (Builder $query) {
    // Now PHPStan knows here the `$query` is `Builder<User>`
});
```

but broke your example `hasOne(CompanyGoal::class)->where(fn (CompanyGoalBuilder $query) ...);`

Since custom builders are less common than normal usage, I decided to keep these changes. And until PHPStan provides a way to fix this for us (issue [here](https://github.com/nunomaduro/larastan/issues/1110) if you want to follow), your only choices are to ignore these errors or not to typehint the builder. Hope you understand.
