### ISSUE TITLE
Calling `whereNotNull` on a `Collection` does not remove the nullable type

### ISSUE THREAD

**Issue by bram-pkg** [nunomaduro/larastan#1176]
- Larastan Version: 2.1.2
- `--level` used: 8

### Description

Calling ->whereNotNull on a collection does not remove the nullable type.

### Laravel code where the issue was found

```php
/**
 * @return Collection<int, string>
 */
public function getStrings() {
  return collect(['foo', null, 'bar'])
      ->whereNotNull();
}
```

The code above will throw an error that the `TValue` should be `string|null`.

**Comment by canvural** [comment]
Hi,

Yes, there is no support for that now. Until it gets implemented you can try to use `filter` instead if possible.

**Comment by bram-pkg** [comment]
For other people have this issue, I have changed the code fragment from:

```php
/**
 * @return Collection<int, string>
 */
public function getStrings() {
  return collect(['foo', null, 'bar'])
      ->whereNotNull();
}
```

to 

```
/**
 * @return Collection<int, string>
 */
public function getStrings() {
  return collect(['foo', null, 'bar'])
      ->filter(fn(?string $value) => ! is_null($value));
}
```

Hope it helps someone.
