### ISSUE TITLE
Eager loading with 'with' using colon syntax no longer works

### ISSUE THREAD

**Issue by mabdullahsari** [nunomaduro/larastan#1193]
- Larastan Version: `dev-master`
- `--level` used: 5

### Description

Probably introduced in #1175 as pointed out by @canvural.

### Laravel code where the issue was found

```php
protected function newCursorQuery(): Builder
{
    return Design::with('collection:id,slug,name', 'media')
        ->whereHas('collection')
        ->select('id', 'collection_id', 'name', 'slug');
}
```

`Relation 'collection:id,slug,name' is not found in Domain\Catalog\Models\Design model.`

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/commit/dcc58cdd330e05d119c97a35503d77780d35c2a7
