### ISSUE TITLE
`cursorPaginate()` doesn't work with `through()`

### ISSUE THREAD

**Issue by BramVanBerkel** [nunomaduro/larastan#1197]
- Larastan Version: 2.1.2
- `--level` used: 5 (occurs from level 2)
- Pull request with failing test:

### Description
When using `->cursorPaginate()->through()` larastan reports: `Call to an undefined method Illuminate\Contracts\Pagination\CursorPaginator::through()`, however when using `->paginate()->through()` larastan doesn't

### Laravel code where the issue was found

Works:
```php
return User::paginate()
            ->through(function(User $user) {
                return [
                    'name' => Str::upper($user->name),
                    'email' => $user->email,
                ];
            });
```

Doesn't work:
```php
return User::cursorPaginate()
            ->through(function(User $user) {
                return [
                    'name' => Str::upper($user->name),
                    'email' => $user->email,
                ];
            });
```

Same when using DB:
```php
return DB::table('users')
            ->select([
                'name',
                'email',
            ])
            ->orderBy('id')
            ->paginate()
            ->through(function($user): array {
                return [
                    'name' => Str::upper($user->name),
                    'email' => $user->email,
                ];
            });
```
and
```php
return DB::table('users')
            ->select([
                'name',
                'email',
            ])
            ->orderBy('id')
            ->cursorPaginate()
            ->through(function($user): array {
                return [
                    'name' => Str::upper($user->name),
                    'email' => $user->email,
                ];
            });
```

**Comment by szepeviktor** [comment]
Hello Bram! 👋 

You may close your own issue with a PR :)
Simple add `cursorPaginate`
https://github.com/nunomaduro/larastan/blob/eef292ffc5a65c15fa9ce32aec602aa68e19550d/stubs/EloquentBuilder.stub#L445-L456

**Comment by szepeviktor** [comment]
> Can you help with this?

Stubs are weird creatures. 🦕 Stubs need every class mentioned in PHPDoc blocks.
Please add them to https://github.com/nunomaduro/larastan/blob/master/stubs/Pagination.stub
