### ISSUE TITLE
Controller actions are not allowed to return redirect() or view()

### ISSUE THREAD

**Issue by vinayaggarwal-softway** [nunomaduro/larastan#1210]
- Larastan Version: #.#.#
- `--level` used: 5
- Pull request with failing test:

### Description
This should not be reported as error, it's a valid return for a controller action
```
Method App\Http\Controllers\API\UsersController::index() should return Illuminate\Http\Response but returns Illuminate\View\View.
```

### Laravel code where the issue was found

```php
public function index(Request $request, $id)
{
  return redirect()->back();
}
```

**Comment by szepeviktor** [comment]
Thank you for your report.
Please see our tests.
https://github.com/nunomaduro/larastan/blob/6a4b861168304cb9d2b9af493e470e36313c3346/tests/Type/data/redirect-response.php#L8-L9

What is your Larastan version?

**Comment by canvural** [comment]
Hi,

This is not about if it is a valid return for an action or not. The error says return type should be `Response` but you are returning `View` It's a valid error. Try adding `View` as return type hint.
