### ISSUE TITLE
When() method expects callable Builder with specific model but Model given

### ISSUE THREAD

**Issue by schonhoff** [nunomaduro/larastan#1214]
- Larastan Version: 1.0.3
- `--level` used: 5

### Description
Hello,

I'm trying to do a little bit of static analyzes on my project but I got an error that I can't fix with my knowledge. I tried to find something in the issues and got the following https://github.com/nunomaduro/larastan/issues/799 . There is a merged pull request, which should fix the problem but in my case it didn't fixed it. So I would guess it is another problem?

I added the `::query()` to the model that fixed most of the `when()` errors but this time it didn't. Can someone look into the problem and maybe provide a solution for it? Thanks and have a day/night!

### Error message:
```
Parameter #2 $callback of method Illuminate\Database\Eloquent\Builder<App\Models\LandingPage>::when() expects callable(Illuminate\Database\Eloquent\Builder<App\Models\LandingPage>, mixed):
Illuminate\Database\Eloquent\Builder<App\Models\LandingPage>|void, Closure(Illuminate\Database\Eloquent\Builder): Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model> given.
Anonymous function should return Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model> but returns Illuminate\Database\Eloquent\Builder<App\Models\LandingPage>.

```

### Laravel code where the issue was found

```php
public function __invoke(Request $request, $keyword, $city = null)
{
  $landingPage = LandingPage::query()
    ->where('keyword_slug', '=', $keyword)
    ->when(is_null($city), function (Builder $builder) {
        return $builder->whereNull('city_slug');
     }, function (Builder $builder) use ($city) {
         return $builder->where('city_slug', '=', $city);
     })
    ->firstOrFail();
    [...]
}
```

**Comment by szepeviktor** [comment]
Hello @schonhoff!

Your issue could be described in https://github.com/nunomaduro/larastan/discussions/1213

**Comment by schonhoff** [comment]
Hello @szepeviktor,

thanks for the fast response. I tried the following:
```php
public function __invoke(Request $request, $keyword, $city = null)
{
	$landingPage = LandingPage::query()
		->where('keyword_slug', '=', $keyword)
		->when(is_null($city),
			/**
			 * @param  Builder<LandingPage>  $builder
			 * @return \Illuminate\Database\Eloquent\Builder
			 */
			function (Builder $builder) {
				return $builder->whereNull('city_slug');
			}, function (Builder $builder) use ($city) {
				return $builder->where('city_slug', '=', $city);
			})
		->firstOrFail();
		[...]
}
```

But it didn't worked out. After I tried out some other things I got this solution:

```php
public function __invoke(Request $request, $keyword, $city = null)
{
	$landingPage = LandingPage::query()
		->where('keyword_slug', '=', $keyword)
		->when(is_null($city), function (Builder $builder) {
			/** @var Builder<LandingPage> $builder */
			return $builder->whereNull('city_slug');
		}, function (Builder $builder) use ($city) {
			return $builder->where('city_slug', '=', $city);
		})
		->firstOrFail();
	[...]
}
```

But I don't really understand why the Builder for the first parameter is a `Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>`. I would say that this should be a `Illuminate\Database\Eloquent\Builder<App\Models\LandingPage>` because the `when()` method is called on a query from the LandingPage model. I don't get why the type changed. In the `stubs/EloquentBuilder.stub` the callable is defined as `@param callable($this, mixed): (void|Builder<TModelClass>) $callback` and TModelClass should be the LandingPage class instead of the Illuminate Model. Am I missing something?

Thanks again and have a nice day/night =)

**Comment by szepeviktor** [comment]
Your first try is ideal but AFAIK docblocks for anonymous functions are ignored by PHPStan.

**Comment by szepeviktor** [comment]
> Thanks again and have a nice day/night =)

You're welcome! Ich bin auch eine von die Bremer Stadtmusikanten mit UTC+2.
