### ISSUE TITLE
Parameter #1 $user of method Illuminate\Foundation\Testing\TestCase::actingAs() expects Illuminate\Contracts\Auth\Authenticatable

### ISSUE THREAD

**Issue by gms8994** [nunomaduro/larastan#1215]
- Larastan Version: 1.0.3
- `--level` used: 5
- Pull request with failing test:

### Description

```
composer create-project laravel/laravel:^8.0 example-app
cd example-app
composer require nunomaduro/larastan
php artisan make:test UserAuthTest
```

#### edit phpstan.neon
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
```

#### Run phpstan
`php vendor/phpstan/phpstan/phpstan analyse --level=5 tests`

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------ 
  Line   Feature/TestUserAuth.php                                                                                                            
 ------ ------------------------------------------------------------------------------------------------------------------------------------ 
  18     Parameter #1 $user of method Illuminate\Foundation\Testing\TestCase::actingAs() expects Illuminate\Contracts\Auth\Authenticatable,  
         Illuminate\Database\Eloquent\Collection<Illuminate\Database\Eloquent\Model>|Illuminate\Database\Eloquent\Model given.               
 ------ ------------------------------------------------------------------------------------------------------------------------------------
``` 

### Laravel code where the issue was found

```php
<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;

class UserAuthTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_example()
    {
        $user = User::factory()->create();
        // dd(get_class($user)); shows `App\Models\User` correctly
        $response = $this->actingAs($user)
            ->get('/');
        $response->assertStatus(200);
    }
}
```

**Comment by szepeviktor** [comment]
Hello!
The case of `Authenticatable` vs. `User` is known.
e.g. https://github.com/nunomaduro/larastan/issues/836#issuecomment-848637431
Please [search issues for Authenticatable](https://github.com/nunomaduro/larastan/issues?q=is%3Aissue+sort%3Aupdated-desc+Authenticatable+is%3Aclosed)

**Comment by gms8994** [comment]
Please note that none of those issues are the issue I'm reporting; they're (almost exclusively) speaking about attributes on the Authenticatable, where I'm specifically calling out that the analysis is not correctly getting back the actual class somehow. #1045 is probably the closest, but is more about a

**Comment by szepeviktor** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Testing/Concerns/InteractsWithAuthentication.php#L12

**Comment by gms8994** [comment]
Right, https://github.com/laravel/laravel/blob/9.x/app/Models/User.php#L11 shows that the User model is an Authenticatable. Is your statement suggesting that it's somehow related to the Trait of InteractsWithAuthentication that is being used?

**Comment by szepeviktor** [comment]
No. Sorry I do not know the answer. That is way I've deleted my answer. (I'm just a janitor here)

**Comment by szepeviktor** [comment]
The cause could be `create()` may return a single Model or a collection of Models.

**Comment by szepeviktor** [comment]
It can be proven by inserting this in place of `dd`.
```php
if ($user instanceof \Illuminate\Database\Eloquent\Collection) return;
```

**Comment by canvural** [comment]
Hi,

The issue is we can't know if `User::factory()->create()` returns a single model or collection of models. So maybe try this:
```php
/** @var User $user */
$user = User::factory()->create();
```

Also you might need to add
```php
/**
 * @extends Factory<User>
 */
```
to your `UserFactory`

**Comment by gms8994** [comment]
Changing the test code to 

```
$user = User::factory()->createOne();
```

still triggers

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   Feature/UserAuthTest.php                                                                                                                                                      
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  21     Parameter #1 $user of method Illuminate\Foundation\Testing\TestCase::actingAs() expects Illuminate\Contracts\Auth\Authenticatable, Illuminate\Database\Eloquent\Model given.  
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
```

I'm happy to add an `@extends Factory<User>`, though it feels like that's something that should be handled out of the box by larastan by finding the factory link, as again, the class that's actually returned in code is correctly an Authenticatable.

**Comment by canvural** [comment]
You need to add `/** @var User $user */`

**Comment by gms8994** [comment]
Am I understanding that the problem is that because of the way Laravel 8.x has implemented the phpdoc lines in https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/Factory.php, this is not fixable by the Larastan devs and requires sprinkling `/** @var User $user */` (and the like for my other models) everywhere that uses a Factory to generate a model?

**Comment by szepeviktor** [comment]
The Laravel 9 sample app includes PHP generics:
https://github.com/laravel/laravel/blob/9.x/database/factories/UserFactory.php#L9

**Comment by canvural** [comment]
> Am I understanding that the problem is that because of the way Laravel 8.x has implemented the phpdoc lines in [https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/Factory.php](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/Factory.php?rgh-link-date=2022-04-18T19%3A36%3A45Z)

No, that's not the problem. Because statically it's hard to know that `User::factory()->create()` returns single model. Because it could be `User::factory()->count(10)->create()` or `User::factory(5)->create()` and these return collection.

**Comment by gms8994** [comment]
> No, that's not the problem. Because statically it's hard to know that `User::factory()->create()` returns single model. Because it could be `User::factory()->count(10)->create()` or `User::factory(5)->create()` and these return collection.

While I don't disagree that determining the result from `->count(10)->create` or even `factory(5)->create` could be problematic, `->createOne` still triggers the failure as mentioned in [in my previous comment](https://github.com/nunomaduro/larastan/issues/1215#issuecomment-1101686794), so knowing "how many" models were returned seems not related to this specific problem, unless I'm wildly misunderstanding something.

The only thing I can see is that because the [8.x framework code is specifying](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/Factory.php#L199) that it returns an `\Illuminate\Database\Eloquent\Model` that it causes some issue.

Adding `@extends` seems to have solved the problem in conjunction with `->createOne`, so I'll close this issue.
