### ISSUE TITLE
`__()` is recognized different from `trans()`

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/larastan#1227]
- Larastan Version: 1.0.3
- `--level` used: 7
- Pull request with failing test: 

### Description

The `__()` function isn't allowed to be used where only string is accepted as it can return `array|string|null` which is true, same for `trans()` but because of the `TransExtension` the `trans()` helper is allowed to be used for string concatination or similar.

### Laravel code where the issue was found

```php
__('my.translation').' '.$variable;
// vs
trans('my.translation').' '.$variable;
```

**Comment by makroxyz** [comment]
Is there a fix on the way or ```__``` must be replaced with ```trans```?
