### ISSUE TITLE
Return type helper for `app()->environment()`

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/larastan#1229]
- Larastan Version: 1.0.3
- `--level` used: 7
- https://github.com/phpstan/phpstan-strict-rules

### Description

As there's an argument for the environment Method it will always return a boolean. The string return type is only when there's no argument passed in.

>  48     Only booleans are allowed in an if condition, bool|string given.  

### Laravel code where the issue was found

```php
if ($this->app->environment('local')) {
    return;
}
```

**Comment by szepeviktor** [comment]
You could take advantage of `$this->app->isLocal()`.
Double benefit!!

**Comment by Gummibeer** [comment]
This was only one example - we also have places checking for multiple environments. So a return type helper would be nice.
