### ISSUE TITLE
How to tell Larastan that a trait exists: support `class_uses_recursive`

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1233]
I've read it here
https://github.com/phpstan/phpstan/issues/2800#issue-545017832

Could we assume that a given trait exist?

```php
in_array(RegistersRoutes::class, class_uses_recursive($field))
```

Support the recursive version of `class_uses`.

**Comment by canvural** [comment]
Doesn't sound like a thing we solve in Larastan. Should be solved in PHPStan somehow.
