### ISSUE TITLE
Laravel 9 Attributes should support public method

### ISSUE THREAD

**Issue by RahulDey12** [nunomaduro/larastan#1238]
- Larastan Version: latest
- `--level` used: 6

Hi, lalastan supports Laravel 9 specified attribute but it supports only protected method
https://github.com/nunomaduro/larastan/blob/eda1094b4eb279b1a4512665c148105c7aeb402e/src/Properties/ModelPropertyExtension.php#L294-L296

But in laravel docs it should support the public and the protected methods.
![image](https://user-images.githubusercontent.com/26340814/168994378-8973114d-37d9-41be-8e6f-1f00102e17a1.png)

**Comment by canvural** [comment]
Hi,

Attribute methods should have `protected` visibility. It is in the [documentation.](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor)

> ... To define an accessor, create a protected method on your model ...

If `public` is used in any of the examples, you should send a PR to Laravel docs instead to change it to `protected`
