### ISSUE TITLE
How to enable and disable a Rule in laraStan !! 

### ISSUE THREAD

**Issue by progalaa** [nunomaduro/larastan#124]
- Larastan Version: latest
- `--level` used: any

**i need to enable and disable rules in larastan** 
example
i got errors in dynamicWhere
#ex >> Transaction::whereStatus(1);
and also get error in If condition is always true
#ex >> if($cond) echo "success";

**but they disappears and appears upon the level so i need to know the limitation and cases for each level**
from 0 to 7

**Comment by ondrejmirtes** [comment]
Please see this: https://www.reddit.com/r/laravel/comments/8zp759/introducing_larastan_alpha_version/e2m0aqq/

**Comment by progalaa** [comment]
@ondrejmirtes  Thanks I'll Check
