### ISSUE TITLE
Scope on Wherehas not working

### ISSUE THREAD

**Issue by schonhoff** [nunomaduro/larastan#1242]
- Larastan Version: 2.1.4
- `--level` used:  5
- Pull request with failing test: Sorry, I would love to do this, but I don't know how to test it.

### Description
Hello,
similar to the error described in https://github.com/nunomaduro/larastan/issues/1216 it seems, that the whereHas function can not handle scopes of the related model. The error message is exactly the same. I tried all the things described in https://github.com/nunomaduro/larastan/issues/1216 but nothing worked out. Did I miss something?

Error message (changed function name to sync with the example):
```
Call to an undefined method Illuminate\Database\Eloquent\Builder::forTestingFirstFunction().
```

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class TestClassA extends Model
{
  public function testClassB(): HasMany
  {
    return $this->hasMany(
      TestClassB::class,
      'test_class_b_id'
    );
  }
}

/**
 * @method static Illuminate\Database\Eloquent\Builder|TestClassA forTestingFirstFunction(bool $someParameter = true)
 */
class TestClassB extends Model
{
  public function scopeForTestingFirstFunction(Builder $builder, bool $someParameter = true): Builder
  {
    return $builder->where('some_column', '=', $someParameter);
  }
}

/** This is a service class in my case */
class TestClassC
{
  TestClassA::whereHas('testClassB', function (Builder $query) {
    $query->forTestingFirstFunction(false);
  })
  ->get();
}
```

**Comment by canvural** [comment]
Hi,

You found the edge case 😄 Generic builder for `whereHas` (and some relation related methods)  are not supported because inside the closure the type of `$query` would be `Builder<TestClassB>` not `Builder<TestClassA>` And currently PHPStan does not have any way to support this.

What you can do is maybe overwrite the type inside the closure with `/** @var Builder<TestClassB> $query */`

If you want to keep track of the process for the issue, you can subscribe to #1110

**Comment by Merdin** [comment]
> `/** @var Builder<TestClassB> $query */`

Hi @canvural,

Before I open a new issue, I wanted to know if there is still no way to handle this?

I have:
```php
self::query()->whereHas(
                    'assignment',
                    function (Builder $q) use ($date): Builder {
                        /** @var Builder<Assignment> $q */
                        return $q->defaultType()->whereDate('start_date', $date);
                    }
                )->max('index') ?? -1;
```

This call is inside the `boot` of the model.

I get this error now:
```
PHPDoc tag @var with type Illuminate\Database\Eloquent\Builder<App\Domain\Projects\Models\Assignment> is not subtype of native type Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>.  
         🪪  varTag.nativeType  
```

Without `/** @var Builder<Assignment> $q */` I get:
```
Call to an undefined method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::defaultType().                                                                                           
         🪪  method.notFound  
```

**Comment by calebdw** [comment]
Just ignore the `varTag.nativeType` warning
