### ISSUE TITLE
Declaration of `AppMakeDynamicReturnTypeExtension::getTypeFromStaticMethodCall`

### ISSUE THREAD

**Issue by zbcchen** [nunomaduro/larastan#1244]
- Larastan Version: v2.1.5
- `--level` used:9
- Pull request with failing test:

### Description
`NunoMaduro\Larastan\ReturnTypes\AppMakeDynamicReturnTypeExtension::getTypeFromStaticMethodCall` cannot return nullable , unless the `PHPStan\Type\DynamicStaticMethodReturnTypeExtension::getTypeFromStaticMethodCall` can return a nullable value.
when a developer upgrade this package and runs `phpstan` then will get an error like below image. 
<img width="1738" alt="Screen Shot 2022-05-24 at 14 50 55" src="https://user-images.githubusercontent.com/90187037/169966923-56e81e9e-4d5c-4409-8915-f1f672d21bcd.png">

Do you have other consider？

### Laravel code where the issue was found

```php
// Now 
public function getTypeFromStaticMethodCall(MethodReflection $methodReflection, StaticCall $methodCall, Scope $scope): ?Type
    {
        
    }
//Revised
public function getTypeFromStaticMethodCall(MethodReflection $methodReflection, StaticCall $methodCall, Scope $scope): Type
    {
        
    }
```

**Comment by canvural** [comment]
Hi,

Since PHPStan 1.5.0 the return type is `?Type` See the source: https://github.com/phpstan/phpstan-src/blob/1.7.x/src/Type/DynamicStaticMethodReturnTypeExtension.php#L17

Update your PHPStan version if you are having this issue.
