### ISSUE TITLE
RelationExistenceRule wrongly identifies a class as a Model

### ISSUE THREAD

**Issue by wimulkeman** [nunomaduro/larastan#1245]
- Larastan Version: 1.0.3
- `--level` used: max

### Description
When requesting a service through Dependency Injection in the construction > setting it in a property or by calling `app(ServiceClass::class)` the following error is thrown:

```
Relation 'foo' is not found in App\Adapter\LaravelConfigurationAdapter model.
```

This behaviour does not occur when instantiating class through new.

### Laravel code where the issue was found

```php
$config = $this->app->make(LaravelConfigurationAdapter::class);
$this->config = $config;

// ...

$configValue = $this->config->has('main-config.sub-config-level')
            ? $this->config->get('main-config.sub-config-level') : null ;
```

### Possible solution
The rule could check if the provided class (on which the method is checked) extends the class `Illuminate\Database\Eloquent\Model` , which is a requirement for a Laravel Model class.

The following code was used as a patch to resolve the issue:

```diff
diff --git a/vendor/nunomaduro/larastan/src/Rules/RelationExistenceRule.php b/vendor/nunomaduro/larastan/src/Rules/RelationExistenceRule.php
--- a/vendor/nunomaduro/larastan/src/Rules/RelationExistenceRule.php	
+++ b/vendor/nunomaduro/larastan/src/Rules/RelationExistenceRule.php	(date 1653380563354)
@@ -4,6 +4,7 @@
 
 namespace NunoMaduro\Larastan\Rules;
 
+use Illuminate\Database\Eloquent\Model;
 use Illuminate\Database\Eloquent\Relations\Relation;
 use PhpParser\Node;
 use PhpParser\Node\Expr\MethodCall;
@@ -76,6 +77,10 @@
 
         $calledOnType = $scope->getType($node->var);
 
+        if (!in_array(Model::class, class_parents($calledOnType->getClassName(), true))) {
+            return [];
+        }
+
         $closure = function (Type $calledOnType, string $relationName, Node $node) use ($scope): array {
             $modelReflection = $this->modelRuleHelper->findModelReflectionFromType($calledOnType);

```

**Comment by dennisprudlo** [comment]
I found the same issue in my code: `Relation 'attempt' is not found in Illuminate\Contracts\Session\Session model.` In my case the line in question is simply checking if the session has a value in a form request.

```php
$this->session()->has('attempt.id');
```

Hope it helps to narrow the issue down

**Comment by dennisprudlo** [comment]
@szepeviktor But in this case `has` is not an eloquent builder method. Or am I missing something here? 😅

**Comment by dennisprudlo** [comment]
@wimulkeman I resolved other larastan errors and with one of them the wrong RelationExistenceRule disappeared. So it seems that another check triggered this one for me.

@szepeviktor I am not sure what you are trying to tell me here 😅 The `$this->session()->has('attempt.id')` does exactly the same thing, the code itself works. I use `$this` instead of `$request` because it is the in fact the request class the line is written in.

**Comment by szepeviktor** [comment]
@wimulkeman Please see here https://github.com/nunomaduro/larastan/blob/d0d5114e757f516bb2a2679ee03b7102db61d587/src/Rules/ModelRuleHelper.php#L19

> what you are trying to tell me here

@dennisprudlo That I'm just a janitor here, not anything more.

**Comment by dennisprudlo** [comment]
@szepeviktor All right then, till next time 😄

**Comment by wimulkeman** [comment]
It seems the issue is within the 1.x branch. When I update the project to use the 2.x branch the error doesn't show. With the Larastan 1.x branch it does.

I suspect that including the method within the foreach for the relation resolved it in 2.x because the method findModelReflectionFromType seems identical between the 2.x (master) and 1.x branch.

In my case the error is given due to the following check in PHPStan https://github.com/phpstan/phpstan-src/blame/1.7.x/src/Type/ObjectType.php#L321. It return a Trinary state of Maybe for all of the checks in findModelReflectionFromType. After the check the method `no()` is called upon the result which provides a `false`.

https://github.com/nunomaduro/larastan/blob/d0d5114e757f516bb2a2679ee03b7102db61d587/src/Rules/ModelRuleHelper.php#L21

https://github.com/phpstan/phpstan-src/blob/1.7.x/src/TrinaryLogic.php#L67

It seems in my case the error is triggered because the property is an interface and the Eloquent classes are not final.

That may change the issue to the following, what to do if an interface is passed? Should we treat it as a maybe and always consider it as a model / builder / etc? Or should we consider it a pass and not check for methods like `has`?

**Comment by szepeviktor** [comment]
> **What to do next**

Make @canvural merge #1247 :)

**Comment by canvural** [comment]
Hi,

Sorry for the delay.

We do not accept anymore bug fixes for 1.x branch. Even if we merge #1247 at this point we'd need to backport a lot of changes to make a release. Since this is not a real blocker, I suggest to ignore these errors, add it to the baseline or upgrade to 2.x

Thanks for understanding.
