### ISSUE TITLE
Unknow class error with PHPStan v1.7.0

### ISSUE THREAD

**Issue by ricklambrechts** [nunomaduro/larastan#1246]
- Larastan Version: 2.1.6
- `--level` used: 8
- Pull request with failing test: 

### Description

I think this is a PHPStan issue, but I created it here because in the latest release we increased the minimum PHPStan version to 1.7.0.
There is no problem with PHPStan version 1.6.9.

### Laravel code where the issue was found
On version 1.7.0, there errors are found.
```
PHPDoc tag @mixin contains unknown class Eloquent.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
```
```
Call to static method info() on an unknown class Log.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
```
```
Call to static method table() on an unknown class DB.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
```

**Comment by szepeviktor** [comment]
Hello Rick! 👋🏻 
Try to use FQCN-s in docblocks.

**Comment by ACWalker** [comment]
Hello,

I am also getting this issue. In my case i'm using Laravel-ide-helper and it generates the mixin:

` @mixin \Eloquent`

Where eloquent is defined in the `app/_ide_helper.php` file as: `class Eloquent extends \Illuminate\Database\Eloquent\Model `

**Comment by canvural** [comment]
@ACWalker Maybe [this](https://phpstan.org/user-guide/discovering-symbols) page will help you.

**Comment by szepeviktor** [comment]
> It seems that the FQCN is just `\Eloquent` in this case.

It is highly advised to use real classes. "Explicit" costs a bit more but is worth much more then "implicit".

**Comment by jnbn** [comment]
@canvural  do you mind leaving this ticket opened for sometime for reference until it's been solved on laravel-ide-helper ?

**Comment by jnbn** [comment]
Just found this:

https://github.com/nunomaduro/larastan/issues/555#issuecomment-624297770
