### ISSUE TITLE
Call to an undefined static method                         Illuminate\Support\Str::contains(). 

### ISSUE THREAD

**Issue by brmn** [nunomaduro/larastan#1249]
- Larastan Version: 2.1.6
- `--level` used: 5

### Description
Code works, nor IDE neither other tools complain, only phpstan

### Laravel code where the issue was found

```php
use Illuminate\Support\Str;
...
return Str::contains(
            $exception->getMessage(),
            [
                'There is already an active transaction',
            ]
        );
```

**Comment by szepeviktor** [comment]
Hello @brmn! 👋🏻 
What a brief issue!!

https://github.com/laravel/framework/blob/21959000a2d64e1aae8d8c12d256c0a0234715f2/src/Illuminate/Support/Str.php#L212
There must be a PHPStan configuration issue or else hundreds of users would complain.

**Comment by brmn** [comment]
`includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app
        - domain

    # The level 9 is the highest level
    level: 5

    ignoreErrors:
        - '#PHPDoc tag @var#'

    excludePaths:
        - ./*/*/FileToBeExcluded.php
        - routes
        - database
        - _ide_helper.php
        - .phpstorm.meta.php
        - tests
        - config/insights.php

    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false

    parallel:
        jobSize: 5
        maximumNumberOfProcesses: 4
        minimumNumberOfJobsPerProcess: 2
`

**Comment by szepeviktor** [comment]
> ```neon
> - _ide_helper.php
> ```

I see! ide-helper is not compatible with Larastan.
What if you remove everything ide-helper related?

**Comment by brmn** [comment]
removing ide-helper from exludePaths helped.
thanks
