### ISSUE TITLE
Required PHPStan 1.7+ breaks integration

### ISSUE THREAD

**Issue by bertoost** [nunomaduro/larastan#1250]
- Larastan Version: 2.1.6
- `--level` used: 2
- Laravel Version: 9.14.0

### Description

The latest version 2.1.6 has a sudden requirement for phpstan 1.7+ and that breaks the integration why phpstan ended up with thousands of errors which are no errors.

We had to downgrade to 2.1.5 and forced phpstan to 1.6.9

**Comment by szepeviktor** [comment]
> and that breaks the integration

Hello @bertoost!
Do you have custom PHPStan extensions?
What does "integration" really mean?

**Comment by bertoost** [comment]
we use `phpstan/extension-installer` .
I mean integration with phpstan in a laravel project.. a lot of magic stuff from laravel is reported as error, like `Route::get()` things etc.

**Comment by bertoost** [comment]
as far we have noticed, it's about the alias mapping in Laravel's app.php config. If you use one of those, without implicit use import statement, it breaks in phpstan

**Comment by szepeviktor** [comment]
> as far we have noticed, it's about the alias mapping in Laravel's app.php config. If you use one of those, without implicit use import statement, it breaks in phpstan

Yes, that comes from fully static reflections.
I follow the "everything must be explicit" rule, so no class aliasing. (Rector comes handy when it comes to mass fixing)
So I do not suggest you this: https://github.com/nunomaduro/larastan/issues/1246#issuecomment-1135698009

**Comment by bertoost** [comment]
Makes sense. We're going to look at that.
Therefore I would like to say, that you should not upgrade such major change in a patch update of larastan. This breaks a lot since Laravel supports the class aliasing anyway

**Comment by wimulkeman** [comment]
@szepeviktor Out of curiosity, I read the update logs from PHPStan https://github.com/phpstan/phpstan/releases/tag/1.7.0. Is this issue caused due to PHPStan not executing the analysed code, which in result prevents Larastan from booting the application with the aliases?

**Comment by szepeviktor** [comment]
We still boot the framework.
But fully static reflections does not include class aliases.

**Comment by j3j5** [comment]
In case it helps somebody, this is the `rector.php` that I used to replace all my aliases with rector, props to [this blog post](https://getrector.org/blog/2020/12/07/laravel-facades-to-constructor-injection-replace-facade-aliases-with-full-classes-in-2-hours) where I got the idea from.

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Renaming\Rector\Name\RenameClassRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
        'App' => Illuminate\Support\Facades\App::class,
        'Arr' => Illuminate\Support\Arr::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Input' => Illuminate\Support\Facades\Input::class,
        'Inspiring' => Illuminate\Foundation\Inspiring::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'Str' => Illuminate\Support\Str::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
    ]);

    $rectorConfig->importNames();
};
```

With that in place, just run `./vendor/bin/rector process app/` and your code-style tool of choice afterwards.
