### ISSUE TITLE
Getting Issue In The Function Return Type

### ISSUE THREAD

**Issue by misusonu18** [nunomaduro/larastan#1257]
- Larastan Version: 2.1
- `8-level` used:

### Description
I'm Getting the issue of return type getting (void and self) but it returns the only self.

### Code
![image](https://user-images.githubusercontent.com/52093984/171393560-6b9b8ec6-bd52-429a-9d42-190d11e045a3.png)

### Larastan Error
![image](https://user-images.githubusercontent.com/52093984/171393639-a6992d10-0618-466f-a7d5-46167dc8b1c5.png)

**Comment by szepeviktor** [comment]
Reference: https://github.com/laravel/framework/blob/6fb604f43a5f2dbce928c704532fde291f313416/src/Illuminate/Conditionable/Traits/Conditionable.php#L13-L19

**Comment by canvural** [comment]
We just need to change the return type to `(TWhenReturnType is void ? $this : TWhenReturnType)` in our stubs. If anyone wants to send PR.

**Comment by hirenkeraliya** [comment]
@canvural on which stub we need to add this?

**Comment by canvural** [comment]
Next version of PHPStan will be able to read stubs from traits, thanks to [this.](https://github.com/phpstan/phpstan-src/pull/1390) So this will be easy to implement again!

**Comment by szepeviktor** [comment]
Can Vural is our hero 🦸🏻‍♂️
