### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Arr::get().  

### ISSUE THREAD

**Issue by brmn** [nunomaduro/larastan#1269]
- Larastan Version: 2.1.8
- `--level` used: 5
- Pull request with failing test: null

### Description

phpstan 1.7.11

larastan 2.1.8

laravel 9

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app
        - domain

    # The level 9 is the highest level
    level: 5

    ignoreErrors:
        - '#PHPDoc tag @var#'
        - '#Call to an undefined method .*Request::input\(\)#'

    scanFiles:
      - .phpstorm.meta.php

    excludePaths:
        - ./*/*/FileToBeExcluded.php
        - routes
        - database
        - tests
        - config/insights.php
        - _ide_helper.php
        - .phpstorm.meta.php

    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false

    parallel:
        jobSize: 5
        maximumNumberOfProcesses: 4
        minimumNumberOfJobsPerProcess: 2
```

```
Call to an undefined static method Illuminate\Support\Arr::get().
```

### Code snippet that reproduces the problem
`\Illuminate\Support\Arr::get($data, 'id_str')`

### Expected output
no output

**Comment by szepeviktor** [comment]
Hello! Try removing `.phpstorm.meta.php`

**Comment by canvural** [comment]
Hi,

`get` is a normal static method on `Arr` class. Can be seen here: https://github.com/laravel/framework/blob/93d3250c748d7b552091495d1585d011d4cd70d3/src/Illuminate/Collections/Arr.php#L307

I do not know why you'd get that error. And I just tried it in a Laravel project with Larastan, and I can not reproduce it. Try removing `scanFiles` from your config like @szepeviktor said. If still does not work, I'd ask for you to create a small repo that reproduces the issue.
