### ISSUE TITLE
phpstan shows error from larastan stubs

### ISSUE THREAD

**Issue by mostafa-rz** [nunomaduro/larastan#1273]
- Larastan Version: 2.1.5
- `--level` used: 5
- Pull request with failing test:

### Description
Hi, I updated my larastan package and now when I run the phpstan it is showing errors from larstan stub files. Is this ok that such errors show to me?

### Laravel code where the issue was found

![Screenshot 2022-06-10 121934](https://user-images.githubusercontent.com/71334549/173045252-ee133d45-baf1-4bfe-9db9-c2fe21319086.png)
```

**Comment by canvural** [comment]
Hi,

I'm not sure how is this happening, but you need to update your PHPStan version also. Please confirm you have at least PHPStan 1.7.10

**Comment by mostafa-rz** [comment]
> Hi,
> 
> I'm not sure how is this happening, but you need to update your PHPStan version also. Please confirm you have at least PHPStan 1.7.10

Thanks my problem is resolved.
One more thing, i didn't install phpstan directly and it is installed as a larastan dependency. Should be in this way that when i upgrade the larastan it must also upgrade the phpstan?

**Comment by canvural** [comment]
Yes it already works like that. Latest release of Larastan needs minimum PHPStan 1.7.10: https://github.com/nunomaduro/larastan/blob/e65978bc2ec0a6177cc1e00d9ed053a877d9e8d3/composer.json#L26

Alternatively you can run `composer update -W` so it'll also update other dependencies.
