### ISSUE TITLE
flatMap always returns mixed

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/larastan#1274]
- Larastan Version: v2.1.10
- `--level` used: 9
- Pull request with failing test:

### Description
When using `flatMap` it always threats the result as a `mixed` even though it should be able to determine the type.

A flatmap should return an iterable and the type of the iterable will be the type of the new collection

### Laravel code where the issue was found

```php
        Collection::make([
            ['string', 'test'],
            ['works'],
        ])
            ->flatMap(fn(array $strings) => $strings)
            ->filter(fn(string $string) => $string === "works")
            ->count();
```

**Comment by olivernybroe** [comment]
Seems `flatten` has the same issue 🤔

**Comment by olivernybroe** [comment]
@canvural true true 🤔 should we try to pr it to laravel instead of creating stubs again?

**Comment by canvural** [comment]
Yes, that's a better way.

We can use collection stubs here to experiment with new ideas or for stuff that is too controversial for Laravel itself 🤣

**Comment by olivernybroe** [comment]
I'll close here then and find some time to create some failing type tests to Laravel 👍

**Comment by olivernybroe** [comment]
Hmm, I tried setting the type in Laravel docs, but was not able to figure out how 🤔 

Problem is that the type returned from `flatMap` is the type of the value of a generic array.

e.g. 
```
/**
 * @template TKey of array-key
 * @template TValue
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @implements \Illuminate\Support\Enumerable<TKey, TValue>
 */
class Collection implements ArrayAccess, CanBeEscapedWhenCastToString, Enumerable
```

is the signature, so the type returned from flatmap is the type of the value key of `TValue`, which I couldn't figure out a way to solve in phpstan. 

Should this be solved in larastan then or created as a feature request to phpstan?

**Comment by canvural** [comment]
@olivernybroe Maybe you can try something with `key-of` or `value-of`: https://phpstan.org/writing-php-code/phpdoc-types#key-and-value-types-of-arrays-and-iterables

**Comment by olivernybroe** [comment]
@canvural I did look at those, however it seems their usecase is different. They are used to limit to specific values of an array and doesn't seem to work with generics 🤔 

At least when using them, it resulted in a invalid type resolving

**Comment by olivernybroe** [comment]
@canvural nevermind, you were right, thanks! 
This seems to solve it 
```
(T is iterable ? static<int, value-of<T>> : static<int, mixed>)
```

**Comment by canvural** [comment]
@olivernybroe I see that the PR got rejected. But we can add that here as a stub if you want.
