### ISSUE TITLE
 Call to method markAsRead() on an unknown class App\Models\collection.

### ISSUE THREAD

**Issue by OmarAbdelazizMahmed** [nunomaduro/larastan#1282]
- Larastan Version: 1.0
- `--level` used:
- Pull request with failing test:

### Description
I'm using  Notifiable for notification that has the markAsRead method but larastan returns the following error

### Laravel code where the issue was found

```
  16     Call to method markAsRead() on an unknown class App\Models\collection. 
```

**Comment by OmarAbdelazizMahmed** [comment]
Solved by Adding above the class name
```
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $unreadNotifications
```

**Comment by szepeviktor** [comment]
Nice!
