### ISSUE TITLE
Check routes

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#129]
Would it be possible to check route classes and methods?
See https://github.com/slevomat/coding-standard/issues/412

**Comment by nunomaduro** [comment]
@szepeviktor Sure! Thanks for the proposal. Great idea!

**Comment by szepeviktor** [comment]
Maybe my code cloud be used
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/Commands/RouteCheckCommand.php#L55-L105

**Comment by nunomaduro** [comment]
No plans at this time to implement this myself. Fell free to pull request this feature.
