### ISSUE TITLE
RelationExistenceRule fails for eager loaded relations

### ISSUE THREAD

**Issue by TomKeyte** [nunomaduro/larastan#1302]
- Larastan Version: 2.1.11
- `--level` used: 1
- Pull request with failing test:

### Description

I am seeing failures of the RelationExistenceRule when eager loading using with

### Laravel code where the issue was found

```php
class Author extends Model {
  public function books() {
    return $this->hasMany(Book::class);
  }
}

$authors = Author::with('books');

```

The error shows
```
Relation 'books' is not found in App\Models\Author model.  
```

I have determined that, in `RelationExistenceRule`, the relation reaches the foreach loop on L91, $relationType is evaluated as `ConstantStringType`, and then the rule erros, as I do not have a method of `books` defined in the docString (there is however a property defined as
```
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Book[] $books
```

I'm using ide-helper to generate the model model docStrings

**Comment by canvural** [comment]
Hi,

Your relation needs to have a return type to be recognized as a relation. Add `HasMany` as native return type to `books` and it should work.

**Comment by TomKeyte** [comment]
Hi,

That was quick :D Thank you!

Is there any way around that? I'm working on a really big project, where adding all of them is a very big task

**Comment by canvural** [comment]
Unfortunately not. PHPStan does not scan method bodies. So we need return type to determine if a method is relation or not.

**Comment by canvural** [comment]
Maybe you can try adding `/** @method HasMany<Book> book() */` to the `Author` class docblocks. But I didn't try it and don't know if it'll work.
