### ISSUE TITLE
How do you deal with `Cannot call method X on App\Models\User|null`

### ISSUE THREAD

**Issue by pacoorozco** [nunomaduro/larastan#1310]
- Larastan Version: 2.1.11
- `--level` used: 8

### Description
When I use `Auth::user()` or `$request->user()` in my code, PHPstan give me this kind of errors:

```
Cannot call method X on Gamify\Models\User|null
```

where `X` is one method.

The code is right, because the guards and `FormRequests`... are ensuring that it can't be null. 

In order to avoid the PHPstan message I end writting:

```
User::firstOrFail(Auth::id()) 
```

but it seems a bit of repetitive and it doesn't add any value. 

**How are you dealing with these kind of messages?**

### Laravel code where the issue was found

```php
public function index(): View
    {
        $questions = Auth::user()?->pendingVisibleQuestions(self::MAX_QUESTIONS_SHOWN);

        return view('dashboard.index')
            ->with('questions', $questions)
            ->with('usersInRanking', Game::getTopExperiencedPlayers());
    }
```

**Comment by szepeviktor** [comment]
> the guards and `FormRequests`... are ensuring that it can't be null.

PHPStan does not know about that.

There are several ways to tell that. The dumbest being
```php
/** @var \App\Models\User $user */
$user = Auth::user();
```

**Comment by pacoorozco** [comment]
I did not though about this simple change... Thanks a lot
