### ISSUE TITLE
[octane] static array memleak not caught

### ISSUE THREAD

**Issue by simonbuehler** [nunomaduro/larastan#1311]
- Larastan Version: 2.1.12
- `--level` used: 9

### Description

when the code has some static array appends like [in the docs](https://laravel.com/docs/9.x/octane#managing-memory-leaks) no error is thrown.

### Laravel code where the issue was found

```php
class Sample {
  public static $leak = [];
}

public function oh_no()
{
   Sample::$leak[] = "oops";
}
```

**Comment by szepeviktor** [comment]
I see! Octane does not exit at the end of an HTTP request so your memory gets full.

**Comment by szepeviktor** [comment]
How would you decide whether the above pattern is intentional or not?

What would be the right implementation?

**Comment by canvural** [comment]
Hi,

This sounds too specific to be included in Larastan. But definitely feel free to create your own custom rule for this! Seems relatively easy. You can read [here](https://phpstan.org/developing-extensions/rules) more about creating custom rules.

**Comment by szepeviktor** [comment]
Larastan has a parameter called `checkOctaneCompatibility`.
Maybe some day this rule will be included.
