### ISSUE TITLE
Relation is not found in pivot model.

### ISSUE THREAD

**Issue by ManuelLeiner** [nunomaduro/larastan#1313]
- Larastan Version: 2.1.12
- `--level` used: 0
- Repo with example: https://github.com/ManuelLeiner/larastan-level-0

### Description
In the repo above you will find a basic Laravel Jetstream installation which reports a level 0 error. You can find a short summary below. What do you think of this error? Can I help in any other way?

#### Scenario
When using a pivot model class `TeamUser` in the `Team`'s `users()` relation, `phpstan analyse` reports a missing relation `projects()` which is of course implemented in the `User` model. 

```bash
/var/www/html# ./vendor/bin/phpstan analyse
Note: Using configuration file /var/www/html/phpstan.neon.
 39/39 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ----------------------------------------------------------------
  Line   Models/Project.php                                     
 ------ ----------------------------------------------------------------
  42     Relation 'projects' is not found in App\Models\TeamUser model.
 ------ ----------------------------------------------------------------

                                                                                                                        
 [ERROR] Found 1 error
 ```
                                                            
### Laravel code where the issue was found

Please have a look into this [commit](https://github.com/ManuelLeiner/larastan-level-0/commit/2cbfa1527a65b8d9667b0f9ab2e524109d30372c), which is the first commit that differs from the basic Jetstream installation.

**Comment by szepeviktor** [comment]
@canvural Could you help?
I think it is easy to spot **for your**.

**Comment by Temepest74** [comment]
any update on the issue?

**Comment by canvural** [comment]
You can define your `users` relation in `Team` like so:

```php
/**
     * Get all of the users that belong to the team.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<User>
     */
    public function users(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return parent::users()->using(TeamUser::class);
    }
```
