### ISSUE TITLE
Accessing model properties using constants

### ISSUE THREAD

**Issue by grzesw** [nunomaduro/larastan#1314]
- Larastan Version: 2.1.12
- `--level` used: 9

### Description

When accessing model properties using constants, Larastan reports `Access to an undefined property` error.

### Laravel code where the issue was found

```php
class Person extends Model {
  public const NAME = 'name';
}

$person->name = 'Joe'; // this works
$person->{Person::NAME} = 'Joe'; // this doesn't ❌
```

**Comment by szepeviktor** [comment]
Thank you @grzesw! 👋🏻

**Comment by canvural** [comment]
Hi,

We are just using the extension points PHPStan provides. So it seems like `PropertiesClassReflectionExtension` does not support a use case like this. There is nothing we can do here.

You can report this to PHPStan if you want.
