### ISSUE TITLE
Parameter #1 $code of function abort expects int|Symfony\Component\HttpFoundation\Response, JsonResource given.

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#132]
- Larastan Version: 0.2.7
- `--level` used: 5

### Description:

`abort` helper function in Laravel has a docblock like `\Symfony\Component\HttpFoundation\Response|int` for the `$code` parameter.
But in the code, `$code` parameter is being checked for `Responsable` interface. So anything that implements `Responsable` is valid here.

Maybe this is Laravel's fault rather than larastan/phpstan.

### Laravel code where the issue was found:

`abort(new Illuminate\Http\Resources\Json\JsonResource([]))`

**Comment by szepeviktor** [comment]
@canvural Try sending a PR to @laravel with adding `Responsable` to PHPDoc.

**Comment by canvural** [comment]
This is fixed in Laravel.
