### ISSUE TITLE
Conflict with PHP CS Fixer

### ISSUE THREAD

**Issue by eskiesirius** [nunomaduro/larastan#1320]
- Larastan Version: v2.1.12
- `--level` used: 5

### Description
Conflict with the coding standards. ```/* @var \App\Models\Category $this */```
if i will change it to ```/** @var \App\Models\Category $this */```, larastan will accept but not cs fixer

### Laravel code where the issue was found

```php
<?php

namespace App\Http\Resources\Admin\Category;

use Illuminate\Http\Resources\Json\JsonResource;

class CategoryResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        /* @var \App\Models\Category $this */
        return [
            'id' => $this->id,
            'name' => $this->name,
            'slug' => $this->slug,
        ];
    }
}
```

**Comment by szepeviktor** [comment]
Hello @eskiesirius!
Thank you for reporting this.

`/*` is the start of a multiline comment, it is not a docblock.

Could you try the following?

```php
/**
 * @var \App\Models\Category $this
 */
```

**Comment by szepeviktor** [comment]
BTW what PHP CS Fixer preset/rule do you use?

**Comment by eskiesirius** [comment]
> Hello @eskiesirius! Thank you for reporting this.
> 
> `/*` is the start of a multiline comment, it is not a docblock.
> 
> Could you try the following?
> 
> ```
> /**
>  * @var \App\Models\Category $this
>  */
> ```
php fixer will accept but larastan will not

**Comment by eskiesirius** [comment]
Sorry, I edited my comment again..

**Comment by eskiesirius** [comment]
i am using v3.9.4 of php-cs-fixer

**Comment by szepeviktor** [comment]
What PHP CS Fixer preset/rule do you use?

**Comment by szepeviktor** [comment]
This is the root cause.
https://github.com/nunomaduro/larastan/blob/f19e93430c48b546f3503e8bd01c0e7f673edc8e/CHANGELOG.md#bc-breaking-changes
You don't have to add `@var`!

```php
/**
 * @mixin \App\Models\Category
 */
class CategoryResource extends JsonResource
{
```

**Comment by eskiesirius** [comment]
> This is the root cause. https://github.com/nunomaduro/larastan/blob/f19e93430c48b546f3503e8bd01c0e7f673edc8e/CHANGELOG.md#bc-breaking-changes You don't have to add `@var`!
> 
> ```
> /**
>  * @mixin \App\Models\Category
>  */
> class CategoryResource extends JsonResource
> {
> ```

thank you so much! It is working now!

**Comment by szepeviktor** [comment]
You're welcome.
