### ISSUE TITLE
Can't seem to get it to recognize database type changes

### ISSUE THREAD

**Issue by ingageco** [nunomaduro/larastan#1321]
- Larastan Version: 1.x
- `--level` used: 5
- Pull request with failing test: none

### Description

Looking to see if there is some sort of cache, or something else, that could keep Larastan (Phpstan?) from detecting changes. I have the following error on a model property from the database: 

```
Parameter #1 $hour of method DateTime::setTime() expects int, string|null given.
```

Initially, this parameter was a string in the database, so I changed it to an integer - yet i'm still receiving the error. When i hover over the property in my IDE, run a var_dump, etc - it's always reported as an int, accurately. 

Is there any reason Larastan would continue to report this, or anything I can do to get it to pick up the change? I know I can use $casts to ensure a type, but shouldn't it now reflect the database change? 

Thank you for the awesome package & any help. Im new to static analysis, this is likely something i'm misunderstanding. 

### Laravel code where the issue was found

Laravel model property

**Comment by szepeviktor** [comment]
Hello Jay! 👋🏻 

> if there is some sort of cache

There is. You may issue `phpstan clear-result-cache`.

> Initially, this parameter was a string in the database

Larastan parses database migrations to get property types.

Have you changed/added migrations?

**Comment by ingageco** [comment]
@szepeviktor Sorry for the delayed reply - somehow I didn't get the email notification of your reply. 

I didn't create a migration - I changed the DB via a custom command, since it's something i need to run only once. Does that make a difference?

**Comment by canvural** [comment]
@ingageco Larastan does not make a db connection to know your columns. It scans the migrations folder, or the squashed migrations. So the change needs to be in either of those.

**Comment by ingageco** [comment]
@canvural Ah ok - i need to re-squash. Got it! Thank you!
