### ISSUE TITLE
Service 'rules.138': Class 'NunoMaduro\Larastan\Rules\RelationExistenceRule' not found. 

### ISSUE THREAD

**Issue by str** [nunomaduro/larastan#1322]
- Larastan Version: 2.1.11
- `--level` used: 5
- Pull request with failing test:

### Description
After installing,  and including the extension.neon file in my phpstan.neon file, I get the following error when running phpstan analyse

```
In Resolver.php line 111:
                                                                                           
  Service 'rules.138': Class 'NunoMaduro\Larastan\Rules\RelationExistenceRule' not found.  
                                                                                           

```

### Laravel code where the issue was found

The only Resolver.php file I found was at `vendor/vlucas/phpdotenv/src/Loader/Resolver.php`, but it only has 65 lines

**Comment by szepeviktor** [comment]
Hello @str!
Could it be https://github.com/nette/union/blob/master/di/src/DI/Resolver.php#L111 ?

It is part of the PHPStan PHAR file.
https://github.com/phpstan/phpstan-src/blob/1.8.x/composer.json#L19

**Comment by szepeviktor** [comment]
This is very strange!
https://github.com/phpstan/phpstan-src/blob/f1fd385433480f87bdda1d7d8ff6887e25f003ba/src/Broker/ClassAutoloadingException.php#L29

Could you search `vendor/composer/` for `RelationExistenceRule` ?

**Comment by str** [comment]
```bash
$  grep -rFn RelationExistenceRule vendor/composer/
vendor/composer/autoload_static.php:9528:        'NunoMaduro\\Larastan\\Rules\\RelationExistenceRule' => __DIR__ . '/..' . '/nunomaduro/larastan/src/Rules/RelationExistenceRule.php',
vendor/composer/autoload_classmap.php:8937:    'NunoMaduro\\Larastan\\Rules\\RelationExistenceRule' => $vendorDir . '/nunomaduro/larastan/src/Rules/RelationExistenceRule.php',

grep -rFn 'NunoMaduro\Larastan' vendor/composer/
# this one did not return anything
```

**Comment by szepeviktor** [comment]
Thank you!

Please try clearing PHPStan cache: `vendor/bin/phpstan clear-result-cache`

**Comment by str** [comment]
- phpstan clear-result-cache # crashes, same error
- commenting the include
- phpstan clear-result-cache # runs fine
- phpstan analyze # runs fine, 

```
Note: Using configuration file /home/str/public_html/gemba360/dashboard/phpstan.neon.
 1463/1463 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
....
[ERROR] Found 6955 errors
```
- removing the comment / re-eanbling larastan
- phpstan analyze # crashes, ame error
- compltely removing tmpDir
- phpstan analyze # crashes, ame error

**Comment by str** [comment]
I think I fund the issue,  Laravel is a subfolder of my project.  We have other files and libraries in the parent folder. 

- If I run phpstan from the laravel folder, it works
- If I run phpstan from the parent folder, I get the error described in the issue.

**Comment by szepeviktor** [comment]
> If I run phpstan from the laravel folder, it works

This is expected. We use `getcwd()`.

**Comment by szepeviktor** [comment]
Could you share a tiny overview of your folder structure?

**Comment by str** [comment]
Let me try to describe the main structure:


```
### tiny overview of project folder structure
- /  # root project, 
    -/.vscode/
    -/laravel/ # standard laravel
        -/app/
        -/vendor/
            -/vendor/nunomaduro/larastan/
            -/autoloader.php
        -/storage/
            -/phpstan/ # phpstan cache    
        -/composer.json
        -/composer.lock
        -/artisan
    -/src/ <- most project code
        -/Model
            -/CustomModel.php extends Illuminate\Database\Eloquent\Model
    -/other-legacy-folders/

    -/l.php # custom laravel loader/front-controller
    -/.htaccess
    -/phpstan.neon # includes: ./laravel/vendor/nunomaduro/larastan/extension.neon
    -/phpcs.xml
```
`phpstan.neon` and `phpcs.xml` are at the root folder, not laravel, because that's what we open in the IDE to include legacy code

```
###  the file at laravel/composer.json
# [..]
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            # [...]
            "CustomNameSpace\\": "../src/" # how src file in larvel's parent folder is loaded
        }
    },
```

Let me know if this helps you picture the project structure

**Comment by szepeviktor** [comment]
I've never seen something like a `CustomModel` outside `app/Models/`.
What made you choose this structure?

Package for Laravel have custom code in `src/` but they do not have an application.

**Comment by str** [comment]
>  What made you choose this structure?

legacy code,  we started migrating old PHP4 code to clasess, then to namespaces, then to autoloader, and then as Laravel models.  "One day" we will have time to migrate from src/ to laravel/app/  but it is low priority

**Comment by szepeviktor** [comment]
It is very commendable to perform static analysis on that code.

**Comment by str** [comment]
That's why I'm trying my best to make this work

**Comment by canvural** [comment]
>   If I run phpstan from the laravel folder, it works

Please do that. I don't know how we can solve this otherwise.

**Comment by str** [comment]
I cannot run phpstan from the laravel folder, as I'm not the one running phpstan, but the IDE/vscode.
