### ISSUE TITLE
`LazyCollection`'s `each` returns false positive

### ISSUE THREAD

**Issue by LucaPuddu** [nunomaduro/larastan#1323]
- Larastan Version: v2.1.12
- Laravel Version: v9.22.1
- `--level` used: 9

### Description
```
Parameter #1 $callback of method Illuminate\Support\LazyCollection<(int|string),mixed>::each() expects callable(mixed, (int|string)): mixed, Closure(App\Models\Category): void given.
```

### Laravel code where the issue was found
```php
Category::query()
    ->lazy()
    ->each(function (Category $category) use ($categories) {
        ...
    });
```
If I remove `->lazy()`, it behaves as expected instead

**Comment by canvural** [comment]
Fixed by https://github.com/nunomaduro/larastan/commit/c77dcc395e71d0e0c16c8882a71259e7022a5b4b Thanks
