### ISSUE TITLE
Adding static methods on facades through macros causing error

### ISSUE THREAD

**Issue by jnoordsij** [nunomaduro/larastan#1324]
- Larastan Version: 2.1.12
- `--level` used: 4
- MWE with failing test: https://github.com/jnoordsij/laravel/tree/larastan-mwe

### Description
As of version 2.1.12, I suddenly got several `Call to an undefined static method Illuminate\Support\Facades\Route::<macro>` errors from within my app code. In my case they originated from using `Route::crud` from the Laravel Backpack package (see https://github.com/Laravel-Backpack/CRUD/blob/main/src/macros.php), but I found that any method added as macro to the `Route` facade triggers this message (see also MWE).

Note there are no errors on 2.1.11 (and earlier versions). I suspect https://github.com/nunomaduro/larastan/pull/1295 might have caused this problem.

### Laravel code where the issue was found

See also the MWE listed above.
```php
Route::macro('test', function () {} );
Route::test();
```

**Comment by szepeviktor** [comment]
Hello Jesper! 👋🏻 
Thank you for your report.

Could it be the duplicate of #1315?

**Comment by jnoordsij** [comment]
Yeah, it looks like that's the same problem. I'll close this in favor of #1315 and will refer to my MWE there for possible easier debugging. Thanks!
