### ISSUE TITLE
Configuration file for users

### ISSUE THREAD

**Issue by ghost** [nunomaduro/larastan#134]
I would like to make a suggestion about a generated larastan configuration file. Even if it's just an idea, the configuration file could contain the following:

- your preferred error format,
- the paths that should be tested,
- the rule level that the user prefers,
- possibly the memory limit set by the user,
- if he likes the progress bar or just want to see the results,

My thought behind this idea is just to use the 'php artisan code:analyse' command instead of attaching several sub commands at the end.

That configuration file should be then, in the usually laravel structure for configuration files.

**Comment by ondrejmirtes** [comment]
If you exclude the memory limit (you can set that globally in PHP) and the progress bar, the reset can be set in phpstan.neon file (that is autodiscovered if it's in the same directory).

**Comment by nunomaduro** [comment]
I think it’s good a idea. Was already in my plans actually.

**Comment by ondrejmirtes** [comment]
I worry it'd be confusing to let people use both phpstan.neon and "larastan configuration". Since these settings are all general PHPStan-specific (and not anything related to Laravel), I don't think it would bring much value here.

**Comment by nunomaduro** [comment]
I will be busy this month ( again ), I will get back to you before
implementing this!

**Comment by ondrejmirtes** [comment]
👍 😊

**Comment by hartman** [comment]
If any Larastan specific config is needed, I think it would be best if it could be added to the phpstan.neon file as some sort of plugin specific annotation. Similar to how [laravel adds laravel specific stuff in composer.json.](https://laravel.com/docs/5.7/packages#package-discovery)

**Comment by johanvanhelden** [comment]
This PR should add this functionality. It allows you to simply define a custom phpstan config file and simply run `artisan code:analyse`

https://github.com/nunomaduro/larastan/pull/178/files
