### ISSUE TITLE
Models: Access to an undefined property

### ISSUE THREAD

**Issue by tillkruss** [nunomaduro/larastan#1342]
I find myself doing this a lot. What's the recommended approach to not having to ignore these?

<img width="790" alt="Screen Shot 2022-08-25 at 9 45 11 AM" src="https://user-images.githubusercontent.com/665029/186723208-2fd413c0-961f-4a62-b2f5-27b8ec005371.png">

**Comment by szepeviktor** [comment]
There are a couple of ways to discover PHPStan these properties.

e.g. The `@property` tag in top of the class declaration.

Could you describe one? Where it comes from?

**Comment by szepeviktor** [comment]
Please see  #175
and https://github.com/nunomaduro/larastan/issues/384#issuecomment-666344851

**Comment by tillkruss** [comment]
I'll got with the `@property` for the classes. Thank you.

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by canvural** [comment]
Normally you shouldn't need @property

Please put some code examples where these errors happens.

For Nova, you should put `@mixin YourModel` to your Nova resource class.

**Comment by tillkruss** [comment]
For Nova, I didn't like the `@mixin`, but type hinting works.

```diff
- URL::make('Stripe Id', fn () => "https://dashboard.stripe.com/subscriptions/{$this->stripe_id}")
+ URL::make('Stripe Id', fn (Model $subscription) => "https://dashboard.stripe.com/subscriptions/{$subscription->stripe_id}")
    ->textAlign('left')
    ->sortable()
    ->showOnPreview()
    ->displayUsing(fn (Model $subscription) => $subscription->stripe_id),
```

**Comment by tillkruss** [comment]
However for Eloquent `Model` classes, I need to add `@property` for relationships:

```php
namespace App\Models;

/**
 * @property \App\Models\Company $company
 * @property \Illuminate\Database\Eloquent\Collection $licenses
 * @property \Illuminate\Database\Eloquent\Collection $subscriptions
 */
class Customer extends Model
{
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function subscriptions()
    {
        return $this->hasMany(Subscription::class);
    }

    public function licenses()
    {
        return $this->hasManyThrough(License::class, Subscription::class);
    }
}
```

**Comment by szepeviktor** [comment]
@tillkruss Try this.

```php
    public function subscriptions() : HasMany
    {
        return $this->hasMany(Subscription::class);
    }
```

See our tests: https://github.com/nunomaduro/larastan/blob/22e68b3f257eb10886c89e05a04f23aa1f480835/tests/Application/app/Group.php#L16

**Comment by canvural** [comment]
Yes, for relationships to be recognized you'd need to add return typehints for your relationships.

If you don't want to add them at least you should update your PHPDocs to include the generic types for the collection: `@property \Illuminate\Database\Eloquent\Collection<int, \App\Models\Subscription> $subscriptions`
