### ISSUE TITLE
Underlying Query/Builder doesn't get resolved when using Eloquent/Builder

### ISSUE THREAD

**Issue by jazerix** [nunomaduro/larastan#1346]
- Larastan Version: 2.1.12
- `--level` used: 6

### Description

Hi,  I currently have a file that looks like so:

```php
use Illuminate\Database\Eloquent\Builder;

/**
 * @template TModel of \Illuminate\Database\Eloquent\Model
 */
class DailyQuery
{
    /**
     * @var Builder<TModel>
     */
    private Builder $query;

    ...
    
    public function daily(Carbon $start, Carbon $end) : DailyResults
    {
        $start = $start->startOfDay();
        $end = $end->endOfDay();
        $occurrencesPerDay = $this->query
            ->select($this->selection())
            ->whereBetween("{$this->query->getQuery()->from}.$this->column", [$start, $end])
            ->groupBy('date')
            ->orderBy('date')
            ->pluck('count', 'date');

        return new DailyResults($this->fillGaps($occurrencesPerDay, $start, $end));
    }
}
```

And I'm getting the error:
>  Call to an undefined method Illuminate\Database\Eloquent\Builder<TModel of Illuminate\Database\Eloquent\Model>::select().

I can remove the `->select(...)`, and it will instead complain that `whereBetween(...)` is undefined. I've gone through many issues here, and I'm uncertain what I'm doing wrong.

From my understanding, Laravel extends the `Query/Builder` using the mixin annotation, so the methods should be available.

You can see the entirety of the file here: https://github.com/SDU-SW-Engineering/ScalableTeaching/blob/admin-changes/domain/Analytics/DailyResults/DailyQuery.php

**Comment by szepeviktor** [comment]
Hello!!
AFAIK `Builder` was designed to work in a `Model`.
I think you are better off with another Laravel feature that integrates your daily query with models.
(it could be that no one will agree with me and will give you a stone-cold technical solution)

**Comment by jazerix** [comment]
Thanks for your comment @szepeviktor! I see where you're coming from. It seems counterintuitive that Larastan should be the limiting factor, and I shouldn't be allowed to do the above, as it's fully functional within Laravel. 

I know much can be done through macros. Unfortunately, I haven't found a way to do the above in a macro without making them only locally available.

**Comment by xwillq** [comment]
Adding `@mixin \Illuminate\Database\Query\Builder` to the stub of Eloquent builder solved the issue for me. Could it be than PHPStan reads docblocks only from stubs, if they are provided, and completely ignores docblocks from source code?

**Comment by canvural** [comment]
This is fixed now.
