### ISSUE TITLE
Larastan don't recognize scopes in eager loading

### ISSUE THREAD

**Issue by jva91** [nunomaduro/larastan#1349]
- Larastan Version: 1.0.3
- `--level` used: 5

### Description
Larastan don't recognize scopes in eager loading. 

### Laravel code where the issue was found

```php
$company->load(
        [
            'custom_filters' => function (\Illuminate\Database\Eloquent\Relations\HasMany $query) {
                $query->enabled()
                    ->forMember();
            },
            'custom_filters.translation'
        ]
    );

// company model
public function custom_filters(): HasMany
    {
        return $this->hasMany(CustomFilter::class);
    }
```

Message from larastan
 274    Call to an undefined method Illuminate\Database\Eloquent\Relations\HasMany::enabled().

Is there a way to let Larastan understand this construction?

**Comment by canvural** [comment]
Hi, this is a limitation/bug of PHPStan. Subscribe to https://github.com/nunomaduro/larastan/issues/1110 for further updates on this.

For now maybe you can try to write 
```php
/** @var \Illuminate\Database\Eloquent\Relations\HasMany<CustomFilter> $query */
```

inside the eager load closure.
