### ISSUE TITLE
Don't report `Dynamic call to static method` on macros

### ISSUE THREAD

**Issue by xwillq** [nunomaduro/larastan#1350]
- Larastan Version: 2.1.12
- `--level` used: 9

### Description
Laravel supports calling the same macro as both static and regular method, so this is a false-positive.

#### Registering macro
```php
Request::macro('to_object', fn (string $class_name) => new $class_name($this->all()));
```
#### Using macro
```php
public function test(TestRequest $request)
{
    $request->to_object(Test::class);
}
```
#### Error
```
Dynamic call to static method App\Http\Requests\TestRequest::to_object().
```

**Comment by canvural** [comment]
Are you also using `phpstan-strict-rules`?

**Comment by xwillq** [comment]
Yes

**Comment by canvural** [comment]
Then this is a know issue. Please subscribe to [this issue](https://github.com/phpstan/phpstan-strict-rules/issues/140) for further updates.
