### ISSUE TITLE
PHPStan 1.8.3 breaks our test

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1357]
### Description

Please see https://github.com/nunomaduro/larastan/runs/8146438432?check_suite_focus=true

`non-falsy-string` ✨

**Comment by szepeviktor** [comment]
and the nightly cron job: https://github.com/nunomaduro/larastan/runs/8147274082?check_suite_focus=true

**Comment by canvural** [comment]
Fixed. Thanks.

**Comment by szepeviktor** [comment]
Now older PHPStan does not like `non-falsy-string`

Will we raise its version contstrain to `^1.8.3` ?
