### ISSUE TITLE
Call to an undefined method Illuminate\Contracts\Routing\ResponseFactory|Illuminate\Http\Response::json()

### ISSUE THREAD

**Issue by lasselehtinen** [nunomaduro/larastan#136]
- Larastan Version: 0.2.9
- `--level` used: max

### Description:
This at least on Laravel 5.7.1. False positive I assume.

### Laravel code where the issue was found:
`return response()->json(['message' => 'foobar']);`

**Comment by nunomaduro** [comment]
@mfn This issue got addressed on the version `v0.2.11`. Can you test it?

**Comment by nunomaduro** [comment]
@lasselehtinen This issue got addressed on the version `v0.2.11`. Can you test it?

**Comment by hartman** [comment]
This improved usage of response significantly for me, but I then ran into a problem with the phpdoc of Lumen's ResponseFactory being incorrect.
I have submitted https://github.com/laravel/lumen-framework/pull/811

**Comment by hartman** [comment]
For future reference the commit was https://github.com/nunomaduro/larastan/commit/a434de96df8d15fea85f8e2240265d2c191bcd90
