### ISSUE TITLE
 Parameter #1  of with() expects array<int|string, Closure|string> error

### ISSUE THREAD

**Issue by ariaieboy** [nunomaduro/larastan#1362]
- Larastan Version: 9.27.0
- `--level` used: 8
- Pull request with failing test:
 - 
### Description

according to laravel framework doc this is a valid code :
```php
$books = Book::with([
    'author' => [
        'contacts',
        'publisher',
    ],
])->get();
```
but larastan throw error :
```
 Parameter #1 $relations of static method Illuminate\Database\Eloquent\Model::with() expects array<int|string, Closure|string>|string, ****** given.
```
### Laravel code where the issue was found

```php
    /**
     * Begin querying a model with eager loading.
     *
     * @param  array|string  $relations
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function with($relations)
    {
        return static::query()->with(
            is_string($relations) ? func_get_args() : $relations
        );
    }
```

**Comment by szepeviktor** [comment]
Hello @ariaieboy!

Please try using variadic parameters.

(my personal stuff) You are very brave to enter `func_get_args` into your computer :)

**Comment by ariaieboy** [comment]
> Hello @ariaieboy!
> 
> Please try using a variadic method.
> 
> (my personal stuff) You are very brave to enter `func_get_args` into your computer :)

the `func_get_args()` has been used in the laravel core that with method is an internal function in laravel.

**Comment by szepeviktor** [comment]
I see!

**Comment by szepeviktor** [comment]
```php
$books = Book::with([
    'author' => 'contacts',
])->get();
```

I suspect that would not cause a type error but would exclude `publisher`.

**Comment by szepeviktor** [comment]
This could be fixed by adding array type here.

https://github.com/nunomaduro/larastan/blob/99861c5c43b5114e89be7fec84f37e01d993c908/stubs/Model.stub#L37

`string|array<int|string, (\Closure)|string|array<int|string, string>>`
