### ISSUE TITLE
not detecting livewire computed property

### ISSUE THREAD

**Issue by ariaieboy** [nunomaduro/larastan#1364]
- Larastan Version: 9.27.0
- `--level` used: 8
- Pull request with failing test:

### Description

in livewire we have [computed properties](https://laravel-livewire.com/docs/2.x/computed-properties) 
it's like this :
```php
class FooComponent extends Component
{
    // Computed Property
    public function getFooProperty()
    {
        return 'foo';
    }

```
and it can be accessible like this in view or the component class itself:
```php
<div>
    <span>{{ $this->foo }}</span>
</div>
```

it is kinda like old laravel Accessors :
```php
/**
 * Get the user's full name.
 *
 * @return string
 */
public function getFullNameAttribute()
{
    return "{$this->first_name} {$this->last_name}";
}
```

I don't know that larastan supports livewire or not but having this covered is a good addition to larastan.

**Comment by szepeviktor** [comment]
Thank you for your report.

It seem like the implementation is a copy-paste job. https://github.com/nunomaduro/larastan/blob/fa598dbc2b319673857ee17f6afe1aed6564b505/src/Properties/ModelAccessorExtension.php#L50

**Comment by canvural** [comment]
There are no plans to support Livewire currently.

**Comment by szepeviktor** [comment]
May I think about `szepeviktor/larastan-livewire` ?

**Comment by canvural** [comment]
Of course!

**Comment by RobertCordes** [comment]
I have created https://github.com/Diverently/phpstan-livewire for this. It's my first — and probably last 😅 — PHPStan extension, so any help is highly appreciated! But for now it got rid of those pesky warnings for me.

**Comment by RobertCordes** [comment]
I have created https://github.com/Diverently/phpstan-livewire for this. It's my first — and probably last 😅 — PHPStan extension, so any help is highly appreciated! But for now it got rid of those pesky warnings for me.
