### ISSUE TITLE
Missing PHP generics for classes extending Laravel\Nova\Resource

### ISSUE THREAD

**Issue by BrekiTomasson** [nunomaduro/larastan#1371]
- Larastan Version: 2.2.0
- `--level` used: 8
- Pull request with failing test: N/A

### Description

All of my Laravel Nova Resources are getting this warning on the class definition. I'm not entirely sure what it's wanting me to do here?

**Comment by szepeviktor** [comment]
Hello @BrekiTomasson! 👋🏻 
Thank you for report.

What is your wish? Adding PHP generics or silencing this error?

**Comment by szepeviktor** [comment]
(_choose the first!_)

**Comment by BrekiTomasson** [comment]
Well, most of all; I'm trying to understand what the warning is so that I can put the right DocBlock in there. I don't want to silence the warning, though, I want to rewrite my code in whatever way is needed so that it doesn't appear. ;)

**Comment by szepeviktor** [comment]
Please see the closed source `Laravel\Nova\Resource` class' docblock and add [PHP generics](https://phpstan.org/blog/generics-in-php-using-phpdocs) to your code.

```php
/**
 * @extends Laravel\Nova\Resource<YOUR-MODEL>
 */
class BlogEntry
{
```

**Comment by BrekiTomasson** [comment]
Ah, that makes sense! Thanks for the help!

Do I still need to `@mixin \MY\Model` for it to understand `$this->property` references to the underlying model or does `@extends` cover that as well?

**Comment by szepeviktor** [comment]
I do not know that.

**Comment by canvural** [comment]
You need to specify the model the resource is created for.

Read more [here](https://phpstan.org/blog/generics-by-examples#specify-template-type-variable-of-a-generic-interface-or-class-in-a-parameter-type)  and [here](https://phpstan.org/blog/generics-in-php-using-phpdocs).
