### ISSUE TITLE
Access to undefined constant static(HelloWorld)::FIELDS

### ISSUE THREAD

**Issue by renakdup** [nunomaduro/larastan#1374]
- Larastan Version: 1.8.2
- PHP: 7.3
- `--level` used:1
- Pull request with failing test:

### Description
I got a strange error `Access to undefined constant static(HelloWorld)::FIELDS`. This const must be defined in a child class which extended abstract class.

### Runned code

https://phpstan.org/r/57cbbd29-52e1-4ea6-9b41-b84e85e8f68c 

```php
<?php declare(strict_types = 1);

abstract class HelloWorld
{
	/**
     * @return array
     */
    private static function getFields() : array
    {
        if (isset(static::$fields)) {
            return static::$fields;
        } elseif (defined('static::FIELDS')) {
            $aOutput = explode(',', static::FIELDS);

            return $aOutput;
        } else {
            return [];
        }
    }
}
```

**Comment by szepeviktor** [comment]
Hello! 👋🏻 Could you try this? `} elseif (defined(__NAMESPACE__ . '\\static::FIELDS')) {`

**Comment by canvural** [comment]
Please report it to PHPStan.
