### ISSUE TITLE
Model::replicate() returns dynamic type

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#138]
https://github.com/laravel/framework/blob/b3f583cd5efbc9e1b9482b00a7c22b00324e936e/src/Illuminate/Database/Eloquent/Model.php#L1143-L1166

I think `new static()` returns an instance of the current class but its PHPDoc says `@return \Illuminate\Database\Eloquent\Model`

Could Larastan calculate the actual type?

It produces something like

> Call to an undefined method Illuminate\Database\Eloquent\Model::translations().

on level 2.

**Comment by nunomaduro** [comment]
Yes it’s possible. This is a false positive.

**Comment by nunomaduro** [comment]
May sound stupid (it's morning in Paris), but shouldn't that function `@return static`?

**Comment by szepeviktor** [comment]
> May sound stupid (it's morning in Paris), but shouldn't that function `@return static`?

It makes Larastan happy.
Let's see how about Laravel developers: https://github.com/laravel/framework/pull/25617

**Comment by szepeviktor** [comment]
@nunomaduro What to do with this? Wait for the next 5.7 minor release?

**Comment by nunomaduro** [comment]
Yeah. The next minor release should fix it.
