### ISSUE TITLE
Missing `Collection::mapWithKeys` support

### ISSUE THREAD

**Issue by lucasvdh** [nunomaduro/larastan#1380]
- Larastan Version: `1.0.3`

### Description
Would be nice if PHPStan could resolve the new type of a Collection when I call a `mapWithKeys` function on it.

I'm currently using this stub as a workaround:
```php
/**
 * @template TReturnIndex of array-key
 * @template TReturnValue
 * @param callable(TValue, TKey): array<TReturnIndex, TReturnValue> $callable
 * @return static<TReturnIndex, TReturnValue>
 */
public function mapWithKeys($callable) {}
```

I realize that I'm using an older version of the package, so the latest version might already support this but I've not been able to find the method `mapWithKeys` in any version.

**Comment by mad-briller** [comment]
mapWithKeys is implemented here:

https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L40

and it simply defers to the laravel provided templates:

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Collection.php#L765

which version of Laravel are you using? if it's not 9.x then you won't gain the benefit of the generics unfortunately and you will need to use a stub file
i imagine Larastan doesn't want to re-implement any generics supported by Laravel in it's latest version, as that means duplicating the definitions and the maintenance that comes with that.

**Comment by szepeviktor** [comment]
> Larastan Version: `1.0.3`

It will be Laravel 8.

**Comment by lucasvdh** [comment]
Thank you for your reply.
