### ISSUE TITLE
Console Command

### ISSUE THREAD

**Issue by Skullbock** [nunomaduro/larastan#1381]
Hi, in my local projects i created a Laravel command to run Larastan as we run the test suites:

`php artisan analyse`

It's basically a super simplified version of the standard Laravel `php artisan test` command.
Would it be interesting as a PR to the project?

**Comment by mad-briller** [comment]
could this result in the application being booted twice? once by artisan and once by larastan?

**Comment by Skullbock** [comment]
That's a good question actually.
I don't see any issue while running the command, is there something i can do to check this out?

**Comment by canvural** [comment]
Hi,

In the early versions of Larastan there was actually an Artisan command `php artisan code:analyse` But it was causing too many issues later on, so we removed it.

As Larastan is just a PHPStan extension, I don't see a need for a command.

Thank you.

**Comment by Skullbock** [comment]
Ok, thanks for the feedback!
