### ISSUE TITLE
Larastan is not auto-registering service providers in packages.

### ISSUE THREAD

**Issue by mad-briller** [nunomaduro/larastan#1384]
- Larastan Version: v2.2.0

### Description

Upon investigation i found the `getVendorDir` static method here:
https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php#L39

When i do 

```
    /**
     * Creates an application and registers service providers found.
     *
     * @return \Illuminate\Contracts\Foundation\Application
     *
     * @throws \ReflectionException
     */
    public static function resolve(): Application
    {
        $app = (new self)->createApplication();

        $vendorDir = self::getVendorDir() ?? getcwd().DIRECTORY_SEPARATOR.'vendor';
        $composerConfigPath = dirname($vendorDir).DIRECTORY_SEPARATOR.'composer.json';

        var_dump($composerConfigPath, $app->basePath());
        // ...
```

i get this output:

```
string(101) "phar:///home/brad/code/esb-workspace/esb-foundation/vendor/phpstan/phpstan/phpstan.phar/composer.json"
string(84) "/home/brad/code/esb-workspace/esb-foundation/vendor/orchestra/testbench-core/laravel"
```

it appears that `getVendorDir` is returning the vendor dir of the PHPStan phar, rather than the local project. This causes larastan to read the `composer.json` from there, and fail to auto-register service providers.
This package used to work in the past (i'm not sure what version of phpstan / larastan) so along the way a change to phpstan / larastan has caused this to happen.

I suspect this is the root of my [view-string issue](https://github.com/nunomaduro/larastan/issues/1355) i posted a while ago.

Not sure how you'd go about fixing this as i'm not super familiar with the bootstrapping of larastan (yet)

**Comment by mad-briller** [comment]
removing the call to `getVendorDir` and using the `getCwd` path instead makes the auto-discovery work again, but assuming that the user will always run `phpstan` from the root of their project is probably less than ideal.

**Comment by szepeviktor** [comment]
Hello Brad!

`getVendorDir` locates `Composer\Autoload\ClassLoader` class.
Could it be that PHPStan PHAR file includes this class?? 🤯

**Comment by canvural** [comment]
Just an idea, I added a ComposerHelper class to PHPStan a while back: https://github.com/phpstan/phpstan-src/blob/5cf39bc960b4b9dbc01be6906cbc1d71285118f7/src/Internal/ComposerHelper.php

Could we use the same logic here also?

**Comment by mad-briller** [comment]
i'm guessing it does, and this is a fairly new addition too. I'm not very familiar with PHARs at all so i can't comment on how / why that might be the case, but it seems that this method of locating the "root" folder is incompatible with modern phpstan.

I suspect several of the recent larastan issues raised to do with macros etc. are likely caused by this issue aswell. As larastan not seeing my collection macros is what made me investigate this in the first place.

**Comment by szepeviktor** [comment]
> Just an idea, I added a ComposerHelper class to PHPStan

Where does `$root` come from?
All those helpers need that.

**Comment by canvural** [comment]
> > Just an idea, I added a ComposerHelper class to PHPStan
> 
> Where does `$root` come from? All those helpers need that.

`$root` is current working directory. We can get that from PHPStan config.

**Comment by szepeviktor** [comment]
@mad-briller Could you vardump this line?
https://github.com/nunomaduro/larastan/blob/dd1087d0cc0b7fcd5fd652737b5ec4c0d1e00272/src/ApplicationResolver.php#L63

**Comment by mad-briller** [comment]
@szepeviktor of course:

```
string(119) "phar:///home/brad/code/esb-workspace/esb-foundation/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php"
```

**Comment by szepeviktor** [comment]
> phpstan.phar/vendor/composer/ClassLoader.php

Oh noooooooooooooooooooooooooooooooooooooooooo!
PHPStan really contains that class.

**Comment by mad-briller** [comment]
yeah it does: 

```
/home/brad/code/esb-workspace/esb-foundation/vendor/composer/ClassLoader.php
```

**Comment by szepeviktor** [comment]
PHPStans work the very same way
https://github.com/phpstan/phpstan-src/blob/71c7bf889fbf0ef3b6ef28841eb97c43ed3b30b0/src/Testing/TestCaseSourceLocatorFactory.php#L40

**Comment by szepeviktor** [comment]
Could you please help me and dump this array `var_dump(ClassLoader::getRegisteredLoaders())` ?

**Comment by mad-briller** [comment]
i have a working "fix" but i'm not confident it will work in all cases, i'll post a pr up in a second and then get you the var_dump of that

**Comment by mad-briller** [comment]
There was _alot_ of output so i var_dump'd this instead for brevity sake:

```
        var_dump(
            array_map(fn ($loader) => get_class($loader), ClassLoader::getRegisteredLoaders())
        );
```

and i got this:

```
array(2) {
  ["phar:///home/brad/code/esb-workspace/esb-foundation/vendor/phpstan/phpstan/phpstan.phar/vendor"]=>
  string(29) "Composer\Autoload\ClassLoader"
  ["/home/brad/code/esb-workspace/esb-foundation/vendor"]=>
  string(29) "Composer\Autoload\ClassLoader"
}
```

**Comment by szepeviktor** [comment]
Thank you!!

**Comment by szepeviktor** [comment]
@mad-briller How about finding ClassLoader by filtering `ClassLoader::getRegisteredLoaders()` throwing away `^phar:`?

**Comment by mad-briller** [comment]
this does not happen in 2.1.12 of larastan, so something between 2.1 and 2.2 has caused this:
https://github.com/nunomaduro/larastan/issues/1387?notification_referrer_id=NT_kwDOAa_w5LM0NTI4MzY4NTA4OjI4MzA3Njg0#issuecomment-1266548993

**Comment by mad-briller** [comment]
upon investigation it seems that `getVendorDir` did not exist in `2.1.12` so it was the addition of that method that broke it for package scenarios;

```
    /**
     * Creates an application and registers service providers found.
     *
     * @return \Illuminate\Contracts\Foundation\Application
     *
     * @throws \ReflectionException
     */
    public static function resolve(): Application
    {
        $app = (new self)->createApplication();

        $composerFile = getcwd().DIRECTORY_SEPARATOR.'composer.json';

        if (file_exists($composerFile)) {

```

**Comment by canvural** [comment]
I'm really confused with all this stuff 😅 

Doesn't `orchestra/testbench` handle all of this [here](https://github.com/nunomaduro/larastan/blob/a92da30117ffb132dba8a64edc519b0247a54d82/src/ApplicationResolver.php#L37) for us?

**Comment by canvural** [comment]
@crynobone Is there a way to get the package root directory from Testbench?

Or another idea: Maybe we can do `$app->basePath()` and go up 3 directories 😄 Cause `basePath()` would give `/foo/bar/vendor/orchestra/testbench-core/laravel` and we can get `/foo/bar/vendor` from there. But don't know if it's reliable.

**Comment by crynobone** [comment]
You should be able to run 

```bash
./vendor/bin/testbench package:discover
```
And this would prepare auto-discovery for `/foo/bar/vendor/orchestra/testbench-core/laravel`

https://user-images.githubusercontent.com/172966/193849911-41161af1-deaf-4c70-a6c0-f6b662ea09f3.mp4

**Comment by canvural** [comment]
@crynobone We are trying to find the service provider of the root package and register it. 

In the Testbench documentation it's stated that

> Be aware that root package doesn't automate using package discovery and you need to define it using [Package Service Providers](https://packages.tools/testbench/basic/testcase.html#package-service-providers)

Do you have any advice for that? Our current solution is really hacky and involves reading the `composer.json` getting the autoloaders, creating class maps from that, then trying to find the service providers 🤢

**Comment by crynobone** [comment]
My response was based on https://packages.tools/testbench/commander.html

Not running tests on Testbench.

**Comment by crynobone** [comment]
See BenSampo/laravel-enum#282 for example.

**Comment by canvural** [comment]
> See [BenSampo/laravel-enum#282](https://github.com/BenSampo/laravel-enum/pull/282) for example.

So are you saying that change in the package's `composer.json` is enough? And in Larastan we can just create the application like we do [here](https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php#L37), and that's all?

**Comment by canvural** [comment]
@mad-briller Can you try the https://github.com/nunomaduro/larastan/tree/fix-application-resolver branch?

**Comment by mad-briller** [comment]
@canvural i tried it and got this:

```
=> php vendor/bin/phpstan
Note: Using configuration file /home/brad/code/esb-workspace/esb-foundation/phpstan.neon.dist.
Error thrown in /home/brad/code/esb-workspace/esb-foundation/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 32 while loading bootstrap file /home/brad/code/esb-workspace/esb-foundation/vendor/nunomaduro/larastan/bootstrap.php: Typed static property NunoMaduro\Larastan\ApplicationResolver::$bootedApp must not be accessed before initialization
```

this needs to be changed:

```
   public static Application $bootedApp;
```

to this:

```
   public static ?Application $bootedApp = null;
```

**Comment by mad-briller** [comment]
if i make that change though i get this:

```
=> php vendor/bin/phpstan
Note: Using configuration file /home/brad/code/esb-workspace/esb-foundation/phpstan.neon.dist.
sh: 1: /home/brad/code/esb-workspace/esb-foundation/vendor/orchestra/testbench-core/laravel/vendor/bin/testbench: not found
```

**Comment by canvural** [comment]
@mad-briller We made some more improvements in the `master` branch. Can you try the latest `master`?

**Comment by mad-briller** [comment]
@canvural that's resolved it for me, my service providers are ran and macros are detected an analysed correctly

great work, thanks for your time on this
