### ISSUE TITLE
Do not implement ExtendedMethodReflection in EloquentBuilderMethodReflection

### ISSUE THREAD

**Issue by ondrejmirtes** [nunomaduro/larastan#1386]
I'd like to resurface my concern here :) We've finally taken advantage of ExtendedMethodReflection and added a new method there in https://github.com/phpstan/phpstan-src/pull/1317. So when PHPStan 1.9.0 is shipped, Larastan as in the current state is not going to be compatible with it.

Context: https://github.com/nunomaduro/larastan/commit/d233e1c3efe5de35430f5b1b1ea3a5a545e4c966

**Comment by szepeviktor** [comment]
Thank you.
We *usually* do not kill the messenger :)

**Comment by canvural** [comment]
@ondrejmirtes Will there still be new 1.8.x releases or the next release is 1.9.0?

**Comment by ondrejmirtes** [comment]
There's gonna be PHPStan 1.8.7 :)

**Comment by canvural** [comment]
Ok, thanks!
