### ISSUE TITLE
VSCode extension for larastan?

### ISSUE THREAD

**Issue by skyrpex** [nunomaduro/larastan#139]
Is something working on a VSCode extension for larastan? There's one for [phpstan](https://github.com/calvinbaart/vscode-phpstan), so creating a new one for this project could be fairly easy.

If no one is working on it, maybe I could give it a try in a near future.

**Comment by ondrejmirtes** [comment]
You can use the one for PHPStan and just include larastan's extension.neon into your configuration.

**Comment by skyrpex** [comment]
Didn't know about that! That's awesome, thanks.

For those interested, you just need to create a `phpstan.neon` file in your project root with this content:

```yaml
includes:
    - vendor/nunomaduro/larastan/extension.neon
```
