### ISSUE TITLE
False positives from NoUnnecessaryCollectionCallRule

### ISSUE THREAD

**Issue by mad-briller** [nunomaduro/larastan#1397]
- Larastan Version: dev-master
- `--level` used: 8
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/1398

### Description

Since updating to `dev-master` to try out the recent fix for packages, i encountered some false positives with this rule, possibly related to this recent merged pr:
https://github.com/nunomaduro/larastan/pull/1375

**Comment by canvural** [comment]
I reverted that PR. Thanks.
