### ISSUE TITLE
extra newlines in jenkins

### ISSUE THREAD

**Issue by corbosman** [nunomaduro/larastan#142]
- Larastan Version: 0.2.10
- `--level` used: any

### Description:

I run larastan as part of my CI flow in Jenkins. There is an annoying issue with larastan compared to running phpstan manually.  Im including a link to a screenshot that shows the issue, first run is larastan, second run is phpstan.  In larastan extra newlines get introduced. 

http://shot.ter.net/img/201809191315-6e572f53592cbb3967d7b9fddaab45b9.png

Any idea what could be causing those?

**Comment by canvural** [comment]
I think with 0.5, this is no longer a problem.
