### ISSUE TITLE
UUID database field with default field name

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1436]
- Larastan Version: 2.2.9
- `--level` used: 8

### Description

```
Access to an undefined property App\Models\User::$uuid.
```
https://github.com/laravel/framework/blob/0702f556f72745f34570fbdfa8e37b8ea0b7ffa5/src/Illuminate/Database/Schema/Blueprint.php#L1245-L1254

### Laravel code where the issue was found

`$table->uuid();` is not recognized
`$table->uuid('someName');` works

https://github.com/szepeviktor/larastan-issue/pull/6/files

**Comment by MJTheOne** [comment]
Laravel 9
PHP 8.2
Larastan 2.4.0

`$table->uuid()` does indeed not work

Changed it to `$table->uuid('uuid')` and the many PHPStan errors are gone
