### ISSUE TITLE
Illuminate\Foundation\Application in Service provider closure type not resolving

### ISSUE THREAD

**Issue by XbNz** [nunomaduro/larastan#1441]
- Larastan Version: 2.2.9
- `--level` used: Max

### Description

Return type of `$app->make(Foo::class)` is not inferred, so PHPStan throws a "mixed given" error

### Laravel code where the issue was found

```php
$this->app->bind(ExampleService::class, function (Application $app) {
      return new ExampleService(
          $app->make(Foo::class),
      );
});

```

**Comment by mad-briller** [comment]
how have i never noticed this is not supported, spent an hour today where i gaslit myself into thinking it was
