### ISSUE TITLE
Getting a false positive on Password facade

### ISSUE THREAD

**Issue by FrancisMawn** [nunomaduro/larastan#1449]
- Larastan Version: 2.2.9
- `--level` used: 4
- Pull request with failing test:

### Description
The Laravel PasswordBroker class exposes a public method `getUser()` which can either return an instance of User or null.
Running Larastan level 4 gives me this error for the following code:

`
If condition is always true.
`

```php
use Illuminate\Support\Facades\Password;

...

// Validate token and its expiry date.
if ($user = Password::getUser($request->only('email'))) {
    $tokenIsValid = Password::tokenExists($user, $token);
}
```

The docblock definition for the `getUser` method on **\Illuminate\Auth\Passwords\PasswordBroker** class seems to be appropriate:
`
@return \Illuminate\Contracts\Auth\CanResetPassword|null
`

**Comment by szepeviktor** [comment]
@FrancisMawn Thank you for your report!
👋🏻 

What is the output of this?
```php
$user = Password::getUser($request->only('email'))
\PHPStan\dumpType($user);
```

**Comment by canvural** [comment]
> The docblock definition for the getUser method on \Illuminate\Auth\Passwords\PasswordBroker class seems to be appropriate:

But the docblock for in the `Password` facade only has `\Illuminate\Contracts\Auth\CanResetPassword`

So please send a  PR to Laravel that fixes the docblock in the `Password` facade.
