### ISSUE TITLE
Class DisbursementReadModel has an uninitialized readonly property $id. Assign it in the constructor.

### ISSUE THREAD

**Issue by asvechkar** [nunomaduro/larastan#1454]
- Larastan Version: 2.2.9
- `--level` used: 5
- Pull request with failing test:

### Description
I found same issue in https://github.com/phpstan/phpstan/issues/7337

But this bug was closed in 1.3.7.

Now I have this error. Pls help.

### Laravel code where the issue was found

```php
final class DisbursementReadModel
{
    public readonly string $id;
    public readonly int $user_id;
    public readonly string $type;
    public readonly string $payload;
    public readonly string $created_at;
    public readonly string $updated_at;
}
```

**Comment by canvural** [comment]
This doesn't seem related to Larastan. Try to produce your issue in https://phpstan.org/try and open an issue there.
