### ISSUE TITLE
Feature request: allow transformation of generic array-syntax in IDE helper docblocks

### ISSUE THREAD

**Issue by jnoordsij** [nunomaduro/larastan#1470]
- Larastan Version: `master`
- `--level` used: max
- Branch with WIP: https://github.com/jnoordsij/larastan/tree/generalise-ide-helper-type-transformer

### Description

In https://github.com/nunomaduro/larastan/pull/479 a resolver was introduced to interpret docblocks like `\Illuminate\Database\Eloquent\Collection|\App\Account[] $accounts` as `\Illuminate\Database\Eloquent\Collection<\App\Account> $accounts`.

It would be useful to also accept another pattern, namely `\Illuminate\Database\Eloquent\Collection|array<\App\Account> $accounts` and convert this. This pattern is the result of auto-correction by [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) using my current ruleset. 

In (https://github.com/jnoordsij/larastan/tree/generalise-ide-helper-type-transformer) I made a first attempt at implementing this, but it currently seems to be resolving incorrectly for some other union types. It also contains tests for both transforms.

**Comment by szepeviktor** [comment]
Hello @jnoordsij! 👋🏻 
The feature in #479 is not the nicest thing in the world.
Using a PHP generics compatible IDE is the sustainable solution.

**Comment by jnoordsij** [comment]
@szepeviktor thanks for your quick reaction!

I totally agree, but looking at https://github.com/barryvdh/laravel-ide-helper/issues/942, it seems like support for that won't land anytime soon, so I was hoping for a workaround.

**Comment by szepeviktor** [comment]
> so I was hoping for a workaround.

You may get it anytime. Here we have a small community.

**Comment by canvural** [comment]
There is no plan to support this. It is a really old syntax. You can use the generic version instead `\Illuminate\Database\Eloquent\Collection<int, \App\Account>`

**Comment by jnoordsij** [comment]
Update for those who find this: https://github.com/barryvdh/laravel-ide-helper/pull/1298 has been merged in the Laravel IDE helper packages, so if you use the `dev-master` version of this package, you can automatically update your docblocks to use the new generic notation.
