### ISSUE TITLE
Illuminate\Config\Repository class dependency causes error

### ISSUE THREAD

**Issue by Nai4rus** [nunomaduro/larastan#1477]
- Larastan Version: 1.0.3
- `--level` used: 6
- Pull request with failing test:

### Description
Hi! I faced this error on my project:
```
Internal error: Internal error: Argument 1 passed to NunoMaduro\Larastan\ReturnTypes\GuardExtension::getAuthModel() must be an instance of Illuminate\Config\Repository, instance of <custom config class> given, called in  
     /application/vendor/nunomaduro/larastan/src/ReturnTypes/GuardExtension.php
```

We are using custom config class with implementing `Illuminate\Contracts\Config\Repository` interface. So, if we change argument typehint from `Illuminate\Config\Repository` to `Illuminate\Contracts\Config\Repository` in `NunoMaduro\Larastan\ReturnTypes\GuardExtension::getAuthModel()`, the error will be fixed.

**Comment by canvural** [comment]
Feel free to send a PR 👍🏽
