### ISSUE TITLE
Call to private method with custom relation

### ISSUE THREAD

**Issue by stein-j** [nunomaduro/larastan#1480]
- Larastan Version: 2.2.9
- `--level` used: 2
- Pull request with failing test:

### Description

Larastan / PHPStan keeps saying private function are being called when it's not the case.
I get this error with all functions on the query build of a relation $model->lines()->_find()_ / _where()_ / _count()_ / _sum()_ / _newQuery()_ / etc.

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------ 
  67     Call to private method find() of parent class Illuminate\Database\Eloquent\Relations\MorphMany<Illuminate\Database\Eloquent\Model>.   
  507    Call to private method whereIn() of parent class Illuminate\Database\Eloquent\Relations\MorphMany<Illuminate\Database\Eloquent\Model>.    
  515    Call to private method whereNull() of parent class Illuminate\Database\Eloquent\Relations\MorphMany<Illuminate\Database\Eloquent\Model>.  
  547    Call to private method orderBy() of parent class Illuminate\Database\Eloquent\Relations\MorphMany<Illuminate\Database\Eloquent\Model>.    
 ------ ------------------------------------------------------------------------------------------------------------------------------------------ 

```

I have a custom relation, it's clearly related with that, the code has been posted in the next section. 

It is important to note, that there is not a single private function in the vendor, here is an example with the `where` function : 

<img width="1078" alt="Screen Shot 2022-12-12 at 16 09 12" src="https://user-images.githubusercontent.com/44996807/207155266-3ffd17ca-90e5-493a-9859-efac3961d55c.png">

### Laravel code where the issue was found

The relation is called as usual, it return the custom relation instead of the prebuilt one :

```php
    public function lines(): MorphManyWithOrder
    {
        return $this->morphManyWithOrder(Line::class, 'lineable')->orderBy('order');
    }
```

The custom relation simply extends to original relation and add extra functions :
```php
<?php

namespace App\Relationships;

use Illuminate\Database\Eloquent\Relations\MorphMany;

class MorphManyWithOrder extends MorphMany
{
    /**
     * Returns the position of the next order position
     *
     * @return int
     */
    public function getNextOrderPosition(): int
    {
        return $this->query->max('order') + 1;
    }

    // Reorder the list from the given array
    public function defineNewOrder(array $orderIds): void
    {
        $order = 0;
        collect($orderIds)->each(function ($id) use (&$order) {
            $query = clone $this->newQuery();
            $query
                ->whereKey($id)
                ->update([
                    'order' => $order++,
                ]);
        });
    }
}

```

There is a trait give access to the function which created an instance of the custom relation:
```php
<?php

namespace App\Traits\Relationships;

trait HasMorphManyWithOrderRelation
{
    /**
     * Define a polymorphic one-to-many relationship.
     *
     * @param  string  $related
     * @param  string  $name
     * @param  string|null  $type
     * @param  string|null  $id
     * @param  string|null  $localKey
     * @return \App\Relationships\MorphManyWithOrder
     */
    public function morphManyWithOrder($related, $name, $type = null, $id = null, $localKey = null)
    {
        $instance = $this->newRelatedInstance($related);

        // Here we will gather up the morph type and ID for the relationship so that we
        // can properly query the intermediate table of a relation. Finally, we will
        // get the table and create the relationship instances for the developers.
        [$type, $id] = $this->getMorphs($name, $type, $id);

        $table = $instance->getTable();

        $localKey = $localKey ?: $this->getKeyName();

        return new \App\Relationships\MorphManyWithOrder($instance->newQuery(), $this, $table.'.'.$type, $table.'.'.$id, $localKey);
    }
}

```

**Comment by szepeviktor** [comment]
Hello @stein-j! 👋🏻 
Thank you for your report.

Please add PHP generics to your relation code.
https://github.com/nunomaduro/larastan/blob/4ec10561ee98e51a7e4f52a0c7c80e19ba7585dd/stubs/HasOneOrMany.stub#L6
and `@return RelationName<Model1, Model2>`

**Comment by canvural** [comment]
Hi,

Yes the error message is little cryptic. And I believe this is somewhat solved in `master` branch.

Anyway, you need to make changes to your code to make it work:

1) `MorphMany` is generic. So you need to either make `MorphManyWithOrder` also generic, or just use `@extends MorphMany<Model>` But in the latter case you will not specific model information. So the former is better. You need to add something like this to top of the class:
```php
/**
 * @template TRelatedModel of \Illuminate\Database\Eloquent\Model
 * @extends MorphMany<TRelatedModel>
 */
```

2) Then the trait method needs to be also generic.
```php
/**
 * @template TRelatedModel
 */
trait HasMorphManyWithOrderRelation
{
    /**
     * Define a polymorphic one-to-many relationship.
     *
     * @param  string  $related
     * @param  string  $name
     * @param  string|null  $type
     * @param  string|null  $id
     * @param  string|null  $localKey
     * @return \App\Relationships\MorphManyWithOrder<TRelatedModel>
     */
    public function morphManyWithOrder($related, $name, $type = null, $id = null, $localKey = null)
    {
        ...
	}
}
```

3) Then when this trait is used, you need to do:
```php
/** @use HasMorphManyWithOrderRelation<self> */
use HasMorphManyWithOrderRelation;
```

Hope this helps.

**Comment by szepeviktor** [comment]
By copying from the above comment you may skip learning PHP generics :(

**Comment by stein-j** [comment]
Thank you @szepeviktor, thank you @canvural. I have managed to fixe the issue, mixed with some reading I have understood what Generics are and how useful they are.

I do have a hard time understanding why in this situation this is needed, because the relation is simply extending the original relation and doesn't depend on the model, which can statically be analyzed without extra PHPComments, PHPStorm correctly identifies it for example.

@szepeviktor I think it's up to the one receiving the answer to decide if they want to understand correctly. In this case, having an example is very useful, I would have never added the comment when calling the trait. Then I can start using it in with more simple parts of my code. Also, because this is publique, it might be helpful for someone else if they find this.
