### ISSUE TITLE
Error with new rule `checkUnusedViews`

### ISSUE THREAD

**Issue by rcerljenko** [nunomaduro/larastan#1487]
- Larastan Version: 2.3.0
- `--level` used: 6

### Description

After updating to v2.3 and enabling rule `checkUnusedViews` this happens:

```
In ViewFileHelper.php line 70:

Undefined array key 1
```

### Laravel code where the issue was found

This is from your code that's reported above:

```php
if (str_contains($view->getPathname(), 'views/vendor')) {
       continue;
 }

$viewName = explode($viewDirectory.'/', $view->getPathname());

yield str_replace(['/', '.blade.php'], ['.', ''], $viewName[1]); // THIS IS LINE 70
```

**Comment by rcerljenko** [comment]
myabe it has something to do with windows - different directory separator  => `DIRECTORY_SEPARATOR` constant

**Comment by rcerljenko** [comment]
yep.. just tried it with that constant and it worked... should i provide a PR for that?

**Comment by canvural** [comment]
> yep.. just tried it with that constant and it worked... should i provide a PR for that?

Yes please.

**Comment by rcerljenko** [comment]
here it is @canvural https://github.com/nunomaduro/larastan/pull/1488

**Comment by canvural** [comment]
Released in https://github.com/nunomaduro/larastan/releases/tag/2.3.1 Thank you
