### ISSUE TITLE
Usage of collect looses shape of arrays

### ISSUE THREAD

**Issue by eithed** [nunomaduro/larastan#1491]
- Larastan Version: 2.3.1
- `--level` used: 7

### Description

While updating some code to use level 7 I've run into issue with array shapes, which got me into a rabbit hole which resulted in following debugging:

```php
<?php

require('vendor/autoload.php');

use Illuminate\Support\Collection;

/** @var array<int,array{value:string,factor:float}> */
$foo = [['value' => 'Yes', 'factor' => 1.0],['value' => 'No', 'factor' => 2.0]];

/**
 * Create a collection from the given value.
 *
 * @template TKey of array-key
 * @template TValue
 *
 * @param  \Illuminate\Contracts\Support\Arrayable<TKey, TValue>|iterable<TKey, TValue>|null  $value
 * @return \Illuminate\Support\Collection<TKey, TValue>
 */
function fcollect($value = null)
{
    return new Collection($value);
}

\PHPStan\dumpType(collect($foo));
\PHPStan\dumpType(fcollect($foo));
```

As fcollect is a copy of collect, I'd expect the dumpType to result in the same, yet following is output:

```
Dumped type: Illuminate\Support\Collection<int, non-empty-array<string,float|string>>                                                                        
Dumped type: Illuminate\Support\Collection<int, array{value: string, factor: float}>  
```

Removing `vendor/nunomaduro/larastan/extension.neon` from phpstan includes brings correct behaviour, which pointed me that the issue was indeed with larastan and indeed debugging the source gives me an insight on how `collect` is being treated and how types are being inferred.

I've tried to tackle this issue myself - I gather that within `determineGenericCollectionTypeFromType` this case passes through all ifs and from
```
return new GenericObjectType(Collection::class, [
            $type->getIterableKeyType()->generalize(GeneralizePrecision::lessSpecific()),
            $type->getIterableValueType()->generalize(GeneralizePrecision::lessSpecific()),
        ]);
```
`array{value: string, factor: float}` will be generalized to less specific value type.

I think that dependent on **something** `$type->getIterableValueType()->generalize(GeneralizePrecision::templateArgument()),` should be used (at least in this case) , but I don't have a clue if Type has the information on what it was parsed from; at least I cannot see it and all my efforts to change this behaviour give me failing tests for `['foo', 'bar', 'baz']` where indeed `Collection<int, string>` should be inferred rather than `Collection{string,string,string}`. Given my current knowledge I don't know if this behaviour is fixable.

Final words - given that the issue is with usage of `collect` and type inferring that phpstan does, replacing `collect($foo)` with `new Collection($foo)` spares  the entire headache as correct type won't need to be inferred from usage of `collect`. Still, filling this as an issue, in case you can advise.

**Comment by szepeviktor** [comment]
> As fcollect is a copy of collect, I'd expect the dumpType to result in the same

Hello @eithed!! 👋🏻 

Larastan recognizes `collect` but not `fcollect`.
https://github.com/nunomaduro/larastan/blob/b0a50dfe2d21c44c9f2577aa5d7c9825b6b9d5b2/src/ReturnTypes/Helpers/CollectExtension.php#L34

I think this is the cause.

**Comment by rovansteen** [comment]
Is there still a need for that `CollectExtension` now that Laravel's collection supports generics? The phpdoc of `collect` in `laravel/framework` seems to be properly set up to support this out of the box: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/helpers.php#L10-L14

**Comment by eithed** [comment]
@szepeviktor `fcollect` is there to illustrate the expected behaviour for `collect` - `Illuminate\Support\Collection<int, array{value: string, factor: float}>` is expected to remain as the type.
