### ISSUE TITLE
Allowed memory size of X bytes exhausted... after update the package

### ISSUE THREAD

**Issue by martio** [nunomaduro/larastan#1492]
### Application:

- Larastan Version: 2.3.1
- PHP Version: 8.1.13
- PHPStan Version: 1.9.4
- `--level` used: 10

### Description:

After upgrading the `nunomaduro/larastan` package, I have a code analyzing problem. It ends up with an error every time... The error occurs after a very large SurnameSeeder file. This file is a seeder and weighs up to 537K.

My command:

`./vendor/bin/phpstan analyse --memory-limit=2G --xdebug --debug -vvv --ansi`

Before the package update, the memory limit was 1 GB and everything worked fine.

Backtrace:

```
/database/seeders/SurnameSeeder.php
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 327680 bytes) in phar:////vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php on line 558
PHP Stack trace:
PHP   1. {main}() /vendor/bin/phpstan:0
PHP   2. include() /vendor/bin/phpstan:120
PHP   3. require() /vendor/phpstan/phpstan/phpstan:8
PHP   4. _PHPStan_5c71ab23c\{closure:phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:13-125}() phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:125
```

**Comment by canvural** [comment]
Pretty sure it's a PHPStan issue. You were probably using older PHPStan version before. Open an issue there **with** a code example or repository.
