### ISSUE TITLE
 Ternary operator condition is always true

### ISSUE THREAD

**Issue by hartman** [nunomaduro/larastan#150]
- Larastan Version: e7b1dd5
- `--level` used: 4 and up

### Description:
I get the following error: Ternary operator condition is always true.

### Laravel code where the issue was found:
```
$owner = $file->owners()->first();
```
Where first returns: "\Illuminate\Database\Eloquent\Model|object|static|null"

The error is reported on the following fragment:
```
$email = ($owner) ? $owner->email : null
```
and the error disappears when I change it to
```
$email = ($owner !== null) ? $owner->email : null
```

**Comment by szepeviktor** [comment]
As per me: I do not see a *truthy* evaluation worthy to use. `$owner !== null` is something I agree.

**Comment by szepeviktor** [comment]
@hartman Please open an upstream issue.
Thanks.
