### ISSUE TITLE
New sql parser causes problems

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1500]
Problems: https://github.com/nunomaduro/larastan/actions/runs/3822439073/jobs/6502584135
Please see https://github.com/phpmyadmin/sql-parser/releases/tag/5.6.0

Also night guard reports it: https://github.com/nunomaduro/larastan/actions/runs/3825841828/jobs/6509121098

**Comment by canvural** [comment]
Fixed https://github.com/nunomaduro/larastan/commit/4643647ee9b4a0cae5f6498631cb23227f75bb33
