### ISSUE TITLE
False negative when using type-hinted class properties and database factories

### ISSUE THREAD

**Issue by gms8994** [nunomaduro/larastan#1507]
- Larastan Version: 2.3.4
- `--level` used: 6
- Pull request with failing test: See commit https://github.com/gms8994/laravel-test-case/commit/55c18552b98db384e61daaa208a81be8beb351bd

### Description

As a continuation of #1215, phpstan/larastan continue to complain about the result from Model factories, specifically when using type-hinted class properties as their destination. I'm still running in to this issue and I don't seem to see a way around it.

### Laravel code where the issue was found

```php
class Foo {
    protected User $user;

    public function bar() {
        $this->user = User::factory()->createOne();
    }
}
```

results in a phpstan complaint of `Property Foo::$user (App\Models\User) does not accept Illuminate\Database\Eloquent\Model.`

This is the case whether it's the `User` model being used or another model. The `UserFactory` already has [`@extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>`](https://github.com/gms8994/laravel-test-case/blob/main/database/factories/UserFactory.php#L9) as [suggested in a comment](https://github.com/nunomaduro/larastan/issues/1215#issuecomment-1101665661). Attempting to add `@var User $user` above the assignment responds with `Variable $user in PHPDoc tag @var does not exist.`; trying `@var User self::$user` or `@var User static::$user` gives the same. Attempts with `@var User $this->user` seems to strangely put phpstan/larastan in to the User model context, and thus it complains `Access to an undefined property App\Models\User::$user.`

**Comment by szepeviktor** [comment]
Hello @gms8994!

As stated here https://github.com/nunomaduro/larastan/issues/1215#issuecomment-1101665661
```php
/** @var User $oneModel */
$oneModel = User::factory()->createOne();
$this->user = $oneModel;
```

**Comment by szepeviktor** [comment]
I see! `createOne`

https://github.com/nunomaduro/larastan/blob/87c3026e01107368730d022176273e673b8cd2af/tests/Features/ReturnTypes/ModelFactory.php#L25-L28

Our tests pass.

**Comment by szepeviktor** [comment]
A simple test for you: https://github.com/szepeviktor/larastan-issue/pull/7

**Comment by canvural** [comment]
Your sample repo does not use Larastan at all.

You need to either create a config file (see https://github.com/nunomaduro/larastan#-getting-started-in-3-steps) or also install `phpstan/extension-installer`, which will automatically register the Larastan.
