### ISSUE TITLE
Eloquent ORM

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#151]
I'm up to use/copy/modify only the Eloquent ORM-related part of Larastan for a framework-less project using `illuminate/database`.

Which part should I pick to solve this?

```yaml
- '#^Call to an undefined( static)? method app\\frontend\\model\\.+::.+\(\)\.$#'
```

`::find()` and `::where()`

...after some progress I'm stuck at mixins as they can't start without Laravel

**Comment by nunomaduro** [comment]
You should require Larastan as dev dependency. Or I am missing something?

**Comment by szepeviktor** [comment]
Okay!
