### ISSUE TITLE
Larastan fails on AWS credentials, unless it has a DB.

### ISSUE THREAD

**Issue by Crell** [nunomaduro/larastan#1515]
- Larastan Version: 1.0.3
- `--level` used: 5
- Pull request with failing test:

### Description

This is an odd one.  Of course. 😄 

I'm trying to run phpstan with larastan on GitHub Actions.  Without any special setup, so there's no DB, I get this error:

```
Error: Internal error: Internal error: Invalid configuration value provided for "region". Expected string, but got bool(false)

region: (string)

  Region to connect to. See
  http://docs.aws.amazon.com/general/latest/gr/rande.html for a list of
  available regions. in file /home/runner/work/blah/blah/CardRepository.php
Run PHPStan with -v option and post the stack trace to:
https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
```

The same error appears 3 times for 3 different files, none of which mention the AWS region or even have "region" in them at all.  There is an AWS region env var, but there is no `.env` file being set.

If, however, I setup a database in the GHA enviornment using Lando (https://peakd.com/hive-168588/@crell/running-lando-on-github-actions), which I already have for phpunit, and run phpstan there, it completes without issue.  Even though the `.env` file in this case *does* still use the generic "region" string for the AWS region env var.

The backtrace from phpstan shows the error is somewhere in Larastan, presumably because Larastan is trying to boot all of Laravel.  What I don't understand is why giving it a database makes the AWS credentials issue go away.  And I'm slightly worried that it's going to do something in the background that impacts some AWS environment, even though it has no real keys for one.

In short, wha?

**Comment by nunomaduro** [comment]
@Crell Larastan boots your application's container, so it can resolve types that are only possible to compute at runtime. The fact that you are saying an error like that while using Larastan, suggests that in one of your service providers you are trying to use the Database or AWS Client, in their respective `boot` / `register` methods, and you should not do that.

You should be able to grab more information about this by running the `--debug` flag by phpstan. Can you check that?

**Comment by Crell** [comment]
So, this confuses me.  With `--debug` on, it shows the error happens when parsing `CardRepository`.  However, `CardRepository` does not appear in the backtrace.  `CardRepository` does make some static calls to the `AWSSecretsManager` Facade, but not in the constructor.

The backtrace shows AWSSecretsManager being constructed from the container, which is several layers deep of calls, which in turn is called from Larastan, which is invoked from somewhere inside phpstan.

But the register command there should be lazy, shouldn’t it?  So why is it invoking it to try and instantiate the service?

And why would making a database available, but not the env far it is asking for, make it work?

**Comment by nunomaduro** [comment]
> But the register command there should be lazy, shouldn’t it? So why is it invoking it to try and instantiate the service?

Laravel, when it boots, it calls the `register` method of all service providers. So it's not lazy.

> And why would making a database available, but not the env far it is asking for, make it work?

I don't know your application - so it's hard to tell.

**Comment by Crell** [comment]
I forgot to include the register command itself, sorry:

```php
    public function register()
    {
        $this->app->singleton('AWSSecretsManager', function ($app) {
            return new AWSSecretsManager();
        });
    }
```

That should be lazy, no?  Just register the factory for the class, but not instantiate anything?

**Comment by nunomaduro** [comment]
We may try to resolve the  `AWSSecretsManager` internally at Larastan, to see the returned type from the closure.

Is `AWSSecretsManager` doing anything crazy on its constructor?

**Comment by Crell** [comment]
The constructor is instantiating a `SecretsManagerClient`, which involves calling getenv().  Presumably the error is happening inside there, as it tries to connect to AWS with an invalid value from the environment.

Would adding a return type to the closure tell Larastan to not bother executing it, perhaps?

**Comment by Crell** [comment]
The facade is trivial:

```php
namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class AWSSecretsManager extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'AWSSecretsManager';
    }
}
```

The backtrace is large, so I've put an anonymized version of it here:  (I just took the project name out of the file path, as it's not a public project.): https://gist.github.com/Crell/0e698930e5665912e56b3240d0298bc0

The relevant portion of the service that's getting loaded is:

```php
namespace App\Services;

use Aws\Exception\AwsException;
use Aws\SecretsManager\SecretsManagerClient;

class AWSSecretsManager
{
    /**
     * @var object
     */
    protected $client = null;

    public function __construct()
    {
        $this->client = $this->getASMClient();
    }

    protected function getASMClient()
    {
        return new SecretsManagerClient([
            'version' => '2017-10-17',
            'region' => getenv('MY_APP_AWS_REGION'),
        ]);
    }
    // ...
}
```

The actual error is getting thrown inside SecretsManagerClient, which is part of the aws-sdk-php package.  It's getting passed an invalid `region` argument, because the env var is indeed invalid at that point, but it shouldn't be called at all.

**Comment by nunomaduro** [comment]
If you do `getenv('MY_APP_AWS_REGION') ?: 'us-east-1'` there is any actual call to AWS? If not, I would just do this.

**Comment by Crell** [comment]
Well, feeding it a valid region but NOT valid AWS credentials seems to load without failing, and then the scan completes.

I still don't understand why:
1. It needs to boot this service at all, when the type information is now provided in the factory closure's return type.
2. Running in a full environment with database *that still doesn't have a valid region code* makes it succeed.  It's like... is Larastan not trying to load that service if there is a database present?

**Comment by canvural** [comment]
When Larastan sees a facade call like `AWSSecretsManager::foo`, it tries to get the underlying facade root to search for the missing method `foo` on it. So it calls `AWSSecretsManager::getFacadeRoot` Which in turn tries to initiate the `App\Services\AWSSecretsManager` This causes the failure in your case.

> It needs to boot this service at all, when the type information is now provided in the factory closure's return type.

This wouldn't be possible with static analysis I think. That's why we do a little bit of dynamic analysis.

>  is Larastan not trying to load that service if there is a database present?

No, it doesn't check if there is DB connection. I'm guessing you have some different setup in the GHA environment that causes it to work.

Anyway, this issue inspired me to make a fix. You can use `@mixin` tag in your facade class to instruct where to find the methods. For your example you can add `/** @mixin App\Services\AWSSecretsManager */` docblock to your facade. So it'll find the methods. Also I wrapped the `::getFacadeRoot` call in a try-catch. So instead of failing, it'll simply ignore it, and later PHPStan will produce error like `Call to an undefined method AWSSecretsManager::foo().`
These changes are in `master` branch currently. So please pull the branch, test and let me know if it fixes the issue.

**Comment by Crell** [comment]
Well this is fascinating.  I tried the dev-master version of larastan, and using the mixin seems to resolve this issue... but find 24 more issues that the current stable doesn't find!  Including several that are objecting to exclude rules in my baseline file that now don't exist.

I don't know if that's good or bad...

I still get different behavior local vs GitHubActions, but the try-catch and `@mixin` directive seem to be working at least.

**Comment by canvural** [comment]
Good to hear that it fixed the issue.

> but find 24 more issues that the current stable doesn't find!

Are those false positives or actual issues?

> Including several that are objecting to exclude rules in my baseline file that now don't exist.

This is good I guess.

**Comment by Crell** [comment]
Seems like actual, I think.  I didn't look closely.
