### ISSUE TITLE
I am forced to write the type of the same variable twice

### ISSUE THREAD

**Issue by Cepairda** [nunomaduro/larastan#1516]
- Larastan Version: 2.2.9
- `--level` used:  8
- Pull request with failing test:

### Description
I am forced to specify the variable type twice 
```php
/**
 * @var stdClass $response;
 */
```
Otherwise I am getting below error. How to get rid of it? And don't write the same thing twice
![image](https://user-images.githubusercontent.com/6544013/211702131-0af97230-7ed7-4e4d-a314-b446d965ad48.png)

### Laravel code where the issue was found

```php
   /**
     * Get Items by API first page
     *
     * @return object|array<string>
     */
    public function getItemsByApiFistPage()
    {
        return Http::kodik()->get('list', [
            'token' => config('services.kodik.token'),
            'types' => 'anime,anime-serial',
            'with_material_data' => 'true',
            'limit' => '100',
            'sort' => 'created_at',
            'order' => 'desc',
        ])->object();
    }

    /**
     * Get Items by API next page
     *
     * @param string $nextPage
     *
     * @return object|array<string>
     */
    public function getItemsByApiNextPage(string $nextPage)
    {
        return Http::get($nextPage)->object();
    }

      /**
     * Import Items
     *
     * @return void
     */
    public function importItems(): void
    {
        /**
         * @var stdClass $response;
         */
        $response = $this->getItemsByApiFistPage();

        do {
            $items = $response->results;
            $nextPage = $response->next_page;

            /**
             * @var stdClass $item
             */
            foreach ($items as $item) {
                /** My code */
            }
        } while (
            $nextPage
                ? (
                 /**
                * @var stdClass $response;
                */
                $response = $this->getItemsByApiNextPage($nextPage))
                : null
        );
    }
```

**Comment by szepeviktor** [comment]
Hello 👋🏻 
Thank you for your report.

Yes, the `@return object|array<string>` return type of `getItemsByApiNextPage` may be an array which has no properties.
Maybe it is just `@return object` ...

**Comment by Cepairda** [comment]
@szepeviktor i tried. Error, because Laravel return object|array
```
/**
     * Get the JSON decoded body of the response as an object.
     *
     * @return object|array
     */
    public function object()
    {
        return json_decode($this->body(), false);
    }
```
![image](https://user-images.githubusercontent.com/6544013/211779303-43ad8d20-6330-4bc9-8ff6-b967702957af.png)

**Comment by szepeviktor** [comment]
All right! You're going the right way.
Now modify `object` method's return type to `@return object` as `json_decode` got a `false`.

**Comment by Cepairda** [comment]
> All right! You're going the right way. Now modify `object` method's return type to `@return object` as `json_decode` got a `false`.

How ?

**Comment by szepeviktor** [comment]
I see. It is a framework method.
Send them a Pull request!
