### ISSUE TITLE
[v1] False-positive when aliasing backpack method

### ISSUE THREAD

**Issue by renanbr** [nunomaduro/larastan#1517]
- Larastan Version: 1.0.4
- `--level` used: 5
- Laravel Version 8.83.27
- Backpack Version: 5.4.14
- Pull request with failing test: https://github.com/renanbr/laravel-php-response/commit/8ac3aafe8908654ea78f2232580caa37c24cda36
    - https://github.com/renanbr/laravel-php-response

### Description

When using larastan and aliasing a method, the return type is no longer checked.

Additional information:

- Removing aliasing makes the error reachable
- Removing larastan extension makes the error reachable

### Laravel code where the issue was found

```php
namespace App\Http\Controllers;

use Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
use Illuminate\Http\Response;

class HelloController extends Controller
{
    use UpdateOperation { update as traitUpdate; } // PHPStan doesn't trigger the error as expected
//    use UpdateOperation; // PHPStan triggers the error as expected

    public function index(): Response
    {
        return $this->traitUpdate();
    }
```

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app/

    level: 5
```

**Comment by canvural** [comment]
Please open a new issue if you can produce it with Larastan 2. 1.x is not supported.
