### ISSUE TITLE
Adding arguments to custom model casts via $casts[] results in incorrect property type

### ISSUE THREAD

**Issue by attac-t** [nunomaduro/larastan#1525]
- Larastan Version: 2.4.0
- `--level` used: 5

### Description
When using `Castable` classes and providing arguments in the eloquent model's `$casts` definition, the property is not being casted to a `phpstan` type.

Model property casting has been handled in #1333.

### How to replicate

Implement a `castable` class as defined [here](https://laravel.com/docs/9.x/eloquent-mutators#castables) and provide an argument via the model's `$casts[]`.

```php
use App\Models\Address;
 
protected $casts = [
    'address' => Address::class.':argument',
];
```

**Comment by canvural** [comment]
What error are you getting?

**Comment by canvural** [comment]
I see. 

@erikgaal Can you take a look at this please?

**Comment by erikgaal** [comment]
This should be covered by the `'secret' => Hash::class . ':sha256'` test case, but I will investigate.

**Comment by strotgen** [comment]
- Larastan Version: 2.4.0
- --level used: 5

Getting a similar error when I updated from 2.2.9 to 2.4.0 and using cknow/laravel-money casters. Example: 

```php
use Cknow\Money\Casts\MoneyIntegerCast;

protected $casts = [
        'amount' => MoneyIntegerCast::class.':currency_code',
];
```

And when calling it like `$model->amount->formatByDecimal()`, PHPStan says the following:

> Cannot call method formatByDecimal() on int.
