### ISSUE TITLE
code:analyse not outputting to stdout/stderr

### ISSUE THREAD

**Issue by nie7321** [nunomaduro/larastan#153]
- Larastan Version: v0.2.12
- `--level` used: Default (5)

### Description:
The `code:analyse` command is outputting to a tty instead of stdout/stderr. 

This renders me unable to capture it for use by my CI system. As a workaround, I'm running the phpstan command with the right config/etc instead.

### Laravel code where the issue was found:
I am running the following:

`php artisan code:analyse --memory-limit 512M --no-progress --no-ansi --error-format=checkstyle > /tmp/phpstan-checkstyle.xml`

The output is printed to the terminal, and `/tmp/phpstan-checkstyle.xml` is empty.

If you comment out [CodeAnalyseCommand.php#L70](https://github.com/nunomaduro/larastan/blob/master/src/Console/CodeAnalyseCommand.php#L70) and re-run the above, it prints to stdout and the report is captured in `tmp/phpstan-checkstyle.xml`.

I have to admit that I don't have a ton of experience on CLI apps, so I'm not sure _why_ using the tty is desirable here? For lack of understanding, I am not sure what a good solution is, otherwise I'd send you a PR 😁

**Comment by szepeviktor** [comment]
@nie7321 Try `php artisan code:analyse >/tmp/phpstan-checkstyle.xml 2>&1`

**Comment by nie7321** [comment]
Same problem -- outputs to my terminal, but my file is empty.

Does that work in your environment? I'm seeing the behaviour both in Homestead & inside a Docker image extended from the official php:7.1-apache docker image.

**Comment by gpressutto5** [comment]
That's a real bug. When using with [grumphp](https://github.com/phpro/grumphp), larastan breaks the "layout".

**Comment by SCIF** [comment]
Hi @gpressutto5 , @nie7321 ,
I've experienced the same issue running the package in official Docker image. As a workaround you can use `--no-tty` option. A coloured output will go but you will be able to use pipes and redirection to file.

**Comment by szepeviktor** [comment]
@SCIF We are open to your PR!

**Comment by szepeviktor** [comment]
+1 for the second option

**Comment by SCIF** [comment]
@nunomaduro , @canvural ,

Guys, my apologies, I didn't finalize but patch is just to introduce `no-tty` option as I [described](https://github.com/nunomaduro/larastan/issues/153#issuecomment-443104671).
