### ISSUE TITLE
Falsely reported "Call to undefined static method"

### ISSUE THREAD

**Issue by EriBloo** [nunomaduro/larastan#1540]
- Larastan Version: 2.0.0
- `--level` used: 1

### Description
Larastan reports "Call to undefined static method..." on core laravel classes.

![image](https://user-images.githubusercontent.com/19932449/216767140-14b7a5ee-57b5-4791-a31f-47ce4c87dbdd.png)
![image](https://user-images.githubusercontent.com/19932449/216767142-5453311f-2125-4e34-8c3f-d90ddb8b4bb7.png)

### Laravel code where the issue was found
Default UserFactory and any migration using `Illuminate\Support\Facades\Schema::connection()`.

```php
    public function definition()
    {
        return [
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Str::random(10),
        ];
    }
```

**Comment by szepeviktor** [comment]
Hello @EriBloo 👋🏻 
Thank you for your report.

Do you import Str?
`use Illuminate\Support\Str;`

**Comment by EriBloo** [comment]
Yes.
I checked it with `Illuminate\Support\Arr` as well and I get the same error. It is not isolated to `UserFactory` class - I get the same error in other classes (and with other static methods of this class).
PhpStorm reports no issues (like undefined method or class doesn't exist) - I can ctrl-click to jump to definition.

**Comment by szepeviktor** [comment]
`Str::random` also appears here
https://github.com/szepeviktor/larastan-issue/blob/fbca632fbdf1775b78495ac2012169abef12054b/database/factories/UserFactory.php#L25

And the analysis succeeds on `level: 8`
https://github.com/szepeviktor/larastan-issue/actions/runs/4089331889/jobs/7051918984

I think there is something wrong with your setup.
Please try starting with `laravel/laravel` sample application and try to reproduce the error there.

**Comment by EriBloo** [comment]
Yes, you are right. I cleaned up `phpstan.neon` a bit and I think I found what causes this error.
I'm using barryvdh/laravel-ide-helper and to include definitions from generated files I added:

```neon
    scanFiles:
        - _ide_helper.php
        - _ide_helper_models.php
        - .phpstorm.meta.php
```
to configuration. After I removed those lines those errors didn't show up (ofc I got multiple new errors due to missing ide_helper definitions).
Is this intended behavior? Or maybe I misunderstood `scanFiles` parameter?

**Comment by szepeviktor** [comment]
This is my own conclusion.
1. Larastan is not fully compatible with ide-helper
2. Please consider purchasing a Laravel add-on for your IDE

**Comment by EriBloo** [comment]
Thank you very much for all the help :)

**Comment by szepeviktor** [comment]
You're welcome.
