### ISSUE TITLE
Try to detect non-use of best practices

### ISSUE THREAD

**Issue by cavo789** [nunomaduro/larastan#1541]
Hi all !

I'm not so new with Laravel but don't work with it so much so, I know it, I'm making conception errors and/or not following best practices like respect naming conventions. I pay a lot of attention to the quality of the code and the respect of the rules.

I've just installed a fresh Laravel site for fun and create two models

* `php artisan make:model Students`
* `php artisan make:model Teacher`

Students, plural form and Teacher, singular form.  I know that Models should be written using singular form. (https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions)

So, does Larastan detect this violation?

```bash
composer require nunomaduro/larastan:^2.0 --dev
 ./vendor/bin/phpstan analyse
```

And this even at level `9`:

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - app/
    level: 9
```

Did you know if Larastan can be used too for such things i.e. notifying the developper he's not following best practices?

If not, did you know some tools for this usage?

Many thanks!

**Comment by szepeviktor** [comment]
Hello Christophe! 👋🏻 
Any software can do this.
I can think of 2: coding standards or static analysis.
Coding standards violation is closer to class naming.

**Comment by cavo789** [comment]
At work, I'm using `php-cs-fixer`, `phpcbf`, `phpcs`, `larastan` and `psalm`.  Using `rector` too.  Yeah, I'm a fan of static analysis tools and how they are great to improve the codebase and increase skills of the developer.

My skills with Laravel (I mean writing code) can be improved and ... voilà, I'm trying to determine if tools exists for helping me (and people who don't write laravel code each day) to try to use best practices.

For the example I've given here above, no tools already detect this. Perhaps are there somewhere some magic I don't have discovered yet ;)

**Comment by szepeviktor** [comment]
Please talk to Slevomat guys. They are deeply into this.

**Comment by cavo789** [comment]
Thanks! Indeed, i've already see https://github.com/slevomat/coding-standard months ago; will read it once more.

**Comment by cavo789** [comment]
(just for info, I think I've enabled all rules of  https://github.com/slevomat/coding-standard and none are helping here i.e. no notification about the user of the plural form in my Students model)

**Comment by szepeviktor** [comment]
I've meant to really talk to them: please open an issue.

**Comment by szepeviktor** [comment]
There are class name processing sniffs. E.g. the one that check interface name ending `Interface`.
It is very easy to copy it and make it check class names.

**Comment by szepeviktor** [comment]
Have you heard of https://laravelshift.com/opinionated-laravel-way-shift ?

**Comment by cavo789** [comment]
Never... Just take a look and create an account and... No, I can't use it.

That tool ask to clone my project but it's not possible. My projects are stored in our corporate GitLab instance and in no way it'll be allowed to push our code to their servers.

**Comment by szepeviktor** [comment]
> to clone my project

There are local shifts: https://laravelshift.com/docker
