### ISSUE TITLE
Getting "Access to an undefined property" for all properties in Resources.

### ISSUE THREAD

**Issue by vishytk** [nunomaduro/larastan#1548]
- Larastan Version: 2.4
- `--level` 7:

### Description
running "./vendor/bin/phpstan analyse" shows error "Access to an undefined property" for all properties in Resources.
Tried adding `/** @extends JsonResource<Patient> */` without any luck.

*PatientResource.php*

```php
namespace App\Http\Resources;

use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PatientResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'firstname' => Str::title($this->firstname),
            'lastname' => Str::title($this->lastname),
            'fullname' => $this->fullname,
            'gender_id' => $this->gender_id,
            'dob' => $this->dob,
            'age' => $this->age,
	    ...	
        ];
    }
}
```

Errors:

Access to an undefined property App\Http\Resources\PatientResource::$id.
Access to an undefined property App\Http\Resources\PatientResource::$firstname.
Access to an undefined property App\Http\Resources\PatientResource::$lastname.
...

**Comment by szepeviktor** [comment]
Hello!
Larastan reads properties from your migrations.
Could you check that?

**Comment by canvural** [comment]
You need to add @mixin YourModel to the class docs.
