### ISSUE TITLE
orchestra/testbench ^3.7 requires laravel 5.7

### ISSUE THREAD

**Issue by Korri** [nunomaduro/larastan#155]
- Larastan Version: 0.3.0
- `--level` used:

### Description:
Trying to install Larastan on a 5.6 app, and he requirement for testbench 3.7 makes it impossible.

**Comment by szepeviktor** [comment]
Yes, they do
https://github.com/orchestral/testbench/blob/3.7/composer.json#L21
trying to resolve it...

**Comment by szepeviktor** [comment]
It was just 2 hours ago!!
https://github.com/nunomaduro/larastan/commit/a85cb4aabe8dfb8bc019ecaf9341fa4077f72248#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R16

**Comment by nunomaduro** [comment]
@szepeviktor Thanks for the help. @Korri the issue has been fixed in the version `v0.3.1`. Can you run a quick test?

FYI: The version `v0.3` allow people to use Larastan while creating packages for Laravel: https://twitter.com/enunomaduro/status/1047948748272422920.

**Comment by Korri** [comment]
> @szepeviktor Thanks for the help. @Korri the issue has been fixed in the version `v0.3.1`. Can you run a quick test?
Yes it works now thanks!


> It was just 2 hours ago!!
> [a85cb4a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R16](https://github.com/nunomaduro/larastan/commit/a85cb4aabe8dfb8bc019ecaf9341fa4077f72248#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R16)

Haha yes, quite the timing, I just finised upgrading to 5.6 and was excited to finally be able to install Larastan

**Comment by nunomaduro** [comment]
Enjoy!

**Comment by emiliopedrollo** [comment]
Now it's not compatible with Laravel 5.7:

    orchestra/testbench v3.6.5 requires laravel/framework ~5.6.13

And ~5.6.13 does not include 5.7. The solution is to allow orchestra/testbench in either version 3.6 or 3.7 (with is compatible with laravel 5.7). There's already a pull request #180 that can resolve this issue.
