### ISSUE TITLE
Anyone else has problems with latest PHPStan 1.10 ?

### ISSUE THREAD

**Issue by rcerljenko** [nunomaduro/larastan#1554]
- Larastan Version: 2.4.1
- `--level` used: 6
- Pull request with failing test:

### Description

Just updated my codebase to new [PHPStan 1.10](https://github.com/phpstan/phpstan/releases/tag/1.10.0) and I've started to get errors on weird places without changing the code.

**Comment by rcerljenko** [comment]
Yeah something like that.. also some local scopes are not recognized as "scopes" and they were before...
And one more thing... model "create" functions are returning generic Model instead of a specific model class eg. Post

**Comment by ondrejmirtes** [comment]
I think this bug report should be more specific - show some code for which PHPStan/Larastan is now failing.

Also make sure to test PHPStan 1.10.1 first :)

**Comment by rcerljenko** [comment]
@ondrejmirtes I agree... actually updating it to 1.10.1 fixed 2/5 errors by itself... so here are the examples of the rest:

1. Match operator with Enum
```php
protected $casts = [
	'provider' => SmsProvider::class, // this is an Enum
];

protected function getDefaultFrom(): ?string
{
	return match ($this->provider) {
		SmsProvider::Vonage => setting('vonage_from_number'),
		SmsProvider::Twilio => setting('twilio_from_number'),
		SmsProvider::InfoBip => setting('infobip_from_number'),
		SmsProvider::NTH => setting('nth_from_number'),
		SmsProvider::Elks => setting('elks_from_number'),
		default => null,
	};
}
```

Reported errors:
```
Match arm comparison between App\Enums\SmsProvider::Elks and App\Enums\SmsProvider::Elks is always true.  
Match arm is unreachable because previous comparison is always true.
```

2. And here is another one in custom validation Rule using a local model scope
```php
protected readonly Model $model; // Eloquent model

public function validate(string $attribute, mixed $value, Closure $fail): void
{
        // this is how we know that this Model instance has `hasTranslatedField` scope
	if (!($this->model instanceof HasTranslations)) {
		$fail('validation.custom.translated-instance')->translate(['attribute' => $attribute]);

		return;
	}

	$builder = $this->model->query()->when($this->model->getKey(), function (Builder $query): void {
		$query->where($this->model->getKeyName(), '<>', $this->model->getKey());
	})
	->hasTranslatedField($attribute, $value);

	if ($builder->exists()) {
		$fail('validation.unique')->translate(['attribute' => $attribute]);
	}
}
```

Reported errors:
```
Call to an undefined method Illuminate\Database\Eloquent\Builder::hasTranslatedField().
```

**Comment by ondrejmirtes** [comment]
The first one is explained in the release article: https://phpstan.org/blog/phpstan-1-10-comes-with-lie-detector

You need to remove the default.

**Comment by rcerljenko** [comment]
After removing default only second part of error is gone but still reports this:
```
Match arm comparison between App\Enums\SmsProvider::Elks and App\Enums\SmsProvider::Elks is always true.
```

**Comment by ondrejmirtes** [comment]
That's weird, that shouldn't happen. Please reproduce that on phpstan.org/try.

**Comment by rcerljenko** [comment]
Yeah it is.. specially because it doesn't show any errors in the playground:

<https://phpstan.org/r/ede80136-2f46-4a42-84d1-4761488b65c1>

**Comment by ondrejmirtes** [comment]
Please make sure you're using PHPStan 1.10 and that you haven't turned on reportAlwaysTrueInLastCondition that causes this behaviour.

If the problem still persists, please create a small repository with your issues. Thank you.

**Comment by rcerljenko** [comment]
I did have `reportAlwaysTrueInLastCondition: true` and now i removed it and the errors are gone... thx for that!
But still the second error for local scope persists.. i'll try to work areound it somehow on my end

**Comment by rcerljenko** [comment]
hi @ondrejmirtes ... i found this.. is it possible that is somehow related?

https://github.com/nunomaduro/larastan/issues/1307

**Comment by ondrejmirtes** [comment]
Someone else will need to help with that, I don't have deep knowledge of Laravel nor Larastan.

**Comment by rcerljenko** [comment]
@szepeviktor we crave for your wisdom...  :)

**Comment by canvural** [comment]
Hi @rcerljenko 

Can you add `\PHPStan\dumpType($this->model); \PHPStan\dumpType($this->model->query());` to the line above `$builder = $this...` and re-run PHPStan? In the output you should be see 2 dumped types. Can you please post them here?

**Comment by szepeviktor** [comment]
I second that.

**Comment by rcerljenko** [comment]
here you go guys:

```
Dumped type: App\Contracts\HasTranslations&App\Models\Model
Dumped type: Illuminate\Database\Eloquent\Builder
```

**Comment by rcerljenko** [comment]
If I'm not mistaken, `Builder` being a generic should be "self model aware" right?
Just to clarify, `scopeHasTranslatedField` method is located in the `HasTranslations` trait and applied to any model along with `HasTranslations` contract.

**Comment by canvural** [comment]
Builder is generic but it only accepts a model as an inner type. So in your case the method is defined in interface and trait, that's not gonna work.

I don't think was ever working, even with older PHPStan versions. I think it was just ignored somehow, and with new release it came to surface.

**Comment by rcerljenko** [comment]
Ah ok... So what should I do then? This is probably gonna mess with me in the future as well...

**Comment by canvural** [comment]
I think your only choices are to either ignore it or try to narrow down the type of `$model` to a specific model class.

**Comment by rcerljenko** [comment]
I guess ignore it for now... is it possible in the future of larastan to resloves this things?

**Comment by rcerljenko** [comment]
a ha! I got it to work without ignoring errors... it's ugly but it works.  ;)

```php
$builder = $this->model::class::hasTranslatedField($attribute, $value)
	->when($this->model->getKey(), function (Builder $query): void {
		$query->where($this->model->getKeyName(), '<>', $this->model->getKey());
	});
```
