### ISSUE TITLE
Unable to work with migration containing raw SQL

### ISSUE THREAD

**Issue by Temepest74** [nunomaduro/larastan#1556]
- Larastan Version: 2.4.1
- `--level` used:2

I have this code in one of my migrations
```php
        Schema::table(
            'A',
            static function (Blueprint $table) {
                DB::select('ALTER TABLE A RENAME COLUMN colA TO colB');
            }
        );
```

And I get this error:
``` Access to an undefined property App\Models\A::$colB. ```
When I try to get colB

**Comment by szepeviktor** [comment]
Yes, you are right.
Larastan understand only simple migrations.
Custom SQL code is not supported.

Let me do a quick Google search for you ...

**Comment by szepeviktor** [comment]
```php
        Schema::table('A', function(Blueprint $table) {
            $table->renameColumn('colA', 'colB');
        });
```

This should be supported.
https://github.com/nunomaduro/larastan/blob/37b302e5c04a3a03fc4c48ea6d17ce97e3913ced/src/Properties/SchemaAggregator.php#L390

**Comment by Temepest74** [comment]
I think my code should be an exception. Dbal does not work on all column types so rename will sometimes change the column type as well. 
Eg: renaming a tiny unsigned int will result in an unsigned int.

Ik it is kind of useless and weird edge case.

**Comment by szepeviktor** [comment]
Okay. Then you have to add `@var int $volB` to your Model.
