### ISSUE TITLE
Lumen `app()` helper resolves to `Illuminate\Foundation\Application` instead of `Laravel\Lumen\Application`

### ISSUE THREAD

**Issue by OllieCrook** [nunomaduro/larastan#1566]
- Larastan Version: 1.0.4 and 2.4.1
- `--level` used: 2

### Description
The use of `app()->withEloquent()` results in:
```
Call to method withEloquent() on an unknown class Illuminate\Foundation\Application
```

### Lumen code where the issue was found

```php
app()->withEloquent();
```

### Reproduction Steps
Setup project:
```bash
composer create-project --prefer-dist laravel/lumen larastan-test

cd larastan-test

composer require nunomaduro/larastan:^2.0 --dev
```

`phpstan.neon.dist`
```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - routes/web.php

    level: 2
```

`web.php`
```php
<?php

app()->withEloquent();
```

Analyse code:
```bash
./vendor/bin/phpstan analyse
```

**Comment by szepeviktor** [comment]
Hello Ollie! 👋🏻 
Thank you for your report.

> an unknown class Illuminate\Foundation\Application

That is because Larastan does not support Lumen.

**Comment by OllieCrook** [comment]
It's not strictly marked as supporting it but there is code in order to support the booting of a Lumen application:
```php
if ($app instanceof Application) {
    $app->make(Kernel::class)->bootstrap();
} elseif ($app instanceof LumenApplication) {
    $app->boot();
}
```

**Comment by szepeviktor** [comment]
It seems that was not removed.

**Comment by canvural** [comment]
Hi,

Lumen is not supported.
