### ISSUE TITLE
Larastan unexpectedly discovers RayServiceProvider (spatie/laravel-ray) required by orchestra/testbench and breaks existing tests

### ISSUE THREAD

**Issue by mpyw** [nunomaduro/larastan#1588]
- Larastan Version: 2.5.1
- `--level` used: 9

### Description

The other day, the following test suddenly broke in a library I am developing.

```php
class ExampleTest extends TestCase
{
    // Note that there are no RefreshDatabase trait

    public function testExample(): void
    {
        config(['database.connections.mysql.' . PDO::ATTR_EMULATE_PREPARES => true]);
        $this->assertTrue((bool)DB::getPdo()->getAttribute(PDO::ATTR_EMULATE_PREPARES)); // false!?!?
    }
}
```

Analysis of the problem revealed the following:

- Simply running `vendor/bin/phpunit` succeeds
- If `vendor/bin/phpunit` is executed after `vendor/bin/phpstan`, it fails

I suspected that Larastan was corrupting the cache, and upon investigation found that Larastan had rewritten the following file with unintended content:

- `vendor/orchestra/testbench-core/laravel/bootstrap/cache/packages.php`
- `vendor/orchestra/testbench-core/laravel/bootstrap/cache/services.php`

In `packages.php`, I found a dependency `spatie/laravel-ray` on `orchestra/testbench` is discovered and cached. As a side effect, unexpectedly, `DB::connection()` is eagerly resolved in all tests. 

I believe #1404 is related to this issue, but still reproduces it. As a workaround, I have introduced the following cache clearing.

- https://github.com/mpyw/laravel-pdo-emulation-control/commit/c95308db797f40ab29d03cfb69d0e509a3534706

**Comment by crynobone** [comment]
This has been fixes in the latest `spatie/laravel-ray`
