### ISSUE TITLE
PEST higher order expectations cause `undefined method` errors in level 2

### ISSUE THREAD

**Issue by magnetas** [nunomaduro/larastan#1589]
- Larastan Version: 2.5.1
- `--level` used: 2
- Pull request with failing test: -

### Description

Running Larastan (starts from level 2) against a PEST test using higher order expectations returns errors:

`Call to an undefined method Pest\Expectation|Pest\Support\Extendable::getIt().`

I did try listing my Demo class in `universalObjectCratesClasses` with no luck.

Is there a way/extension/configuration to deal with it? It's purely PEST related but maybe Larastan or Laravel plugin should deal with it by default?

### Laravel code where the issue was found

The class (Demo.php):

```php
<?php

namespace App;

class Demo
{
    public function getIt(): int
    {
        return 123;
    }
}

```

The test (DemoTest.php):

```php
<?php

use App\Demo;

test('it returns expected number', function () {
    expect(new Demo())->getIt()->toBe(123);
});
```

**Comment by canvural** [comment]
Hello,

This doesn't seem related to Larastan itself. PEST would need it's own extensions to support this.

**Comment by szepeviktor** [comment]
PHPStan understand straight-forward code only. You need to add a PHPStan extension to PEST if you want to analyze its _tricky_ code.

**Comment by magnetas** [comment]
> PHPStan understand straight-forward code only. You need to add a PHPStan extension to PEST if you want to analyze its _tricky_ code.

And it doesn't yet exist, right?

**Comment by szepeviktor** [comment]
No, it does not (yet) exist.
