### ISSUE TITLE
Is the only way to resolve this by muting the error?

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [nunomaduro/larastan#1602]
- Larastan Version: 2.4.0
- `--level` used: 7
- Pull request with failing test:

### Description
I'm getting the following error: 

> Method App\Models\Order::getSeatingCodes() should return array{array{code: string, type: string, status: string}} but returns array.

However the Eloquent query returns exactly the format specified. 

Of course, I'm guessing it's impossible to resolve a situation like this (without putting an exception to mute the error in place or a making the return type more generic) -- Larastan simply can't tell what's being returned, but I thought I'd double check.

### Laravel code where the issue was found

```php
/**
 * @return array{array{code: string, type: string, status: string}}
 */
public function getSeatingCodes(): array
{
    return $this->tickets()
        ->select('ticket_code AS code', 'seating_type AS type', 'order_state AS status')
        ->get()
        ->toArray();
}
```

**Comment by szepeviktor** [comment]
Everything may be much better if you use a value object to store these three fields.
Array are best for homogeneous lists.

**Comment by JohnnyWalkerDigital** [comment]
Thanks. Good tip!

**Comment by canvural** [comment]
Hi,

The error is not really about the array shape. It's about the array key for the first array.

What's the output of
```php
\PHPStan\dumpType($this->tickets()
        ->select('ticket_code AS code', 'seating_type AS type', 'order_state AS status')
        ->get());
```
