### ISSUE TITLE
PHPStorm says it can be referred from source code but PHPStan can't understand otherwise

### ISSUE THREAD

**Issue by glamorous** [nunomaduro/larastan#1605]
- Larastan Version: 2.5.1
- `--level` 5:

### Description
From what I can see the source code is configured correctly (vendor package) to inform that a Custom Eloquent Collection is being used. PHPStorm gives a warning because it's not needed: 
```
Reports the @var tags for variables whose type is already inferred from source code
```

### Laravel code where the issue was found

```php
/** @var MediaCollection<int, Media> $downloads */
$downloads = $this->getMedia('downloads');

/** @var ?Media $mediaitem */
$mediaitem = $downloads->first(fn(Media $item) => $item->getCustomProperty('property') === $myCustomProperty);
```

This can be found in the vendor package:

```php
/**
 * @template TKey of array-key
 * @template TModel of \Spatie\MediaLibrary\MediaCollections\Models\Media
 *
 * @extends \Illuminate\Database\Eloquent\Collection<TKey, TModel>
 */
class MediaCollection extends Collection implements Htmlable
```

The error in PHPStan without the first comment to inform about the MediaCollection:

```
Parameter #1 $callback of method Illuminate\Support\Collection<(int|string),Illuminate\Database\Eloquent\Model>::first() expects (callable(Illuminate\Database\Eloquent\Model, (int|string)): bool)|null,  
         Closure(Spatie\MediaLibrary\MediaCollections\Models\Media): bool given.
```

So to conclude, this particular line: `/** @var MediaCollection<int, Media> $downloads */` fixes the issue in PHPStan but it shouldn't be there because the vendor package is wellformed and even PHPStorm knows it can be found in the source code.

Or am I missing something?

**Comment by szepeviktor** [comment]
Maybe this with 2 generic types?
https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-collections

**Comment by canvural** [comment]
We don't know what is the return type of `getMedia` method. If you fix that, then you would not need `@var` Also, this really doesn't seem like an issue with Larastan.

**Comment by glamorous** [comment]
How could you not now? The function is from a trait with correct return type, see here:

```
    /**
     * Get media collection by its collectionName.
     *
     * @param array|callable $filters
     *
     */
    public function getMedia(string $collectionName = 'default', array|callable $filters = []): MediaCollections\Models\Collections\MediaCollection
    {
```
