### ISSUE TITLE
Larastan reads records in DB tables?

### ISSUE THREAD

**Issue by CalebDW** [nunomaduro/larastan#1609]
- Larastan Version: 2.5.1
- `--level` used: 1
- Pull request with failing test:

### Description
Hello!

I noticed that Larastan started failing when a particular database table was empty...I was under the impression that the DB was not queried. Furthermore, it apparently doesn't just check for a non-empty DB table but the exact record must be in the table or I get an `Attempt to read property "price_per_pound" on null` error.

Note that the DB is seemingly only queried on the first run when the cache is built, subsequent runs with the proper record in the database does not change the failure to passing.

### Laravel code where the issue was found

```php
        $pricePerPound  = PlateSettings::active()
            ->where('gauge', 20)
            ->where('grade', 60)
            ->where('galvanization', 60)
            ->first()
            ->price_per_pound;
```

**Comment by CalebDW** [comment]
Further testing reveals that:
1. Larastan *passes* when using `firstOrFail()` and the record is not in the DB table.
2. Larastan *passes* when using `first()` and the DB table does not exist.
3. Larastan **fails** when using `first()`, the DB table exists, and the record is not in the DB table.

**Comment by szepeviktor** [comment]
Although Larastan boots up the framework but does not execute controllers.
If you find the root of database connection you will solve this problem.

**Comment by CalebDW** [comment]
@szepeviktor, thanks for the info!

Larastan may not execute controllers, but does it *construct* them?

**Comment by szepeviktor** [comment]
I'm just a janitor here 🧹 I'm sure you can find the root where database connection originates from with a few well-directed `dd` calls.

**Comment by mad-briller** [comment]
I believe laravel itself constructs controllers when booting as it needs to check for calls to middleware() etc.

**Comment by CalebDW** [comment]
So this has nothing to do with controllers (in this case).

Apparently Larastan resolves objects from the service container as it comes across them, and will execute any queries that are in any constructors...

```php
resolve(<class>)->property // fails
(new <class>())->property // does not fail
```

**Comment by CalebDW** [comment]
So this has nothing to do with controllers (in this case).

Apparently Larastan resolves objects from the service container as it comes across them, and will execute any queries that are in any constructors...

```php
resolve(<class>)->property // fails
(new <class>())->property // does not fail
```
