### ISSUE TITLE
PHPDoc tag @extends contains generic type Illuminate\Http\Resources\Json\JsonResource<Model> but class Illuminate\Http\Resources\Json\JsonResource is not generic.

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/larastan#1614]
- Larastan Version: 1.10.10
- Laravel Version: 10.5.1
- `--level` used: 5

### Description

The upgrade guide states:

> Upgrading To 0.5.3 From 0.5.2

> Eloquent Resources
> In order to perform proper analysis on your Eloquent resources, you must typehint the underlying Eloquent model class. This will >inform PHPStan that this resource uses User model. So calls to $this with model property or methods will be inferred correctly.

```
/**
 * @extends JsonResource<User>
 */
class UserResource extends JsonResource
{
...
}
```

However, doing this, causes Larastan to report:

*PHPDoc tag @extends contains generic type Illuminate\Http\Resources\Json\JsonResource<App\Models\WorkProfile> but class Illuminate\Http\Resources\Json\JsonResource is not generic.*

Am I confused or should this be working as described?

Example of one of my JsonResource's 
```
<?php

namespace App\Http\Resources;

use App\Models\WatchProfileChecklistItem;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @extends JsonResource<WatchProfileChecklistItem>
 * @mixin WatchProfileChecklistItem
 */
class WatchProfileChecklistItemResource extends JsonResource
{
    /**
     * @param  Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id'                         => $this->id,
            'name'                       => $this->name,
            'watch_profile_checklist_id' => $this->watch_profile_checklist_id,
            'created_at'                 => $this->created_at,
            'updated_at'                 => $this->updated_at,

            'checklist' => new WatchProfileChecklistResource($this->whenLoaded('checklist')),
        ];
    }
}
```

**Comment by szepeviktor** [comment]
I'm very sorry.
Larastan v1 is not supported any more.

**Comment by SlyDave** [comment]
no worries, also occurring in v2.5.1, no issue raised :)
