### ISSUE TITLE
Eloquent Model attributes issues with PHPStan v1.10.12

### ISSUE THREAD

**Issue by magnetas** [nunomaduro/larastan#1620]
- Larastan Version: 10.7.1
- `--level` used: 2

### Description

After phpstan update to `1.10.12` generic Eloquent Model attributes are not recognised (fields or relations).

### Laravel code where the issue was found

Sample from tests:

```php
/** @var \Illuminate\Database\Eloquent\Collection */
$books = Book::factory()->count(4)->create();

$data = [
    $books->get(0)->id => 'some value',
    $books->get(2)->id => 'other value',
];
```

I get errors like:

`Access to an undefined property Illuminate\Database\Eloquent\Model::$id.`

and

`Call to an undefined method Illuminate\Database\Eloquent\Model::genres().`

Not sure what is affected here. Downgrading phpstan back to `1.10.11` helps.

**Comment by parallels999** [comment]
> Not sure what is affected here. Downgrading phpstan back to 1.10.11 helps.

I have a similar problem with collections and contracts

```php
class MyModel extends \Illuminate\Database\Eloquent\Model implements MyModelContract{
    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    protected static function getCollection(): \Illuminate\Database\Eloquent\Collection
    {
        return static::select()->get();
    }

    /**
     * @return MyModelContract|null
     */
    protected static function getCollectionFirst(): ?MyModelContract
    {
        return static::getCollection()->first();
    }
}
```

ping @szepeviktor, downgrading is the only solution I found

**Comment by szepeviktor** [comment]
@ondrejmirtes What change in https://github.com/phpstan/phpstan/releases/tag/1.10.12 could lead to this?

**Comment by ondrejmirtes** [comment]
@szepeviktor I don't have any context for this error. Please take time to understand how PHPStan was behaving before, how it's behaving now, and open a bug report in PHPStan with thorough description. Thank you.

**Comment by parallels999** [comment]
This is my problem, any ideas?
https://phpstan.org/r/40edc559-8c6b-4376-b9da-34b941703630

**Comment by szepeviktor** [comment]
@parallels999 On my computer it fails with PHPStan v1.10.11

```
Method MyModel::getCollectionFirst() should return MyModelContract|null but returns Model|null.
```

**Comment by parallels999** [comment]
Did you try with laravel or with that simple example i did to show the message i am getting?

**Comment by parallels999** [comment]
@szepeviktor look at this for example https://github.com/spatie/laravel-permission/actions/runs/4681036769/jobs/8293124388#step:6:14

**Comment by magnetas** [comment]
In my original example it IS Laravel & Eloquent. Upgrading to phpstan 1.10.12 causes issues, downgrading back to 1.10.11 "fixes" it again.
Both on my mac and AWS CodeBuild.

**Comment by magnetas** [comment]
It seems 1.10.13 was released 50 minites ago with some fix. Didn’t have a chance to try it out yet

**Comment by szepeviktor** [comment]
Could be useful: https://github.com/spatie/laravel-permission/pull/2397#issuecomment-1505925271

**Comment by magnetas** [comment]
Just confirming the issue is still present with PHPStan v1.10.13

**Comment by canvural** [comment]
```php
/** @var \Illuminate\Database\Eloquent\Collection */
$books = Book::factory()->count(4)->create();
```

is incorrect. Since `Collection` is generic you need to give the generic types. Like so `\Illuminate\Database\Eloquent\Collection<int, Book>` Also you can safely drop the `var` tag. Larastan can understand the call returns a collection.

**Comment by magnetas** [comment]
@canvural you're right, fixing the typehints did the trick. Thank you!

**Comment by Jurigag** [comment]
BTW, I am still having it, as I understand the only option to work around it is to just put proper phpdoc? We use factories in one project quite often to create testing models.

We just do:

```
$report = Report::factory()->create();
$report->id
```

And phpstan tells about `Illuminate\Database\Eloquent\Model::$id`

https://github.com/larastan/larastan/pull/861#issue-936044545

I checked that where those factories were initially developed, changed it to createOne() but still doesn't work.

**Comment by calebdw** [comment]
@Jurigag, 

Here's how to hook up the model/factory for static analysis:

```php
/** @extends Factory<User> */
class UserFactory extends Factory
{
    protected $model = User::class;
    // ...
}

class User extends Model
{
    use HasFactory;
    // ...
    protected static function newFactory(): UserFactory
    {
        return UserFactory::new();
    }
}
```

**Comment by wslawski-printify** [comment]
Okay, that works actually.

**Comment by wslawski-printify** [comment]
But updating tons of models isn't really nice way to solve it now. Is it possible to create some stub for it?

**Comment by szepeviktor** [comment]
> updating tons of models

You can use 20 lines of Rector to do that.

**Comment by wslawski-printify** [comment]
But seems like useless code to add only to satisfy PHPStan. Actually I wrote extension that returns correct type.

Why just not get default value of property if I have it already defined?

**Comment by calebdw** [comment]
What do you mean by this?

> Why just not get default value of property if I have it already defined?

**Comment by wslawski-printify** [comment]
I just used PHP ReflectionClass to get default model value property from there and it works. I guess not really perfect in phpstan extension world and should be avoided but for the needs I have it's good enough.
