### ISSUE TITLE
Models and dynamic properties/attributes

### ISSUE THREAD

**Issue by CalebDW** [nunomaduro/larastan#1622]
- Larastan Version: 2.5.1
- `--level` used: 2
- PHP Version: 8.1

### Description
Hello!

The following assignment is valid on an Eloquent Model:

```php
$user->foo_bar = 'fooBar';
```
where `foo_bar` is not an accessor or table column. The assignment creates an attribute on the model, however, Larastan is failing with the following error:
```
Access to an undefined property App\Models\User::$foo_bar.
```

This is just a temporary, calculated value that I'm appending to the model before I send it to a view so I don't have to convert the model to an array, add the key/value pair to the array, and use array syntax in the blade file. Because it's a temporary value, I also don't want to have to add `@property` docs to the model.

I was reading about [universal object crates](https://phpstan.org/blog/solving-phpstan-access-to-undefined-property#universal-object-crates)  (which the Eloquent Model does act like) and it resolved the error but a little too well---I presume it just assumes anything accessed is a mixed type.

It would be better if it could report on properties/attributes that are accessed but have not been set:

E.g.,
```php
// accessing `foo_bar` will fail because it hasn't been defined
$user->foo_bar;

// accessing `foo_bar` after it's been set won't result in a failure
$user->foo_bar = 'some value';
$user->foo_bar;
```

**Comment by canvural** [comment]
Hi,

This doesn't look like an issue with Larastan itself. This is how static analysis works. Ideally you shouldn't feel to add this temporary properties to the model itself. You can use View Models, DTOs, VOs etc. whatever suits your needs.

**Comment by szepeviktor** [comment]
I wasn't brave enough to give the very same answer.
