### ISSUE TITLE
Parameter #1 `$column` of method Eloquent Builder `where()` fails with `Illuminate\Contracts\Database\Query\Expression`

### ISSUE THREAD

**Issue by bradietilley** [nunomaduro/larastan#1625]
- Larastan Version: v2.5.1
- Laravel Version: v10.8.0
- `--level` used: 6
- Pull request with failing test: N/A (private repo)

### Description

Apologies if I'm just doing something wrong, but since I upgraded Larastan I seem to be getting this phpstan error.

```
 ------ -------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   JsonApi/Filters/WhereDate.php                                                                                                               
 ------ -------------------------------------------------------------------------------------------------------------------------------------------- 
  18     Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::where() expects array<int|string,  
         mixed>|(Closure(Illuminate\Database\Eloquent\Builder): void)|(Closure(Illuminate\Database\Eloquent\Builder):                                
         Illuminate\Database\Eloquent\Builder)|Illuminate\Database\Query\Expression|string, Illuminate\Contracts\Database\Query\Expression given. 
```

For context, I also upgraded Laravel 9 to 10 amongst other changes today. No failing tests, just these phpstan issues which weren't prevalent this morning.

### Laravel code where the issue was found

`app/JsonApi/Filters/WhereDate.php`:

```php
<?php

namespace App\JsonApi\Filters;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use LaravelJsonApi\Eloquent\Filters\Where;

class WhereDate extends Where
{
    /**
     * @param Builder $query 
     * @param mixed $value 
     */
    public function apply($query, $value): Builder
    {
        return $query->where(
            DB::raw('DATE(' . $this->column() . ')'), /** line 18 */
            $this->operator(),
            $this->deserialize($value)
        );
    }
}
```

**DB::raw**

According to the error, phpstan understands that `DB::raw()` returns an instance of `\Illuminate\Contracts\Database\Query\Expression`.

Just to confirm - as per `vendor/laravel/framework/src/Illuminate/Support/Facades/DB.php`, the method phpdoc is defined as such:

```
 * @method static \Illuminate\Contracts\Database\Query\Expression raw(mixed $value);
```

**Builder::where**

According to the error, phpstan is failing to understand that `->where()` parameter #1 (`$column`) accepts an instance of `\Illuminate\Contracts\Database\Query\Expression`.

Just to confirm - as per `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php`, the method phpdoc is defined as such:

```php
    /**
     * Add a basic where clause to the query.
     *
     * @param  \Closure|string|array|\Illuminate\Contracts\Database\Query\Expression  $column
     * @param  mixed  $operator
     * @param  mixed  $value
     * @param  string  $boolean
     * @return $this
     */
    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {
        if ($column instanceof Closure && is_null($operator)) {
            $column($query = $this->model->newQueryWithoutRelationships());

            $this->query->addNestedWhereQuery($query->getQuery(), $boolean);
        } else {
            $this->query->where(...func_get_args());
        }

        return $this;
    }
```

**Comment by szepeviktor** [comment]
Hello!

Our stub overrides that

https://github.com/nunomaduro/larastan/blob/0750017b3d3e1bbe3d0342f3777f09d0c19f91a9/stubs/EloquentBuilder.stub#L221

The difference between the two is `Contracts`

**Comment by szepeviktor** [comment]
Could be duplicate of #1547

**Comment by bradietilley** [comment]
> The difference between the two is Contracts

Didn't notice the lack of `Contracts` 😬.

> Could be duplicate of https://github.com/nunomaduro/larastan/issues/1547

That's the exact same issue but more high-level. I'll close mine and watch theirs.
