### ISSUE TITLE
Falsely reported "Call to undefined static method" if __construct may throw an Exception

### ISSUE THREAD

**Issue by crhg** [nunomaduro/larastan#1630]
- Larastan Version: 2.6.0
- `--level` used: 5

### Description
A 'Call to undefined static method' error occurs when the constructor of the target class of Facade may throw an exception.

If there is no part that throws an exception, no error will occur.

### Laravel code where the issue was found
app/Foo.php:
```php
<?php

namespace App;

class Foo
{
    public function __construct()
    {
        if (config('app.foo') === null) {
            throw new \Exception('app.foo required'); // error will not occur if this line is commented out
        }
    }
    public function foo(): void
    {
        //
    }
}
```

app/FooFacade.php:
```php
<?php

namespace App;

use Illuminate\Support\Facades\Facade;

class FooFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return Foo::class;
    }
}
```

app/SomeClass.php:
```php
<?php

namespace App;

class SomeClass
{
    public function callFoo(): void
    {
        FooFacade::foo();
    }
}
```

Note: The result cache may cause changes to the file that do not change the results, so either `clear-result-cache` before executing the `analyze` command or specify the `--debug` option to the `analyse` command.

**Comment by CalebDW** [comment]
Larastan boots your service container and so the `__construct` method *is* called during the static analysis since the class is being resolved using the container. In this case, Larastan is throwing the exception since `config('app.foo') === null`

**Comment by canvural** [comment]
Exactly what @CalebDW said. Also you can add `/** @mixin Foo */` to top of `FooFacade`, so Larastan will not have to resolve the facade itself.
