### ISSUE TITLE
How to run checks only for 1 file/subdirectory?

### ISSUE THREAD

**Issue by sergeynilov** [nunomaduro/larastan#1640]
When checking fixes in laravel laravel/framework 9.52.5 with nunomaduro/larastan 2.6.0 / PHP 8.1 in some file after 
./vendor/bin/phpstan analyse
command, if there is a way to run checks only for 1 file/subdirectory?

I did not find such option at https://github.com/nunomaduro/larastan docs...

**Comment by szepeviktor** [comment]
`./vendor/bin/phpstan analyse src/1dir/` voilà

**Comment by mad-briller** [comment]
Running the checks against single files can negatively affect performance:
https://phpstan.org/blog/why-you-should-always-analyse-whole-project
