### ISSUE TITLE
How to let know to phpstan that it has some model by used trait of 3rd pluging?

### ISSUE THREAD

**Issue by sergeynilov** [nunomaduro/larastan#1643]
Running 

    ./vendor/bin/phpstan analyse 

in **laravel/framework** 9.52.5 **nunomaduro/larastan** 2.6.0

I got error :

    Call to an undefined method Illuminate\Database\Eloquent\Model::getTranslation().     

  
But this app uses Spatie\Translatable plugin and relative model has Translatable defininions :

```php
use Spatie\Translatable\HasTranslations;

class PageContent extends Model implements HasMedia
{
    use HasTranslations;

    public $translatable = ['title', 'content_shortly', 'content'];
```

   
If there is a way to fix it and say to larastan that this model has  getTranslation method, not using 

     // @phpstan-ignore-line  

 
construction ?

**Comment by mad-briller** [comment]
the issue is that where every you've got the error message from doesn't understand the model is a `PageContent` and not a `Model`, `PageContent` contains the `getTranslation` method, not `Model`

can you provide more context around the code that is causing the error please ?

**Comment by sergeynilov** [comment]
Please look at https://spatie.be/docs/laravel-translatable installation docs : How it is declared in model and used...

**Comment by mad-briller** [comment]
can you show us the code where you are calling `getTranslation`, where the error is being produced?

phpstan believes what you are calling `getTranslation` on is not a `PageContent` but just a plain `Model`, which will not have the trait applied to it

providing the calling context allows us to see where phpstan might be making a mistake, or where the type hasn't been narrowed correctly

**Comment by sergeynilov** [comment]
In first message I show model PageContent.php file and it is used in resource file app/Filament/Resources/PageContentResource.php :

in which I collect dynamic array of TextInputs using getTranslation method of the model :
```
class PageContentResource extends Resource
{
    protected static ?string $model = PageContent::class;
    public static function form(Form $form): Form
    {
        ...
        $localeFields      = [];
        foreach ($locales as $locale) { // show multi language elements for all locales of the app
            $titleLocaleFields[] = TextInput::make('title_' . $locale)
                ->afterStateHydrated(function (TextInput $component, $state) use ($locale) {
                    $pageContentModel = $component->getModelInstance();
                    if ( ! empty($pageContentModel->title)) { // Fill title field only in "edit" mode
                        $component->state($pageContentModel->getTranslation('title', $locale,
                            false));
                    }
                })
                ->required();
        }
        
        Forms\Components\Group::make()
            ->schema($titleLocaleFields)
            ...

```

Is it enough info from me to clear which problem I have ?

**Comment by mad-briller** [comment]
can you add this to the code below `$pageContentModel = $component->getModelInstance();` and then run phpstan and show us the output?

```
\PHPStan\dumpType($pageContentModel);
```

**Comment by szepeviktor** [comment]
I bet it'll be `Illuminate\Database\Eloquent\Model`

**Comment by mad-briller** [comment]
yeah my guess is it's `?Model` from the code, and as such `TextInput::getModelInstance()` is defined to return `?Model`, and either needs to be narrowed or generic, or an `instanceof` needs to be performed instead of the `empty()`

**Comment by szepeviktor** [comment]
> made generic

Choose PHP Generics!

**Comment by sergeynilov** [comment]
I got :
`Call to undefined function PHPStan\dumpType()
`
Have I to  import some classes to my resource file ?

**Comment by canvural** [comment]
Seems not related to Larastan itself.
