### ISSUE TITLE
Call to private method of parent class

### ISSUE THREAD

**Issue by CalebDW** [nunomaduro/larastan#1646]
- Larastan Version: 2.6.0
- `--level` used: 1
- Pull request with failing test:

### Description
I have some custom Eloquent Builder class that we use to add searching functionality to various models. I have followed the [guidance here](https://github.com/nunomaduro/larastan/blob/19866e06d5846f8c17460ce1c1808da8166d3747/UPGRADE.md#custom-eloquent-builders) to add generics to the classes, but PHPstan fails with:
```
Call to private method whereIn() of parent class Larastan\Test\AbstractBuilder<Larastan\Test\TestModel>
```

Below is a test snippet, it is interesting that only some methods have issues (`whereIn`) and others do not 

### Laravel code where the issue was found

```php
<?php

namespace Larastan\Test;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @template TModelClass of \Illuminate\Database\Eloquent\Model
 * @extends \Illuminate\Database\Eloquent\Builder<TModelClass>
 */
class AbstractBuilder extends Builder
{
}

class TestModel extends Model
{
}

/** @extends AbstractBuilder<TestModel> */
class TestBuilder extends AbstractBuilder
{
    public function search(): void
    {
        $this->where('id', 1);
        $this->whereIn('id', [1]);                <------------- this line has issue
        $this->whereHas('testing', fn () => 'foobar');
    }
}
```

**Comment by szepeviktor** [comment]
Do you have a docblock for `AbstractBuilder::newEloquentBuilder`?

**Comment by CalebDW** [comment]
Hmmm, not sure what the solution is... I made `AbstractBuilder` generic and `TestBuilder` properly extends the `AbstractBuilder`

**Comment by szepeviktor** [comment]
I am not sure too!

Maybe `whereIn` is not in https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub

**Comment by szepeviktor** [comment]
Do you have a docblock for TestModel::newEloquentBuilder?

**Comment by CalebDW** [comment]
> Maybe whereIn is not in https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub

That's probably it, it's also missing the `whereJson*` methods as well.

> Do you have a docblock for TestModel::newEloquentBuilder?

No these aren't actually hooked up to the models yet (the AbstractBuilder class needs a refactor and it's on my list to do). Right now they're just used standalone:
```
resolve(TestBuilder::class)
    ->search(...);
```

**Comment by CalebDW** [comment]
I'm also getting this same error for:
- `whereNull`
- all `whereJson*` methods
- `whereIn`
which doesn't make sense as they're all public methods. 

Note that this error goes away when I make the child builder generic:
```php
/** @template TModelClass of Model */
class CustomBuilder extends Builder

// instead of

/** @extends Builder<Model> */
class CustomBuilder extends Builder
```
It also goes away when using a closure:
```php
return $this->where(fn ($q) => $q->whereNull('end_date'));
// instead of
return $this->whereNull('end_date');
```
But neither of these options are desirable solutions.

Why are these methods being marked `private` when they are public and why do methods need to be listed in the stubs (does Larastan have issues with `__call`)? `whereIn` is missing from the stub files, but `whereNull` *is* in the `QueryBuilder` stub and yet still has issues---adding it to the `EloquentBuilder` stub might work, but obviously there shouldn't be a need for duplication and `whereIn` is defined in `QueryBuilder` and not the `EloquentBuilder`.

**Comment by canvural** [comment]
@CalebDW Can you try the latest master? I pushed a fix that might solve this.

**Comment by canvural** [comment]
This should be fixed in the latest master.

**Comment by CalebDW** [comment]
It seems to work, thanks!

**Comment by canvural** [comment]
Released https://github.com/nunomaduro/larastan/releases/tag/v2.6.1
