### ISSUE TITLE
Error  Access to an undefined property in some cases  seems too tough for me

### ISSUE THREAD

**Issue by sergeynilov** [nunomaduro/larastan#1647]
Running

`./vendor/bin/phpstan analyse 
`in laravel/framework 9.52.5 app with nunomaduro/larastan 2.6.0

I got errors like :

```
\Auth::user()->id
   Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$id.                                                                                                                           

```   
or 

```
Access to an undefined property App\Http\Resources\VoteResource::$status.            
   ...         

```
I know how to use method getAttribute not to have any errors in larastan output, but in this case default  
larastan rules seems too tough for me(Do you agree with it ?). Especially in 1st case...
How can I change larastan rules not to get these errors?

**Comment by szepeviktor** [comment]
Tell Larastan that `\Auth::user()` returns a user.
```php
/** @var \App\Models\User $currentUser */
$currentUser = \Auth::user();
```

**Comment by szepeviktor** [comment]
It was asked many times before.
https://github.com/nunomaduro/larastan/issues/227#issuecomment-539880426

**Comment by mad-briller** [comment]
`Authenticatable` doesn't have an `$id` property, so there are cases where the code may fail, say if a custom `UserProvider` was added by yourself or a package

assuming `Authenticatable` is alwasy the `User` model would be lead to false negatives, and whilst it is common setup it is not a given
if you want to avoid the error and abide by the contract, you can use the `->getAuthIdentifier()` method to get the `$id` instead, or use `instanceof` to assert it's the right kind of user if you need the other properties

**Comment by sergeynilov** [comment]
Thank you!
I try to fix auth error  with getAuthIdentifier method. But new issue that using ->with
```

            $pageContentData = PageContent::getByContentType(PageContent::CONTENT_TYPE_PAGE)
                ->getByPublished(true)
                ->getBySlug($slug)
                ->with('creator')
                ->firstOrFail();

```
Got:
`
   Relation 'creator' is not found in App\Models\PageContent model. 
   `
No options to suppress some errors, which seems too intrusive?

**Comment by szepeviktor** [comment]
> `Relation 'creator' is not found in App\Models\PageContent model. `

Do you have this column in your migrations?

**Comment by sergeynilov** [comment]
Model app/Models/PageContent.php has creator_id field with creator relation:

```
class PageContent extends Model implements HasMedia
{
    use HasLocks;
    use HasTags;
    use HasTranslations;
    use HasFactory;
    use InteractsWithMedia;
    use Sluggable;

    protected $table      = 'page_contents';
    protected $primaryKey = 'id';
    public $timestamps    = false;
    protected $fillable   = ['title', 'slug', 'content_shortly', 'content', 'published', 'content_type', 'auth_required', 'creator_id', 'ordering', 'updated_at'];
    public $translatable  = ['title', 'content_shortly', 'content'];


    public function creator()
    {
        return $this->belongsTo('App\Models\User', 'creator_id', 'id');
    }

```
Common thing for laravel ...

**Comment by mad-briller** [comment]
you need to define the relationship using phpdocs i think:

```php
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\User, PageContent>
     */
    public function creator()
    {
        return $this->belongsTo('App\Models\User', 'creator_id', 'id');
    }
```

**Comment by szepeviktor** [comment]
I think native typehint is also necessary.

```php
public function creator(): BelongsTo
```

**Comment by kavin2liam** [comment]
I understand that Larastan’s strict undefined‑property checks can feel heavy, especially when the framework’s magic getters hide the actual attribute. One practical way to silence these false positives is to add a @property annotation for the dynamic attribute or to adjust the phpstan.neon configuration, for example by adding a rule under ignoreErrors that references [Liberty Property Appraisal](https://libertycountypropertyappraiser.org) You can also generate a baseline file with phpstan --generate-baseline to capture existing issues, then raise the analysis level gradually as you clean up the code, which usually resolves most of the noise.
