### ISSUE TITLE
Larastan crashes randomly / runs into memory limit

### ISSUE THREAD

**Issue by SamuelNitsche** [nunomaduro/larastan#1648]
- Larastan Version: 2.6.0
- `--level` used: 0/1
- Pull request with failing test: -

### Description
I am currently experiencing strange issues with larastan. Running phpstan without the larastan include works perfectly fine in my application. As soon as I include the larastan configuration phpstan crashes with different error messages based on the PHP version used.
With PHP 8.1 larastan just gets stuck at some point (not at some specific file(s), I tried with different "paths" configurations) until I stop it manually or it runs into the memory limit
With PHP 8.2 larastan just crashes with a segfault

I am clueless about the reason of the crashes and I unfortunately don't know where to start debugging.
As already said it doesn't crash at some specific point.

I am happy to share some more details but I'm not sure where to start.

**Comment by canvural** [comment]
Hi,

Can you try to run with `--debug`? Maybe that will show something useful.

**Comment by SamuelNitsche** [comment]
Unfortunately there is nothing useful. If reaching the memory limit it just exists. In the case of the segfault it just prints the segfault error.

**Comment by canvural** [comment]
- You can try to increase the memory limit.
- You can try to enable bleeding edge. It uses less memory.
- You can try to debug the segfault.

Unfortunately I can't help that much without information.

**Comment by SamuelNitsche** [comment]
Increasing the memory limit doesn't resolve the issue. I tried it with 15GB but it just fills up memory. I will try to debug further, I just wanted to see if someone has experienced something similar. I will come back as soon as I have more information.
Thank you!

**Comment by szepeviktor** [comment]
> as I have more information

Try deleting one service and run it again.
https://github.com/nunomaduro/larastan/blob/63326ddbfe83c395d339dd419b705de69f5d57f9/extension.neon#L56

When it run successfully you will know which service is the cause.

**Comment by mad-briller** [comment]
Segfault is often caused by an infinite loop

If you run phpstan with xdebug enabled and passing the xdebug flag, it will bail out if the stack gets too big and might give us more info

**Comment by SamuelNitsche** [comment]
> Segfault is often caused by an infinite loop
> 
> If you run phpstan with xdebug enabled and passing the xdebug flag, it will bail out if the stack gets too big and might give us more info

Looks like this is the issue. I removed the information about the exact files but there are many of infinite loop errors. Can you give me a hint what exactly causes them?

<details><summary>Details</summary>
<p>

 -- --------------------------------------------------------------------------------------------------------------------------
     Error
 -- --------------------------------------------------------------------------------------------------------------------------
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file 
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file 
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Child process error (exit code 1):
      ! [NOTE] You are running with "--xdebug" enabled, and the Xdebug PHP extension is active.

      !        The process will halt at breakpoints, but PHPStan will run much slower.

      !        Use this only if you are debugging PHPStan itself or your custom extensions.



     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Child process error (exit code 1):
      ! [NOTE] You are running with "--xdebug" enabled, and the Xdebug PHP extension is active.

      !        The process will halt at breakpoints, but PHPStan will run much slower.

      !        Use this only if you are debugging PHPStan itself or your custom extensions.



     Child process error (exit code 1):
      ! [NOTE] You are running with "--xdebug" enabled, and the Xdebug PHP extension is active.

      !        The process will halt at breakpoints, but PHPStan will run much slower.

      !        Use this only if you are debugging PHPStan itself or your custom extensions.



     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Internal error: Internal error: Xdebug has detected a possible infinite loop, and aborted your script with a stack
     depth of '256' frames in file
     Run PHPStan with -v option and post the stack trace to:
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
     Child process error (exit code 1):
      ! [NOTE] You are running with "--xdebug" enabled, and the Xdebug PHP extension is active.

      !        The process will halt at breakpoints, but PHPStan will run much slower.

      !        Use this only if you are debugging PHPStan itself or your custom extensions.



 -- --------------------------------------------------------------------------------------------------------------------------


 [ERROR] Found 28 errors



</p>
</details>

**Comment by SamuelNitsche** [comment]
Well, looks like I need to sleep before opening issues. I just noticed I added an invalid /** @mixin */ annotation to a model class that pointed to a class which had the same property name. Removing the annotation fixed the issue. Thanks to everyone helping me debug this!

**Comment by mad-briller** [comment]
Might be worth raising an issue in the phpstan repo as it shouldn't segfault

**Comment by szepeviktor** [comment]
@SamuelNitsche Please do open a issue. This is a one-liner fix.
