### ISSUE TITLE
Call to function is_array() with string will always evaluate to false.

### ISSUE THREAD

**Issue by tanaka-thiago-bs** [nunomaduro/larastan#1649]
- Larastan Version: 2.6.0
- `--level` used: 8
- Pull request with failing test:

### Description

In Larastan version 2.6.0, there's an error at level 8 where a valid is_array() check on a variable potentially holding an array or string is flagged as always false. I think this is causing a false positive.

Error message:
Call to function is_array() with string will always evaluate to false.

### Laravel code where the issue was found

```php
use Illuminate\Console\Command;

class TestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test-command {option}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $option = $this->argument('option');
        if(is_array($option)){ // This is the line that is triggering the error.
            $option = implode(',', $option);
        }else {
            $option = (string) $option;
        }
        dump($option);
    }
}
```

This is content of phpstan.neon file.

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app/
        - tests/
    level: 8
```

**Comment by szepeviktor** [comment]
Hello @tanaka-thiago-bs!
Thank you for opening this issue.

`{option}` in your command signature must be a string.

Please see https://laravel.com/docs/10.x/artisan#input-arrays

**Comment by tanaka-thiago-bs** [comment]
@szepeviktor 
Thank you for your answer

I have a question, if I need to work with 2 arrays like the code below, what do you suggest? Because the code is working perfectly as i expected.

![image](https://github.com/nunomaduro/larastan/assets/117956120/f98e7e74-1972-4905-aa69-a55b384c8157)

In this case larastan will cause that error I mentioned before.

![image](https://github.com/nunomaduro/larastan/assets/117956120/05eb62b0-f137-4a00-a432-c8995ba0f471)

**Comment by canvural** [comment]
What is the signature look like for `option2`?

**Comment by canvural** [comment]
Also I'd say you are doing something that is not documented/supported. `{option}` means you are defining an argument named `option` and it can only have 1 value. Not an array of values.

**Comment by tanaka-thiago-bs** [comment]
@canvural 
> What does the signature look like for option2?

![image](https://github.com/nunomaduro/larastan/assets/117956120/25045caf-1025-4617-8950-3b624972c1bb)

**Comment by canvural** [comment]
That means it accepts a single argument. If you want multiple arguments as an array add a star at the end of it.
