### ISSUE TITLE
Cannot call method assertSuccessful() on Illuminate\Testing\PendingCommand|int.

### ISSUE THREAD

**Issue by tanaka-thiago-bs** [nunomaduro/larastan#1650]
- Larastan Version: 2.6.0
- `--level` used: 8
- Pull request with failing test:

### Description

https://laravel.com/docs/10.x/console-tests#success-failure-expectations

I read in the laravel documentation that you can use the "assertSuccesful" method in artisan, but when I run phpstan this error message appears:
```Cannot call method assertSuccessful() on Illuminate\Testing\PendingCommand|int.```

what can I do to fix this error?

### Laravel code where the issue was found

```php
<?php

namespace Tests\Unit;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_that_command_is_running(): void
    {
        $this->artisan('app:test-command')->assertSuccessful();
    }
}
```

**Comment by szepeviktor** [comment]
Hello @tanaka-thiago-bs! 👋🏻 

Here is the return type: https://github.com/laravel/framework/blob/693e0c790ed61f78ac75cb1445df8362f6606a3c/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php#L68-L74
Test for `PendingCommand`.
