### ISSUE TITLE
Incorrect type for foreignIdFor when primary key is uuid

### ISSUE THREAD

**Issue by sanfair** [nunomaduro/larastan#1653]
- Larastan Version: 2.6.0
- `--level` used: 5

### Description
Reference type for a model with `\Illuminate\Database\Eloquent\Concerns\HasUuids` trait resolves to `int` instead of `string`

Here is a minimal repo that reproduces this issue: https://github.com/sanfair/larastan-playground/commit/35d934f0b258fe5c27bbe3a14aa514f4d61f4aee

### The root cause of the problem
Type hardcoded in [src/Properties/SchemaAggregator.php#L204](https://github.com/nunomaduro/larastan/blob/ccac5b25949576807862cf32ba1fce1769c06c42/src/Properties/SchemaAggregator.php#L204)
```php
if ($firstMethodCall->name->name === 'foreignIdFor') {
    if ($firstArg instanceof PhpParser\Node\Expr\ClassConstFetch
        && $firstArg->class instanceof PhpParser\Node\Name
    ) {
        $modelClass = $firstArg->class->toCodeString();
    } elseif ($firstArg instanceof PhpParser\Node\Scalar\String_) {
        $modelClass = $firstArg->value;
    } else {
        continue;
    }

    $columnName = Str::snake(class_basename($modelClass)).'_id';
    if ($secondArg instanceof PhpParser\Node\Scalar\String_) {
        $columnName = $secondArg->value;
    }

    $table->setColumn(new SchemaColumn($columnName, 'int' /** <---- HERE */, $nullable));

    continue;
}
```

#### Lookup type in parsed tables
 Problems:
* If the table name is not default need to use reflection or class instance to find the correct table name
* Need to know the primary column name

Partial implementation:
```php
private function getIdTypeFromRelationModel(string $modelClass): ?string
{
    $tableName = Str::snake(Str::pluralStudly(class_basename($modelClass)));
   
    if (!array_key_exists($tableName, $this->tables)) {
         /* Resolve table using reflection. */
        return null;
    }
 
    $table = $this->tables[$tableName];

    $column = 'id';

    if (!array_key_exists($column, $table->columns)) {
         /* Resolve column using reflection. */
        return null;
    }

    return $table->columns[$column]->readableType;
}

**Comment by szepeviktor** [comment]
Maybe related #1436

**Comment by sanfair** [comment]
> Maybe related #1436

Unrelated. That is a different issue and seems easy to fix.
