### ISSUE TITLE
model, query builder functions not found

### ISSUE THREAD

**Issue by tvbeek** [nunomaduro/larastan#168]
- Larastan Version: 0.3.4
- `--level` used: 2

### Description:
I get errors for the query builder methods on models. (first, where, get, whereDoesntHave, delete, pluck ...)

### Laravel code where the issue was found:

Error: Call to an undefined method App\Http\Controllers\SomeController::first().
```
ModelName::where('publication_id', '=', $id)
                ->where('position', '=', $position + 1)
                ->first();
```

Errors:
Call to an undefined method App\Http\Controllers\LocationController::with().
~~Call to an undefined method App\Http\Controllers\LocationController::where().~~
~~Call to an undefined method App\Http\Controllers\LocationController::orderBy().~~
```
$location = Location::where('site_id', $siteId)->orderBy('title')->with('page')->get();
```

If anyone can help me that should be very nice.

If it is something in larastan and someone can point me in the right direction, I like to try to create a PR.

**Comment by nunomaduro** [comment]
This is an issue in your code. Can you share the exact code where this line exists `Location::where('site_id', $siteId)->orderBy('title')->with('page')->get();`?

**Comment by tvbeek** [comment]
I see that only the `with` error was from that line, the other errors where from more below in the code.

The code (I did remove the rest of the functions that isn't part of this)

```
namespace App\Http\Controllers\Admin;

use App\Location;
use App\Page;

class LocationController extends Controller

    public function index()
    {
        $siteId = $this->findAndSetSessionSiteId('location');

        return view('admin.locations.index', [
            'locations' => Location::where('site_id', $siteId)->orderBy('title')->with('page')->get(),
        ]);
    }

    public function create()
    {
        $pages = Page::where('site_id', $siteId)
            ->where('parent_id', 0) // this is the line wiht the where error
            ->where('active', 1)
            ->orderBy('pos')
            ->get();
        // rest of the function
    }

    public function edit(Location $location)
    {
        $pages = Page::where('site_id', $location->site_id)
            ->where('parent_id', 0)
            ->orderBy('pos') // error of the orderBy function
            ->get();
        // rest of the function
    }
```

**Comment by ThomHurks** [comment]
Not sure that's an issue in his code, I have the exact same issue in various (but not all) calls on Eloquent instances:
```
Call to an undefined method App\Http\Controllers\<snip>::orWhere().
Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation::save().
Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation::sync().
Call to an undefined method App\Http\Controllers\<snip>::get().
Call to an undefined method Illuminate\Database\Eloquent\Relations\HasMany::withTimestamps().
```

**Comment by cosmok** [comment]
I am noticing the same, and, it seems to related to chaining multiple where:
 "nunomaduro/larastan": "^0.3.4"

```
<?php

namespace App;
use App\Models\Customer;

class Stan
{
    public function useWhere()
    {
        return Customer::where('email', 'test@example.com')->where('name', 'test')->first();
    }

    public function useWhereSingleWhere()
    {
        return Customer::where([
                        'email' => 'test@example.com',
                        'name' => 'test'
                      ])->first();
    }

}
```
```
php artisan code:analyse --paths=app/Stan.php 
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------ 
  Line   app/Stan.php                                    
 ------ ------------------------------------------------ 
  10     Call to an undefined method App\Stan::first().  
 ------ ------------------------------------------------ 
```

**Comment by hulkur** [comment]
I think it might be issue with methods returning `$this`. I get same error message for `->count()` missing on controller.

**Comment by alexey-m-ukolov** [comment]
Yes, it looks like a `$this`-related issue.
I have this code:
```
<?php
declare(strict_types=1);

namespace App\Html\Form;

use App\Models\Country;

class CountrySelect extends Select
{
    public function __construct(string $id, string $title, bool $editable = true)
    {
        $options = Country::orderBy('order')->orderBy('name')->pluck('name', 'id');

        parent::__construct($id, $title, $editable, $options);
    }
}
```

And I get this error:
```
Call to an undefined method App\Html\Form\CountrySelect::pluck().
```

Method `pluck` is called on `Country`, but phpstan thinks that it is called on `CountrySelect`.

**Comment by ThomHurks** [comment]
@nunomaduro Do you agree with this analysis? Or do you think it's something else?

**Comment by szepeviktor** [comment]
I think all these should be dynamic return types as they return the same type what they are given.

**Comment by nunomaduro** [comment]
@tvbeek @ThomHurks This issue has been fixed in Larastan `v0.3.10`. 

Please run a `composer update nunomaduro/larastan` and tell me the results.

**Comment by ThomHurks** [comment]
@nunomaduro Thanks! The issue where it thinks that the Eloquent methods should be present on the current file is gone :)

**Comment by tvbeek** [comment]
It is indeed fixed, thanks
