### ISSUE TITLE
How to resolving Auth Facade type correctry

### ISSUE THREAD

**Issue by snmatsui** [nunomaduro/larastan#1693]
- PHPVersion: 7.4
- Larastan Version: 1.0.4
- Laravel Version: 8.83.27
- `--level` used: 2

### Description
Using https://github.com/barryvdh/laravel-ide-helper, I generated _ide_helper.php
```php
namespace { 
class Auth extends \Illuminate\Support\Facades\Auth
{
}
}

namespace Illuminate\Support\Facades { 
class Auth {
        /**
         * @return \App\Models\User|null 
         * @static 
         */ 
        public static function user() {}
}
}
```
and add
```neon
parameters:
    scanFiles:
        - _ide_helper.php
```
to  phpstan.neon.

However, type of  `\Auth::user()` estimated original `Illuminate\Contracts\Auth\Authenticatable` defined by `\Illuminate\Support\Facades\Auth` phpdoc 
```php
\PHPStan\dumpType(auth());
// Dumped type: Illuminate\Auth\AuthManager

\PHPStan\dumpType(auth()->user());
// Dumped type: App\Models\User|null

\PHPStan\dumpType(\Auth::user());
// Dumped type: Illuminate\Contracts\Auth\Authenticatable|null
```

**Comment by szepeviktor** [comment]
Hello! 👋🏻 

Ide Helper and Larastan are not compatible.

**Comment by rudiedirkx** [comment]
I still have this problem - I think - in larastan 2.6.4. How do I tell phpstan that `\Auth::user()` always returns `?\App\Models\User`, not just `Illuminate\Contracts\Auth\Authenticatable`? I can add `@var User` everywhere I call `\Auth::user()`, but that seems silly.

**Comment by calebdw** [comment]
@rudiedirkx, well first update to the latest larastan version

Second, import and use the actual `Illuminate\Support\Facades\Auth` facade and not `\Auth`

**Comment by rudiedirkx** [comment]
We don't import facades. For recognition, all facades are called with `\Name::bla()`. But I'll see how newer larastan does it, and maybe I can fake that. Thanks.

**Comment by canvural** [comment]
`\Auth` alias (for any facade) is not really well supported by PHPStan and Larastan. If you wanna get rid of errors, try to use the proper class names.

**Comment by rudiedirkx** [comment]
I created a few copies of `Larastan\Larastan\ReturnTypes\AuthExtension` for my fav facades 👍 Works perfectly.
