### ISSUE TITLE
Regression: generic `Builder` with union types errors out

### ISSUE THREAD

**Issue by JosephSilber** [nunomaduro/larastan#1699]
- Larastan Version: v2.5 - v2.6.3. It works in v2.4.1.
- `--level` used: 3
- Repository with failing test: https://github.com/JosephSilber/larastan-regression

### Description

Working with a `Builder` whose generic is a union type results in the following error:

```
Internal error: Internal error: Call to undefined method
PHPStan\Type\Generic\TemplateUnionType::getClassName() in file
app\AbstractClass.php
```

![image](https://github.com/nunomaduro/larastan/assets/1403741/996d195e-7331-4b31-a32d-8987898c4fad)

You can see this error by running PHPStan against the latest code in [the demo repository](https://github.com/JosephSilber/larastan-regression).

When running PHPStan against [this commit](https://github.com/JosephSilber/larastan-regression/commit/9e5be368c388d41938852d6624afaec311383fd5), which uses Larastan v2.4.1, there's no error.

### Laravel code where the issue was found

I spent a lot of time creating a small test case. Hope it's now simple enough. What I ended up with is [a repository](https://github.com/JosephSilber/larastan-regression) with 2 simple models: `User` and `Team`. There's nothing special about them.

Then I have these 3 files:

#### `AbstractClass`

```php
<?php

namespace App;

use App\Models\Team;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @template TModel of User|Team
 */
abstract class AbstractClass
{
    /**
     * The failing case.
     *
     * @return TModel
     */
    public function test(int $id): Model
    {
        return $this->getQuery()->findOrFail($id);
    }

    /**
     * @return Builder<TModel>
     */
    abstract public function getQuery(): Builder;
}
```

#### `TeamClass`

```php
<?php

namespace App;

use App\Models\Team;
use Illuminate\Database\Eloquent\Builder;

/**
 * @extends AbstractClass<Team>
 */
class TeamClass extends AbstractClass
{
    /**
     * {@inheritdoc}
     */
    public function getQuery(): Builder
    {
        return Team::query();
    }
}
```

#### `UserClass`

```php
<?php

namespace App;

use App\Models\User;
use Illuminate\Database\Eloquent\Builder;

/**
 * @extends AbstractClass<User>
 */
class UserClass extends AbstractClass
{
    /**
     * {@inheritdoc}
     */
    public function getQuery(): Builder
    {
        return User::query();
    }
}
```

**Comment by sanfair** [comment]
**Indrudused in** 
https://github.com/nunomaduro/larastan/pull/1571

Caused by code on line 83:
https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/src/ReturnTypes/BuilderModelFindExtension.php#L78-L83

**Change that triggers the error.** 
The code before 2.5.0:
https://github.com/nunomaduro/larastan/blob/238fdbfba3aae133cdec73e99826c9b0232141f7/src/ReturnTypes/BuilderModelFindExtension.php#L63-L67
Code after 2.5.0:
https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/src/ReturnTypes/BuilderModelFindExtension.php#L52-L56

**Comment by canvural** [comment]
I'll be taking care of this soon. Thank you 👍🏽
