### ISSUE TITLE
 Call to an undefined method T of

### ISSUE THREAD

**Issue by Geovanek** [nunomaduro/larastan#1705]
- Larastan Version: 2.6.4
- `--level` used: 2
- Pull request with failing test:
![image](https://github.com/nunomaduro/larastan/assets/7670960/c113ae6a-c3bc-4d54-a754-8971679818be)

### Description
I tried using generics, but I couldn't solve this error.

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Model;

/** @template T of Model */
final class TagsService
{
    /**
    * @param T $model
    */
    public function tagsAssociateOrCreate(Model $model, array $tags): void
    {
        foreach ($tags as $tag) {
            $model->tags()->firstOrCreate(['name' => $tag]);
        }
    }
}
```

The code is working normally but when running phpstan analyze it does return this error.

Is there anything that I'm missing?

**Comment by Geovanek** [comment]
For example, `@template T of Competitions`??

But then, whenever I add the `tags()` relationship to a new model, I have to come into the service and add a new comment.

**Comment by szepeviktor** [comment]
You could use an interface for that.
