### ISSUE TITLE
publicPath() declaration fatal error in Laravel v9

### ISSUE THREAD

**Issue by InToSSH** [nunomaduro/larastan#1716]
- Larastan Version: 2.6.4
- Laravel version: 9.52
- PHP Version: 8.2
- `--level` used: 3
- Pull request with failing test: None

### Description
As soon as I enable this extension, when any file is analysed inside the PHPStorm, I get this error.
```
Declaration of Illuminate\Foundation\Application::publicPath() must be compatible with Illuminate\Contracts\Foundation\Application::publicPath($path = '')
 in vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 453 
```

phpstan.neon settings
```neon
parameters:
    level: 3
    paths:
        - app/
        - Modules/
```

### Laravel code where the issue was found

```php
    /**
     * Get the path to the public / web directory.
     *
     * @return string
     */
    public function publicPath()
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'public';
    }

```

**Comment by peterjbassi** [comment]
This error occurs for me as well, and prevents PHPStan from working at all.

A very temporary work-around is to simply silence the fatal error by "correcting" the referenced code. Of course, you'll have to do this any time you get a new copy of the file, which can get annoying depending on your workflow. 


```php
    /**
     * Get the path to the public / web directory.
     *
     * @return string
     */
    public function publicPath($path = '')
    {
        return $this->basePath . DIRECTORY_SEPARATOR . 'public';
    }
```

**Comment by szepeviktor** [comment]
It is in Laravel v9 only.
Fixed in v10.
https://github.com/search?q=repo%3Alaravel%2Fframework%20%22function%20publicPath%22&type=code

**Comment by canvural** [comment]
`publicPath` is not even in the contract in Laravel 9.x: https://github.com/laravel/framework/blob/v9.52.15/src/Illuminate/Contracts/Foundation/Application.php I don't know how you can get this error.

**Comment by cweiske** [comment]
I also have this with a freshly updated laravel 9.52.20 installation.

My problem was that I had larastan installed both globally and locally, and used the global installation to run checks on the local application. Those versions conflicted.
