### ISSUE TITLE
ModelName->whereRelation returns plain Model

### ISSUE THREAD

**Issue by romek-dev** [nunomaduro/larastan#1717]
- Larastan Version: 2.0.0
- `--level` used: 3
- Pull request with failing test:

### Description
I am getting the error: 
``` 
Method App\Models\Template::getMasterTemplateForProject() should return
 App\Models\Template|null but returns
 Illuminate\Database\Eloquent\Model|null. 
``` 
### Laravel code where the issue was found

```php
public static function getMasterTemplateForProject($project_id): ?Template
    {
        return Template::where('project_id', $project_id)
            ->whereRelation('type', 'name', '=', 'master')
            ->first();
    } 
```

### With this code it doesn't show an error:
```php
    public static function getMasterTemplateForProject($project_id): ?Template
    {
        return Template::where('project_id', $project_id)
            ->whereHas('type', function ($query) {
                $query->where('name', 'master');
            })
            ->first();
    }
```

**Comment by szepeviktor** [comment]
Hello!

We have a passing test for `whereRelation`
https://github.com/nunomaduro/larastan/blob/9dbd4cf22cae0ca2956ddd4fa797ce97848353e4/tests/Type/data/where-relation.php#L20

**Comment by romek-dev** [comment]
Interesting, then it seems I might be doing something wrong in my code 🤔 
I will keep the ->whereHas solution in my code for now though 😄

**Comment by romek-dev** [comment]
I just updated to the newest version (2.6.4) and now it works with ```whereRelation``` as well 👍
