### ISSUE TITLE
private functions and __callStatic not detected

### ISSUE THREAD

**Issue by hailwood** [nunomaduro/larastan#173]
- Larastan Version: 0.3.4
- `--level` used: 5 (default)

### Description:
A package which has a method defined as private, but then also defines a `__callStatic` handler is being detected as a false positive.

We're using Rodenastyle/stream-parser 

It defines `private function xml(String $source);` here https://github.com/Rodenastyle/stream-parser/blob/master/src/StreamParser.php#L34

It uses a Trait called `Facade` which defines a `__callStatic` method as shown here https://github.com/Rodenastyle/stream-parser/blob/master/src/Traits/Facade.php#L14

Meaning out calls look like `StreamParser::xml($filePath)->each(...)` which is totally valid, however larastan is throwing out

>Static call to instance method Rodenastyle\StreamParser\StreamParser::xml(). 

Of interest, PHPstorm also detects there is something weird, but has a better understanding of what's going on 
![image](https://user-images.githubusercontent.com/709773/47318868-b5a35f00-d6a9-11e8-9806-01d86c68b445.png)

**Comment by canvural** [comment]
This is not really a `Larastan` issue.

**Comment by szepeviktor** [comment]
@hailwood You could teach phpstan with a very simple one-file extension to understand `__callStatic` https://github.com/phpstan/phpstan#class-reflection-extensions
