### ISSUE TITLE
found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded

### ISSUE THREAD

**Issue by mikemastercorp** [nunomaduro/larastan#1736]
- Larastan Version: 2.0
- `--level` used: dev
- Pull request with failing test: N/A
- PHP version: 8.1
- Server: Apache 2.4 + nginx
- OS: Windows 10
- Development environment: local
- Commands issued as: administrative privileges console or non-administrative.

### Description
On a fresh Laravel 10.10 project created by: `composer create laravel/laravel test.local` while trying to install Larastan 2.0 I got the following message;
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nunomaduro/larastan 2.0 -> satisfiable by nunomaduro/larastan[2.0.0].
    - nunomaduro/larastan 2.0.0 requires illuminate/console ^9 -> found illuminate/console[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Retried creating multiple times the project using alternative method: Laravel new test.local and still got the same issue but any other module required by the project got installed (e.g. filament, pint etc)

**Comment by szepeviktor** [comment]
Try installing a newer version of Larastan
```bash
composer require --dev "nunomaduro/larastan:^2.0"
```

**Comment by mikemastercorp** [comment]
Well, I've tried issuing the suggested command and got still the same reply.
Any other ideas or suggestions? I am not sure why but I've tested on few spare PCs I have at home by just installing npm/composer, creating a new project and trying to install larastan and they all failed the same way stating that I have the required illuminate/console but it is not loaded because of some conflict.

**Comment by szepeviktor** [comment]
> OS: Windows 10

Oh no!
The caret character may be misinterpreted on Windows.
Could you edit `composer.json` directly?
