### ISSUE TITLE
Method Maatwebsite\Excel\Sheet::styleCells() invoked with 2 parameters, 3 required.

### ISSUE THREAD

**Issue by CeansBzh** [nunomaduro/larastan#1742]
- Larastan Version: 2.6.4
- `--level` used: 2

### Description
I'm trying to use the macro provided in the documentation of the Laravel Excel package (https://docs.laravel-excel.com/3.1/exports/extending.html#customize), but I'm getting the following error :

`Method Maatwebsite\Excel\Sheet::styleCells() invoked with 2 parameters, 3 required.`

### Laravel code where the issue was found

_AppServiceProvider.php_
```php
Sheet::macro('styleCells', function (Sheet $sheet, string $cellRange, array $style) {
     $sheet->getDelegate()->getStyle($cellRange)->applyFromArray($style);
});
```

_LeavesExport.php_
```php
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $event->sheet->styleCells(
                    'A1:ZZ1',
                    [
                        'fill' => [
                            'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                            'color' => [
                                'argb' => \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK,
                            ],
                        ],
                        'font' => [
                            'bold' => true,
                            'size' => 13,
                            'color' => [
                                'argb' => \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE,
                            ],
                        ],
                    ]
                );
            },
        ];
    }
```

**Comment by canvural** [comment]
Hi,

The error message is clear. Looks like you forgot to pass the sheet as the first argument.

**Comment by szepeviktor** [comment]
@canvural Isn't the first parameter the object that the macro is called upon?

**Comment by CeansBzh** [comment]
@canvural Sorry I didn't mention this in my first message, but passing manually the "$sheet" parameter causes an error :

```Maatwebsite\Excel\Sheet::App\Providers\{closure}(): Argument #2 ($cellRange) must be of type string, Maatwebsite\Excel\Sheet given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 123```

Code causing the error :

_LeavesExport.php_
```php
public function registerEvents(): array
{
    return [
        AfterSheet::class => function (AfterSheet $event) {
            $event->sheet->styleCells(
                $event->sheet,
                'A1:ZZ1',
                [
                    'fill' => [
                        'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                        'color' => [
                            'argb' => \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK,
                        ],
                    ],
                    'font' => [
                        'bold' => true,
                        'size' => 13,
                        'color' => [
                            'argb' => \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE,
                        ],
                    ],
                ]
            );
        },
    ];
}
```
It seems that the fact that this is a macro isn't really understood by PHPStan/Larastan.

**Comment by CeansBzh** [comment]
For anyone with the same issue, I added this to my phpstan.neon config file to ignore the error for the meantime:
```
ignoreErrors:
   - '#[a-zA-Z0-9\\_]+ Maatwebsite\\Excel\\Sheet::styleCells\(\) [a-zA-Z0-9\\_]+.#'
```

**Comment by mad-briller** [comment]
> @canvural Isn't the first parameter the object that the macro is called upon?

late to the party here but no, `Macroable` [uses](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Macroable/Traits/Macroable.php#L120) `bindTo()` so that the `$this` of the closure is the object it is called on

the excel package is [subverting this behaviour](https://github.com/SpartnerNL/Laravel-Excel/blob/3.1/src/DelegatedMacroable.php#L26) itself and so it is unlikely Larastan will ever support this use case.

**Comment by szepeviktor** [comment]
This is an excellent comment.

**Comment by CeansBzh** [comment]
Closing the issue because, as said above, this is an issue with Laravel-Excel rather than Larastan.
