### ISSUE TITLE
Undefined property on Fluent class

### ISSUE THREAD

**Issue by CalebDW** [nunomaduro/larastan#1743]
- Larastan Version: 10.22.0
- `--level` used: 8
- Pull request with failing test:

### Description
Hello!

I'm getting an `undefined property` error on a Fluent class, I saw a PR (#924) was rejected, however, as Fluent is by definition a universal object crate this really needs to be fixed by the package (either by adding it to the universalObjectCratesClasses or developing an extension)---shouldn't expect everyone to have to add the class to their own config just to use it.

Thanks!

**Comment by canvural** [comment]
Hi,

I do not want to ignore stuff on behalf of users. We did that in the past, and it was annoying in some scenarios. Also, PRs are welcome if you want to develop an extension for it. But I don't think we need to keep an issue open for it.

**Comment by CalebDW** [comment]
@canvural, what do you envision the extension would look like?
