### ISSUE TITLE
[Bug]: generics - should return T of [class] but returns [class] #9934

### ISSUE THREAD

**Issue by iamarpitpatidar** [nunomaduro/larastan#1745]
- Larastan Version: #.#.#
- `--level` used: 9

### Description
Phpstan error:
```
Method App\Repositories\BaseRepository::create() should return T of Illuminate\Database\Eloquent\Model
 but returns Illuminate\Database\Eloquent\Model.
```

I've checked https://github.com/phpstan/phpstan/issues/4411 https://github.com/phpstan/phpstan/issues/4412 but I am still not sure what's wrong with the code

### Laravel code where the issue was found

```php
<?php

namespace App\Repositories;

use App\Contracts\BaseRepositoryInterface;
use Illuminate\Database\Eloquent\Model;

/**
 * @phpstan-template T of Model
 */
class BaseRepository implements BaseRepositoryInterface
{
    protected Model $model;

    /**
     * @param Model $model
     *
     * @phpstan-param T $model
     */
    public function __construct(Model $model)
    {
        $this->model = $model;
    }

    /**
     * @param array<string, mixed> $attributes
     * @return Model
     *
     * @phpstan-return T
     */
    public function create(array $attributes): Model
    {
        return $this->model->create($attributes);
    }
}
```

**Comment by szepeviktor** [comment]
Hello Arpit! 👋🏻

Could you try the following?
```php
    /** @phpstan-var T */
    protected Model $model;
```

**Comment by iamarpitpatidar** [comment]
@szepeviktor this works, but is there some way we can automatically assign these generics or something ?

**Comment by szepeviktor** [comment]
No. There is none.

**Comment by iamarpitpatidar** [comment]
@szepeviktor Hey sorry I was wrong, for some reason it's still not working.. any other ideas ?

**Comment by canvural** [comment]
Hi,

This does not have anything to do with Larastan itself.

But this is expected. PHPStan does not have enough information while analyzing the class itself. But it'll work correctly with child classes: https://phpstan.org/r/9787ed3d-7034-4fda-b297-5f08825814ac
