### ISSUE TITLE
Custom Eloquent Builder and Chaining

### ISSUE THREAD

**Issue by amooij** [nunomaduro/larastan#1747]
- Larastan Version: 2.6.4
- `--level` used: 9
- Pull request with failing test:

No PR, custom repo.

### Description

It appears that chaining methods in a custom builder leads to this error:
```Dynamic call to static method```

### Laravel code where the issue was found

https://github.com/amooij/custom-builder-test

**Comment by szepeviktor** [comment]
Hello @amooij!

If you comment out other extensions you will get an `OK`.

**Comment by amooij** [comment]
Hi, that works, but what I'd really like to figure out is how to make the two work together.

**Comment by szepeviktor** [comment]
The Laravel Framework does things `phpstan-strict-rules` says _no_ to.

**Comment by amooij** [comment]
I know, but the thing is, if I don't use a custom eloquent builder, I get none of these errors. So I'm guessing there's a place somewhere in Larastan where I can tell it to accept any subclass of Eloquent Builder.
I tried modifying the stub, but that didn't work.

**Comment by canvural** [comment]
Hi,

This is a know issue with `phpstan-strict-rules` Subscribe to [this](https://github.com/phpstan/phpstan-strict-rules/issues/140) issue for further info.
