### ISSUE TITLE
[API Resources] Call to an undefined method

### ISSUE THREAD

**Issue by johanvanhelden** [nunomaduro/larastan#176]
- Larastan Version: v0.3.4
- `--level` used: 5

### Description:
Laravel has [Eloquent Resources](https://laravel.com/docs/5.7/eloquent-resources) to make it easy to standardize model output for API usage.

In my case I've got the [Spatie Permissions](https://github.com/spatie/laravel-permission) package installed to handle roles and permissions. That package adds a `getAllPermissions()` method to the User model. And this works great. However, Larastan does not detect this and flags it as an undefined method.

### Laravel code where the issue was found:

```php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\Resource;

/**
 * Defines a user resource.
 */
class UserResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return array
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function toArray($request)
    {
        return [
            'name'        => $this->name,
            'email'       => $this->email,
            'permissions' => $this->getAllPermissions()->pluck('name')->toArray(),
        ];
    }
}
```

**Comment by szepeviktor** [comment]
See https://github.com/spatie/laravel-permission/blob/71e28f3d12b77587351c09c608fe667e477a65d8/src/Models/Role.php#L18

**Comment by johanvanhelden** [comment]
I'm sorry, but is that directed to me? I am not sure what to do with that information.

**Comment by szepeviktor** [comment]
Actually I don't understand that `class Role` declares `getAllPermissions()` but `$this` in the above code is of `UserResource`.

**Comment by johanvanhelden** [comment]
In my code, it looks like this:

Building the resource:
```
'user' => new UserResource(auth()->user()),
```
The model looks like this:
```
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

/**
 * Defines a user.
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasRoles;

    <snip>
}
```

And because it has the roles trait, it also has the permission trait.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by johanvanhelden** [comment]
I can not reproduce this anymore. So this seems to be fixed in a newer version of either PHPStan or Larastan.

**Comment by johanvanhelden** [comment]
I am sorry, it still happens.

**Comment by newlinkcapital** [comment]
+1, any workarounds?

**Comment by bolechen** [comment]
+1

**Comment by Resin01** [comment]
Any solution for this yet?

**Comment by ondrejmirtes** [comment]
Did you send or proposed one? If not, why don’t you do it?

**Comment by canvural** [comment]
You can add `@mixin <ModelClass>` to the docblock of your resource class.

**Comment by sergiy-petrov** [comment]
@canvural not working in my case :(
![image](https://user-images.githubusercontent.com/8986207/80864781-7e920e80-8c8d-11ea-8d6b-428495182c08.png)

**Comment by SagarNaliyapara** [comment]
Any better solution or workaround for this issue? can we reopen?

**Comment by SagarNaliyapara** [comment]
Just found a better solution from Upgrade guide - https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#eloquent-resources

May help someone

**Comment by johanvanhelden** [comment]
> Just found a better solution from Upgrade guide - https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#eloquent-resources
> 
> May help someone

Yeah, this is the solution I have been using.

**Comment by SagarNaliyapara** [comment]
@johanvanhelden Another solution would be https://github.com/nunomaduro/larastan/issues/583#issuecomment-1050528014 If you prefer one line docblock

**Comment by canvural** [comment]
@SagarNaliyapara @johanvanhelden `JsonResource` is not generic anymore. I already wrote the solution to this problem 4 years ago: https://github.com/nunomaduro/larastan/issues/176#issuecomment-542889501
