### ISSUE TITLE
Feature Request: Prevent using a trait with the same name twice

### ISSUE THREAD

**Issue by dammy001** [nunomaduro/larastan#1763]
- Larastan Version: 2.6.4
- `--level` used: 5

### Description

Larastan should be able to prevent this.

### Laravel code where the issue was found

```php
class Controller extends BaseController
{
    use ValidatesRequests;
    use ValidatesRequests;
}
```

**Comment by canvural** [comment]
Hi,

This is not in the scope of Larastan. PHPStan should handle it.

**Comment by szepeviktor** [comment]
PHPCS has `PSR12.Traits.UseDeclaration` - maybe that is more suitable for this purpose.
