### ISSUE TITLE
url() helper returns UrlGenerator|string

### ISSUE THREAD

**Issue by devfrey** [nunomaduro/larastan#177]
- Larastan Version: 0.3.4
- `--level` used: 6

### Description:
When using the `url()` helper provided by Laravel, it returns an instance of `Illuminate\Contracts\Routing\UrlGenerator` when the `$path` parameter is `null` (which it is by default). But when providing a string to the `url()` method, it always returns a `string`.

Passing the return result of the url() method to a function that requires a string, raises an error:
```
Parameter #2 $url of method Illuminate\Notifications\Messages\SimpleMessage::action() expects string, Illuminate\Contracts\Routing\UrlGenerator|string given.
```

### Laravel code where the issue was found:
```php
$redirectTarget = url('http://somewebsite.com');
```

**Comment by szepeviktor** [comment]
We are open to a PR!
