### ISSUE TITLE
Redis::connect(): php_network_getaddresses: getaddrinfo for  failed: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by gms8994** [nunomaduro/larastan#1771]
- Larastan Version: 2.6.4
- `--level` used: 7
- Pull request with failing test: N/A

### Description

This is a little bit of a weird one. When the phpstan cache is empty (`phpstan clear-result-cache`), I get the Redis::connect error when analyzing code (`phpstan analyse`). If I continue to run phpstan without modifying anything, I continue to get the error. However, as soon as I modify the file in question (add a line, etc), the error goes stops appearing on the next `phpstan analyse` run. Additionally, this only seems to happen when the Redis pecl package is installed. 

### Error returned
```
 ------ ------------------------------------------------------------------------------------------------------------------- 
  Line   app/Providers/AppServiceProvider.php                                                                               
 ------ ------------------------------------------------------------------------------------------------------------------- 
  18     Redis::connect(): php_network_getaddresses: getaddrinfo for  failed: nodename nor servname provided, or not known  
 ------ -------------------------------------------------------------------------------------------------------------------
```

### Laravel code where the issue was found

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Redis;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     */
    public function register() : void
    {
        $this->app->singleton(Redis::class, function ($app) {
            $pubSubRedis = new Redis();
            $pubSubRedis->connect('127.0.0.1', 6379);
            $pubSubRedis->select(1);

            return $pubSubRedis;
        });
    }
}
```

**Comment by szepeviktor** [comment]
Hello!

Larastan boots up the framework, so this code actually runs.
Please see https://github.com/nunomaduro/larastan/issues/1196#issuecomment-1075465984

**Comment by gms8994** [comment]
Why would code inside a singleton closure defined in a ServiceProvider execute?

**Comment by szepeviktor** [comment]
I do not know.

**Comment by mad-briller** [comment]
it executes because larastan boots the container and tries to resolve things from the container to get an accurate understanding of what `$app->make(Redis::class)` actually returns because `make()` can take arbitrary strings, such as `'config'` aswell as `class-strings`.

larastan isn't using fully static analysis because there is a lot of "magic" in laravel, in the past @canvural has suggested he would like to move away from this approach but it is a hard problem to solve

**Comment by mad-briller** [comment]
is there a stack trace that is output or do you only get that error ?

**Comment by szepeviktor** [comment]
Issue `phpstan analyse --debug`
