### ISSUE TITLE
How  to mark variable $filter_published_at  as invalid ?

### ISSUE THREAD

**Issue by sergeynilov** [nunomaduro/larastan#1775]
If there is a way with larastan 2.6 in laravel 10 to mark variable
`$filter_published_at`

as invalid, but 
`$filterPublishedAt`
as valid ?

**Comment by mad-briller** [comment]
you should use phpcs for this kind of rule rather than larastan, as phpcs is more interested in formatting / style:

https://github.com/squizlabs/PHP_CodeSniffer
https://stackoverflow.com/questions/45530721/what-sniff-needs-to-be-used-to-enforce-a-camelcase-variable-naming-convention
