### ISSUE TITLE
Undefined method when calling a scope from another scope

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1776]
- Larastan Version: 2.6.4
- `--level` used: 2
- Pull request with failing test:

### Description
Hello!

I have several scopes that reference other scopes in the same model, and  PHPStan fails with 
```
 Call to an undefined method Illuminate\Database\Eloquent\Builder::<scope>().   
```

Example:
```php
    public function scopeExists(Builder $query): Builder
    {
        return $query->where('exists', true);
    }
    public function scopeActive(Builder $query): Builder
    {
        return $query->exists()->where(...);
    }
```
yields
```
 Call to an undefined method Illuminate\Database\Eloquent\Builder::exists().   
```

Thanks!

**Comment by szepeviktor** [comment]
This is a known issue reported several times.

**Comment by szepeviktor** [comment]
I myself also bumped into it a project!

**Comment by canvural** [comment]
You have to add the generic type for query parameter. Like Builder<User>

**Comment by calebdw** [comment]
> You have to add the generic type for query parameter. Like Builder

This should be something that the plugin can do automatically?

**Comment by szepeviktor** [comment]
Rector can do ANYthing.

**Comment by canvural** [comment]
> > You have to add the generic type for query parameter. Like Builder
> 
> This should be something that the plugin can do automatically?

In some cases it already does. But in this example it cannot unfortunately. Currently I don't have time to explain the technical reasons. Maybe later.
