### ISSUE TITLE
Calling model scope on relation fails with custom Builders

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1777]
- Larastan Version: 2.6.4
- `--level` used: 2

### Description
Hello!

I'm trying to call a model scope on a relation that has the proper docs:
```php
$schedules = $this->station->schedules()
    ->forDate($this->date)
    // ...

// Station
/** @return BelongsToMany<Schedule> */
public function schedules(): BelongsToMany
{...}

```
but it errors with:

```
Call to an undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany<App\Models\Schedule>::forDate().
```

Thanks!

**Comment by szepeviktor** [comment]
Could you show `Schedule::forDate`?

**Comment by calebdw** [comment]
So I am using a custom query builder, but everything's been hooked up properly so it shouldn't matter:

```php
class Schedule extends Model
{
    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return ScheduleBuilder<self>
     */
    public function newEloquentBuilder($query)
    {
        return new ScheduleBuilder($query);
    }

}

/** @extends Builder<Schedule> */
class ScheduleBuilder extends Builder
{
    public function forDate(?CarbonInterface $date = null): self
    {
        // ...
    }
}
```

**Comment by szepeviktor** [comment]
The return type is missing from `newEloquentBuilder`.
https://github.com/nunomaduro/larastan/blob/2.x/UPGRADE.md#upgrading-to-051-from-050

**Comment by canvural** [comment]
I'll check this after holidays.

**Comment by calebdw** [comment]
Hmmm, I left out the abstractions because I didn't think it was the cause of the issue, but perhaps my generics aren't hooked up properly so here goes:

The project I work on has a TON of models and I don't want to have to copy/paste the same block of code around. We also use a common Model and Builder class for common functionality. Due to this, I've tried to make the common classes generic to reduce duplication.

```php
/**
 * @template TBuilder of CommonBuilder
 */
abstract class AbstractModel extends EloquentModel
{
    /** @var class-string<TBuilder> */
    protected static string $builder = CommonBuilder::class;

    /** @return TBuilder */
    public static function query()
    {
        return parent::query();
    }

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return TBuilder<static>
     */
    public function newEloquentBuilder($query)
    {
        return new static::$builder($query);
    }
}

/**
 * @template TModelClass of AbstractModel
 * @extends \Illuminate\Database\Eloquent\Builder<TModelClass>
 */
class CommonBuilder extends Builder
{
    /** @var TModelClass */
    protected $model;
}

/** @extends CommonBuilder<Schedule> */
class ScheduleBuilder extends CommonBuilder
{
    public function forDate(?CarbonInterface $date = null): static
    {
        return $this->where(...);
    }
}

/** @extends AbstractModel<ScheduleBuilder> */
class Schedule extends AbstractModel
{
    protected static string $builder = ScheduleBuilder::class;
}
```

**Comment by canvural** [comment]
I found the issue.

`TBuilder<static>` is not supported by PHPStan. Template types itselves can't be generic. There was a feature request for PHPStan, but couldn't find now.

Closing this because it is not directly related to Larastan. Feel free to open a new issue if you replicate it without the `TBuilder<static>` part.

**Comment by calebdw** [comment]
@canvural, can you recommend a better way of hooking up all the generics to make this work without changes to Larastan? I did mention that what I have now might not be correct so I'm all ears for some suggestions

**Comment by canvural** [comment]
> @canvural, can you recommend a better way of hooking up all the generics to make this work without changes to Larastan? I did mention that what I have now might not be correct so I'm all ears for some suggestions

The setup looks mostly correct. Try it only with `TBuilder` instead of `TBuilder<static>`

**Comment by calebdw** [comment]
@canvural, thanks I'll give that a shot.

Also, is this the PR you were referring to?

https://github.com/phpstan/phpstan/issues/5512

If so, then the issue appears to be with `static<T>` rather than `T<static>`---the latter appears to work just fine.

CC: @ondrejmirtes

**Comment by ondrejmirtes** [comment]
I don't have the context, I just came here to say that generic `static<T>` isn't fully understood by PHPStan, only `static`.

**Comment by calebdw** [comment]
@ondrejmirtes, thanks for the confirmation---is `T<static>` supported by PHPStan on the other hand?

**Comment by ondrejmirtes** [comment]
@calebdw Please try it on phpstan.org/try and if it doesn't do what you want please open an issue or discussion in PHPStan's repo.

**Comment by calebdw** [comment]
@canvural, 

> TBuilder<static> is not supported by PHPStan. Template types itselves can't be generic. There was a feature request for PHPStan, but couldn't find now.

PHPStan has no issues with `TBuilder<static>` so not sure that's the issue...

https://phpstan.org/r/88538213-a280-47dc-95cb-415f547170f7

**Comment by canvural** [comment]
I fixed your example to actually call the method: https://phpstan.org/r/960a322b-5973-4254-8a27-cfcc1ee9a82b

**Comment by ondrejmirtes** [comment]
Both PHPStan 1.12.17 and PHPStan 2.1.3 will understand generic `static<...>`: https://github.com/phpstan/phpstan-src/commit/0c1f22ad73fea06e7ef3c5ea0b936700057f6062

**Comment by calebdw** [comment]
Awesome, thanks!
