### ISSUE TITLE
Variables created by `extract` are not recognized

### ISSUE THREAD

**Issue by jhcastaneda** [nunomaduro/larastan#1781]
- Larastan Version: 2.6.4
- `--level` used: 5
- Pull request with failing test:

### Description

Hello!

When receiving an array in a method I am applying `extract($data)`, larastan tells me that the variables contained in the array may not be defined, which is not the case.

#### Errores!
```bash
308    Variable $variable1 might not be defined.
308    Variable $variable2 might not be defined.
308    Variable $variable3 might not be defined.
308    Variable $variable4 might not be defined.
308    Variable $variable5 might not be defined.
```

### Laravel code where the issue was found

```php
public function create(array $data)
    {
        extract($data);
        ..... // remaining logic of the function
    }
```
Thanks!

**Comment by rmunate** [comment]
This happens to me very often and I'm tired of ignoring this error in the .neon

**Comment by szepeviktor** [comment]
`extract` is not your friend. That is all.
The PHP language has bad parts.

**Comment by canvural** [comment]
Hi,

This is not related to Larastan. Please report it to PHPStan. But first try to replicate the error on https://phpstan.org/try
