### ISSUE TITLE
Non-Standard Laravel Location Support?

### ISSUE THREAD

**Issue by marktinsley** [nunomaduro/larastan#1783]
### Description

Hey! I was just wondering if there is or will be support for non-standard locations for Laravel directories.

In a project I'm working in, it's being transitioned to Laravel. Right now, the `app/` directory is not in the root of the repo but under a directory that is in the root of the repo.

Larastan is having trouble finding Laravel's bootstrap file. I think that directory difference is why.

```
Note: Using configuration file /var/www/html/phpstan.neon.
Exception thrown in /var/www/html/vendor/nunomaduro/larastan/bootstrap.php on line 22 while loading bootstrap file /var/www/html/vendor/nunomaduro/larastan/bootstrap.php: Could not find Laravel bootstrap file nor Testbench is installed. Install orchestra/testbench if analyzing a package.
```

**Comment by szepeviktor** [comment]
Hello Mark!
Thank you for your report.

Although I cannot answer your question you can modify our bootstrap code right now.
https://github.com/nunomaduro/larastan/blob/51028c0aba0d8756f7d9e9972ed74e7d34976958/bootstrap.php#L17

**Comment by szepeviktor** [comment]
... or you may start PHPStan from the folder where `bootstrap/app.php` is.
https://github.com/nunomaduro/larastan/blob/51028c0aba0d8756f7d9e9972ed74e7d34976958/bootstrap.php#L15

**Comment by marktinsley** [comment]
> ... or you may start PHPStan from the folder where `bootstrap/app.php` is.
> 
> https://github.com/nunomaduro/larastan/blob/51028c0aba0d8756f7d9e9972ed74e7d34976958/bootstrap.php#L15

This worked fine! Thank you!
