### ISSUE TITLE
More frequent release cadence?

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1784]
Hello!

Would it be possible to cut releases more frequently? The last release was almost 6 months ago and there's a good deal  of changes sitting on `2.x` and `master`.

Thanks!

**Comment by szepeviktor** [comment]
We are low on human resources.

**Comment by calebdw** [comment]
No worries! I understand 🙂 

Is there anything I can do to help?

**Comment by canvural** [comment]
Hi,

I just made a new release. And from now on I'll try to keep it more up-to-date. There were some private life stuff happening for the past 6 months, but seems like now I can spend more time again for OSS.

**Comment by calebdw** [comment]
@canvural, I totally get it---my daughter has just been in the hospital for the past week.

Thanks for the release!
