### ISSUE TITLE
README file links to CHANGELOG.md, but it no longer exists.

### ISSUE THREAD

**Issue by robertatcd** [nunomaduro/larastan#1789]
- Larastan Version: 2.6.0
- `--level` used:
- Pull request with failing test:

### Description

README file links to CHANGELOG.md, but it was removed in v2.6.0.

I didn't want to just remove the link, as I'm unsure whether something replaced it?

**Comment by owenvoke** [comment]
I'd assume probably the GitHub Releases are replacing this going forward.
https://github.com/larastan/larastan/releases
