### ISSUE TITLE
How to fix phpstan error with models defined in interface ?

### ISSUE THREAD

**Issue by PetroGromovo** [nunomaduro/larastan#1799]
Using repository with interface on laravel site phpstan raised error :
`    Parameter #1 $value of method App\Library\Reports\TaskDetailsReport::setTask() expects App\Models\Task, Illuminate\Database\Eloquent\Model given.
`
in Http/Controllers/Api/ReportsController.php :

```
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Library\Reports\TaskDetailsReport;
use App\Repositories\Interfaces\CrudRepositoryInterface;

class ReportsController extends Controller
{
    protected CrudRepositoryInterface $taskCrudRepository;

    public function __construct(CrudRepositoryInterface $taskCrudRepository)
    {
        $this->taskCrudRepository = $taskCrudRepository;
    }

    public function showTaskDetailsReport(int $taskId)
    {
        try {
            $task = $this->taskCrudRepository->get(id: $taskId);  //   Method "get" returns Model in interface class and Task in implementation class
            $taskDetailsReport = new TaskDetailsReport;
            $taskDetailsReport->setTask($task);    //  This line raise error as method setTask got 1 Task parameter

Which type of casting have I to use ? How to fix it ?
```
"laravel/framework": "^10.34.2",
"nunomaduro/larastan": "^2.6.4",

``````

            Thanks in advance!

**Comment by canvural** [comment]
Hi,

You'd need to make your `CrudRepositoryInterface` interface generic. Read more about generics [here](https://phpstan.org/writing-php-code/phpdocs-basics#generics) and [here](https://phpstan.org/blog/generics-by-examples).

Then in your `ReportsController` controller, you can typehint it as `@param CrudRepositoryInterface<Task> $taskCrudRepository` to indicate that this repository works with `Task` models.
