### ISSUE TITLE
Error in second step of documentation?

### ISSUE THREAD

**Issue by MarkelovSergey** [nunomaduro/larastan#1801]
- Larastan Version: 2.7
- `--level` used: 5
- Pull request with failing test:

### Description
Error in second step of documentation?

docker exec -it app ./vendor/bin/phpstan analyse
Note: Using configuration file /var/www/html/phpstan.neon.dist.
File '/var/www/html/./vendor/nunomaduro/larastan/extension.neon' is missing or is not readable.

### Laravel code where the issue was found
phpstan.neon.dist

- ./vendor/nunomaduro/larastan/extension.neon 
needs to be changed to
- ./vendor/larastan/larastan/extension.neon

**Comment by calebdw** [comment]
Docs look fine to me:

![image](https://github.com/larastan/larastan/assets/4176520/652d9374-07c9-44c0-a6a6-f1e2ea70369b)
