### ISSUE TITLE
Two dozen PR-s were closed by deleting the master branch

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1807]
https://github.com/larastan/larastan/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc

**Comment by nunomaduro** [comment]
@canvural I don't get it. Why people were making pull requests against master? They were simply old pull requests that were still pointing at the old master branch, right?

**Comment by canvural** [comment]
I honestly don't remember what was the default branch before 😅 And I don't remember merging master into 2.x or something. 

Maybe we can post a message to all the closed PRs that says something like "Please open a new PR and target 2.x branch if you wish to re-open this PR"

**Comment by nunomaduro** [comment]
That's a good idea. Thanks!

**Comment by nunomaduro** [comment]
We've closed the `master` branch. Please open a new pull request and target the `2.x` branch if you wish to re-open this pull request.
