### ISSUE TITLE
Getting error "Class self was not found while trying to analyse it"

### ISSUE THREAD

**Issue by gregor-gabriel** [nunomaduro/larastan#1812]
- Larastan Version: 2.8.0
- `--level` used: 1

### Description

**Here phpstan/phpstan team already analyzed the problem: https://github.com/phpstan/phpstan/issues/10369**

When I run phpstan, I get the error "_Class self was not found while trying to analyse it - discovering symbols is probably not configured properly. Learn more at https://phpstan.org/user-guide/discovering-symbols_"

I know, that this error is caused by my work on the code, because it was not occuring, when my code only supported level 3.
The problem is that there is no clue, how to find the error, because the error does not come with a code line (line 35 is not correct, it is "_class Advice extends Model_" nothing more)

```
PS C:\git\myApp> .\vendor\bin\phpstan
Note: Using configuration file C:\git\myApp\phpstan.neon.
 241/241 [============================] 100%

 ------ ----------------------------------------------------------------------------------------------------------------
  Line   app\Models\Advice.php
 ------ ----------------------------------------------------------------------------------------------------------------
         Class self was not found while trying to analyse it - discovering symbols is probably not configured properly.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  35     Class self was not found while trying to analyse it - discovering symbols is probably not configured properly.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ----------------------------------------------------------------------------------------------------------------



 [ERROR] Found 2 errors
```
**When I run phpstan only on the affected file there is no error found!**

```
PS C:\git\myApp> .\vendor\bin\phpstan analyse .\app\Models\Advice.php
Note: Using configuration file C:\git\myApp\phpstan.neon.
 1/1 [============================] 100%



 [OK] No errors
```

**So when there is an error in my code, I would expect a better error location identification.
If there is no error, there is something to improve.**

### Laravel code where the issue was found

Here is a repository that reproduces the problem: https://github.com/gregor-gabriel/larastan-app
use `composer install` and then `vendor/bin/phpstan` , to reproduce the problem (I don't think you need to run `php artisan migrate`)

**Comment by canvural** [comment]
Fixed: b7cc6a2

Thank you.
