### ISSUE TITLE
Model::where()->firstOrFail() has unspecific return type

### ISSUE THREAD

**Issue by DouglasAR01** [nunomaduro/larastan#1814]
- Larastan Version: 2.8.0
- `--level` used: 5
### Description
The method `Role::where(...)->firstOrFail()` returns a Role model. However, Larastan says it is of type `Illuminate\Database\Eloquent\Model` instead of `App\Models\Role`.

### Laravel code where the issue was found

```php
   /**
   * @return Collection<int, Permission>
   */
  public static function getAllDsPermissions(): Collection
  {
      $superAdmin = Role::where('hierarchy', 0)->firstOrFail();
      return $superAdmin->permissions;
  }
```

**Comment by calebdw** [comment]
It works fine for me...

**Comment by DouglasAR01** [comment]
I found what was causing the problem. It isn't Larastan. It's the `->permissions` that is a dynamic property from a vendor package. 
Is there a way to assert the type of it without modifying the vendor code?

The vendor code causing the issue:
```php
public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(
            Config::get('laratrust.models.permission'),
            Config::get('laratrust.tables.permission_role'),
            Config::get('laratrust.foreign_keys.role'),
            Config::get('laratrust.foreign_keys.permission')
        );
    }
```

**Comment by szepeviktor** [comment]
> Is there a way to assert the type of it without modifying the vendor code?

Yes. They are called stubs.

**Comment by mad-briller** [comment]
alternatively send a PR to the vendor package that adds a `@phpstan-return` annotation so that everyone who uses larastan can benefit
