### ISSUE TITLE
SoftDeletes "createOrRestore" macro not recognised

### ISSUE THREAD

**Issue by jackwh** [nunomaduro/larastan#1819]
- Larastan Version: 2.8.1
- `--level` used: 2

### Description

Calling the `createOrRestore` macro on an Eloquent Builder for a `MorphOne` relationship (whose child model implements `SoftDeletes`) throws errors for each model with the relationship. For example:

```
------ ------------------------------------------------------------------------------------------------------------------------
  Line   Models/Traits/HasIdentifier.php (in context of class App\Auth\User)
 ------ ------------------------------------------------------------------------------------------------------------------------
  92     Call to an undefined method Illuminate\Database\Eloquent\Relations\MorphOne<App\Models\Identifier>::createOrRestore().
         ✏️  Models/Traits/HasIdentifier.php
 ------ ------------------------------------------------------------------------------------------------------------------------
```

Other `SoftDeletes` macros like `withTrashed()` etc. work as expected.

### Laravel code where the issue was found

Example `MorphOne` relationship, which correctly returns an `Identifier` model `withTrashed()`:

```php
/** The Identifier relationship for this Model. */
public function identifier(): MorphOne
{
    return $this->morphOne(Identifier::class, 'identifiable')->withTrashed();
}
```

Calling the `createOrRestore` macro on the identifier relationship works as expected in the codebase:

```php
$this->identifier()->createOrRestore([
    'identifiable_type' => $this->getMorphClass(),
    'identifiable_id'   => $this->getKey(),
]);
```

But throws the error above in Larastan.

**Comment by calebdw** [comment]
Does the `identifier` method have the correct generics?
https://github.com/larastan/larastan/blob/be5870665785bad22ac5701b6527d34720a1163d/stubs/common/MorphOne.stub#L5-L9

**Comment by canvural** [comment]
> Does the `identifier` method have the correct generics?
> https://github.com/larastan/larastan/blob/be5870665785bad22ac5701b6527d34720a1163d/stubs/common/MorphOne.stub#L5-L9

From the error message it looks like it does. Even it doesn't have, Larastan is able to handle that automatically.

The issue is that support for SoftDeleta macros are handled in a special case in Larastan. As far as I can remember, there is no logic to recognize them automatically like all the other macros.

**Comment by jackwh** [comment]
I noticed that `createOrRestore` was only [added to Laravel 5 months ago](https://github.com/laravel/framework/blame/443ec4438c48923c9caa9c2b409a12b84a10033f/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L100) — perhaps the special case exception just hasn't made its way into Larastan yet?
