### ISSUE TITLE
Attributes cast as Collections incorrectly interpreted as non-nullable

### ISSUE THREAD

**Issue by jackwh** [nunomaduro/larastan#1820]
- Larastan Version: 1.10.56
- `--level` used: 5

### Description

I'm probably doing something wrong here, but I've searched the repo and can't find anything...

I have an Eloquent model which has a fillable property called `input_values`. This is set as a `collection` in `$casts = [...]`. At the database-level, this is stored in a nullable JSON column.

There are no docblocks indicating this is guaranteed as a `Collection`, and even so, I have `treatPhpDocTypesAsCertain: false` in my config. But Larastan reports:

```
------ ------------------------------------------------------------------------------------------------
  Line   Example/ExampleModel.php
 ------ ------------------------------------------------------------------------------------------------
  251    Using nullsafe method call on non-nullable type Illuminate\Support\Collection. Use -> instead.
         ✏️  Example/ExampleModel.php
 ------ ------------------------------------------------------------------------------------------------
```

The affected line is shown below.

### Laravel code where the issue was found

```php
$fallbackValue = $this->input_values?->get($field->id, null) ?? $field->default;
```

I believe this is a false-positive, because `input_values` is only cast to a `Collection` when a non-null value is returned from the DB (as per Laravel docs).

**Comment by calebdw** [comment]
Could be due to [bad generics](https://github.com/laravel/framework/blob/91bc0f6c0898a311355dff666d640a48f2636ad5/src/Illuminate/Database/Eloquent/Casts/AsCollection.php#L10-L18):

```php
class AsCollection implements Castable
{
    /**
     * Get the caster class to use when casting from / to this cast target.
     *
     * @param  array  $arguments
     * @return \Illuminate\Contracts\Database\Eloquent\CastsAttributes<\Illuminate\Support\Collection<array-key, mixed>, iterable>
     */
    public static function castUsing(array $arguments)
```

Try adding null to the first type of CastsAttributes, and if that works then submit a pr to the framework

**Comment by canvural** [comment]
I think issue comes from here: https://github.com/larastan/larastan/blob/be5870665785bad22ac5701b6527d34720a1163d/src/Properties/ModelCastHelper.php

Feel free to send PR with tests.

**Comment by calebdw** [comment]
So I was digging into this, and the `ModelPropertyExtension` already adds null to the casted types if the column is nullable:

https://github.com/larastan/larastan/blob/fd8db7c951e9c8e15825818fb7f246fa0d7a2b35/src/Properties/ModelPropertyExtension.php#L178-L181

**Comment by calebdw** [comment]
@JackWH, are you sure the column is nullable? Can you whip up an example Laravel repo so I can replicate?
