### ISSUE TITLE
`ModelPropertyRule` rule do not support methods such as: select(), find(), first()

### ISSUE THREAD

**Issue by clementbirkle** [nunomaduro/larastan#1824]
- Larastan Version: 2.8.1
- `--level` used: 5

### Description

I have observed that the `ModelPropertyRule` rule does not support methods that involve selecting columns, such as `select()`, `find()`, and `first()`.

### Example

```php
MyModel::query()
    ->where('xxx1')
    ->first(['xxx2', 'xxx3']);
```

In this example, an error will be triggered for `->where('xxx1')`, but not for `->first(['xxx2', 'xxx3'])`.

Is this behavior a bug, or does the `ModelPropertyRule` rule intentionally not support these methods?

**Comment by canvural** [comment]
Hi,

No it is not a bug. The support in that rule is not widespread yet. You can look into [this](https://github.com/larastan/larastan/issues/676) issue, I wrote there in detail. And it also includes a section about how you can contribute,if you want.

**Comment by clementbirkle** [comment]
Thank you @canvural for your reply. I checked the stub for `->first()` method. `model-property<TModelClass>` is already present: https://github.com/larastan/larastan/blob/2.x/stubs/10.0.0/EloquentBuilder.stub#L107

I am not sure how I can fix/improve this stub.

**Comment by canvural** [comment]
Maybe something needs to be checked then.
