### ISSUE TITLE
Infinite recursion until phpstan runs out of memory

### ISSUE THREAD

**Issue by emil-nasso** [nunomaduro/larastan#1830]
- Larastan Version: 2.8.1
- `--level` used: 1
- Pull request with failing test: -

### Description

I ran into an instance where running phpstan (with larastan/larastan) installed took long to execute and then always failing, because it was running out of memory.

I have dug down and reproduced the problem in this repo: https://github.com/emil-nasso/larastan-recursion-reproduction

The problem can be reproduced by running: `./vendor/bin/phpstan analyze --memory-limit=512M app/Http/Controllers/TestController.php`

### The reproduction

We have a very simple controller that accesses a property of a model:

```php
class TestController extends Controller
{
    public function __invoke(): string
    {
        $model = MyModel::make();
        return $model->testAttribute;
    }
}
```

The model is very simple

```php
class MyModel extends BaseModel
{
}
```

but it does extend a `BaseModel`

```php
/**
 * @mixin MyModel
 */
abstract class BaseModel extends Model
{
}

```

that uses a mixing annotation.

### What happens?

When checking the controller, phpstan tries to check if `testAttribute` exists on `MyModel` using the `ModelPropertyExtension` where it uses the `ReflectionHelper` to fetch properties: https://github.com/larastan/larastan/blob/2.x/src/Properties/ModelPropertyExtension.php#L58

The `ReflectionHelper` then uses the `MixinPropertiesClassReflectionExtension` here: https://github.com/larastan/larastan/blob/2.x/src/Reflection/ReflectionHelper.php#L30

In `MixinPropertiesClassReflectionExtension` it looks at `MyModel` again, because of the `@mixin` annotation, and we have a loop that will go on for ever.

### How can this be fixed?

When `MixinPropertiesClassReflectionExtension` is instantiated ([here](https://github.com/larastan/larastan/blob/2.x/src/Reflection/ReflectionHelper.php#L30)), a list of classes to be ignored can be passed to the constructor like this:

```diff
- return (new MixinPropertiesClassReflectionExtension([]))->hasProperty($classReflection, $propertyName); // @phpstan-ignore-line
+ return (new MixinPropertiesClassReflectionExtension([$classReflection->getName()]))->hasProperty($classReflection, $propertyName); // @phpstan-ignore-line
```

This tells the class to lookup the property, based on the mixin but tells it "by the way, I'm class X, I already know I don't have the property, so ignore any mixings mentioning me".

There might also be an opportunity to fix this directly in [MixinPropertiesClassReflectionExtension](https://github.com/phpstan/phpstan-src/blob/1.11.x/src/Reflection/Mixin/MixinPropertiesClassReflectionExtension.php) but I'm not 100% certain on how, of that would have any side effects.

Let me know if you want me to create a PR with tests for the fix in this package and I can see what I can do there.

**Comment by calebdw** [comment]
Interesting, but I don't think a parent model should mixin child models

**Comment by emil-nasso** [comment]
> Interesting, but I don't think a parent model should mixin child models

Yeah, maybe not.

However, I also think a bad/typo annotation shouldn't be able to make phpstan/larastan spiral out and try to use an infinite amount of memory. :)

**Comment by canvural** [comment]
Yes, please send a PR with tests 😊
