### ISSUE TITLE
[Feature] Detect appended accessors

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1831]
### Description
See https://github.com/laravel/framework/pull/50003 for context. Essentially only **computed properties** should be appended as accessors are already called when casting a model to an array. We should be able to detect and report this case.

On a side note, could also report entries in `$appends` that don't exist on the model.

**Comment by canvural** [comment]
Is the issue that both a method accessor and the property in `appends` exists at the same time?

> On a side note, could also report entries in $appends that don't exist on the model.

We have `model-property` custom type. We can do this easily with that.
