### ISSUE TITLE
Call to an undefined method Illuminate\Database\Eloquent\Relations\MorphTo::using()

### ISSUE THREAD

**Issue by netdjw** [nunomaduro/larastan#1836]
- Larastan Version: 2.8.1
- `--level` used: 2
- Pull request with failing test:

### Description

I get this error:

Call to an undefined method Illuminate\Database\Eloquent\Relations\MorphTo<Domain\Product\Models\Color, Domain\Product\Models\Price>::using().

### Laravel code where the issue was found

```php
    /**
     * Get the color that owns the price.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo<Color, Price>
     */
    public function color(): MorphTo
    {
        return $this->morphTo(Color::class, 'colorizable')->using(Colorizable::class);
    }
```

Is there any trick to fix this?

**Comment by mad-briller** [comment]
What Laravel version are you on? i can't find any reference to the `morphTo::using()` method in laravel 10.x but i could be missing something.

**Comment by calebdw** [comment]
There's nothing to do here, `using` is only defined on the `BelongsToMany` (and therefore `MorphToMany`) relation.

**Comment by netdjw** [comment]
Thank you guys! I'm really precious for your help!
