### ISSUE TITLE
False positive with Zttp::get

### ISSUE THREAD

**Issue by mvdnbrk** [nunomaduro/larastan#185]
- Larastan Version: 0.3.4
- `--level` used: default / 5

### Description:

Call to an undefined static method Zttp\Zttp::get().

### Laravel code where the issue was found:
```
...
use Zttp\Zttp;
...
Zttp::get('https://github.com/nunomaduro/larastan');
...
```

Zttp class:

```
class Zttp
{
    static function __callStatic($method, $args)
    {
        return PendingZttpRequest::new()->{$method}(...$args);
    }
}

class PendingZttpRequest
{
    ...
    function get($url, $queryParams = [])
    ....
}
```

**Comment by szepeviktor** [comment]
Could you please @mvdnbrk ?

**Comment by mvdnbrk** [comment]
Sure, thanks!

**Comment by mvdnbrk** [comment]
@ondrejmirtes I guess this is related to issue https://github.com/phpstan/phpstan/issues/1105
