### ISSUE TITLE
Error when accessing objects in service container boot method

### ISSUE THREAD

**Issue by nwehrhan** [nunomaduro/larastan#1855]
- Larastan Version: 2.3.5
- `--level` used: 8
- Pull request with failing test:

### Description
Start with a auxiliary service provider. If you reference a object (such as 'events') in the Service Container within the `boot()` method I receive 
`Cannot access offset 'events' on Illuminate\Contracts\Foundation\Application`.

[I found a similar issue here which was marked as fixed.](https://github.com/larastan/larastan/issues/31)

### Laravel code where the issue was found
Make a new Service Provider. Register it in `config/app.php`

`config/app.php`
```php
'providers' => [ app/AccountServiceProvider::class ]
```

`// app/AccountServiceProvider.php`
```php
use Illuminate\Support;
class AccountServiceProvider extends Support\ServiceProvider
{
    public function boot()
    {
        $this->app['events']->subscribe(SomeClass::class);
    }
}

```

**Comment by calebdw** [comment]
Try using the facade instead:

```php
use Illuminate\Support;
class AccountServiceProvider extends Support\ServiceProvider
{
    public function boot()
    {
        Support\Facades\Event::subscribe(SomeClass::class);
    }
}
```

**Comment by nwehrhan** [comment]
This works for the events since it has a Facade, but not every class has a Facade. This pattern is quite prevalent `$this->app['some.binding']` or `$this->app[SomeClass::class]` in laravel. Would be nice to support this.

**Comment by calebdw** [comment]
I've hardly ever seen `$this->app['some.binding']` outside of the framework itself. Most things like this either have a helper function or a facade to use.

Have you tried using the following in your config?

```php
    'providers' => ServiceProvider::defaultProviders()->merge([
        App\AccountServiceProvider::class,
    ])->toArray(),
```

**Comment by nwehrhan** [comment]
> I've hardly ever seen $this->app['some.binding'] outside of the framework itself.

Most of the apps I am working in are enterprise apps that have been upgraded since laravel 4.2 so this exists a lot for me 😢  as previous developers saw the pattern in the core and copied it.

Hmm bummer the current app I am working on is still at [9.x](https://github.com/laravel/laravel/blob/9.x/config/app.php#L157) vs [10.x](https://github.com/laravel/laravel/blob/10.x/config/app.php#L158) and I don't have `ServiceProvider::defaultProviders`.

**Comment by calebdw** [comment]
So here's the default 9.x config:

https://github.com/laravel/laravel/blob/5b60b604c4167b30286a6e033723a6b274e8452d/config/app.php#L157-L198

I'm not sure if it will fix the issue or not, but it looks like you're not loading any of the Laravel service providers

**Comment by nwehrhan** [comment]
> I'm not sure if it will fix the issue or not, but it looks like you're not loading any of the Laravel service providers

I have that in the config as well.

I also have this issue on custom bindings not just laravel core so `ServiceProvider::defaultProviders` wouldn't solve everything. 

```php
boot() {
        $this->app['events']->listen('some-event', function ($user) {
            $this->app['cool.class.binding.string']->log()); // Same phpstan issue
        });
       
       $this->app->bind('some.class', function () {
            return $this->app['auth']->user();  // Same phpstan issue
        });
```

We have hundreds of ignores for these errors since there's a ton of Service Providers written like this 🙁

**Comment by calebdw** [comment]
The problem is that the `$app` property is type hinted as the interface `\Illuminate\Contracts\Foundation\Application` in the service provider instead of the implementation `\Illuminate\Foundation\Application`. Laravel is really bad about type hinting interfaces and then proceeding to use the object in a manner that's not defined by the interface. The implementation defines `ArrayAccess` so it works.


An easy fix is to just override the type hint:

```php
/** @property \Illuminate\Foundation\Application $app */
class AppServiceProvider extends ServiceProvider
```

**Comment by calebdw** [comment]
Whenever an interface is type-hinted you are restricted to only calling methods defined on that interface. The other (more technically correct) option is to update your code to use the methods defined on the interface:

```php
$this->app->get('events')->subscribe(SomeClass::class);
```

**Comment by mad-briller** [comment]
> Whenever an interface is type-hinted you are restricted to only calling methods defined on that interface. The other (more technically correct) option is to update your code to use the methods defined on the interface:
> 
> ```php
> $this->app->get('events')->subscribe(SomeClass::class);
> ```

I'd recommend refactoring to make() instead of get() as larastan has quite good handling of make() but not get(), was something I've been meaning to look into at some point but haven't had the time

**Comment by calebdw** [comment]
That works too!

**Comment by nwehrhan** [comment]
Thanks @calebdw for the help! I appreciate it! Will link this in my PR so you get some credit too. Get to clean up a bunch of errors.

Will use the `make(` for smaller service providers and the typehint for larger diffs :)
