### ISSUE TITLE
Model property with decimal cast (numeric-string) does not accept float or int

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1869]
- Larastan Version: 2.9.2
- `--level` used: 3

### Description
Hello!

First off, I'm not sure if this is a Larastan issue or a PHPStan issue, but here goes:

On PHPStan level 3, types assigned to properties are checked. In my work codebase, we use the `decimal` model cast somewhat occasionally (mainly on prices and other things that need a guaranteed precision). However, I'm now running into an error where I cannot assign any numerical value to the property:

> Property LineItem::$agreed_price (numeric-string|null) does not accept float.

Type `int` and literals (`0`, `0.`) are not accepted either.

The only way to fix this that I've found is to cast it to a string but that's not really something I'd like to do all over.

Thoughts?

### Laravel code where the issue was found

```php
class LineItem extends Model
{
    protected $casts = ['agreed_price' => 'decimal:2'];
}
// ...

// error
$lineItem->agreed_price = $quantity * $discountPrice;
// works, but ugly
$lineItem->agreed_price = (string) $quantity * $discountPrice;
// works, but verbose and I'd rather not have to repeat the precision around the codebase
$lineItem->agreed_price = number_format($quantity * $discountPrice, 2);
```

P.S. I'm making the push to bring my work codebase up to PHPStan level 3...so there will likely be several issues as I run into things that aren't easily fixable.

CC: @ondrejmirtes 

Thanks!

**Comment by canvural** [comment]
Hi,

The `decimal` cast in Laravel casts the value to a string. And in Larastan we represent that with `numeric-string` So it makes it does not accept float.

But if Laravel works in a way that, `decimal` casted fields accept `float` then we can adjust the writeable type for those properties in Larastan 👍🏽

**Comment by calebdw** [comment]
So it looks like Laravel will auto cast values---not sure how far down the writable rabbit hole you want to go down. Sure we could specify a writable type of `mixed` but that might not be the most helpful

```php
/*
    protected $casts = [
        'agreed_price'      => 'decimal:2',
        'shipped_date'      => 'date:Y-m-d',
        'warehouse_pending' => 'boolean',
    ];
*/

$l = LineItem::factory()->create();

dump($l->agreed_price); //? "18.02"
dump($l->shipped_date); //? Carbon@2024-01-01 00:00
dump($l->warehouse_pending); //? false
// these will all throw phpstan errors
$l->agreed_price = 50;
$l->shipped_date = 'today';
$l->warehouse_pending = 5;
dump($l->agreed_price); //? " 50.00"
dump($l->shipped_date); //? Carbon@2024-03-07 00:00
dump($l->warehouse_pending); //? true
```

Same thing for collections/arrays/json etc.
