### ISSUE TITLE
Invalid return type for find and findOrFail

### ISSUE THREAD

**Issue by Korri** [nunomaduro/larastan#187]
- Larastan Version: 0.3.5
- `--level` used: 6

### Description:
`Model::findOrFail()` return type is wrong, when passed a single ID the return type should be `static` and when passes and array `Collection<static>`

### Laravel code where the issue was found:
```php
<?php
function test() {
    $user = User::findOrFail(1);
    return $user->isGood();
}
```

Throw the following error:
```
Call to an undefined method (Illuminate\Database\Eloquent\Collection&iterable<static(App\User)>)|static(App\User)::isGood().
```

Same issue with find, which should have the same behavior, but including null as a possible return value.

**Comment by nunomaduro** [comment]
Can you re-test this is the latest version?

**Comment by Korri** [comment]
Version `0.3.10` still triggers:
```
 Call to an undefined method (Illuminate\Database\Eloquent\Collection&iterable<static(App\User)>)|static(App\User)::isGood().
```

**Comment by nunomaduro** [comment]
Thanks for the test.

**Comment by newlinkcapital** [comment]
+1 
Thanks for this great software.

**Comment by set0x** [comment]
I have the same problem, any solution?

```php
$path = Path::withTrashed()->findOrFail($path);

$places = $path->places;
```


```bash
Access to an undefined property (Illuminate\Database\Eloquent\Collection&iterable<Models\Path>)|Illuminate\Database\Eloquent\Model::$places.
```

**Comment by pushchris** [comment]
Same problem, always with ```findOrFail``` any updates on a way around it?

**Comment by masterix21** [comment]
Same problem

**Comment by allok** [comment]
> +1
> Thanks for this great software.
> 
> The problem also hapens when using `->first()`

+1 The same with `->first()`

**Comment by szepeviktor** [comment]
We are open for a PR.

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?

**Comment by Korri** [comment]
Tested it, works properly now, thanks a lot!
