### ISSUE TITLE
Parent class not being accepted in place of template type, static, or this

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1870]
- Larastan Version: 2.9.2
- `--level` used: 3

### Description
Hello!

Not sure if this is an issue with Larastan or PHPStan, or I could just be doing something wrong.

I have many errors in my codebase where the parent class is not accepted in place of a template type, static, or this---and these usually happen on the parent class where I'm trying to define the proper generics for the children. 

The errors follow the form:

```
should return TFoo of Foo but returns Foo

should return static(Foo) but returns Foo

should return $this(Foo) but returns Foo
```

### Laravel code where the issue was found

```php
class CacheableService
{
    public function __construct(
        protected Repository $cache,
    ) {
    }

    /**
     * @template TModel of Model
     * @param class-string<TModel> $model
     * @return EloquentCollection<int, TModel>
     */
    public function put(string $model): EloquentCollection
    {
        $records = $model::query()
            ->orderBy('id')
            ->get();

        $this->cache->forever($this->resolveKey($model), $records);

        // Method put() should return Collection<int, TModel of Model> but returns Collection<int, Model>.
        return $records;
    }
}
```

```php
/** @template TRecord of Model */
class Token extends Model
{
    /** @return BelongsTo<TRecord,static> */
    public function record(): BelongsTo
    {
        // no errors here though
        return $this->belongsTo(
            static::getTokenType()->record_type,
            'record_id',
        );
    }

    /** @return BelongsTo<TokenType,static> */
    public function type(): BelongsTo
    {
         // Method Token::type() should return BelongsTo<TokenType, static(Token<TRecord of Model>)> but returns BelongsTo<TokenType, Token>.
        return $this->belongsTo(TokenType::class, 'type_id');
    }

    /** @param TRecord $record */
    public static function generate(Model $record): static
    {
        $token = static::create(['record_id' => $record->getKey()]);

        return $token; // Method Token::generate() should return static(Token<TRecord of Model>) but returns Token.
    }
}
```

Note that the Token model fails even when the model is not generic so that's not the issue here:

> Method Token::generate() should return static(Token) but returns Token.

Granted, the Token class might could use some structural changes, but I'm just trying to work within the confines of the existing architecture (#legacy) while having types

CC: @ondrejmirtes 

Thanks!

**Comment by canvural** [comment]
If you can replicate it on https://phpstan.org/try , that might indicate it is a PHPstan issue. No need to tag Ondrej every time 😊

**Comment by calebdw** [comment]
This could be related: https://github.com/larastan/larastan/issues/1149

@canvural, did you ever look to see if that was an issue in phpstan?

**Comment by canvural** [comment]
Hi,

The error is somewhat expected.

When PHPStan analyzes your `CacheableService` class it does not have enough information about generics. Only when it analyzes the code that calls `put` method, then it can have enough information. This is somewhat producable in PHPStan: https://phpstan.org/r/bcf570b2-406e-4927-90dc-311d92bc0c93

Similar kind of errors always happens when you analyze a class itself where you define generics etc. But I'm not the best person to explain this. You might open an issue in PHPStan repo. And probably there are past discussions about this there.

**Comment by calebdw** [comment]
@canvural, that makes sense---however, there were other issues I found that were just lumped into this (which I should not have done) that are valid issues. The PRs for them should not have been closed.
