### ISSUE TITLE
Support Laravel 11 new method of model casts

### ISSUE THREAD

**Issue by gabrielrbarbosa** [nunomaduro/larastan#1877]
- Larastan Version: 11.x
- `--level` used: 5

### Description
Using new L11 casts function doesnt work, as shown in the print below it cant understand the property as an array:

![Capturar](https://github.com/larastan/larastan/assets/12158575/635891b9-9219-47f4-9da6-e656f57d57ac)

**Comment by calebdw** [comment]
Larastan uses the `getCasts()` method from the model so this should work:

https://github.com/laravel/framework/blob/8be331c3fe7ce932b96c87b6e4cc0e428900829c/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1586-L1598

**Comment by calebdw** [comment]
Ah, they are only merged when the trait is initialized in the constructor and we create model instances by bypassing the constructor

https://github.com/laravel/framework/blob/8be331c3fe7ce932b96c87b6e4cc0e428900829c/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L186-L196

**Comment by gabrielrbarbosa** [comment]
https://blog.laravel.com/laravel-11-now-available

Can we release a new version of larastan today? 😁

**Comment by calebdw** [comment]
Laravel 9 has reached eol so likely need to drop support for it at the same time:

https://laravel.com/docs/11.x/releases#support-policy

**Comment by szepeviktor** [comment]
Existing projects may run on Laravel 9 for a long time.

**Comment by calebdw** [comment]
Maybe so, but that same argument could be made for L8 and we've dropped support for that.

We could start a `3.x` branch and drop support for L9 when that is released

**Comment by gabrielrbarbosa** [comment]
@calebdw Agree, I think this is good idea so everyone knows there are breaking changes in a new major release

**Comment by gabrielrbarbosa** [comment]
Any estimate on this release?

**Comment by ejntaylor** [comment]
Looks like best to just revert to original protected $casts approach until this is updated.

**Comment by zepfietje** [comment]
Well, the best approach to me seems to get https://github.com/larastan/larastan/pull/1878 merged and tagged in a release. 😉

**Comment by gabrielrbarbosa** [comment]
@nunomaduro can you help us here please?

**Comment by baschnipke** [comment]
Any chance this will be merged soon?

**Comment by DarrenChowles** [comment]
Experiencing the same issue with API resources.
```php
protected function casts(): array
{
    return [
        'starts_at' => 'datetime',
        'ends_at' => 'datetime',
    ];
}
```

````php
$resource = [
    'id' => $this->id,
    'title' => $this->title,
    'slug' => $this->slug,
    'starts_at_utc' => $this->starts_at->format('Y-m-d H:i'),
    'ends_at_utc' => $this->ends_at->format('Y-m-d H:i'),
],
````

`Cannot call method format() on string.`

**Comment by gabrielrbarbosa** [comment]
@canvural can you help us here please?

**Comment by studnitz** [comment]
If you don't want to wait until this is merged and released, you can alias the fix into your project with these composer commands:

```sh
composer config repositories.larastan-fix vcs https://github.com/calebdw/larastan  
composer require --dev --with-all-dependencies "larastan/larastan:dev-l11_casts as 2.9.2-dev"
```

**Comment by Etra-0** [comment]
@studnitz Appreciate it. I was migrating to the new structure from L10 and all of a sudden a bunch of errors 😓 ... 🙏 @calebdw

**Comment by zepfietje** [comment]
With https://github.com/larastan/larastan/pull/1878 having been closed, what's the route forward?

Laravel 11 apps use the new casts method by default on the user model, so Larastan is broken for all new Laravel apps. Let me know if there's anything I can do to get this issue fixed as soon as possible. 🙏

**Comment by canvural** [comment]
Nothing is broken. It does not give an internal error or anything.

I'll implement it on the weekend, if nobody else tackles it first.

**Comment by zepfietje** [comment]
> Nothing is broken. It does not give an internal error or anything.

Not broken in that sense, but users expect Larastan to pass on a fresh Laravel app using the documented casting approach. In that regard, it may be seen as broken when Larastan doesn't pick up the casted attribute types.

> I'll implement it on the weekend, if nobody else tackles it first.

Unfortunately I don't have any experience with the Larastan codebase personally. Thanks a lot for planning to tackle this issue, I know what open source maintainership is like. 👍

**Comment by xiCO2k** [comment]
Thanks for this @canvural, any idea when a tag will be available?

**Comment by canvural** [comment]
> Thanks for this @canvural, any idea when a tag will be available?

I need to write some documentation about it. So, this week.

**Comment by marco-introini** [comment]
Thank you so much @canvural for your work!

**Comment by zepfietje** [comment]
Hey @canvural, just checking in to see if there's something I can do to get this ready for release? 🙂

**Comment by canvural** [comment]
Done: https://github.com/larastan/larastan/releases/tag/v2.9.6 Please read the upgrade guide on how to use this feature correctly.

**Comment by DarrenChowles** [comment]
Amazing, thank you @canvural

**Comment by rabol** [comment]
@canvural what is the correct way to indicate that a enum is used ?

```
  Method App\Models\User::casts() should return array{email_verified_at: 'datetime', webhooks: 'array', trial_ends_at: 'datetime', user_level: 'App\\\\Enums\\…', is_admin: 'bool', is_blocked: 'bool'} but returns array{email_verified_at: 'datetime', webhooks: 'array', trial_ends_at: 'datetime', user_level: 'App\\Enums\\UserLevelEnum', is_admin: 'bool', is_blocked: 'bool'}.  
         💡 Offset 'user_level' ('App\\\\Enums\\…') does not accept type 'App\\Enums\\UserLevelEnum'.   
 ```

```
/**
     * @return array{email_verified_at: 'datetime', webhooks: 'array', trial_ends_at: 'datetime', user_level: 'App\\Enums\\UserLevelEnum::class', is_admin: 'bool', is_blocked:  'bool'}
*/
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'webhooks' => 'array',
            'trial_ends_at' => 'datetime',
            'user_level' => UserLevelEnum::class,
            'is_admin' => 'bool',
            'is_blocked' => 'bool',
        ];
    }
```

**Comment by schaeferalex** [comment]
@rabol  I was also struggling with this a bit; here is what I have working now:

```
    /**
     * Get the attributes that should be cast.
     *
     * @return array{
     *   channel: 'App\Enum\Channel',
     *   created_at: 'datetime',
     *   updated_at: 'datetime'
     * }
     */
    protected function casts(): array
    {
        return [
            'channel' => \App\Enum\Channel::class,
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }
```

**Comment by rabol** [comment]
Small note: you cannot have a space between array and the curly bracket

**Comment by Yi-pixel** [comment]
@canvural Excuse me, this seems to be a little bit problematic

this is a bit weird for object types, like enums.

You have to do this 👇:

```php
/**
 * @return array{location: 'App\Models\Enums\UploadLocation'}
 */
```

The enumeration here is restricted to a string, which will not be automatically typed in phpstorm.

```php
use App\Models\Enums\UploadLocation;

...

/**
  * @return array{location: UploadLocation}
  */

```

👆It should be just like this.

Note that if I use FQN, it will throw an error from PHPStan. 👇

```
/**
 * @return array{location: \App\Models\Enums\UploadLocation}
 */
```
