### ISSUE TITLE
Call to an undefined static method GrahamCampbell\GitHub\Facades\GitHub::repo()

### ISSUE THREAD

**Issue by apasov** [nunomaduro/larastan#1886]
- Larastan Version: 2.9.2
- `--level` used: 9

### Laravel code where the issue was found

```php
use GrahamCampbell\GitHub\Facades\GitHub;

$tag_name = GitHub::repo()->releases()->latest('GrahamCampbell', 'Laravel-GitHub')["tag_name"];
$response = GitHub::getHttpClient()->get("repos/GrahamCampbell/Laravel-GitHub/git/ref/tags/$tag_name");
```

### Description
This code throws the following errors:

```php
Call to an undefined static method GrahamCampbell\GitHub\Facades\GitHub::repo().
Call to an undefined static method GrahamCampbell\GitHub\Facades\GitHub::getHttpClient().
```

I first posted it to https://github.com/GrahamCampbell/Laravel-GitHub/issues/161 

But @GrahamCampbell replied:

> There are no plans to add facade doc. I believe larastan may be able to fill this for you.

So I'm re-posting it here, hoping that larastan may be able to fix this.

**Comment by szepeviktor** [comment]
The facade
https://github.com/GrahamCampbell/Laravel-GitHub/blob/7906f5a5dd530f7a94b5749d8a017518cbe5c0fa/src/Facades/GitHub.php#L32

**Comment by calebdw** [comment]
That's really just bad facade design on their part---facades should have the `@method` docs as well as the `@see` for the classes that the methods actually exist on. Perhaps try submitting a PR to push the issue?

If they're still adamant about not adding the docs, then you can create a [stub file](https://phpstan.org/user-guide/stub-files) to override the facade (can take a look at the stubs here for examples). However, I would say there's really nothing to do on this end because Larastan shouldn't be creating stubs for 3rd party packages.

**Comment by szepeviktor** [comment]
The stubs file guarantees 100% success.
It takes only 1 `@mixin`.
https://github.com/larastan/larastan/blob/2.x/stubs/common/Facades.stub

**Comment by apasov** [comment]
Thank you for your response!
I fixed this by creating `GitHub.stub` file with the following content:

```php
<?php

namespace GrahamCampbell\GitHub\Facades;

use GrahamCampbell\GitHub\GitHubManager;
use Illuminate\Support\Facades\Facade;

/**
 * @mixin GitHubManager
 */
class GitHub extends Facade
{
}

```

**Comment by calebdw** [comment]
Try to submit a PR---not sure why they wouldn't accept a single `@mixin` statement

**Comment by calebdw** [comment]
Is this issue complete?

**Comment by apasov** [comment]
I submitted a PR as you suggested. And yes, I think this is complete now.

**Comment by apasov** [comment]
In response to my PR @GrahamCampbell said that mixin loads these methods as instance methods instead of static methods, therefore this is incorrect.
What do you think about it?

**Comment by calebdw** [comment]
I prefer to use the `@method` and `@see` docs--- you also get the benefit of autocompletion and that's how Laravel's facades are documented
