### ISSUE TITLE
Eloquent\Collection concat() returns Eloquent\Collection, gets typed as Support\Collection

### ISSUE THREAD

**Issue by Grldk** [nunomaduro/larastan#1893]
- Laravel Version: 10.48.4
- Larastan Version: 2.9.2
- `--level` used: 8

### Description

Similar to https://github.com/larastan/larastan/issues/1731, after upgrading larastan to 2.9.2 (from 2.6.x I think) I've gotten a couple of new errors regarding`EloquentCollection@concat`

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Collection as EloquentCollection;

        if ($collection instanceof EloquentCollection) {
            \PHPStan\dumpType($collection);

            $collection = $collection
                ->concat([new User()])
            ;

            \PHPStan\dumpType($collection);
        }
```
Dumped type before concat: Illuminate\Database\Eloquent\Collection<int, App\Models\User>
Dumped type after concat Illuminate\Support\Collection<int, App\Models\User>

Expected type after concat: Illuminate\Database\Eloquent\Collection<int, App\Models\User>

**Comment by crissi** [comment]
yeah, needs to be added here:

https://github.com/larastan/larastan/blob/aef45ddd14749d2e5f07a1ad598b40de1173c1bd/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L41
