### ISSUE TITLE
php artisan code:analyse --level=max

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#19]
When I want to run this command, I get as result  
Path D:\xxx\D:\xxx\app does not exist

When `php artisan code:analyse --paths="app"` or `php artisan code:analyse --paths="app" --level=max` runs then Larastan knows, where the app folder is.

**Comment by usamaejaz** [comment]
I also get the same error. Adding --paths="app" fixed. There are also no spaces in the path.

**Comment by nunomaduro** [comment]
@ForzaSFerrari Do you confirm that @usamaejaz's solution fixes the issue?

**Comment by ForzaSFerrari** [comment]
Work all the time with --paths="app" at Xampp. @nunomaduro

**Comment by nunomaduro** [comment]
And without that option, doesn't work right ?

**Comment by ForzaSFerrari** [comment]
yes

**Comment by nunomaduro** [comment]
@ForzaSFerrari Weird....

**Comment by staf** [comment]
Getting this too when running on windows. No spaces in the name and did not matter if I used it in a fresh Laravel installation or an old project. Unless I specify the path option it doubles the base path.

**Comment by nunomaduro** [comment]
This issue has been fixed.
