### ISSUE TITLE
RelationExistenceRule is very strict, without being specific

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#1902]
- Larastan Version: v2.6.4
- `--level` used: 0

I define all my relationships like

```php

	public function analytics_key() {
		return $this->belongsTo(AnalyticsKey::class, 'analytics_key_id');
	}
```

without return type, because the `return $this->belongsTo` is clear enough. Larastan is very strict and tells me

> Relation 'analytics_key' is not found in App\Models\AnalyticsSite model.

It definitely exists, but not with a concrete return type, but that's not what it says. `RelationExistenceRule` returns the same message for "the method doesn't exist" as for "the existing methods doesn't have a strict correct return type".

I'd like to ignore this error, but I can't, because that would also ignore really missing relationships.

**Comment by rudiedirkx** [comment]
I don't know how phpstan's Type works, nor how to run it with source code, so I can't prepare a PR.

**Comment by calebdw** [comment]
> without return type, because the return $this->belongsTo is clear enough.

If you want good static analysis, then you're going to need return types

**Comment by rudiedirkx** [comment]
Isn't the point of static analysis that it can match the defined return type against the functional return type? So it knows the functional return type. Why not use that? Instead of the `: BelongsTo` etc.

At least make it 2 different messages so I can choose to ignore the second one. Don't tell me the relationship doesn't exist. It exists. You might not agree with the return type **definition**, but the correct function exists. Strict is okay, but fix the message so I can make it less strict plz.

**Comment by calebdw** [comment]
No. Phpstan "doesn’t descend to called functions and symbols, it just reads their typehints and PHPDocs." Doing so would be too costly and slow.

https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods

As you get into higher phpstan levels, phpstan will validate that what you return from a function matches the return signature (but that's when it's inside the method), outside the method it only looks at the return type.

There's nothing to do here. If you want the method to be recognized as a relationship by Larastan then you need to add the return type

**Comment by szepeviktor** [comment]
Static analysis has great benefits.
The cost is that you have to aid static analysis.

The conclusion: really good code = when PHPStan tells you "[OK] No errors." on level max.

**Comment by rudiedirkx** [comment]
I see. But 2 different messages? "Relation 'analytics_key' is not found" is confusing.

**Comment by calebdw** [comment]
It's not confusing because you know exactly what the problem is and how to fix it.  The message is appropriate because the method is not recognized as a relationship by Larastan---the relationship is literally not found.

**Comment by rudiedirkx** [comment]
I do now, because I looked at the package code. Before that I was just confused and thought the package couldn't find the `analytics_key` method. Having to look at the package code is not a good sign IMO, but maybe I'm just dumb. Alright, I think we're done here. Thanks for all the patience.

**Comment by szepeviktor** [comment]
We will help you next time too.

**Comment by calebdw** [comment]
I suppose we could add something in the readme about this--- I'll do that later today if I get the chance

**Comment by rudiedirkx** [comment]
> I suppose we could add something in the readme about this--- I'll do that later today if I get the chance

Or the message..? 😉
