### ISSUE TITLE
Access to undefined property after squashing migrations with prune

### ISSUE THREAD

**Issue by DanielGSoftware** [nunomaduro/larastan#1904]
- Larastan Version: 2.7.0
- `--level` used: 5
### Description
After squashing migrations and pruning them, PHPStan generates a whole lot of new errors: `Access to an undefined property Model::$exampleProperty`. This is because the migrations do not longer exist, but this should not be problem since Larastan should use the dumped schema [instead](https://github.com/larastan/larastan/blob/2.x/docs/custom-config-parameters.md#squashedmigrationspath).

The same problem has been described in an old issue [here](https://github.com/larastan/larastan/issues/711), which seemed to be solved, but it seems to not be working for us. I also found another user stating the [same](https://github.com/larastan/larastan/issues/1468#issuecomment-1512283167).

**Comment by calebdw** [comment]
What database are you using?

**Comment by calebdw** [comment]
Also, latest larastan version is `2.9.2`---try updating

**Comment by szepeviktor** [comment]
Clearing results cache?

**Comment by DanielGSoftware** [comment]
> What database are you using?

Thanks for the reply! I am using Mysql

**Comment by DanielGSoftware** [comment]
> Also, latest larastan version is `2.9.2`---try updating

Good point, I should've tried that from the start X). Unfortunately after updating, the same problem persists.

**Comment by DanielGSoftware** [comment]
> Clearing results cache?

Thanks for your suggestion! Tried that, but that does not seem to be the issue.

**Comment by calebdw** [comment]
What is your dump called and where is it located? What does your phpstan.neon look like?

**Comment by DanielGSoftware** [comment]
> What is your dump called and where is it located? What does your phpstan.neon look like?

Relevant phpstan.neon config:
```neon
includes:
    - ./vendor/larastan/larastan/extension.neon
    - phpstan-baseline.neon

parameters:

    paths:
        - app/

    # Level 9 is the highest level
    level: 5
```

Dump is called `mysql-schema.sql`.

**Comment by calebdw** [comment]
And where is the dump located?

**Comment by DanielGSoftware** [comment]
> And where is the dump located?

Sorry, it's located in database/schema

**Comment by calebdw** [comment]
Hmmm, everything looks to be correct and we have tests that ensure everything works:

https://github.com/larastan/larastan/blob/2.x/tests/Unit/SquashedMigrationHelperTest.php

Try running `vendor/bin/phpstan clear-result-cache` and then rerun phpstan.

**Comment by szepeviktor** [comment]
Does your dump have [only standard](https://github.com/larastan/larastan/blob/2.x/tests/application/database/migrations/2020_03_20_000000_create_accounts_table.php) table altering PHP code?

Larastan recognizes: https://github.com/larastan/larastan/blob/b66a8982878f808183afa533ddcaf02542c6c755/src/Properties/SchemaAggregator.php#L94-L110


NO! It is SQL only. Sorry.

**Comment by DanielGSoftware** [comment]
> Hmmm, everything looks to be correct and we have tests that ensure everything works:
> 
> https://github.com/larastan/larastan/blob/2.x/tests/Unit/SquashedMigrationHelperTest.php
> 
> Try running `vendor/bin/phpstan clear-result-cache` and then rerun phpstan.

Still the same issue unfortunately, pretty odd.. but now that I know which code is responsible for handling this, I might do some debugging myself and see if I can find anything, will report back!

**Comment by DanielGSoftware** [comment]
> NO! It is SQL only. Sorry.

No worries, thanks for the input anyway!

**Comment by calebdw** [comment]
I suspect that there's an issue with the dump (maybe a unsupported datatype?) that could be causing the whole dump to fail.

Are all properties throwing errors or just properties of a certain type? Try with a subset of the dump

**Comment by DanielGSoftware** [comment]
I found the issue, and it's not related to Larastan.
If I have a closer look at which properties are undefined, there's an important detail:
The properties in question are not defined in a table column, but in the $casts property of a model, like so:
```php
class SomeModel extends Model
{
    protected $casts => [
        'principal' => MoneyCast::class . ':principal_in_cents',
    ];
}
```

So the `principal` column does not exist in my table, so it makes sense why Larastan throws an error. But then that would mean that Larastan should've failed on an earlier stage, so why would this fail after squashing my migrations?
The answer lays in my schema dump: the column has changed in the table from `principal` to `principal_in_cents`: Larastan was using our outdated dump which resulted in the errors not being shown before. We don't have calls to `principal_in_cents`, so it makes sense why no errors were generated even if the column can't be found by Larastan.

I thank you @calebdw and @szepeviktor for trying to help me figure this one out, and sorry for it being a issue not related to Larastan 😅
