### ISSUE TITLE
non-nullable type error for logger()

### ISSUE THREAD

**Issue by nepster-web** [nunomaduro/larastan#1914]
- Larastan Version: v2.9.2
- Laravel Version: v11.3.1

### Description

Using Larastan I encountered the following errors:

```Using nullsafe method call on non-nullable type Illuminate\Log\LogManager. Use -> instead. ```

### Laravel code where the issue was found

```php
...
  logger()?->error($message ?: $this->getClassName(), [
      'tags' => $this->getLogTags(),
      'exception' => $throwable,
      'cron' => $this->option('cron'),
  ]);
...
```

and if I remove the question mark, the warning will be issued by ide:
![image](https://github.com/larastan/larastan/assets/5681979/dd4d13af-0a23-40c5-bb61-458d734d9346)

however there shouldn't be any problems:
![image](https://github.com/larastan/larastan/assets/5681979/01afe711-ba25-43f9-bbcb-9fd565750d29)

**Comment by canvural** [comment]
Hi,

logger helper method never returns null. Larastan is right here. You get that error in PHPStorm because it reads the PHPDocs.

**Comment by nepster-web** [comment]
however, the problem is still present, and if laravel has special phpdoc with null perhaps it has a sense.

in any case, I would like to avoid the error in larastan and the warning in the ide.

**Comment by canvural** [comment]
In this case PHPStorm is wrong. `logger()` never returns `null` (without arguments I mean) There is nothing we can do here.

**Comment by szepeviktor** [comment]
@nepster-web You can add a stub for that function with [conditional return type](https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types).

**Comment by canvural** [comment]
We already have a stub in Larastan. Do you mean stub file in PHPStorm?

**Comment by szepeviktor** [comment]
> Do you mean stub file in PHPStorm?

No.
I didn't know we had a stub.

https://github.com/larastan/larastan/blob/40b227e2c1bb1e61c1fa90020e2fd048ed39b958/stubs/common/Helpers.stub#L30-L37
