### ISSUE TITLE
Using `sole()` on a BelongsTo relation returns Model instead of Model Extension

### ISSUE THREAD

**Issue by Roardom** [nunomaduro/larastan#1918]
- Larastan Version: 2.9.4
- Laravel Version: 10.48.7

### Description

When accessing a BelongsTo relation, such as:

```php
$topic = $post->topic()->sole();
```

`$topic` is seen as an `Illuminate\Database\Eloquent\Model` instead of an `App\Models\Topic`. `->firstOrFail()` seems to work.

### Laravel code where the issue was found

```php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Post.
 *
 * @property int                             $id
 * @property string                          $content
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property int                             $user_id
 * @property int                             $topic_id
 */
class Post extends Model
{
    use HasFactory;

    /**
     * Belongs To A Topic.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<Topic, self>
     */
    public function topic(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Topic::class);
    }
}
```

**Comment by szepeviktor** [comment]
Thank you!

Adding `sole` method to our stubs solves your problem.

**Comment by Roardom** [comment]
> Thank you!
> 
> Adding `sole` method to our stubs solves your problem.

I tried adding a `sole()` method to some of the stubs, but couldn't get it to work. Would you mind pointing out which file I have to add it in, and I can send a PR?

**Comment by szepeviktor** [comment]
🤯 

Seems like we already have that!

https://github.com/larastan/larastan/blob/40b227e2c1bb1e61c1fa90020e2fd048ed39b958/stubs/10.0.0/EloquentBuilder.stub#L167-L173

**Comment by szepeviktor** [comment]
What type is topic?
```php
\PHPStan\dumpType($post->topic());
```

**Comment by Roardom** [comment]
> What type is topic?
> 
> ```
> \PHPStan\dumpType($post->topic());
> ```

```
phpstan: Dumped type: Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Topic, App\Models\Post>
```
