### ISSUE TITLE
Custom eloquent collection not detected

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#1924]
- Larastan Version: v2.9.4
- Laravel Version: v10.48.8

### Description

If a model uses a custom collection (through `newCollection()`), the new collection type isn't detected. This presents in 2 ways:

1. Correct collection, but unknown element type `User`:

```php
$userQuery->chunk(1000, function(CustomCollection $users) {
    \PHPStan\dumpType($users); << Dumped type: CustomCollection
    foreach ($users as $user) {
        var_dump($user->fullname); << Access to an undefined property Illuminate\Database\Eloquent\Model::$fullname
    }
});
```

If I omit the `CustomCollection` type in the `chunk()` callback, PHPStan says `Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\User>` which is also half-correct, but the other half (wrong Collection class, right element type).

2. Incorrect collection, but known element type `User`:

```php
$users = $query->get();
\PHPStan\dumpType($users); << Dumped type: CustomCollection
foreach ($users as $user) {
    \PHPStan\dumpType($user); << Dumped type: Illuminate\Database\Eloquent\Model
    var_dump($user->fullname); << Access to an undefined property Illuminate\Database\Eloquent\Model::$fullname
}
```

I feel like PHPStan or Larastan could be smarter and combine the two: it's definitely a `CustomCollection`, because PHP makes sure, and static analysis says it contains `App\Models\User`. Combine it into a `CustomCollection<App\Models\User>`? 😆 

Demo repo: https://github.com/rudiedirkx/larastan-demo

**Comment by rudiedirkx** [comment]
#1558 is relevant, but not quite the same, I think. But maybe it's the same unsolvable reason..?

**Comment by canvural** [comment]
Hi,

Yes this is the same issue as the one you linked. Unfortunately there is no way to solve for now. You can use the workaround I wrote on that issue.

**Comment by rudiedirkx** [comment]
I'm not going to make actual PHP code worse just to get better static analysis, so I'll just wait for the brilliant solution that will happen some day 👍 Thanks anyway. Larastan is pretty brilliant, and addictive =(

**Comment by calebdw** [comment]
For 1), try to remove the closure type---adding the type removes the generic info:

```php
$userQuery->chunk(1000, function($users) {
    foreach ($users as $user) {
        var_dump($user->fullname);
    }
});
```

I missed that you already tried this

**Comment by rudiedirkx** [comment]
I'm not quite conviced, but I'm not sure it's the collection 'bug':

```php
$sites = \DB::transaction(function() use ($importer) {
	return $importer->importRows();
});
\PHPStan\dumpType($sites); << Dumped type: App\Base\ModelCollection&iterable<App\Models\Site>
```

That type is good, because I added a `@return` to `importRows()` (and apparently PHPStan does look inside the closure?).

But then:

```php
foreach ($sites->chunk(10) as $sitesChunk) {
	\PHPStan\dumpType($sitesChunk); << Dumped type: Illuminate\Database\Eloquent\Model
}
```

That type doesn't make sense. Shouldn't `collection::chunk()` make `collection<collection>` instead of `collection<model>`? Do I have to add some phpdoc magic to my custom collection?

**Comment by calebdw** [comment]
How are you defining your collection generics?

`Collection<Model>` is incorrect, it should be `Collection<int, Model>`

**Comment by rudiedirkx** [comment]
> For 1), try to remove the closure type---adding the type removes the generic info:

I know. I think PHPStan could be smarter and combine the two hints, but what do I know. (I think PHPStorm does that?) But that's changing actual real PHP code just to make PHPStan happy. I don't like that.

**Comment by rudiedirkx** [comment]
> How are you defining your collection generics?

In my custom collection class, I define nothing. It extends `Illuminate\Database\Eloquent\Collection` so I assume it uses those `@template` etc.

> `Collection<Model>` is incorrect, it should be `Collection<int, Model>`

Alright, but that doesn't change the result (at all, weird). The first dumpType is now `ModelCollection&iterable<int, Site>` (because of the `@return`), but after the chunk() it's still `Model` instead of `ModelCollection`. Should I do more in the `ModelCollection` phpdoc?

**Comment by calebdw** [comment]
No, you need to define the generics in your custom collection class.

Either:

```php
/** @extends EloquentCollection<int, FooModel> */
class FooCollection extends EloquentCollection
```
if the collection class does not need to be generic itself.

Or
```php
/**
 * @template TKey of array-key
 * @template TModel of FooModel // or Model
 *
 * @extends EloquentCollection<TKey, TModel>
 */
class FooCollection extends EloquentCollection
```
if the collection does need to be generic.

If the collection is generic itself, then you would need to define the generics where you use it:

```php
/** @return FooCollection<int, FooModel> */
```

**Comment by rudiedirkx** [comment]
> If the collection is generic itself, then you would need to define the generics where you use it:

Not if I don't extend the collection at all and only use EloquentCollection. Then Larastan knows what's inside. But not if I extend it, **and the template**. Does it only/hardcoded do that for `EloquentCollection`?

I understand Larastan can't detect the `newCollection()` and apply that, but why can't it use an extended collection if I hint that new collection? Like `chunk()`. How can collection::chunk() be broken for a custom collection that extends EloquentCollection?

**Comment by rudiedirkx** [comment]
Wait, now `chunk()` works!

```
\PHPStan\dumpType($sitesChunk); << App\Base\ModelCollection&iterable<int, App\Models\Site>
```

And the contents!

```
\PHPStan\dumpType($sitesChunk->first()); << App\Models\Site|null
```

I don't get it, but something fixed it. One of the 5000 clueless changes I've made the last hour.

Thanks @calebdw for being incredibly patient once again. ❤️ Some day I'll get it ;) Maybe...

**Comment by calebdw** [comment]
I need to see how you're defining and using your collection because this:

> App\Base\ModelCollection&iterable<int, App\Models\Site>

is still wrong and is indicative of `Collection<Model>` instead of `Collection<int, Model>`

**Comment by rudiedirkx** [comment]
Aaw man, but it works (or seems to work)... Alright.

- All my models extend `App\Base\Model`
- `App\Base\Model` overrides `newCollection()` to return `App\Base\ModelCollection`
- `App\Base\ModelCollection` extends Laravel's `EloquentCollection`, and includes phpdoc:
	```
	/**
	 * @template TKey of array-key
	 * @template TModel of \App\Base\Model
	 *
	 * @extends EloquentCollection<TKey, TModel>
	 */
	```
- Somewhere in a controller I import a bunch of `Site` models:
	```php
	$sites = \DB::transaction(function() use ($importer) {
		return $importer->importRows();
	});
	\PHPStan\dumpType($sites); << App\Base\ModelCollection<int, App\Models\Site>
	```
- `importRows()` looks like this:
	```php
	/** @return ModelCollection<int, Site> */
	public function importRows() : ModelCollection {
	```
- In the same controller action, I create batches of `Site` to put in a job:
	```php
	foreach ($sites->chunk(10) as $sitesChunk) {
		\PHPStan\dumpType($sitesChunk); << App\Base\ModelCollection<int, App\Models\Site>
		\PHPStan\dumpType($sitesChunk->first()); << App\Models\Site|null
		dispatch(new AfterImportJob($sitesChunk->modelKeys(), $checkIds, \Auth::id()));
	}
	```

Wait what? Where's the `&iterable`? This is better, right?

I promise, I do `clear-result-cache` all the time, AND I run `analyze --debug`.

**Comment by rudiedirkx** [comment]
Because I'm a curious boy, I also wanted to know what the chunk() output looks like:

```php
\PHPStan\dumpType($sites->chunk(10));
```

```
Dumped type: App\Base\ModelCollection<int, App\Base\ModelCollection<int, App\Models\Site>>
```

Aaw yea!

**Comment by rudiedirkx** [comment]
I'm gonna have to remember to remove SO MANY `\PHPStan\dumpType()` 😆

**Comment by calebdw** [comment]
Everything looks pretty good to me! Larastan should be able to understand newCollection if all the generics are set up properly.

`App\Base\ModelCollection&iterable<int, App\Models\Site>` is an intersection type and occurs when there's only one argument to Collection like `Collection<Model>`. If you ever see that, it usually means the generics weren't defined properly.

How do you define `newCollection` on your base model?

**Comment by rudiedirkx** [comment]
> Larastan should be able to understand newCollection if all the generics are set up properly.
> How do you define newCollection on your base model?

OMG I DIDN'T HAVE A RETURN TYPE in `newCollection()`!

```diff
-public function newCollection(array $models = []) {
+public function newCollection(array $models = []) : ModelCollection {
 	return new ModelCollection($models);
 }
```

I had to dig into `ModelRelationsExtension` and `CollectionHelper` to find out what \*\*I\*\* did wrong.

Damn, Larastan is smart! Much smarter than me 😆

**Comment by rudiedirkx** [comment]
It is too bad PHPStan doesn't look inside methods though. This is such a waste:

```diff
+       /** @return ModelCollection<int, Check> */
        public function getChecksForType(string $type) : ModelCollection {
                return $this->checks->filter->doForType($type);
        }
```

Inside the method PHPStan knows exactly what it returns (OMG Larastan, even HigherOrderProxies!), but from outside it's just a `ModelCollection`, so it needs a `@return` =(

**Comment by calebdw** [comment]
You still need generics on the newCollection:

```php
/**
 * @param array<int, static> 
 * @return ModelCollection<int, static>
 */
public function newCollection(array $models = []): ModelCollection
{
    return new ModelCollection($models);
}
```

Also, for flexibility (and to use composition rather than inheritance), I would recommend using the following trait instead of sticking this method on your base model---this will allow you to use other custom collections and even apply it on models that don't extend your base model

```php
/**
 * @template TCollection of EloquentCollection
 * @mixin Model
 */
trait HasCollection
{
    // Must add the following property to the model
    // protected static string $collection;

    /**
     * @param array<int, static> $models
     * @return TCollection
     */
    public function newCollection(array $models = []): EloquentCollection
    {
        return new static::$collection($models);
    }
}
```

Then to use:
```php
class FooModel extends Model
{
    /** @use HasCollection<ModelCollection<int, static>> */
    use HasCollection;

    protected static string $collection = ModelCollection::class;
}
```

Or if the custom collection is not generic:

```php
class BarModel extends Model
{
    /** @use HasCollection<BarCollection> */
    use HasCollection;

    protected static string $collection = BarCollection::class;
}
```

This is a pattern I've been using for Builders and Factories to reduce the amount of code on the models

**Comment by rudiedirkx** [comment]
> You still need generics on the newCollection:

What does that do? I get perfect types everywhere. Except for the not looking inside methods. Or is that what that solves?? 😮😮

**Comment by calebdw** [comment]
It defines the generics at the source

**Comment by rudiedirkx** [comment]
> It defines the generics at the source

Right. Buuuut, you don't seem to understand that I am dumb, and I don't know what that means. Does it make PHPStan understand types better? Because without it PHPStan seems to understand perfectly. Does `CollectionHelper::determineCollectionClass()` use those hints for ever better details?

**Comment by rudiedirkx** [comment]
> Or is that what that solves?? 😮😮

No =(

**Comment by calebdw** [comment]
Larastan should be looking at the generics returned by `newCollection` since that is the source to obtain that information for a given model.

It's just a suggestion, you can follow it or not. But if I was implementing custom collection classes (we haven't but I've heavily used custom builder classes) then I would create and use the `HasCollection` trait defined above.

**Comment by rudiedirkx** [comment]
Another loss of correct Collection: (by now I doubt it's a bug, but still)

```php
class App\Models\Site {
	static function indexQuery() : EloquentBuilder {
		return self::query();
	}
}
```

In controller:

```php
\PHPStan\dumpType(Site::indexQuery()); << EloquentBuilder
\PHPStan\dumpType(Site::indexQuery()->get()); << Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Model>

// What I expected:
\PHPStan\dumpType(Site::query()); << Illuminate\Database\Eloquent\Builder<App\Models\Site>
```

I could add `/** @return Builder<self> */` to `indexQuery()`, but I feel that shouldn't be necessary. Or does Stan lose track of the generic because of the static method and it can't be helped?

**Comment by calebdw** [comment]
PHPStan only reads typehints and phpdocs

> During the analysis of the foo() method, PHPStan doesn’t understand that the type of $object was narrowed to BarService because it doesn’t descend to called functions and symbols, it just reads their typehints and PHPDocs.

https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods

Anytime you return a collection like that (or any generic object for that matter like arrays) you're going to have to define the generics. The same thing goes with input parameters (@param) and properties (@var)


However, I see no reason to have the method `indexQuery` just wrap `query`...just use `::query()`. On a side note, I start **all** of my queries with `::query()` because you get better generic and ide autocompletion support.

**Comment by rudiedirkx** [comment]
> However, I see no reason to have the method `indexQuery` just wrap `query`...just use `::query()`.

That was a simplified example =) There's a lot of logic in there, with arguments. I could move it into a scope, and Larastan would probably understand that, but I like to keep the method names literal (no scope* magic) when possible. I'll just add the `@return`.

**Comment by rudiedirkx** [comment]
I did find another Collection loss:

```php
$sites = Site::query()->get(); // Good collection 👍 
$orgs = $sites->map(fn(Site $site) => $site->user_org->org_org); // Larastan thinks it's a Illuminate\Support\Collection<int, App\Models\Organization|null>, not even an EloquentCollection, and definitely not a custom ModelCollection
```

**Comment by calebdw** [comment]
You should look into custom builders if you don't want to use scopes

**Comment by calebdw** [comment]
> $orgs = $sites->map(fn(Site $site) => $site->user_org->org_org);

You shouldn't need the type since that's already given by the collection generics:

```php
$orgs = $sites->map(fn ($site) => $site->user_org->org_org);
```

Also, I would need to see what `user_org` and `org_org` are defined as

**Comment by rudiedirkx** [comment]
> You shouldn't need the type since that's already given by the collection generics:

Again, that's changing actual/useful PHP code. I don't write code to make PHPStan/Larastan happy. But that's not the problem.

> Also, I would need to see what `user_org` and `org_org` are defined as

It results in an Organization, and Larastan understands that 👍 

    Illuminate\Support\Collection<int, App\Models\Organization|null>

But the ModelCollection (`$sites`) turned into a base `Collection`. Not in reality/PHP, but in Larastan. I kinda get why, because `EloquentCollection::map()` does dynamic magic, but I still don't like it =)

**Comment by calebdw** [comment]
Ah yeah, `map` always results in a support collection

> I don't write code to make PHPStan/Larastan happy.

The whole point of using PHPStan is to write code that makes PHPStan happy :stuck_out_tongue_winking_eye:

**Comment by rudiedirkx** [comment]
> Ah yeah, `map` always results in a support collection

But not in reality. Is there a trick (besides `@var`) to make Larastan see it's still models?

> The whole point of using PHPStan is to write code that makes PHPStan happy 😜

I thought the point was to make better code, but I'm starting to see it's just a giant scheme. If I remove phpstan, I get no errors! 🎉

**Comment by calebdw** [comment]
> But not in reality. Is there a trick (besides @var) to make Larastan see it's still models?

So Larastan is detecting that models are returned: `App\Models\Organization|null`

Based on the stub, it should detect if models are returned and use the `static` class:
```php
    /**
     * Run a map over each of the items.
     *
     * @template TMapValue
     *
     * @param  callable(TModel, TKey): TMapValue  $callback
     * @return (TMapValue is \Illuminate\Database\Eloquent\Model ? static<TKey, TMapValue> : \Illuminate\Support\Collection<TKey, TMapValue>)
     */
    public function map(callable $callback);
```

The reason why it's likely not working in your case is because it thinks the values could possibly be `null`.


> I thought the point was to make better code, but I'm starting to see it's just a giant scheme. If I remove phpstan, I get no errors! 🎉

:100: no static errors---however, you most definitely will have runtime errors. So it's really just about choosing your hard

**Comment by rudiedirkx** [comment]
> Based on the stub, it should detect if models are returned and use the static class:

Oh daamn Larastan got this! The ternary syntax is new to me. Very cool.

> The reason why it's likely not working in your case is because it thinks the values could possibly be `null`.

It can't be null in reality, so there might be something going wrong in the `$site->user_org->org_org`. Let's debug!

> however, you most definitely will have runtime errors

Nah, I don't make bugs. I'm one of those programmers who never makes bugs.

**Comment by calebdw** [comment]
> so there might be something going wrong in the $site->user_org->org_org. 

It's quite normal, really just depends on what `user_org` / `org_org` are and how they're defined



> I'm one of those programmers who never makes bugs.

Lookout everybody! We got a 10x programmer in the house! :upside_down_face:

**Comment by rudiedirkx** [comment]
There's another `map()` where Larastan doesn't think it can be null, and it still maps to a base collection. Shield your eyes, this code might be TOO beautiful!:

```php
\PHPStan\dumpType($questions); // 👍 App\Base\ModelCollection<int, App\Models\A11yA12yQuestion>
$formAnswers = $questions->map(function(A11yA12yQuestion $question) use ($givenAnswers) {
	$answer = $givenAnswers[$question->id] ?? new A11yA12yAnswer([
		'a11y_a12y_question_id' => $question->id,
		'answer' => '',
	]);
	\PHPStan\dumpType($answer); // 👍 App\Models\A11yA12yAnswer
	$answer->setRelation('question', $question);
	return $answer;
});
\PHPStan\dumpType($formAnswers); // 👎 Illuminate\Support\Collection<int, App\Models\A11yA12yAnswer>
```

No `null` allowed, only models, but still no `ModelCollection`.

I double checked 'reality', and yes, it is a ModelCollection there. (I still venture into 'reality' sometimes.)

```
App\Base\ModelCollection {#720 ▼
  #items: array:74 [▼
    0 => App\Models\A11yA12yAnswer {#875 ▶}
```

**Comment by rudiedirkx** [comment]
> It's quite normal, really just depends on what `user_org` / `org_org` are and how they're defined

It's a BelongsTo without scopes, on a non-null column, so there's always one model in that relationship. How do I tell Larastan it's never null? Even the FK column in the dumped schema is `not null`, if Larastan even uses that, which would be insanely impressive.

**Comment by rudiedirkx** [comment]
> How do I tell Larastan it's never null?

Maybe it's impssible. The `BelongsTo` stub has a `@phpstan-return ?TRelatedModel` so it's always nullable. And maybe it doesn't even matter. The other `map()` also degrades into a base Collection.

**Comment by calebdw** [comment]
Larastan gets the type from the closure return type:

```
     * @param  callable(TModel, TKey): TMapValue  $callback
```

So you might need to add the return type to the closure for Larastan to recognize it:

```php
$formAnswers = $questions->map(function(A11yA12yQuestion $question) use ($givenAnswers): A11yA12yQuestion {
```

A BelongsTo relationship can only be non-nullable *iff* the column is non-nullable **and** there is a foreign-key constraint on the column---otherwise the column could have a value but there's not a matching record in the other table.

**Comment by rudiedirkx** [comment]
> So you might need to add the return type to the closure for Larastan to recognize it:

Larastan really doesn't like me:

```php
\PHPStan\dumpType($audits); // 👍 App\Base\ModelCollection<int, App\Models\A11yAudit>
\PHPStan\dumpType($audits->map(function(A11yAudit $audit) : Organization {
	return $audit->main_site->organization;
}));
// Dumped type: Illuminate\Support\Collection<int, App\Models\Organization> 👎 
```

`App\Models\Organization` good, `Illuminate\Support\Collection` bad. I've never seen map() return a model collection. Maybe my generics are still messed up somewhere?

> **and** there is a foreign-key constraint on the column---otherwise the column could have a value but there's not a matching record in the other table

Good point. There goes my bug-free history. Luckily we always remember to add FK constraints!

**Comment by rudiedirkx** [comment]
> A BelongsTo relationship can only be non-nullable _iff_ the column is non-nullable **and** there is a foreign-key constraint on the column

Larastan doesn't actually parse all that, does it? 😮 That would be insane. (And then you can still get invalid ids in the db if you did some `SET FOREIGN_KEY_CHECKS = 0` hacking.)

**Comment by calebdw** [comment]
> Larastan doesn't actually parse all that, does it? 

I can't remember if Larastan does use that info or not---it is possible. The [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) uses that information when writing the model doc blocks for the relation properties.

**Comment by calebdw** [comment]
Hmmm, I'm curious---try this:


```php
$audits->map(function(A11yAudit $audit) : Model {
```

**Comment by rudiedirkx** [comment]
> Hmmm, I'm curious---try this:

With `App\Base\Model` it doesn't work. With `Eloquent\Model` it also doesn't work. And the result type is less useful like this:

    Illuminate\Support\Collection<int, App\Base\Model>

instead of

    Illuminate\Support\Collection<int, App\Base\Organization>

Can you get map() to ever return a ModelCollection (or EloquentCollection)??

**Comment by calebdw** [comment]
No no, set the return type to Eloquent Model

**Comment by rudiedirkx** [comment]
If I remove the custom `newCollection()` it still degrades into a base collection:

Input:

```
Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\A11yAudit>
```

After map:

```
Dumped type: Illuminate\Support\Collection<int, App\Models\Organization>
```

**Comment by rudiedirkx** [comment]
> No no, set the return type to Eloquent Model

I did. I tried both. Both degrade into a base collection.

**Comment by calebdw** [comment]
Are you on the latest larastan version?

**Comment by rudiedirkx** [comment]
> Are you on the latest larastan version?

No 😊 v2.6.4. My Laravel 10 isn't uptodate. I'll try upgrading both (just for testing).

**Comment by calebdw** [comment]
That's probably why :upside_down_face: Things tend to work as expected when you're on the latest version :stuck_out_tongue_closed_eyes:

**Comment by rudiedirkx** [comment]
Ooooh 2.9.4 is better, but not quite there yet:

```
  49     Dumped type: App\Base\ModelCollection<int, App\Models\A11yAudit>
  53     Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\Organization>
```

It's a EloquentCollection now, but not a ModelCollection.

> Things tend to work as expected when you're on the latest version 😝

My sinceres apologies. I assumed you were on exactly the same version as me, because that totally makes sense.

**Comment by rudiedirkx** [comment]
Even though the template in the stub says `static`...:

```
    /**
     * @return (TMapValue is \Illuminate\Database\Eloquent\Model ? static<TKey, TMapValue> : \Illuminate\Support\Collection<TKey, TMapValue>)
     */
    public function map(callable $callback);
```

**Comment by rudiedirkx** [comment]
(Ooeeeh Larastan changed its namespace between 2.6.4 and 2.9.4. That's not very BC. Is that allowed in a minor change?)

**Comment by calebdw** [comment]
> (Ooeeeh Larastan changed its namespace between 2.6.4 and 2.9.4. That's not very BC. Is that allowed in a minor change?)

:shrug: what's in the past is past. A lot of folks use the phpstan extension installer which keeps you from having to manually list all the extensions

**Comment by rudiedirkx** [comment]
Larastan 2.9.5 still doesn't see the custom collection after `map()`. It does find `Illuminate\Database\Eloquent\Collection`, but it should find `static` = `App\Base\ModelCollection`.

```
         before map():
  49     Dumped type: App\Base\ModelCollection<int, App\Models\A11yAudit>
         map() output:
  53     Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\Organization>
```

**Comment by calebdw** [comment]
@rudiedirkx, open up a new issue with the relevant details and I'll take a look

**Comment by canvural** [comment]
`map` always returns a support collection at runtime. It will not return the custom collection. Larastan is right here.

**Comment by calebdw** [comment]
@canvural, that's not correct:

SupportCollection returns `new static()`:
https://github.com/laravel/framework/blob/22f4864fcb54cd04fc0e110af193aa9a63905e22/src/Illuminate/Collections/Collection.php#L767-L778

And EloquentCollection only calls `toBase()` if there's not models in the array anymore:
https://github.com/laravel/framework/blob/22f4864fcb54cd04fc0e110af193aa9a63905e22/src/Illuminate/Database/Eloquent/Collection.php#L334-L347

**Comment by canvural** [comment]
>  if there's not models in the array anymore

Yes. And in this example collection items are models. So it returns support collection.

**Comment by calebdw** [comment]
...if the collection only contains models then it would **not** return a SupportCollection

**Comment by canvural** [comment]
Please try it first. I know what I'm talking about. I spent lot's of time on this topic.

**Comment by calebdw** [comment]
![image](https://github.com/larastan/larastan/assets/4176520/0c26f291-a5a1-44fe-993b-dd444080932c)

I mapped a collection of EngineerSeal models to State models---an EloquentCollection is returned, not SupportCollection.

I don't have a custom collection, but if this were then the custom collection would be returned

**Comment by calebdw** [comment]
Just for kicks and grins:

Here's a FooCollection of EngineerSeal models:

![image](https://github.com/larastan/larastan/assets/4176520/724d1473-b20d-4843-ba6b-88c0da8ce5de)

And here's the FooCollection of State models:

![image](https://github.com/larastan/larastan/assets/4176520/506a1ba6-bcdc-40d8-b9fc-fae55f2852a7)

**Comment by canvural** [comment]
Ah, yes. You are right. I was thinking the opposite way for some reason 😅

**Comment by rudiedirkx** [comment]
> `map` always returns a support collection at runtime. It will not return the custom collection. Larastan is right here.

Larastan even tries to do the right thing by returning `static` (in the `map()` `@return`, https://github.com/larastan/larastan/issues/1924#issuecomment-2064576197), but still sometimes it doesn't quite get it.

**Comment by rudiedirkx** [comment]
More details and a demo in #1927
