### ISSUE TITLE
Model scope with explicit return still returns Builder

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#1930]
- Larastan Version: 2.9.5
- PHPStan Level: 2
- Laravel Version: 10.48.8

### Description

Usually, my scopes return `void`, so the original `Builder` is returned for chaining. I explicitly add `: void` to all my scopes to make that clear. Those scopes work. But sometimes I have a scope that actually returns something. No more query chaining, but the end of the query/builder:

In `SiteMetric`:

```php
public function scopeIdsAtTime(Builder $query, int $time) : void {
	// Do stuff to $query
}

/** @return ModelCollection<int, self> */
public function scopeObjectsAtTime(Builder $query) : ModelCollection {
	$ids = $query->pluck('sm_id');
	return self::find($ids);
}
```

But when I dump the return type:

```php
\PHPStan\dumpType(
	SiteMetric::query()
		->idsAtTime($utc) // ✅ Scope with `void` works: EloquentBuilder<SiteMetric>
		->where('sm.site_id', $this->site->id)
		->objectsAtTime() // ❌ This is the 'end' scope with explicit return, but it still says EloquentBuilder<SiteMetric>
);
```

If I debug `BuilderHelper` to see how Larastan finds scope return types:

```php
if ($model->hasNativeMethod('scope' . ucfirst($methodName))) {
	dump($methodName);
	....
	$returnType = $parametersAcceptor->getReturnType();
	dump($returnType->describe(\PHPStan\Type\VerbosityLevel::typeOnly()));
```

I get exactly what I expected and hoped:

```
"idsAtTime"
"void"
"objectsAtTime"
"App\Base\ModelCollection<int, App\Models\SiteMetric>"
```

But somewhere after that I lose track and it ends up as a `EloquentBuilder<SiteMetric>` instead of a `ModelCollection<int, SiteMetric>`.

Why does Larastan find the correct return type, but still uses the other/default one?

**Comment by canvural** [comment]
Hi,

From Laravel [docs](https://laravel.com/docs/10.x/eloquent#local-scopes):

> Scopes should always return the same query builder instance or void

So, returning query results from scopes is not supported.

**Comment by rudiedirkx** [comment]
Aaw =( The Laravel code is perfectly set up for this. And Larastan code too. Why doesn't it use the return type it finds? Still curious.
