### ISSUE TITLE
FilamentPHP macro support

### ISSUE THREAD

**Issue by ariaieboy** [nunomaduro/larastan#1935]
FilamentPHP uses a custom Macroable trait https://github.com/filamentphp/filament/blob/3.x/packages/support/src/Concerns/Macroable.php for its components.

Because of that larastan not detecting custom macros.

**Comment by calebdw** [comment]
I would say that Filament is outside of our concern, and it should include support for its Macros like Carbon does. Or a separate package could be created for it.

However, the easiest thing for Filament to do is to distribute an [auto-discoverable PHPStan extension](https://github.com/phpstan/extension-installer) for its own magic.

**Comment by canvural** [comment]
Hi,

Like it's been said, there is no plan to support anything outside of Laravel. You can create your own extension. Take a look at https://github.com/larastan/larastan/blob/66db15f82209d971e9bcca99ea3b2cb031be9d52/src/Methods/MacroMethodsClassReflectionExtension.php for inspiration.
