### ISSUE TITLE
Date Casting in Eloquent Models causes errors when receiving variable of type string instead of mixed

### ISSUE THREAD

**Issue by JulienSteininger** [nunomaduro/larastan#1936]
- Larastan Version: 2.9.2
- Laravel Version: 10.46.0

### Description
`Property App\Models\SomeModel::$from (Carbon\Carbon) does not accept string.`

The type detection when casting to date seems to rely on the type being mixed. When typehinting the variable as string, larastan reports an error. A string being a subset of mixed should be valid and not cause errors being reported.

### Laravel code where the issue was found
Simplified code where the strict type string is not useful. The strict type definition could be used in a real scenario when using a helper class or a service to save the model instead of saving directly in the controller.
```php
class SomeModel
{
    protected $casts = [
        'from' => 'date',
    ];
}
```
```php
class SomeController
{
    public function store(SomeModelRequest $request): RedirectResponse
    {
        $validated = $request->validated();

        /** @var string $from */
        $from = $validated['from'];
        $someInstance = new SomeModel();
        $someInstance->from_date = $from;
    }
}
```

**Comment by calebdw** [comment]
> The type detection when casting to date seems to rely on the type being mixed

This is not true---when you cast the property to a `date` then the writable type of a property is set to `Carbon` (or the class set by `Date::use()`).

You can either:
- convert `$from` to a carbon instance
- use the `$request->date()` method
- use the model public api instead of setting the property directly (like `fill`)

**Comment by JulienSteininger** [comment]
Thank you very much for the response and the explanation. I already checked 2 of those yesterday :)

However I still do not get why above code is reported erroneous while below code does not yield an error.

```php
class SomeController
{
    public function store(SomeModelRequest $request): RedirectResponse
    {
        $validated = $request->validated();

        /** @var mixed $from */
        $from = $validated['from'];
        $someInstance = new SomeModel();
        $someInstance->from_date = $from;
    }
}
```

**Comment by canvural** [comment]
> Thank you very much for the response and the explanation. I already checked 2 of those yesterday :)
> 
> However I still do not get why above code is reported erroneous while below code does not yield an error.
> 
> ```
> class SomeController
> {
>     public function store(SomeModelRequest $request): RedirectResponse
>     {
>         $validated = $request->validated();
> 
>         /** @var mixed $from */
>         $from = $validated['from'];
>         $someInstance = new SomeModel();
>         $someInstance->from_date = $from;
>     }
> }
> ```

You'd get an error if you use level 8 or 9.

As for the original question, you need to pass a Carbon instance not a string.

**Comment by chippisc** [comment]
> You'd get an error if you use level 8 or 9.

Thank you very much! and sorry for not having checked that myself. 👍
