### ISSUE TITLE
`When` method do not supports clousure with `whereIn` expression

### ISSUE THREAD

**Issue by matysekmichal** [nunomaduro/larastan#1937]
- Larastan Version: 2.9.5
- Laravel Version: 11.5.0

### Description
```
Anonymous function should return Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model> but returns Illuminate\Database\Eloquent\Builder<App\Models\User>.
    Template type TModelClass on class Illuminate\Database\Eloquent\Builder is not covariant. Learn more:
    https://phpstan.org/blog/whats-up-with-template-covariant
```

There is no problem when to the `when` is provided a callback with a `where` expression, but other statements such as `whereIn` or `whereNotNull` and probably much more causes this error.

### Laravel code where the issue was found

```php
User::query()
    ->when(
        $names !== [],
        static fn (\Illuminate\Database\Eloquent\Builder $query) => $query->whereIn('name', $names)
    )
```

**Comment by canvural** [comment]
Hi,

This is a known limitation of PHPStan unfortunately. We cannot influence the types inside the closure. 

As a not ideal workaround you can remove the typehint in the closure. Then, it might work fine.
