### ISSUE TITLE
Class App\Rules\ValidateCPF implements class Illuminate\Validation\Rule. 

### ISSUE THREAD

**Issue by yanpenalva** [nunomaduro/larastan#1938]
- Larastan Version: 2.9.5
- Laravel Version: 11

### Description
I have a custom rule for validating CPF(Brazilian register); When I create this rule, I receive this: 
'Illuminate\Contracts\Validation\Rule' is deprecated" 

Then, I updated to Illuminate\Validation\Rule;

But when I run my larastan, I receive this error: 
`Class App\Rules\ValidateCPF implements class Illuminate\Validation\Rule.`

So what would be right? Since the previous call is depreciated, Larastan still doesn't recognize that.

### Laravel code where the issue was found

```php
<?php

namespace App\Rules;

use Illuminate\Validation\Rule;

class ValidateCPF implements Rule
{
  /**
   * Determine if the validation rule passes.
   *
   * @param  string  $attribute
   * @param  mixed  $value
   * @return bool
   */
  public function passes($attribute, $value)
  {
    $cpf = preg_replace('/\D/', '', $value);

    if (strlen($cpf) != 11) {
      return false;
    }

    if (preg_match("/^{$cpf[0]}{11}$/", $cpf)) {
      return false;
    }

    for ($t = 9; $t < 11; $t++) {
      for ($d = 0, $c = 0; $c < $t; $c++) {
        $d += (int)$cpf[$c] * (($t + 1) - $c);
      }
      $d = ((10 * $d) % 11) % 10;
      if ($cpf[$c] != $d) {
        return false;
      }
    }

    return true;
  }

  /**
   * Get the validation error message.
   *
   * @return string
   */
  public function message()
  {
    return 'O campo :attribute não é um CPF válido.';
  }
}

```

**Comment by szepeviktor** [comment]
Hello!!

How about `implements \Illuminate\Contracts\Validation\ValidationRule` ?

**Comment by calebdw** [comment]
Here's the docs: https://laravel.com/docs/11.x/validation#using-rule-objects

**Comment by yanpenalva** [comment]
> Hello!!
> 
> How about `implements \Illuminate\Contracts\Validation\ValidationRule` ?

I've implemented it similar to what I told you in the 
“Laravel code where the problem was found” tab

The difference is that it replaces the import at the top of the file.


> Here's the docs: https://laravel.com/docs/11.x/validation#using-rule-objects

Ok, I use this, but larastan kept complaining that he didn't recognize this implementation.

**Comment by calebdw** [comment]
> Ok, I use this, but larastan kept complaining that he didn't recognize this implementation.

Can you show your new code?

**Comment by yanpenalva** [comment]
> > Ok, I use this, but larastan kept complaining that he didn't recognize this implementation.
> 
> Can you show your new code?

**The code with the deprecated function**
```

<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class ValidateCPF implements Rule
{
    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        $cpf = preg_replace('/\D/', '', $value);

        if (strlen($cpf) != 11) {
            return false;
        }

        if (preg_match("/^{$cpf[0]}{11}$/", $cpf)) {
            return false;
        }

        for ($t = 9; $t < 11; $t++) {
            for ($d = 0, $c = 0; $c < $t; $c++) {
                $d += (int) $cpf[$c] * (($t + 1) - $c);
            }
            $d = ((10 * $d) % 11) % 10;
            if ($cpf[$c] != $d) {
                return false;
            }
        }

        return true;
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'O campo :attribute não é um CPF válido.';
    }
}

```

And the error in my vs code: 
![image](https://github.com/larastan/larastan/assets/72168914/d791ef3d-740e-4296-be45-d853fc881b93)

**The code with the new call but the error in Larastan when I run it**

```
<?php

namespace App\Rules;

use Illuminate\Validation\Rule;

class ValidateCPF implements Rule
{
  /**
   * Determine if the validation rule passes.
   *
   * @param  string  $attribute
   * @param  mixed  $value
   * @return bool
   */
  public function passes($attribute, $value)
  {
    $cpf = preg_replace('/\D/', '', $value);

    if (strlen($cpf) != 11) {
      return false;
    }

    if (preg_match("/^{$cpf[0]}{11}$/", $cpf)) {
      return false;
    }

    for ($t = 9; $t < 11; $t++) {
      for ($d = 0, $c = 0; $c < $t; $c++) {
        $d += (int) $cpf[$c] * (($t + 1) - $c);
      }
      $d = ((10 * $d) % 11) % 10;
      if ($cpf[$c] != $d) {
        return false;
      }
    }

    return true;
  }

  /**
   * Get the validation error message.
   *
   * @return string
   */
  public function message()
  {
    return 'O campo :attribute não é um CPF válido.';
  }
}

```

The only difference is the import. 
I ended up keeping the `use Illuminate\Contracts\Validation\Rule`; to avoid the error and put it in my phpstan.neon and ignored the Rule/ValidateCPF path.

**Comment by calebdw** [comment]
The problem is that `Illuminate\Validation\Rule` is not a contract and therefore you cannot implement it.

You need to use `Illuminate\Contracts\Validation\ValidationRule`

**Comment by yanpenalva** [comment]
> The problem is that `Illuminate\Validation\Rule` is not a contract and therefore you cannot implement it.
> 
> You need to use `Illuminate\Contracts\Validation\ValidationRule`

Thanks for you help;

I refactoring my Rule and apply this: 


```php
<?php

namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule as Rule;

class ValidateCPF implements Rule
{
  public function validate(string $attribute, mixed $value, Closure $fail): void
  {
    $cpf = preg_replace('/\D/', '', $value);

    if (strlen($cpf) != 11) {
      $fail('CPF deve conter 11 dígitos.');
    }

    if (preg_match("/^{$cpf[0]}{11}$/", $cpf)) {
      $fail('CPF inválido.');
    }

    for ($t = 9; $t < 11; $t++) {
      for ($d = 0, $c = 0; $c < $t; $c++) {
        $d += (int) $cpf[$c] * (($t + 1) - $c);
      }
      $d = ((10 * $d) % 11) % 10;
      if ($cpf[$c] != $d) {
        $fail($this->message());
      }
    }
  }

  /**
   * Get the validation error message.
   *
   * @return string
   */
  public function message()
  {
    return 'O campo :attribute não é um CPF válido.';
  }
}
```

Then, it's work!
