### ISSUE TITLE
Analysis is considerably slower when Larave11 is used.

### ISSUE THREAD

**Issue by Sado4** [nunomaduro/larastan#1943]
- Larastan Version: 2.9
- Laravel Version: 11.7

### Description

This was not a problem in Laravel 10, but when updating to Larave 11, stan becomes extremely slow. Specifically, what used to take around 30 seconds takes 9 minutes, etc.

### Laravel code where the issue was found

Thus, it stops at 94%.

```
Result cache not used because the metadata do not match: projectConfig, analysedPaths
 703/743 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  94% 19 secs/20 secs
```

**Comment by calebdw** [comment]
We execute Larastan on a Laravel installation in the tests:

19s on Laravel 11:
https://github.com/larastan/larastan/actions/runs/8993915765/job/24706568451

20s on Laravel 10:
https://github.com/larastan/larastan/actions/runs/8993915765/job/24706567912

This would appear to be influenced by your specific config/files/etc. Without additional information there's not much we can do.

Try running PHPStan with the `--debug -vvv` switches to see what files take the longest.

**Comment by Sado4** [comment]
@calebdw (@szepeviktor)

Thank you for your reply.

I used `--debug` `-vvv` and found the cause. It seemed to be a large enum file that was taking a long time.

Specifically, an enum file that has over 100 cases and several methods that reference them. If necessary, I will send you the file information so you can investigate.

[LibraryMasterEnum.php.zip](https://github.com/larastan/larastan/files/15256325/LibraryMasterEnum.php.zip)

As I repeat, this will be done immediately with no problem in Laravel 10, but this will start to slow down in Laravel 11.

Thank you in advance.

**Comment by Sado4** [comment]
[LibraryMasterEnum.php.zip](https://github.com/larastan/larastan/files/15256322/LibraryMasterEnum.php.zip)

**Comment by canvural** [comment]
Hi,

Maybe you also upgraded the PHPStan version during the upgrade to Laravel 11. I don't think Larastan itself causing the issue. Please try with the older version of PHPStan first and see if it is slow still. If it is we might say it's an issue with Larastan, if not probably it's an issue with PHPStan itself and open an issue there.

Thank you.
