### ISSUE TITLE
Improve Laravel 11 attribute casting

### ISSUE THREAD

**Issue by tobiasdalhof** [nunomaduro/larastan#1947]
It's great that Larastan now has support for Laravel 11 model casts. However, users should not have to define the return type.

I understand that this can be difficult to implement, but it would greatly improve the developer experience.

**Comment by szepeviktor** [comment]
https://github.com/larastan/larastan/commit/66db15f82209d971e9bcca99ea3b2cb031be9d52#commitcomment-141843347 👈🏻

**Comment by tobiasdalhof** [comment]
> [66db15f#commitcomment-141843347](https://github.com/larastan/larastan/commit/66db15f82209d971e9bcca99ea3b2cb031be9d52#commitcomment-141843347) 👈🏻

I've seen the commit comments, but I think we should keep this topic open

**Comment by canvural** [comment]
Hi,

I understand your concern. But another thing to keep in mind is this is a static analysis tool. The entire concept depends on types. If you don't want to define your return types, then maybe you should reconsider if static analysis is right for you.

About the Laravel 11 casting, currently there is no better solution unfortunately.

**Comment by tobiasdalhof** [comment]
Hi @canvural

Your main concern is executing user code in Larastan, right? For projects that use [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper), maybe we can pull the cast type from the generated IDE helper code and use PHPDoc as a fallback

Example: 

![image](https://github.com/larastan/larastan/assets/10046578/ca4d1d14-9b6e-417a-a08e-b60132a5a278)

**Comment by niekbr** [comment]
I think its important this feature request remains open so there can be discussions for improvements, even if its not planned on short-term. Defining all casts twice really messes up a codebase if a model has many casts, as you can see in this example: 

![image](https://github.com/larastan/larastan/assets/10487997/0717a90f-91ad-4449-9b40-a44455cd5646)
