### ISSUE TITLE
TWhenReturnType error

### ISSUE THREAD

**Issue by makroxyz** [nunomaduro/larastan#1961]
- Larastan Version: 2.9.6
- Laravel Version: 10.48
- PHPStan 1.11.2

### Description
error: Unable to resolve the template type TWhenReturnType in call to method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::when()   

PHPStan 1.11.1 was fine!

### Laravel code where the issue was found

```php
$this->query
    /** @phpstan-ignore-next-line */
    ->when($this->type, fn ($q, $value) => $q->type($value))
    ->paginate($this->request->get('per-page'))

```

**Comment by canvural** [comment]
Hi,

This is coming from PHPStan. And I believe only in bleeding edge.

I'll report it there and see if it was intentional.
