### ISSUE TITLE
Larastan 2.9.7 dependencies broken

### ISSUE THREAD

**Issue by daniser** [nunomaduro/larastan#1962]
- Larastan Version: 2.9.7
- Laravel Version: 11.8.0

### Description
During installation of latest Larastan version, it uninstalls `phpstan/phpstan` and `phpmyadmin/sql-parser` dependencies from my project.

**Comment by canvural** [comment]
Hi,

That's weird. I updated couple of projects and did not see this. 

Could you try to debug it a little bit more maybe?

**Comment by daniser** [comment]
@canvural it just been fixed by itself. Probably was something with Packagist metadata.
