### ISSUE TITLE
Access to an undefined property on a JsonResource

### ISSUE THREAD

**Issue by encore-tomv** [nunomaduro/larastan#1965]
- Larastan Version: 2.9.6
- Laravel Version: 11.7.0

### Access to an undefined property
I understand the reasoning behind this message, however I don't know what the best way of solving this is.
There are countless suggestions to use the `@mixin Model` in your resource class. However, this doesn't fix the issue regarding additional attributes for instance: withCount, withSum, subSelects, etc.

Should I add these as properties in my resource class phpdoc? Or am I doing something that does not conform to Laravel?

### Laravel code where the issue was found
_(this is a calculated column using a subquery, thus doesn't exist on the model referenced in the mixin)_

```php
 'stock' => $this->stock,
```

**Comment by canvural** [comment]
Hi,

> (this is a calculated column using a subquery, thus doesn't exist on the model referenced in the mixin)

This is exactly the reason. If you add a property to the model from a query, that is not really discoverable by static analysis. 

You can add `@param int $stock` in your `JsonResource` class.

**Comment by santigarcor** [comment]
@canvural What is recommended to do in cases when you use `withSum` or extra selects?

**Comment by calebdw** [comment]
You can use the `->getAttribute()` public api

**Comment by canvural** [comment]
> [@canvural](https://github.com/canvural) What is recommended to do in cases when you use `withSum` or extra selects?

It is the same. You can add it to your resource via `@property` tag, or you can ignore the errors based on property name.

**Comment by santigarcor** [comment]
> > [@canvural](https://github.com/canvural) What is recommended to do in cases when you use `withSum` or extra selects?
> 
> It is the same. You can add it to your resource via `@property` tag, or you can ignore the errors based on property name.

Well I don't think this option is a good solution because then I'll have to fill the model with properties that won't be always available. Also I'm trying to avoid as many errors as possible.

> You can use the `->getAttribute()` public api

In think this one is a better option.

Thanks to both of you.
