### ISSUE TITLE
Variable "$foo" is propably undefined when using ->when() function on eloquent.

### ISSUE THREAD

**Issue by VaclavKlima** [nunomaduro/larastan#1966]
- Larastan Version: v2.9.7
- Laravel Version: 10.48.12

### Description
Using `when` with `isset()` function in it still throws warning "Variable $ids might not be defined. "

### Laravel code where the issue was found

```php
if ($user->is_admin) {
     $ids = Position::pluck('id')
}

InvoiceableItem::query()
   ->when(isset($ids), fn($query) => $query->whereIn('position_id', $ids))
   ->get();
```

**Comment by calebdw** [comment]
That's because you're accessing the `$ids` from the outer scope which hasn't has the isset applied to it (from static analysis standpoint).

First use a null default value, and then use the `$ids` that is passed to the closure:

```php
$ids = null;

if ($user->is_admin) {
     $ids = Position::pluck('id')
}

InvoiceableItem::query()
   ->when($ids, fn($query, $ids) => $query->whereIn('position_id', $ids))
   ->get();
```

**Comment by szepeviktor** [comment]
🤝 
```php
$ids = $user->is_admin
    ? Position::pluck('id')
    : [];
```

**Comment by calebdw** [comment]
Can this issue be closed? There's nothing for us to do here...
