### ISSUE TITLE
"Access to an undefined property" for all properties of models that are not direct descendants of the Model class

### ISSUE THREAD

**Issue by chosten** [nunomaduro/larastan#1967]
- Larastan Version: 2.9.7
- Laravel Version: 10

### Description
Models that are not direct descendants of the Model class are not properly instantiated in the `hasDatebaseProperty` method of the `Larastan\Larastan\Properties\ModelPropertyHelper` class. (There is a typo in that method name btw)

### Laravel code where the issue was found

```php
class BaseModel extends \Illuminate\Database\Eloquent\Model {}

final class RealModel extends BaseModel
{
    protected $table = 'real_models';
}
```

With that configuration the table name returned in ModelPropertyHelper will be `base_models` instead of `real_models` resulting in undefined properties.

**Comment by calebdw** [comment]
I use a base model and I don't have any issues, and we override the model table names with the `$table` property.

The code checks if `Model` is a parent, the class is not abstract, and it uses `getTable()`, so it should work:

https://github.com/larastan/larastan/blob/5948c964d711fee7859275713e906f172c9d2ca6/src/Properties/ModelPropertyHelper.php#L59-L82

**Comment by chosten** [comment]
Do you see any reason why $classReflectionOrTable is my `BaseModel` instead of the `RealModel` when doing a simple `RealModel::first()->id` ?

**Comment by calebdw** [comment]
That means the generics are messed up. What does `RealModel::query()->first()->id` return?

You can also (and probably should) set `BaseModel` to be `abstract` which will prevent it from being new'd up

**Comment by chosten** [comment]
It returns the value of the field correctly.
Adding abstract is correct but it does not help with this specific problem it seems.

**Comment by calebdw** [comment]
Hmm, just curious, but can you try the branch in this PR: https://github.com/larastan/larastan/pull/1874 to see if that fixes the issue?

![image](https://github.com/larastan/larastan/assets/4176520/29e8d054-eb42-4cb8-b55b-da357e5e9f05)

**Comment by chosten** [comment]
That did not help, but the abstract thing actually helped. Sorry the cache is playing with me. I still have the undefined properties errors but now the problem seems to be in the `SquashedMigrationHelper`.
I already had to clean the SQL manually because the parser was crashing, so there might be more problems with it. (FYI it was crashing due to stored procedures)

Thanks for your help, I need to investigate more and will close this since it is obviously not a inheritance problem.
