### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Str::kebab()

### ISSUE THREAD

**Issue by LuizCristino** [nunomaduro/larastan#1970]
- Larastan Version: 2.9.7
- Laravel Version: 11.10.0

### Description
I just installed the larastan to start check my project and this error appeared:

```
Call to an undefined static method Illuminate\Support\Str::kebab()
```

### Laravel code where the issue was found

```php
public function getLabel(): ?string
  {
    return __(sprintf('enums/asset/%s.%s.%s', Str::kebab(class_basename(self::class)), self::class, $this->name));
  }

```

**Comment by szepeviktor** [comment]
Hello @LuizCristino 👋🏻 

We are out of kebab currently, but will fix it in the next release.

https://github.com/laravel/framework/blob/fecf031bffad5ae986cab43c0d505bfb9c28f510/src/Illuminate/Support/Str.php#L569

**Comment by szepeviktor** [comment]
I've added
```php
$a = \Illuminate\Support\Str::kebab('AlmaKörte');
```
to a random file in app/ and I get no error messages on level 5.

**Comment by canvural** [comment]
Hi,

As @szepeviktor mentioned the method is there and I cannot reproduce this. I'm sure it's something with your setup. Do you have any other strange errors or just this?

**Comment by LuizCristino** [comment]
Only this problem with kebab from the Str support class.

**Comment by canvural** [comment]
Cannot produce.
