### ISSUE TITLE
error when installing larastan on fresh herd project

### ISSUE THREAD

**Issue by alifnuryana** [nunomaduro/larastan#1971]
- Larastan Version: 2.0.0
- Laravel Version: ^11.9

### Description
error when installing larastan on fresh herd project

```powershell
composer require larastan/larastan:^2.0 --dev
```
![image](https://github.com/larastan/larastan/assets/38722267/0be1caa5-85c7-4092-9615-ebdfde5e9dd0)

**Comment by szepeviktor** [comment]
Hello @alifnuryana 👋🏻 

You are on Windows. Try
```console
composer require "larastan/larastan:^2.0" --dev
```
Caret is a special character.
