### ISSUE TITLE
Access to an undefined property

### ISSUE THREAD

**Issue by FrancisMawn** [nunomaduro/larastan#1972]
- Larastan Version: 2.9.2
- Laravel Version: 10.48.4

### Description
I have a model attribute called "event" used to stored a serialized event instance.
The attribute is defined like any other attributes within a database migration.
```php
Schema::create('operations', function (Blueprint $table): void {
    $table->text('event')->nullable();
});
```

I also have an attribute accessor/mutator defined on the Operation model to handle the serialization.
```php
protected function event(): Attribute
{
    return Attribute::make(
        set: fn ($value) => serialize($value),
        get: fn ($value) => unserialize($value),
    );
}
```

PHPStan complains that the property is undefined on the model.
![image](https://github.com/larastan/larastan/assets/45174482/68bab2e4-5434-44cc-bf95-9f9535a1f225)

Here is the code in question in case that would help:
```php
// Retrieve the pending jobs batch from the dispatched event.
/** @var ?PendingBatch $batch */
[$batch] = Event::dispatch($operation->event);
```

Interresting fact:
If I remove the **event()** method on the Operation model, PHPStan no longer complains.
I can always add the property docblock on the model class to resolve this issue but it seems like an odd behavior?
Am I missing something?

**Comment by canvural** [comment]
Hi,

I think it's because you are missing generic annotation for your attribute. If you update it like so

```php
/** @return Attribute<string, string> */
protected function event(): Attribute
```

it should be fine. The types inside the generic annotations are the `set` and `get` types. In order. Feel free to change them to suit your case.

**Comment by bibrokhim** [comment]
This solution did not help me.
Laravel Framework 10.48.10
Larastan Version: 2.9.7

I have an accessor in Customer model:
```php
/** @return Attribute<string, never> */
public function fullName(): Attribute
{
    return Attribute::get(
        fn () => "$this->name $this->surname $this->patronymic",
    );
}
```

![image](https://github.com/larastan/larastan/assets/74450789/8ad9c9b0-6ba8-437d-a85c-a607859abce5)

**Comment by calebdw** [comment]
Accessors / computed properties need to be `protected`

**Comment by bibrokhim** [comment]
@calebdw Yes, that was the problem. Thank You!
