### ISSUE TITLE
The `analyse` command doesn't seem to properly traverse nested directories

### ISSUE THREAD

**Issue by travisobregon** [nunomaduro/larastan#1973]
- Larastan Version: 2.9.7
- Laravel Version: 11.10.0

### Description

I have installed Larastan in a fresh Laravel app with Breeze using Inertia and React. The phpstan.neon file I am using is the same that is in the README with `paths` set to "app/". This returns "[OK] No errors", which is unexpected. However, if I set `paths` to "app/Http/Controllers/", the analyse command correctly returns "[ERROR] Fond 1 error".

**Comment by szepeviktor** [comment]
Hello!
What is the error message?

**Comment by calebdw** [comment]
What is the error? This is likely because by narrowing your path to `app/Http/Controllers` phpstan has missing context from other files in the other directories.

You would also have to tell PHPStan to [scan the other directories](https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies) without analyzing so it properly discovers all the symbols.

If Larastan works when analyzing `app/` then I don't see a bug here.

**Comment by travisobregon** [comment]
Sorry, I am expecting Larastan to highlight errors when the the path is `app/`, but it doesn't:
<img width="961" alt="Screenshot 2024-06-13 at 17 18 03" src="https://github.com/larastan/larastan/assets/12074713/1782727c-452c-41ec-b199-4cff5096c8db">


If I narrow the path to `app/Http/Controllers` I get:
<img width="1257" alt="Screenshot 2024-06-13 at 17 18 34" src="https://github.com/larastan/larastan/assets/12074713/f416a86f-b786-4297-8a84-8fbf42e672f4">

**Comment by szepeviktor** [comment]
What if you specify two paths? `app/Http/Controllers app/Models`

**Comment by calebdw** [comment]
So what's the problem? The User model extends the framework User model:

https://github.com/laravel/laravel/blob/3b3f9f13faab1753e7b7cad6a0e7098e54c8199f/app/Models/User.php#L6-L10

which in turn implements the contract:

https://github.com/laravel/framework/blob/741560fc1405dd2ee7b319cb2a9305728e52d969/src/Illuminate/Foundation/Auth/User.php#L5-L20


You're getting this error because by only analyzing `app/Http/Controllers` PHPStan has not scanned the User model and doesn't know that the model implements the contract.

There is no bug here, the failure is expected.

**Comment by travisobregon** [comment]
> What if you specify two paths? `app/Http/Controllers app/Models`
Still one error, but you can see that it scanned an extra file (12/12)
<img width="1263" alt="Screenshot 2024-06-13 at 17 27 23" src="https://github.com/larastan/larastan/assets/12074713/3da44f6b-11f4-4094-ac6f-5c88544f5511">




> So what's the problem? The User model extends the framework User model:
> 
> https://github.com/laravel/laravel/blob/3b3f9f13faab1753e7b7cad6a0e7098e54c8199f/app/Models/User.php#L6-L10
> 
> which in turn implements the contract:
> 
> https://github.com/laravel/framework/blob/741560fc1405dd2ee7b319cb2a9305728e52d969/src/Illuminate/Foundation/Auth/User.php#L5-L20
> 
> You're getting this error because by only analyzing `app/Http/Controllers` PHPStan has not scanned the User model and doesn't know that the model implements the contract.
> 
> There is no bug here, the failure is expected.

Shouldn't I also get the error in `VerifyEmailController` if the path is just `app/`?

**Comment by travisobregon** [comment]
Sorry, I think understand what you may be saying now @calebdw.

**Comment by travisobregon** [comment]
Although that means adding the paths`app/Http/Controllers` and `app/Models` should have returned no errors, but it did.

**Comment by travisobregon** [comment]
If we look at a simpler example though, in `AppServiceProvider` I have added this to the `boot` method:
```
$property = User::query()->firstOrNew()->this_property_does_not_exist;
```

With the `paths` in the PHPStan config only set to `app/`, no errors are returned:
<img width="950" alt="Screenshot 2024-06-13 at 17 42 29" src="https://github.com/larastan/larastan/assets/12074713/cfab3b18-5533-46f8-8392-b3e5f99971e5">


With the `paths` in the PHPStan config set to include `app/Providers`, or `app/Providers` and `app/Models` , an error is returned:
<img width="766" alt="Screenshot 2024-06-13 at 17 44 18" src="https://github.com/larastan/larastan/assets/12074713/d38da682-9f5a-4b9a-b67a-0935d5b7e9c6">

**Comment by calebdw** [comment]
What does your phpstan config look like?

Try running phpstan with `--debug -vvv`

**Comment by travisobregon** [comment]
phpstan.neon
```
includes:
    - vendor/larastan/larastan/extension.neon
parameters:
    paths:
        - app/Providers
        - app/Models
    # Level 9 is the highest level
    level: 5
```

Ah, after running with `--debug -vvv` it seems to have cleared some cache? Now I am getting the error with just `app/`

**Comment by calebdw** [comment]
Yep, `--debug` clears the cache, there's also a command that will clear it: https://phpstan.org/user-guide/result-cache

**Comment by szepeviktor** [comment]
@travisobregon Maybe reporting this cache issue to phpstan/phpstan will benefit many.

**Comment by travisobregon** [comment]
Thanks both for your time. 

How would you describe that issue in phpstan/phpstan? Just that there seems to be some aggressive caching on first install and then link to this issue?

**Comment by szepeviktor** [comment]
Changing paths in the config file vs. on the command line produces the same error?

**Comment by travisobregon** [comment]
I did try setting the path on the command line to `app/` before the cache was cleared and was getting the same output as with just the config file.

**Comment by canvural** [comment]
Hi,

Looks like this is not related to Larastan. You can read more about PHPStan's result cache [here](https://phpstan.org/user-guide/result-cache).
