### ISSUE TITLE
dynamicWhere() expects string, int|null given.

### ISSUE THREAD

**Issue by loic-lopez** [nunomaduro/larastan#198]
- Larastan Version: 0.3.8
- `--level` used: 1

### Description:
Throw this error:
```bash
Parameter #1 $parameters of static method Illuminate\Database\Query\Builder::dynamicWhere() expects string, int|null given.
```
### Laravel code where the issue was found:
```php
/**
* Display the specified resource.
*
* @return \Illuminate\Http\JsonResponse
*/
public function show()
{
    return $this->ok(UserProfile::whereId(Auth::id())->first());
}
```

**Comment by nunomaduro** [comment]
@loic-lopez There is 2 issues with that code.

First: `whereId` expects a string, and you are providing an `int`.

Second: The result of `Auth::id()` may be null, you may want to add a if condition before using the `whereId` with that result.

**Comment by loic-lopez** [comment]
Thanks for reply.

Firstly in my case Auth::id() can't be NULL because is a protected route with : `Route::group(['middleware' => 'auth:api'])`

Secondly in my case Auth::id() will return a string because i use Uuid as primary key.

**Comment by nunomaduro** [comment]
@loic-lopez Thanks for the details.

Try to cast the `null`/`int` to `string`
```
return $this->ok(UserProfile::whereId((string) Auth::id())->first());
```

**Comment by loic-lopez** [comment]
It's an unnecessary cast.

What i do in phpstan.neon: `'#Illuminate\\Database\\Query\\Builder::dynamicWhere()#'`

**Comment by loic-lopez** [comment]
Thanks for reply, also i use [https://github.com/barryvdh/laravel-ide-helper](url) to generate data about Models and more.

Can generated files may help larastan?

**Comment by szepeviktor** [comment]
I've been through laravel-ide-helper etc. and I can say that Larastan is the clear winner with a huge distance to the second place!

**Comment by szepeviktor** [comment]
Larastan is a bunch of extension on top of PHPStan.
So we need a quick PR to resolve a false positive.
