### ISSUE TITLE
Add support for Cashier wrapper classes

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/larastan#1981]
# Feature Request

Cashier has multiple classes which is wrapping stripe objects. They however only forward the properties not the methods, so it cannot be solved with `@mixin` in `Cashier` itself. 

https://github.com/laravel/cashier-stripe/pull/1685

**Comment by szepeviktor** [comment]
Strange things need stubs!

**Comment by calebdw** [comment]
Or just access the property on the Stripe object itself:

```php
$invoice->asStripeInvoice()->foobar;
```

**Comment by olivernybroe** [comment]
@calebdw def. worth mentioning the workaround, ty! 
but it is still a missing support that seems fixable :)

**Comment by szepeviktor** [comment]
> the workaround,

We could call it _explicit solution_.

**Comment by calebdw** [comment]
In any case, I don't think this this something that Larastan needs to support. A stub requires the same maintenance burden as class `@property` tags and Larastan's primary concern is providing support for the framework and not other packages.

However, it may be worthwhile to open an issue at [phpstan/phpstan](https://github.com/phpstan/phpstan) to see if Ondrej would be okay with adding more fine-grained control over what gets mixed in via the `@mixin` tag

For example:
```php
/** @mixin-properties Foo */
/** @mixin-methods Foo */
```

Keep in mind that the package itself can create an [auto-installable extension](https://github.com/phpstan/extension-installer) for its own magic. Carbon does the same thing to provide support for its macro system

**Comment by olivernybroe** [comment]
Yeah good idea, I'll ask Ondrej what he feels about more finegrained mixins :) 

https://github.com/phpstan/phpstan/issues/11259
