### ISSUE TITLE
Custom ModelCollection still not recognized/kept after method

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#1985]
- Larastan Version: v2.9.9
- Laravel Version: v11.23.5

### Description

I have a custom eloquent collection with a custom method that I made a Phpstan plugin for, and that works. And then I call `unique()` on that collection, and then Larastan thinks it's an `EloquentCollection` instead of a `ModelCollection`:

### Laravel code where the issue was found

```php
\PHPStan\dumpType($this->logs); // Dumped type: array<int, App\Models\MiscLog>

$logs = ModelCollection::make($this->logs);
\PHPStan\dumpType($logs); // ✅ Dumped type: ModelCollection<int, App\Models\MiscLog>

\PHPStan\dumpType($logs->relation('organization')); // ✅ Dumped type: ModelCollection<int, App\Models\Organization>

\PHPStan\dumpType($logs->relation('organization')->unique()); // ❌ Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\Organization>
```

Phpstan understands `->relation()` (because of that custom plugin I made), but it doesn't understand `->unique()` (which is Larastan's or Laravel's 'responsibility'?). I feel like `unique()` should work.

----

I thought this was fixed for a lot of Laravel collection methods recently. Maybe it's still the same problem as #1927?

**Comment by rudiedirkx** [comment]
Any advice on this? Still doesn't work in Laravel 11 and Larastan 2.9.9.

Laravel's `unique()` has hint `@return static<int, TModel>`, and with that it doesn't work for me. But if I change that to just `@return static` it does work 😮 Phpstan understands the collection class AND the generic types inside:

    Dumped type: App\Base\ModelCollection<int, App\Models\Organization>

instead of

    Dumped type: Illuminate\Database\Eloquent\Collection<int, App\Models\Organization>

Maybe because `EloquentCollection::unique()` overwrites `Collection::unique()` with a different generic name?? `TModel` instead of `TValue`. I have no idea.

----

I can achive the same as `unique()` with `keyBy('id')`, but that's hacky.

**Comment by calebdw** [comment]
Fixed in the framework: https://github.com/laravel/framework/pull/53239

**Comment by szepeviktor** [comment]
> Fixed in the framework: [laravel/framework#53239](https://github.com/laravel/framework/pull/53239)

to be fixed ...

**Comment by canvural** [comment]
Fixed with f97d92ee

**Comment by rudiedirkx** [comment]
I'm glad it's fixed, but why did it fail? The `@return` made sense, didn't it?

**Comment by canvural** [comment]
@rudiedirkx Generic static type is not really supported by PHPStan. It's a weird concept as of right now. So we have some workaround for it in Larastan, and I just added `unique` method to that list. So `@return` made sense, yes.
