### ISSUE TITLE
Undefined Properties Error After Adding New Columns in Laravel Model

### ISSUE THREAD

**Issue by hirenkeraliya** [nunomaduro/larastan#1993]
- Larastan Version: v2.9.7
- Laravel Version: v10.48.12

### Description
I am encountering an issue with undefined properties in a Laravel model. I added new columns to an existing table using Laravel's after closure. However, I am now receiving errors related to undefined properties.

### Steps to Reproduce:

- Add new columns to an existing table using Laravel's after closure.
- Attempt to access the new columns in the model.

#### Expected Behavior:
- The new columns should be accessible in the Laravel model without any errors.

#### Actual Behavior:
- An undefined property error occurs when accessing the newly added columns.

#### Additional Information:
Upon investigation, it appears that the after-closure is not [being considered](https://github.com/larastan/larastan/blob/2.x/src/Properties/SchemaAggregator.php) correctly, which is causing the undefined property error.

### Laravel code where the issue was found

```
Schema::table('users', function (Blueprint $table): void {
    $table->after('status', function () use ($table) {
        $table->string('city')->nullable();
        $table->string('area_code')->nullable();
    });
});
```

**Comment by hirenkeraliya** [comment]
It will work if I will do something like this.

```
Schema::table('users', function (Blueprint $table): void {
    $table->after('status', function (Blueprint $table) {
        $table->string('city')->nullable();
        $table->string('area_code')->nullable();
    });
});
```

**Comment by szepeviktor** [comment]
> `$table->after('status', function (Blueprint $table) {`

This is the correct form.
Maybe add `: void` here too.

**Comment by hirenkeraliya** [comment]
Got it. As per the [laravel documentation](https://laravel.com/docs/10.x/migrations#column-order), it is right. But I think it will create a new object for the Blueprint class.
