### ISSUE TITLE
Detect calling 'class' level methods against an instantiated/hydrated model, such as first()

### ISSUE THREAD

**Issue by EliW** [nunomaduro/larastan#1994]
# Feature Request
My apologies if this has been discussed before, but I tried hard to search the issues/discussions about this and couldn't find anything ... but it was hard to search for 'exactly' this.

We ran into a bug in our codebase today that was a 'stupid bug', and was something that I would have 100% expected static analysis to find and alert us about.   (To be fair, I would have expected PHP/Laravel to throw an error if you try this, but it appears that it's "by design".

## The situation

So the simplest example of this problem, is that you are able in Laravel to make a call to what I would call a 'class level' method (ie, referencing relationships, scopes, etc) against a single instantiated/hydrated model, where you wouldn't expect this to happen.  For example, the `first()` method.   Which means, if you have a model called `Tenant`, then the following code 'works':
```php
Tenant::find(56789)->first();
```

It works, but it doesn't do at all what you would expect, because what it does is return the very first tenant in your system.   Which obviously is not at all what one would expect to have gotten.   While this exact case is somewhat 'made up'.  The real example was more hidden in our code, because we basically had the following:
```php
// in Policy model:
    public function tenants(): BelongsToMany
    {
        return $this
            ->belongsToMany(Tenant::class, 'tenant_policy', 'policy_id', 'tenant_id')
            ->using(TenantPolicy::class)
            ->withPivot('type')
            ->withTimestamps();
    }

    public function primaryTenant(): ?Tenant
    {
        return $this->tenants()->wherePivot('type', PRIMARY)->first();
    }

// elsewhere in a command we were running:
                    $policy = Policy::where('carrier_policy_number', $policy_number)->first();
                    $tenant = $policy->primaryTenant()?->first();
```

Now obviously when these lines of code are jammed together it's pretty obvious now what the bug was.  But in full context of thousands of lines of code, it wasn't and this problem was caused during a refactor.   originally that `primaryTenant` method returned the entire pivot of PRIMARY ... and code everywhere called `->first()` ... a refactor made us realize that was silly, since you only ever have a single primary tenant anyway, so we updated this method to return just the Tenant model itself.

But that one line of code off in a command that was run in a cron job ... was missed.  And was still calling `->first()`, and suddenly 'everyone' became the first Tenant in our system.   (luckily it was only reading them in to do some logging, not changing any data).

## The Proposal

I'd propose that if phpstan detects that you have an instantiated/hydrated Model class, that you throw an error if you see a call to any methods that are passthroughs to biulder, such as `all`, `first`, `where`, `where*`, any scopes, `chunk`, `chunk*`, `lazy*`, `select`, `addSelect` ... well the list goes on.

And only would allow direct calls to methods that are actually defined for that model, no passthrough magic methods.

**Additional context**
FWIW we are currently running on phpstan level:5 ... just in case the answer to all this is "we do that, on level 7" ;)

**Comment by calebdw** [comment]
Hmm, I'm not sure about this---on one hand there's nothing *wrong* with mixing in the Builder methods on a Model instance, that's on the developer to decide and there could be a valid use-case for doing so; on the other hand it would be nice I suppose to prevent unwanted/accidental queries. In my app I tend to always start off my queries with `Model::query()` instead of using the static mixins

At best this would probably be an optional rule that could be opted into. However, I do want to point out that you can disable the mixin completely by creating a base Model in your application and overriding `__call` to prevent the mixin in the first place.

**Comment by canvural** [comment]
Hi,

I think this is very hard to detect from static analysis point of view. If I understood you correctly this new rule would also warn you if you do something like `(new SomeModel)->first()` While it might be a useless code, it is totally fine and does not have the bug you mentioned. And I think there might be other cases that would produce false positives.

All that being said, I think this is a good opportunity to write a custom rule for your app! You can read the [documentation](https://phpstan.org/developing-extensions/rules) about how to write rules and let me know if you need any help 😊

**Comment by EliW** [comment]
Well I was going to say "before we close this lets chat" ... but that seems a touch late now ;) ... but here's some more chatting anyway @calebdw @canvural:

@calebdw wrote:
> on one hand there's nothing wrong with mixing in the Builder methods on a Model instance, that's on the developer to decide and there could be a valid use-case for doing so

But what 'is' a valid use case?  I can't think of any valid use cases where you would want to call first() (or any of these) on any instantiated model as a valid use case.  It's sort of a weird/odd passthrough ... going from an instantiated model, to suddenly asking it to give you a completely new query against the database.   Instead of 'starting at the top' again.   I definitely understand the 'there could be' part of this, but I honestly can't think of any valid usecase where you wouldn't be better served by needing to be pedantic and starting back from a static query again against the class.   And static analysis is all about being pedantic :) 

@calebdw wrote:
> In my app I tend to always start off my queries with Model::query() instead of using the static mixins

Right, which would be perfectly fine.  In fact I could see an argument that any 'static' mixin would be fine, since it's obvious when you are calling a static method, that you aren't operating against the instantiated/hydrated data in the model itself.

@calebdw wrote:
> At best this would probably be an optional rule that could be opted into.

That could be fine if so.  Optional is better than nothing.

@calebdw wrote:
> However, I do want to point out that you can disable the mixin completely by creating a base Model in your application and overriding __call to prevent the mixin in the first place.

True, I could, but you could also do lots of things in the code to work around things like this.  But IMO that's kinda the point of using static analysis.  To look at the code, and point out potential bugs because of things you did that might be completely 'functional' but have a code smell to them.    This is somewhat like saying:  "Well if you don't like having your undefined variable treated as a null value, you should declare it with a value first".  Yup, you can totally do that, and, PHP is 'ok' with you not doing that.  But we have static analysis to point out "Ummm, you probably didn't mean to do that" :-D 

@canvural wrote:
> I think this is very hard to detect from static analysis point of view.

This I 100% can't speak to since I don't know any of the internals of how phpstan actually works/tokenizes things/etc, so will completely default to your POV there, and if this is not possible to do, so be it.

@canvural wrote:
> If I understood you correctly this new rule would also warn you if you do something like (new SomeModel)->first() While it might be a useless code, it is totally fine and does not have the bug you mentioned.

You are correct it would capture this, because this should just be: `SomeModel::first()` instead.   My argument is that this isn't just useless code (which, again, static analysis picks up on.  A large part of the static analysis is pointing out useless code so you can clean it up) ... but that it's not 'fine' because it does still describe the bug.    

Because you are taking an instantiated object, and calling a function against it to say "give me the first of this resultset" ... when it isn't a resultset.  it's a singular object.   

At worst, while 'useless code', you'd expect it to just return the same model back to you ... ye ole 'You idiot, you only had 1 model object, here it is back again'.    But instead it returns a completely different object to you.

It's that latter part that makes this really dangerous.   Since going from an instantiated object, to then making a call like first() against it, and assuming that you still have the same object, but having a completely different one ... is potentially major issue.  Especially if say, the model you were operating under was 'User' and you just pulled a completely different user's information.

It does feel to me that this is something that static analysis should be able to pick up on, whether an optional rule, or not, so that it points out the code smell of doing `(new SomeModel)->first()` instead of `SomeModel::first()`

@canvural wrote:
> All that being said, I think this is a good opportunity to write a custom rule for your app! You can read the [documentation](https://phpstan.org/developing-extensions/rules) about how to write rules and let me know if you need any help 😊

Thanks, but I'm a bit confused now.  You started out saying that this was 'very hard to do' ... and ended with "why don't you write a custom rule"?   So is it something truly possible, or not?

Side topic:  If I were able to get a rule created that did this, would Larastan be willing to accept a PR to address this, as an optional rule?   If I can get a rule working (if it's not impossible), I'd of course be happy to share it here and would hope it would help others.

**Comment by canvural** [comment]
> Thanks, but I'm a bit confused now. You started out saying that this was 'very hard to do' ... and ended with "why don't you write a custom rule"? So is it something truly possible, or not?

The being hard part refers to not generate any false positives. Sorry I wasn't clear. Disallowing certain method calls on certain type of objects is easy to do with PHPStan. There is also a generic extension that does that: https://github.com/spaze/phpstan-disallowed-calls

> Side topic: If I were able to get a rule created that did this, would Larastan be willing to accept a PR to address this, as an optional rule? If I can get a rule working (if it's not impossible), I'd of course be happy to share it here and would hope it would help others.

I just don't think this is a good fit for Larastan because it'd generate lots of false positives. I suggest you to start with a custom rule.
