### ISSUE TITLE
false error when using alias for selecting Model properties

### ISSUE THREAD

**Issue by ariaieboy** [nunomaduro/larastan#1998]
- Larastan Version: 2.9.8
- Laravel Version: 11.16.0

### Description

After updating my laravel to the latest version phpstan threw new errors at me I fixed lots of them by adding generic types to variables of the Builder class. 

But I couldn't find a solution for this error. 

Here is the code that I use.

### Laravel code where the issue was found

```php
Example::find($id,['id as page_unique', 'title', 'description']);
```
And here is the error:

```

Parameter #2 $columns of method Illuminate\Database\Eloquent\Builder<App\Models\Example>::find() expects array<int, model property of App\Models\Example>|model     
         property of App\Models\Example, array<int, string> given.
         💡 Type #1 from the union: The given string should be a property of App\Models\Example, id as page_unique given.

```

**Comment by calebdw** [comment]
What do your builder and model classes look like?

**Comment by calebdw** [comment]
Also, aliases like that are not going to be supported---you'll need to use a selectRaw

**Comment by ariaieboy** [comment]
@calebdw 
I don't use custom Builder its the default `Illuminate\Database\Eloquent\Builder` and my model is very large and I can't share it here but if I don't use aliases It will work fine

**Comment by ariaieboy** [comment]
> Also, aliases like that are not going to be supported---you'll need to use a selectRaw

Not supported In larastan or laravel? 
Cause I use this code and it works perfectly.

**Comment by calebdw** [comment]
It's not supported in Larastan, I suppose we could handle this case right before here though:

https://github.com/larastan/larastan/blob/9a87f3ca0ad4a70d81bf67d086fdf4165ea70bda/src/Types/ModelProperty/GenericModelPropertyType.php#L71

**Comment by calebdw** [comment]
I PR'd a fix, but note that trying to access the alias property will still fail---you would have to use the Model public api (i.e., `getAttribute('alias')`)
