### ISSUE TITLE
Higher Order Proxy functions

### ISSUE THREAD

**Issue by jkniest** [nunomaduro/larastan#200]
- Larastan Version: 0.3.8
- `default level` used:

### Description:
I am using the higher order proxy methods of collections, for example "map". The error message I get is: ` Access to an undefined property Illuminate\Support\HigherOrderCollectionProxy::$id.`

### Laravel code where the issue was found:
```php
        return collect($room->getLights())->map(function (HueLight $hueLight) {
            return Light::whereExternalId($hueLight->getId())->first();
        })->map->id;
```

**Comment by nunomaduro** [comment]
Thanks for reporting this. We don't support Higher Order Proxy functions, yet.

**Comment by mfn** [comment]
Just to add another example, it's not only about attributes, also methods:
```php
$post->attachments->map->getAttributes()->all();
```
yields
```
    Call to an undefined method
    Illuminate\Support\HigherOrderCollectionProxy::getAttributes().
```

**Comment by szepeviktor** [comment]
Yes, I've seen this error message.

**Comment by canvural** [comment]
This can be solved by the PHPStan generics to some extent. But there would be some edge cases I think.

I would accept a PR that adds a support for this :+1:

**Comment by nmokkenstorm** [comment]
> I would accept a PR that adds a support for this 👍

I created a plugin that fixes this, and extracted it to a package over [here](https://github.com/Sustainabil-IT/phpstan-higher-order-collections) today. Do I clean up the package and add it as a dependency, or is porting the code directly to this repository preferable?

**Comment by canvural** [comment]
@nmokkenstorm I'd prefer the functionality inside the Larastan. With proper implementation and tests. Feel free to make a PR :+1:

**Comment by szepeviktor** [comment]
I would gladly see @nmokkenstorm's extension in Larastan ❤️
