### ISSUE TITLE
Model::factory->times not recognized as collection returned

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/larastan#2001]
- Larastan Version: 2.9.8
- Laravel Version: 11.16.0

### Description

When calling `times` on a factory, it does not recognize that it will now return a collection instead of the model. 

Calling `times` seems to always convert it to a collection, even when doing `times(1)` and `times(0)`.

We even have information on how long the array is, so we should know if `$users[4]` is a valid call or not.

### Laravel code where the issue was found

```php
    $users = User::factory()
        ->times(2)
        ->create();
```

**Comment by calebdw** [comment]
This is a known limitation, we are unable to determine what the return type should be based on earlier calls---use `createMany` instead

**Comment by olivernybroe** [comment]
Hmm, we can't solve it with Generics? Making `times` return `Factory<Collection<User>>` or something like that. 

And thank you for mentioning the workaround 👍

**Comment by canvural** [comment]
We already support `count` method on factories. It can follow any kind of chaining. So I just added support for `times` too here: c83c0c7

Thank you for the issue.
