### ISSUE TITLE
Carbon being treated as string, resulting in phpstan reporting unable to call function on string

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/larastan#2005]
- Larastan Version: 2.9.8
- Laravel Version: 11.17.0

### Description

Using PHPStorm Laravel Idea and Larastan

Have a custom cast of a property on a model cast to 'date', attempting to use a method on that date results in Cannot call method on string error. -- We can see that Laravel Idea generated and reports the correct type, but Larastan hasn't 

if I manually add the Laravel Idea helper to the includes, it works correctly - but this can't be automated because phpstan doesn't support adding all files in a directory as stubs and Laravel Idea generates its stubs with random hashes. furthermore I don't believe this should be required as Larastan is meant to generate the types from casts(), or at least that is my understanding? 

phpstan.neon
```
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/nesbot/carbon/extension.neon
```
![image](https://github.com/user-attachments/assets/a9ee420f-85c9-4c4e-890c-8b1b4751dd9e)

![image](https://github.com/user-attachments/assets/b3cf3410-99da-41ee-b306-162d60e9f9dc)
![image](https://github.com/user-attachments/assets/662f5077-0200-41f5-af1b-6009c14d34b8)

**Comment by calebdw** [comment]
As mentioned in the other PHPStan thread, there is no bug. The `casts()` method must be annotated with the generics as specified in [the upgrade guide](https://github.com/larastan/larastan/blob/2.x/UPGRADE.md#upgrading-to-296-from-295).

Larastan is not designed to be used with Laravel Idea/IDE Helper stubs. You are welcome to try, but your mileage may vary and any issues that arise from using it will not be supported.

For what's it's worth, I understand the unwillingness to repeat the casts array in the phpdoc. I had a [working PR](https://github.com/larastan/larastan/pull/1878) that would not require this but unfortunately it was rejected for reasons you can read about there. So as it stands, your two options are:
1. Use the `$casts` property
2. Add the array shape to the `casts()` method

**Comment by SlyDave** [comment]
Thanks @calebdw that PR was **EYE OPENING**, and good work! - holyshit the toxicity towards you and others from Can Vural, and the number of contradictions in the reasoning and responses. -- sigh, think I reevaluate my team's usage of larastan

Guess it's array-shapes for now then, curse more Laravel anti-static-analysis magic.

**Comment by calebdw** [comment]
To be fair, a lot of the magic in the framework isn't really static analysis friendly. Larastan tries to help the developer by using the container and executing runtime code, but this opens a whole other can of worms as Can mentioned.

**Comment by canvural** [comment]
>  holyshit the toxicity towards you and others from Can Vural, and the number of contradictions in the reasoning and responses. -- sigh, think I reevaluate my team's usage of larastan

What toxicity are you mentioning? Can you elaborate? I do not see any contradictions in my reasoning also 🤔

**Comment by SlyDave** [comment]
> > holyshit the toxicity towards you and others from Can Vural, and the number of contradictions in the reasoning and responses. -- sigh, think I reevaluate my team's usage of larastan
> 
> What toxicity are you mentioning? Can you elaborate? I do not see any contradictions in my reasoning also 🤔

Replying because you asked:

I quote from you from the PR: " Now work on your reading skills" and "Sounds like a you problem." and "Why do you act like I owe you something? This is an open source project. Deal with it." and "Oh, please yes! I hope you'll stop using it forever honestly."

Basically, your entire response is antagonistic, maybe a language barrier thing, maybe a text is terrible at providing sentiment; in either case it reads badly. I've no skin in the game anymore, so I don't particular care either way, but it's a shame to see people being deterred from contributing because of the community.

**Comment by canvural** [comment]
> > > holyshit the toxicity towards you and others from Can Vural, and the number of contradictions in the reasoning and responses. -- sigh, think I reevaluate my team's usage of larastan
> > 
> > 
> > What toxicity are you mentioning? Can you elaborate? I do not see any contradictions in my reasoning also 🤔
> 
> Replying because you asked:
> 
> I quote from you from the PR: " Now work on your reading skills" and "Sounds like a you problem." and "Why do you act like I owe you something? This is an open source project. Deal with it." and "Oh, please yes! I hope you'll stop using it forever honestly."
> 
> Basically, your entire response is antagonistic, maybe a language barrier thing, maybe a text is terrible at providing sentiment; in either case it reads badly. I've no skin in the game anymore, so I don't particular care either way, but it's a shame to see people being deterred from contributing because of the community.

If you don't see the problem in the comment that I was replying to, then I have nothing to say :shrug:

**Comment by SlyDave** [comment]
This was never about the comments you replied to, but how you replied.

Thank you for proving my point so succinctly.
