### ISSUE TITLE
`Tap` closure not taking into account when deciding return type.

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/larastan#2010]
- Larastan Version: 2.9.8
- Laravel Version: 11.16.0

### Description
When using `tap` method, I could narrow down the return type inside the closure, which phpstan would understand if I did it before the `tap` method. 

E.g. calling `Instanceof` etc. 
Not sure if there is any way to tell phpstan this, but thought I would report it anyways 👍 

### Laravel code where the issue was found

```php
return tap($object, function ($object) {
            if (! $object instanceof MyClass) {
                throw new InvalidArgumentException();
            }
        });
```

**Comment by calebdw** [comment]
This is a PHPstan issue, nothing we can do here

PHPstan can handle type assertion, but not sure how well they would work with a closure:
https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods

**Comment by calebdw** [comment]
Just to be clear here, the `tap` method returns the first argument as-is:

https://github.com/laravel/framework/blob/516bf8d73d678eefce7a7ca3efea6904b83e0036/src/Illuminate/Support/helpers.php#L374-L383

Therefore the closure cannot be assumed to narrow the type in any way---this just needs to be rewritten to be more amenable to static analysis

**Comment by olivernybroe** [comment]
@calebdw it can. Take the example I just shared. I am throwing an exception if it's not a specific type. 

Obviously there is an easy way to fix it which is just to not use `tap`. 
Just wanted to report it anyways.

**Comment by canvural** [comment]
Hi,

This really doesn't seem to be related to Larastan itself. It could be solved in PHPStan directly I believe.
