### ISSUE TITLE
Casts defined in Trait are ignored

### ISSUE THREAD

**Issue by makroxyz** [nunomaduro/larastan#2011]
- Larastan Version: 2.9.8
- Laravel Version: 11.19

### Description
Casts defined in Trait are ignored

### Laravel code where the issue was found

```php
trait MyTrait {

    public function initializeServiceTrait()
    {
        $this->mergeCasts([
             'price' => 'double',
             'quantity' => 'integer',
        ])
    }
}

```

**Comment by szepeviktor** [comment]
Hello @makroxyz 👋🏻 

Is your trait in use?
PHPStan does not analyze traits.

**Comment by makroxyz** [comment]
Yes it is, used in a couple of models

**Comment by szepeviktor** [comment]
I think Larastan does not support `mergeCasts`.
https://github.com/search?q=repo%3Alarastan%2Flarastan%20mergeCasts&type=code

**Comment by calebdw** [comment]
Yes, this is not supported. While we do use the `getCasts` method from the model (but not for the new L11 casts), we new up the model bypassing the constructor---which means traits are not booted/initialized:

https://github.com/larastan/larastan/blob/c8ec6f04f800d9425be743998574f1034e2ffb3f/src/Properties/ModelCastHelper.php#L240-L249

**Comment by canvural** [comment]
Hi,

I'm not sure if this can be ever solved without doing more voodoo black magic type of things. So I'm gonna close it for now.
