### ISSUE TITLE
Shouldn't excludePaths: *.blade.php

### ISSUE THREAD

**Issue by johntheteam** [nunomaduro/larastan#2018]
- Larastan Version: Any
- Laravel Version: Any

### Description

Larastan's extension file has below:

https://github.com/larastan/larastan/blob/c8ec6f04f800d9425be743998574f1034e2ffb3f/extension.neon#L8-L9

Since Neon config can't override the parameter, this make it impossible to analyse blade file any more even with bladestan installed.

**Comment by szepeviktor** [comment]
> this make it impossible to analyse blade file

Yes, you are right. This is a known problem.
I uninstall Larastan because of this.

**Comment by AJenbo** [comment]
Bladestan maintainer here. Bladestan does not run on the .blade.php files directly, it works by compiling the template when ever the analyzer encounters a view function. So this has no baring on Bladestan at all.

**Comment by szepeviktor** [comment]
I've never managed to get view errors when both Bladestan and Larastan were installed.

**Comment by AJenbo** [comment]
Ok, if you can try again and provide an example in an issue over at https://github.com/TomasVotruba/bladestan/issues then I'm happy to look in to it, just make sure that you analyze the call point (a controller for example) and not the *.blade.php files.

**Comment by szepeviktor** [comment]
@AJenbo That could be https://github.com/TomasVotruba/bladestan/issues/2

I would like to analyze blade files too!
How to analyze blade files without a call point?

**Comment by AJenbo** [comment]
@szepeviktor 

>  How to analyze blade files without a call point?

You can't effectively analyze Blade files without knowing the call point, as it provides the necessary context for understanding the scope. Without this, you risk generating numerous false positives. This isn't what providing `templatePaths` does.

Bladestan focuses on analyzing compiled templates to ensure they're being used correctly and to identify any errors in the generated code. Without the call context, all you'd be able to verify is whether the Blade syntax itself is valid. However, this falls outside Bladestan's scope. For syntax checking, you might want to consider using a tool like https://github.com/Magentron/laravel-blade-lint instead

**Comment by szepeviktor** [comment]
> Without the call context, all you'd be able to verify is whether the Blade syntax itself is valid.

@AJenbo Thank you.

**Comment by AJenbo** [comment]
@canvural  This was fixed in 3.x and can be closed
