### ISSUE TITLE
Builder doesn't have correct generic when initialized through class-string

### ISSUE THREAD

**Issue by vixducis** [nunomaduro/larastan#2021]
- Larastan Version: 2.9.2
- Laravel Version: 11.1.1

### Description

When you initialize a `Builder` through the `::query()` method on a `class-string`, the generic on the `Builder` isn't correctly deduced from the generic of the `class-string`, and defaults to `Model`. This can be easily tested by trying to access a local scope on the query, as demonstrated by the code below. This results in a PHPStan error: `Call to an undefined method Illuminate\Database\Eloquent\Builder::test().`.

It's debatable whether this is a bug or rather a feature request.

### Laravel code where the issue was found

```php
<?php

namespace App\Models\Example;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Example extends Model
{
    public function scopeTest(Builder $query): void {}
}

/** @var class-string<Example> $className */
$className = Example::class;
$className::query()
    ->test()
    ->get();
```

**Comment by calebdw** [comment]
:+1: I'll try to get to this in the next week or two

A similar issue I've noticed is calling `static::query()` does not handle the static instance:

```php
class AbstractModel extends Model
{
    public static function new(): static
    {
        return static::query()->create(); // fails, returns AbstractModel instead of static(AbstractModel)
    }
}

class User extends AbstractModel {}

\PHPStan\Testing\assertType('User', User::new());
```

**Comment by JeRabix** [comment]
I try help for first part of this issue, but currently can't understand how fix this:

> ```
>  return static::query()->create(); // fails, returns AbstractModel instead of static(AbstractModel)
> ```


`ModelDynamicStaticMethodReturnTypeExtension`- skip all native class methods except only this: 

```php
if (in_array($name, ['get', 'hydrate', 'fromQuery'], true)) {
   return true;
}
```

when add method `new` to this except rule - it work correctly.
