### ISSUE TITLE
Facades that use a manager pattern internal, are not supported

### ISSUE THREAD

**Issue by georgeboot** [nunomaduro/larastan#203]
- Larastan Version: 0.3.8
- `--level` used: 1

### Description:
`Call to an undefined static method Vinkla\Hashids\Facades\Hashids::encode()`

The package [laravel-hashids](https://github.com/vinkla/laravel-hashids) uses a the manager pattern for their library. This means that not only the facade is a "magic method", once the facade resolves to the instance, the method in that instance is also called magically.

At the moment, Larastan does not support this behaviour.

The packages has added the avaialble methods as doc blocks to their manager class (the class where the facade resolved to), like so:

```php
/**
 * This is the Hashids manager class.
 *
 * @method string encode(mixed ...$numbers) Encode parameters to generate a hash.
 * @method array decode(string $hash) Decode a hash to the original parameter values.
 * @method string encodeHex(string $str) Encode hexadecimal values and generate a hash string.
 * @method string decodeHex(string $hash) Decode a hexadecimal hash.
 *
 * @author Vincent Klaiber <hello@vinkla.com>
 */
class HashidsManager extends AbstractManager
{
    // code
}
```

It would be great if Larastan could also read from these doc blocks.

### Laravel code where the issue was found:
```php
use Vinkla\Hashids\Facades\Hashids;

// this line
$hash = Hashids::encode($sale->id);
```

**Comment by nunomaduro** [comment]
Hey @ondrejmirtes, does PHPStan supports `method` annotations?

**Comment by georgeboot** [comment]
It looks like it does: https://phpstan.org/r/0cddca2a-d104-4251-8614-785f9ebc2f2a

**Comment by ondrejmirtes** [comment]
Yeah, of course :)

**Comment by Krato** [comment]
Same error 👍

**Comment by nunomaduro** [comment]
This issue is fixed.
