### ISSUE TITLE
Method overloading causes undefined method error

### ISSUE THREAD

**Issue by ahoiroman** [nunomaduro/larastan#2034]
- Larastan Version: 2.9.8
- Laravel Version: 11.22

### Description
I am using spatie/media-library. Larastan tells me that `nonQueued()` cannot be found in `ImageDriver::class`.

> phpstan: Call to an undefined method Spatie\Image\Drivers\ImageDriver::nonQueued().

### Laravel code where the issue was found

This is the `User` model I prepared to use media:

```php
final class User extends Authenticatable implements MustVerifyEmail, HasMedia
{
    use HasFactory, HasUlids, InteractsWithMedia, Notifiable;
    
    public function registerMediaConversions(Media|null $media = null): void
    {
        $this
            ->addMediaConversion('preview')
            ->fit(Fit::Contain, 300, 300)
            ->nonQueued();
    }
    
}
```

The image driver comes from spatie/image: https://github.com/spatie/image/blob/main/src/Drivers/ImageDriver.php, but the nonQueued() method comes from the `InteractsWithMedia` trait (https://github.com/spatie/laravel-medialibrary/blob/main/src/InteractsWithMedia.php#L496-L503).

The Conversion class itself does contain the method `nonQueued()` (https://github.com/spatie/laravel-medialibrary/blob/main/src/Conversions/Conversion.php#L175-L180).

**Comment by szepeviktor** [comment]
`fit` could go through `__call` - the vendor of the above mentioned package is not the best friend of static analysis.

What is the error message when you remove `fit`?

**Comment by calebdw** [comment]
This isn't going to work without a custom dynamic return type extension / class reflection extension---which Larastan should not support. The package can add one real easily for their own magic.

The `Conversion` class has a "decorated" mixin pattern to `ImageDriver` (it forwards calls, but returns itself and not the return type of the forwarded call). The `@mixin` tag always returns the return type of the forwarded call so PHPStan thinks that an `ImageDriver` is returned and the `nonQueued` method does not exist on the interface.

This is a common enough pattern that it may be worth seeing if PHPStan can introduce a `@mixin-decorated` tag or something for it.


Note that you should be able to reverse the order of operations and everything will pass:

```php
    public function registerMediaConversions(Media|null $media = null): void
    {
        $this
            ->addMediaConversion('preview')
            ->nonQueued()
            ->fit(Fit::Contain, 300, 300);
    }
```

**Comment by calebdw** [comment]
I've opened an issue with PHPStan, but there's nothing for us to do here so this issue can be closed

**Comment by canvural** [comment]
Hi,

Looks like this is an issue specific to the `spatie/media-library` library. It'd need to have it's own PHPStan extension. Or a community maintained one.
