### ISSUE TITLE
Calling map on an eloquent paginator, results in a false positive

### ISSUE THREAD

**Issue by georgeboot** [nunomaduro/larastan#205]
- Larastan Version: 0.3.8
- `--level` used: 2

### Description:
As per @nunomaduro 's request in #107 

Larastan generates a validator error when the `map()` method is called on an eloquent paginator.

`Call to an undefined method Illuminate\Contracts\Pagination\LengthAwarePaginator::map().`

### Laravel code where the issue was found:
```php
$result = SaleTicket::paginate(10)->map(function ($saleTcket) {
    return $saleTcket;
});
```

**Comment by nunomaduro** [comment]
@georgeboot Can you test this using the latest version of Larastan? This should be fixed.

**Comment by georgeboot** [comment]
Hi @nunomaduro thanks for the hard work!

Just tested with version `v0.3.12` and I can confirm the issue is indeed fixed.
