### ISSUE TITLE
`when` statement not taken into account inside closure

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/larastan#2055]
- Larastan Version: 2.9.8
- Laravel Version: 11.26.0

### Description
When a `when` statement is used to do for example a simple null check, if that variable is used inside the closure, then phpstan does not know that it cannot be null.

### Laravel code where the issue was found

```php
  $count = $resource->teams()
      ->when($team !== null, fn ($query) => $query->whereKey($team->getKey()))
      ->delete();

```

I know that this example here can be solved by just passing `$team` directly into `whereKey` or by calling making it an optional call. This was more to raise the general issue of the statement not being checked as if it was an `if` statement.

**Comment by calebdw** [comment]
Right now you're accessing the `$teams` variable from the global scope on the same line as the `$team !== null`---phpstan has no way of knowing that it's been narrowed.

Below is the proper solution, use the value that is passed to the closure for this exact purpose:
```php
  $count = $resource->teams()
      ->when($team, fn ($query, $t) => $query->whereKey($t->getKey()))
      ->delete();
```

I see no reason to try and create a complicated extension to allow this particular case when there's a provided solution.
