### ISSUE TITLE
Larastan reports private Attribute as unused

### ISSUE THREAD

**Issue by EriBloo** [nunomaduro/larastan#2056]
- Larastan Version: 2.9.8
- Laravel Version: 10.48.22

### Description
Hi.
As stated in title, when I have private Attributes in Models PHPStan reports them as unused even with annotation added. Is there any way to inform PHPStan what is going on? Since my models are final I don't think setting Attributes as protected is a good solution.

### Laravel code where the issue was found

```php
/**
* @property-read string $full_name
*/
final class User
{
    /** @return Attribute<string, never> */
    private function fullName(): Attribute
    {
        return Attribute::get(fn () => "{$this->first_name} {$this->last_name}");
    }
}
```

**Comment by calebdw** [comment]
They should be `protected`, it doesn't matter anyway since the class is `final`. Or just ignore the error, there's really nothing we can do on the Larastan side here

**Comment by EriBloo** [comment]
Thanks for a quick response. That's what I'm going to do then. Greetings!
