### ISSUE TITLE
new eloquent collection from typed array has unknown type

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#2062]
- Larastan Version: v2.9.8
- Laravel Version: v10.48.8

```php
$instances = ...;
\PHPStan\dumpType($instances); // array<int, App\Models\ProfessionInstance> 🟩 

$instancesCollection = new EloquentCollection($instances);
\PHPStan\dumpType($instances); // EloquentCollection<(int|string), EloquentModel> 🟥 
```

The new collection loses all information of its items. Should I create the collection differently? Or could Larastan detect a Laravel collection's input and assign its types to the collection object (or whatever however you say that! 😆)? Is there even a Phpstan extension to assign the type of a `new` object?

**Comment by calebdw** [comment]
Try using `EloquentCollection::make($instances)`

**Comment by rudiedirkx** [comment]
So there's no way to specify the types in a generic `new` object with Phpstan?

**Comment by calebdw** [comment]
Not that I know of

**Comment by rudiedirkx** [comment]
Thanks.

**Comment by calebdw** [comment]
Feel free to raise an issue at PHPStan to see if this is possible

**Comment by rudiedirkx** [comment]
Eeeh my example is very simplified, but I did not expect this: https://phpstan.org/r/ae990226-f169-4313-872a-ed0b1e092763 Is that because of how Collection is defined? Then Larastan could do that for Laravel collections? I'm just guessing here.

**Comment by calebdw** [comment]
Ah, probably happens because of the template rename, might just need to add the constructor to the stubs (or better yet, PR a fix to the framework)

https://phpstan.org/r/bb88114a-b3c1-4387-97f9-cb85e3071b5e
