### ISSUE TITLE
CheckUnusedViews don't check method view in MailMessage class

### ISSUE THREAD

**Issue by koraga** [nunomaduro/larastan#2063]
- Larastan Version: 2.9.8
- Laravel Version: 11.26.0

### Description
I am using views in my notifications with the MailMessage class, but phpstan doesn't recognize that these views are being used there and throws an error with the rule checkUnusedViews: true.

### Laravel code where the issue was found

```php

class TournamentConfirmationRegistration extends Notification
{
    /**
     * @return non-empty-list<string>
     */
    public function via(): array
    {
        return [MailChannel::class];
    }

    public function toMail(): MailMessage
    {
        return (new MailMessage())->view('mails.tournament-confirmation-registration');
    }
}

```

error: 
```
 ------ ---------------------------------------------------------------------- 
  Line   resources/views/mails/tournament-confirmation-registration.blade.php  
 ------ ---------------------------------------------------------------------- 
  0      This view is not used in the project.                                 
 ------ ---------------------------------------------------------------------- 
```

**Comment by szepeviktor** [comment]
What happens if you comment out https://github.com/larastan/larastan/blob/b0bfa092aa3fac7a5df36ce4fb8cd90866ac8f0e/extension.neon#L9 ?

**Comment by calebdw** [comment]
I'm not sure that we are collecting views from `MailMessage` calls (only `Mailable` calls):

https://github.com/larastan/larastan/blob/b0bfa092aa3fac7a5df36ce4fb8cd90866ac8f0e/src/Rules/UnusedViewsRule.php#L50-L57

**Comment by koraga** [comment]
> What happens if you comment out
> 
> https://github.com/larastan/larastan/blob/b0bfa092aa3fac7a5df36ce4fb8cd90866ac8f0e/extension.neon#L9
> 
> ?

Same error

**Comment by koraga** [comment]
> I'm not sure that we are collecting views from `MailMessage` calls (only `Mailable` calls):
> 
> https://github.com/larastan/larastan/blob/b0bfa092aa3fac7a5df36ce4fb8cd90866ac8f0e/src/Rules/UnusedViewsRule.php#L50-L57

I found this too

**Comment by koraga** [comment]
I can contribute and add a new Collector for MailMessage

**Comment by calebdw** [comment]
All that should be needed is to also check that `MailMessage` is a super type

https://github.com/larastan/larastan/blob/b0bfa092aa3fac7a5df36ce4fb8cd90866ac8f0e/src/Collectors/UsedEmailViewCollector.php#L45-L47

```php
$type = $scope->getType($class);
 if (
    ! (new ObjectType(Mailable::class))->isSuperTypeOf($type)->yes()
    && ! (new ObjectType(MailMessage::class))->isSuperTypeOf($type)->yes()
) { 
     return null; 
 }
