### ISSUE TITLE
Cannot find properties trough foreach

### ISSUE THREAD

**Issue by adminfriso** [nunomaduro/larastan#207]
- Larastan Version: 0.3.8
- `--level` used: 2

### Description:
When using a foreach on a collection the model iterated over as the class it runs in instead of the models contained in the collection

### Laravel code where the issue was found:

```php
        $unAnalyzedDatas = Data::whereAnalyzed(false)->get();
        $geoFences = GeoFence::all();

        $calculator = new Vincenty();

        foreach ($geoFences as $geoFence) {
            $fenceCoord = new Coordinate($geoFence->lat, $geoFence->lng);
            foreach ($unAnalyzedDatas as $data) {
                $coord = new Coordinate($data->lat, $data->lng);
```

#### Error
Access to an undefined property App\Jobs\AnalyzeGeofences::$lat.       
Access to an undefined property App\Jobs\AnalyzeGeofences::$lng.  

#### should be
the property is part of App\Models\Data, as $data is an instance of that model. It however inspects the class it has run in.

Could be I am being stupid or something but I do not think this is the wanted behaviour

**Comment by mfn** [comment]
Even PHPStorm doesn't know it. I usually *always* typehint these with `/** @var DatModel[]|Eloquent\Collection */`.

**Comment by nunomaduro** [comment]
@georgeboot This issue has been fixed in Larastan `v0.3.10`. 

Please run a `composer update nunomaduro/larastan` and tell me the results.

**Comment by adminfriso** [comment]
Yes with v0.3.10 this works, amazing!

**Comment by szepeviktor** [comment]
@nunomaduro Could you tell me how and where it was fixes? Is it in PHPStan or Larastan?

**Comment by nunomaduro** [comment]
@szepeviktor This was the fix: https://github.com/nunomaduro/larastan/commit/382fc759cc8a1f42dfbd288d670906e76783ea29.

The `ThisType`, for someone reason pointed to the instance where the code runs, and now every `ThisType` is now converted to Model::class =>`StaticType`.

**Comment by nunomaduro** [comment]
Thanks for asking, but honestly Larastan is about dark magic. 👍

**Comment by szepeviktor** [comment]
Thank you.

I thought the loop variable in foreach belongs to PHPStan.
