### ISSUE TITLE
New eloquent collection loses item type information on creation

### ISSUE THREAD

**Issue by rudiedirkx** [nunomaduro/larastan#2073]
- Larastan Version: v2.9.9
- Laravel Version: v11.23.5

### Description

Probably due to a generic model (`SiteCheck<Checked>`), creating an eloquent collection (`ModelCollection`) loses the information about the item type. If passed in as **array**, it breaks by double wrapping the collection, and if passed in from a (non-eloquent) **collection** it breaks by losing type information. See type dumps:

### Laravel code where the issue was found

```php
// Not models:
\PHPStan\dumpType($checkables); // 🟩 array<int, App\Service\SiteChecker\Checkable>
// Create SiteCheck models from those non-models:
$siteChecks = collect($checkables)->map(function(Checkable $checkable) {
	return (new SiteCheck())->forceFill([
		'id' => $checkable->last_scid,
		'site_id' => $checkable->site_id,
		'check_id' => $checkable->check_id,
	]);
});

\PHPStan\dumpType($siteChecks); // 🟩 Illuminate\Support\Collection<int, App\Models\SiteCheck<App\Service\SiteChecker\Checked>>

// Now I want to eager-load a relationship in those models, so I need a ModelCollection instead of a Collection:

// Directly from the Collection loses information:
\PHPStan\dumpType(ModelCollection::make($siteChecks)); // 🟥 ModelCollection<(int|string), mixed>

// First to array keeps HALF the type information, but makes a double ModelCollection!?:
\PHPStan\dumpType($siteChecks->all()); // 🟩 array<int, App\Models\SiteCheck<App\Service\SiteChecker\Checked>>
\PHPStan\dumpType(ModelCollection::make($siteChecks->all())); // 🟥  ModelCollection<int, ModelCollection<App\Service\SiteChecker\Checked>>
```

`$checkables` is an array of **non-models**, so I can't start with a `ModelCollection`, or Larastan will complain. I'm okay with that. First a `collect()`, then map to models, then make a `ModelCollection`, and load a relationship.

<s>Creating the ModelCollection from the array from the Collection works, but creating it directly from the Collection does not. Very simple workaround, acceptable for now, but still a bug I think.</s> Nope, doesn't work either, see type dumps.

<s>Once again, **I THINK** it's due to the genericness of `SiteCheck`. The second dump shows that genericness correctly: `App\Models\SiteCheck<App\Service\SiteChecker\Checked>`.</s> Nope, information is lost with non-generic models too, see `Contact` example below.

**Comment by rudiedirkx** [comment]
No, even then it's broken! I missed the double `ModelCollection`. Bad bad `Collection::make()`!

**Comment by calebdw** [comment]
When converting a collection, try to use `wrap` instead of `make`:

```php
\PHPStan\dumpType(ModelCollection::wrap($siteChecks));
```

**Comment by rudiedirkx** [comment]
> When converting a collection, try to use `wrap` instead of `make`:

Still a double `ModelCollection`, in both methods (directly from `Collection` and through `->all()` array).

**Comment by rudiedirkx** [comment]
My `ModelCollection` works everywhere else, but just in case:

```php
use Illuminate\Database\Eloquent\Collection as EloquentCollection;

/**
 * @template TKey of array-key
 * @template TModel of Model
 *
 * @extends EloquentCollection<TKey, TModel>
 */
class ModelCollection extends EloquentCollection {
```

`Model` is in the same namespace, not the base eloquent Model, but it extends it.

**Comment by calebdw** [comment]
Does it work with the base EloquentCollection?

**Comment by rudiedirkx** [comment]
It's not due to the genericness, mostly:

```php
$contacts = Contact::all()->all();
\PHPStan\dumpType($contacts); // 🟩 array<int, App\Models\Contact>

$contacts = collect($contacts)->map(function(Contact $contact) {
	return (new Contact())->forceFill([
		'id' => $contact->id,
		'organization_id' => $contact->organization_id,
	]);
});
\PHPStan\dumpType($contacts); // 🟩 Illuminate\Support\Collection<int, Contact>

\PHPStan\dumpType(ModelCollection::make($contacts)); // 🟥 ModelCollection<(int|string), mixed>
\PHPStan\dumpType($contacts->all()); // 🟩 array<int, Contact>
\PHPStan\dumpType(ModelCollection::make($contacts->all())); // 🟩 ModelCollection<int, Contact> -- SURPRISINGLY WORKS!
```

That last dump surprised me. With ungeneric `Contact` it works, but with generic `SiteCheck` it doesn't. Maybe something to do with the genericness after all. Seems like 2 bugs.

**Comment by rudiedirkx** [comment]
`wrap()` and `make()` have the same exact results in the `Contact` example.

**Comment by calebdw** [comment]
What does \PHPStan\dumpType(ModelCollection::wrap($contacts));` do?

**Comment by rudiedirkx** [comment]
> Does it work with the base EloquentCollection?

No, same bug:

```php
\PHPStan\dumpType($siteChecks); // 🟩 Illuminate\Support\Collection<int, App\Models\SiteCheck<App\Service\SiteChecker\Checked>>

// Wrong because mixed:
\PHPStan\dumpType(EloquentCollection::make($siteChecks)); // 🟥 Illuminate\Database\Eloquent\Collection<(int|string), mixed>

// Wrong because double wrapped collection:
\PHPStan\dumpType(EloquentCollection::make($siteChecks->all())); // 🟥 Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Collection<App\Service\SiteChecker\Checked>>
```

The double collection from the array is so weird. Why would it double wrap an array? But at least it kept the collection item type information....

**Comment by rudiedirkx** [comment]
> But at least it kept the collection item type information....

That's not even true! I missed it again. It kept the template type `Checked`, but it lost the model type `SiteCheck`. That's even weirder!

**Comment by rudiedirkx** [comment]
Btw, is there a fluent way to convert/cast a collection into another collection class? Like

```php
collect($items)
  ->map(...)
  ->convertTo(ModelCollection::class)
  ->load('relation_name');
```

----

That's a Laravel question, not a Larastan question, sorry.

**Comment by calebdw** [comment]
Yes, you can look into `pipe` / `pipeInto`

**Comment by rudiedirkx** [comment]
`pipeInto` has the same item type loss problem as expected:

```php
\PHPStan\dumpType($siteChecks); // 🟩 array<int, Checkable> - non-models

$siteChecks = collect($checkables)
	->map(function(Checkable $checkable) {
		return (new SiteCheck())->forceFill([
			'id' => $checkable->last_scid,
			'site_id' => $checkable->site_id,
			'check_id' => $checkable->check_id,
		]);
	})
	->pipeInto(ModelCollection::class)
	->keyBy('site_id')
	->load('metrics');
\PHPStan\dumpType($siteChecks); // 🟥 ModelCollection<(int|string), App\Base\Model>
```

`App\Base\Model` instead of `SiteCheck`.

It seems that `pipeInto` loses even more information:

```php
$contacts = Contact::all()->all();
\PHPStan\dumpType($contacts); // 🟩 array<int, App\Models\Contact>
$contacts = collect($contacts)
	->map(function(Contact $contact) {
		return (new Contact())->forceFill([
			'id' => $contact->id,
			'organization_id' => $contact->organization_id,
		]);
	})
	->pipeInto(ModelCollection::class);
\PHPStan\dumpType($contacts); // 🟥 App\Base\ModelCollection - not even a generic??
```

so that's never a good option.

**Comment by canvural** [comment]
Fixed with 9e7233d88f4f10796fadb8a2d85c5f2b55277c76

Thank you!

**Comment by rudiedirkx** [comment]
Aah it was the `EnumerableGenericStaticMethodDynamicStaticMethodReturnTypeExtension` 😆 That has to be the longest class short name I've ever seen!

Does `pipeInto()` also work now? That would be very cool.

**Comment by canvural** [comment]
hmm. For `pipeInto` we might need a new extension. Or maybe it's solvable some other way. Can you open a feature request for that please? With minimal complete code example. Thank you.

**Comment by rudiedirkx** [comment]
But `Collection::make()` works? With `$collection` and with `$collection->all()`?

**Comment by canvural** [comment]
Yes it does.
