### ISSUE TITLE
Regression of Eloquent Query Builder where method

### ISSUE THREAD

**Issue by aldobarr** [nunomaduro/larastan#2074]
- Larastan Version: 2.9.9
- Laravel Version: 11.28.1

### Description
I'm getting the following error with my static analysis today:
```
  :51    Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<*>::where() expects array<int|model property of never, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<*>):  
         mixed)|Illuminate\Contracts\Database\Query\Expression|model property of never, 'record_status' given.   
```

Indicating that I'm sending an incorrect value to the where method. However I'm sending a simple string for the column name. See code below.

### Laravel code where the issue was found

```php
        $query = $this->getBasePinsQuery()
            ->where(static function (Builder $query) {
                $query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)
                    ->orWhereNull('record_status');
            })
            ->whereNull('deleted_at')
            ->whereRaw("to_tsvector('simple', public.f_concat_ws(' ', address, city, state, zip))
                @@ plainto_tsquery('simple', ?)", $search);

        return $query->limit(20)->get();
```
The error refers to line 51, which is `$query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)`

However, if I replace the where that passes in the closure with a simple where as such:

```php
        $query = $this->getBasePinsQuery()
            ->where('record_status', '')
            ->whereNull('deleted_at')
            ->whereRaw("to_tsvector('simple', public.f_concat_ws(' ', address, city, state, zip))
                @@ plainto_tsquery('simple', ?)", $search);

        return $query->limit(20)->get();
```

I get the same error:

```
  :50    Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<*>::where() expects array<int|model property of never, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<*>):  
         mixed)|Illuminate\Contracts\Database\Query\Expression|model property of never, 'record_status' given. 
```

Line 50, which would be `->where('record_status', '')`

I downgraded larastan to 2.9.8 and it started working again, so the regression must be with this morning's release of 2.9.9

**Comment by aldobarr** [comment]
The `$this->getBasePinsQuery()` method just returns a model's query builder:
```php
    public function getBasePinsQuery(): Builder
    {
        return Pin::select([
            'columns',
        ])->with(['relations']);
    }
```

**Comment by calebdw** [comment]
You don't have the proper generics:

```php
    /** @return Builder<Pin> */
    public function getBasePinsQuery(): Builder
    {
        return Pin::select([
            'columns',
        ])->with(['relations']);
    }
```

**Comment by calebdw** [comment]
Also, I've add issues with Closure types overriding the generics so you might need to use:



```php
            ->where(static function ($query) {
                $query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)
                    ->orWhereNull('record_status');
            })
```

**Comment by aldobarr** [comment]
@calebdw If I do that, with this code:

```php
    public function getByAddress(string $search): Collection
    {
        $query = $this->getBasePinsQuery()
            ->where(static function ($query) {
                $query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)
                    ->orWhereNull('record_status');
            })
            ->whereNull('deleted_at')
            ->whereRaw("to_tsvector('simple', public.f_concat_ws(' ', address, city, state, zip))
                @@ plainto_tsquery('simple', ?)", $search);

        return $query->limit(20)->get();
    }

    /**
     * @return Builder<Pin>
     */
    public function getBasePinsQuery(): Builder
    {
        return Pin::select([
            'columns',
        ])->with(['relations']);
    }
```

I get the following errors:

```
  :51    Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<*>::where() expects array<int|model property of never, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<*>):  
         mixed)|Illuminate\Contracts\Database\Query\Expression|model property of never, 'record_status' given.                                                                                 
  :64    PHPDoc tag @return contains generic type Illuminate\Contracts\Database\Eloquent\Builder<App\Models\Pin> but interface Illuminate\Contracts\Database\Eloquent\Builder is not generic. 
```

**Comment by calebdw** [comment]
> Illuminate\Contracts\Database\Eloquent\Builder

There's your problem, don't use the contract

**Comment by aldobarr** [comment]
Gotcha, it's weird that it only broke on that specific line only though. Looking over this class, there's another place with a similar where using the contract that phpstan isn't complaining about... Oh well, thanks phpstan is passing now after replacing the contract import with `Illuminate\Database\Eloquent\Builder`

**Comment by calebdw** [comment]
> there's another place with a similar where using the contract that phpstan isn't complaining about... 

It's not going to complain until you go to **use** the inner type, your `Collection` also needs to have its generics defined so that whatever calls the method knows what's inside of it:

```php
    /** @return Collection<int, Pin> */
    public function getByAddress(string $search): Collection
```

> Oh well, thanks phpstan is passing now after replacing the contract import with Illuminate\Database\Eloquent\Builder

Great!, sounds like you can close this then :smile:

**Comment by canvural** [comment]
I think the actual issue was that it detected somehow the builder as `Illuminate\Database\Eloquent\Builder<*>` (attention on `*`) Then of course it can't find a property on it because there is no model to check. A solution was to type hint it correctly, like you did.

But maybe we can make it so it doesn't produce an error when the generic type is `*`

**Comment by calebdw** [comment]
> But maybe we can make it so it doesn't produce an error when the generic type is *

The solution should be to tell PHPstan about the inner type, not to silently ignore potential errors. Ignoring `*` would mean that the user is not aware that there's an issue that needs to be fixed in the first place

**Comment by canvural** [comment]
PHPStan already produces error if you don't typehint the generic types. (like in the OP's example) But for `checkModelProperties` if the generic type is `*` there is nothing we can infer so we can just skip the `if it is a model property` check and treat it as a normal string.
