### ISSUE TITLE
cannot find object type in create

### ISSUE THREAD

**Issue by adminfriso** [nunomaduro/larastan#208]
- Larastan Version: v0.3.10
- `--level` used: max

### Description:
Cannot find object type in create, whereas it does find the property in the same level as the create exists as shown in line 39.

### Laravel code where the issue was found:

```php
        $collars = Collar::all();
        foreach ($collars as $collar) {
            if (!empty($collar->type)) {
    39          $response = $this->getLastDeviceLocation($collar->type);
                if (!empty($response)) {
                    if (!empty($response['lat'])) {
                        $lat = $response['lat'];
                    }
                    if (!empty($response['lng'])) {
                        $lng = $response['lng'];
                    }
                    CollarData::create(
                        [
    51                      'collar_id' => $collar->id, 
                            'lng' => $lng,
                            'lat' => $lat,
                            'log_at' => now(),
                        ]
                    );
                }
            }//end if
        }//end foreach
```

### error 

 51     Access to an undefined property object::$id.

**Comment by adminfriso** [comment]
calling collar->id on line 40 also gives the error.

    $id = $collar->id;

adding id to fillable on the model still gives the error.

    protected $fillable = [
        'id',
        'type',
    ];

Am I doing something wrong?

**Comment by szepeviktor** [comment]
Hello @adminfriso !

Try to make your code better by changing `if(!empty()) {...}` to `if(empty()) continue;`

**Comment by szepeviktor** [comment]
Maybe PHPStan does not know that foreach puts 1 collar into `$collar`

**Comment by nunomaduro** [comment]
@szepeviktor I can add feature.

**Comment by adminfriso** [comment]
@szepeviktor good one, thanks

**Comment by adminfriso** [comment]
@szepeviktor as shown in line 39 it can find the value of type in the object. this issue should also be adressed in V.03.10 as @nunomaduro fixed it, related to issue #207

**Comment by szepeviktor** [comment]
> as shown in line 39 it can find the value of type in the object

I think `if (!empty($collar->type)) {` tells PHPStan that type exists, not the foreach loop.

**Comment by adminfriso** [comment]
good one, would think so indeed

**Comment by canvural** [comment]
Can you re-test this with 0.4.3?
