### ISSUE TITLE
Larastan generates incorrect type for relationship

### ISSUE THREAD

**Issue by gms8994** [nunomaduro/larastan#2083]
- Larastan Version: v2.9.5
- Laravel Version: v10.48.20

### Description
If I use a relationship inside another relationship, the resulting information that phpstan knows about the relationship is only `Illuminate\Database\Eloquent\Model`, not my model class. The below code with `\PHPStan\dumpType($service->hours2)` will show `Dumped type: Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Model>`. This is true whether I use a scope on the relationship or not. I found this by trying to `$service->hours->map(function (Hours $hours) ... );`, and phpstan kept complaining about `Parameter #1 $callback of method Illuminate\Database\Eloquent\Collection<int,Illuminate\Database\Eloquent\Model>::map() expects callable(Illuminate\Database\Eloquent\Model, int): (string|null), Closure(App\Models\Hours, int): (string|null) given.`

### Laravel code where the issue was found

```php
class Service extends Model {
    public function hours() : \Illuminate\Database\Eloquent\Relations\HasMany {
        return $this->hasMany(Hours::class, 'id');
    }

    public function hours2() : \Illuminate\Database\Eloquent\Relations\HasMany {
        return $this->hours()->myScope();
    }

    public function hours3() : \Illuminate\Database\Eloquent\Relations\HasMany {
        return $this->hasMany(Hours::class, 'id')->myScope();
    }

}
```

**Comment by calebdw** [comment]
You need to add the generics to the relationships if you want this to work (also, update to the latest Larastan version):

```php
    /** @return HasMany<Hours, $this> */
    public function hours(): HasMany {
        return $this->hasMany(Hours::class, 'id');
    }
```

**Comment by gms8994** [comment]
Is this documented as a necessity anywhere? Because this is the first time I've seen this kind of information anywhere.

**Comment by calebdw** [comment]
I have an open PR (#2036) to add some more docs and my relation PR had docs for the relationships that was not merged (there's a comment about that [here](https://github.com/larastan/larastan/issues/2071#issuecomment-2416781749)).

However, this is *static* analysis, if you want PHPStan to understand your code then you're going to have to add the generics to your methods (this includes things like the inner Collection types, etc.). Larastan tries to help the developer out manually parsing the Model file and looking for the class strings when looking at the relationship **properties** but we don't do that for the relationship methods (nor should we)

**Comment by MrPunyapal** [comment]
@calebdw 👀
it works without Lasrastan. (I tried locally)
https://github.com/pinkary-project/pinkary.com/actions/runs/11573726758/job/32216443410

**Comment by canvural** [comment]
Hi,

PHPStan actually [tells you](https://phpstan.org/r/20ca5e9a-5fe0-4258-8027-a6216f809a36) that you forgot to write the generic inner types for generic classes. Unless you have `checkGenericClassInNonGenericObjectType: false` or use a lower level.
