### ISSUE TITLE
Undefined properties after model change in foreach

### ISSUE THREAD

**Issue by ju5t** [nunomaduro/larastan#2086]
- Larastan Version: 2.9.9
- Laravel Version: 11.29.0

### Description

We had to rename a column in multiple tables so decided to use a loop in the migration.

```php
foreach ($tables as $table) {
    Schema::table($table, function (Blueprint $table) {
        $table->renameColumn('field', 'field_id');
    });
}
```

This results in `field_id` being an undefined property in something like:

```php
$customer = Customer::query()->find($id);
$customer->field_id;
```

When I don't use a loop Larastan works as expected.

```php
Schema::table('customers', function (Blueprint $table) {
    $table->renameColumn('field', 'field_id');
});
```

So it looks like the loop is causing the issue here.

**Comment by calebdw** [comment]
The code that scans your migration to understand the database columns is not going to properly understand this dynamic code. Either don't use a foreach loop and copy/paste the block or squash the migration after it's executed

**Comment by ju5t** [comment]
Makes sense. Thanks for the quick reply @calebdw!
