### ISSUE TITLE
PHPStan stops working on Windows

### ISSUE THREAD

**Issue by ggolda** [nunomaduro/larastan#209]
If I add `phpstan.neon` file as proposed in this [issue](https://github.com/nunomaduro/larastan/issues/139), vscode phpstan plugin stops working on Windows.

Any ideas how I can fix or at least debug this?
Without this additional `phpstan.neon` file phpstan works as expected.

**Comment by szepeviktor** [comment]
> PHPStan stops working on Windows

Are you sure is not Larastan?

**Comment by canvural** [comment]
This sounds like an issue with the VSCode PHPStan plugin.
