### ISSUE TITLE
Larastan 2.9.9: model factory Type inference regression causing `undefined property|method` errors

### ISSUE THREAD

**Issue by plakhin** [nunomaduro/larastan#2097]
- Larastan Version: 2.9.9
- Laravel Version: 11.30.0

### Description
After updating from 2.9.8 to 2.9.9 I'm getting a lot of errors like `Access to an undefined property Illuminate\Database\Eloquent\Model::$id.`, `Call to an undefined method Illuminate\Database\Eloquent\Model::getTransaction().` and `Parameter #1 $callback of static method Services\PaymentProvider::notifyOfReceivedCallback() expects App\Models\PaymentProviderCallback, Illuminate\Database\Eloquent\Model given.`.

All of these errors happen when a model instance is created using a factory, e.g. `$callback = app(PaymentProviderCallback::class)::factory()->create();`

In case an instance were created simply using `$callback = PaymentProviderCallback::factory()->create();`, I'm getting `Access to an undefined property Illuminate\Database\Eloquent\Collection<int, Illuminate\Database\Eloquent\Model>|Illuminate\Database\Eloquent\Model::$id.`

I'm not getting any of these errors with larastan 2.9.8.

Adding `/** @var PaymentProviderCallback $callback */` helps, but I don't think this is the right way.

**Comment by calebdw** [comment]
Your factory likely doesn't have the proper generics, what does it look like? Also, what does your model look like?

**Comment by plakhin** [comment]
@calebdw, adding this helped:

```php
/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\PaymentProviderCallback>
 */
class PaymentProviderCallbackFactory extends Factory
...
```

I've also added generics to some complicated relationships to solve few other similar issues.

Thanks for the hint!
