### ISSUE TITLE
Extract extension rules to a separated package

### ISSUE THREAD

**Issue by carusogabriel** [nunomaduro/larastan#21]
Hi @nunomaduro 

Can I suggest you extract all the extension rules to a separated package? I'd love to use PHPStan + Laravel, but without a command, only the simple `vendor/bin/phpstan analyze` :smile: 

Regards

**Comment by nunomaduro** [comment]
Hey @carusogabriel 👋

You can do it already.

1. Add to your phpstan.neon file:

```
includes:
	- vendor/nunomaduro/larastan/extension.neon
```

2. Run:

```
./vendor/bin/phpstan analyse -l 5 -c phpstan.neon app
```

**Comment by carusogabriel** [comment]
Oh, thank you :tada:
