### ISSUE TITLE
Related model type is inferred as `mixed`

### ISSUE THREAD

**Issue by sebj54** [nunomaduro/larastan#2100]
- Larastan Version: 2.9.10
- Laravel Version: 11.30.0

### Description

I am using Larastan alongside this package: https://github.com/staudenmeir/belongs-to-through

Since version 2.9.9, I am facing these `Cannot access property $id on mixed.` errors:

![image](https://github.com/user-attachments/assets/71b5580f-fad4-4568-b6b0-21b1efcd1f5a)

I have opened an issue on this repo, but the owner thinks this issue is due to Larastan, so I'm opening an issue here (see [related issue](https://github.com/staudenmeir/belongs-to-through/issues/105)).

I made a repro project: https://github.com/sebj54/debug-belongs-to-through-phpstan

Just run these commands to see the issue:

```
composer install
php artisan migrate
php ./vendor/bin/phpstan
```

You can check the commits to see what I've done in this reproduction project. I reused the tables and relations described in the README of the `belongs-to-through` package (Comment → belongs to → Post → belongs to → User → belongs to → Country).

Feel free to ask, I'll be glad to help in any way!

**Comment by szepeviktor** [comment]
Thank you!!

Could you show us one of the belongs to definitions?

**Comment by sebj54** [comment]
Yes, sure!

It's a `BelongsToThrough` from this package: https://github.com/staudenmeir/belongs-to-through

```php
/**
 * @return BelongsToThrough<Country, $this>
 */
public function country(): BelongsToThrough
{
    return $this->belongsToThrough(Country::class, User::class);
}
```

Here is the phpdoc for the custom relation class:

```php
/**
 * @template TRelatedModel of \Illuminate\Database\Eloquent\Model
 * @template TDeclaringModel of \Illuminate\Database\Eloquent\Model
 *
 * @extends \Illuminate\Database\Eloquent\Relations\Relation<TRelatedModel>
 */
class BelongsToThrough extends Relation
```

If it helps, the package's developer also stated that this issue occurs in all of his relation-related packages, like this one: https://github.com/staudenmeir/laravel-adjacency-list/actions/runs/11539893630/job/32120085541

**Comment by szepeviktor** [comment]
I see! `BelongsToThrough` is not in the framework, so not supported by Larastan.
It needs a [PHPStan extension](https://github.com/larastan/larastan/blob/2339c97acea06561a4ecbdc7af792d2771a2a779/src/Types/RelationDynamicMethodReturnTypeExtension.php#L43-L53).

**Comment by calebdw** [comment]
> I see! BelongsToThrough is not in the framework, so not supported by Larastan.

This is not true, Larastan should be able to handle any relation which extends from Relation---I'll dig into this when I get the chance

**Comment by canvural** [comment]
Hi,

This was a error with the package. The 2.16.1 version is using [wrong annotations](https://github.com/staudenmeir/belongs-to-through/blob/v2.16.1/src/Relations/BelongsToThrough.php#L19) when extending the Relation. But looks like it is fixed in main, just not released. If you use `main` your issue should be solved.

**Comment by sebj54** [comment]
@canvural Thank you very much for the quick reply! I just tested with the `main` branch and it works like you said. I will inform the author then :)
