### ISSUE TITLE
Cannot install larastan/larastan:^2.0 on Laravel 11.30.0

### ISSUE THREAD

**Issue by rokaspaulik** [nunomaduro/larastan#2101]
- Larastan Version: 2.9.10
- Laravel Version: 11.30.0

### Description

Cannot install Larastan on Laravel 11.30.0.

### Laravel code where the issue was found (with steps to reproduce)

**This bug was found on fresh Laravel installation after using:**

```bash
laravel new example-app
```

```bash
composer require --dev "larastan/larastan:^2.0"
```

### Output

```bash
Composer could not detect the root package (laravel/laravel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
The "2.0" constraint for "larastan/larastan" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Composer could not detect the root package (laravel/laravel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Running composer update larastan/larastan
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires larastan/larastan 2.0 -> satisfiable by larastan/larastan[2.0.0].
    - larastan/larastan 2.0.0 requires illuminate/console ^9 -> found illuminate/console[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
```

**Comment by szepeviktor** [comment]
Caret must be a special character.

> The "2.0" constraint for "larastan/larastan" appears too strict

appears to be lost ...

**Comment by szepeviktor** [comment]
I do not use cmd.exe but maybe
```
composer require --dev larastan/larastan:^^2.0
```

**Comment by rokaspaulik** [comment]
> I do not use cmd.exe but maybe
> 
> ```
> composer require --dev larastan/larastan:^^2.0
> ```

Please stop talking out of the blue without trying to reproduce bug yourself.
Tried your suggestions, none of them work.

**Comment by rokaspaulik** [comment]
> Caret must be a special character.
> 
> > The "2.0" constraint for "larastan/larastan" appears too strict
> 
> appears to be lost ...

Where is it lost? I copied over the command I ran directly from console.

`composer require --dev "larastan/larastan:^2.0"`

It is the composer output that says this "The "2.0" constraint for "larastan/larastan" appears too strict" but I ran the command using special character as defined in docs.

I actually even know the root cause - the problem is that Larastan requires illuminate/console[v9.0.0, ..., v9.52.16] to be within range of v9 but some Laravel packages are newer (v10+|v11+) and that prevents the installation of Larastan.

**Comment by rokaspaulik** [comment]
I actually even know the problem - the problem is that Larastan requires illuminate/console[v9.0.0, ..., v9.52.16] to be within range of v9 but some Laravel packages are newer and that prevents the installation of Larastan.

**Comment by calebdw** [comment]
> Please stop talking out of the blue without trying to reproduce bug yourself.

Viktor is just trying to help, there's no need to be rude. If Viktor can't reproduce then it's likely a "you" problem


> I actually even know the root cause

If you're so confident that you know the root cause then submit a PR to fix the root cause. However, you are mistaken:
https://github.com/larastan/larastan/blob/e4cdc6034db31e3873c9bb88d795c584793c9ff1/composer.json#L20

Have you tried just installing the package without the version constraint? Composer should be smart enough to grab the latest version that satisfies your existing dependencies:

```bash
composer require --dev "larastan/larastan"
```

Finally, if all else fails then you can likely just manually add the package to your `composer.json` and then execute `composer upgrade`:

```json
"require-dev": {
        "larastan/larastan": "^2.0",
}

**Comment by rokaspaulik** [comment]
Well in composer.lock of default laravel install I see this:

```
"name": "laravel/pail",
"version": "v1.2.0",
"source": {
    "type": "git",
    "url": "https://github.com/laravel/pail.git",
    "reference": "085a2306b520c3896afa361c25704e5fa3c27bf0"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/laravel/pail/zipball/085a2306b520c3896afa361c25704e5fa3c27bf0",
    "reference": "085a2306b520c3896afa361c25704e5fa3c27bf0",
    "shasum": ""
},
"require": {
    "ext-mbstring": "*",
    "illuminate/console": "^10.24|^11.0",
```

`"illuminate/console": "^10.24|^11.0",`

> Have you tried just installing the package without the version constraint? Composer should be smart enough to grab the latest version that satisfies your existing dependencies:

I'm not saying I cannot workaround the problem. Mostly posted this because it must be misleading to lots of beginners when docs suggest to run and it does not work **as a default**

```bash
composer require --dev "larastan/larastan:^2.0"
```

My suggestion is to then change suggested install command to:

```bash
composer require --dev "larastan/larastan"
```

**Comment by canvural** [comment]
Hi,

The problem is in your system somehow. This line tells you all what you need to know `The "2.0" constraint for "larastan/larastan" appears too strict and will likely not match what you want.`

**Comment by BrunoHoinacki** [comment]
Fix this error with composer require --dev "larastan/larastan"  
        "laravel/framework": "^11.9"
        "larastan/larastan": "*",

**Comment by gvdp** [comment]
I'm getting the same error when upgrading from 2.9 -> 2.10, I think the new illuminate/console requirement conflicts with `laravel/prompts`:

```
laravel/prompts             v0.3.5   conflicts illuminate/console (>=10.17.0 <10.25.0)
```

Not sure why they are limiting the `illuminate/console` version to this specific window.
