### ISSUE TITLE
Support phpstan 2.0

### ISSUE THREAD

**Issue by momala454** [nunomaduro/larastan#2106]
# Feature Request

Support the latest version of phpstan

**Additional context**

**Comment by canvural** [comment]
Hi,

It is being worked on. If you want you can try the `3.x` branch

**Comment by pindab0ter** [comment]
While taking into account that this is an open source project and you are under no obligation to answer this question, and even if you answer, knowing that this can and most likely will change;

Do you have a rough estimate of when 3.0 might be done? Should we expect orders of magnitude of weeks, months or longer than that?

**Comment by canvural** [comment]
Sure, no problem to ask that. It'll be released this week: https://x.com/can__vural/status/1855877591720173801

**Comment by pindab0ter** [comment]
Awesome! Looking forward to it!

**Comment by canvural** [comment]
You can already try 3.x branch if you can't wait 😄

**Comment by calebdw** [comment]
@canvural, can we try to get some of my PRs merged (some have been open since Feb.) before 3.x is released?

**Comment by canvural** [comment]
> @canvural, can we try to get some of my PRs merged (some have been open since Feb.) before 3.x is released?

I don't see any breaking changes. So I think it's not urgent. We can always make new releases later. And first I need to review them. Sorry it took so long, I'll try to get to it next week or so.

**Comment by matthiasPOE** [comment]
Is there any way to have this work on laravel 10? Is the dependancy lock to 11^ required?

**Comment by canvural** [comment]
Maintaining multiple Laravel versions is always an hassle. And because of PHPstan 2.0.x we had to make a new major version, so I decided to drop the older versions too.

2.x branch of Larastan will still receive updates for some time though. Also if you enable bleeding edge in PHPStan 1.12.x you'll basically get PHPStan 2.0.x So you are not losing any features or anything.

Hope that clears it.
