### ISSUE TITLE
Missing tests on 3.x

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#2112]
There seems to have been a bad rebase / merge during the 3.x creation and release process. I noticed that a [test file was missing on 3.x](https://github.com/larastan/larastan/blob/3.x/tests/Type/data/model-relations-l11-15.php) and after further digging I found that the the assertions were not moved to another file. 

The test file in question is [`tests/Type/data/model-relations-l11-15.php`](https://github.com/larastan/larastan/blob/2.x/tests/Type/data/model-relations-l11-15.php) and git seems to have no record of the file being deleted on 3.x

Not sure if other files have been affected.

**Comment by canvural** [comment]
Hi,

You are totally right. I'm not sure what happened. I was sure I moved all those tests to `model-relations` file. Fixed with: 02f35d2d

Thank you.

**Comment by calebdw** [comment]
@canvural, I had type tests *inside* the model relation methods for a reason which seem to have been removed...
