### ISSUE TITLE
Opt-in for a self-contained binary?

### ISSUE THREAD

**Issue by sikhlana** [nunomaduro/larastan#2113]
`larastan` sometimes fails when I have some kind of error in my code (which obviously occurs during work-in-progress), for example in a service provider, and the error notification fills up my IDE's entire viewport; which is kind of annoying sometimes.

So my suggestion is how about opting in for a self-contained binary which doesn't use/load dependencies from the project just like how it's done in https://github.com/laravel/pint/

I can work on a PR if you guys are interested.

**Comment by calebdw** [comment]
I don't think this is going to work as well as you think:
- Larastan **has** to boot the container to understand Laravel's magic---if you don't want / need this than just use PHPStan.
- Larastan is just a bunch of PHPStan extensions which is already a self contained PHAR

**Comment by sikhlana** [comment]
The first point kills the whole idea then. LOL.
