### ISSUE TITLE
Upgrade to 8.3 + Larastan 3.0.2 : errors with model properties

### ISSUE THREAD

**Issue by ryssbowh** [nunomaduro/larastan#2144]
- Larastan Version: 3.0.2
- Laravel Version: 11.34.2

### Description

I've been phpstanning this new project since day 1 and it's been working beautifully.
Today I updated to the versions mentionned above and I'm getting 400+ errors, which seem to be all either :
- `property.notFound` on models
- `return.type` on model queries
- `argument.type` on models

I do not comment my classes with properties, I use migrations and I type every single function return and argument. I've also cleared my phpstan cache.

I feel I'm missing something obvious but can't figure it out, any pointers appreciated.

Thanks for your help and this package, it's prevented countless problems already.

**Comment by szepeviktor** [comment]
Hello @ryssbowh 👋🏻 

`$this` is our _highly secretive_ document: https://github.com/larastan/larastan/blob/3.x/UPGRADE.md#upgrading-to-30-from-2x

**Comment by ryssbowh** [comment]
Very obvious miss indeed ! :grin:

**Comment by nunodonato** [comment]
Sorry to post here, but I didn't want to open a new issue.
I'm facing this exact problem, already went through the upgrade guide, still get the property.notFound errors all over the place.

If I run ide-helper and generate the docblocks in the model files, it solves the issue. But I didn't need this before and don't want all that clutter. Any pointers on what I might be doing wrong?

**Comment by canvural** [comment]
@nunodonato Did you read [this part](https://github.com/larastan/larastan/blob/3.x/UPGRADE.md#correct-return-types-for-model-relation-methods) of the upgrade guide? Does all your relations have the correct `@return` annotations?

**Comment by nunodonato** [comment]
> [@nunodonato](https://github.com/nunodonato) Did you read [this part](https://github.com/larastan/larastan/blob/3.x/UPGRADE.md#correct-return-types-for-model-relation-methods) of the upgrade guide? Does all your relations have the correct `@return` annotations?

@canvural sorry for my delay.
yes, they do. And I get these errors even in simple properties (like `country->code`) not related to relations at all

**Comment by canvural** [comment]
@nunodonato Can you open a new discussion with a simple code example, error and how your migrations are written?

**Comment by nunodonato** [comment]
@canvural migrations are squashed, so I dont think it matter how they are written. will open a new discussion

**Comment by calebdw** [comment]
What database are you using?

**Comment by nunodonato** [comment]
@calebdw mysql8

**Comment by nunodonato** [comment]
actually guys, this doesn't even require different models. In the same model I do something like `$this->name` and it fails with the same error. If I add the `@property` phpdoc, it works, but then all my models get cluttered

**Comment by canvural** [comment]
@nunodonato For squashed migrations Larastan tries to parse the SQL file to understand the database structure. If you have your squashed file somewhere else than the usual location use [this](https://github.com/larastan/larastan/blob/3.x/docs/custom-config-parameters.md#squashedmigrationspath) config option to specify it.

**Comment by nunodonato** [comment]
@canvural yes, thanks, I do have it in the standard location

**Comment by calebdw** [comment]
Can you share your phpstan config?

**Comment by nunodonato** [comment]
@calebdw sure: https://gist.github.com/nunodonato/c0235ece44d8ecb3d2410b5355ead358

**Comment by nunodonato** [comment]
@canvural started a new discussion as requested: https://github.com/larastan/larastan/discussions/2300
