### ISSUE TITLE
Eloquent collection each

### ISSUE THREAD

**Issue by ahoiroman** [nunomaduro/larastan#2148]
- Larastan Version: 3.0.2
- Laravel Version: 11

### Description
I am getting this error:

```
  39     Parameter #1 $callback of method                                                        
         Illuminate\Support\Collection<(int|string),Illuminate\Database\Eloquent\Model>::each()  
         expects callable(Illuminate\Database\Eloquent\Model,                                    
         int|string): mixed, Closure(App\Domain\User\Models\User):                               
         App\Domain\User\Models\User given.                                                      
         🪪  argument.type                                                                                                      
```

### Laravel code where the issue was found

```php
/** @var Collection<User> $users */
$users = SuggestionService::search($member);

$users->each(function (User $user) {
    app(CreateSuggestion::class)($user);

    return $user;
});
```

The search method also has a proper annotation:

```
/**
 * @return Collection<User>
 */
 ```

**Comment by szepeviktor** [comment]
This is a work-around: `function ($user)`

**Comment by ahoiroman** [comment]
Sure. But in this case I need do create a docblock for `$user` again before passing it to the `CreateSuggestion` action, because this expects an instance of `User`, not of `Model`.

While this would work, it doesnt seem like the intended way to do that?

**Comment by szepeviktor** [comment]
> I need do create a docblock for `$user` again

I think Larastan will figure it out without a docblock.

**Comment by ahoiroman** [comment]
Unfortunately, it does not.

**Comment by calebdw** [comment]
Your generics are incorrect, you need to specify the both the key and model type:

```php
Collection<int, User>
```

Also, when using `each`, there's no need to return anything---the return is not used (unlike `map`):

```php
/** @var Collection<int, User> $users */
$users = SuggestionService::search($member);

$users->each(fn ($user) => app(CreateSuggestion::class)($user));
```

**Comment by ahoiroman** [comment]
Great, thanks.
