### ISSUE TITLE
variable.undefined when used in a laravel when construct with isset condition

### ISSUE THREAD

**Issue by giacomomasseron** [nunomaduro/larastan#2151]
- Larastan Version: 3.0.2
- Laravel Version: 11.35.1

### Description
I got the error `Variable $trialUntil might not be defined`.  
But as you can see, the variable `$trialUntil` can not be undefined, cause the `when` condtion avoid this.

### Laravel code where the issue was found

```php
return tap(
    $this->newSubscription($customerTierEnum->value, $price->id)
        ->when(
            isset($trialUntil),
            fn (SubscriptionBuilder $subscriptionBuilder) => $subscriptionBuilder
                ->trialUntil($trialUntil)
        )
        ->create(
            $paymentMethod,
        ),
    fn () => doWhatever(),
);
```

**Comment by calebdw** [comment]
This is not a bug, the second parameter is evaluated in the same context as the undefined variable--- you need to use the variable that's passed to the closure:

```php
return tap(
    $this->newSubscription($customerTierEnum->value, $price->id)
        ->when($trialUntil, fn ($q, $until) => $q->trialUntil($until))
        ->create($paymentMethod),
    fn () => doWhatever(),
);
```
