### ISSUE TITLE
Fails to detect existing model relation

### ISSUE THREAD

**Issue by maxacarvalho** [nunomaduro/larastan#2159]
- Larastan Version: 3.0.2
- Laravel Version: 11.27.2

### Description
I'm getting an error about a missing model relationship while the relationship is declared.  
The error only happens when the return type includes the related model builder, for example:

```php
/**
 * @return BelongsTo<Coupon, $this>|CouponBuilder
 */
public function coupon(): BelongsTo|CouponBuilder
{
    return $this->belongsTo(Coupon::class, 'coupon_id');
}
```

See that I include the `CouponBuilder` in the return type. It helps the IDE to rely on the custom builder custom methods. But it cause the Larastan check to fail:
```bash
Relation 'coupon' is not found in App\Models\Household\Household model.
```

If I remove the `CouponBuilder` from the return type it works as expected.

**Comment by calebdw** [comment]
This is not a bug, the relation **never** returns a CouponBuilder so it shouldn't be included

**Comment by maxacarvalho** [comment]
Hi @calebdw 
Thanks for your reply.
I agree that it does not return an instance of the builder but Laravel allows builder methods to be called against the relationship method. Things like `$myModel->myRelation()->someCustomBuilderMethod()` will work normally.  
Any suggestion to solve that?

**Comment by calebdw** [comment]
Larastan will properly forward calls to the correct builder so that's not an issue. If you're talking about IDE support then that's another story. You can try using `getQuery()` to call the method directly on the builder, or you can look into the ide-helper package

```php
$myModel
    ->myRelation()
    ->getQuery()
    ->someCustomBuilderMethod();
```

**Comment by maxacarvalho** [comment]
Thanks again @calebdw 
Yes, I'm talking about the IDE support. Nope, the `getQuery()` method won't help us there 😢 
The `ide-helper` package brings more problems than help we decided to stay away from it.  
Until we find a better solution I'll have to turn-off that check.

**Comment by calebdw** [comment]
Yeah, sometimes you just have to suffer through IDE issues for the more magical parts of Laravel

But this issue can be closed since this isn't a bug with Larastan
