### ISSUE TITLE
Access to an undefined property object::$ (False positive)

### ISSUE THREAD

**Issue by neoplomero** [nunomaduro/larastan#216]
- Larastan Version: 0.3.12
- `--level` used: default

### Description:
Having  this error: 

 ------ ------------------------------------------------------
  Line   xxx/xxxx/xxxx/xxx.php
 ------ ------------------------------------------------------
  257    Access to an undefined property object::$Dividend.
  260    Access to an undefined property object::$IdtRace.
  267    Access to an undefined property object::$StartTime.
  268    Access to an undefined property object::$RaceNumber.
 ------ ------------------------------------------------------

### Laravel code where the issue was found:

```
/**
* Process raceResults
*
* @param object    $races Race xml
* @param object    $track track data
* @param object    $date  DateTime object     *
*
* @return string
*/
public function loadRaceResults($races, $track, $date)
{
    foreach ($races as $race) {
       $this->racesNum++;
       // check that we have results
       if (isset($race->Result) && isset($race->Result[0]->WinnersTime)) {
           $dividends = $this->getDividends($race->Dividend) : '';
           $raceData = [
               'source_id' => (string) $race->IdtRace : '',
               'winner_time' => (float) $race->Result[0]->WinnersTime,
               'dividends' => $dividends
           ];
           $raceStored = $this->race->fromXmlData([
                'track_id' => $track->id,
                'date' => (string) $date->format('Y-m-d'),
                'time' => (string) $race->StartTime : '',
                'race_num' => (string) $race->RaceNumber : '',
          ]);
              if (!empty($raceStored)) {
                  $raceUpdated = $this->race->update($raceStored->id, $raceData);
                  $this->racesUpdated++;
             }
         $this->processResultsDogs($race, $raceStored->id);
    }
}
```

**Comment by neoplomero** [comment]
I've sorted validating if !empty() each of those but I think is not the best way. What do you guys think?

**Comment by nunomaduro** [comment]
@neoplomero The problem is in your code: `@param object    $races Race xml`.

**Comment by neoplomero** [comment]
@nunomaduro what is the problem?

**Comment by adminfriso** [comment]
@neoplomero There is no strongtype to races to the varables as input, therefor larastan does not know  what type of object the $races varable is. And therfore it cannot relate what kind of object $race is.
Try to qualify the object in your input variable
 `public function loadRaceResults (collect(Race) $races, Track track, DateTime $date)`'

**Comment by neoplomero** [comment]
:thinking:  hmm didn't work. I'll close the ticket anyways. Thanks a lot. 

Note: Validating (empty()) those fields did the trick.

**Comment by nunomaduro** [comment]
Try this

```php
/**
* Process raceResults
*
* @param \Illuminate\Database\Eloquent\Model[]    $races Race xml <-------
* @param object    $track track data
* @param object    $date  DateTime object     *
*
* @return string
*/
public function loadRaceResults($races, $track, $date)
{
```

**Comment by neoplomero** [comment]
@nunomaduro it is not an Eloquent model object.  It is a parsed XML object.

**Comment by nunomaduro** [comment]
Sorry, my bad.

**Comment by neoplomero** [comment]
Thanks again.
