### ISSUE TITLE
False positive if return is encapsulated in conditions

### ISSUE THREAD

**Issue by Sch-Tim** [nunomaduro/larastan#218]
- Larastan Version: ^0.3.12
- `--level` used: default

### Description:
I'm getting some false positives if a function should return some specific types by PHPDoc and indeed returns them, but encapsulated in if conditions.  

```
    /**
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public static function someFunction()
    {
        if (condition)) {
            return abort(123, "nope!");
        } else {
            return redirect('/');
        }
    }
```

You can see that this will in any case return something, but I get an error that it would return void.

**Comment by Sch-Tim** [comment]
This is indeed a better solution, but I wonder if returns inside if-conditions are investigated? 

Strangely, this doesn't solve the problem. I changed the code and still get this warning. The Line hint points to the line with the abort. 
Could the reason for this be that abort doesn't really return something but throws an exception?

**Comment by staudenmeir** [comment]
Since `abort()` returns `void`, I would say that the error is correct.

You can change your code to this:

```php
if (condition) {
    abort(123, 'nope!');
}

return redirect('/');
```

**Comment by Sch-Tim** [comment]
Well then I'll have to stop returning my aborts. Bad habit.. 
Thank you guys!
