### ISSUE TITLE
Using Eloquent whereParam()

### ISSUE THREAD

**Issue by richardkeep** [nunomaduro/larastan#22]
Throws an error `Call to an undefined static method *whereParamId*` when you do `App\Model::whereParamId($id)->get()`. It wants you to do `App\Model::where('param_id', $id)->get()`.

**Comment by nunomaduro** [comment]
Because this issue seems to be inactive for quite some time now, I will close it. This problem should be fixed by now.

Thank! ☺️

**Comment by richardkeep** [comment]
The issue has been fixed. Sorry for not reverting soon. Thanks :)
