### ISSUE TITLE
False positive: Call to an undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::withTrashed()

### ISSUE THREAD

**Issue by Turtle1363** [nunomaduro/larastan#225]
- Larastan Version: 0.3.13
- `--level` used: 5

### Description

I'm getting what I believe are false positives

Call to an undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::withTrashed()

### Laravel code where the issue was found:

here is the trait I'm using

```php

namespace App\Relations;

use App\Model\System\SoftwarePublisher;


trait BelongsToSoftwarePublisher
{
    public function software_publisher()
    {
        return $this->belongsTo(
            SoftwarePublisher::class,
            'software_publisher_id'
        )->withTrashed();
    }

    public function setSoftwarePublisherAttribute($value)
    {
        $this->setBelongsTo(
            SoftwarePublisher::class,
            'software_publisher',
            $value
        );
    }
}
```

I get an error like this:

```
 ------ -------------------------------------------------------------------------------------------------
  Line   Relations\BelongsToSoftwarePublisher.php (in context of class App\Model\System\SoftwarePackage)
 ------ -------------------------------------------------------------------------------------------------
  12     Call to an undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::withTrashed().
 ------ -------------------------------------------------------------------------------------------------
```

`App\Model\System\SoftwarePackage` is extended (eventually) from a `Illuminate\Database\Eloquent\Model`.  There are a few classes inherited between `Illuminate\Database\Eloquent\Model` and `App\Model\System\SoftwarePackage`.  The direct descendant of `Illuminate\Database\Eloquent\Model` has `uses SoftDeletes`.

In general the code "works", meaning I can use the soft-delete functionality successfully.  Which leads me to believe this may be a false positive?

**Comment by nunomaduro** [comment]
@Turtle1363 @szepeviktor Wanna take this one?

**Comment by Turtle1363** [comment]
@nunomaduro, I wouldn't be able to fix.  I'm a n00b.  I am literally in awe of this package for laravel, it is truly amazing how many errors in my code it found.

**Comment by Turtle1363** [comment]
@szepeviktor , it is related.  @nunomaduro asked that I make a separate issue with relevant snippets?

**Comment by canvural** [comment]
Fixed in newer releases.

**Comment by scottypipz** [comment]
Is this fixed? I am still having an issue

**Comment by szepeviktor** [comment]
Maybe `public function morphTo(): AModel` needs a return typehint.

**Comment by alecpl** [comment]
I'm having a problem creating a new ticket. Could someone fix the issue mentioned above in https://github.com/nunomaduro/larastan/issues/225#issuecomment-825526950 and/or create a ticket?

**Comment by szepeviktor** [comment]
> I'm having a problem creating a new ticket.

Here you go: https://github.com/nunomaduro/larastan/issues/new/choose 🚀

**Comment by alecpl** [comment]
The ticket created, I don't know what was it. #942
