### ISSUE TITLE
Isset operator (??) is not correctly parsed

### ISSUE THREAD

**Issue by telefoontoestel** [nunomaduro/larastan#231]
- Larastan Version: 0.3.13
- `--level` used: 5
- Laravel Framework Version: 5.6.39

### Description:
When parsing a piece of code with an isset operator (??), will return an error that it will always have the value of the rhs.

### Laravel code where the issue was found:  
`return ($entity->active ?? true) 
    && !($entity->deleted ?? false)`

This will yield the following errors:

- Left side of && is always true.
- Negated boolean is always true.

**Comment by szepeviktor** [comment]
Thank you for the report!

This seems to be a PHPStan error.
Please provide a sample code on https://phpstan.org/ and [open an issue upstream](https://github.com/phpstan/phpstan/issues/new).

**Comment by ondrejmirtes** [comment]
I can't reproduce it: https://phpstan.org/r/47c4d3dd-e395-4333-8f10-a8be93a7aa9a, https://phpstan.org/r/6c3b5611-ddb6-484d-8890-334cacbc214f

Which type is `$entity->active` and `$entity->deleted`?

**Comment by telefoontoestel** [comment]
The entity is a wrapper class around the Eloquent Model class. I've changed the example at https://phpstan.org/r/f23dc113-588c-4d7b-a976-54f63f788ace. When running it on cli I don't get the warning _Access to an undefined property Entity::$active_. It seems that the sandbox doesn't handle the magic __get very well. The default value for active is 1 and for deleted is 0, but obviously this can change depending on the model attribute values.

**Comment by nunomaduro** [comment]
🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️🧙‍♂️
