### ISSUE TITLE
Bootstrap file vendor/autoload.php does not exist.

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#232]
- Larastan Version: 0.3.15
- `--level` used: default

### Description:
I get this error when I run the analyze command:
```
$ php artisan code:analyse
Bootstrap file vendor/autoload.php does not exist.
```
The help says:
```
…
  -a, --autoload-file=AUTOLOAD-FILE  Project's additional autoload file path [default: "/vagrant/project/vendor/autoload.php"]
…
```
and it's there:
```
$ ls -ld /vagrant/project/vendor/autoload.php
-rw-r--r-- 1 501 dialout 157 Jan 25 18:06 /vagrant/project/vendor/autoload.php
```
Also, I've phpstan and can run it:
```
$ vendor/bin/phpstan analyse --level=6 --configuration=phpstan.neon app
 101/573 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  17%
```
In my (existing!) `phpstan.neon` I've this:
```
$ head -n 2 phpstan.neon
parameters:
  bootstrap: vendor/autoload.php
```
When I remove the line, `larastan` works.

phpstan works either with the line present or absent.

For me a solution is easy: I can simply remove that line from the config file.

However, even if benign it seems to me larastan should still work; there's something magic going on which breaks this.

**Comment by szepeviktor** [comment]
Hello @mfn !

Try using absolute paths, see https://github.com/phpstan/phpstan/blob/master/README.md#configuration-variables

**Comment by mfn** [comment]
The reason it doesn't work out of the box that way is that larastan decides to run phpstan from it's vendor installation "cwd"; so any relative path in the `phpstan.neon` file suddenly is relative to this.

That's quite an interesting choice, given that when phpstan is run the first instinct is to run it from a projects root, like other software, e.g.:
- `./vendor/bin/phpstan` or
- `./vendor/phpstan/phpstan/bin/phpstan`

I'm not really complaining and the fix is easy (or: in my case I even don't need the specific line) but the users expectations aren't really met (=> IMHO 😉)

`\NunoMaduro\Larastan\Console\CodeAnalyseCommand` currently doesn't provide a way to _really_ refer to the `phpstan` binary, it's hardcoded in `\NunoMaduro\Larastan\Console\CodeAnalyseCommand::cmd`:
```php
        $params = [
            Artisan::phpBinary(),
            'phpstan',
            'analyse',
            implode(' ', $paths),
            $options,
        ];
```

My expectations would have been:
- cwd would default to project root (and not `$cwd = $this->laravel->basePath('vendor/phpstan/phpstan/bin');`)
- phpstan binary default would be `./vendor/phpstan/phpstan/bin/phpstan`

(I tested it that way and my unchanged phpstan.neon work immediately).

**Comment by szepeviktor** [comment]
There are already path-related issues open.

**Comment by ondrejmirtes** [comment]
Try running Larastan this way to see if it solves your problem: https://github.com/nunomaduro/larastan#usage-in-packages-for-laravel instead of `artisan code:analyse`.

**Comment by mfn** [comment]
> There are already path-related issues open.

@szepeviktor funny that you mention it, I immediately found https://github.com/nunomaduro/larastan/issues/47 which also contains my input regarding surprising behaviour.



> Try running Larastan this way to see if it solves your problem: https://github.com/nunomaduro/larastan#usage-in-packages-for-laravel instead of `artisan code:analyse`.

@ondrejmirtes jup, that works.

I just don't think it makes sense to force phpstan run from a cwd in practice no one will ran it from. The majority simply runs it from the project root.

**Comment by nunomaduro** [comment]
The `code:analyse` artisan command is no longer available. Therefore, this should be no longer an issue.

**Comment by mfn** [comment]
Smart decision 👏
