### ISSUE TITLE
Class 'Symfony\Component\VarDumper\Tests\Fixtures\NotLoadableClass' not found

### ISSUE THREAD

**Issue by Evil85** [nunomaduro/larastan#233]
- Larastan Version: master / 3fb8427cbd4ec886c609e1501923015bcd028324
- `--level` used:

### Description:
My Enviroment
Ubuntu 18.04
php7.1

I tried to analyze a Laravel 5.1 project.

PHP Fatal error:  Class 'Symfony\Component\VarDumper\Tests\Fixtures\NotLoadableClass' not found in /larastan/vendor/symfony/var-dumper/Tests/Fixtures/NotLoadableClass.php on line 5

**Comment by Evil85** [comment]
Thanks your guide, Viktor.

So this plugin coudn't analyze any project before Laravel 5.6 ?

**Comment by szepeviktor** [comment]
Larastan **may** be compatible with earlier Laravel version.

In that case you should hack your way through it.

All the best to you!
