### ISSUE TITLE
Class 'SwaggerFixures\stdClass' not found

### ISSUE THREAD

**Issue by Evil85** [nunomaduro/larastan#234]
- Larastan Version: master / 3fb8427cbd4ec886c609e1501923015bcd028324
- `--level` used:

### Description:
My Enviroment :
Ubuntu 18.04
Php 7.1

I tried to analyze my Laravel 5.5 project,

PHP Fatal error:  Class 'SwaggerFixures\stdClass' not found in /larastan/vendor/phpstan/phpstan/src/Broker/Broker.php(302) : eval()'d code on line 1

**Comment by szepeviktor** [comment]
How could you install Larastan in a Laravel 5.5 project?

**Comment by Evil85** [comment]
I cloned the repo and run composer install.

Ran phpstan from /larastan/vendor/bin with this way : 

./phpstan analyse --memory-limit=1024M /path/to/my_project

**Comment by szepeviktor** [comment]
Larastan is a [set of services](https://github.com/nunomaduro/larastan/blob/master/extension.neon#L18) on top of PHPStan.

If you run directly PHPStan please include our extension.neon.
