### ISSUE TITLE
FromRequest class say "Illuminate\Validation\ValidationException  : The given data was invalid."

### ISSUE THREAD

**Issue by hokutoasari** [nunomaduro/larastan#236]
- Larastan Version: 0.3.15
- `--level` used: 5 (default, and I tried `--level=1` also.)

### Description:

I run `$ php artisan code:analyse --debug -v` and I see following lines.

```
   Illuminate\Validation\ValidationException  : The given data was invalid.

  at /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php:126
    122|      * @throws \Illuminate\Validation\ValidationException
    123|      */
    124|     protected function failedValidation(Validator $validator)
    125|     {
  > 126|         throw (new ValidationException($validator))
    127|                     ->errorBag($this->errorBag)
    128|                     ->redirectTo($this->getRedirectUrl());
    129|     }
    130|

  Exception trace:

  1   Illuminate\Foundation\Http\FormRequest::failedValidation(Object(Illuminate\Validation\Validator))
      /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php:26

  2   Illuminate\Foundation\Http\FormRequest::validateResolved()
      /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php:30
```

### Laravel code where the issue was found:

May be this errors fire in following code. But I can't have confidence in that.

```php
use App\Http\Requests\Contracts\Admin\Authors\AuthorStoreRequest;

final class AuthorStoreUseCase implements AuthorStoreUseCaseInterface
{
    /**
     * @param AuthorStoreRequest $request
     * @return AuthorEntity
     */
    public function __invoke(AuthorStoreRequest $request): AuthorEntity
    {
        // snip
    }
}
```

The `App\Http\Requests\Contracts\Admin\Authors\AuthorStoreRequest` is just interface like following lines.

```php
interface AuthorStoreRequest extends BaseRequest
{
    /**
     * @return array
     */
    public function rules(): array;
}
```

The `BaseRequest` as just a interface. That was bind to following abstract class.

```php
use Illuminate\Foundation\Http\FormRequest;

/**
 * Class BaseRequest
 * @package App\Http\Requests
 */
abstract class BaseRequest extends FormRequest
{
    //
}
```

It just extends `FormRequest` class.

But I can't have confidence in that...

I will try to rewrite more simply my code, and to check the reproducibility in my local machine.

Do you have an idea how to fix these errors?

(And sorry my poor english.)

**Comment by szepeviktor** [comment]
> Larastan Version: 5.7.21

Could you state your *larastan* version?

**Comment by hokutoasari** [comment]
@szepeviktor Oh, sorry my mistake.

* Larastan Version: 0.3.15

is right.

And updated my first post.

**Comment by szepeviktor** [comment]
Thanks.

**Comment by yazeed** [comment]
Why am I getting this when I type `php artisan code:analyse`?

```
There are no commands defined in the "code" namespace.
```

**Comment by szepeviktor** [comment]
Using artisan is deprecated - maybe removed.
Please consider starting phpstan directly and configure in phpstan.neon
