### ISSUE TITLE
sentinel methods are not recognized

### ISSUE THREAD

**Issue by lorvent** [nunomaduro/larastan#237]
- Larastan Version: v0.3.15
- `--level` used: default

### Description:
When i use Cartalyst/sentinel package, it throws errors saying 
`Call to an undefined static method Cartalyst\Sentinel\Laravel\Facades\Sentinel::inRole()`

is there anything i do to supress this kind of errors?

**Comment by nunomaduro** [comment]
Just add PR to fix that: https://github.com/cartalyst/sentinel/pull/453.

You should wait until is merged.

**Comment by lorvent** [comment]
lol,
is it such a simple fix?

i am getting errors from following packages aswell

Maatwebsite\Excel
ConsoleTVs\Charts

**Comment by nunomaduro** [comment]
@lorvent Just commit then similar fix.
