### ISSUE TITLE
Put orchestra/testbench in require-dev

### ISSUE THREAD

**Issue by larsnystrom** [nunomaduro/larastan#238]
- Larastan Version: 0.3.15
- `--level` used: N/A

### Description:

Normally orchestra/testbench should be put in `require-dev` since it is used to run the tests of the package. Since larastan has it in `require` it affects the dependency tree of applications that depend on larastan. For example, I can't update to PHPUnit 8 because orchestra/testbench require PHPUnit 7, even though my application doesn't even use orchestra/testbench.

The same actually goes for `Mockery`, which is also a test library and should be put in `require-dev`.

### Laravel code where the issue was found:
N/A.

**Comment by nunomaduro** [comment]
@larsnystrom Larastan uses both when you are using Larastan to test your packages.

**Comment by pablorsk** [comment]
I agree with @larsnystrom.

For example, I'm not testing `nunomaduro/larastan` and on my library I like to use another version of `orchestra/testbench`. 

`orchestra/testbench` on this library is uses only for development; although it is also used in the development process of another applications.
