### ISSUE TITLE
Fix Lumen error

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#244]
```
 ------ ----------------------------------------------------------------------
  Line   app/Providers/AuthServiceProvider.php
 ------ ----------------------------------------------------------------------
  33     Cannot call method viaRequest() on Illuminate\Auth\AuthManager|null.
 ------ ----------------------------------------------------------------------
```

Can anybody land me a hand how to solve this one in Lumen?
https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L33

Now we test Lumen too in CI.

**Comment by szepeviktor** [comment]
@goodevilgenius ?

**Comment by goodevilgenius** [comment]
@szepeviktor Not sure. It seems to think that `$app['auth']` can be `Illuminate\Auth\AuthManager|null`. `AuthManager` has a `viaRequest` method, but of course `null` doesn't, which seems to be the problem.

But from my reading of the code, it's not possible for `$app['auth']` to be `null`.

The binding for `auth` is registered at https://github.com/laravel/lumen-framework/blob/87e7dcccda1b83ef0953253d03c056575308439e/src/Application.php#L270-L272

Or more precisely https://github.com/illuminate/auth/blob/master/AuthServiceProvider.php#L35-L42

So, the question is, why does it think it could be `null` as well?

**Comment by szepeviktor** [comment]
@ondrejmirtes Could it be a phpstan bug?

**Comment by ondrejmirtes** [comment]
@szepeviktor I don't know what `$app` is and who is defining the type of `$app['auth']` - maybe some dynamic method return type extension hooked onto `offsetGet`?

**Comment by szepeviktor** [comment]
`$app` is `\Illuminate\Contracts\Foundation\Application|\Illuminate\Foundation\Application`

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/ServiceProvider.php#L9-L14

It is not clear to me how it can be an [array] also.

**Comment by goodevilgenius** [comment]
In Lumen, it's actually `Laravel\Lumen\Application`. It doesn't extend, `Illuminate\Foundation\Application`, because `Illuminate\Foundation` is *only* in Laravel, and not Lumen.

It works as an array because `Illuminate\Foundation\Application` and `Laravel\Lumen\Application` extend `Illuminate\Container\Container`, which implements `ArrayAccess`.

See https://github.com/illuminate/container/blob/d65a58f5f8d9a6d3514ed2ca6c40822ad7f960ef/Container.php

`$app['auth']` works the same as `$app->make('auth')` (or `app('auth')`), which resolves `auth` by instantiating `AuthManager`.

**Comment by ondrejmirtes** [comment]
> It is not clear to me how it can be an [array] also.

It probably implements `ArrayAccess` interface.

I'm not too familiar with Larastan, but there's probably an extension that says that `$app->offsetGet('auth')` (which is the same as `$app['auth']`) can return `Illuminate\Auth\AuthManager|null`.

**Comment by szepeviktor** [comment]
> In Lumen, it's actually `Laravel\Lumen\Application`.

App\Providers\AuthServiceProvider extends Illuminate\Support\ServiceProvider

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/ServiceProvider.php

```php
    /**
     * The application instance.
     *
     * @var \Illuminate\Contracts\Foundation\Application|\Illuminate\Foundation\Application
     */
    protected $app;
```

@goodevilgenius Where do you see `Laravel\Lumen\Application`?

**Comment by goodevilgenius** [comment]
@szepeviktor

That DocBlock was written for Laravel, not Lumen.

`$app` is originally instantiated in `bootstrap/app.php`.

In Laravel, the line says:

```php
$app = new Illuminate\Foundation\Application(
    realpath(__DIR__ . '/../')
);
```

In Lumen, that line says:

```php
$app = new Laravel\Lumen\Application(
    realpath(__DIR__ . '/../')
);
```

Also, you would think that `Laravel\Lumen\Application` would implement `Illuminate\Contracts\Foundation\Application`, but it doesn't. There are only three or four methods they'd have to implement to be able to implement that interface, but it just isn't done.

**Comment by szepeviktor** [comment]
@goodevilgenius I was starting at the error: https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L33

it says `$this->app` which is - I think - a property of `Illuminate\Support\ServiceProvider`

Am I wrong?

**Comment by goodevilgenius** [comment]
@szepeviktor You are correct. But it's the same `$app` that's instantiated in `bootstrap/app.php`.

Each service provider is registered with the `register` method on `$app` in `bootstrap/app.php` in Lumen. It passes itself as the first parameter to the service provider's constructor, and that's where `$this->app` is set, from https://github.com/illuminate/support/blob/66a6ce7da82927f4278872a26b1f3c2e20d215cf/ServiceProvider.php#L37

So, `$this->app` in each service provider is the exact same `$app` from `bootstrap/app.php`, which in Laravel is an `Illuminate\Foundation\Application`, but in Lumen is a `Laravel\Lumen\Application`.

**Comment by szepeviktor** [comment]
I see what you mean. Maybe the code works that way.

What I was talking about are the contents of the PHPDocblock.
Do you see the difference?

**Comment by goodevilgenius** [comment]
@szepeviktor I do see the difference. My point is that that DocBlock was written for Laravel, and not Lumen. The DocBlock is wrong when used in Lumen. It could be right, if `Laravel\Lumen\Application` implemented `Illuminate\Contracts\Foundation\Application`, which it *could* easily do, but doesn't.

**Comment by szepeviktor** [comment]
Thank you @goodevilgenius 

How would you solve the issue? https://github.com/nunomaduro/larastan/issues/244#issue-410747438

**Comment by nunomaduro** [comment]
`v0.3.16` has been released and it fixes this.

**Comment by szepeviktor** [comment]
> fixes

:)
