### ISSUE TITLE
Eloquent\Model is recognized instead of class extending Model

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#246]
- Larastan Version: 0.3.15
- `--level` used: 2

### Description:

>   Call to an undefined method Illuminate\Database\Eloquent\Model::addMediaFromUrl().

### Laravel code where the issue was found:

```php
$artist->addMediaFromUrl();

# and

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class Artist extends Model implements HasMedia
```

**Comment by szepeviktor** [comment]
Is it a know error/duplicate issue?

**Comment by canvural** [comment]
How does the `$artist` variable initialized?

**Comment by szepeviktor** [comment]
`new Artist()`

**Comment by canvural** [comment]
Ok. So I think this is also related to #324. I'll open a PR today for that, then we'll see.

**Comment by szepeviktor** [comment]
Thank you very much!
