### ISSUE TITLE
[False positive] for Storage::put and UploadedFiles

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#250]
- Larastan Version: 0.3.15
- `--level` used: 5

### Description
I am getting a false positive for `Storage::put` with uploaded files:

```
Parameter #2 $contents of method Illuminate\Contracts\Filesystem\Filesystem::put() 
expects resource|string,
array<Illuminate\Http\UploadedFile>|Illuminate\Http\UploadedFile|null given.
```

As you can see, the Laravel code already does a check for Uploaded files:

https://github.com/laravel/framework/blob/c821cbf6f20fca4c50aa9d8fb08f71425afc07b8/src/Illuminate/Filesystem/FilesystemAdapter.php#L188-L191

I guess I could just call `putFile` directly to get rid of the error, but it's not available in the `Filesystem` contract. Also: using `put` with files changes the return type from `bool` to `string`, so there's that.

### Laravel code where the issue was found

```php
public function store(Request $request)
{
    $image = $request->file('file');

    Storage::put('images', $image);
}
```

**Comment by szepeviktor** [comment]
Thank you for the report.

Please do send a PR to Laravel: `resource|string|File|UploadedFile`
