### ISSUE TITLE
Illuminate\Support\Collection is not deteced as Countable

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#252]
- Larastan Version: #.#.#
- `--level` used: 2

### Description

```
Access to an undefined property Illuminate\Support\Collection::$count.
```

```php
namespace Illuminate\Support;

class Collection implements ArrayAccess, Arrayable, Countable, IteratorAggregate, Jsonable, JsonSerializable
{
```

http://php.net/manual/en/countable.count.php

### Laravel code where the issue was found

```php
        $results = DB::table('artworks')->selectRaw("
            ifnull(case
                when meta->\"$.price.{$currency}\" between 0 and {$step} then 1
                when meta->\"$.price.{$currency}\" between {$step} and ({$step} * 2) then 2
                when meta->\"$.price.{$currency}\" between ({$step} * 2) and ({$step} * 3) then 3
                when meta->\"$.price.{$currency}\" between ({$step} * 3) and ({$step} * 4) then 4
            end, 0) as category, count(id) as count"
        )->where('database_id', $this->database->id)
        ->whereNotNull('deleted_at')->groupBy('category')->get();

        while ($start < $max->price) {
            $data['labels'][] = $start . " - " . ($start + $step);
//   -------- HERE --------
            $data['datasets'][0]['data'][] = $results->firstWhere('category', $category)->count ?? 0;
            $category++;
            $start += $step;
        }
```

**Comment by szepeviktor** [comment]
It turns out "count" is an SQL column: `count(id) as count`

What to do now?

**Comment by canvural** [comment]
The error is correct here. `Collection` does not have `count` property. It has `count` method.

**Comment by szepeviktor** [comment]
@canvural Is there a laravelish way to tell phpstan what are the SQL fields?
Which later turn out to be PHP properties of the `Collection`.

**Comment by canvural** [comment]
I don't understand. What SQL fields are you talking about?

**Comment by szepeviktor** [comment]
In the above code there is `selectRaw("... as category, count(id) as count")`, so category and count.
How can I tell phpstan that the `Collection` will have these properties?

**Comment by canvural** [comment]
But that's still not true. `Collection` will not have those properties. It will just have an array of objects. And those objects will have properties.

I don't know if PHPStan supports specifying properties on plain `object` Or you can create an object to represent that data, and typehint that.

**Comment by szepeviktor** [comment]
I see!
I've just created such a class yesterday https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/class-wp-nav-menu-item.php
