### ISSUE TITLE
Catch the live dd() found in code.

### ISSUE THREAD

**Issue by dakshhmehta** [nunomaduro/larastan#253]
Hello,

I am Daksh from Laravel Live Meetup, as asked in question and as you mentioned to send PR for cathcing dd.

Scenario:
I had a site where my team was using dd() function to debug something. Normally, they either comment it out or completely remove it. However, somehow in code review, I missed that and despite using Larastan, production environment got messed.
Solution: It's awesome if dd() function found can be caught if it lives within the code and is getting executed, that means if it is commented, I guess we can just throw a warning but still passes (if that's supported by phpstan)

I will be glad to work on this PR if you can brief me on how do I get started.

Thanks,
Daksh

**Comment by ondrejmirtes** [comment]
It's very simple. Follow the PHPStan's README: https://github.com/phpstan/phpstan#custom-rules

Create a Rule that is registered to FuncCall node and check if the name of the called function is `dd`. Return an array with the error message if it is.

**Comment by szepeviktor** [comment]
A better way: use PHPCS!

**Comment by dakshhmehta** [comment]
Sounds great. Thanks.
