### ISSUE TITLE
Model::on()->firstOrFail has unspecific return type

### ISSUE THREAD

**Issue by mr-feek** [nunomaduro/larastan#255]
- Larastan Version: 0.3.13
- `--level` used: 3

### Description
MyModel::on('conection')->firstOrFail() should return an instance of `MyModel`

Expected: 
no errors

Actual:
`MyModel::on('conection')->firstOrFail() should return MyModel but returns Illuminate\Database\Eloquent\Model`

### Laravel code where the issue was found

here's an example failing test case (put in `ModelExtension.php`)

```
public function testFirstOrFail(): Thread
{
        return Thread::on()->firstOrFail();
}
```

**Comment by szepeviktor** [comment]
Thank you. We have several issue on this, e.g. #246

**Comment by mr-feek** [comment]
this test case passes when the laravel docblock is changed to just be `static` https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Builder.php#L442

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?
