### ISSUE TITLE
Call to an undefined method Illuminate\Database\Query\Builder::orWhereHas().

### ISSUE THREAD

**Issue by adminfriso** [nunomaduro/larastan#256]
- Larastan Version: v0.3.15
- `--level` used: 2

### Description

 51     Call to an undefined method Illuminate\Database\Query\Builder::orWhereHas().                     
on the line with the -->

In the api description the method does exist.
I think this is a false positive.

Strange thing this actually is line 56

this also creates an issue on the same line 
51     Method Illuminate\Database\Query\Builder::dynamicWhere() invoked with 2 parameters, 1 required. 

### Laravel code where the issue was found

```php


        $duties = new Duty();
        $duties = $duties->sortable();

        // Apply search
        if ($request->filled('search')) {
            $search = '%' . $request->get('search') . '%';
51          $duties->whereHas(
                'customer',
                function ($query) use ($search) {
                    $query->where('company_name', 'LIKE', $search);
                }
56 -->      )->orWhereHas(
                'type',
                function ($query) use ($search) {
                    $query->where('title', 'LIKE', $search);
                }

```

**Comment by szepeviktor** [comment]
Thank you.

We have other Eloquent false positives.

**Comment by KeithTurkowski** [comment]
I get this error when wrapping orWhereHas() inside of whereNested(), but it works fine wrapped inside of where()

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?

**Comment by adminfriso** [comment]
works
