### ISSUE TITLE
In Expect.php line 378:Unexpected option 'services › relativePathHelper › factory'.  

### ISSUE THREAD

**Issue by zhangrenjie** [nunomaduro/larastan#258]
- Larastan Version: #.#.#
- `--level` used:

### Description
In Expect.php line 378:
                                                                
  Unexpected option 'services › relativePathHelper › factory'.  
                                                                

### Laravel code where the issue was found

```php

```

**Comment by jankal** [comment]
Related to #257 which is not solved but closed...

**Comment by jankal** [comment]
I do also encounter this issue on Laravel v5.8.7 with larastan v0.3.15. I have to note that I use laravel spark inside my project.

**Comment by szepeviktor** [comment]
Hello @jankal !

Please see the comments in https://github.com/phpstan/phpstan/issues/2033

If you cannot solve the problem please get back to me.
