### ISSUE TITLE
Larastan broke config() on tests, by orchestra

### ISSUE THREAD

**Issue by lintaba** [nunomaduro/larastan#259]
- Larastan Version: 0.3.15
- `--level` used: n/a

### Description

Larastan included orchestra's core, and somehow even replaced the original environment with orchestra during testing, which replaces all config('') with its own.

**Comment by szepeviktor** [comment]
Hello @lintaba !

Are you talking about orchestra/testbench-core conflicting with your testing environment?

Could you give use details?

**Comment by lintaba** [comment]
Hey @szepeviktor,

Exactly. Without larastan, the following snippet runs perfectly. With larastan, it fails. I've backtraced till I found that for some reason my testing environment got replaced with orchestra, and that its only larastan's dependency.

```
class TestCase extends \Illuminate\Foundation\Testing\TestCase {
   public function testConfig(){
    $this->assertNotNull(config('myConfig'));
  }
}
```

`config/myConfig.php`
```
<?php return [];
```

**Comment by canvural** [comment]
`orchestra` is no longer a dependency of Larastan. So this issue can be closed.
