### ISSUE TITLE
Redis: Call to an undefined static method

### ISSUE THREAD

**Issue by Xethron** [nunomaduro/larastan#262]
- Larastan Version: v0.3.16
- `--level` used: 2

### Description
When using the Redis Facade, it complains about a call to an undefined static method.

### Laravel code where the issue was found
Using the following code:
```php
Redis::setNx('key', 'value');
Redis::get('key');
Redis::del('key');
```
larastan produced:
```
Call to an undefined static method Illuminate\Support\Facades\Redis::setNx().
Call to an undefined static method Illuminate\Support\Facades\Redis::get().
Call to an undefined static method Illuminate\Support\Facades\Redis::del().
```

I tried changing it to:
```php
Redis::connection()->setNx('key', 'value');
Redis::connection()->get('key');
Redis::connection()->del('key');
```
But I still got:
```
Call to an undefined method Illuminate\Redis\Connections\Connection::setNx().
Call to an undefined method Illuminate\Redis\Connections\Connection::get().
Call to an undefined method Illuminate\Redis\Connections\Connection::del().
```

---
# Workaround
The only workaround I found was to not use the magic methods like this:
```php
Redis::connection()->command('setNx', ['key', 'value']);
Redis::connection()->command('get', ['key']);
Redis::connection()->command('del', ['key']);
```

**Comment by canvural** [comment]
This can be fixed by changing the class docblock in `Redis` facade. You can open a PR in [Laravel](https://github.com/laravel/framework) repo.

**Comment by elijahchancey** [comment]
We're using larastan 0.4.3 and laravel 5.8.35. 

When we use something like:
`$redis->exists('key')`

We get larastan errors like:
`Call to an undefined method Illuminate\Redis\Connections\Connection::exists().`

I'm happy to open either of the aforementioned PRs. Do you think I should open up a PR with Laravel, phpstan, or both?

**Comment by szepeviktor** [comment]
The magic `__call`!
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Redis/Connections/Connection.php#L209

In Laravel docblock you may not list all non locally declared function.
But in a new Larastan extension you may succeed.

**Comment by elijahchancey** [comment]
We'll upgrade to laravel 6 and give it a go. Thanks!

**Comment by harrisdt15f** [comment]
I also ahead with this problem, please someone guide me how to solve it.
