### ISSUE TITLE
Package is not compatible with lumen 5.6

### ISSUE THREAD

**Issue by leandrodaf** [nunomaduro/larastan#265]
- Larastan Version: **0.3.16.**
- Lumen Version: **5.6.\***

### Description
![Screenshot from 2019-05-08 11-06-11](https://user-images.githubusercontent.com/12107458/57381452-55759580-7181-11e9-849b-1bafd54c3c2b.png)

**Comment by szepeviktor** [comment]
Strange https://github.com/nunomaduro/larastan/blob/master/composer.json#L17-L23

**Comment by szepeviktor** [comment]
I think I've met with this path.storage issue.

**Comment by szepeviktor** [comment]
@leandrodaf Could you please follow up in that issue?

**Comment by j3rrey** [comment]
created a pr working fine here https://github.com/nunomaduro/larastan/pull/268/commits/cd1b1ad83d3e7ad274d8a6e2e291e5b8bdd8f071
