### ISSUE TITLE
phpstan/phpdoc-parser no longer works with larastan

### ISSUE THREAD

**Issue by HarleyScotcher** [nunomaduro/larastan#271]
- Larastan Version: 3.1.16
- `--level` used: no

### Description

PHPStan/phpdoc-parser version 0.3.4 has broken Larastan. This issue directed me to resolve this issue here: https://github.com/phpstan/phpdoc-parser/issues/29

### Laravel code where the issue was found

Symfony\Component\Debug\Exception\FatalThrowableError : Argument 7 passed to class@anonymous::create() must be of the type string or null, boolean given, called in /vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php on line 83

at /private/var/folders/23/25rt362577n6ck0zdpzcbz1r0000gn/T/phpstan/cache/nette.configurator/Container_5bbaf41769.php:1811
1807| $this->container = $container;
1808| }
1809|
1810|

1811| public function create(
1812| PHPStan\Reflection\ClassReflection $declaringClass,
1813| ?PHPStan\Reflection\ClassReflection $declaringTrait,
1814| PHPStan\Reflection\Php\BuiltinMethodReflection $reflection,
1815| array $phpDocParameterTypes,
Exception trace:

1 class@anonymous/private/var/folders/23/25rt362577n6ck0zdpzcbz1r0000gn/T/phpstan/cache/nette.configurator/Container_5bbaf41769.php0x1086a4166::create(Object(PHPStan\Reflection\ClassReflection), Object(NunoMaduro\Larastan\Methods\Macro))
/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php:83

2 NunoMaduro\Larastan\Methods\Pipes\Macros::handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163

Please use the argument -v to see more details.

```php

```

**Comment by szepeviktor** [comment]
Maybe https://github.com/nunomaduro/larastan/pull/269 ?

**Comment by nunomaduro** [comment]
This has been fixed on the version `v0.3.17`.
