### ISSUE TITLE
Query\Builder::dynamicWhere() expects array, string given with Laravel 5.8.23

### ISSUE THREAD

**Issue by bolechen** [nunomaduro/larastan#272]
- Larastan Version: v0.3.17
- `--level` used:5

### Description
When upgrade to Laravel 5.8.23, I have this error

```
Parameter #1 $parameters of method Illuminate\Database\Query\Builder::dynamicWhere() expects array, string given.
```

### Laravel code where the issue was found

```php
$item = Item::whereUuid($item_uuid)->first();
```

```php
    public static function getByOpenid(string $openid)
    {
        return static::whereWeixinOpenid($openid)->first();
    }
```

**Comment by bolechen** [comment]
When i down laravel to 5.8.21, the error is gone.
may be ref this pull https://github.com/laravel/framework/pull/28734

**Comment by szepeviktor** [comment]
I happened between 5.8.19 and 5.8.24

**Comment by olivier-acid** [comment]
Hello, now have the same issue on Laravel 6.0 with astrotomic/laravel-translatable

**Comment by spaceemotion** [comment]
@szepeviktor Sorry, but the error is back for me with latest laravel (6.3) and larastan versions:

```php
Commission::query()
    ->whereNotNull('reviewed_at')
    ->whereHas('user')
    ->get();
```

Curiously enough, if I leave out either of the `where()` calls, the error is gone.

**Comment by szepeviktor** [comment]
@spaceemotion I see.

Please open a new issue linking this one.
Thank you!
