### ISSUE TITLE
Call to an undefined scope

### ISSUE THREAD

**Issue by brendt** [nunomaduro/larastan#28]
Not sure if this is fixable.

The error is this

```
Call to an undefined method Illuminate\Database\Eloquent\Builder::whereResidence()
```

The calling code is this

```php
InvoiceLabel::query()
    ->whereResidence($this->residence)
    ->whereId($parameters['id'])
    ->firstOrFail();
```

The `::query()` part returns `Illuminate\Database\Eloquent\Builder` per its doc blocks, but actually returns the concrete model.

**Comment by szepeviktor** [comment]
@nunomaduro While running v0.1.8 with `--level=2` I've got this:

```php
    /**
     * Filter only the trashed exhibitions.
     *
     * @param  bool|string  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function trashed($value = false)
    {
        return  $value == 'true' ? $this->builder->onlyTrashed() : $this->builder;
    }
```

*Call to an undefined method Illuminate\Database\Eloquent\Builder::onlyTrashed().*



`$this->builder` is a `\Illuminate\Database\Eloquent\Builder`.

**Comment by brendt** [comment]
@nunomaduro , it seems fixed! I had to mark `0.2.0@dev` though, only `0.1.5` and below were seen by composer as "stable".

**Comment by brendt** [comment]
@nunomaduro Do you, by any chance; have an idea if this is also fixable in PHPStorm? It works with PHPStan now, but PHPStorm also shows the error. I know this is not related to this package, but maybe you have an idea?

**Comment by bhulsman** [comment]
@nunomaduro Something might still be causing an issue here:

```
$member = Member::where(/* some condition */)->firstOrFail();
$contact = $member->contacts()->create(/* some data */);
```

Yields the following error: "Call to an undefined method Illuminate\Database\Eloquent\Model::contacts()."

Changing `firstOrFail` to `first` solves the error.

**Comment by tsushant** [comment]
@nunomaduro Running 0.5.2 with --level=5. I am still getting this for a local scope:
` Call to an undefined method Illuminate\Database\Eloquent\Builder::search()`

```
    public function scopeSearch($query, $search)
    {
        if ($search) {
            return $query->where('name', 'like', '%'.$search.'%');
        }

        return $query;
    }
```
`$this->model->search(request('search'))->paginate();`

**Comment by szepeviktor** [comment]
@tsushant Thank you for your report.

Please try opening a new issue :) waking up a 2 year old one makes us react slower.
