### ISSUE TITLE
False positives with Facade Fakes

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#281]
- Larastan Version: 0.3.17
- `--level` used: 1

### Description

When you use Facade fakes it gives false positives.

For example following code

```php
Event::fake([UserActivated::class]);
...
Event::assertDispatched(UserActivated::class);
```

gives `Call to an undefined static method Illuminate\Support\Facades\Event::assertDispatched().`

This one is tricky. I'm not sure how it can be solved.

Currently I solved it by adding `#Call to an undefined static method Illuminate\\Support\\Facades\\[a-zA-Z0-9\\_]+::assert[a-zA-Z0-9_]+#` to my `ignoreErrors`

**Comment by szepeviktor** [comment]
> Currently I solved it by adding `#Call to an undefined static method Illuminate\\Support\\Facades\\[a-zA-Z0-9\\_]+::assert[a-zA-Z0-9_]+#` to my `ignoreErrors`

Very good!

It can be solved by developing another PHPStan service: https://github.com/nunomaduro/larastan/blob/master/extension.neon#L20
