### ISSUE TITLE
null check?

### ISSUE THREAD

**Issue by viezel** [nunomaduro/larastan#282]
- Larastan Version: 0.3.17 (latest)
- `--level` used: 1

### Description

In the following code larastan outputs: `Variable $user might not be defined`
If I change it to `!isset($user)` then larastan is ok with it - but isset has various downsides. 

Why is a regular null check not ok? 

### Laravel code where the issue was found

```php
$user = $this->auth->guard()->user();

 if (null === $user) {
    throw new SomeException;
}
```

**Comment by ondrejmirtes** [comment]
It's not about null check, it's about the variable not existing because it's created probably in some condition. Also, this issue is not specific to Larastan, but to PHPStan.

**Comment by ondrejmirtes** [comment]
It's basically something like this: https://phpstan.org/r/f9c61726-8f06-46d3-88c3-7900c41257a8

**Comment by viezel** [comment]
of course 🤦‍♂  you are right. Thank you.
