### ISSUE TITLE
The logic in getProjectClasses is dangerous

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#284]
@ondrejmirtes said

>  Anyway, the logic in getProjectClasses is dangerous and shouldn't be done this way...

See #273

**Comment by szepeviktor** [comment]
@nunomaduro Could you contribute a little when you get back from SF?

**Comment by nunomaduro** [comment]
@szepeviktor You don't work that much with Laravel anymore, sorry.

**Comment by nunomaduro** [comment]
@szepeviktor Would be cool find people that would like to maintain this project.

**Comment by CyberiaResurrection** [comment]
@nunomaduro , @szepeviktor, @canvural , since #318 has been rolled up, can this issue be closed?

**Comment by canvural** [comment]
Sure. Thanks for the PR :+1:

**Comment by nunomaduro** [comment]
@canvural Fell free to perform NON breaking new releases: https://github.com/nunomaduro/larastan/blob/master/RELEASE.md. The next one should be `v0.4.2`.

**Comment by canvural** [comment]
@nunomaduro I can't push directly to master, so I can't make new releases. How do you wanna do that? Should I open PR for CHANGELOG, and then try to use the GitHub's release tool?

**Comment by szepeviktor** [comment]
@canvural Even is you work on a project *alone* please consider not pushing to master.

I could open a PR for you regarding the changelog :)

**Comment by canvural** [comment]
@szepeviktor I already have the changes I can create the PR. 

But to create the tags etc. we still need to push it to master. I don't see a downside. Also, that's what written in the release document.

**Comment by szepeviktor** [comment]
I think @nunomaduro has more liberal view on project management than I do.

We may create a tag on the release page https://github.com/nunomaduro/larastan/releases/new
