### ISSUE TITLE
Scopes returns void

### ISSUE THREAD

**Issue by AJenbo** [nunomaduro/larastan#286]
- Larastan Version: 0.3.16
- `--level` used: 7

### Description

> Result of static method App\Models\User::scopeIsAdmin() (void) is used.

The return type should be `Illuminate\Database\Eloquent\Builder` since the call is to the magic `isAdmin` and not the actual `scopeIsAdmin`.

### Laravel code where the issue was found

```php
        $admin = User::isAdmin()->findOrFail($id);
```

**Comment by szepeviktor** [comment]
Thank you for report.

We have partial Eloquent coverage. PRs are welcome!

**Comment by canvural** [comment]
This should be fixed in `master` branch. @AJenbo  Can you check and confirm?

**Comment by AJenbo** [comment]
Unfortunately I no longer have access to the relevant codebase.
