### ISSUE TITLE
$queryBuilder->leftJoin()->get() returns wrong Collection

### ISSUE THREAD

**Issue by AJenbo** [nunomaduro/larastan#287]
- Larastan Version: 0.3.16
- `--level` used:7

### Description
When a leftJoin is used with the query builder it will be seen as returning `Illuminate\Support\Collection` instead of `Illuminate\Database\Eloquent\Collection`.
If you leave out the `leftJoin` it actually detects the correct type.

### Laravel code where the issue was found

```php
$user->clients()->leftJoin('keywords', 'keywords.keyword_group_id', '=', 'keyword_groups.id')->get();
```

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?

**Comment by AJenbo** [comment]
Sorry I no longer have access to the affected source.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by canvural** [comment]
OK. So I'm closing this.
