### ISSUE TITLE
App\{Model}::$timestamps is detected as an array

### ISSUE THREAD

**Issue by sera527** [nunomaduro/larastan#288]
- Larastan Version: 0.3.17 
- `--level` used: 5

### Description

Property App\{Model}::$timestamps (array) does not accept default value of type false.

Laravel documentation:

> By default, Eloquent expects created_at and updated_at columns to exist on your tables. If you do not wish to have these columns automatically managed by Eloquent, set the  $timestamps property on your model to false
[https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions](documentation)

### Laravel code where the issue was found

```php
class Profile extends Model
{
    public $timestamps = false;
}
```

**Comment by ondrejmirtes** [comment]
The phpDoc for the property should probably be updated in Laravel itself.

**Comment by szepeviktor** [comment]
Is it this timestamps?

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Concerns/HasTimestamps.php#L9-L14

**Comment by ondrejmirtes** [comment]
So either it's a property `$timestamp` somewhere in Laravel that has `array` typehint, or it's this property and Larastan is doing something that makes PHPStan think it's an `array`.

**Comment by sera527** [comment]
I am very sorry. This is my mistake.

**Comment by szepeviktor** [comment]
No problem.

Feel free to report if you benefit from it.
