### ISSUE TITLE
Using larastan without artisan

### ISSUE THREAD

**Issue by pablorsk** [nunomaduro/larastan#292]
- Larastan Version: 0.3.18
- `--level` used: max

### Description
Sometimes we don't have avaiable `php artisan`, for example when we are building another library. Then, we can include on `.neon` config file `vendor/nunomaduro/larastan/extension.neon` file.
But, larastan extension uses `services` that call `config` of laravel.

### Laravel code where the issue was found

```
php -d memory_limit=4G ./vendor/bin/phpstan analyse -l 7 -c myphpstan.src.neon app --debug

/app/app/ExternalApp.php

Fatal error: Uncaught Error: Call to a member function get() on null in /app/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php:71
Stack trace:
#0 /app/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php(42): NunoMaduro\Larastan\Methods\Pipes\Mixins->getMixinsFromClass(Object(PHPStan\Broker\Broker), Object(PHPStan\Reflection\ClassReflection))
#1 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): NunoMaduro\Larastan\Methods\Pipes\Mixins->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
#2 /app/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php(91): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
#3 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): NunoMaduro\Larastan\Methods\Pipes\Macros->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
#4 /app/vendor/nunomaduro/larastan/src/Methods/Pipes/SelfClass.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( in /app/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php on line 71

```

**Comment by ondrejmirtes** [comment]
If you don't override the `bootstrap` in your `phpstan.src.neon` then it will work.

The solution would be to move Larastan's bootstrap from `bootstrap` key to `autoload_files`.

**Comment by pablorsk** [comment]
Thanks @ondrejmirtes!

#### Solution

```php
// my-phpstan-bootstrap.php
require 'vendor/nunomaduro/larastan/bootstrap.php';
```

**Comment by pablorsk** [comment]
By the way, could the `HasContainer.php` file could be have an uncontrolled error?

For example when ReflectionException, BindingResolutionException or NotFoundExceptionInterface ocurr.

Check this code (with a proposed solution) https://github.com/pablorsk/larastan/commit/9532519dab9463ce756f05b23b23eec0f249417c#diff-fbf6f38400be348eeeea812bc383eb0bL63

**Comment by szepeviktor** [comment]
See https://github.com/nunomaduro/larastan#usage-in-packages-for-laravel

**Comment by pablorsk** [comment]
Thanks @szepeviktor, I see that text, my problem was like @ondrejmirtes says: `bootstrap` overwrited.
