### ISSUE TITLE
Improvement: remove orchestra dependency

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/larastan#295]
The addition of the `orchestra` dependency cause too many issues. https://github.com/nunomaduro/larastan/issues/259 https://github.com/nunomaduro/larastan/pull/247 and many others.

**Goal**: 

1. Remove the dependency `orchestra/testbench` here.
2. Add the dependency `orchestra/testbench` to the suggest on composer, and update the readme explaining if you are using `larastan` for packages you need to install this dependency.

> After this feature we need to release a major version.

**Comment by mfn** [comment]
Ah, interesting, I was just wondering today why I could not run larastan with Laravel 6.0.

My failing build https://travis-ci.org/rebing/graphql-laravel/jobs/574566750 at the end says:
> nunomaduro/larastan v0.3.21 requires orchestra/testbench ^3.6

But I've to be honest, the composer dependency output is SO convoluted, I really don't know what I'm looking for and whether this is really the cause; just a guess for now.

**Comment by mfn** [comment]
> 2\. Add the dependency `orchestra/testbench` to the **suggest** on composer

But doesn't _this_ package require orchestra for its own tests?

Shouldn't it be rather moved to `require-dev`?

**Comment by ondrejmirtes** [comment]
@mfn It isn't just for tests. It sets up the application for Laravel package development.

**Comment by mfn** [comment]
> It sets up the application for Laravel package development.

Oh, sorry. I was not really aware of it. I only know this package for "providing a Laravel compatible test runner for the package".

I'll see myself out before adding too much noise here ;)

**Comment by szepeviktor** [comment]
@mfn Your comments are welcome.

**Comment by martijngastkemper** [comment]
I've made a PR (#304) with an alternative solution. Not removing the requirement, but add additional versions to the constraint.
