### ISSUE TITLE
PHP 7.4 and 8 support

### ISSUE THREAD

**Issue by kylekatarnls** [nunomaduro/larastan#302]
- Larastan Version: 5.8/6.0

### Description

larastan (or at least its unit tests) is not PHP 7.4 ready.

### Laravel code where the issue was found

https://travis-ci.org/kylekatarnls/larastan/jobs/574811156#L313

There will be changes on closures in PHP 7.4/8 that will impact Laravel macros. To anticipate the impact on larastan. 7.4snapshot and nightly versions of PHP should be added in Travis-CI but right now it throws errors.

**Comment by ondrejmirtes** [comment]
FYI PHPStan itself is PHP 7.4-ready since 0.11.13 released a week ago.

**Comment by ondrejmirtes** [comment]
And declaring support for PHP 8 now does not make sense, no one knows what PHP 8 will be like.

**Comment by kylekatarnls** [comment]
Testing PHP 8 in Travis-CI (even if you allow failure) gives you hints of what to watch. It helped us to discover earlier the macros problem:

https://github.com/laravel/framework/pull/29482
https://github.com/php/php-src/pull/4548

**Comment by szepeviktor** [comment]
Done in #306
