### ISSUE TITLE
Call to an undefined method Illuminate\Contracts\Auth\Factory::xxx()

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/larastan#309]
- Larastan Version: 0.3.21
- `--level` used: default/not set

### Description

>  53     Call to an undefined method `Illuminate\Contracts\Auth\Factory::check()`.  
>  53     Call to an undefined method `Illuminate\Contracts\Auth\Factory::user()`.  
>  80     Call to an undefined method `Illuminate\Contracts\Auth\Factory::login()`.   

### Laravel code where the issue was found

```php
auth()->check(); 
auth()->user();
auth()->login();
```

This is only for example, I get this error everywhere where I use `auth()->xxx()`.

**Comment by szepeviktor** [comment]
Could it be related to https://github.com/nunomaduro/larastan/pull/254 ?

**Comment by Gummibeer** [comment]
It's definitely related to #44 just opened this one because the issue was closed and the PR merged.

**Comment by cosmok** [comment]
\Illuminate\Contracts\Auth\Factory::class resolves to \Illuminate\Auth\AuthManager::class see [1](#k71), so in the AuthExtension Helper  [2](#k72), we could return AuthManager ?

<a name="k71"></a>  https://github.com/laravel/framework/blob/b3bc1e05622fbb13ca54f30525773c462d310b89/src/Illuminate/Foundation/Application.php#L1151

<a name="k72"></a> https://github.com/nunomaduro/larastan/blob/559fd2bedc46e0795ecf3dc1f678978f4feb3dcc/src/ReturnTypes/Helpers/AuthExtension.php#L45
