### ISSUE TITLE
Undefined property Application::$request.

### ISSUE THREAD

**Issue by brendt** [nunomaduro/larastan#31]
```
Access to an undefined property Illuminate\Contracts\Foundation\Application::$request.
```

This is the calling code, in a service provider.

```
$this->app->request->getHost()
```

**Comment by brendt** [comment]
Hi Nuno, this issue still seems to be there in 0.2.0:

```
68     Cannot access offset 'docs.navigation' on Illuminate\Contracts\Foundation\Application.
```

**Comment by nunomaduro** [comment]
@brendt Hummmmmmm.

Do you mind of performing a `composer update nunomaduro/larastan` and double check it?

If the problem is still there: When `docs.navigation` is registered on the container? Seems to me that service is bound into the container outside to bootstrap `life-cycle` of laravel.

**Comment by brendt** [comment]
It's gone now, I'm on 0.2.3. FYI, the parameter was read from `$this->app` in the `boot` method of a service provider. Seems to work, so great! 🌟
