### ISSUE TITLE
Eloquent\Collection::map()'s return type

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/larastan#310]
- Larastan Version: #.#.#
- `--level` used:

### Description
>   17     Call to an undefined method `Illuminate\Support\Collection::makeHidden()`. 

The doc-tag of `\Illuminate\Database\Eloquent\Collection::map()` says `@return \Illuminate\Support\Collection|static` - so it warns me for the case that the `map()` returns a base collection?

### Laravel code where the issue was found

```php
UserSession::with('user')->get()->map(function (UserSession $userSession) {
        $userSession->setAttribute('user_email', $userSession->user->email);
        $userSession->setAttribute('user_name', $userSession->user->full_name);

        return $userSession;
})->makeHidden('user')
```

**Comment by canvural** [comment]
Where is `makeHidden` defined? Is it a custom Collection macro?

**Comment by Gummibeer** [comment]
No, it's a default Laravel eloquent collection method.

https://laravel.com/docs/5.8/eloquent-serialization#hiding-attributes-from-json

https://github.com/illuminate/database/blob/fba945616f6f80cf91ea3bf73c55f43ffe3cc6ba/Eloquent/Collection.php#L381-L384

**Comment by canvural** [comment]
Ah, sorry my bad. So it thinks it returns `Illuminate\Support\Collection` not `Illuminate\Database\Eloquent\Collection`

I made a fix for the return type of `get`. I'll open the PR today. Then we'll see :+1:

**Comment by spaceemotion** [comment]
While https://github.com/laravel/framework/pull/30239 got merged into 6.3 I am seeing the same with a get() call on Eloquent queries. Testing a few things out this hopefully gets resolved with https://github.com/nunomaduro/larastan/pull/325 as it only happens when using where statements.

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?

**Comment by spaceemotion** [comment]
I am no longer seeing the issue with dev-master.

**Comment by nunomaduro** [comment]
Thanks @spaceemotion ! Good job @canvural
