### ISSUE TITLE
Unable to install - composer error

### ISSUE THREAD

**Issue by rtrzebinski** [nunomaduro/larastan#312]
- Larastan Version: 0.4.0
- `--level` used: none
- Laravel v5.8.23

### Description

```
$ composer require --dev nunomaduro/larastan
Using version ^0.4.0 for nunomaduro/larastan                                                            
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                           
Package operations: 1 install, 0 updates, 0 removals
  - Installing nunomaduro/larastan (v0.4.0): Loading from cache
nunomaduro/larastan suggests installing orchestra/testbench (^3.6)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In InputDefinition.php line 203:
                                                                               
  Argument 1 passed to _HumbugBoxc6397e257f28\Symfony\Component\Console\Input  
  \InputDefinition::addOption() must be an instance of _HumbugBoxc6397e257f28  
  \Symfony\Component\Console\Input\InputOption, instance of Symfony\Component  
  \Console\Input\InputOption given, called in /Users/robert/projects/cornerst  
  one/vendor/nunomaduro/larastan/src/Console/OptionsResolver.php on line 77    
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

### Laravel code where the issue was found

```php

```

**Comment by nunomaduro** [comment]
Can you clean your vendor and try again?

No issues here: ```➜ composer require --dev nunomaduro/larastan   
Using version ^0.4.0 for nunomaduro/larastan
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.5.1): Loading from cache
  - Installing phpstan/phpdoc-parser (0.3.5): Loading from cache
  - Installing nette/utils (v3.0.1): Loading from cache
  - Installing nette/schema (v1.0.0): Loading from cache
  - Installing nette/finder (v2.5.0): Loading from cache
  - Installing nette/robot-loader (v3.2.0): Loading from cache
  - Installing nette/php-generator (v3.2.3): Loading from cache
  - Installing nette/neon (v3.0.0): Loading from cache
  - Installing nette/di (v3.0.1): Loading from cache
  - Installing nette/bootstrap (v3.0.0): Loading from cache
  - Installing jean85/pretty-package-versions (1.2): Loading from cache
  - Installing composer/xdebug-handler (1.3.3): Loading from cache
  - Installing phpstan/phpstan (0.11.15): Loading from cache
  - Installing nunomaduro/larastan (v0.4.0): Loading from cache
nette/bootstrap suggests installing tracy/tracy (to use Configurator::enableTracy())
nunomaduro/larastan suggests installing orchestra/testbench (^3.6)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: nunomaduro/larastan
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

**Comment by rtrzebinski** [comment]
@nunomaduro Thank you for such a quick answer. I dropped `vendor` folder and trying again, this is the error now:

```
$ composer require --dev nunomaduro/larastan 
Using version ^0.4.0 for nunomaduro/larastan                                                            
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                           
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nunomaduro/larastan ^0.4.0 -> satisfiable by nunomaduro/larastan[v0.4.0].
    - nunomaduro/larastan v0.4.0 requires phpstan/phpstan ^0.11.15 -> satisfiable by phpstan/phpstan[0.11.15].
    - Conclusion: don't install nikic/php-parser v4.2.2
    - phpstan/phpstan 0.11.15 requires nikic/php-parser ^4.2.3 -> satisfiable by nikic/php-parser[v4.2.3, v4.2.4].
    - Can only install one of: nikic/php-parser[v4.2.3, v4.2.2].
    - Can only install one of: nikic/php-parser[v4.2.4, v4.2.2].
    - Installation request for nikic/php-parser (locked at v4.2.2) -> satisfiable by nikic/php-parser[v4.2.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by szepeviktor** [comment]
Seems like nikic/php-parser needs an upgrade

`composer require nikic/php-parser:4.2.4`

**Comment by rtrzebinski** [comment]
@szepeviktor thank you for your answer

running

`composer require --dev nikic/php-parser:4.2.4`

before

`composer require --dev nunomaduro/larastan`

fixed the issue, although I don't really understand what happened - why is this issue specific to my instance, and works fine on others?

**Comment by szepeviktor** [comment]
A package or your project required the specific version of nikic/php-parser

**Comment by iwasherefirst2** [comment]
> fixed the issue, although I don't really understand what happened - why is this issue specific to my instance, and works fine on others?

I had the exact same error. In my case, `nikic/php-parser,` was not required by an other package. I created an application in 2017 and the version `4.2.0` was simply fixed through `composer.lock` The update to `4.2.4` fixed the issue for me. Although I am not sure why composer did not automatically update it, when it did not conflict with any dependency.
