### ISSUE TITLE
Custom Notification Channel problem

### ISSUE THREAD

**Issue by alberto-bottarini** [nunomaduro/larastan#315]
- Larastan Version: 0.4.0

### Description
I get this error: 

> Call to an undefined method Illuminate\Notifications\Notification::toApns().

when using custom Notification Channel (https://laravel.com/docs/5.8/notifications#custom-channels). I guess because type-hinting of method signature reference an abstract Notification class that does not have custom toChannel method.

### Laravel code where the issue was found

```php
    public function send($notifiable, Notification $notification)
    {
        $notification->toChannel($notifiable, $notification);
    }
```

**Comment by chrisbjr** [comment]
I have the same problem. I'm thinking now that custom notification channels should have an `interface` from the channel package attached to the Notification themselves. But this is not feasible for third party packages.

**Comment by nunomaduro** [comment]
You will need to use `phpdocs` hint the `$notification` variable.

**Comment by Temepest74** [comment]
> You will need to use `phpdocs` hint the `$notification` variable.

I am facing the same issue, can you provide an example? What do you exactly mean by hinting the notification variable? isn't it hinted already in ```Notification $notification```

**Comment by szepeviktor** [comment]
```php
/** @var your-type $notification */
```

**Comment by Temepest74** [comment]
> ```php
> /** @var \your-concrete-notification $notification */
> ```
> 

Oh, I was hoping for a fix with the preexisting notification class.

**Comment by wesamly** [comment]
You can create an interface with the method in question, and type hint when needed. Example given below:

```php
namespace App\Notifications;

use App\Messages\SmsMessage;

interface SmsableNotification
{
    public function toSms(object $notifiable): SmsMessage;
}

class InvoicePaid extends Notification implements SmsableNotification
{
    // ...

    public function toSms(object $notifiable): SmsMessage
    {
        return new class {
            private $content = 'This is a test';

            public function getContent(): string
            {
                return $this->content;
            }
        };
    }

    // ...
}

class SmsChannel
{
    public function send(object $notifiable, SmsableNotification $notification): void
    {
        $sms = $notification->toSms($notifiable);
        // Send the SMS notification
    }
}
```
