### ISSUE TITLE
Wrong tests and possible wrong implementation

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#324]
In `ModelExtension` test class we have [tests](https://github.com/nunomaduro/larastan/blob/master/tests/Features/Methods/ModelExtension.php#L23-L49) that are using some Builder methods on a model and expect the return type to be the model itself.

I'm thinking this is wrong. I also checked this in a different project in tinker. `(new User)->whereId(1)` statements like this, returns `Illuminate\Database\Eloquent\Builder`

Am I missing something or this is actually wrong? I can fix this but wanted to ask first.

cc @szepeviktor, @nunomaduro

**Comment by nunomaduro** [comment]
The `Illuminate\Database\Eloquent\Builder` contains a magic method that proxies all calls to the original model. That's why.

**Comment by canvural** [comment]
@nunomaduro But at the end, the return type shouldn't be the model itself. You have to call `get` to return the model itself.

**Comment by canvural** [comment]
You can also test it in a Laravel project by doing `dd(User::whereId(1));` This dumps the Builder instance, not the model.

**Comment by nunomaduro** [comment]
How about supporting relations methods on that chain? Today is possible because we modify the return type to a model:

```php
User::whereId(1)->companies();
```

**Comment by canvural** [comment]
@nunomaduro That's not a valid Laravel code.
