### ISSUE TITLE
proposal: rules specific to laravel

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#326]
I was thinking maybe we can implement some Laravel specific PHPStan rules.

What common mistakes do you see Laravel developers do, that can be caught by static analysis?

**Comment by CyberiaResurrection** [comment]
I'm not sure I've seen it recently, but the following idiom has had me scratching my head:

`
$foo = $someBuilder->first();
$foo = $foo ? $foo : null;
`
Where the second line is completely implied by the semantics of the ->first() call off the query builder.

**Comment by BrandonSurowiec** [comment]
Using a Model reference in a migration could raise a warning. If the model gets changed down the line, the migration could break: https://twitter.com/calebporzio/status/1184497422187274240

**Comment by crissi** [comment]
reusing names for routes
