### ISSUE TITLE
There are no commands defined in the "code" namespace. 

### ISSUE THREAD

**Issue by di1606** [nunomaduro/larastan#327]

**Comment by szepeviktor** [comment]
Sorted out.

**Comment by linkgeneral** [comment]
how did you sorted out guys?

**Comment by szepeviktor** [comment]
@linkgeneral Please read the docs.
https://github.com/nunomaduro/larastan/blob/master/README.md#-getting-started-in-3-steps
We moved away from `artisan` command.

**Comment by mr-feek** [comment]
@szepeviktor no one ever updated the carbon screenshot to remove the analyze command
