### ISSUE TITLE
Extension needed for abort_unless

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#331]
We need another type specifying extension. This time for `abort_unless`

It should be the almost the same as [this extension](https://github.com/nunomaduro/larastan/blob/master/src/Types/AbortIfFunctionTypeSpecifyingExtension.php). Also [this comment](https://github.com/nunomaduro/larastan/issues/331#issuecomment-543112339) from below should be considered.

This can be a good first issue to start contributing to larastan! :+1:

**Comment by canvural** [comment]
And I guess same thing can apply to `throw_if` and `throw_unless`

**Comment by canvural** [comment]
No. I think they should have seperate extensions.

**Comment by szepeviktor** [comment]
Okay. I thought they need the very same action.

**Comment by ondrejmirtes** [comment]
You can register one extension multiple times with different constructor arguments. `abort_if` and `throw_if` seem like they do the same thing with the first argument.
