### ISSUE TITLE
Query\Builder::dynamicWhere() expects array, string given

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#334]
- Larastan Version: 0.4.2
- `--level` used: 5
- Laravel version 6.3

### Description

Similar to https://github.com/nunomaduro/larastan/issues/272 I am getting false positives.

### Laravel code where the issue was found

```php
Commission::query()
    ->whereNotNull('reviewed_at')
    ->whereHas('user')
    ->get();
```

Curiously enough, if I leave out either of the where() calls, the error is gone.

**Comment by canvural** [comment]
That code doesn't even use dynamic wheres. It's just builder methods. I. Guess this will also be fixed with #325

**Comment by canvural** [comment]
Can you test this with the latest changes in `master` branch?

**Comment by spaceemotion** [comment]
Yep, seems to have been fixed. Thanks!

**Comment by nunomaduro** [comment]
Good job @canvural
