### ISSUE TITLE
Model relationship resolution ignores @property hints

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#335]
- Larastan Version: 0.4.2
- `--level` used: 5

### Description
I'm always adding `@property` hints to my models for better autocompletion. So my models look like these:

```php

/**
 * @property int $id
 * @property string $title
 * @property User $author
 * ...
 */
class BlogPost extends Model
{
    // ...

    public function author()
    {
        return $this->belongsTo(User::class);
    }
}
```

I am getting a false positive when using the `author` property in context though:

> [...] expects App\Models\User|null, App\Builders\UserBuilder|(Illuminate\Database\Eloquent\Collection&iterable<App\Builders\UserBuilder>)|Illuminate\Database\Eloquent\Model given.

It looks like it simply ignores the typehint in my phpdoc and tries to resolve the instance by itself.

### Laravel code where the issue was found
```php
$blogPost = BlogPost::findOrFail($id);

$this->sendNotification($blogPost->author);

public function sendNotification(User $user)
{
    // ...
}
```

(This issue just describes an SCCE, the actual code I have is different, but the error is the same)

**Comment by canvural** [comment]
Can you test this again with 0.4.3?

**Comment by spaceemotion** [comment]
Sorry for the late response, it looks like this has also been resolved. Thanks!
