### ISSUE TITLE
Support for 5.4

### ISSUE THREAD

**Issue by walkertrack5** [nunomaduro/larastan#34]
This package looks really awesome!! 

Will there ever be support for Laravel 5.4 or 5.5?

**Comment by shirshak786** [comment]
As this package requires php 7.1 I don't think we should support old version of laravel

**Comment by nunomaduro** [comment]
Thanks!

I am sorry @walkertrack5. Support old versions of Laravel is not on my plan.

**Comment by walkertrack5** [comment]
No worries! I will def use this in all my 5.6 apps!

**Comment by nunomaduro** [comment]
@walkertrack5 Thanks! Don't forget that your feedback is important. If you find false positives report them on our issue tracker. 👍

**Comment by walkertrack5** [comment]
Ok will do! Gonna try to get this set up over the weekend on a few projects.

**Comment by bitfactory-justin-kouwenhoven** [comment]
Any reason why 5.5 is not supported? Since 5.5 is an lts version most people will use.

**Comment by shirshak786** [comment]
It may be compatibility issues. And I think people mostly use latest version of laravel although 5.5 is LTS
