### ISSUE TITLE
firstOrCreate() flagging up undefined property

### ISSUE THREAD

**Issue by ohnotnow** [nunomaduro/larastan#344]
- Larastan Version: 0.4.3
- `--level` used: 2

### Description

I have a call to `firstOrCreate()` which works fine - but the analyser is still showing the warning about an undefined property.  Running with level 2 (not below) it will give me `Access to an undefined property Illuminate\Database\Eloquent\Builder::$id.`

### Laravel code where the issue was found

```php
$ebeam = EquipmentCategory::firstOrCreate(['name' => 'EBeam']);
$vb6Equipment = Equipment::firstOrCreate(
    ['name' => 'VB6'], 
    ['equipment_category_id' => $ebeam->id]
);
```

**Comment by canvural** [comment]
We can't know which properties does your model have.

Do you have annotation for the `id` property in your `EquipmentCategory` model?

**Comment by ohnotnow** [comment]
Ah - no, I don't.  I was (wrongly!) assuming the package would make that assumption. I didn't spot any mention in docs on doing that - though I am a dev, and thus barely skim docs.... ;-)

**Comment by szepeviktor** [comment]
We are happy that it was resolved in this quick manner.

**Comment by bolechen** [comment]
When upgrade to 0.4.3, have this error

```php
        $curr_user = Member::firstOrCreate(['weixin_openid' => $oauth_user->id], $default_user_data);

        if ($curr_user->shop_id != $shop->id) {
...
```

```
 ------ ----------------------------------------------------------------------------------------
  Line   app/Listeners/WechatOpenPlatform/WeChatUserAuthorizedListener.php
 ------ ----------------------------------------------------------------------------------------
  49     Access to an undefined property Illuminate\Database\Eloquent\Builder::$shop_id.
```

Member.php doc annotation is below
```php
/**
 * App\Member.
 *
 * @property int                                                                                                       $id
 * @property null|int                                                                                                  $pid
 * @property int                                                                                                       $level_id
 * @property null|string                                                                                               $tel
 * @property null|int                                                                                                  $shop_id
```

Downgrade to 0.4.2 was no error. @canvural

**Comment by szepeviktor** [comment]
Maybe `firstOrCreate` is missing here https://github.com/canvural/larastan/blob/master/src/Methods/ModelForwardsCallsExtension.php#L39

**Comment by canvural** [comment]
@bolechen Thanks for reporting that. Like @szepeviktor said, `firstOrCreate` is missing from the list. Would you like to do a PR for this? Or I can do it tomorrow.

**Comment by szepeviktor** [comment]
@bolechen This kind of contribution - I think - fits you :)
