### ISSUE TITLE
Support accessors in interface to fix uncorrect `access to undefined property`

### ISSUE THREAD

**Issue by bertheyman** [nunomaduro/larastan#345]
- Larastan Version: 0.3.0
- `--level` used: default = 0

### Description
If an interface defines a required accessor, the analysis stills thinks that this property does not exist.

### Laravel code where the issue was found

```php
// Interface
public function getPropertyAttribute();

// Some class, model is implementing the interface
$model->property

// Will result in `access to undefined property`
```

**Comment by canvural** [comment]
I don't think we should support this. 

You can define those properties in the class annotation of your model. And [larave-ide-helper](https://github.com/barryvdh/laravel-ide-helper) can help you do that automatically.

**Comment by szepeviktor** [comment]
[off] Does larave-ide-helper itself use Larastan? That would be very nice.

**Comment by bertheyman** [comment]
@canvural Ok, valid point there!
I'm already using the laravel-ide-helper, but writing the output to a file and not in the model itself.
Doesn't seem like the easiest thing to support though, will have a look a rendering the annotations in the model itself.

**Comment by canvural** [comment]
@bertheyman laravel-ide-helper can write the annotations to the model file.
