### ISSUE TITLE
variadic query builder methods fail (groupBy)

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#350]
- Larastan Version: 0.4.3
- `--level` used: max

### Description
I am getting the following false positive:

```
Method Illuminate\Database\Eloquent\Builder::groupBy() invoked with 2 parameters, 0-1 required.
```

### Laravel code where the issue was found

```php
Model::query()->groupBy('day', 'type');
```

I suspect this has something to do with larastan since the following raw PHP example works: https://phpstan.org/r/d2cf11d7-bd8a-4061-bd2f-120128c38cb1

**Comment by canvural** [comment]
Thank you for reporting this!

I know what's causing this. I'll fix it :+1:
