### ISSUE TITLE
Support baselineNeon functionality

### ISSUE THREAD

**Issue by tmcnicholls** [nunomaduro/larastan#356]
- Larastan Version: 0.4.3
- `--level` used: 5

### Description

Are there any plans to support the new baselineNeon functionality from PHPStan? I'm using it in other non-Laravel projects and it's really helpful:

https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff

I have updated to the latest version of PHPStan `0.11.19` in a Laravel project and tried to add the `--error-format baselineNeon` option.

The analyser runs as expected, but the output is incorrect. The path in each output block is an absolute path to the file on disk, instead of the expected project relative path.

I'm also unable to pipe the output from `php artisan code:analyse` to a file as required for this feature to work correctly.

Examples:

Output from PHPStan `0.11.19`:

```
 -
    message: "#^Result of \\|\\| is always true\\.$#"
    count: 1
    path: app/Service/Sitemap/SitemapFactory.php
```

Output from Larastan `0.4.3`:

```
 -
    message: "#^Result of \\|\\| is always true\\.$#"
    count: 1
    path: /Users/username/larastan-test/app/Service/Sitemap/SitemapFactory.php
```

Thanks

**Comment by szepeviktor** [comment]
Thank you.

> unable to pipe the output

Please refer to an existing issue or open a separate one for piping problems.

**Comment by canvural** [comment]
The `code:analyse` artisan command is no longer available. Therefore, this should be no longer an issue.
