### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#366]
I guess @nunomaduro removed the StyleCI integration because we were getting some errors with it.

Is it possible to fix the error and re-enable the StyleCI? Or maybe we can integrate `phpcs` to the project.

Any thoughts?

**Comment by szepeviktor** [comment]
This problem is quite deep.

Laravel publishes its rules only on StyleCI.

StyleCI is not an enterprise ready service.

StyleCI uses an old an modified version of PHP CS Fixer.

See my hacky-hack: https://support.google.com/mail/contact/abuse

**Comment by canvural** [comment]
The problem is not the StyleCI. It's working correctly. And many open source projects use it.

The problem was the settings with the Github integration. `push` shouldn't be markes as `required`

**Comment by nunomaduro** [comment]
@canvural Do you want me to reactivate stylci right?

**Comment by canvural** [comment]
@nunomaduro Yes. But maybe we can try to disable the `required` for the `push` It was causing problems earlier.

**Comment by szepeviktor** [comment]
Why running it if you ignore its result?

**Comment by nunomaduro** [comment]
@canvural @szepeviktor Should be good now.
