### ISSUE TITLE
Switch to use PHPStan shim

### ISSUE THREAD

**Issue by Jamesking56** [nunomaduro/larastan#370]
To avoid any dependency conflicts, I think it would be better to switch to using `phpstan/phpstan-shim` in larastan instead of `phpstan/phpstan`.

**Comment by szepeviktor** [comment]
Thank you!

Good news: PHPStan will switch to PHAR distribution from v0.12.0

**Comment by szepeviktor** [comment]
Although!

If you add `phpstan/phpstan-shim` to `"require"` `phpstan/phpstan` won't be installed.
