### ISSUE TITLE
Argument of an invalid type Illuminate\Database\Eloquent\Builder supplied for foreach, only iterables are supported.

### ISSUE THREAD

**Issue by larsnystrom** [nunomaduro/larastan#373]
- Larastan Version: 0.4.3
- `--level` used: 5

### Description

When iterating over a cursor phpstan warns about "Argument of an invalid type Illuminate\Database\Eloquent\Builder supplied for foreach, only iterables are supported.".

### Laravel code where the issue was found

```php
foreach (MyModel::cursor() as $item) {
//
}
```

**Comment by spaceemotion** [comment]
What happens when you use `MyModel::query()->cursor()` instead?

**Comment by larsnystrom** [comment]
Yeah, I think that fixes it. I've noticed this does not only happen for `cursor()` but also for `get()`, `max()`, etc, when you call those methods directly on the model class.

**Comment by canvural** [comment]
Hi,

Can you test this in 0.5?

**Comment by larsnystrom** [comment]
I can't even reproduce this with 0.4 anymore so closing for now.
