### ISSUE TITLE
Method Illuminate\Database\Eloquent\Builder::groupby() invoked with 2 parameters, 0-1 required.

### ISSUE THREAD

**Issue by nithinwilson** [nunomaduro/larastan#374]
- Larastan Version: #.#.#
- `--level` used:

### Description

MyModel::select('var1','var2')->groupBy('var1','var2')->get();

### Laravel code where the issue was found

```php

```

**Comment by jafar690** [comment]
Whoever comes here looking for a solution, just do this:
`MyModel::select(['var1','var2'])->groupBy(['var1','var2'])->get();`
