### ISSUE TITLE
Call to undefined method NunoMaduro\Larastan\ApplicationResolver::getAnnotations()

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#376]
- Larastan Version: 0.4.3 (also tested 0.4.2)
- `--level` used: n/a

### Description
Larastans latest release is not compatible with the latest release of orchestral/testbench-core 4.4.0 because of this commit https://github.com/orchestral/testbench-core/commit/7454ff7fd85dcbd739d915b53b308a21e67bca31

See https://travis-ci.org/rebing/graphql-laravel/jobs/615608011#L365

/cc @crynobone

**Comment by szepeviktor** [comment]
Aren't we compatible with v3.x versions of `orchestra/testbench`?

**Comment by crynobone** [comment]
@mfn `getAnnotations()` is coming from PHPUnit.

**Comment by crynobone** [comment]
Released `v4.4.1` which should solved this issue.

**Comment by mfn** [comment]
@crynobone thank you very much!
