### ISSUE TITLE
Eloquent Relationship issue with hasOne

### ISSUE THREAD

**Issue by sumityadav** [nunomaduro/larastan#38]
```    
/**
 * @return \Illuminate\Database\Eloquent\Relations\HasOne
 */
public function phone()
{
    return $this->hasOne('App\Phone');
}
```

Gives the following error:
```
Class Illuminate\Database\Eloquent\Relations\HasOne referenced with incorrect case: Illuminate\Database\Eloquent\Relations\hasOne.
```

**Comment by nunomaduro** [comment]
@sumityadav You don't have on your code any reference to "Illuminate\Database\Eloquent\Relations\hasOne" with **hasOne** instead of **HasOne** ?

**Comment by sumityadav** [comment]
@nunomaduro I did not reference "Illuminate\Database\Eloquent\Relations\hasOne" instead I am just defining the Eloquent relationship in User model (same as the code snippet)

**Comment by nunomaduro** [comment]
Because this issue seems to be inactive for quite some time now, I will close it. This problem should be fixed by now.

Thanks! ☺️

**Comment by sumityadav** [comment]
Just verified with fresh installation of Laravel 5.6 and it worked without issues. 
Thanks
