### ISSUE TITLE
Invalid typehint when upgrading Laravel 6.6.0->6.6.1

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#380]
- Larastan Version:  v0.4.3 
- `--level` used: max
yesterday still OK but today not working after updated to laravel 6.6.1 from laravel 6.6.0
### Description
PHP version
PHP 7.3.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

Errors
```
------ ------------------------------------------------------------------------------ 
 Line   app/Http/Controllers/BackendApi/Headquarters/Merchant/PlatformController.php  
------ ------------------------------------------------------------------------------ 

  23     Parameter $action of method
         App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController::detail()
         has invalid typehint type
         App\Http\SingleActions\Backend\Headquarters\Merchant\Platform\DetailAction.                                                                          

  23     Parameter $action of method
         App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController::detail()
         has invalid typehint type
         App\Http\SingleActions\Backend\Headquarters\Merchant\Platform\DetailAction.
```

### Laravel code where the issue was found

[PlatformController.php.txt](https://github.com/nunomaduro/larastan/files/3920058/PlatformController.php.txt)
[DetailAction.php.txt](https://github.com/nunomaduro/larastan/files/3920059/DetailAction.php.txt)

```php
namespace App\Http\Controllers\BackendApi\Headquarters\Merchant;

use App\Http\Controllers\BackendApi\Headquarters\BackEndApiMainController;
use App\Http\SingleActions\Backend\Headquarters\Merchant\Platform\DetailAction;
use Illuminate\Http\JsonResponse;

/**
 * 运营商
 */
class PlatformController extends BackEndApiMainController
{
    /**
     *
     * @param DetailAction $action Action.
     * @return JsonResponse
     */
    public function detail(DetailAction $action): JsonResponse
    {
        return $action->execute();
    }
}
```

**Comment by szepeviktor** [comment]
Thank you for your report!

**Comment by harrisdt15f** [comment]
Please, /\_/\

**Comment by harrisdt15f** [comment]
I don't know why after updated laravel to 6.6.2 then not appear such problems.
