### ISSUE TITLE
Update PHPStan to 0.12.* version

### ISSUE THREAD

**Issue by Deifinger** [nunomaduro/larastan#381]
- Larastan Version: 0.4.3

### Description

Can you, please, update phpstan from 0.11.19 version to the next minor version ^0.12.*?

**Comment by nunomaduro** [comment]
Yes. @canvural is doing an amazing job on this: https://github.com/nunomaduro/larastan/pull/378.

**Comment by Deifinger** [comment]
Read all comments. Serious changes are coming! Thanks for working on it
