### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by hudsonpereira** [nunomaduro/larastan#382]
- Larastan Version: master
- `--level` used:

### Description

![Screen Shot 2019-12-12 at 16 16 24](https://user-images.githubusercontent.com/911094/70741778-d6d66d00-1cfa-11ea-9578-d32f81f5d416.png)

**Comment by szepeviktor** [comment]
Hello @hudsonpereira !

This seems to be a packagist network error.

Please check your network or try downloading packages on another net connection.
