### ISSUE TITLE
We should support phpstan/extension-installer

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#385]
https://github.com/phpstan/extension-installer#instructions-for-extension-developers

3 lines in the JSON file!

**Comment by nunomaduro** [comment]
Can you make a pull request on that?

**Comment by szepeviktor** [comment]
Yes.

**Comment by szepeviktor** [comment]
Oh noooooooooooo!
Already done :)
https://github.com/nunomaduro/larastan/blob/master/composer.json#L58-L62
