### ISSUE TITLE
Access to an undefined property for custom accessors

### ISSUE THREAD

**Issue by johanvanhelden** [nunomaduro/larastan#396]
- Larastan Version: 0.5.0
- `--level` used: 5

### Description

I have a model with a few attributes that are not being recognized. Both "normal" database column attributes and accessors.

Here is an issue with normal columns:
```
 ------ ----------------------------------------------------------------- 
  Line   Actions/Subscriber/CreateSubscriber.php                          
 ------ ----------------------------------------------------------------- 
  35     Access to an undefined property App\Models\Subscriber::$uuid.    
  36     Access to an undefined property App\Models\Subscriber::$secret.  
 ------ ----------------------------------------------------------------- 
```

And here are some issues with accessors:
```
 ------ ---------------------------------------------------------------------------------- 
  Line   Http/Controllers/SubscriberController.php                                         
 ------ ----------------------------------------------------------------------------------       
  84     Access to an undefined property App\Models\Subscriber::$is_confirmed.             
  94     Access to an undefined property App\Models\Subscriber::$manage_subscription_url.  
 ------ ---------------------------------------------------------------------------------- 
```

These issues started showing up right after I upgraded to 0.5.0 from 0.4.3. They show up everywhere I use them in the codebase, so they are not only showing up in the examples above, but these should give some solid examples.

## Actions/Subscriber/CreateSubscriber.php  
```php
/**
 * Perform the action.
 *
 * @param array $data
 */
public function execute(array $data)
{
    $subscriber = new Subscriber($data);

    $subscriber->uuid = Str::uuid()->toString();
    $subscriber->secret = hash_hmac('sha256', Str::random(40), config('app.key'));

    $subscriber->save();

    $this->confirmationAction->execute($subscriber);
}
```

## Http/Controllers/SubscriberController.php
```php
/**
 * Executes the request to update a subscriber.
 *
 * @param string           $uuid
 * @param string           $secret
 * @param UpdateRequest    $request
 * @param UpdateSubscriber $action
 *
 * @return \Illuminate\Http\RedirectResponse
 */
public function update(string $uuid, string $secret, UpdateRequest $request, UpdateSubscriber $action)
{
    $subscriber = $this->getSubscriber($uuid, $secret);

    if (!$subscriber->is_confirmed) {
        return $this->handleNotConfirmed($subscriber);
    }

    $action->execute($subscriber, $request->validated());

    $subscriber->refresh();

    return redirect($subscriber->manage_subscription_url);
}
```

And to show the accessors actually exist:

### App/Models/Subscriber.php
```php
/**
 * Builds the is_confirmed attribute to determine if the subscription has been confirmed.
 *
 * @return bool
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
public function getIsConfirmedAttribute()
{
    return !empty($this->confirmed_at);
}

/**
 * Builds the subscription management URL.
 *
 * @return string
 */
public function getManageSubscriptionUrlAttribute()
{
    return route('subscriber.edit', [
        'uuid'   => urlencode($this->uuid),
        'secret' => urlencode($this->secret),
    ]);
}
```

And, of course, the regular columns exist as well (don't worry, it's a local, seeded, database):

![Screenshot from 2019-12-27 11-40-01](https://user-images.githubusercontent.com/19389981/71514185-c945e900-289d-11ea-8fcb-e91e804b001a.png)

**Comment by szepeviktor** [comment]
Thank you for your bug report.

**Comment by canvural** [comment]
Hi,

This is expected. At least to some extent.

We can't know what columns does your database has. This tool does static analysis of your code. And yes, in previous versions we were simply ignoring any property access on the models, so it wasn't giving any error. But we removed it to be able to support accessing relations as properties.

You can write custom docblocks on your class to specify which properties does your class have. And you can use `laravel-ide-helper` to automate this process.

Support for custom accessors on models is planned. I will work on it maybe next week.

**Comment by szepeviktor** [comment]
👍 for **custom docblocks**

**Comment by canvural** [comment]
Let's leave this open until we have support for custom accessors.

**Comment by johanvanhelden** [comment]
Ah, thank you. I had no clue that it was ignored in the old version. So for now I will just manually add the ignores to the neon file until I find some time to overhaul the codebase to support level 7 without ignores. 

I look forward to the accessor support!

**Comment by szepeviktor** [comment]
@johanvanhelden Here you are.

**Comment by canvural** [comment]
Accessor support added with #401
