### ISSUE TITLE
[0.5.0] Fatal error: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by johanvanhelden** [nunomaduro/larastan#397]
- Larastan Version: 0.5.0
- `--level` used: 5

### Description
I use Larastan as part of a CircleCI workflow to ensure no release goes live without a passing build. Since upgrading to 0.5.0  all builds now fail because of a memory exhausted error.

```
#!/bin/bash -eo pipefail
./vendor/bin/phpstan analyse
Note: Using configuration file /root/redacted.com/phpstan.neon.
 35/85 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  41%Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///root/redacted.com/vendor/phpstan/phpstan/phpstan/vendor/phpstan/phpdoc-parser/src/Lexer/Lexer.php on line 57
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /root/redacted.com/vendor/symfony/debug/Exception/FatalErrorException.php on line 1
Exited with code exit status 255
CircleCI received exit code 255
```

On my local machine it works fine, but on CircleCI it crashes.

### Laravel code where the issue was found

n.a.

**Comment by canvural** [comment]
Hi,

You can increse the memory limit with giving the option `memory-limit` to PHPStan. For example `./vendor/bin/phpstan analyse --memory-limit=512M`

**Comment by szepeviktor** [comment]
I usually run `php -d memory-limit=512M vendor/bin/phpstan analyse`

**Comment by johanvanhelden** [comment]
Thank you, that works like a charm! Good that it's now a documented feature :+1:
