### ISSUE TITLE
Cache helper Phpdoc - dynamic issue

### ISSUE THREAD

**Issue by danijelk** [nunomaduro/larastan#402]
133    Function cache invoked with 1 parameter, 0 required.
    160    Function cache invoked with 2 parameters, 0 required.
There is a dynamic definition for the cache helper

https://github.com/laravel/framework/blob/db794ceea6734cc90286e04a8a2a48e5b4cd4130/src/Illuminate/Foundation/helpers.php#L225-L235

Which side would be the best place to fix something liket his? An extension on phpstan would be overkill, but changing it to a mixed from dynamic isn't enough on this issue. Maybe the cache helper should be rewritten to a (...$parameters) ?

**Comment by canvural** [comment]
`@param  dynamic  key|key,default|data,expiration|null` this is not a valid PHPDoc syntax.
If this is removed everything is working as expected. PHPStan sees `config` function uses `func_get_args` so it allows any number of arguments to the function.

So this is not an issue on Larastan or PHPStan. You can try opening an issue in Laravel repository.

**Comment by mfn** [comment]
@canvural do you know if there's _a way_ to phpdoc this (also as a help for users)?

Could it work with `...$args` and then `@phpdoc ...$args a|b|c`?

**Comment by canvural** [comment]
> @canvural do you know if there's _a way_ to phpdoc this (also as a help for users)?
> 
> Could it work with `...$args` and then `@phpdoc ...$args a|b|c`?

Yes, this is the only way it can work as far as I know. You can see here https://phpstan.org/r/b8e2165c-7abf-4f5b-80b1-ee299b59db42

**Comment by mfn** [comment]
Much appreciated, thanks 👍

**Comment by CalebDW** [comment]
Has a solution been found for this? I tried create the below stub but that didn't seem to help:

```php
<?php

/**
 * @param  int|string|array<mixed, mixed> ...$args
 * @return mixed|\Illuminate\Cache\CacheManager
 *
 * @throws \InvalidArgumentException
 */
function cache(...$args)
{
}
```

**Comment by glennjacobs** [comment]
Using a stub for this doesn't seem to be possible.

The solutions are either...

a) Use the Cache facade, e.g. `Cache::get('foo')`

b) Ignore the errors

```
    ignoreErrors:
        -   '#Function cache invoked with 1 parameter, 0 required.#'
        -   '#Function cache invoked with 2 parameters, 0 required.#'
```

**Comment by CalebDW** [comment]
Instead of trying to use a stub, perhaps we could just raise an Issue/PR with the framework to fix the root issue?

The function should probably be updated to either:
1. Remove the incorrect PHPDoc
2. Update the function signature to accept variadic arguments (`config(...$args)`) and update the type information in the PHPDoc

**Comment by glennjacobs** [comment]
> Instead of trying to use a stub, perhaps we could just raise an Issue/PR with the framework to fix the root issue?
> 
> The function should probably be updated to either:
> 
> 1. Remove the incorrect PHPDoc
> 2. Update the function signature to accept variadic arguments (`config(...$args)`) and update the type information in the PHPDoc

Correct. We have a solution for now in ignoring the errors and ideally, a PR should be made to the Laravel framework.

**Comment by szepeviktor** [comment]
> 2\. to accept variadic arguments (`config(...$args)`)

Is it cache or config?

**Comment by glennjacobs** [comment]
> > 2. to accept variadic arguments (`config(...$args)`)
> 
> Is it cache or config?

cache for me, but it's possibly both and more potentially.

**Comment by CalebDW** [comment]
It's `cache` (I haven't finished my morning coffee lol), I updated the issue

**Comment by CalebDW** [comment]
Merged into 10.x! :partying_face:

**Comment by szepeviktor** [comment]
Is `key|key,default|data,expiration|null` a valid type?

**Comment by CalebDW** [comment]
> Is key|key,default|data,expiration|null a valid type?

No, I left that as the description
