### ISSUE TITLE
Model properties don't have typehint specified

### ISSUE THREAD

**Issue by BertvanHoekelen** [nunomaduro/larastan#412]
- Larastan Version: 6.x
- `--level` used: 7

### Description
As Laravel needs to support older versions of php they are unable to typehint the properties on the base model. So when you overwrite those properties you get errors like `Property App\Models\User::$dates has no typehint specified.`.

For now I have added these to ignoreErrors as seen below. However when models are in a different namespace than `App\Models` you still get those errors. Any way we can ignore these errors based on the `Model` class in this package?

```
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$attributes has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$original has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$changes has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$casts has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$dates has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$dateFormat has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$appends has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$guarded has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$touches has no typehint specified.#'
- '#Property App\\Models\\[a-zA-Z0-9\\_]+::\$timestamps has no typehint specified.#'
```

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Model;

class FooModel extends Model
{
    protected $dates = ['booking_date'];
}
```

**Comment by szepeviktor** [comment]
Would adding `checkMissingTypehints: false` be okay for you?

**Comment by BertvanHoekelen** [comment]
That comes close, except I like to get an error when I forget to set a type hint. E.g.
```php
/** @var array */
public $bla = [];
```
is valid with `checkMissingTypehints: false` on.

**Comment by szepeviktor** [comment]
The best would be to open an issue at @phpstan and state your PHP version and where you wish to receive errors.

**Comment by BertvanHoekelen** [comment]
I don't think it's an @phpstan issue as the `checkMissingTypehints: false` does exactly what it's supposed to do. It's because Laravel has to be backwards compatible that they cannot add the typehint, but in projects that do use php 7.4 I still want to receive the error.

**Comment by szepeviktor** [comment]
> Any way we can ignore these errors based on the `Model` class in this package?

I see!

**Comment by canvural** [comment]
Hi,

This error is not related to PHP 7.4 typed properties. You are getting the error because you don't have any PHPDoc for `$dates`. 
```php
/** @var array<int,string> $dates*/
protected $dates = ['booking_date'];
```

will solve your problem.

> but in projects that do use php 7.4 I still want to receive the error.

PHPStan rules doesn't work conditionally like this. You can get what you want with using a coding standard. For example [slevomat/coding-standard](https://github.com/slevomat/coding-standard)
