### ISSUE TITLE
Dynamic call to static method (Model)::toBase().

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#413]
- Larastan Version: 0.5.0
- `--level` used: max

### Description
Seems like yet another type casting issue with models and queries.

I suspect it to be the same error internally as https://github.com/nunomaduro/larastan/issues/355.

### Laravel code where the issue was found

```php
Payment::query()
  ->where('uuid', (string) $id)
  ->firstOrFail()
  ->toBase()
  ->update($record);
```

also happens when I do 

```php
Payment::query()
  ->where('uuid', (string) $id)
  ->firstOrFail()
  ->query()
  ->toBase()
  ->update($record);
```

but then the error is:

> Dynamic call to static method Illuminate\Database\Eloquent\Model::query().

**Comment by szepeviktor** [comment]
Yes, You are right. This is a duplicate.
