### ISSUE TITLE
Call to a member function get() on null in …/src/Methods/Pipes/Mixins.php:73

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#414]
- Larastan Version: 0.5.0
- `--level` used: 6
- Laravel Version: 6.10.1

### Description
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: 
Call to a member function get() on null 
in /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php:73

Stack trace:
#0 /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php(42): NunoMaduro\Larastan\Methods\Pipes\Mixins->getMixinsFromClass()
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): NunoMaduro\Larastan\Methods\Pipes\Mixins->handle()
#2 /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php(114): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#3 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): NunoMaduro\Larastan\Methods\Pipes\Macros->handle()
#4 /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/SelfClass.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#5 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171):  in /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Mixins.php on line 73
```

### Laravel code where the issue was found

This is on a project which works with phpstan 0.12.4 (which I removed) and then installed larastan `^0.5.0`.

It happens on a file which is a `Mail/….php` and which references e.g. some models. I suspect it's models related (?) becaus the problem has to do with mixins and I have `@mixin \Eloquent` annotations in all my models (using barryvdh/laravel-ide-helper to write them there).

It's private code repo so ...

Any suggestion how can I further debug this? I was already running `vendor/bin/phpstan analyse --configuration=phpstan.neon app --debug`

Thanks!

**Comment by mfn** [comment]
Hmm, I gets at least past this point once I remove this line from my neon file:
```
parameters:
  …
  bootstrap: vendor/autoload.php
```
Not sure why it's even there 😄

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/larastan/blob/430ccefbb4fc99c25d0a083dda504ee6469a1d34/src/Methods/Pipes/Mixins.php#L73

**Comment by mfn** [comment]
Hmm, no, removing the boostrap gets my totally weird errors like this:
```
/vagrant/project/app/Models/SomeModel.php

   Exception  : Unable to resolve PSR response. Please install nyholm/psr7.

  at /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:167
    163|             if (class_exists(ZendPsrResponse::class)) {
    164|                 return new ZendPsrResponse;
    165|             }
    166|
  > 167|             throw new Exception('Unable to resolve PSR response. Please install nyholm/psr7.');
    168|         });
    169|     }
    170|
    171|     /**

  Exception trace:

  1   Illuminate\Routing\RoutingServiceProvider::Illuminate\Routing\{closure}()
      /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:799

  2   Illuminate\Container\Container::build()
      /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:681

  Please use the argument -v to see more details.
PHP Fatal error:  Uncaught Exception: Unable to resolve PSR response. Please install nyholm/psr7. in /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:167
Stack trace:
#0 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}()
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build()
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->resolve()
#3 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Container\Container->make()
#4 /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php(51): Illuminate\Foundation\Application->make()
#5 /vagrant/project/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php(65): Swat\Api\V2\Services\Vendor\Illuminate\ in /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 167
```

**Comment by szepeviktor** [comment]
Try adding config.

**Comment by mfn** [comment]
> `#4 /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php(51): Illuminate\Foundation\Application->make()`

I'm using a custom `Application` instance which also seems to clash with some things larastan expects to work, but I mostly disabled the code within already for testing.

**Comment by mfn** [comment]
> Try adding config.

What config do you mean?

**Comment by mfn** [comment]
I stripped down the neon to it's bare minimum:
```
includes:
  - ./vendor/nunomaduro/larastan/extension.neon
parameters:
  level: 6
```

**Comment by szepeviktor** [comment]
I remembered Lumen had needed config as Service.

Try `./artisan config:cache`

**Comment by mfn** [comment]
Doesn't change anything, https://github.com/nunomaduro/larastan/issues/414#issuecomment-573826848 is still the error.

I _had_ a different error in between where Larastan tried to create an instance of an interface, but can reproduce _that_ one anymore.

Granted, the project I'm trying it on, by any standards I have, is "big and heavily customized". It's living since Laravel 5.0 and well maintained into 6.10.1 as of today and I thought I have larastan another try.

Example: we do not allow `make`ing of classes, which are not explicitly registered. This falls already flat which some introspection assumption of larastan when it tries to instantiate some classes we don't intend too 😄

**Comment by mfn** [comment]
Ok, back to the original stacktrace when I leave the `bootstrap` in, seems to be the most sensible error to chase at this point.

After removing all the `catch` clauses in `\NunoMaduro\Larastan\Concerns\HasContainer::resolve` I get a more explicit:
> `PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:803`

So, of course the config is present in general, just no idea why it can't be resolved. Digging further…

**Comment by mfn** [comment]
```
            dump($this->getContainer()->bindings);
```
`bindings` is empty in this case (I made it public for quick testing). Seems like nothing is "booted" here. Wonder where that did go wrong.

**Comment by canvural** [comment]
Hi,

That's weird. Does `app('config')` gives the same exception?

On another note, maybe we should remove those config files. Something to consider.

**Comment by mfn** [comment]
Just a warning, I'm "almost sure" I've a very specific setup and my gut feeling is, it's a "project problem" 😄 

(though I appreciate any pointers)

is `bootstrap/app.php` "executing" during larastan? Don't know any other place where `Application` itself is bootet and AFAICS if `\Illuminate\Foundation\Application::registerCoreContainerAliases` isn't called, there won't be a config (and: it isn't called in my case)

**Comment by mfn** [comment]
> That's weird. Does `app('config')` gives the same exception?

Yes!

**Comment by canvural** [comment]
> is `bootstrap/app.php` "executing" during larastan? Don't know any other place where `Application` itself is bootet and AFAICS if `\Illuminate\Foundation\Application::registerCoreContainerAliases` isn't called, there won't be a config (and: it isn't called in my case)

Yes, Larastan bootstraps your application. Check the [bootstrap.php](https://github.com/nunomaduro/larastan/blob/master/bootstrap.php) file.

**Comment by mfn** [comment]
Ah!

I've re-enabled my `bootstrap`: is it possible that this "overrides" the one from `larastan/extension.neon`?

**Comment by mfn** [comment]
Ok, then it's clear: I **must** remove my own `bootstrap` otherwise larastan does not receive a bootetd application, make sense 👍

**Comment by canvural** [comment]
> Ah!
> 
> I've re-enabled my `bootstrap`: is it possible that this "overrides" the one from `larastan/extension.neon`?

I'm not sure how PHPStan works in that case. But possible.

> Ok, then it's clear: I **must** remove my own `bootstrap` otherwise larastan does not receive a bootetd application, make sense +1

Or maybe you can include the Larastan's bootstrap file in your custom bootstrap file.

**Comment by mfn** [comment]
> Or maybe you can include the Larastan's bootstrap file in your custom bootstrap file.

It's actually not customized. It's not necessary, even pure phpstan works correctly _without_ it. Seems it's just a legacy leftover which tripped me just too early with larastan. I think we can simply ignore that information fact for now :|

----

No I get it why processing of PHP files has more progress and then I turn up with completely other errors because it simply gets much further.

After disabling bootstrap, I now get this 😄
```
/vagrant/project/app/Models/SomeModel.php

   RuntimeException  : The class Project\Services\GuzzleHttp\Loggable has not been registered

  at /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php:48
    44|      */
    45|     public function make($abstract, array $parameters = [])
    46|     {
    47|         if ($this->abstractRequiresRegistration($abstract) && !$this->bound($abstract)) {
  > 48|             throw new RuntimeException("The class $abstract has not been registered");
    49|         }
    50|
    51|         return parent::make($abstract, $parameters);
    52|     }

  Exception trace:

  1   Project\Services\Vendor\Illuminate\Foundation\Application::make()
      /vagrant/project/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php:65

  2   NunoMaduro\Larastan\Methods\Pipes\Macros::resolve()
      /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php:57

  Please use the argument -v to see more details.
PHP Fatal error:  Uncaught RuntimeException: The class Project\Services\GuzzleHttp\Loggable has not been registered in /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php:48
Stack trace:
#0 /vagrant/project/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php(65): Project\Services\Vendor\Illuminate\Foundation\Application->make()
#1 /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php(57): NunoMaduro\Larastan\Methods\Pipes\Macros->resolve()
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): NunoMaduro\Larastan\Methods\Pipes\Macros->handle()
#3 /vagrant/project/vendor/nunomaduro/larastan/src/Methods/Pipes/SelfClass.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#4 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): NunoMaduro\Larastan\Methods\Pipes\SelfClass->handle()
#5 /vagrant/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105):  in /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php on line 48
```
Now this is specific because we don't allow instantiating non-registered classes in our namespace; safety precaution.

When I remove this, I get this far (`SomeModel` is the same model):
```
/vagrant/project/app/Models/YtRequestLog.php

   Exception  : Unable to resolve PSR response. Please install nyholm/psr7.

  at /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:167
    163|             if (class_exists(ZendPsrResponse::class)) {
    164|                 return new ZendPsrResponse;
    165|             }
    166|
  > 167|             throw new Exception('Unable to resolve PSR response. Please install nyholm/psr7.');
    168|         });
    169|     }
    170|
    171|     /**

  Exception trace:

  1   Illuminate\Routing\RoutingServiceProvider::Illuminate\Routing\{closure}()
      /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:799

  2   Illuminate\Container\Container::build()
      /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:681

  Please use the argument -v to see more details.
PHP Fatal error:  Uncaught Exception: Unable to resolve PSR response. Please install nyholm/psr7. in /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:167
Stack trace:
#0 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}()
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build()
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->resolve()
#3 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Container\Container->make()
#4 /vagrant/project/app/Services/Vendor/Illuminate/Foundation/Application.php(51): Illuminate\Foundation\Application->make()
#5 /vagrant/project/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php(65): Project\Services\Vendor\Illuminate\ in /vagrant/project/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 167
```

**Comment by mfn** [comment]
I think the final error is because larastan tries to make `Psr\Http\Message\ResponseInterface`.

The `SomeModel` in question uses trait which itself has a "helper" method like this:
```php
    public function mapGuzzleRequest(
        RequestInterface $request,
        array $options = [],
        ResponseInterface $response = null,
        Exception $error = null
    ): array {
```
Any idea what larastan would try to do here?

(this helper is used in a custom guzzle middleware for logging)

**Comment by mfn** [comment]
Nope, it's not "just" the function signature; it also depends on the body somehow 💥

**Comment by mfn** [comment]
Aha!

This is the most minimal code:
```php
    public function mapGuzzleRequest( ResponseInterface $response ): void {
        $response->curl_info['total_time'];
    }
```
There is **no** `curl_info` on the interface. This whole code is some dirty black magic hack to get access to CURLs `total_time` which otherwise no one knows how to get (or so).

The thing is: larastsan probably sees this and realizes that this (property) isn't defined on the interface (…) and then tries to "introspect it".

But you can't just make the `\Psr\Http\Message\ResponseInterface`, doesn't make sense.

Any ideas :-) (besides me rewriting this code somehow 🤷‍♀️)

**Comment by canvural** [comment]
Yep, you are right. The issue is [here](https://github.com/nunomaduro/larastan/blob/master/src/Properties/Extension.php#L41). There is even a todo for it :smile: 

Larastan tries to resolve the interface through the container, to check if the property is there in the concrete class. We can do as the todo says, and do this check only in `Illuminate\Contracts`. This can solve it.

**Comment by canvural** [comment]
Thanks for all the debugging! I will fix this sometime this week. :+1:

**Comment by mfn** [comment]
Gotta love them "TODOs" 😄

**Comment by mfn** [comment]
Yep, this quick'n'dirty diff did let me "pass" laratsan: now into 1k reported errors 😄 
```diff
diff --git a/vendor/nunomaduro/larastan/src/Properties/Extension.php b/vendor/nunomaduro/larastan/src/Properties/Extension.php
index 3061cee20..448f6bdbd 100644
--- a/vendor/nunomaduro/larastan/src/Properties/Extension.php
+++ b/vendor/nunomaduro/larastan/src/Properties/Extension.php
@@ -13,6 +13,8 @@ declare(strict_types=1);

 namespace NunoMaduro\Larastan\Properties;

+use Illuminate\Support\Str;
+use Predis\Command\StringBitPos;
 use function get_class;
 use Illuminate\Contracts\Container\Container;
 use NunoMaduro\Larastan\Concerns;
@@ -38,7 +40,10 @@ final class Extension implements PropertiesClassReflectionExtension, BrokerAware
         /*
          * @todo Consider apply this rule only for Illuminate\Contracts.
          */
-        if ($classReflection->isInterface()) {
+        if (
+            $classReflection->isInterface() &&
+            Str::startsWith('Illuminate\Contracts', $classReflection->getName())
+        ) {
```

**Comment by canvural** [comment]
Or we can catch more general exceptions in the `resolve` method.

**Comment by mfn** [comment]
Btw I also have issues with `\NunoMaduro\Larastan\Methods\Pipes\Macros::handle`:
```php
        if ($classReflection->isInterface()) {
            $concrete = $this->resolve($classReflection->getName());

            if ($concrete !== null) {
                $className = get_class($concrete);

                if ($passable->getBroker()
                    ->getClass($className)
                    ->hasTraitUse(Macroable::class)) {
                    $macroTraitProperty = 'macros';
                }
            }
```

I.e. after making it that far I, again, enabled code which throws an error if something is tried to be "make" from the container when it's not registered.

In this case this code seems to try to also introspect interfaces for stuff and, this particular (another) interface it tries to resolve isn't registered (and not supposed to be).

**Comment by mfn** [comment]
Same here also `\NunoMaduro\Larastan\Methods\Pipes\Contracts::concretes`:
```php
        if ($classReflection->isInterface()) {
            $concrete = $this->resolve($classReflection->getName());

            if ($concrete !== null) {
                return [get_class($concrete)];
            }
        }
```
So yeah, maybe working this into `resolve` might make sense:
```php
    public function resolve(string $abstract)
    {
        $concrete = null;

        try {
            $concrete = $this->getContainer()
                ->make($abstract);
        } catch (ReflectionException $exception) {
            // ..
        } catch (BindingResolutionException $exception) {
            // ..
        } catch (NotFoundExceptionInterface $exception) {
            // ..
        }

        return $concrete;
    }
```
In "my" `make` I throw a `RuntimeException`; I guess this all wouldn't happen if I would just throw a `\Psr\Container\NotFoundExceptionInterface`.

I'll look into that.

**Comment by canvural** [comment]
This was also partially discussed in #338 

Catching everything makes sense in the `resolve` method. But also there are some cases the error is actually useful.

**Comment by mfn** [comment]
I'm already changing my resolver code to use a PSR-11 compliant exception; should have been there from the beginning but what do I know :)

However the change in https://github.com/nunomaduro/larastan/issues/414#issuecomment-573851642 is real, without it I can't make it work at all.

OTOH the code I try to inspect is a hack: blindly accessing a proper my project knows to set "by convention" is a call for troubles, as we see here. I'll also rework this part now that I know of it.

So in the end, not sure if _this issue_ is a good evidence to fix the TODO you outlined…

**Comment by canvural** [comment]
I think it still needs fixing. This is an extension for Laravel, so resolving Laravel interfaces makese sense. But we should not resolve every interface blindly like this.

**Comment by mfn** [comment]
> not resolve every interface blindly like this

After I woke up: maybe a `->bound()` check would generally help in `resolve()`.

However, there are classes you want from your `resolve` implementation you basically _expect_ them to be there (like `config`), so the bound check wouldn't make sense.

Make there should be a distinction when resolving:
- you require framework default interfaces, use a non-forgiving resolve approach
- you want to resolve something for larastan introspection itself => add the check?

**Comment by mfn** [comment]
Today I tried larastan again but was immediately reminded why I can't use it yet 😅

@canvural do my ideas make sense (https://github.com/nunomaduro/larastan/issues/414#issuecomment-574023913 ) or do you have more feedback? 

I might try a PR here but not sure yet.

**Comment by canvural** [comment]
@mfn Sorry, I totally forgot about this issue :sweat_smile: 

Recently we received a [PR](https://github.com/nunomaduro/larastan/pull/431) that adds support for dynamic return type for `app` helper. It does this by resolving the passed argument out of the container.

So, if we just limit the argument to framework interface/classes, this will not be so useful.

So ideally in the `resolve` function, we want to resolve everything. Maybe we can add more catch statements though.

But maybe we can should add the checks to `NunoMaduro\Larastan\Properties\Extension`, `\NunoMaduro\Larastan\Methods\Pipes\Macros` and `\NunoMaduro\Larastan\Methods\Pipes\Contracts`

You are welcome to make a PR for this :+1:

**Comment by mfn** [comment]
[I feel like in the movie Groundhog Day!](https://github.com/nunomaduro/larastan/issues/414#issuecomment-581066721)
> Today I tried larastan again but was immediately reminded why I can't use it yet 😅

I went through the whole thread again and, interestingly, the **only** problem right now from running larastan is what I pointed out in https://github.com/nunomaduro/larastan/issues/414#issuecomment-573851642
```diff
$ git diff
diff --git a/vendor/nunomaduro/larastan/src/Properties/Extension.php b/vendor/nunomaduro/larastan/src/Properties/Extension.php
index 7054c3b23..39d842d5c 100644
--- a/vendor/nunomaduro/larastan/src/Properties/Extension.php
+++ b/vendor/nunomaduro/larastan/src/Properties/Extension.php
@@ -4,6 +4,7 @@ declare(strict_types=1);

 namespace NunoMaduro\Larastan\Properties;

+use Illuminate\Support\Str;
 use function get_class;
 use Illuminate\Contracts\Container\Container;
 use NunoMaduro\Larastan\Concerns;
@@ -29,7 +30,7 @@ final class Extension implements PropertiesClassReflectionExtension, BrokerAware
         /*
          * @todo Consider apply this rule only for Illuminate\Contracts.
          */
-        if ($classReflection->isInterface()) {
+        if ($classReflection->isInterface() && Str::startsWith('Illuminate\Contracts', $classReflection->getName())) {
             $concrete = $this->resolve($classReflection->getName());

             if ($concrete !== null) {
```
I.e. resolving arbitrary interfaces yields to instantiation of things which aren't meant to be and cause problems.

I tried to outsmart the system and modify `\NunoMaduro\Larastan\Properties\Extension::hasProperty` to only resolve when it's bound:
```php
        if ($classReflection->isInterface() && $this->getContainer()->bound($classReflection->getName())) {
```
Turns out this interface _is_ bound, very much in `\Illuminate\Routing\RoutingServiceProvider::registerPsrResponse`:
```php
    protected function registerPsrResponse()
    {
        $this->app->bind(ResponseInterface::class, function () {
            if (class_exists(PsrResponse::class)) {
                return new PsrResponse;
            }

            throw new Exception('Unable to resolve PSR response. Please install nyholm/psr7.');
        });
    }
```
I actually would realized this, what I have properly read the stacktrace:
```
$ vendor/bin/phpstan analyse --configuration=phpstan.neon app --debug
…
/vagrant/project/app/Models/SomeModel.php

   Exception

  Unable to resolve PSR response. Please install nyholm/psr7.

  at vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:156
    152|             if (class_exists(PsrResponse::class)) {
    153|                 return new PsrResponse;
    154|             }
    155|
  > 156|             throw new Exception('Unable to resolve PSR response. Please install nyholm/psr7.');
    157|         });
    158|     }
    159|
    160|     /**

      +5 vendor frames
  6   app/Services/Vendor/Illuminate/Foundation/Application.php:51
      Illuminate\Foundation\Application::make()
```
When I looked at `\NunoMaduro\Larastan\Concerns\HasContainer::resolve` and saw the mean `catch` blocks:
```php
        try {
            $concrete = $this->getContainer()
                ->make($abstract);
        } catch (ReflectionException $exception) {
            // ..
        } catch (BindingResolutionException $exception) {
            // ..
        } catch (NotFoundExceptionInterface $exception) {
            // ..
        }
```
The `BindingResolutionException` stood out. I wondered if that code from `\Illuminate\Routing\RoutingServiceProvider::registerPsrResponse` shouldn't rather throw it instead of `\Exception`. At least to me it would make sense.

And lo' and behold, if I change it of course it gets silently caught and the whole process goes on.

I made https://github.com/laravel/framework/pull/32348 in the hopes they accept it!

**Comment by canvural** [comment]
I added [this](https://github.com/nunomaduro/larastan/commit/38058ec4722ee435242ad1be8d5f215cda6fe711) commit. This resolves that TODO comment. So together with the PR you made to framework, this should solve the issue for you, right?

In the future I want to get rid of the `resolve` method completly, but that means a lot of work :smile:

**Comment by mfn** [comment]
Both my Laravel PRs were merged (https://github.com/laravel/framework/pull/32349 and they also made my make one for Lumen ( https://github.com/laravel/lumen-framework/pull/1065 ).

I only needed either the Laravel or the Larastan fix and can already confirm, only with your fix it already works (but the change in Laravel is forthegood/harmless anyway)!

Thanks, issue resolved for me 😄
