### ISSUE TITLE
Static call to instance method Illuminate\Support\Facades\Redirect::intended().

### ISSUE THREAD

**Issue by ejunker** [nunomaduro/larastan#415]
- Larastan Version: 0.5.0
- `--level` used: 1

### Description
Static call to instance method Illuminate\Support\Facades\Redirect::intended().

### Laravel code where the issue was found

```php
return Redirect::intended($url);
```

**Comment by mr-feek** [comment]
I wasn't able to reproduce this on master.

this test case in `RedirectExctension` passed for me
```
/** @test */
    public function it_redirects_facade(): RedirectResponse
    {
        return Redirect::intended();
    }
```

**Comment by ejunker** [comment]
No longer able to reproduce.
