### ISSUE TITLE
Default value of the parameter (null) of function is incompatible with type array

### ISSUE THREAD

**Issue by repat** [nunomaduro/larastan#417]
- Larastan Version: 0.4.3
- `--level` used: 5

### Description
```
Default value of the parameter #2 $userAgent (null) of function http_get() is incompatible with type array.
```

I don't know what array has to do with it? It's supposed to be either a string or `null` (which is also the default value). It has nothing to do with the `! empty()` call or the `['headers' => ['User-Agent' => $userAgent]]` as the error message does not disappear, when I remove those parts.

`http_client()` returns a [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle) instance.

### Laravel code where the issue was found

```php
if (! function_exists('http_get')) {
    function http_get(string $url, ?string $userAgent = null) : string
    {
        $client = http_client();
        if (! empty($userAgent)) {
            $response = $client->get($url, ['headers' => ['User-Agent' => $userAgent]]);
        } else {
            $response = $client->get($url);
        }

        return $response->getBody()->getContents();
    }
}
```

**Comment by szepeviktor** [comment]
Could you share how you call `http_client`?

**Comment by repat** [comment]
```php
if (! function_exists('http_client')) {
    /**
     * Returns GuzzleHttp Client
     *
     * @return \GuzzleHttp\Client
     */
    function http_client()
    {
        return new \GuzzleHttp\Client();
    }
}
```

**Comment by canvural** [comment]
Hi,

Can you share the actual code that is producing the error? Not the `http_get` function definition. But the code where you use it.

**Comment by repat** [comment]
Not sure what you mean. The function works fine, it's just larastan that's throwing the error:

`php artisan code:analyse --paths=app/Helpers/helpers.php`

`helpers.php` the file the function is in.

**Comment by canvural** [comment]
This doesn't look anything related to Larastan or Laravel.

Please open an issue in the PHPStan repository. And try to reproduce your error in phpstan.org
