### ISSUE TITLE
TestCase with custom TestResponse cause mismatch in return type

### ISSUE THREAD

**Issue by deleugpn** [nunomaduro/larastan#418]
- Larastan Version: 6.10.1
- `--level` used: 3

### Description
When overriding `createResponse` in TestCase, Larastan complains that return mismatches.

```
Method Tests\TestCase::get() should return Tests\TestResponse but returns Illuminate\Foundation\Testing\TestResponse.
```

### Laravel code where the issue was found

```php
    public function get($uri, array $headers = []): TestResponse
    {
        return parent::get($uri, $headers);
    }

    public function post($uri, array $data = [], array $headers = []): TestResponse
    {
        return parent::post($uri, $data, $headers);
    }

    public function put($uri, array $data = [], array $headers = []): TestResponse
    {
        return parent::put($uri, $data, $headers);
    }

    public function delete($uri, array $data = [], array $headers = []): TestResponse
    {
        return parent::delete($uri, $data, $headers);
    }

    protected function createTestResponse($response): TestResponse
    {
        return TestResponse::fromBaseResponse($response);
    }
```

The custom TestResponse is a class that inherits from `Illuminate\Foundation\Testing\TestResponse`

**Comment by szepeviktor** [comment]
Pls show the get method of custom TestResponse.

**Comment by szepeviktor** [comment]
You may also consider PHP generics: https://medium.com/@ondrejmirtes/generics-in-php-using-phpdocs-14e7301953

**Comment by deleugpn** [comment]
The `TestResponse` class does not contain a `get` method. The `get` method is inherited (and overridden) from the TestCase class.

**Comment by BertvanHoekelen** [comment]
This is correct behaviour. The parent::get() responds with `Illuminate\Foundation\Testing\TestResponse` and is unaware of your `TestResponse`. If you would have add methods to your custom `TestResponse` you couldn't call them.

```php
class MyTestResponse extends \Illuminate\Foundation\Testing\TestResponse
{
    public function foo()
    {
          //Never getting here   
    }
}

class TestCase extends \Illuminate\Foundation\Testing\TestCase
{
    public function get($uri, array $headers = []): MyTestResponse
    {
        return parent::get($uri, $headers); // Returns instance of \Illuminate\Foundation\Testing\TestResponse which doesn't have the method foo
    }
}
```

**Comment by deleugpn** [comment]
@BertvanHoekelen that is not true. If you take a closer look at the snippet I pasted, you'll see a method called `createTestResponse`. If you look at [Illuminate\Foundation\Testing\Concerns\MakesHttpRequests](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L563), you'll notice that we're free to override what Laravel will return when creating a TestResponse class.

This allows me to put methods inside a custom TestResponse and call them after calling `get()|post()|put()|delete()`. The only reason I actually override these methods and add the type-hint is so PHPStorm offer auto-complete for all my methods in my custom TestResponse. Unfortunately, the static analyse doesn't understand this Laravel offering.

**Comment by BertvanHoekelen** [comment]
Aha, sorry didn't see the `protected function createTestResponse($response): TestResponse`. I think [TestCaseExtension](https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/TestCaseExtension.php) should be expanded to fix the return type. 

However you could fix it with this snippet for now:

```php
public function get($uri, array $headers = []): TestResponse
{
     /** @var \Tests\TestResponse $response */
     $response = parent::get($uri, $headers);

     return $response;
}
```

**Comment by nunomaduro** [comment]
You will need to type-hint with php-docs this as @BertvanHoekelen suggested.
