### ISSUE TITLE
now() helper & CarbonImmutable

### ISSUE THREAD

**Issue by deleugpn** [nunomaduro/larastan#421]
- Larastan Version: 6.11.0
- `--level` used: 5

### Description

With the new `Date` Facade, we're now able to configure Laravel to always use `CarbonImmutable`.

```php
final class CalendarServiceProvider extends ServiceProvider
{
    public function register()
    {
        Date::useMonthsOverflow();

        Date::useYearsOverflow();

        Date::use(CarbonImmutable::class);
    }
}
```

However, the docblock for the helper `now()` (as well as the Date facade itself) says that the return type will be `Illuminate\Support\Carbon`, which extends `Carbon\Carbon` and not `Carbon\CarbonImmutable`. This causes an error with the following message:

`Parameter #x $date of method \My\Class::myMethod() expects Carbon\CarbonImmutable, Carbon\Carbon given.

### Laravel code where the issue was found

```php

function myFunction(\Carbon\CarbonImmutable $date)
{
}

myFunction(now());
```

**Comment by mfn** [comment]
>  Date::use(CarbonImmutable::class);

Happy to see others also doing this!

But it's not just `now()`, `today()` is affected too.

PS: I recently added support for this to ide-helper, i.e. the models $dates and similar will then generate the correct phpdoc with CarbonImmutable

**Comment by deleugpn** [comment]
I don't use `ide-helper` as it causes PHPStorm to give me warnings about every class because they're duplicated, etc.

**Comment by canvural** [comment]
@mfn Is it enough to just use something like `get_class(\Illuminate\Support\Facades\Date::now())` to get the return type?

**Comment by mfn** [comment]
@canvural to my knowledge, yes (see https://github.com/barryvdh/laravel-ide-helper/pull/859/files#diff-9c76e55ce4ef570404e58c82d642c1e5R114-R117 )

**Comment by mr-feek** [comment]
Please remove the good first issue since you have yourself assigned @canvural . Others may think they can help to work on it.

**Comment by canvural** [comment]
@mr-feek Sorry about that. Removed now :+1:
