### ISSUE TITLE
Cache Repository TTL parameter (PSR-16) & Carbon

### ISSUE THREAD

**Issue by deleugpn** [nunomaduro/larastan#422]
- Larastan Version: 6.11.0
- `--level` used: 5

### Description
Laravel 6 improved the PSR-16 implementation. However, Laravel's implementation still accepts a `Carbon` instance as a TTL ([and documents it](https://laravel.com/docs/5.8/cache#storing-items-in-the-cache)). However, since PSR-16 docblock says TTL is only null|int|DateInterval, we have the following error:

```
Parameter #3 $ttl of method Illuminate\Cache\Repository::set() expects DateInterval|int|null, Carbon\Carbon given.
```

### Laravel code where the issue was found

```php

namespace App\Components\Cache;

use Illuminate\Cache\Repository;

class SomeCacheClass
{
    /** @var Repository */
    private $cache;

    public function __construct(Repository $cache)
    {
        $this->cache = $cache;
    }

    public function save(string $value): void
    {
        $this->cache->set('my-key', $value, now()->addDay());
    }
}

```

**Comment by canvural** [comment]
Hi,

If you check the implementation, `set` method just redirects to `put` method. And `put` method has `\DateTimeInterface|\DateInterval|int|null` for `$ttl` parameter.

So you can either use the `put` method directly or open PR in the Laravel repository and change the PHPDoc types for the `set` method.

**Comment by deleugpn** [comment]
I don't think Laravel would be open to changing the `set` docblock as it's an {@inheritdoc} only. However, using the `put` method is a great option. Thank you for that, I should totally have thought of that!
