### ISSUE TITLE
Socialite::driver should not return Contracts\Provider

### ISSUE THREAD

**Issue by bistory** [nunomaduro/larastan#433]
- Larastan Version: 0.5.0
- `--level` used: default

### Description

When calling the scopes function of Laravel Socialite, Larastan return an error (false positive) : 

`Call to an undefined method Laravel\Socialite\Contracts\Provider::scopes()`

### Laravel code where the issue was found

```php
use Socialite;

$driver = Socialite::driver('facebook');
$driver->scopes(['public_profile']);
```

**Comment by szepeviktor** [comment]
Thank you for your report!

We may write code to mitigate that or you may add a comment:

`/** @var someType $driver`

**Comment by bistory** [comment]
Thanks, I have added it waiting for a potential fix and it works 👍

**Comment by canvural** [comment]
Hi,

Thanks for reporting this.

But this is a similar issue to #101, #158 or #203 They are all about facades and the manager pattern being used. So I am closing this as duplicate.
