### ISSUE TITLE
Support for custom Eloquent Collection

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#436]
Users can override the Eloquent's `newCollection` method to return a [custom Eloquent collection](https://laravel.com/docs/6.x/eloquent-collections#custom-collections).

We should add support for this. 

It'll affect the collection returned by methods like `find`, `all` etc. As well as collections returned by relationships.

**Comment by Gummibeer** [comment]
Because it's flagged as `good first issue` - could you point out where the custom collection stuff should hook in/get placed?

**Comment by canvural** [comment]
Hi,

Thanks for taking an interest.

For starters, everywhere we use `Collection::class` in the code, needs to be changed with the custom collection class name. Figuring out if model uses custom collection and getting the custom collection class name can be extracted to a helper class/method. Like in the `BuilderHelper` with `determineBuilderType`

**Comment by Gummibeer** [comment]
I think that we even doesn't have to check if the method is overridden because by default the `newCollection` method returns the default collection. So it could be simpler to just do `get_class($model->newCollection())` all the time!?

I'm not sure when I will find time, but if no one has already started with it I could try it. If I start I will write here - would be great if another dev starting it would also write so we won't do it twice. :)

**Comment by canvural** [comment]
Yes, that can also work. :+1:

**Comment by cweiske** [comment]
When calling a method on that custom collection class that has been returned by `newCollection()`, I still got an error:

> Call to an undefined method Illuminate\Database\Eloquent\Collection<App\Account>::collectionMethod()

The solution was to define a "property-read" for the HasMany-property:
```
@property-read \App\AccountCollection $accounts
```

This was with phpstan 0.12.57, larastan v0.6.10

----

Full code:

AccountCollection.php:
```
<?php
namespace App;
use Illuminate\Database\Eloquent\Collection;
/**
 * @template TModel
 * @extends Collection<TModel>
 */
class AccountCollection extends Collection
{
    function collectionMethod(): void
    {
    }
}
```

Account.php:
```
<?php
namespace App;
class Account extends \Illuminate\Database\Eloquent\Model
{
    /**
     * @param array<int, Account> $models
     *
     * @return AccountCollection<Account>
     */
    public function newCollection(array $models = []): AccountCollection
    {
        return new AccountCollection($models);
    }
}
```

User.php:
```
<?php
namespace App;
use Illuminate\Database\Eloquent\Relations\HasMany;
/**
 * @property-read \App\AccountCollection $accounts <-- This is still required
 */
class User extends \Illuminate\Foundation\Auth\User
{
    public function accounts(): HasMany
    {
        return $this->hasMany(Account::class);
    }

    public function testCollectionMethodCall()
    {
        $this->accounts->collectionMethod();
    }
}
```

**Comment by szepeviktor** [comment]
Very nice tutorial.
Thank you!

**Comment by canvural** [comment]
@cweiske Can you show the code that produces that error?

**Comment by cweiske** [comment]
Yes, that's the one :)

**Comment by canvural** [comment]
@cweiske It's fixed by https://github.com/nunomaduro/larastan/pull/719 You can try it on the `master` branch
