### ISSUE TITLE
Support for Eloquent Resources

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#437]
We should add support for [Eloquent resources](https://laravel.com/docs/6.x/eloquent-resources).

With the help of PHPStan generics, this is really easy to do.

**Comment by mr-feek** [comment]
Since this is listed as a good first issue, would you mind pseudo-coding the implementation? I find it hard to find phpstans documentation on generics

**Comment by szepeviktor** [comment]
You may of course send pseudo code.

**Comment by canvural** [comment]
> Since this is listed as a good first issue, would you mind pseudo-coding the implementation? I find it hard to find phpstans documentation on generics

Sure. First, we need a stub for `Illuminate\Http\Resources\Json\JsonResource` This should be similar to the `EloquentBuilder.stub` we have.

Then we need a new extension that implements both `PropertiesClassReflectionExtension` and `MethodsClassReflectionExtension`

Then you can get the model from the resource like this
```php
$templateTypeMap = $classReflection->getActiveTemplateTypeMap();
$modelType = $templateTypeMap->getType('TModelClass');
```

Then just implement the interface methods with simple calls like `hasMethod` or `hasProperty` on the model reflection.

**Comment by mr-feek** [comment]
fantastic @canvural , I'd like to take a stab at this 🙌

**Comment by mr-feek** [comment]
note: also remove - Illuminate\Http\Resources\Json\JsonResource as a universalObjectCrate!

**Comment by mr-feek** [comment]
@canvural does this stub look right? And I added it to the extension'sstubFiles...


```
<?php

namespace Illuminate\Http\Resources\Json;

/**
 * @template TModelClass
 * @implements \ArrayAccess<string, mixed>
 */
class JsonResource implements \ArrayAccess
{
    /**
     * @var TModelClass
     */
    public $resource;

    /**
     * @param TModelClass $resource
     */
    public function __construct($resource)
    {
        $this->resource = $resource;
    }
}

```

However, my extension keeps returning null for 

```
public function hasProperty(ClassReflection $classReflection, string $propertyName): bool
    {
        if (!$classReflection->isSubclassOf(JsonResource::class)) {
            return false;
        }

        dd($classReflection->getTemplateTypeMap());
```

Trying to figure all this out! Appreciate any guidance.

**Comment by mr-feek** [comment]
Ah, I've figured out a way..

Creating a `UserResource` with an `@extends JsonResource<User>` annotation. Is that what we are expecting to have to do?

and then in the extension...

```
public function hasProperty(ClassReflection $classReflection, string $propertyName): bool
    {
        if (!$classReflection->isSubclassOf(JsonResource::class)) {
            return false;
        }

        $templateTypeMap = $classReflection->getParents()[0]->getActiveTemplateTypeMap();
...
```

That returns the correct type. Am I going down the correct path?
