### ISSUE TITLE
Call to an undefined method user()

### ISSUE THREAD

**Issue by ghost** [nunomaduro/larastan#44]
```php
auth()->user()
```

No error on
```php
Auth::user()
```

> Call to an undefined method Illuminate\Contracts\Auth\Factory|Illuminate\Contracts\Auth\Guard::user()

I think the code above is also often used in many different projects.

**Comment by nunomaduro** [comment]
Do you mind of doing: `composer update nunomaduro/larastan`? That problem was already fixed on previous versions.

Please make sure you use the following composer configuration:
```
        "nunomaduro/larastan": "^0.1",
```

**Comment by ForzaSFerrari** [comment]
My composer.json says
```php
"nunomaduro/larastan": "^0.1.0",
````
and my composer.lock
```php
"name": "nunomaduro/larastan",
"version": "v0.1.2",
```

I also tried your statement, but nothing has been changed.

**Comment by ForzaSFerrari** [comment]
Have to add `id()` as well.

```php
auth()->id()
```

**Comment by stelgenhof** [comment]
I am running larastan 0.3.12 and get this as well (when using `Guard::user()`)

**Comment by UksusoFF** [comment]
Same trouble with `auth()->check()`.

**Comment by Okipa** [comment]
Seems that a regression happened on v0.3.21 of larastan.   
I encounter those 3 errors during a run :
- `Call to an undefined method Illuminate\Contracts\Auth\Factory::check().`
- `Call to an undefined method Illuminate\Contracts\Auth\Factory::user().`
- `Call to an undefined method Illuminate\Contracts\Auth\Factory::id().`

Is anybody else encountering this ?
