### ISSUE TITLE
What is waiting to be included in v0.5.1?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#441]
Which issue needs to be resolved or feature developed?

**Comment by canvural** [comment]
Actually only #430 is actually blocking now. But I'd like to include also #432 and #435 in the 0.5.1 release

**Comment by nunomaduro** [comment]
You guys are amazing.

**Comment by canvural** [comment]
@nunomaduro You still have to merge or approve them :smile:

**Comment by nunomaduro** [comment]
I will check them tonight!

**Comment by canvural** [comment]
0.5.1 is released today! :tada:

**Comment by szepeviktor** [comment]
What a release.
Thank you @canvural !
