### ISSUE TITLE
Collection doesn't return correct model instance

### ISSUE THREAD

**Issue by BertvanHoekelen** [nunomaduro/larastan#452]
- Larastan Version: 0.5.1
- `--level` used: max

### Description
When getting the first value in a collection the return type is invalid. You get the error:
`testAllFirst() should return App\\User but returns Illuminate\\Database\\Eloquent\\Model|null.`

### Laravel code where the issue was found

```php
/**
* @return User
*/
public function testAllFirst(): User
{
    return User::all()->first();
}
```

**Comment by BertvanHoekelen** [comment]
@canvural Can you point me in the right direction?

**Comment by canvural** [comment]
We need to make sure `all` method returns generic collection with the model. `first` will work then, thanks to the stub.

So I think the place to investigate is `ReturnTypes/ModelExtension`

**Comment by BertvanHoekelen** [comment]
Thanks! Will try to find and squeeze this bug.
