### ISSUE TITLE
Model is not returned from custom builder when stored in a variable

### ISSUE THREAD

**Issue by BertvanHoekelen** [nunomaduro/larastan#456]
- Larastan Version: 0.5.1
- `--level` used: max

### Description
When a custom builder is set to a temporary variable it's impossible to get the model when calling `first` or `firstOrFail.` on that variable.

### Laravel code where the issue was found
Duplicating [this test](https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/CustomEloquentBuilderTest.php#L40) method and storing the builder to a temporary variable will fail the test with
`Method Tests\\Features\\ReturnTypes\\CustomEloquentBuilderTest::testFindAfterCustomBuilderMethodAfterDynamicWhere() should return Tests\\Features\\ReturnTypes\\ModelWithCustomBuilder|null but returns Tests\\Features\\ReturnTypes\\CustomBuilder|null.`
```php
public function testFindAfterCustomBuilderMethodAfterDynamicWhere(): ?ModelWithCustomBuilder
{
    $query = ModelWithCustomBuilder::whereFoo(['bar'])->type('foo');
    return $query->first();
}
```

**Comment by canvural** [comment]
Fixed in #457. Thanks!
