### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Facades\Cache::lock()

### ISSUE THREAD

**Issue by jcalonso** [nunomaduro/larastan#458]
- Larastan Version: 0.5.1
- Laravel Version: 6.14.0
- `--level` used: 1

### Description
phpstan reports:
Call to an undefined static method Illuminate\Support\Facades\Cache::lock()
Cant find whats wrong.

### Laravel code where the issue was found

```php
Cache::lock($lock)->get(...);
```

**Comment by canvural** [comment]
Hi,

Which cache driver are you using? Because `lock` method is available in some of the drivers not all.

**Comment by jcalonso** [comment]
Ah! excellent point. I have set the default as file in dev, but in prod is using Memcached.
I will add this error to the `ignoreErrors` array.
Unless you can recommend a better way to handle this cases.

**Comment by canvural** [comment]
Ignoring the error is not the best option I guess. Your code will not work on dev like this. Either you can also set the driver to Memcached on dev, or you can surround the code with `method_exists` checks.
