### ISSUE TITLE
Run static analysis on the /tests directory too

### ISSUE THREAD

**Issue by mr-feek** [nunomaduro/larastan#462]
### Description
When running `composer test`, also run `phpstan` on the `tests` directory.  You'll notice lots of errors, which will help us uncover more issues with this library.

Currently there are 153 errors with phpstan in the test suite.

**Comment by szepeviktor** [comment]
Thank you for your suggestion.

You're welcome to open a PR that **starts** to fix those errors.

**Comment by mr-feek** [comment]
Sorry, there are only 10 errors when including this extension in the phpstan config! I didn't realize that it wasn't already included. I'll work on getting some PRs up.
