### ISSUE TITLE
Optimize laravel/framework for better static analysis?

### ISSUE THREAD

**Issue by voku** [nunomaduro/larastan#465]
Maybe some people here can help to improve laravel itself? I see thousands of error messages, if I run phpstan / psalm on the framework code, but I think we can fix many of them without more magic, but with some assert() calls, type hints and better phpdocs. What do you think? Where should we start?

Some days ago, I started with this small pull request: ⇾ https://github.com/laravel/framework/pull/31388/files

**Comment by mr-feek** [comment]
I think this would be better to open up as an issue/discussion on laravel ideas, rather than in larastan :) But i totally agree with you

**Comment by voku** [comment]
@mr-feek https://github.com/laravel/ideas/issues/2057 :)

**Comment by canvural** [comment]
We can use https://github.com/laravel/ideas/issues/2057 as a place to discuss this. Closing this.
