### ISSUE TITLE
Relationship count should be recognized as property

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#466]
From the [docs](https://laravel.com/docs/6.x/eloquent-relationships#counting-related-models):

> If you want to count the number of results from a relationship without actually loading them you may use the withCount method, which will place a {relation}_count column on your resulting models.

We should add support for this. It should be simple check. If a property named `{relation}_count` is accessed on the model, and `{relation}` method exists in the model, then we can say this property also exists. And has an `integer` type.

**Comment by mr-feek** [comment]
@canvural can we say it always exists, or do we need to somehow check if `withCount` has been called in the same scope?

**Comment by mr-feek** [comment]
I'm guessing whether or not the property can be accessed can be a rule

**Comment by edwinvdpol** [comment]
I also have a lot of `_count` warnings.
Does the support of `_count` properties become a rule eventually, or?

**Comment by canvural** [comment]
@edwinvdpol No, it's not about a rule. There needs to be an addition in `ModelRelationsExtension`

If you are interested you can make a PR! You can take a look at #525, and try to finish it.

**Comment by spawnia** [comment]
Is there any difference between using `->{relation}()->count()` and the magic `_count` property?

**Comment by canvural** [comment]
@spawnia The magic `_count` property is only available if you loaded the count before, with `withCount('relation')` method.

But under the hood, I guess they are doing similar things.

**Comment by MarianoMoreyra** [comment]
> The magic _count property is only available if you loaded the count before, with withCount('relation') method.

Actually, it will also be available if you call `loadCount('relation')` after getting the resulting models or if you add any relationships to the `protected $withCount = []` property (although in this case it will end up doing a `->withCount(''relationship)` call under hood).

The problem is that you can alias this property to anything you want, just by doing:
```php
protected $withCount = ['relationship as count_alias'];

// OR

App\Model::withCount('relationship as count_alias')->get();
```
in which case I don't see how it could be recognized as a relationship count although that might be treated as a separate case right?

**Comment by canvural** [comment]
> The problem is that you can alias this property to anything you want, just by doing:

Yeah, we can't detect this. In that case, it's better if the user adds this property to the docblocks of the class.

**Comment by MatanYadaev** [comment]
@canvural There's an option to add a property to class' docblock within the local scope? 

Something like:

```php
<?php

/** @var WithProperty<User, posts_count, int> $user */
$user = User::withCount('posts')->firstOrFail();

echo $user->posts_count; // Infered as `int`
```

If it doesn't exist today, is that feasible to implement?

**Comment by canvural** [comment]
@MatanYadaev That is not possible and doable.

You can add `/** @property int $posts_count */` above your `User` class.

**Comment by MatanYadaev** [comment]
@canvural Bummer. My models have tens of custom aliases. I'm not sure I want to add all of these aliases to the models' codeblocks. The issue with that is my models will have too many auto-complete nullable properties. I guess that PHPStan will even alert to check that the property isn't null (although I know for sure it's not null in this scope).
