### ISSUE TITLE
wrong return type when using model with()

### ISSUE THREAD

**Issue by GeNyaa** [nunomaduro/larastan#469]
- Larastan Version: 0.5.2
- `--level` used: 5

### Description
When using `::with()` in model statement phpstan throws error of wrong return type while using it later `->with()` instead works fine.
Error:
`Method App\Services\ProcessRecords\Transactions\ProcessTravelTransactionRecord::getOwnershipWithCardAndUser() should return App\Ownership but returns  
         Illuminate\Database\Eloquent\Builder<mixed>|Illuminate\Database\Eloquent\Model.  `

### Laravel code where the issue was found

doesn't work:
```php
private function getOwnershipWithCardAndUser(array $ownershipsIds): Ownership
{
    return Ownership::with('card.users')->whereHas('card')->whereIn('number', $ownershipsIds)->firstOrFail();
}
```
does work:
```php
private function getOwnershipWithCardAndUser(array $ownershipsIds): Ownership
{
    return Ownership::whereHas('card')->with('card.users')->whereIn('number', $ownershipsIds)->firstOrFail();
}
```

**Comment by mr-feek** [comment]
I wonder if this is someting to do with `whereHas`, because otherwise wouldn't https://github.com/nunomaduro/larastan/blob/master/tests/Features/Methods/ModelExtension.php#L182-L196 be failing?
