### ISSUE TITLE
[Enhancement] Inspect fields queried for in eloquent where clauses

### ISSUE THREAD

**Issue by mr-feek** [nunomaduro/larastan#472]
### Description
Now that model's aren't `universalObjectCratesClasses`, we have a better idea of what properties exist on a model.

We should be able to inspect parameters passed to the likes of `Model::where()` to determine if they exist or not.

IE https://github.com/nunomaduro/larastan/blob/master/tests/Features/Methods/ModelExtension.php#L182-L196 should really be failing test cases, considering `foo` is not a relation on the model

**Comment by canvural** [comment]
This is really interesting! We can also do the same thing for dynamic wheres and passed arguments. Like `Model::whereIdAndEmail(5, 'foo#example.com')`

Just thinking how valuable it'd be before spending time to implement it :thinking:

**Comment by ondrejmirtes** [comment]
I think it's very valuable, we're doing something similar in phpstan-doctrine.

**Comment by mr-feek** [comment]
I am leaving my issue closed until it is clear to everyone that their input, help, and collaboration is not welcome nor desired by the maintainers of this project.

**Comment by canvural** [comment]
@mr-feek I'm sorry you are feeling that way! We, of course, appreciate all the help we can get. And we show it in every case. In the issues, comments, or on Twitter.

In your case, I already explained the reason I closed your PR and said that I'm sorry to cause confusion.

**Comment by nunomaduro** [comment]
@mr-feek I am sorry you feel this way, you know. Sometimes you manage multiple open source projects, that are used by thousands of developers,  in your limited time each day, confusions may happen. I am sure we want collaboration.

**Comment by mr-feek** [comment]
However in this specific case, no collaboration is desired. I had an idea, and began working on it when I had time (and am actually done it now and using it personally). It could be committed here for all to benefit, however Can wants do it himself. 

There is a communication gap here. Can non-contributors only work on issues with “help wanted”, labels, the rest are only for maintainers to fix? Surely there is a better way than that. 

I’ve opened several PRs here and hoped to continue doing so, however it has been quite a frustrating experience.
