### ISSUE TITLE
Handle TestResponse::macro()

### ISSUE THREAD

**Issue by ejunker** [nunomaduro/larastan#473]
- Larastan Version: 0.5.1
- `--level` used: 1

### Description
I created a TestResponse macro and getting errors like:

```
Using $this outside a class.
Undefined variable: $this
```

### Laravel code where the issue was found

```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestResponse;

TestResponse::macro(
    'dumpResponse',
    function () {
        /** @var TestResponse $this */
        echo $this->baseResponse;

        return $this;
    }
);

```

I thought the `@var` annotation would help but it still gets errors. I found this possibly related issue phpstan/phpstan#2296

**Comment by canvural** [comment]
Hi,

This seems to be related to PHPStan itself, not to Larastan. [Here](https://github.com/phpstan/phpstan/issues/2296#issuecomment-565422047) it's been said that it's fixed. But if you still have issues you can open a new issue at PHPStan.
