### ISSUE TITLE
[Enhancement] Clean up directory structure

### ISSUE THREAD

**Issue by mr-feek** [nunomaduro/larastan#478]
### Description
I would like to propose a refactor in which we clean up the directory structure. It is quite confusing coming into this project wanting to be a contributor, as there are lots of `Reflection` classes in the `Properties` namespace, helpers riddled around the place, etc. It's difficult to determine where certain logic should be placed.

### Proposal
```
- src
    - Scopes
    - Concerns
    - Contracts
    - Extensions
        - Methods
        - Properties
        - ReturnTypes
    - Helpers
    - Reflections
    - Schema
    - Types
```

Would a PR implementing a restructure like this be welcomed?

**Comment by canvural** [comment]
Yes, a cleanup would be good. You can create a PR and we can discuss the details there.
