### ISSUE TITLE
request for laravel 7 support

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#484]
- Larastan Version: #.#.#
- `--level` used:

### Description
Please add support for  Laravel 7

### Laravel code where the issue was found

```php

```

**Comment by nunomaduro** [comment]
@harrisdt15f Why you say that we don't have support for Laravel 7?

**Comment by harrisdt15f** [comment]
sorry my version is 0.4.3 I need to update to latest thank you.
