### ISSUE TITLE
Errror on Container tag()

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#486]
- Larastan Version: v0.5.2
- `--level` used: max

### Description
Illuminate\Contracts\Container\Container::tag() expects array<int,  
         mixed>, string given.

### Laravel code where the issue was found

`$this->app->tag([App\Game\GameModule\KyGame::class], GameIF::class);`

**Comment by canvural** [comment]
Hi,

I think this can be fixed in the Laravel repo by making the actual parameter `$tags` variadic in the method definition.

Also, you can try to open an issue in PHPStan repo. Maybe PHPStan can read that the variable is variadic from the phpdocs.
