### ISSUE TITLE
Undefined property: PhpParser\Node\Expr\StaticCall::$var 

### ISSUE THREAD

**Issue by m50** [nunomaduro/larastan#488]
- Larastan Version: 0.4.3
- PHPStan Version: 0.11.19
- `--level` used: 5

### Description

I am seeing this issue when I am running PHPStan:

In RelationCreateExtension.php line 173:
                                                            
  Undefined property: PhpParser\Node\Expr\StaticCall::$var  

I only get this problem when I run it with Larastan. If I disable Larastan, it's fine. (But then I have a ton of other issues caused by not having larastan features).

### Laravel code where the issue was found

I can't really provide this, as it just tells me it about the whole controller.

I don't know how to get a stack trace, because running it with `--debug` just provides that.

**Comment by m50** [comment]
Actually, by commenting things out, I was able to narrow it down to this code:

```php
$entry = Auth::user()->otp()->create([
            'secret'  => $valid['secret'],
            'options' => '', //TODO
            'flavour' => '',
        ]);
```

With that commented out, no issue. With it there, the error above is given.

**Comment by canvural** [comment]
Hi,

You are using an older version. This issue is fixed in the newer releases. So please try to upgrade Larastan.
