### ISSUE TITLE
Model's dates are forced to use Illuminate\Support\Carbon

### ISSUE THREAD

**Issue by arxeiss** [nunomaduro/larastan#495]
- **Larastan Version: dev-master**
- `--level` used: 6

### Description
This ticket follows conversation opened in #494 <br>
After updating to dev-master I got errors related to Carbon in models.

### Laravel code where the issue was found

When assigning Carob::now() into models attribute, this pops out `Property SunApp\Models\Term::$start (Illuminate\Support\Carbon|string|null) does not accept Carbon\Carbon.` like this in code below.

```php
use Carbon\Carbon;

$term->start = Carbon::now();
```

Issues thrown: `Cannot call method diffInDays() on string.` , `Cannot call method format() on string.` and `Cannot access property $year on string.` All of them are on lines in getTermRangeAttribute method.

```php
use Carbon\Carbon;

/**
 * @property Carbon $start
 * @property Carbon $end
 */
class Term extends BaseModel
{
    protected $casts = [
        'start'             => 'date',
        'end'               => 'date',
    ];

    /**
     * Eloquent method for getting date "name", ie start and end date formatted
     */
    public function getTermRangeAttribute(): string
    {
        if ($this->start->diffInDays($this->end) === 0) {
            $termRange = $this->start->format('d.m.Y');
        } else {
            $start = $this->start->format('d.m.');
            if ($this->start->year != $this->end->year) {
                $start .= $this->start->year;
            }
            $end = $this->end->format('d.m.Y');
            $termRange = "{$start} - {$end}";
        }
        if (!empty($this->label)) {
            $termRange .= " - {$this->label}";
        }

        return $termRange;
    }
}
```

**Comment by szepeviktor** [comment]
Thank you for your report.

Have you search for Carbon in PHPStan's issues?

**Comment by canvural** [comment]
It is about [this line](https://github.com/nunomaduro/larastan/blob/master/src/Properties/ModelPropertyExtension.php#L137) I think.

`Carbon\Carbon` can be added there at the end of string like `|Carbon\Carbon`

**Comment by szepeviktor** [comment]
See the solution in https://github.com/nunomaduro/larastan/pull/496#issuecomment-600554700
