### ISSUE TITLE
Consider 1.0 as next release

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#504]
I think we can consider 1.0 as the next release. We will not have any major features any time soon I'm guessing. And existing features are pretty stable in my opinion. In a few of my work projects, I was able to perform analysis on level 6 and it was ok.

What are your thoughts? cc @nunomaduro, @szepeviktor

**Comment by szepeviktor** [comment]
Okay!
Wait 10 days and bump major version.

**Comment by nunomaduro** [comment]
My opinion is: I agree. I also trust to take the best decision on this one.

**Comment by mr-feek** [comment]
I think we are close, we need to do a bit better of a job of documentation. 

For example, i don’t believe there’s anything in the readme about how to declare the model template for eloquent resources, it’s only in the upgrade guide. 

Shall we go through the upgrade guide and document the important bits in the readme?

**Comment by canvural** [comment]
@mr-feek That's a good idea, we can do it.

Also something to think about is that PHPStan itself is not in 1.0, should we wait for it? Does it really matter I don't know.

**Comment by ondrejmirtes** [comment]
I expect PHPStan to hit 1.0 in winter 2020/21.

**Comment by canvural** [comment]
> I expect PHPStan to hit 1.0 in winter 2020/21.

Oh, that's great!

**Comment by nunomaduro** [comment]
I would say: Let's follow him on this one.

**Comment by canvural** [comment]
As decided, we can tag 1.0 after PHPStan 1.0 is released.
