### ISSUE TITLE
Database migrations path should be configurable

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#507]
Right now we assume users have the migrations in the default place. That is at the project root under `database/migrations` folder.

We can make this configurable in the user's `phpstan.neon` file. So, people who have it in a different location can set it and take advantage of type inference for their model properties.

It should default to `database/migrations` And it should be allowed to set it to null or empty as pointed out by @deleugpn [here](https://github.com/nunomaduro/larastan/pull/498#issuecomment-601066926). In that case, model property analysis should be just skipped.

**Comment by szepeviktor** [comment]
Oh yes!

**Comment by szepeviktor** [comment]
@canvural May I add a word about `databaseMigrationsPath` to the CHANGELOG?

**Comment by canvural** [comment]
@szepeviktor Yeah definitely! Also maybe we can add a new section to README about available configuration values.
