### ISSUE TITLE
Undefined property UserResource::$pivot

### ISSUE THREAD

**Issue by ludo237** [nunomaduro/larastan#515]
- Larastan Version: 0.5.5
- `--level` used: 1

### Description

The command `larastan analyse` throws an error on JsonResources that use `$this->pivot`. I've an User model with a m:m relationship to another table. `UserResource` will load some data of the pivot table if it is requested using the method `whenPivotLoaded`. The problem is that Larastan does not recognize the pivot as a valid property.

The error that Larastan throws is this:

```json
 {
        "description": "Access to an undefined property App\\Http\\Resources\\UserResource::$pivot.",
        "fingerprint": "b910d56075e641d4c94e7412d3e499d7b832002568a667e1d5ee2ca0c888e18b",
        "location": {
            "path": "app/Http/Resources/UserResource.php",
            "lines": {
                "begin": 45
            }
        }
    },
```

### Laravel code where the issue was found

```php
/**
 * @extends JsonResource<\App\User>
*/
class UserResource extends JsonResource
{
    // Other parts of the resource omitted
    public function toArray($request)
    {
        return [
              "time_to_live" => $this->whenPivotLoaded("table", function () {
                return $this->pivot->time_to_live;  // This is the line 45
            })
         ];
      }
}

```

**Comment by canvural** [comment]
Thank you for reporting!

I guess we can add a special case for `pivot` with return type `mixed`

**Comment by ludo237** [comment]
Yea I was digging into the source code in hope to help find a solution and that seems the right way to do it, just "white list" it

**Comment by mr-feek** [comment]
Hm,  I don't necessarily think this is specific to resources. @ludo237 does this problem exist outside of resources in your codebase?

**Comment by ludo237** [comment]
The only error that larastan triggers is on $pivot property on JsonResources. I've used the reccomended PHPDoc for larastan 0.5+

**Comment by canvural** [comment]
One of the possible solutions is we can tell in `ModelPropertiesExtension` that `pivot` exists in `Model`. And also add `\Illuminate\Database\Eloquent\Relations\Pivot` to the `universalObjectCrates` Because we can't tell which properties exist on the pivot table.

**Comment by mr-feek** [comment]
I see, we'll also have to account for the customized `pivot` attribute name, as it can't be assumed to be `pivot`

**Comment by ludo237** [comment]
@mr-feek a configuration should do the trick

**Comment by ludo237** [comment]
**UPDATE**

Apparently you can easily fix this without any change to this package. Basically if you call `getRelationValue("pivot")` instead of relying to the magic property Larastan gets happy about it 🤣 

@mr-feek @canvural 

```PHP
/**
 * @extends JsonResource<\App\User>
*/
class UserResource extends JsonResource
{
    // Other parts of the resource omitted
    public function toArray($request)
    {
        /** @var \App\User **/
        $user = $this;
        return [
              "time_to_live" => $this->whenPivotLoaded("table", function () use($user) {
                return $user->getRelationValue("pivot")->time_to_live;  // This is the line 45
            })
         ];
      }
}
```

**Comment by nunomaduro** [comment]
Please re-open the issue if this issue still exists in the latest version.

**Comment by iraklisg** [comment]
The issue still exists. Using the workaround `getRelationValue("pivot")` proposed by @ludo237 we can bypass this error

**Comment by ludo237** [comment]
Speaking for myself I get used to avoid magic methods for Eloquent ORM because they produce more headaches that anything else so for instance instead of `$model->colum_name` I'd rather use `$model->getAttributeValue("my_column_name")`, same goes for relationships etc.

Magic methods seems to be a problem with almost every static analyser not only Larastan and, in my opinion, the code result is messier with them

**Comment by F-Yousri** [comment]
thank you @ludo237 for the workaround
I still tend to think Larastan should handle the magic method as it does with many other Laravel magic methods since it's probably the very reason Larastan is wrapping PHPstan.

**Comment by bernardwiesner** [comment]
Agree with @F-Yousri , larastan should deal with this, since its a common use case and even in the official docs: https://laravel.com/docs/8.x/eloquent-relationships#retrieving-intermediate-table-columns

**Comment by djjavo** [comment]
Is the solution still to use the workaround `getRelationValue("pivot")`?

**Comment by amooij** [comment]
The workaround doesn't work for the higher levels of phpstan.

**Comment by koenhendriks** [comment]
I've ran into this issue and using `getAttributeValue` seems to work on `level: max` (@amooij ) if you assign the `Pivot` to the property in a doc block of the model.

Model:
```php
use Illuminate\Database\Eloquent\Relations\Pivot;

/**
 * @property ?Pivot $results
 */
class Competition extends Model {
    public function contenders(): BelongsToMany
    {
        return $this->belongsToMany(Contender::class)
            ->as('results')
            ->withPivot('pivot_data');
    }
}
```
And implemented like this:
```php
$competition->results->getAttributeValue('pivot_data')
```

**Comment by leecolarelli-tgb** [comment]
Issue still present in Larastan v2.6.4.

Is the accepted solution to use `getAttributeValue` or `getRelationValue` then? I'm happy with either solution, but what @F-Yousri said in his last comment is correct.

**Comment by maxxwv** [comment]
This is still an issue and not specific to resources. I'm working with an Event and using the following code:
```
namespace App\Events;
class AddItemToListEvent
{
    use Dispatchable, InteractsWithSockets, SerializesModels;
/* ... */
    /**
     * Get the channels the event should broadcast on.
     *
     * @return array<int, Channel>
     */
    public function broadcastOn(): array
    {
        return [
            new PrivateChannel('list-'.$this->item->shoppingList->id.'-add-item'),
        ];
    }
}
```
results in `Access to an undefined property Illuminate\Database\Eloquent\Model::$id.`. If I change the return value to this:
```
            new PrivateChannel('list-'.$this->item->shoppingList->getAttributeValue('id').'-add-item'),
```
it works as expected.
