### ISSUE TITLE
Class mixed was not found

### ISSUE THREAD

**Issue by j6s** [nunomaduro/larastan#516]
- Larastan Version: 0.5.1 and higher
- `--level` used: 2

### Description
After updating to laravel 7 and larastan 0.5.x my codebase produced the following error on nearly all query builder methods:

```
Class mixed was not found while trying to analyse it - autoloading is probably not configured properly.
```

After jumping through a couple of version combinations I noticed that everything worked fine with larastan 0.5.0 but the issue started occurring with 0.5.1 and later.

I had a quick glance at the changes between the two versions and noticed, that `ModelPropertyExtension::getReadableAndWritableTypes` is returning `'mixed'` as a string instead of an instance of `MixedType` - could that already be the source of this issue?

### Laravel code where the issue was found

```php
    public function priceGroups(): HasMany
    {
        return $this
            ->hasMany(PriceGroup::class, 'price_information_id')
            ->orderBy('sorting', 'ASC');
    }
```

**Comment by canvural** [comment]
It doesn't seem to be related to `ModelPropertyExtension` There is no property access on a model in the code you shared.

Do you get more information when you run with `--debug` flag?

**Comment by mfn** [comment]
I've a very similar error but getting `self` instead of mixed:
```
 ------ --------------------------------------------------------------------------------------------------------
  Line   Some/Klass.php
 ------ --------------------------------------------------------------------------------------------------------
         Class self was not found while trying to analyse it - autoloading is probably not configured properly.
  56     Class self was not found while trying to analyse it - autoloading is probably not configured properly.
  56     Class self was not found while trying to analyse it - autoloading is probably not configured properly.
  56     Class self was not found while trying to analyse it - autoloading is probably not configured properly.
 ------ --------------------------------------------------------------------------------------------------------
```
Not kidding, the first line does truly not report a (line) number. Since it doesn't "crash", adding `--debug` didn't reveal anything.

The reported line looks like this:
```php
            Model
                ::whereIn(
                    'some_column',
                    $anotherModel
                    ->children() # <- a `HasMany` relation defined as `return $this->hasMany(self::class, 'parent_id');`
                    ->pluck('id')
                );
```
In my case its triggered because I call `pluck` directly on the relation; if I insert `->get()` the reported error is gone:
```php
            Model
                ::whereIn(
                    'some_column',
                    $anotherModel
                    ->children()
                    ->get() # <- line added
                    ->pluck('id')
                );
```
I think the repeated reported in due to the span across so many lines, it changes when I join the lines etc.

Do you think it's the same problem or should I open a separate issue?

**Comment by canvural** [comment]
@mfn I think this is only happening at the current `master`?

I don't know the reason for the original issue, but I guess I know the reason for your case. You can create a new issue, and I'll try to come up with a fix.

**Comment by mfn** [comment]
> You can create a new issue, and I'll try to come up with a fix.

Thank you 🙏  => https://github.com/nunomaduro/larastan/issues/531

**Comment by canvural** [comment]
@j6s I'm unable to reproduce this with the example you shared. Can you provide more information about the issue? Also can you test with the latest `master` branch?

**Comment by j6s** [comment]
I just checked it again after updating from larastan `0.5.0` and phpstan `0.12.25` to larastan `dev-master#44535adce4fda0ac4d9fe175318fb91959dbb2b4` and phpstan `0.12.28`.

Seems like the older version of `thecodingmachine/safe` that I have in this project has some compatibility issues, but I can no longer reproduce the initially reported problem in my project.

Closing this issue.
