### ISSUE TITLE
Call to protected method increment() 

### ISSUE THREAD

**Issue by edwinvdpol** [nunomaduro/larastan#523]
- Larastan Version: 0.5.5
- `--level` used: 5

### Description
Got the following warning when analizing:

`Call to protected method increment() of class Illuminate\Database\Eloquent\Model.`

### Laravel code where the issue was found

```php
$something->statistics()->firstOrCreate(['day' => today()->toDateString()])->increment('certain_count');
```

**Comment by canvural** [comment]
Hi,

I believe this was because Larastan couldn't determine the returned model type after `firstOrCreate`

I've [updated](https://github.com/nunomaduro/larastan/commit/af981c61d94368f28c72e5e6710cd38ba1afc5c4) the stubs. I believe that will fix it.

Thank you!
