### ISSUE TITLE
Question : Is there a reason for "php": "^7.2" ?

### ISSUE THREAD

**Issue by fico7489** [nunomaduro/larastan#526]
can we downgrade to 7.1  ?

**Comment by nunomaduro** [comment]
The maintainers don't use that version of PHP.

**Comment by szepeviktor** [comment]
Please also see https://www.php.net/supported-versions.php

**Comment by canvural** [comment]
The reason is Laravel 6 and 7 require minimum PHP version 7.2. And Larastan supports Laravel 6 or higher.
