### ISSUE TITLE
PhpStorm shows 'Multiple definitions exists for class'

### ISSUE THREAD

**Issue by mariomka** [nunomaduro/larastan#527]
- Larastan Version: 0.5.5

### Description

PhpStorm shows 'Multiple definitions exist for class' warnings. It breaks code assistance.

Check the following screenshots.

![image](https://user-images.githubusercontent.com/1822472/78979153-8a216800-7b1b-11ea-9f4f-ef9ea6784445.png)

![image](https://user-images.githubusercontent.com/1822472/78979170-91e10c80-7b1b-11ea-9416-d5268fa9ada5.png)

![image](https://user-images.githubusercontent.com/1822472/78979193-9c9ba180-7b1b-11ea-8289-06e875a20886.png)

It seems to be related to stubs defined in the package.

### Laravel code where the issue was found

Declaring a model is an example.

```php
<?php

declare(strict_types=1);

namespace Domain\Campaign\Model;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
}
```

**Comment by szepeviktor** [comment]
Very interesting!

**Comment by nunomaduro** [comment]
@mariomka We are not sure how to improve this. Can you investigate this?

**Comment by canvural** [comment]
The stubs in Larastan are not even php files. They have `.stub` extensions for this very reason.

So check your IDE settings, I believe you associated `stub` extensions with PHP files.

**Comment by mariomka** [comment]
@canvural Yep! I removed `.stub` extension from PHP file types. I don't know if this extension is set by default or maybe I added it.

Thank you all.
