### ISSUE TITLE
\Illuminate\Database\Eloquent\Relations\Relation not treated as \Illuminate\Database\Eloquent\Builder

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#532]
- Larastan Version: master at https://github.com/nunomaduro/larastan/commit/15e8d17cbccbf83bcebadbf581a037920803f510
- `--level` used: 6

### Description
I _think_ the issue description is the one I want to go for, not exactly sure TBH; this is the reported error:
> ` Parameter #1 $builder of method Repo::addSomeImportentConditions() expects Illuminate\Database\Eloquent\Builder, Illuminate\Database\Eloquent\Relations\HasManyThrough<App\Table2> given.`

### Laravel code where the issue was found
I've a helper method defined like this:
```php
    /**
     * @param Builder|QueryBuilder $builder
     * @return Builder|QueryBuilder
     */
    private function addSomeImportentConditions($builder)
    {
        return $builder
            ->where('table1.deleted', '=', false)
            ->where('table2.deleted', '=', false)
            ->whereNull('table2.parent_id')
            ->whereIn('table2.type', ['foo', 'bar']);
    }
```
and I use it from code like this:
```php
    public function someImportantMethod(Model $model): int
    {
        return (int) $this
            ->addSomeImportentConditions($model->thisIsAHasManyThroughRelation())
            ->sum('table2.some_aggregate_column');
    }
```
The `thisIsAHasManyThroughRelation` is defined as:
```php
    public function thisIsAHasManyThroughRelation(): HasManyThrough
    {
        return $this->hasManyThrough(Table2::class, Table1::class);
    }
```

Now, `HasManyThrough` is a `Relation` defined as:
```php
/**
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
abstract class Relation
```
I.e. internally it forwards certain calls to the builder, see the `__call` method:
```php
    /**
     * Handle dynamic method calls to the relationship.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }

        $result = $this->forwardCallTo($this->query, $method, $parameters);

        if ($result === $this->query) {
            return $this;
        }

        return $result;
    }
```
This means I can technically use the relation directly and call `->where()` etc. on it which I'm doing in `addSomeImportentConditions`.

### Workaround
I can write this code and it works, i.e. adding `->getQuery()` on the relationship:
```php
    public function someImportantMethod(Model $model): int
    {
        return (int) $this
            ->addSomeImportentConditions($model->thisIsAHasManyThroughRelation()->getQuery())
            ->sum('table2.some_aggregate_column');
    }
```

**Comment by canvural** [comment]
Hi,

I think this is normal behavior. You are expecting `Builder|QueryBuilder` type in `addSomeImportentConditions` method, but you are passing `Relation` (`HasManyThrough` in this case) Doesn't matter if relation forwards calls to the query builder. Types don't match.

So I think having `Builder|QueryBuilder|Relation` as the type of the parameter would fix it.

**Comment by szepeviktor** [comment]
testing my signed email :)

Idézem/Quoting Can Vural <notifications@github.com>:

> Hi,
>
> I think this is normal behavior. You are expecting  
> `Builder|QueryBuilder` type in `addSomeImportentConditions` method,  
> but you are passing `Relation` (`HasManyThrough` in this case)  
> Doesn't matter if relation forwards calls to the query builder.  
> Types don't match.
>
> So I think having `Builder|QueryBuilder|Relation` as the type of the  
> parameter would fix it.


SZÉPE Viktor, webes alkalmazás üzemeltetés / Running your application
https://github.com/szepeviktor/debian-server-tools/blob/master/CV.md
~~~
ügyelet/hotline: +36-20-4242498  sms@szepe.net  skype: szepe.viktor
Budapest, III. kerület

**Comment by mfn** [comment]
Hmm. You're right, works! Strange why I didn't thought of it.

> Strange why I didn't thought of it.

Well, I think because I expected the `@mixin` to tell phpstan/larastan that "Relation is-a Builder".

Acceptable solution for me 😛 😏 Thanks!
