### ISSUE TITLE
Query with custom builder broken return type

### ISSUE THREAD

**Issue by Daanra** [nunomaduro/larastan#535]
- Larastan Version: https://github.com/nunomaduro/larastan/commit/7abe5f61f516f27182b5326717796c54c0d52f26
- `--level` used: max

### Description
Calling either `::get()` directly on a model with a custom builder or on a model with a custom builder that does not have the proper PHPDoc annotations:

```php
/**
 * @template TModelClass
 * @extends Builder<TModelClass>
 */
```
results in error messages because the return type of a query will be inferred as `Illuminate\Database\Eloquent\Builder<Illuminate\\Database\\Eloquent\\static>`.

### Laravel code where the issue was found

```php
<?php

declare(strict_types=1);

namespace Tests\Features\Weird;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class WeirdErrorMessageTest
{
    /**
     * @return Collection<ModelWithCustomBuilder>
     */
    public function testWeirdErrorMessage(): Collection
    {
        // Fails even though Builder has correct annotations
        return ModelWithCustomBuilder::get();
    }

    /**
     * @return Collection<ModelWithCustomBuilderMissingDocs>
     */
    public function testWeirdErrorMessage2(): Collection
    {
        // Fails because missing annotations
        return ModelWithCustomBuilderMissingDocs::where('id', 1)->get();
    }

    /**
     * @return Collection<ModelWithCustomBuilder>
     */
    public function testWeirdErrorMessage3(): Collection
    {
        // Succeeds only because we have annotations
        return ModelWithCustomBuilder::where('id', 1)->get();
    }
}

class ModelWithCustomBuilder extends Model
{
    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return CustomEloquentBuilder
     */
    public function newEloquentBuilder($query): CustomEloquentBuilder
    {
        return new CustomEloquentBuilder($query);
    }
}

class ModelWithCustomBuilderMissingDocs extends Model
{
    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return CustomEloquentBuilderMissingDocs
     */
    public function newEloquentBuilder($query): CustomEloquentBuilderMissingDocs
    {
        return new CustomEloquentBuilderMissingDocs($query);
    }
}

/**
 * @template TModelClass
 * @extends Builder<TModelClass>
 */
class CustomEloquentBuilder extends Builder
{
}

// Missing PHPDoc annotations causes error
class CustomEloquentBuilderMissingDocs extends Builder
{
}

```

This example results in the following error message:

**testWeirdErrorMessage** 
```
Method Tests\\Features\\Weird\\WeirdErrorMessageTest::testWeirdErrorMessage() should return Illuminate\\Database\\Eloquent\\Collection<Tests\\Features\\Weird\\ModelWithCustomBuilder> but returns Illuminate\\Database\\Eloquent\\Collection<Illuminate\\Database\\Eloquent\\static>.
```
**testWeirdErrorMessage2**
```
Method Tests\\Features\\Weird\\WeirdErrorMessageTest::testWeirdErrorMessage2() should return Illuminate\\Database\\Eloquent\\Collection<Tests\\Features\\Weird\\ModelWithCustomBuilder> but returns Illuminate\\Database\\Eloquent\\Collection<Illuminate\\Database\\Eloquent\\static>.
```

**Comment by canvural** [comment]
Hi,

I changed the stub for `EloquentBuilder` [here.](https://github.com/nunomaduro/larastan/commit/47d917912672669d3dd1fe38cbf237dee7397247) So that should solve the issue with `testWeirdErrorMessage`

About `testWeirdErrorMessage2` there is nothing we can do I think. `Builder` is a generic class, so any custom builder class extending it has to have the annotations.

**Comment by Daanra** [comment]
@canvural Thanks for the update!

I don't mind the Builder requiring the annotations. The biggest problem, in my opinion, is that the error message can get quite confusing. It doesn't say anything about a missing annotation and that might lead the developer in the wrong direction.

If we change the test slightly:
```php
    public function testWeirdErrorMessage2(): int
    {
        return ModelWithCustomBuilderMissingDocs::where('id', 1)->get()->last()->id;
    }
```
The error message will be something like 
```Access to property $id on an unknown class Illuminate\Database\Eloquent\static.```

I had this occur in a relatively large application and it took me a solid hour to find that the annotations on my builder were missing. 

Is there perhaps an easy way to check if the developer defined any annotations on their custom builder and if they did not, report that as an error?

That might save the developers some time when forgetting to add the annotations. If it's not a trivial task, then I suppose this issue can be closed.

**Comment by canvural** [comment]
Warning about that you forgot to add the annotations is PHPStan's job. And actually it does it. [Here](https://phpstan.org/r/7ea49c33-fe70-4e31-baba-d3b50dc51569) is an example.

But I think in our case, we have the extensions and the extension is trying to do something with the generic class, so it somehow suppresses that error. I'm not sure how we can fix it or if it is trivial to fix or not.

**Comment by canvural** [comment]
I think this is improved with https://github.com/nunomaduro/larastan/commit/c54b5179e72b8ea18e724c50bf6a9c36af79d52d Closing the issue.
