### ISSUE TITLE
Allow using non-integer model IDs

### ISSUE THREAD

**Issue by zlodes** [nunomaduro/larastan#536]
- Larastan Version: 0.5.5
- `--level` used: `max`

### Description
PR #499 allows only (!) integer type for model IDs.

But we are using UUID for some models IDs and static analysis failing.

I propose to rollback the PR.

### Laravel code where the issue was found

```php
/**
 * @property string $user
 */
class User extends Model
{
/...
}

function foo(string $foo): void
{
    echo $foo;
}

foo($user->id);

```

**Comment by szepeviktor** [comment]
So you'd like to have `int|string`?

**Comment by canvural** [comment]
Hi,

This is fixed in the current master. You can specify a type for your `id` property in the annotation, and that will be used.

```php
/**
 * @property string $id
 */
class User extends Model
{}
```

**Comment by zlodes** [comment]
@canvural cool, thanks!
