### ISSUE TITLE
Issue with Carbon startOfWeek

### ISSUE THREAD

**Issue by deleugpn** [nunomaduro/larastan#541]
- Larastan Version: 6.18.8
- `--level` used: 4

### Description

```
Method Carbon\Traits\Date::startOfWeek() invoked with 1 parameter, 0 required.
```

I believe this issue is being caused because the `Date` trait uses the Rounding trait, which has a docblock of `* @method CarbonInterface startOfWeek()`. I will report this to the Carbon repository, however I thought about reporting here as well for the reason that the CarbonInterface contains the following method:

```
    /**
     * Resets the date to the first day of week (defined in $weekStartsAt) and the time to 00:00:00
     *
     * @example
     * ```
     * echo Carbon::parse('2018-07-25 12:45:16')->startOfWeek() . "\n";
     * echo Carbon::parse('2018-07-25 12:45:16')->locale('ar')->startOfWeek() . "\n";
     * echo Carbon::parse('2018-07-25 12:45:16')->startOfWeek(Carbon::SUNDAY) . "\n";
     * ```
     *
     * @param int $weekStartsAt optional start allow you to specify the day of week to use to start the week
     *
     * @return static
     */
    public function startOfWeek($weekStartsAt = null);
```

From this, it is clear that the actual code (Interface) accepts a parameter. The fact that the docblock doesn't accept a parameter doesn't seem enough reason to cause an error here? Maybe I'm wrong.
My understanding is that docblock is really helpful to teach static analyses to accept something that code cannot reproduce (e.g. string[]), but if the docblock is 'less correct' than the actual code and the error being reported by the docblock does not exist in the actual code, perhaps it should not emit an error at all?

### Laravel code where the issue was found

```php
        // https://github.com/briannesbitt/Carbon/pull/1980
        return $carbon->startOfWeek(CarbonImmutable::MONDAY)->format($format);
```

**Comment by canvural** [comment]
Hi,

This doesn't seem to be related to Larastan if I understood correctly. `Date` trait, `Rounding` trait and `CarbonInterface` all defined in Carbon. So, it should be fixed there. And looks like its fixed with https://github.com/briannesbitt/Carbon/pull/2069

The issue with the mismatch parameter with PHPDocs and the actual code can be a real issue with PHPStan. So, you can try to replicate it at phpstan.org and open an issue at PHPStan.

**Comment by deleugpn** [comment]
Thanks for the guidance! I reported it on phpstan.
