### ISSUE TITLE
Eloquent Builder expects other value

### ISSUE THREAD

**Issue by edwinvdpol** [nunomaduro/larastan#549]
- Larastan Version: 0.5.6
- `--level` used: 5

### Description
When I run the `analyse` command, errors like these are popping up:
`
Parameter #1 $attributes of method Illuminate\Database\Eloquent\Relations\HasOneOrMany<App\Models\ModelName>::firstOrCreate() expects array<int, mixed>, array<string, string> given.`

Laravel source ([link](https://github.com/laravel/framework/blob/8f3efb4883bc29b529f15db3f35963747ba37248/src/Illuminate/Database/Eloquent/Builder.php#L433)):
```php
public function firstOrCreate(array $attributes, array $values = []) {}
```

Not sure where the `expects array<int, mixed>` in the error message comes from.

As far as I can see, these methods are reported:
`firstOrCreate()` and `updateOrCreate()`, but my guess is that is applicable for [other creation methods](https://laravel.com/docs/7.x/eloquent#other-creation-methods) as well. Not tested though.

### Laravel code where the issue was found

```php
$modal->belongsToRelation->hasManyRelation()->firstOrCreate([
    'day' => today()->toDateString()
]);

$modal->hasManyRelation()->updateOrCreate(
    ['day' => today()->toDateString()],
    [
        'one_count' => $modal->one_count,
        'two_count' => $modal->two_count,
    ]
);
```

**Comment by canvural** [comment]
Hi,

Yes, this was an error. And already fixed in `master` branch.

I'll release 0.5.7 with the fix today.

**Comment by edwinvdpol** [comment]
Allright, thank you! 👍

**Comment by canvural** [comment]
[0.5.7](https://github.com/nunomaduro/larastan/releases/tag/v0.5.7) is released!
