### ISSUE TITLE
Call to undefined method loginUsingId()

### ISSUE THREAD

**Issue by nmfzone** [nunomaduro/larastan#552]
- Larastan Version: 0.5.5
- `--level` used: 5

### Description

```
 ------ ----------------------------------------------
  Line   LoginController.php
 ------ ----------------------------------------------
  62     Call to an undefined method
         Illuminate\Auth\AuthManager::loginUsingId().
 ------ ----------------------------------------------
```

### Laravel code where the issue was found

```php
auth()->loginUsingId($user->id);
```

**Comment by szepeviktor** [comment]
Could you try `auth()->login($user);` ?

**Comment by nmfzone** [comment]
@szepeviktor Ah nice solution. But how about that?

**Comment by nunomaduro** [comment]
May not be related, but make sure you update for the latest version.

**Comment by nmfzone** [comment]
@nunomaduro Yeah, updated to the latest version. Still the same.

**Comment by nmfzone** [comment]
For anyone who faced this issue, maybe we can just ignore those error for now:

**phpstan.neon**
```neon
parameters:
    ignoreErrors:
        - '#Call to an undefined method Illuminate\Auth\AuthManager::login()#'
```

**Comment by canvural** [comment]
Yep, this looks like a bug. Thanks for reporting @nmfzone 

`AuthManager` has the magic `__call` method which forwards method calls to guards. We might need a new extension for this behavior.

**Comment by nmfzone** [comment]
@canvural Sure, thanks. Keep a good work guys ⚡

**Comment by canvural** [comment]
Fixed: https://github.com/nunomaduro/larastan/commit/6a7009b23eefd33031b5e0845e1f20a02da968ec

Thank you!

**Comment by devfaysal** [comment]
I am not sure if it is related to the fix:
I am on v0.5.8
It is not working properly when `auth()` helper is called for a custom guard.
For example, I have a custom guard 'employee' and the model is Employee which has the function `latest_pending_leave_request`.
when I call `auth('employee')->user()->latest_pending_leave_request()`, larastan says `Call to an undefined method Illuminate\Contracts\Auth\Authenticatable::latest_pending_leave_request()`

**Comment by canvural** [comment]
@devfaysal Although custom guards are not supported in Larastan, I believe your issue will be fixed in the next release. You can try to pull the `master` branch and check now if you want.
