### ISSUE TITLE
Take advantage of `@mixin` in Laravel's code itself

### ISSUE THREAD

**Issue by ondrejmirtes** [nunomaduro/larastan#555]
Hi,
PHPStan's dev-master now supports `@mixin` annotation (https://github.com/phpstan/phpstan-src/commit/b02ee1444440ed995c17171c456feec2c56e0cb2). I've been told that Laravel's codebase uses this annotation heavily, so maybe Larastan could take advantage of it. Maybe we could delete some of Larastan's custom code if the only thing it does is describing Laravel magic that's also described by the `@mixin` annotation.

What I'd like to see happen:

1) Require `phpstan/phpstan: ^0.12.20` (soon to be released, in a matter of days) so that people that would update Larastan but not PHPStan are not left without this functionality.
2) Go through extensions that describe Laravel's code that uses `@mixin` and try to delete them/reduce them.

(If you don't find any code in Larastan that can be deleted thanks to `@mixin` support, then `^0.12.20` doesn't have to be required.)

Thank you!

**Comment by ondrejmirtes** [comment]
Also, one more idea - it's also possible that Larastan's describes some code from Laravel that would justify adding `@mixin` annotation to Laravel itself. In that case, you can just create a [stub file](https://github.com/nunomaduro/larastan/issues/555) for that class in Larastan with `@mixin` and it would work.

**Comment by nunomaduro** [comment]
If I remember correctly, we are already using those `mixings` somewhere on the larastan codebase. We need to check.

**Comment by ondrejmirtes** [comment]
It might be possible to simplify that code, or maybe somehow re-use this extension: https://github.com/phpstan/phpstan-src/blob/master/src/Reflection/Mixin/MixinMethodsClassReflectionExtension.php

**Comment by canvural** [comment]
Actually we were doing this manually. Here: https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Mixins.php Looking for `@mixin` and `@see` in the class docs, and searching the missing method in those classes.

So, I guess we can remove that. I'll look into it :+1:

**Comment by canvural** [comment]
`laravel-ide-helper` package adds `@mixin \Eloquent` to the models docblock when you generate ide helper files.

`\Eloquent` is a class alias to `Illuminate\Database\Eloquent\Model` So basically it is adding a mixin for the class' actual parent. This is to have some auto-completion in the IDE.

And I found out this kinda breaks Larastan's extensions. Because when a missing method is found PHPStan will try to look for that method in `\Eloquent` because of the `@mixin`. And when our extensions run they are getting the `Illuminate\Database\Eloquent\Model` as the class reflection. So they are producing the wrong return types. For example we an extension to determine the return type of `find` method on the model. If the argument is iterable a collection should be returned, model otherwise. But with `@mixin \Eloquent` added, we don't know the real model name. We just have `Model`

But also `laravel-ide-helper` can be configured to write the mixin inside of the `_ide_helper.php` file. So I'd say we don't need to fix or workaround for this. We just need to notify people about this in upgrade guide or readme.

**Comment by ondrejmirtes** [comment]
Why is Larastan even reading anything that `laravel-ide-helper`produces? It should read the application source code written by its developers, no?

**Comment by canvural** [comment]
`laravel-ide-helper` modifies the model files written by the developers. It adds the `@mixin` to the models php docblocks.

**Comment by canvural** [comment]
But like I said it can be configured to write it to a dedicated file. `_ide_helper_models.php` In that case it'll not conflict with Larastan/PHPStan.

**Comment by ondrejmirtes** [comment]
Can you explain the thing in https://github.com/nunomaduro/larastan/issues/555#issuecomment-624297770 in a bit more detail? What class has `@mixin`, what PHPStan sees vs. what it should see instead, what ClassReflection reports... maybe I can think of a solution, but I didn't get it what's exactly wrong from the comment. I'm not sure about the relationships between the classes.

**Comment by ondrejmirtes** [comment]
1) I could add an exclude option to the mixin extension that would Larastan set.
2) Maybe I’ll figure out how to get the info we need even in the current system.

**Comment by canvural** [comment]
```php
/**
 * @mixin \Eloquent
 */
class User extends \Illuminate\Database\Eloquent\Model
{}
```

This is an Eloquent model that the developer writes. `@mixin \Eloquent` part, might be added by the `laravel-ide-helper` package.

And `\Eloquent` is just a class alias to `Illuminate\Database\Eloquent\Model`

When we analyze `User::find(1)`, `MixinMethodsClassReflectionExtension` runs and [here](https://github.com/phpstan/phpstan-src/blob/master/src/Reflection/Mixin/MixinMethodsClassReflectionExtension.php#L31) `$type` is `\Eloquent` object type. And PHPStan loops thorough all extensions to find if the extension has that method and gets it if it finds. The problem is `Illuminate\Database\Eloquent\Model` is passed to the extensions as class reflection and not the `App\User`

Which is, expected :sweat_smile: 

Now going through the code I realized maybe we can fix it in the extensions. Tell it to not work if the given class reflection is `Illuminate\Database\Eloquent\Model` Some of the extensions are already doing this. Like [this,](https://github.com/nunomaduro/larastan/blob/master/src/Methods/ModelForwardsCallsExtension.php#L33-L35) but found we don't do it for https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Mixins.php

**Comment by canvural** [comment]
I just need to spend more time on this. Looks like it is Larastan's problem for now. Sorry to bother :sweat_smile:

**Comment by ondrejmirtes** [comment]
I'm not sure how https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Mixins.php works because it doesn't look like a traditional PHPStan extension, but I'm quite certain that the Eloquent\Model exclusion now needs to happen on PHPStan's side because it now handles `@mixin` itself.

**Comment by canvural** [comment]
https://github.com/nunomaduro/larastan/commit/bd84cae67f8c947e17e563c757858c9db72ebeab this seems to fix the issue. And everything else works as expected.

**Comment by canvural** [comment]
Looks like it still can cause issues, like #565 @ondrejmirtes Is it possible to have a blacklist of classes that should not be inspected in `@mixin` ?

**Comment by ondrejmirtes** [comment]
@canvural Definitely, do you have time to contribute that to phpstan-src or shoud I do it?

**Comment by canvural** [comment]
@ondrejmirtes I can try to do it. Only `MixinMethodsClassReflectionExtension` and `MixinPropertiesClassReflectionExtension` should be changed I guess. And a new config parameter for users to fill in?

**Comment by ondrejmirtes** [comment]
Yes, I'd call it `mixinExcludeClasses`. It doesn't even have to be documented :)

**Comment by iraklisg** [comment]
I am using `laravel-ide-helper` with the option to add a mixin tag to the Model files: For example:
```php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * @mixin IdeHelperUser
 */
class User extends Authenticatable
{ ... }
``` 
When running `./vendor/bin/phpstan analyse` I am getting the following warnings
```
  Line   Models/User.php                                                     
 ------ -------------------------------------------------------------------- 
  14     PHPDoc tag @mixin contains unknown class App\Models\IdeHelperUser.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 
```

The phpstan.neon configuration I am using is the following:
```yml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - app
    level: 5
    checkMissingIterableValueType: false
```

I am not sure how to use the `mixinExcludeClasses` option propsosed by @ondrejmirtes to suppress these warnings. Could someone help me on this please?

**Comment by canvural** [comment]
@iraklisg If `IdeHelperUser` is a class in the global namespace, then it should be `@mixin \IdeHelperUser`

**Comment by iraklisg** [comment]
@canvural it makes sense but the `@mixin IdeHelperUser ` is automatically injected by ide-helper plugin.
I try to to add something like this in the `phpstan.neon` file but with no luck
```yml
parameters:
    ...
    mixinExcludeClasses:
        - Illuminate\Database\Eloquent\Model
        - App\Models
```

**Comment by canvural** [comment]
@iraklisg Then looks like it's an issue with that plugin.

You should try this I think:
```neon
mixinExcludeClasses:
    - IdeHelperUser
```

**Comment by iraklisg** [comment]
@canvural thank you for the reply. I tried `IdeHelperUser` as well as `App\Models\IdeHelperUser` but I am getting the same error.
The plugin creates an `_ide_helper_models.php` file that includes the following information
```php
namespace App\Models{
/**
 * App\Models\User
 *
 * @mixin IdeHelperUser
 * @property int $id
 * ...
 }
```
Nevertheless, Larastan works pretty well, I just wanted to know if there is any way to suppress this warnings about `@mixin contains unknown class App\Models\IdeHelperUser.`

**Comment by canvural** [comment]
@iraklisg If you are writing to the `_ide_helper_models.php` file, why your model has the `@mixin` also? It shouldn't do that.

**Comment by iraklisg** [comment]
@canvural from the [ide-helper docks](https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models)
> Alternatively using the --write-mixin (-M) option will only add a mixin tag to your Model file, writing the rest in (_ide_helper_models.php). The class name will be different from the model, avoiding the IDE duplicate annoyance.

**Comment by canvural** [comment]
Ah, now I understand.

Did you try to add it with leading backslash?

```neon
parameters:
	...
	mixinExcludeClasses:
	    - \App\Models\IdeHelperUser
```

**Comment by iraklisg** [comment]
Yes I tried this as well. As well as `App\Models\IdeHelperUser` 
If it is of any help, the _ide_helper+models.php file includes the following
```php
namespace App\Models{
/**
 * App\Models\User
 *
 * @property int $id
    ...
 * @mixin \Eloquent
 */
	class IdeHelperUser extends \Eloquent {}
}
```
I also tried `\Eloquent`, `Eloquent` but neither of these works

I understant that the actual class ``App\Models\IdeHelperUser` does not exists and phpstan correctly report it as an error. I was wondering if there is a way to disable this rule

**Comment by canvural** [comment]
Now I realized the problem. (I guess I still didn't woke up) It's got nothing to do with `mixinExcludeClasses` 

I think you might want to read [here](
https://phpstan.org/user-guide/discovering-symbols) and try to use `scanFiles`

**Comment by iraklisg** [comment]
@canvural I think you are pointing to the right direction. I used:
```yaml
    scanFiles:
      - _ide_helper_models.php

```
Now I am getting a different error on another model
```
 ------ -------------------------------------------------------------------- 
  Line   Models/Application.php                                              
 ------ -------------------------------------------------------------------- 
         Reflection error: Eloquent not found.        
```
However, I am using larastan on an existing application that makes hard to track why is this happening. I will try to use larastan with ide-helper on a fresh Laravel application to see what's happening
Thank you

**Comment by ondrejmirtes** [comment]
I don't think that you should use both Larastan and Laravel IDE helper. They're both trying to do the same job I don't think it makes sense combining them.

**Comment by szepeviktor** [comment]
> I don't think that you should use both Larastan and Laravel IDE helper.

Very well said.

**Comment by iraklisg** [comment]
@ondrejmirtes in a sense probably yes, they serve the same purpose. However with Laravel IDE helper you get nice auto-completion features in your IDE

**Comment by ondrejmirtes** [comment]
@iraklisg Of course no one is telling you not to use IDE helper if you need to use it for your IDE. But you need to keep the generated classes out of sight for PHPStan.

**Comment by iraklisg** [comment]
@ondrejmirtes sure, both tools are helpful in the development process. 

There is the option to use Laravel IDE helper without mixins (which caused the issues with PHPStan) and either generate the full PHPDocs or or write to a separate file `_ide_helper_models.php` with `--nowrite` option, but this causes some issues with duplicate class names.

For the time being, I opt to use the Laravel Idea plugin  (PHPSstorm) that offers auto-completion without needing to generate PHPDocs for models while avoiding the IDE duplicate annoyance.

**Comment by kukukk** [comment]
@iraklisg Have you found a solution to use both Larastan and IDE helper? I would like to keep IDE helper to have auto-completion and Larastan to check the code during the CI process.

**Comment by ondrejmirtes** [comment]
PHPStan has no interest in IDE helper-generated code. You just need to make sure it's not discovered by PHPStan via autoloading and other means: https://phpstan.org/user-guide/discovering-symbols

**Comment by ondrejmirtes** [comment]
So by default I think it should work fine.
