### ISSUE TITLE
Misleading instruction on screenshot

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#558]
Please create a new one :)

https://github.com/nunomaduro/larastan/blob/master/docs/example.png

From https://github.com/nunomaduro/larastan/issues/327#issuecomment-623201869
Thank you @mr-feek

**Comment by szepeviktor** [comment]
Was it created with https://carbon.now.sh/ ?

**Comment by nunomaduro** [comment]
@szepeviktor fixed.

**Comment by szepeviktor** [comment]
Thank you.
