### ISSUE TITLE
Xampp on Windows

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#56]
With the latest update, Larastan finally works in Homestead. Unfortunately, it doesn't work anymore with Xampp on Windows. The result, what I get is. 

```
'phpstan' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by deleugpn** [comment]
I'm going to try to pick this up next week.

**Comment by boomhq** [comment]
Hi,  i've found 2 solutions but i dont know what is the best way.
The bug is a regression from :  [COMMIT](https://github.com/nunomaduro/larastan/commit/08dcba3740bc24e5f1e8ac8e530170717c49478c#diff-fd1a7c19da3313d9dcfb80ffadb016bb
)
1st solution: Back to "vendor/bin" and work on LINUX/Windows

2nd solution: on CodeAnalyseCommand.php  on 

> private function command()

 replace with :

`   private function command(): string
    {
        $command = Artisan::phpBinary();
        return "$command phpstan analyse";
    }
`

On this case the PHP binary is alwways resolved.
Maybe you can help me with your opinion and i'm ready for PR

**Comment by ForzaSFerrari** [comment]
@boomhq The first solution would not work with Laravel's Homestead. Look at #35 

Your second solution does not seem to work for me on Windows. Larastan does not do anything.

**Comment by boomhq** [comment]
@ForzaSFerrari it's strange for me in classique laravel app (no homestead, valet ...)  on linux and windows with         `$process = new Process($this->cmd(), $this->laravel->basePath('vendor/phpstan/phpstan/bin'));`

And after replace` function command()` it's work fine.

Test on Windows10 PHP 7.1.7 and Debian 9 with PHP 7.1.18

**Comment by staf** [comment]
Not only related to XAMPP, seems to be a general Windows thing as this also happens running with apache and php installed "manually". Using Windows 10 and php 7.2.

It seems to try to run phpstan globally and not the binary from the vendor folder. I tried to install phpstan globally but that ended up with larastan "doubling" the path name.

Fresh Laravel app installed in ` C:\Code\larastan` results in the error `Path C:\Code\larastan\C:\Code\larastan\app does not exist`. when running the script with phpstan installed globally to allow actually running the command.

**Comment by boomhq** [comment]
@staf  you can start larastan with `php artisan code:analyse --path=app`

**Comment by staf** [comment]
That does work, but you shouldn't have to specify what path to run though. This library is supposed to know the Laravel structure anyway 😄

**Comment by Necko1996** [comment]
Any progress with this bug?
