### ISSUE TITLE
when using whereLike method with Tucker-Eric / EloquentFilter got error on commit

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#566]
- **Larastan Version: 7.10.2**
- package **Tucker-Eric / EloquentFilter** version: 2.3.0
- `--level` used: **max**

### Description
when I dump data with dd(), and then I got 
![image](https://user-images.githubusercontent.com/27404296/81178230-78c46200-8fda-11ea-8a62-d35795683253.png)
![image](https://user-images.githubusercontent.com/27404296/81178267-8b3e9b80-8fda-11ea-9ecf-078eb77a44da.png)

Actually  return is App\ModelFilters\Finance\SystemBankFilter and hook should **allow me to pass it** but when I commit I got below error 
```
------ ----------------------------------------------------------------------- 
  Line   SystemBankFilter.php                                                   
 ------ ----------------------------------------------------------------------- 
  40     Method App\ModelFilters\Finance\SystemBankFilter::name() should        
         return App\ModelFilters\Finance\SystemBankFilter but returns           
         Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Mod  
         el>.                                                                   
 ------ ----------------------------------------------------------------------- 
```

 [ERROR] Found 1 error                         

### Laravel code where the issue was found
[SystemBankFilter.php.txt](https://github.com/nunomaduro/larastan/files/4586706/SystemBankFilter.php.txt)

**Comment by canvural** [comment]
Hi,

That `ModelFilter` class in that package has it's own `__call` method to handle magic calls. This has nothing to do with Larastan.

You can either ignore this error message, or you can write your own `MethodsClassReflectionExtension` PHPStan extension for this case. You can read [here](https://phpstan.org/developing-extensions/class-reflection-extensions) more about it how to write such extensions.

Thank you!
