### ISSUE TITLE
Access to an undefined property object::$property_name

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#57]
Example
```php
$user = User::where('id', '=', '1')->first();

$user->first_name
```

Result
```
Access to an undefined property object::$first_name.
```

The same problem is still open in phpstan. ([Access to an undefined property object::$property_name](https://github.com/phpstan/phpstan/issues/928))

**Comment by ondrejmirtes** [comment]
What kind of object is `$user` in runtime?

**Comment by nunomaduro** [comment]
@ondrejmirtes On the `first` method, the return type wrote on the PHPDocs is `object` instead of an instance of `Model::class`. I will write a PR to the core of Laravel to fix this.

**Comment by ondrejmirtes** [comment]
@nunomaduro What return typehint `where` method has? If you want to return the same object as it's called on, you should use both `@return static` in phpDoc and `self` native return typehint at the same time.

**Comment by ondrejmirtes** [comment]
Or you can fix this with dynamic return type extension 😊

**Comment by nunomaduro** [comment]
@ForzaSFerrari Thanks again for reporting this false positive. 👍

This issue **got fixed** on the version `v0.1.7`. Do you mind of performing a `composer update nunomaduro/larastan` and test it again?

**Comment by ForzaSFerrari** [comment]
Looks like it's been fixed. @nunomaduro

**Comment by neoplomero** [comment]
@nunomaduro I'm on "nunomaduro/larastan": "^0.3.4", and still having this issue :(

**Comment by adminfriso** [comment]
@neoplomero could you provide us with more information about your issue, is it in a foreach loop etc. Between 0.3.4 and 0.3.12 quite some false positives has been addressed related to here. Could you proform a `composer update nunomaduro/larastan` and test it again? If it still is an false positive could you address it as a new issue.

**Comment by neoplomero** [comment]
@adminfriso  Thanks. Issue created https://github.com/nunomaduro/larastan/issues/216
