### ISSUE TITLE
Polymorphic relationship return types

### ISSUE THREAD

**Issue by j-dexx** [nunomaduro/larastan#573]
- Larastan Version: 0.5.5
- `--level` used: max

### Description
I'm not sure this is an issue or whether I just can't work out how to solve with a docblock.  Essentially is there any way to set the class on a morph many relationship?

### Laravel code where the issue was found

```php
trait Pageable
{
    /**
     * Get all of the pages for the pageable.
     */
    public function pages(): MorphMany
    {
        return $this->morphMany(Page::class, 'pageable');
    }
}
```

elsewhere using things like this in another class (where pageable is set to an instance of the class with the pages relationship on) 
```php
function initializePage(): Page
{
   $this->pageable->pages()->firstOrNew();
}

```

I get `should return App\Models\Page but returns Illuminate\Database\Eloquent\Model`

Is there anything I can add in a docblock on the relationship to tell larastan that it's a relationship for a morphMany to the Page class?

**Comment by canvural** [comment]
Hi,

This should actually work as is. Weird.

One thing you can try is to change your relation method to this
```php
/**
 * Get all of the pages for the pageable.
 * @phpstan-return MorphMany<Page>
 */
public function pages(): MorphMany
{
    return $this->morphMany(Page::class, 'pageable');
}
```

This is done automatically by Larastan under-the-hood, but it might be worth a try.

**Comment by szepeviktor** [comment]
The word _Polymorphic_ makes me afraid.
Could we use "kitty cat" instead??

**Comment by j-dexx** [comment]
Hi @canvural, thanks for the speedy reply.  That doesn't make any difference I'm afraid.  One thing I should have mentioned before is that the pages relationship is defined in a trait I'd assume this could be the issue?

**Comment by canvural** [comment]
@j-dexx We are supporting relations defined in traits. But PHP reflection around traits can be tricky sometimes.

Can you move that one relation to your model and test it that way?

**Comment by canvural** [comment]
Ah, also noticed one thing. What is the type of `$this->pageable` in your code?

**Comment by j-dexx** [comment]
It might help to show a cut down version of the actual code
```php
class Video extends Model
{
    #    use Pageable;

    /**
     * Get all of the pages for the pageable.
     *
     * @phpstan-return MorphMany<Page>
     */
    public function pages(): MorphMany
    {
        return $this->morphMany(Page::class, 'pageable');
    }
}
```

```php
class VideoPageSaver
{
    /**
     * @var \App\Models\Site
     */
    private $site;
    /**
     * @var \App\Models\Video
     */
    private $video;

    public function __construct(Video $video, Site $site)
    {
        $this->video = $video;
        $this->site = $site;
    }

    public function call(): void
    {
        try {
            DB::beginTransaction();
            $this->saveVideoPage();
            DB::commit();
        } catch (Throwable $e) {
            Log::error($e);
            DB::rollBack();
        }
    }

    private function saveVideoPage(): void
    {
        $page = $this->findOrInitializeVideoPage();
        $page->name = $this->getVideo()->title;
        $page->save();
    }

    private function findOrInitializeVideoPage(): Page
    {
        return $this->getVideo()->pages()->firstOrNew([
            'template' => Page::TEMPLATE_VIDEO_SHOW,
        ]);
    }

    private function getVideo(): Video
    {
        return $this->video;
    }
}
```

So in this one `$this->pageable` would be a Video.  Defining the relation directly on the model I still have the same issue.

**Comment by canvural** [comment]
Thank you, I'll look into it.

**Comment by j-dexx** [comment]
@canvural I think you can ignore this, updating larastan to the latest version resolves my issue.  Sorry, I hadn't checked whether I was on the latest version or not before creating my issue.  Thanks for looking into this.

**Comment by szepeviktor** [comment]
We are glad that you've succeeded.
