### ISSUE TITLE
Subqueries on local scope

### ISSUE THREAD

**Issue by YannickYayo** [nunomaduro/larastan#574]
- Larastan Version: 0.5.2
- `--level` used: 5

### Description
I am using a subquery on a local scope from my `App\Models\User` model.
Running Larastan give me this error : 
``` bash
TypeError 

  Argument 1 passed to PHPStan\Type\TypeTraverser::mapInternal() must implement interface PHPStan\Type\Type, null given, called in phar:///var/www/html/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php on line 179

  at phar://vendor/phpstan/phpstan/phpstan/src/Type/TypeTraverser.php:45
    41|     {
    42|         $this->cb = $cb;
    43|     }
    44|     /** @internal */
  > 45|     public function mapInternal(\PHPStan\Type\Type $type) : \PHPStan\Type\Type
    46|     {
    47|         return ($this->cb)($type, [$this, 'traverseInternal']);
    48|     }
    49|     /** @internal */
```

### Laravel code where the issue was found

``` php
    /**
     * Scope to add subquery for preferred living area name.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithPreferredLivingArea(Builder $query): Builder
    {
        return $query->addSelect(['preferredLivingArea' => LivingArea::select('name')
            ->whereColumn('preferred_living_area', 'living_areas.id')
            ->latest()
            ->take(1),
        ]);
    }
```

**Comment by canvural** [comment]
Hi,

Can you upgrade to the latest version and try again?

**Comment by YannickYayo** [comment]
Running on Larastan `0.5.8` now, the issue still occurs.

**Comment by canvural** [comment]
I know it shouldn't make a difference, but can you try to remove the comment `param` and `return` annotations and try again?

**Comment by YannickYayo** [comment]
Done, this isn't fixed by removing `param` and `return` :(

**Comment by YannickYayo** [comment]
Okay, this was my bad.

On my model I'm using the [laravel-mysql-spatial](https://github.com/grimzy/laravel-mysql-spatial) package.
So i'm using a trait on this model : 
``` php
class LivingArea extends Model
{
    use SpatialTrait;
    ....
}
```
And this trait is using a custom Builder, so i followed up this [upgrade guide](https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders) and now all is working :)

**Comment by szepeviktor** [comment]
We are glad that you've resolved your own issue :)
