### ISSUE TITLE
Should AppExtension@getTypeFromFunctionCall return Illuminate\Contracts\Foundation\Application? (patch included)

### ISSUE THREAD

**Issue by StanAngeloff** [nunomaduro/larastan#576]
- Larastan Version: 0.5.8
- `--level` used: 5

### Description

[NunoMaduro\Larastan\ReturnTypes\Helpers\AppExtension@getTypeFromFunctionCall](https://github.com/nunomaduro/larastan/blob/6b0d6d83e39aaad94907e56b2e35a115eaadb164/src/ReturnTypes/Helpers/AppExtension.php) currently returns `Illuminate\Foundation\Application`. This is not available in a Lumen application and will cause any call to `app()->method()` to error with `Call to method method() on an unknown class Illuminate\Foundation\Application.`

### Laravel code where the issue was found

```php
<?php

$locale = app()->getLocale();
```

Should this return `Illuminate\Contracts\Foundation\Application` instead **when `Illuminate\Foundation\Application` is not defined**?

```diff
--- src/ReturnTypes/Helpers/AppExtension.php.original	2020-05-13 14:30:08.890761233 +0300
+++ src/ReturnTypes/Helpers/AppExtension.php	2020-05-13 14:30:11.438767312 +0300
@@ -2,11 +2,10 @@
 
 declare(strict_types=1);
 
 namespace NunoMaduro\Larastan\ReturnTypes\Helpers;
 
-use Illuminate\Foundation\Application;
 use NunoMaduro\Larastan\Concerns\HasContainer;
 use PhpParser\Node\Expr;
 use PhpParser\Node\Expr\ClassConstFetch;
 use PhpParser\Node\Expr\FuncCall;
 use PhpParser\Node\Name\FullyQualified;
@@ -33,11 +32,15 @@
         FunctionReflection $functionReflection,
         FuncCall $functionCall,
         Scope $scope
     ): Type {
         if (count($functionCall->args) === 0) {
-            return new ObjectType(Application::class);
+            return new ObjectType(
+                class_exists(\Illuminate\Foundation\Application::class)
+                    ? \Illuminate\Foundation\Application::class
+                    : \Illuminate\Contracts\Foundation\Application::class
+            );
         }
 
         /** @var Expr $expr */
         $expr = $functionCall->args[0]->value;
```

**Comment by StanAngeloff** [comment]
On second thought, that may not be the root cause of the issue…

**Comment by canvural** [comment]
Hi,

I don't use Lumen so I can't test this within any actual project. But did you test your suggested solution in a Lumen project? Is `\Illuminate\Contracts\Foundation\Application` solves the issue?

**Comment by nunomaduro** [comment]
No plans on supporting Lumen.
