### ISSUE TITLE
Variable $req might not be defined after abort()

### ISSUE THREAD

**Issue by DSpeichert** [nunomaduro/larastan#577]
- Larastan Version: v0.5.8
- `--level` used: 5

### Description
>  Variable $req might not be defined. 

In the snippet below, it shows that the only case where variable $req might be undefined, is when exception is thrown but then an `abort()` exception is thrown again.

It looks like larastan does not treat `abort()` as a terminating statement (throwing exception) in this case.

### Laravel code where the issue was found

```php
<?php

public function autodiscover(Request $request)
    {
        // https://msdn.microsoft.com/en-us/library/hh352638(v=exchg.140).aspx
        try {
            $req = simplexml_load_string($request->getContent());

            if (count(explode('@', $req->Request->EMailAddress)) < 2) {
                // okay, that's not AutoDiscovery - valid response
                return response('Invalid email.', 404);
            }
        } catch (\Exception $e) {
            abort(400, $e->getMessage());
        }

        [$local, $domain_name] = explode('@', $req->Request->EMailAddress, 2);
```
Error is thrown about the last line.

**Comment by Daanra** [comment]
We have [abort](https://github.com/nunomaduro/larastan/blob/master/extension.neon#L29) listed as an early terminating function call. So I'm guessing this is more of a PHPStan issue than a Larastan issue.

**Comment by szepeviktor** [comment]
> `abort()` as a terminating statement (throwing exception)

A terminating function is simply exiting.

This is a really interesting problem.
I couldn't find a single path of execution where `$req` in the last line of the snippet is not defined.

**Comment by szepeviktor** [comment]
You can make sure by adding `exit;` right after `abort`

**Comment by DSpeichert** [comment]
> You can make sure by temporarily adding `exit;` right after `abort`

That works, yeah. Maybe it is a phpstan issue indeed.

**Comment by szepeviktor** [comment]
@DSpeichert That is not released yet.
https://github.com/nunomaduro/larastan/blob/v0.5.8/extension.neon

Please try the master branch.

**Comment by canvural** [comment]
Like @szepeviktor and @Daanra this is fixed. And it'll be in the next release. In the meanwhile you can also add it to your config manually.

```neon
earlyTerminatingFunctionCalls:
    - abort
```
