### ISSUE TITLE
'avg' on collection vs query - false positive

### ISSUE THREAD

**Issue by judahnator** [nunomaduro/larastan#578]
- Larastan Version: 0.5.8
- `--level` used: 5

### Description
I started seeing this when using this library:
```
 ------ ------------------------------------------------------------------------------- 
  Line   some/file.php                                                              
 ------ ------------------------------------------------------------------------------- 
  123    Called 'avg' on Laravel collection, but could have been retrieved as a query.  
 ------ ------------------------------------------------------------------------------- 
```
Now I had a few cases in my project where this was legit and did help, but in one specific case I think it is a false positive.

### Laravel code where the issue was found

```php
// snip
$avg_of_fancy_pants_relationship = $model->my_relationship()
  ->withCount(['another_relationship' => $fancyQueryGoesHere])
  ->pluck('another_relationship_count')
  ->avg();
// snip
```

Because I am taking an average of a "withCount" I dont think that can be dont with Eloquent. At least, not this way:
```php
$avg_of_fancy_pants_relationship = $model->my_relationship()
  ->withCount(['another_relationship' => $fancyQueryGoesHere])
  ->avg('another_relationship_count');
// Illuminate/Database/QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'another_relationship_count' in 'field list'...
```

Is this an actual false positive for the static analyzer? Is there maybe a better way to handle this?

**Comment by Daanra** [comment]
Although this might be possible with a single query, aggregates should only trigger an error if the aggregation is performed simply over a column. So this is indeed a bug.

I'll create a pull request to fix this tomorrow. Thanks for reporting this!
