### ISSUE TITLE
Call to an undefined method with()

### ISSUE THREAD

**Issue by ghost** [nunomaduro/larastan#58]
```php
return view('user.profile')->with('user', $user);
```

Produce:

```
Call to an undefined method Illuminate\Contracts\View\Factory|Illuminate\View\View::with().
```

**Comment by nunomaduro** [comment]
@ForzaSFerrari I am not sure if you are using the latest version of Larastan.

Just tested that code, and there is no errors.

```
        $user = auth()->user();

        return view('user.profile')->with('user', $user);

```

**Comment by nunomaduro** [comment]
@ForzaSFerrari What is the level you are using?

**Comment by ForzaSFerrari** [comment]
Always the maximum level.

**Comment by Korri** [comment]
Had the same issue, and update to the latest version of PHPStan fixed it though
