### ISSUE TITLE
Unclear why Expects String, array|string|null given is an issue

### ISSUE THREAD

**Issue by JoeCianflone** [nunomaduro/larastan#580]
- Larastan Version: master branch
- `--level` 7:

### Description
Parameter #1 $hostname of function gethostbyname expects string, array|string|null given.                   

### Laravel code where the issue was found

```php

$currentIP = gethostbyname($this->argument('name'));
```
The above code is run in the CLI and it returns the IP address of a site given a string. So you give it foo.com it returns 127.0.0.1 or whatever. So when you run stan on level 7 you get the error `Parameter #1 $hostname of function gethostbyname expects string, array|string|null given.` and I don't exactly get it. `$this->argument()` could return an array or a string or null...but `getbyhostname` expects *just* a string. So in my head I don't see an issue here...while `argument()` could be an array...I don't want that, so if that was returned, I'd want getbyhostname to yell at me. I guess I could be more explicit here and coerce `$this->argument()` to *always* be a string? I guess I'm wondering why is PHPStan yelling at me if `getbyhostname` wants a string and `$this->argument()` could return a string?

**Comment by canvural** [comment]
Hi,

It is pretty clear in my opinion. `argument` returns an union type but `gethostbyname` expects just a string. These types don't match, therefore you have an error.

This kind of errors starting to be reported at level 7. So you can stay at level 6 if you don't want to see them. You can check [here](https://phpstan.org/user-guide/rule-levels) for the level documentation.

Or you can [narrow down the type](https://phpstan.org/writing-php-code/narrowing-types) like this
```php
<?php
/** @var string $argument */
$argument = $this->argument('name');
$currentIP = gethostbyname($argument);
```

Lastly, this is not a Larastan issue. Please report this kind of issues to PHPStan directly. (After checking the [documentation](https://phpstan.org/user-guide/getting-started) of course.)

**Comment by JoeCianflone** [comment]
@canvural thanks, I realized after I submitted this that this was a level/phpstan thing, but thanks for taking the time to answer it anyway!
