### ISSUE TITLE
laravel redis not able to check

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#581]
- Larastan Version: 0.5.8
- `--level` used: max

### Description
Is there a trick to step up for  laravel Redis. now I just can only use original redis class could not able to use laravel facades redis. need help.

### Laravel code where the issue was found

```
use Illuminate\Support\Facades\Redis;
$redis  = Redis::connection();
$top_up = $redis->lrange('headquarters_statistics:top_up', 0, -1);
```
`Call to an undefined method Illuminate\\Redis\\Connections\\Connection::lrange().`
```
use Illuminate\Support\Facades\Redis;
$top_up = Redis::lrange('headquarters_statistics:top_up', 0, -1);
```
`Call to an undefined static method Illuminate\\Support\\Facades\\Redis::lrange().
`

------------------------------------------------------------------------------------------------
workaround
```
use Redis;
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$top_up = $redis->lrange('headquarters_statistics:top_up', 0, -1);
```

**Comment by canvural** [comment]
Hi,

Thanks for the report. I think this is related to #203. I'd appreciate any help with this!

**Comment by mr-feek** [comment]
Mixin annotation should work
