### ISSUE TITLE
`RedirectResponse::with()` expects `array|string`, `true` given

### ISSUE THREAD

**Issue by matthewsuan** [nunomaduro/larastan#586]
- Larastan Version: 0.5.8
- `--level` used: 5

### Description
The following code throws an error:
```php
return redirect()->back()->withSuccess(true);
```

```
Parameter #1 $key of method Illuminate\Http\RedirectResponse::with() expects array|string, true given.
```

**Comment by canvural** [comment]
Hi,

Is `withSucess` a macro you wrote? I don't think this is in Laravel.

And the error message is different than the code example you shared. So I'm not sure what the real issue is. But the error message is correct, you can't pass `true` to `with` method.

**Comment by Daanra** [comment]
RedirectResponse can dynamically forward calls to `with` just like a Builder does with `where`:
```php
public function __call($method, $parameters)
{
        // ...
        if (Str::startsWith($method, 'with')) {
            return $this->with(Str::snake(substr($method, 4)), $parameters[0]);
        }

        static::throwBadMethodCallException($method);
}
```
So `withSuccess(true)` seems like it would be equivalent to `with('succes', true)`

**Comment by canvural** [comment]
> RedirectResponse can dynamically forward calls to `with` just like a Builder does with `where`:

Ah, didn't know that!

> 
> Also see:
> 
> https://github.com/nunomaduro/larastan/blob/0a4edcd23955c0cd209395d44ed476339d003605/src/Methods/Pipes/RedirectResponseWiths.php#L28-L37

Ok, so it seems this is indeed a bug here.
