### ISSUE TITLE
`Larastan\Methods\Macro` does not implement `PHPStan\Reflection\Php\BuiltinMethodReflection::getReflection`

### ISSUE THREAD

**Issue by oppiansteve** [nunomaduro/larastan#587]
- Larastan Version: v0.5.8
- `--level` used: 5

### Description

Sorry, if I've missed this already being raised, of if I'm missing something obvious, but running phpstan now raises this error with Laravel 7, but only once at around 88% through:

In Macro.php line 16:
```
Class NunoMaduro\Larastan\Methods\Macro contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\Php\BuiltinMethodReflection::getReflection)

PHP Fatal error:  Class NunoMaduro\Larastan\Methods\Macro contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\Php\BuiltinMethodReflection::getReflection)
```

if it helps, I'm running using `vendor/bin/phpstan analyse --no-interaction --memory-limit=1024M`

I am defining my own class derived from `MethodsClassReflectionExtension` and have inline classes implementing `MethodReflection` and also `ParametersAcceptor`

**Comment by canvural** [comment]
Hi,

Which version of PHPStan are you using? I saw an issue like that with the latest `master` of PHPStan. But shouldn't happen if you use any stable release.

**Comment by oppiansteve** [comment]
ah ha, I thought I was using a fixed release, but seems not.
I've changed it to "0.12.25" and it now works fine - sorry about that

**Comment by canvural** [comment]
No problem :blush:
