### ISSUE TITLE
Builder mixin creates more  errors

### ISSUE THREAD

**Issue by drewjw81** [nunomaduro/larastan#588]
- `--level` used: 5

### Description

We include `@mixin Builder` in our model docs to aid in code completion. But this causes errors like `Static call to instance method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::create()` in larastan. If we remove `@mixin Builder` they go away but then the various editors our devs use lose code completion. Is there a workaround for this, or something I missed in setup?

**Comment by szepeviktor** [comment]
The only thing pops into my head is https://github.com/phpstan/phpstan-src/blob/f96e0de5924cab79e78f41c96a6e039a175f1849/conf/config.neon#L40

**Comment by drewjw81** [comment]
That seems to do it. Thanks

**Comment by shalvah** [comment]
Hey, I can't figure out how to fix this. @drewjw81 what was the fix specifically?

**Comment by rihardssceredins** [comment]
@uintaam i'm wondering about this too. How did you manage to fix it?

**Comment by rihardssceredins** [comment]
Ok, got it. Adding this to `phpstan.neon` in my project got rid of the error:

```
parameters:
    mixinExcludeClasses:
        - Illuminate\Database\Eloquent\Builder
```
