### ISSUE TITLE
Call to an undefined method forever().

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#59]
```
$response->withCookie(cookie()->forever('name', 'value'));
```
Produce:
> Call to an undefined method Illuminate\Cookie\CookieJar|Symfony\Component\HttpFoundation\Cookie::forever().

**Comment by nunomaduro** [comment]
@ForzaSFerrari Can you show me how the variable $response was build ?

**Comment by ForzaSFerrari** [comment]
Sent you a screenshot on Twitter

**Comment by nunomaduro** [comment]
What is the level you are using?

**Comment by ForzaSFerrari** [comment]
Always the maximum level.
