### ISSUE TITLE
Breaking change in PhpStan 0.12.26 causeing larastan to error

### ISSUE THREAD

**Issue by georgeboot** [nunomaduro/larastan#591]
- Larastan Version: v0.5.8

### Description
`This option has been replaced with bootstrapFiles which accepts a list of files
to execute before the analysis.`

Suspected commit: https://github.com/phpstan/phpstan-src/commit/aad1bf888ab7b5808898ee5fe2228bb8bb4e4cf1

Releates to https://github.com/phpstan/phpstan/issues/3408

**Comment by canvural** [comment]
Hi,

Yes, Larastan is not yet compatible with PHPStan 0.12.26. #590 is gonna fix that issue :+1: Meanwhile you can stay at PHPStan 0.12.25
