### ISSUE TITLE
Bootstrap option is depcrecated

### ISSUE THREAD

**Issue by FonsAtabix** [nunomaduro/larastan#592]
- Larastan Version: 0.5.5
- `--level` used: 8

### Description

PHPStan still works, but when running PHPStan the output gives the following warning:

```
$ #!/bin/sh -eo pipefail
composer analyse

> ./vendor/bin/phpstan analyse
Note: Using configuration file /home/webapp/project/phpstan.neon.
⚠️  You're using a deprecated config option bootstrap. ⚠️️
```

I believe this refers to [line 20 of `extension.neon`](https://github.com/nunomaduro/larastan/blob/v0.5.5/extension.neon#L20).

**Comment by canvural** [comment]
Hello,

Yes, this was a knows issue. It was fixed by #590 There will be a release with this fix soon. Meanwhile you can stay at PHPStan 0.12.25
