### ISSUE TITLE
Reflection error with encrypted binary file

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#598]
- Larastan Version: 0.5.8
phpstan version 0.12.26
- `--level` used:max

Error Occur when I composer updated , because
phpstan version changed to 0.12.26 but work fine in phpstan version 0.12.25
![image](https://user-images.githubusercontent.com/27404296/84049700-5493e080-a9df-11ea-91f4-4f74c3c126aa.png)

### Code snippet that reproduces the problem

`/var/www/jianghu_entertain/vendor/bin/phpstan analyse -c /var/www/jianghu_entertain/phpcs-rule/phpstan.neon app/Http/Requests/Backend/Headquarters/Report/GameProjectRequest.php --error-format=table --memory-limit=1G`

[GameProjectRequest.php.txt](https://github.com/phpstan/phpstan/files/4746915/GameProjectRequest.php.txt)

Below is obscued binary file php stan work well in version 0.12.25 but now in 0.12.26 not working well.
[BaseFormRequest.php.txt](https://github.com/phpstan/phpstan/files/4746922/BaseFormRequest.php.txt)

### Expected output
should pass

**Comment by szepeviktor** [comment]
Thank you.

Yes, PHPStan should recognize swoole_loader's encrypted files.
Please report this upstream: https://github.com/phpstan/phpstan/issues/3413
