### ISSUE TITLE
Model stub is wrong

### ISSUE THREAD

**Issue by ollieread** [nunomaduro/larastan#608]
- Larastan Version: 0.6.1
- `--level` used: N/A

### Description
The [`stubs/Model.stub`](https://github.com/nunomaduro/larastan/blob/master/stubs/Model.stub) file has a `Model` class that doesn't extend Laravels. This causes PHPStorm to incorrectly flag the model as missing some necessary methods.

![image](https://user-images.githubusercontent.com/469515/86036171-63e1d900-ba35-11ea-8209-76d98c824a51.png)

To get around this I had to manually mark the stub as plain text.

**Comment by canvural** [comment]
Hi,

`stub` files are not meant to be analyzed by text editors or IDEs. That's why the extension is `.stub` I think you configured your IDE to recognize `.stub` files as `.php` files. You should change that instead.
