### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by MP-okui** [nunomaduro/larastan#610]
- Larastan Version: 0.6.1
- `--level` used: 8

### Description

[phpstan/phpstan-doctrine](https://github.com/phpstan/phpstan-doctrine) Version: 0.12.17

phpstan.neon

```neon
parameters:
	doctrine:
		objectManagerLoader: %currentWorkingDirectory%/tests/phpstan-doctrine.php
```

phpstan-doctrine.php

```php
require __DIR__.'/../vendor/autoload.php';

$app = require __DIR__.'/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

return $app->make(\Doctrine\ORM\EntityManager::class);
```

### Laravel code where the issue was found

phpstan --debug

Invalid argument supplied for foreach()
at vendor/nunomaduro/larastan/src/Methods/Passable.php:179

```php
         if (! $this->staticAllowed && $staticAllowed === false) {
             $statics = $this->resolve('config') === null ? [] : $this->resolve('config')->get('larastan.statics');

             foreach ($statics as $staticClass) {
                 if ($staticClass === $class || $classReflection->isSubclassOf($staticClass)) {
                     $staticAllowed = true;
                     break;
                 }
```

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/larastan/blob/63a393433805a1142fbffe507875f2af825d11fd/src/Methods/Passable.php#L179-L184

**Comment by szepeviktor** [comment]
Relevant commit

https://github.com/nunomaduro/larastan/commit/9f5ffacf0c9f48d100f5cbc63ac949ed2eb7e627

**Comment by szepeviktor** [comment]
@MP-okui Could you help us and `dd($statics);` before the for loop?

**Comment by MP-okui** [comment]
@szepeviktor 

Add `dump($statics);` before the for loop.

# result

/var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php
null

   ErrorException

  Invalid argument supplied for foreach()

  at vendor/nunomaduro/larastan/src/Methods/Passable.php:179
 
```php
         if (! $this->staticAllowed && $staticAllowed === false) {
             $statics = $this->resolve('config') === null ? [] : $this->resolve('config')->get('larastan.statics');
             dump($statics);
             foreach ($statics as $staticClass) {
                 if ($staticClass === $class || $classReflection->isSubclassOf($staticClass)) {
                     $staticAllowed = true;
                     break;
                 }
```

**Comment by szepeviktor** [comment]
Thank you @MP-okui !


Could it be that our config does not get set??

https://github.com/nunomaduro/larastan/blob/63a393433805a1142fbffe507875f2af825d11fd/bootstrap.php#L31

**Comment by MP-okui** [comment]
@szepeviktor 

How can I check that?

phpstan.neon includes these.

```neon
includes:
	- vendor/nunomaduro/larastan/extension.neon
	- vendor/phpstan/phpstan-doctrine/extension.neon
	- vendor/phpstan/phpstan-phpunit/extension.neon
	- vendor/phpstan/phpstan-phpunit/rules.neon
	- vendor/phpstan/phpstan-mockery/extension.neon
```

**Comment by szepeviktor** [comment]
unintentional close :)

Please try `dd()`-ing values one by one.

**Comment by MP-okui** [comment]
@szepeviktor 

This is `dump($statics)`.

# phpstan --debug

/var/www/html/app/Console/Kernel.php
array:2 [
  0 => "Illuminate\Database\Eloquent\Model"
  1 => "Illuminate\Support\Facades\Facade" 
]
array:2 [
  0 => "Illuminate\Database\Eloquent\Model"
  1 => "Illuminate\Support\Facades\Facade"
]
/var/www/html/app/Doctrine/Repositories/ScheduleRepository.php
/var/www/html/app/Exceptions/Handler.php
array:2 [
  0 => "Illuminate\Database\Eloquent\Model"
  1 => "Illuminate\Support\Facades\Facade"
]
/var/www/html/app/Http/Controllers/Api/ScheduleController.php
/var/www/html/app/Http/Controllers/Controller.php
/var/www/html/app/Http/Controllers/DoctrineController.php
/var/www/html/app/Http/Controllers/HomeController.php
/var/www/html/app/Http/Kernel.php
/var/www/html/app/Http/Middleware/Authenticate.php
/var/www/html/app/Http/Middleware/CheckForMaintenanceMode.php
/var/www/html/app/Http/Middleware/EncryptCookies.php
/var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php
null

**Comment by szepeviktor** [comment]
I see!
Sometimes it is **not** an array.

**Comment by szepeviktor** [comment]
Strange.
How could a config *change*??

**Comment by MP-okui** [comment]
What should I provide?
`phpstan.neon` ?

**Comment by szepeviktor** [comment]
@nunomaduro? Our Superman?

**Comment by canvural** [comment]
Fixed with 657bf56

**Comment by szepeviktor** [comment]
@canvural Under what circumstances can that be `null`?

**Comment by canvural** [comment]
@szepeviktor I am not sure :sweat_smile: And it doesn't matter too much, in fact, we should remove this config files in the future. They are not necessary any more.
