### ISSUE TITLE
Call to an undefined method restore()

### ISSUE THREAD

**Issue by ammannbe** [nunomaduro/larastan#616]
- Laravel Version: v7.7.1
- Larastan Version: 0.6.1 / 0.6-dev
- `--level` used: 7

### Description

The reported error:
```bash
 ------ ----------------------------------------------------------------------- 
  Line   app/Http/Controllers/Ingredients/IngredientAttributeController.php     
 ------ ----------------------------------------------------------------------- 
  83     Call to an undefined method                                            
         App\Models\Ingredients\IngredientAttribute|Illuminate\Database\Eloque  
         nt\Collection<App\Models\Ingredients\IngredientAttribute>::restore().  
 ------ -----------------------------------------------------------------------
```

The problem is, that the method `findOrFail` has following return value in phpdocs:
```php
\Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static|static[]
```

### Laravel code where the issue was found

```php
    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return void
     */
    public function restore(int $id)
    {
        $food = Food::onlyTrashed()->findOrFail($id);
        $this->authorize($food);
        $food->restore();
    }
```

I don't know if I can solve the problem by myself, but I thought there must be a better way than exclude every error manually.

**Comment by canvural** [comment]
Hi,

Thanks for the report! This looks weird. Larastan knows that a single model is returned when an integer passed to `findOrFail` Not sure why the collection is not dropped from the union.

Can you just try `Food::findOrFail($id)`? Maybe the soft delete trait is the problem.

**Comment by ammannbe** [comment]
Thanks for that quick response! You're right, seems that the SoftDeletes Trait is the problem.
I just tried your suggestion and it works.
I've also tried `withTrashed()` and `withoutTrashed()` and with both of them it didn't worked.

**Comment by canvural** [comment]
For now you can override the type with `@var`

```php
/** @var Food $food */
$food = Food::onlyTrashed()->findOrFail($id);
```

I'll try to resolve the bug.

**Comment by canvural** [comment]
It's fixed with https://github.com/nunomaduro/larastan/commit/023043b05c9ec04ef92f32960315621fdfe21100
