### ISSUE TITLE
High memory consumption on large test suite

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#621]
- Larastan Version: 0.6.1
- `--level` used: 0, 1, … does not matter

### Description
This is probably a bit meta, so let me explain a bit: I've been using larastan since some time, obviously 😏 , otherwise I wouldn't have been able to report bugs etc.

So far this worked with because I was only using it on `app/`.

I've been using _phpstan_ on `tests/` but only some custom rules so far.

When I now tried to also embrace larastan there, with this minimal config it consumes about 5-6GB RAM, which is borderline to what the VM can handle we use (had to temporarily stop ElasticSearch to free up RAM).

This is the minimal config I use to have high RAM usage:
```neon
includes:
  - ./vendor/nunomaduro/larastan/extension.neon
parameters:
  level: 0
```
So, really only the basics.

Now, the tests are comprised of about ~8k phpunit tests over ~1.1k files and in total we're at about 375k lines of test code 😬

So, running phpstan locally is almost impractical, though it's usually fine on CI (GHA at least, giving 7GB RAM).

"It is probably what it is". And I guess it makes sense that loading / analyzing lots of files is expected to take up RAM, but still caught be a bit by surprise.

At first I got "process timeout" errors from phpstan but it turned on the VM it was running within started to swap and basically came to a halt 😅

### Why do I care running it on the tests
Well, I did manage to get it run and it found potential bugs/leftovers of removed code etc. so there's definitely value in having it.

Since (at least to me) PHP and memory debugging is a big of black magic, I'm not sure how to proceed here or if creating this issue makes even sense: we're talking about a private project, nothing I can give access to.

But maybe some of the devs have an idea or quick win thought how to stabilize memory consumption a bit 🤷‍♀️

Maybe I should look into using https://github.com/BitOne/php-meminfo ? don't have experience with it but looks like the next best thing to do but also means I would need to modify source code somewhere to add the dump call…

**Comment by szepeviktor** [comment]
Larastan is a PHPStan extension for Laravel, so to reduce the memory footprint PHPStan needs to be redesigned.

Have you tries analyzing subdirectories separately?

**Comment by szepeviktor** [comment]
> Since (at least to me) PHP and memory debugging is a big of black magic

Sign up for Blackfire trial!

**Comment by mfn** [comment]
I realized that in fact just phpstan without the larastan extension already consumes LOTS of RAM, just never came across the tipping point which caused the problems I saw.

Closing as it's definitely unrelated to larastan itself, sorry for the noise!

**Comment by mfn** [comment]
Since I already opened _this_ issue, I thought it makes sense to document this here, too.

The latest version of phpstan was just realized https://github.com/phpstan/phpstan/releases/tag/0.12.40
> Optimized memory consumption. It's now down 30 % to 40 % than in 0.12.39!

In the meantime, my originally reported problem was that phpstan consumed, and I verified this before I upgraded with 0.12.38 (from `htop` output):
- VIRT: 1.8GB
- RES: 1.4GB

But note, this was the consumption _per worker_ and 4 of them were running.

With 0.12.40 I get:
- VIRT: 1.3GB
- RES: 1.1GB

Again, _per worker_

(Note: this method isn't very scientific, rather it's: watching `htop` in another terminal and remembering the highest values 😏 )

Not sure where else I could have posted this, so thanks @ondrejmirtes , nice job 👍

**Comment by ondrejmirtes** [comment]
Awesome, thank you :) You can make the number of workers smaller if it bothers you too much: https://phpstan.org/config-reference#parallel-processing

**Comment by mfn** [comment]
But then it's slower 😅 (think about Github Actions / pay per minute…)

But in fact I had to increase `processTimeout` in GHA as the CPUs are a bit slower and tended to timeout.

The codebase is quite a challenge I guess, over 1k files doesn't sound much, but it's a grown test suite, LOTS of trait, lots of test classes with multi-thousand lines of code and code and code … 💥
