### ISSUE TITLE
Class \Illuminate\Support\Testing\Fakes\NotificationFacadeFake was not found while trying to analyse it

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#622]
- Larastan Version: 0.6.1
- `--level` used: 0

### Description
I've a custom setup for asserting notifications due to special requirements.

- In `\Tests\TestCase` I add my `\Tests\NotificationAssertionTrait`
- This trait makes use of a custom `\Tests\NotificationFacade` extending the one from Laravel
- Has a custom `fake` method so I can use my own `\Tests\NotificationFake`

I've create a reproducible project with:
- the code for all the above => https://github.com/mfn/larastan-notification-trait/tree/master/tests
- a phpstan/larastan configuration => https://github.com/mfn/larastan-notification-trait/blob/master/phpstan-tests.neon
- and a github action showing how it fails => https://github.com/mfn/larastan-notification-trait/runs/912461548?check_suite_focus=true#step:5:14

```
 ------ -------------------------------------------------------------------- 
  Line   TestCase.php                                                        
 ------ -------------------------------------------------------------------- 
         Class \Illuminate\Support\Testing\Fakes\NotificationFacadeFake was  
         not found while trying to analyse it - discovering symbols is       
         probably not configured properly.                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  18     Class \Illuminate\Support\Testing\Fakes\NotificationFacadeFake was  
         not found while trying to analyse it - discovering symbols is       
         probably not configured properly.                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 
```

I even tried to minimize the code triggering this, removing actual body of code and such in this commit:
- https://github.com/mfn/larastan-notification-trait/commit/3e25813dd8cc8b9377fe760cbd342522d70e75c0
- but GHA still fails https://github.com/mfn/larastan-notification-trait/runs/912475272?check_suite_focus=true#step:5:13

I've literally no idea where it does come up with that name or the line number (!) and where the problem lies 🤷‍♀️

**Comment by mfn** [comment]
Fun fact: in `tests/NotificationFacade.php` I could change
```php
use Illuminate\Support\Facades\Notification;

class NotificationFacade extends Notification
{
}
```
to
```php
use Illuminate\Support\Facades\Cache;

class NotificationFacade extends Cache
{
}
```
and then get
> `Class \Illuminate\Support\Testing\Fakes\CacheFake was not found while trying to analyse it`

**Comment by szepeviktor** [comment]
> Class \Illuminate\Support\Testing\Fakes\NotificationFacadeFake was  
>          not found

I think the classes name is `Illuminate\Support\Testing\Fakes\NotificationFake`
https://github.com/illuminate/support/blob/63a50a0ad26a336907b40bd59621b6b947c8eb41/Testing/Fakes/NotificationFake.php#L16
not `NotificationFacadeFake`

**Comment by mfn** [comment]
Of course, that's the perplexing thing 😄 You won't find the name `NotificationFacadeFake` anywhere in the sample repo!

**Comment by mfn** [comment]
I failed to mention but as @szepeviktor tried it themselves, removing larastan from the phpstan config "works":
- https://github.com/mfn/larastan-notification-trait/pull/1/files
- https://github.com/mfn/larastan-notification-trait/pull/1/checks#step:5:10
  > `[OK] No errors`

**Comment by szepeviktor** [comment]
I'm only a `himslef` :)

**Comment by mfn** [comment]
Tried my best to not assume anything 😏

**Comment by canvural** [comment]
`NotificationFacadeFake` was coming from [this](https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Facades.php#L44) method. 

We weren't checking if the fake facade actually exists. Added the check with 852c131 Can you try the latest `master`?

Also, you need to add `@method` annotations to the `NotificationFacade` if you want PHPStan to understand the method calls. Or you can add `@mixin \Tests\NotificationFake`

**Comment by mfn** [comment]
I can confirm the issue is fixed with the change!

> Also, you need to add `@method` annotations to the `NotificationFacade` if you want PHPStan to understand the method calls. Or you can add `@mixin \Tests\NotificationFake`

Awesome, phpstan even reminded me about that with a "call to an undefined static method"

Is there a release planned soon? Otherwise I can go with the dev alias `0.6-dev` I guess.

All solved and so quickly, thank you very much 🙇

**Comment by canvural** [comment]
> Is there a release planned soon?

I want to make a new release when there is new PHPStan version is released. There are some bug fixes there that Larastan benefits.

**Comment by johanvanhelden** [comment]
@canvural @szepeviktor I am having a similar issue using the Maatwerk Excel package's `Excel` facade calling the `Excel::fake()` during my tests and getting:

```
Class \Illuminate\Support\Testing\Fakes\ExcelFake was not found while trying to analyse it - discovering symbols is probably not configured properly.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
```

The actual facade is located in: `Maatwebsite\Excel\Fakes`.


Should that error also be fixed with https://github.com/nunomaduro/larastan/commit/852c1313e1c94feab8da8055d0abceda97a27586, or should I open a new issue?

**Comment by canvural** [comment]
@johanvanhelden Are you using 0.6.2?

**Comment by johanvanhelden** [comment]
I thought it was still unreleased because a composer update just now only updated to 0.6.1.

But after removing the package and re-requiring it's at 0.6.2 now and indeed the issue is fixed, thanks!
