### ISSUE TITLE
False positive for "Called 'first' on Laravel collection, but could have been retrieved as a query"

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#623]
- Larastan Version: 0.6-dev
- `--level` used: 1

### Description
```php
App\User::where('users.id', '=', 1)->pluck('email')->first();
```
Output e.g. `your@email.com`

I'm in fact not sure what the larastan error is trying to tell me here, because for this kind of code you **can't** reverse pluck/first, it gives a totally different result (just try it with any system you have at hand):
```php
App\User::where('users.id', '=', 1)->first()->pluck('email');
```
This in fact returns all emails of all users 💥

**Comment by Daanra** [comment]
```php
App\User::where('users.id', '=', 1)->first()->email;
```

Should achieve the same without retrieving all users from the database right?

**Comment by mfn** [comment]
🤔

**Comment by canvural** [comment]
Wow, how does that even work? Why `App\User::where('users.id', '=', 1)->first()->pluck('email');` returns all emails of all users? Isn't the call to `pluck` here on a model instance?

**Comment by mfn** [comment]
Yeah it is, totally weird.

But @Daanra is absolutely right, totally useless complex. No idea why I didn't see it? "cannot see the forest for the trees" syndrome.

Nothing to be done!

**Comment by Daanra** [comment]
>Wow, how does that even work?

> Yeah it is, totally weird.

I agree that this line `App\User::where('users.id', '=', 1)->first()->pluck('email');` gives a very confusing result. Might be nice to make another Larastan rule that forbids constructs like this one.

**Comment by canvural** [comment]
Just `pluck` has this issue I guess. Maybe it should be fixed in Laravel itself? It should be scoped to the current model instance, not every row in the database.

**Comment by canvural** [comment]
But `User::pluck('email')` and `$user->pluck('email')` is kinda the same in Laravel's eyes.
