### ISSUE TITLE
Parameter #2 $values of method Illuminate\Database\Query\Builder::whereBetween() expects array<string, mixed>, array<int, Carbon\CarbonImmutable> given.

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#624]
- Larastan Version: 0.6-dev
- `--level` used: 1

### Description
```php
DB::table('some_tables')->whereBetween('created_at', [CarbonImmutable::now()->subMinutes(30), CarbonImmutable::now()])
```
generates
```
         Parameter #2 $values of method
         Illuminate\Database\Query\Builder::whereBetween() expects
         array<string, mixed>, array<int, Carbon\CarbonImmutable> given.
```
But this code is perfectly fine/correct!

**Comment by mfn** [comment]
Same also for `orWhereBetween`

**Comment by canvural** [comment]
The QueryBuilder stub we have is wrong. [Here](https://github.com/nunomaduro/larastan/blob/master/stubs/QueryBuilder.stub#L470) it can be just `mixed[] $values` I think.

Same for the other issues. So a basic search and replace for `array<string, mixed>  $values` and replacing it with `mixed[] $values` should be enough. Feel free to send a PR. If not I can fix it later.

**Comment by mfn** [comment]
PR via https://github.com/nunomaduro/larastan/pull/626
