### ISSUE TITLE
0.6 not scan all files

### ISSUE THREAD

**Issue by Shahrudinov** [nunomaduro/larastan#628]
- Larastan Version: 0.6.2
- `--level` used: 3

### Description
Not scan all files. show message " [OK] No errors   ". But version 0.5.* find many errors with same code.

**Comment by canvural** [comment]
Hi,

There is not much information to understand what is the issue. Maybe you got all false positives with 0.5.* and with 0.6 it's all fixed? Unlikely though.

You can run PHPStan with `--debug` to see the analysed files. And check if any files are missing.

**Comment by Shahrudinov** [comment]
sorry. looks like this problem in my code.

**Comment by szepeviktor** [comment]
No problem.
Feel free to report the next bug!
