### ISSUE TITLE
Suggestion: Inspect model traits @mixin for getAttribute and setAttribute to ascertain property types

### ISSUE THREAD

**Issue by axit-joost** [nunomaduro/larastan#636]
- Larastan Version: 0.6.2
- `--level` used: 5

### Description

This is not a bug, but more like a suggestion or a feature request.

I have a model that `HasEnums` (spatie/laravel-enum) and `HasState` (spatie/laravel-model-states) and I am getting the following 'errors':

```sh
 ------ ---------------------------------------------------------------------------
  Line   src/Order/Controllers/Api/ConfirmOrderController.php
 ------ ---------------------------------------------------------------------------
  13     Cannot call method transitionTo() on string.
 ------ ---------------------------------------------------------------------------
```

and
```sh
 ------ --------------------------------------------------------------------
  Line   src/Order/Controllers/Api/OrderController.php
 ------ --------------------------------------------------------------------
  185    Cannot call method isEqual() on string.
 ------ --------------------------------------------------------------------
```

In both cases, `larastan` will traverse the migrations to get the actual type of the column, which are indeed strings, so technically, this error is both accurate and on point.

However, the utilized packages will `@mixin` with the `Model` and either provide `setAttribute()` and `getAttribute()` (in the case of `laravel-enum`) as well as performing a `$model->setAttribute()` (in the case of laravel-model-states) that basically alter or otherwise modify the 'type' the property.

The immediate problem of the errors is easily alleviated by providing a docblock above the class, declaring the correct types for the `@property`, like so:

```php
/**
 * @property OrderState $status
 * @property OrderTypeEnum $type
 */
```

My question (or suggestion, or feature request) would be for larastan to do some deeper inspection on the models to ascertain the correct types. Of course this should be done in a generic way, you don't want to create custom logic for millions of external packages. 

However, in some cases, like with the `enum` package, that basically overrides the `getAttribute()` and `setAttribute()` of the `HasAttributes` Eloquent concern, `Larastan` might be able to ascertain the final types (e.g. not just the type ascertained from the migrations).

Looking forward in seeing your thought on this.

**Comment by canvural** [comment]
Hi,

I don't understand how would Larastan/PHPStan would know `status` is the type of `OrderState`. Also, PHPStan does not really analyze 3rd party vendor code. So this would be really hard or impossible.

As you suggested adding the property types with the docblock is a way to go in this case. Larastan would see that and don't use the types from the migrations.

**Comment by axit-joost** [comment]
Hi,

Thanks for taking the time to read and comment, I appreciate it.

As I was typing the issue, I more or less realized the same thing: analyzing 3rd party vendor code simply is not feasible. And adding that DocBlock is fast enough.

Thanks again.

**Comment by canvural** [comment]
Sure, no problem :+1:
