### ISSUE TITLE
Undefined method setAttributeNames() when creating Instance via the Laravel validator() helper

### ISSUE THREAD

**Issue by JayDijkstra** [nunomaduro/larastan#638]
- Larastan Version: 0.6.0
- `--level` used: 3

### Description
When creating a validator instance via the validator() helper, the following error is thrown:
`Call to an undefined method                                                                              
         Illuminate\Contracts\Validation\Factory|Illuminate\Contracts\Validation\Validator::setAttributeNames().`

In code I set a custom attribute name based on the localization used for the application.

### Laravel code where the issue was found

```php
    public function process(Request $request): RedirectResponse
    {
        $validator = validator($request->all(), [
            'message' => 'required',
        ]);

        $validationAttributeNames = [
            'message' => trans('g.label.message'),
        ];

        $validator->setAttributeNames($validationAttributeNames);
        $validator->validate();

        // Further method implementations
     }
```
I hope you can help me out!

Kind Regards!

**Comment by canvural** [comment]
Hi,

Weird, this error shouldn't happen on level 3. I thought errors related to union types are started reporting on level 7.

Anyways, this is a feature request for a new extension for `validator` helper function.

For now you can use

```php
/** @var \Illuminate\Contracts\Validation\Validator $validator */
$validator = validator($request->all(), [
    'message' => 'required',
]);

// Rest of the code
```

to resolve it.

I'll try to implement the new extension later.
