### ISSUE TITLE
RouteCollection vs. RouteCollectionInterface

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#639]
- Larastan Version: v0.6.2
- `--level` used: 5

### Description

https://github.com/szepeviktor/debian-server-tools/blob/2b4157dfc4c67c292a4004f334d4fd178e762974/webserver/laravel/Commands/RouteCheckCommand.php#L51

This fails as follows

> Property App\Console\Commands\RouteCheckCommand::$routes (Illuminate\Routing\RouteCollection) does not accept Illuminate\Routing\RouteCollectionInterface.

How could my code be correct and be nicer than the below forced type?

### Laravel code where the issue was found

```php
    /**
     * The router instance.
     *
     * @var \Illuminate\Routing\Router
     */
    protected $router;

    /**
     * An array of all the registered routes.
     *
     * @var \Illuminate\Routing\RouteCollection
     */
    protected $routes;

    /**
     * Create a new route command instance.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function __construct(Router $router)
    {
        parent::__construct();

        $this->router = $router;
        /** @var \Illuminate\Routing\RouteCollection */
        $routeCollection = $router->getRoutes();
        $this->routes = $routeCollection;
    }
```

**Comment by nunomaduro** [comment]
@szepeviktor You should probably try this:

```php
    /**
     * An array of all the registered routes.
     *
     * @var \Illuminate\Routing\RouteCollectionInterface
     */
    protected $routes;
```
