### ISSUE TITLE
Access to an undefined property on Models attributes

### ISSUE THREAD

**Issue by LucianoVandi** [nunomaduro/larastan#643]
- Larastan Version: 0.6.2
- `--level` used: 5

### Description
I have many models where I'm getting "Access to an undefined property...", these are database column attributes no accessor or custom stuff.

```
 ------ ---------------------------------------------------------------------------
  Line   Http/Controllers/MacroController.php
 ------ ---------------------------------------------------------------------------
  69     Access to an undefined property App\Models\Macro::$name.
  70     Access to an undefined property App\Models\Macro::$comment.
  71     Access to an undefined property App\Models\Macro::$priority.
  72     Access to an undefined property App\Models\Macro::$status.
  73     Access to an undefined property App\Models\Macro::$enabled.
```

### Laravel code where the issue was found

```php
    use App\Models\Macro;

    /**
     * 
     * @param Request $request
     * @param Macro $macro
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request, Macro $macro) {
        $this->authorize('create macro');
        $this->validate($request, $rules, $messages, $customAttr);

        $macro->name = $request->input('name');
        $macro->comment = $request->input('comment');
        $macro->priority = $request->input('priority');
        $macro->status = $request->input('status');
        $macro->enabled = $request->input('enabled');
        $status = $macro->save();

        ...
        return response()->json([
              'status' => $status,
              'data' => $macro
        ]);

    }
```
### Model code

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Macro extends Model {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'macros';

}
```

### Database table

```sql
+-----------------+------------------+------+-----+-------------------+-----------------------------+
| Field           | Type             | Null | Key | Default           | Extra                       |
+-----------------+------------------+------+-----+-------------------+-----------------------------+
| id              | int(10) unsigned | NO   | PRI | NULL              | auto_increment              |
| name            | varchar(255)     | NO   |     | NULL              |                             |
| enabled         | tinyint(1)       | NO   |     | 0                 |                             |
| priority        | varchar(255)     | YES  |     | NULL              |                             |
| status          | varchar(255)     | YES  |     | NULL              |                             |
| comment         | longtext         | YES  |     | NULL              |                             |
| created_at      | timestamp        | NO   |     | CURRENT_TIMESTAMP |                             |
| updated_at      | timestamp        | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
+-----------------+------------------+------+-----+-------------------+-----------------------------+
```
Am I doing something wrong? Do I need to write docblocks with properties on each model class?

Thanks!

**Comment by szepeviktor** [comment]
Larastan should recognize your model's fields.
Is your migration file okay?

**Comment by LucianoVandi** [comment]
@szepeviktor yes, this is how migrations looks like:

```php
class CreateMacrosTable extends Migration {

    protected $table = 'macros';

    public function up() {
        Schema::create($this->table, function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->boolean('enabled')->default(false);
            $table->string('priority')->nullable();
            $table->string('status')->nullable();
            $table->longText('comment')->nullable();
            $table->timestamps();
        });
    }

    public function down() {
        Schema::dropIfExists($this->table);
    }

}
```

**Comment by canvural** [comment]
Hi @LucianoVandi 

Looks like it is because of the usage of `$this->table`. Larastan doesn't resolve that, and it just expects string there.

You can solve it by just inlining the `$this->table`

Later I'll check if it's possible to resolve the value in Larastan.

**Comment by LucianoVandi** [comment]
Hi @canvural, thanks. I've inlined table_name on both `Schema::create()` and `Schema::dropIfExists()`, still get the same result. I'm trying to debug `ModelPropertyExtension::hasProperty()` to see the results of `initializeTables()` but it seems never gets called.

**Comment by canvural** [comment]
Do you have the migrations in the default place or somewhere custom?

**Comment by LucianoVandi** [comment]
Default location: `/database/migrations/2016_03_18_170645_create_macros_table.php`

**Comment by LucianoVandi** [comment]
@canvural sorry, do larastan uses a cache? I've made a small change to the controller, not related with this issue, and now the errors disappeared. -_-

Now I have these left:

```
 ------ -----------------------------------------------------------------------------
  Line   Http/Controllers/UserController.php
 ------ -----------------------------------------------------------------------------
  132    Access to an undefined property Spatie\Permission\Models\Role::$name.
  163    Access to an undefined property Spatie\Permission\Models\Role::$name.
  270    Access to an undefined property Spatie\Permission\Models\Permission::$name.
  289    Access to an undefined property Spatie\Permission\Models\Role::$name.
 ------ -----------------------------------------------------------------------------

 ------ --------------------------------------------------------------------------
  Line   Http/Requests/UpdateUser.php
 ------ --------------------------------------------------------------------------
  38     Access to an undefined property Spatie\Permission\Models\Role::$name.
 ------ --------------------------------------------------------------------------
```
In both files I'm using `Role::find()`, this time I have the migration file but it's from the v1 of the `spatie/laravel-permission`, then upgraded to last versions with [this custom migration](https://gist.github.com/fabricecw/58ee93dd4f99e78724d8acbb851658a4)

**Comment by szepeviktor** [comment]
PHPStan caches everything.
Issue `vendor/bin/phpstan clear-result-cache`

**Comment by mfn** [comment]
Alternatively you can run https://github.com/barryvdh/laravel-ide-helper add the phpdoc `@property` directly to your model.

**Comment by szepeviktor** [comment]
Markus we may disagree on that ide-helper. When I was searching for a way to run PHPStan on WordPress code I realized that software is a no-go.

**Comment by LucianoVandi** [comment]
@mfn I'm already using `barryvdh/laravel-ide-helper`, but with the option `--nowrite` to write on a separate file.

**Comment by canvural** [comment]
So with inlining the table name your problem is solved? 

About the Spatie Role model, Larastan can't parse the migration because of the usage of `$tableNames` in the upgrade migration. There is nothing we can do.

If you want you can create a [stub](https://phpstan.org/user-guide/stub-files) for the `Role` model by yourself and add the properties.

**Comment by LucianoVandi** [comment]
@canvural yes inlining table_name solved the problem, I will look into creating stubs for `Spatie\Permission\Models`. Thanks for your help and for the effort in maintaining Larastan! Have a nice day. ;)

**Comment by mfn** [comment]
> but with the option `--nowrite` to write on a separate file.

If you write them, static analyzers automagically pick them up btw
