### ISSUE TITLE
Problems with auth facade

### ISSUE THREAD

**Issue by grcasanova** [nunomaduro/larastan#644]
_Latest version, level 5, default configuration_

Upon running, all occurrences of `Auth::user()->something` are reported. In the files I simply added `use Auth` as import;
An example:

```
Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$username
Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$id
```

**Comment by canvural** [comment]
Can you try to import the facade with `use Illuminate\Support\Facades\Auth`?

**Comment by grcasanova** [comment]
yes seems to work thanks
