### ISSUE TITLE
 Method Authenticate::redirectTo() should return string|null

### ISSUE THREAD

**Issue by fgilio** [nunomaduro/larastan#645]
- Larastan Version: 0.6.2
- `--level` used: 5

### Description
Hello!
I'm trying Larastan in a new and really small project, which is a much better experience than doing so in an old and messy one... 😅

When running the checks I get this error in a default Laravel file that has no modifications:
```
 ------ ------------------------------------------------------------------------------------------------------------------ 
  Line   Http/Middleware/Authenticate.php                                                                                  
 ------ ------------------------------------------------------------------------------------------------------------------ 
  17     Method App\Http\Middleware\Authenticate::redirectTo() should return string|null but return statement is missing.  
 ------ ------------------------------------------------------------------------------------------------------------------ 
```

### Laravel code where the issue was found

It's a default Laravel file: `app/Http/Middleware/Authenticate.php`
```php
namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }
}
```

Is this something PHPStan/Larastan will eventually understand?

**Comment by szepeviktor** [comment]
If that condition is false PHP implicitly returns null.

Write readable code! Be explicit! Add `return null;` to the end of that method.

**Comment by fgilio** [comment]
Yep! Forgot to mention that's exactly the code change I made. 

So it's just a matter of PHPStan wanting the explicit return statement?

**Comment by szepeviktor** [comment]
> So it's just a matter of PHPStan wanting the explicit return statement?

We humans also want explicit code 😃

**Comment by fgilio** [comment]
Hahaha ❤️

**Comment by amenk** [comment]
We are using level 3 only and a plain Laravel project. It seems to be already triggering with stock Laravel code:

https://github.com/laravel/laravel/blob/9.x/app/Http/Middleware/Authenticate.php

Should we make a Laravel pull request?

I think it would be nice if Larastan does not trigger warnings on fresh Laravel projects, or is this intended?

**Comment by canvural** [comment]
This was discussed before. Laravel team will not accept a PR that is changing that. Or unlikely. 
There is nothing we can do about it. As you can see there is no `return` statement outside of the `if` That is causing the issue.

**Comment by amenk** [comment]
Okay, sorry - but as it is larastan, we could ignore this issue on larastan side?

**Comment by canvural** [comment]
We can't. The error comes from PHPStan not Larastan. But you can ignore it in your config. But it's better to just add `return null`
