### ISSUE TITLE
Access to an undefined property on models

### ISSUE THREAD

**Issue by genesiscz** [nunomaduro/larastan#647]
- Larastan Version: 0.6.3
- `--level` used: 4

### Description
 80     Access to an undefined property Illuminate\Database\Eloquent\Builder<App\Models\UlozenkaBranch>::$name. 
 80     Access to an undefined property Illuminate\Database\Eloquent\Builder<App\Models\UlozenkaBranch>::$lat. 

### Laravel code where the issue was found

```php
$dbr = UlozenkaBranch::firstWhere("id", "=", $branch->getId());
 $dbr->name = $branch->getName();
$dbr->lat = $branch->getGps()->getLatitude();
 
```

sure I can use find() here, but many similar errors where I cant replace it appear too.

**Comment by canvural** [comment]
Hi,

It seems we need to fix the return type of `firstWhere`.

But you say you get this error even when you use `find`. Do you have database migrations for your models? And are they in the default place? Larastan tries to read them to understand the properties of the models. Or if not, do you have `@property` annotations for your properties in your model files?

**Comment by genesiscz** [comment]
Sorry, my English was somewhat sluggish.
I meant that I can replace the firstWhere -> first here, and I did, which supressed the error, but there were many different errors like this caused by firstWhere where I couldnt just easily replace it with some other function.

Would not it be a possibility to use Reflection on Model instead of guessing based on migrations? I did not have any migrations as I like to manage the db with Adminer first. I generated the migrations and it seems that most errors went away. Nice!

**Comment by canvural** [comment]
No, it's not possible to know the properties of a model with reflection. That information is only in database. That's how active record pattern works.

But if everything is ok by changing `firstWhere` to `first` then it's ok. I'll fix the return type of `firstWhere` :+1:

**Comment by genesiscz** [comment]
I mean if you read what `@property` does the model have, I guess PHPstan does it in case it knows where to look at

**Comment by canvural** [comment]
If you define your model properties with `@property` above your class. Then yes, Larastan knows the model properties. And will not scan the migrations.

**Comment by genesiscz** [comment]
This bug is btw applicable even for hasMany relation

**Comment by canvural** [comment]
Yes I'm aware of it. Also `BelongsTo` relations are affected too.
