### ISSUE TITLE
PHPStan Internal error

### ISSUE THREAD

**Issue by DavyDeCoster** [nunomaduro/larastan#650]
- Larastan Version: 0.6.4
- `--level` used: 5

### Description

When I run PHPStan, I get the following exception (flag -vvv used):
```
In StubPhpDocProvider.php line 150:
                                      
  [PHPStan\ShouldNotHappenException]  
  Internal error.                     
```

This config-file is used:

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app

    # The level 8 is the highest level
    level: 5                
```

Recently got this on 2 different codebases.

**Comment by canvural** [comment]
Hi,

Maybe you can try running it with `--debug` to get more information.

That error looks like there is some issue within the stubs. But Larastan's stubs are ok. No errors in CI or in any of my personal projects. Do you have some stubs of your own?

**Comment by Jonatanmdez** [comment]
We had the same issue with our projects. Is not only @DavyDeCoster 

And we don't have any stub, laravel 7 by default. In fact, is a new project with days of life

**Comment by szepeviktor** [comment]
Do you happen to recognize your code in these cases?
https://github.com/nunomaduro/larastan/search?q=ShouldNotHappenException&unscoped_q=ShouldNotHappenException

**Comment by DavyDeCoster** [comment]
```
  PHPStan\ShouldNotHappenException 

  Internal error.

  at phar://vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubPhpDocProvider.php:150
    146|     }
    147|     private function initializeKnownElements() : void
    148|     {
    149|         if ($this->initializing) {
  > 150|             throw new \PHPStan\ShouldNotHappenException();
    151|         }
    152|         if ($this->initialized) {
    153|             return;
    154|         }

```

I think this may be a problem with PHPStan itself.

**Comment by canvural** [comment]
I created new Laravel 7 project, installed Larastan. Scanned `app` directory. No errors. So I'm not sure what is the issue here.

Which Laravel version are you using? Also did `--debug` give you more information?

**Comment by DavyDeCoster** [comment]
@canvural Laravel 7.27.0 is used in my current project. My previous comment was the output of the debug-flag.

**Comment by canvural** [comment]
Can you try to analyze just one file? If it doesn't happen, can you try to find a file in which this error happens?

**Comment by DavyDeCoster** [comment]
@canvural Something strange is happening. I've updated my dependencies through composer and now it's working again. For me updating zircote/swagger-php from 3.0.5 to 3.1.0 fixed the problem.

**Comment by canvural** [comment]
Ah yes. I saw issues related to that in PHPStan repo. https://github.com/zircote/swagger-php/issues/834 and https://github.com/zircote/swagger-php/issues/841

If @Jonatanmdez can also confirm this is the issue, we can close this I think.

**Comment by canvural** [comment]
Closing this one as it seems it's fixed. Please open a new issue if it continues.
