### ISSUE TITLE
Incorrect return type when calling unique on an Eloquent Collection

### ISSUE THREAD

**Issue by Daanra** [nunomaduro/larastan#652]
- Larastan Version: 0.6.4
- PHPStan Version: 0.12.42
- `--level` used: max

### Description

When calling `unique()` on an Eloquent Collection (or a custom Collection class), the return type is inferred as `Illuminate\\Support\\Collection`, however, this is incorrect. 

[Laravel's PHPDoc](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Collection.php#L361) seems to be correct, and it doesn't seem like we're overriding it with a stub. So I'm unsure why this is happening.

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Collection as EloquentCollection;

// ...

public function testCollectionUnique(EloquentCollection $collection): EloquentCollection
{
    return $collection->unique();
}
```

**Error output:**
```
Method Tests\\Features\\ReturnTypes\\CustomEloquentCollectionTest::testCollectionUnique() should return Illuminate\\Database\\Eloquent\\Collection but returns Illuminate\\Support\\Collection.
```

**Comment by canvural** [comment]
I think the return type in Laravel is wrong. It should be just `static` There is no need for union. Changing it to just `static` makes your test case pass.

But I couldn't figure out in which cases can it return `Support/Collection` instead of `Eloquent/Collection` Do you have any example?

**Comment by Daanra** [comment]
> Edit: I think PHPStan normalizes the type static|\Illuminate\Support\Collection to \Illuminate\Support\Collection because it's the parent class.

Thanks for pointing me in the right direction, I wasn't aware of this. This is kind of weird though.  `static|\Illuminate\Support\Collection` is a perfectly valid type and is definitely not equivalent to just `\Illuminate\Support\Collection`. Anyhow, this is more a PHPStan problem.

The `unique` return type was indeed incorrect, so I fixed it [here](https://github.com/laravel/framework/pull/34167).
