### ISSUE TITLE
Pivot Table Attach/Detach results in undefined error

### ISSUE THREAD

**Issue by jny986** [nunomaduro/larastan#653]
- Larastan Version: v0.6.4
- `--level` used: 5

### Description

Has many relationship through a pivot with [using()](https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Relations/BelongsToMany.html#method_using) causes error when using [attach()](https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.html#method_attach) or [detach()](https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.html#method_detach)

### Laravel code where the issue was found

Error coming from this code
```php
$result = $page->lists()->attach($list);
```
which relates to this relationship
```php
public function lists(): Relation
    {
        return $this->hasMany(PageList::class)->using(PageListItem::class);
    }
```
### Error

```
 30     Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation<App\Models\PageList>::attach().  
 53     Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation<App\Models\PageList>::detach(). 
```

Any help to resolve this issue would be appreciated.

I am not sure if it is an issue with our code, config or the package.

**Comment by Daanra** [comment]
Does this line of code:
```php
$result = $page->lists()->attach($list);
```
actually work?

Did you not mean to use a `BelongsToMany` relation?

E.g.
```php
public function lists(): BelongsToMany
{
        return $this->belongsToMany(PageList::class)->using(PageListItem::class);
}
```

**Comment by jny986** [comment]
@Daanra Thanks that was the issue.
