### ISSUE TITLE
Incorrect database_path()

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#655]
- Larastan Version: latest
- `--level` used: 1

### Description

When analyzing a superior webshop https://github.com/thepinecode/bazar which is a Composer package, not an application `database_path()` returns `vendor/orchestra/testbench-core/laravel/database/migrations` thus no migration analysis takes place.

### Laravel code where the issue was found

```php
// in Larastan
ModelPropertyExtension::initializeTables()
```

Please advise.

**Comment by szepeviktor** [comment]
After hard-wiring the path it works 🎉

**Comment by canvural** [comment]
This is maybe related to #507 

Also if you are using the `testbench` package, maybe you can copy the migrations into the app `testbench` creates in the `setUp` method. Like we do [here.](https://github.com/nunomaduro/larastan/blob/master/tests/TestCase.php#L19)

**Comment by szepeviktor** [comment]
Thank you.
