### ISSUE TITLE
Call to undefined method MyServiceProvider::package()

### ISSUE THREAD

**Issue by Flynsarmy** [nunomaduro/larastan#660]
- Larastan Version: ^0.6.0@dev
- `--level` used: 5

### Description
My package has a service provider. When running `php -d memory_limit=-1 ./vendor/bin/phpstan analyse` I get the error:
> Error thrown in /path/to/src/MyServiceProvider.php on line 24 while loading bootstrap file /path/to/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php: Call to undefined method My\Package\MyServiceProvider::package()

My phpstan.neon
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src
```

and my service provider class:
```php
<?php

namespace My\Package;

use Illuminate\Support\ServiceProvider;

class MyServiceProvider extends ServiceProvider
{
    protected $defer = false;

    public function boot()
    {
        $this->package('my/package');
    }

    public function register()
    {
        //
    }

    public function provides()
    {
        return [];
    }
}
```

composer.json
```javascript
{
    // ...
    "require": {
        "php": ">=7.4",
        "illuminate/support": ">=4.1.0"
    },
    "autoload": {
        "psr-4": {
            "My\\Package\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "My\\Package\\Tests\\": "tests"
        }
    },
    "minimum-stability": "dev",
    "require-dev": {
        "orchestra/testbench": "6.*",
        "squizlabs/php_codesniffer": "3.*",
        "nunomaduro/larastan": "^0.6.0@dev"
    },
    "scripts": {
        "phpstan": "php -d memory_limit=-1 ./vendor/bin/phpstan analyse"
    }
}
```

**Comment by szepeviktor** [comment]
Try issuing `composer dump-autoload`, Laravel should discover your ServiceProvider.

**Comment by Flynsarmy** [comment]
Running `composer dump-autoload` made no difference. The package is [here](https://github.com/Flynsarmy/laravel-csv-seeder) if you'd like to test:
```
git clone https://github.com/Flynsarmy/laravel-csv-seeder.git
cd laravel-csv-seeder
composer install
composer phpstan
```

**Comment by szepeviktor** [comment]
Here you go!

https://github.com/laravel/sanctum/blob/2.x/composer.json#L38-L47

🚀

**Comment by Flynsarmy** [comment]
Added, though it still didn't fix the problem unfortunately.

**Comment by canvural** [comment]
Where does the `package` methods comes from here: `$this->package('my/package');`?

**Comment by Flynsarmy** [comment]
Actually it might be a relic of the past. The docs had it here (it's an old package)
https://laravel.com/docs/4.2/packages#service-providers

but I guess it is no longer required?

**Comment by canvural** [comment]
Yeah, it does not exist anymore. So the error you got from PHPStan is correct.

**Comment by Flynsarmy** [comment]
Ahh, my bad. Thanks for your time and patience!
