### ISSUE TITLE
Support Laravel 8 factories

### ISSUE THREAD

**Issue by JeroenVanOort** [nunomaduro/larastan#661]
- Larastan Version: 0.6.4
- `--level` used: max

### Description
It's seems that states on the new factories that came with Laravel 8 are not yet supported.

It would be nice if we could deduct the return type of the `Model::factory()` method, added by the [HasFactory](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/HasFactory.php) trait.

### Laravel code where the issue was found

```php
User::factory()->expired()->create();
```

I would love to help out, but I haven't got a clue where to start. If anyone could guide me, I'm very much willing to put some time and effort into this.

**Comment by Daanra** [comment]
> I would love to help out, but I haven't got a clue where to start. If anyone could guide me, I'm very much willing to put some time and effort into this.

One way of doing this would be to write a `DynamicStaticMethodReturnTypeExtension`.

Here's an example of one https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/StorageDynamicStaticMethodReturnTypeExtension.php

See also: https://phpstan.org/developing-extensions/dynamic-return-type-extensions


The class could look something like this:
```php
public function getClass(): string
{
     return Model::class;
}

public function isStaticMethodSupported(MethodReflection $methodReflection): bool
{
     return $methodReflection->getName() === 'factory';
}

public function getTypeFromStaticMethodCall(
    MethodReflection $methodReflection,
    StaticCall $methodCall,
    Scope $scope
): Type {
    $modelName = $methodReflection->getDeclaringClass()->getName();
    // Here you have to determine $factoryName from $modelName
    return new ObjectType($factoryName);
}

```

I haven't worked a lot with the new factories yet, so I'm not sure if there are any caveats, but I think this should be enough to make it work.

**Comment by robbplo** [comment]
I've been spending some time on this, I've got the return type resolving the correct factory but it's still in a union type with the base factory. When i have more time I'll try to fix this.

**Comment by mrsamse** [comment]
For all those who currently have this problem: I solved it by specifying the static method `factory` with a specified return value in the PHPDoc:


```php
/**
 * @method static UserFactory factory(mixed $parameters)
 */
class User extends Model
{
    use HasFactory;
}
```

**Comment by canvural** [comment]
Hi,

I'll be adding support for Laravel 8 factories soon.

Apart from the basic support (`User::factory()->create()` should return `User`), which features would you like to see get implemented? Support for [factory relationships](https://laravel.com/docs/8.x/database-testing#factory-relationships) seems to be possible as well.

**Comment by spawnia** [comment]
@canvural glad to see you pick this up. Given the massive blocker to further Laravel updates that is https://github.com/laravel/framework/pull/37794, I personally would appreciate an MVP and am willing to help.

**Comment by canvural** [comment]
PHPStan errors are rarely blockers. You can ignore them or add to baseline.

I think next week I should have something 👍🏽

**Comment by szepeviktor** [comment]
> PHPStan errors are rarely blockers.

Fro whom? The short-term brave guy or the long-term guy who does care about technical debt?

**Comment by canvural** [comment]
> > PHPStan errors are rarely blockers.
> 
> For whom? The short-term brave guy or the long-term guy who does care about technical debt?

Anyone. It does not block you to deploy and use your code.

**Comment by szepeviktor** [comment]
> It does not block you to deploy and use your code.

It blocks long-term guys like me. CI produces an ❌ and I fix it.

**Comment by szepeviktor** [comment]
@canvural Please do not be a short-term guy. Technical debt can kill any project.

![Monkey User](https://www.monkeyuser.com/assets/images/2018/106-tech-debt.png)
