### ISSUE TITLE
Retry helper stub doesn't accept Throwable

### ISSUE THREAD

**Issue by carlalexander** [nunomaduro/larastan#662]
- Larastan Version: #.#.#
- `--level` used: max

### Description

When using `retry`, the `when` callable will pass the exception to the callable. PHPStan won't accept the code and throw this error:

```console
Parameter #4 $when of function retry expects (callable(Throwable|null): bool)|null, Closure(Throwable): bool given
```

I managed to solve it by changing the stub and adding `TValue` to the `callable` like this:

```php
/**
 * @template TValue
 * @param int $times
 * @param callable(): TValue $callback
 * @param int $sleep
 * @param null|callable(TValue): bool $when
 * @phpstan-return TValue
 *
 * @throws \Exception
 */
function retry($times, callable $callback, $sleep = 0, $when = null)
{
}
```

I'm happy to do a PR with tests. I'm just not familiar with PHPStan stubs so I don't know if my change is correct.

### Laravel code where the issue was found

```php
retry(5, function () {
  // Code to retry
}, 30 * 1000, function (\Throwable $exception): bool {
    return $exception instanceof \RuntimeException;
});
```

**Comment by szepeviktor** [comment]
Let us compare those.

1. `(callable(Throwable|null): bool)|null`
2. `Closure(Throwable): bool`
