### ISSUE TITLE
Call to an undefined method Laravel\Sanctum\Contracts\HasAbilities::delete()

### ISSUE THREAD

**Issue by ammannbe** [nunomaduro/larastan#664]
- Laravel Version: ^7.24
- Larastan Version: ^0.6.4
- `--level` used: 7

### Description

The reported error:

```
 ------ --------------------------------------------------- 
  Line   app/Http/Controllers/Auth/TokenController.php      
 ------ --------------------------------------------------- 
  39     Call to an undefined method                        
         Laravel\Sanctum\Contracts\HasAbilities::delete().  
 ------ ---------------------------------------------------
```

### Laravel code where the issue was found

```php
    /**
     * Remove the specified resource from storage.
     *
     * @return void
     */
    public function destroy()
    {
        auth()->user()->currentAccessToken()->delete();
    }
```

This method comes from the HasApiTokens Trait and returns a HasAbilities Contract.
But as stated in the [documentation](https://laravel.com/docs/7.x/sanctum#revoking-tokens) we can revoke the current token as in the provided code snippet.

Have you any solution? Thanks in advance!

**Comment by szepeviktor** [comment]
In many OOP projects have a very tiny thing - like an Interface - specified, and a bigger object is returned.

```php
/** @var TellPhpstanTheType $token */
$token = auth()->user()->currentAccessToken();
$token->delete();
```

**Comment by ammannbe** [comment]
Thank you.
Yes I already thought about this solution but wasn't sure if that's the best way.

**Comment by canvural** [comment]
Hi,

I think this is Laravel's problem. They shouldn't write an interface if they are gonna call not existing method on it.

The code @szepeviktor showed is the best way to go. Also currently we do not support any Laraval package in Larastan. Only the Laravel core. So I don't think we are gonna fix this here.
