### ISSUE TITLE
Analyzing blade templates

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#665]
Blade templates are not in PHP, so we need to compile them: `php artisan view:cache`
Then simply analyzing the view cache directory can check templates.

![kép](https://user-images.githubusercontent.com/952007/94170607-906c8c00-fe90-11ea-837c-952a3ccc7634.png)

This is my hack to move template variable types into the template itself.

Could we prepend template variables?

**Comment by szepeviktor** [comment]
`/** @var \Illuminate\View\Factory $__env */` is necessary for `{{  }}`

**Comment by nunomaduro** [comment]
Not sure when we will be adding support for this.
