### ISSUE TITLE
Call to an undefined method App\Providers\AppServiceProvider::toSql()

### ISSUE THREAD

**Issue by fgilio** [nunomaduro/larastan#667]
- Larastan Version: 0.6.4
- `--level` used: 1

### Description
I've been trying to make this work without success, please tell me if I should reopen in https://github.com/phpstan/phpstan
I saw that there was a discussion about something similar [here](https://github.com/nunomaduro/larastan/issues/642), but I tried adding the comment and it seems that it's not enough.

This is the error I get:
```
 ------ ------------------------------------------------------------------------ 
  Line   Providers/AppServiceProvider.php                                        
 ------ ------------------------------------------------------------------------ 
  41     Call to an undefined method App\Providers\AppServiceProvider::toSql().  
 ------ ------------------------------------------------------------------------ 
```

### Laravel code where the issue was found
```php
\Illuminate\Database\Query\Builder::macro('toSqlWithBindings', function () {
    /** @var \Illuminate\Database\Query\Builder $this */
    $sql = $this->toSql();
    foreach ($this->getBindings() as $binding) {
        $value = is_numeric($binding) ? $binding : "'$binding'";
        $sql = preg_replace('/\\?/', $value, $sql, 1);
    }

    return $sql;
});
```

---

The weird thing is that I don't get any error if I do this:
```php
/** @var \Illuminate\Database\Query\Builder $this */
$builder = $this;
$sql = $builder->toSql();
foreach ($builder->getBindings() as $binding) {
```

Thanks for taking the time!

**Comment by szepeviktor** [comment]
Please try clearing PHPStan cache.

**Comment by szepeviktor** [comment]
Or try to insert an empty line after `...@var...`

**Comment by canvural** [comment]
Hi,

This is more related to PHPStan. There are still some issues about typehinting `$this` in closures.

As a workaround you can use `assert`:
```php
\Illuminate\Database\Query\Builder::macro('toSqlWithBindings', function () {
    assert($this instanceof \Illuminate\Database\Query\Builder);
    $sql = $this->toSql();
    foreach ($this->getBindings() as $binding) {
        $value = is_numeric($binding) ? $binding : "'$binding'";
        $sql = preg_replace('/\\?/', $value, $sql, 1);
    }

    return $sql;
});
```

**Comment by fgilio** [comment]
Thanks guys!
Tried cleaning the cache, adding spaces and moving things around. But using the `assert` is the only way it works fine.
I think this is related to this issue https://github.com/phpstan/phpstan/issues/149, so I'll comment there.
