### ISSUE TITLE
Call to an undefined method route()/back().

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#68]
```
return redirect()->route('index');
```
Produce:
> Call to an undefined method Illuminate\Http\RedirectResponse|Illuminate\Routing\Redirector::route()
--------
```
return redirect()->back();
```
Produce:
> Call to an undefined method Illuminate\Http\RedirectResponse|Illuminate\Routing\Redirector::back().

**Comment by nunomaduro** [comment]
What is the level you are using?

**Comment by ForzaSFerrari** [comment]
Always the maximum level.

**Comment by szepeviktor** [comment]
Could all of you test @Korri 's solution?

**Comment by bramceulemans** [comment]
I am getting this exact error message @nunomaduro 

```
Call to an undefined method Illuminate\Http\RedirectResponse|Illuminate\Routing\Redirector::route().
```
