### ISSUE TITLE
Unit test problem on MINGW64

### ISSUE THREAD

**Issue by xitox97** [nunomaduro/larastan#681]
Laravel version: master

### Description
I just fork this repo and run composer test on master branch. I got a fail test for my PHPUnit. I already run composer install. Is there anything that I'm doing wrongly?

![image](https://user-images.githubusercontent.com/15958161/95650395-0b32d980-0b16-11eb-9b8b-b0e5df083384.png)

I'm using windows 10. PHP 7.4.5

**Comment by szepeviktor** [comment]
Please share the *text* of the error message with us.

**Comment by xitox97** [comment]
```
1) Tests\FeaturesTest::testFeatures with data set "Methods\Builder.php" ('E:\Code\Package\larastan\test...er.php')
null
```
@szepeviktor this one?

**Comment by szepeviktor** [comment]
😲 Just a lonely null??

Try with `--debug` or with `-v`!

**Comment by xitox97** [comment]
yup, same.

```
There were 47 failures:

1) Tests\FeaturesTest::testFeatures with data set "Methods\Builder.php" ('E:\Code\Package\larastan\test...er.php')
null

E:\Code\Package\larastan\tests\FeaturesTest.php:43
E:\Code\Package\larastan\tests\FeaturesTest.php:33

2) Tests\FeaturesTest::testFeatures with data set "Methods\CarbonExtension.php" ('E:\Code\Package\larastan\test...on.php')
null

E:\Code\Package\larastan\tests\FeaturesTest.php:43
E:\Code\Package\larastan\tests\FeaturesTest.php:33

3) Tests\FeaturesTest::testFeatures with data set "Methods\Contracts.php" ('E:\Code\Package\larastan\test...ts.php')
null

E:\Code\Package\larastan\tests\FeaturesTest.php:43
E:\Code\Package\larastan\tests\FeaturesTest.php:33

4) Tests\FeaturesTest::testFeatures with data set "Methods\Facades.php" ('E:\Code\Package\larastan\test...es.php')
null
```

This is for test 47
```
47) Tests\Rules\NoUnnecessaryCollectionCallRuleTest::testNoFalseNegativesQuery
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'Called 'max' on Laravel colle...query.'
-    1 => 'Called 'isNotEmpty' on Larave...query.'
-    2 => 'Called 'pluck' on Laravel col...query.'
 )
```

**Comment by szepeviktor** [comment]
Please debug the output of sprintf here

https://github.com/nunomaduro/larastan/blob/073778dc8f22de6be70ea66a2ce984c524c9f108/tests/TestCase.php#L33

maybe with `error_log();`

**Comment by xitox97** [comment]
![image](https://user-images.githubusercontent.com/15958161/95651225-64e9d280-0b1b-11eb-9d94-18d4695e3270.png)
Like this? I'm using `dump`

**Comment by szepeviktor** [comment]
Yes. The complete return value of sprintf, the whole command line.

**Comment by xitox97** [comment]
`"C:\laragon\bin\php\php-7.4.5\php.exe" E:^\Code^\Package^\larastan^\tests/../vendor/bin/phpstan analyse --no-progress  --level=max --configuration "E:\Code\Package\larastan\tests/../extension.neon"  "E:\Code\Package\larastan\tests\Features\Methods\Builder.php" --error-format=json`

**Comment by szepeviktor** [comment]
Does it run?
So this produces the null?

**Comment by szepeviktor** [comment]
I think we don't support MINGW64, only pure Windows.

**Comment by xitox97** [comment]
> Does it run?
> So this produces the null?

TBH I dont know whether that is the cause that produces the null or not.

I tried using Windows PowerShell and CMD both also same.
![image](https://user-images.githubusercontent.com/15958161/95651512-7d5aec80-0b1d-11eb-9c98-aa0d78c1399d.png)
![image](https://user-images.githubusercontent.com/15958161/95651517-864bbe00-0b1d-11eb-9a0b-9c0a5128e82f.png)

**Comment by szepeviktor** [comment]
> "C:\laragon\bin\php\php-7.4.5\php.exe" E:^\Code^\Package^\larastan^\tests/../vendor/bin/phpstan analyse --no-progress  --level=max --configuration "E:\Code\Package\larastan\tests/../extension.neon"  "E:\Code\Package\larastan\tests\Features\Methods\Builder.php" --error-format=json

This is highly abnormal in my eyes.

See #682!

**Comment by xitox97** [comment]
I tried pull the PR 682, and still not solves my issue.

**Comment by szepeviktor** [comment]
Could you run it actually?
If not what to modify in it?

**Comment by xitox97** [comment]
> Could you actually run the dumped value thus command?
> If not what to modify in it?

Using Latest PR from #682 
I got this value from sprint f
```
"C:\laragon\bin\php\php-7.4.5\php.exe" E:^\Code^\Package^\larastan/vendor/bin/phpstan analyse --no-progress --level=max --error-format=json --configuration="E:\Code\Package\larastan/extension.neon" "E:\Code\Package\larastan\tests\Features\Methods\Builder.php"
```
Result after I run above code

![image](https://user-images.githubusercontent.com/15958161/95659686-57e9d500-0b55-11eb-9aec-d8f5c444e683.png)


Then I modify it to be like this 
```
"C:\laragon\bin\php\php-7.4.5\php.exe" "E:\Code\Package\larastan/vendor/bin/phpstan" analyse --no-progress --level=max --error-format=json --configuration="E:\Code\Package\larastan/extension.neon" "E:\Code\Package\larastan\tests\Features\Methods\Builder.php"
```

and try run it and got this

![image](https://user-images.githubusercontent.com/15958161/95659722-8d8ebe00-0b55-11eb-84bd-4299686ec10b.png)

I saw this [issue](https://github.com/nunomaduro/phpinsights/issues/41), and try follow remove the php command as said they said [here](https://github.com/nunomaduro/phpinsights/issues/41#issuecomment-492402148). Then I got the output like this 

![image](https://user-images.githubusercontent.com/15958161/95659773-eb230a80-0b55-11eb-9215-bdf0aee41ca7.png)

**Comment by xitox97** [comment]
@szepeviktor I update execLarastan function to be like this 
```
public function execLarastan(string $filename)
    {
        $command = escapeshellcmd(dirname(__DIR__).'/vendor/bin/phpstan');
        
        exec(
            '"E:\Code\Package\larastan/vendor/bin/phpstan" analyse --no-progress --level=max --error-format=json --configuration="E:\Code\Package\larastan/extension.neon" "E:\Code\Package\larastan\tests\Features\Methods\Builder.php"',
            $jsonResult
        );

        return json_decode($jsonResult[0], true);
    }
```

Then I run PHPUnit, only got 7 failures. Before this 47 failures.

![image](https://user-images.githubusercontent.com/15958161/95659853-9764f100-0b56-11eb-8efe-414280e2e5d1.png)

**Comment by szepeviktor** [comment]
Thank you for your digging!

BTW Do you know how to detect MINGW64? Maybe by PHP_OS and PHP_OS_FAMILY ?

**Comment by szepeviktor** [comment]
🤔 https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/helpers.php#L361

**Comment by szepeviktor** [comment]
This rabbit hole is very deep https://www.php.net/manual/en/function.escapeshellarg.php#123718

You should not get funky stuff like `E:^\Code^\Package^\larastan/vendor/bin/phpstan` on MINGW64.

Surprisingly this works in cmd.exe: `C:^/Windows/explorer.exe` :)

**Comment by xitox97** [comment]
> This rabbit hole is very deep https://www.php.net/manual/en/function.escapeshellarg.php#123718
> 
> You should not get funky stuff like `E:^\Code^\Package^\larastan/vendor/bin/phpstan` on MINGW64.
> 
> Surprisingly this works in cmd.exe: `C:^\Windows/explorer.exe` :)

Yup can confirm that `C:^\Windows/explorer.exe` work in cmd.exe. So I update **execLarastan** method like below. Then try run it in cmd.exe

```
public function execLarastan(string $filename)
    {
        $command = escapeshellcmd(dirname(__DIR__).'/vendor/bin/phpstan');

        exec(
            'E:^\Code^\Package^\larastan/vendor/bin/phpstan analyse --no-progress --level=max --error-format=json --configuration="E:\Code\Package\larastan/extension.neon" "E:\Code\Package\larastan\tests\Features\Methods\Builder.php"',
            $jsonResult
        );

        return json_decode($jsonResult[0], true);
    }
```

Then I got same 7 failures as before. I still need to remove `"C:\laragon\bin\php\php-7.4.5\php.exe"` at front of the command though.

**Without PHP at front**
![image](https://user-images.githubusercontent.com/15958161/95668974-62d05400-0bad-11eb-9a03-915f6549c2f8.png)

**With PHP at front**

![image](https://user-images.githubusercontent.com/15958161/95669010-b80c6580-0bad-11eb-8afd-d1e69af3327b.png)

@szepeviktor  is it possible that my PHP environment problem? maybe need someone to test on their windows OS whethere they have same issue like me or not.

**Comment by szepeviktor** [comment]
From where do you have PHP MINGW64? Have you compiled PHP yourself?

**Comment by xitox97** [comment]
I uses MINGW64 because I set Git Bash as default terminal in my vscode. I did not compile PHP by myself, I just download it and put it inside [Laragon](https://forum.laragon.org/topic/166/tutorial-how-to-add-another-php-version-php-7-4-updated).

**Comment by szepeviktor** [comment]
`PHP 7.4.11 (cli) (built: Sep 29 2020 13:17:42) ( NTS Visual C++ 2017 x64 )` from windows.php.net says:

```
C:\usr\php>php -r "echo PHP_OS;"
WINNT
C:\usr\php>php -r "echo PHP_OS_FAMILY;"
Windows
```

**Comment by xitox97** [comment]
> @xitox97 Please run `php path\to\composer run-script test:unit` with this branch.
> 
> ...not really Windows junctions: Composer substitutes `vendor/bin/*` symlinks on Windows with POSIX shell scripts.
> 
> _Originally posted by @szepeviktor in https://github.com/nunomaduro/larastan/pull/682#issuecomment-706689568_

If I run with **PHP infront**

![image](https://user-images.githubusercontent.com/15958161/95679433-5ed02080-0c05-11eb-8a5c-66102dc26cf9.png)

If **without PHP**, I got the **7 failures**. I think there is improvements than before where I run got **47 failures**.

![image](https://user-images.githubusercontent.com/15958161/95679457-8f17bf00-0c05-11eb-8f9d-42ea18fc768c.png)

**Comment by szepeviktor** [comment]
> Edit: I tested both in cmd.exe and MINGW64

Thank you!
Have you pulled the recent changed from my branch?

**Comment by szepeviktor** [comment]
Got it!

Composer uses symlinks on POSIX-compat os-es and POSIX shell scripts on Windows :(

![image](https://user-images.githubusercontent.com/15958161/95679433-5ed02080-0c05-11eb-8a5c-66102dc26cf9.png)

Your path to the Composer tool seems to be a such a POSIX shell script.

Please run `php path\to\REAL\PHAR-FILE\composer run-script test:unit`

**Comment by xitox97** [comment]
> > Edit: I tested both in cmd.exe and MINGW64
> 
> Thank you!
> Have you pulled the recent changed from my branch?

Yup I already pull your latest changes.

@szepeviktor so I run using this command `php C:\ProgramData\ComposerSetup\bin\composer.phar run-script test:unit` and it does show stop at `php "${dir}/composer.phar" "$@"` anymore.

However, I still got 7 failures.

![image](https://user-images.githubusercontent.com/15958161/95680180-3860b400-0c0a-11eb-8492-b6e1dbf531ec.png)

**Comment by szepeviktor** [comment]
All right!
We have a solution.

Please open a separate issue if you are curious about those model property tests. I am!

**Comment by xitox97** [comment]
@szepeviktor Wow. You are legend! :heart_eyes: TQVM. I will open seperate issue for the model property tests. Should I wait for the PR merged first?

**Comment by szepeviktor** [comment]
> Should I wait for the PR merged first?

No, just open that issue.
Please try to fix the failing tests before that!
