### ISSUE TITLE
Make Eloquent builder when() recognize variables is set in the closure if variables is checked in the first param

### ISSUE THREAD

**Issue by crissi** [nunomaduro/larastan#684]
- Larastan Version: v0.6.4
- `--level` used: 6

### Description
Make Eloquent builder when() recognize variables is set in the closure if variables is checked in the first param.

**Error: Offset 'status' does not exist on array().**

### Laravel code where the issue was found

```php
 /**
     * @param array{'filters?':{'status?':int[]}} $args
     */
    public function resolve($root, array $args, SelectFields $fields, ResolveInfo $info)
    {
       $filters = $args['filters'] ?? [];
        $query = EloqentModel::when(isset($filters['status']), function ($query) use ($filters) {
                $query->whereIn('status_id', $filters['status']);
            })->get()`

```
I would love to do it myself, but I do not have enough knowledge about phpstan plugins yet

**Comment by Daanra** [comment]
A possible workaround is to use the second argument of the callback. E.g.
```php
EloquentModel::when($filters['status'] ?? false, function ($query, array $status) {
    $query->whereIn('status_id', $status);
})->get();
```

But, unfortunately, you lose the information that `$status` is an array of ints here, if you dont use another PHPDoc annotation within the closure.

**Comment by canvural** [comment]
See the comment here: https://github.com/phpstan/phpstan/issues/3955#issuecomment-708973931 Closing because of that.
