### ISSUE TITLE
Problems with eloquent relationships

### ISSUE THREAD

**Issue by grcasanova** [nunomaduro/larastan#689]
- Larastan Version: 0.6.4
- `--level` used: default

### Description
Within the User model I have the following relationship
```
public function coupons()
{
        return $this->belongsToMany(Coupon::class);
}
```
Which returns the following error when analysed
`Access to an undefined property App\Models\User::$coupons.`

### Laravel code where the issue was found
Such error is caused by the following line within the _UserController_:
```
$user->coupons->count();
```

**Comment by canvural** [comment]
Hi,

You need to define the return type of the relation method. Either in the docblocks
```php
/**
 * @return BelongsToMany
*/
public function coupons()
{
    return $this->belongsToMany(Coupon::class);
}
```

or as the native return type
```php
public function coupons(): BelongsToMany
{
    return $this->belongsToMany(Coupon::class);
}
```

then Larastan will understand the relation and property access.

**Comment by grcasanova** [comment]
Great thanks

**Comment by grcasanova** [comment]
None of the methods described work

**Comment by canvural** [comment]
@grcasanova Are you getting the same error? Can you share the updated code snippet to reproduce it?

**Comment by grcasanova** [comment]
Ok solved. Two notes for reference.

- types have capital letter: `HasOne`, `BelongsTo`, `HasMany`, etc
- if using return types, remember to reference them at the beginning with:
`use Illuminate\Database\Eloquent\Relations\HasOne;`
