### ISSUE TITLE
Access to an undefined property Illuminate\Database\Eloquent\Model::attribute

### ISSUE THREAD

**Issue by LucianoVandi** [nunomaduro/larastan#691]
- Larastan Version: 0.6.6
- `--level` used: 5
- Laravel Framework 6.18.43

### Description
I'm getting `Access to an undefined property Illuminate\Database\Eloquent\Model::$status`, it happens only if the model is injected in the __construct method.

### Laravel code where the issue was found

**OrderController.php**

```php
    use App\Order;

    /**
     * @var Order
     */
    protected $orderModel;

    /**
     * @param Order $orderModel
     */
    public function __construct(Order $orderModel){
        $this->orderModel = $orderModel;
    }
```
In another method I have:
```php
$order = $this->orderModel
            ->with('items')
            ->with('parcels')
            ->find($invoiceId);
$order->status = Order::INCOMPLETE;
```
It won't happen if I do:
```php
$order = Order::with('items')
            ->with('parcels')
            ->find($invoiceId);
$order->status = Order::INCOMPLETE;
```

**Comment by canvural** [comment]
Hi,

Thank you for the report. I can confirm this is a bug. `$this->orderModel->with()` returns `Builder` without generic type for the model specified. So the default `Model` is used.

I can fix this, but I'd also argue that injecting a model instance and then calling `find` on it does not make much sense. The second example makes more sense.

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/commit/957f34a177be441ce1fe5b3457551c9866ed6da8

**Comment by szepeviktor** [comment]
🐎 6 minutes.

**Comment by mfn** [comment]
> 🐎 6 minutes.

After 11PM ❗
