### ISSUE TITLE
Local scopes not detected

### ISSUE THREAD

**Issue by grcasanova** [nunomaduro/larastan#693]
- Larastan Version: _0.6.4_
- `--level` used: _default_

### Description
Local scopes using Spatie [model states package](https://github.com/spatie/laravel-model-states) fail.

`Call to an undefined method Illuminate\Database\Eloquent\Collection<App\Models\User>::reported()`

Here's how the scope is defined within the _User_ model:
```php
public function scopeReported($query)
{
    return $query->whereState('status', Reported::class);
}
```

The scope is referenced in this way:
```php
$reported_users = $thread->users->reported()->count();
```
where the thread model _hasMany_ users

**Comment by canvural** [comment]
Are you sure that code actually works?

The error looks correct. You should use `$thread->users()->reported()->count()`

**Comment by grcasanova** [comment]
I tried with and without brackets (`users()` and `users`). I'll investigate further. Thanks

**Comment by canvural** [comment]
If you still have issues please try the new release https://github.com/nunomaduro/larastan/releases/tag/v0.6.7 And after that if you still have issues please open a new issue.
