### ISSUE TITLE
MorphToMany relations + withPivot

### ISSUE THREAD

**Issue by kblais** [nunomaduro/larastan#698]
- Larastan Version: 0.6.8
- `--level` used: 5

### Description

This issue is pretty similar to #519, but concerns MorphToMany relations instead of BelongsToMany.

When calling `withPivot()` (or `withTimestamps()`)  on a MorphToMany relation, I have the following error :

> Method App\Models\Tag::addresses() should return Illuminate\Database\Eloquent\Relations\MorphToMany but returns Illuminate\Database\Eloquent\Relations\BelongsToMany.

### Laravel code where the issue was found

```php
class Tag extends Model
{
    public function addresses(): MorphToMany
    {
        return $this->morphToMany(Address::class, 'taggable')
            ->withTimestamps()
        ;
    }
}

class Address extends Model
{
}
```

Am I doing something wrong, or is Larastan incorrectly detecting the return type ?

**Comment by canvural** [comment]
Hi,

That definitely looks like a bug. I'll take a look :+1:
