### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by jameslkingsley** [nunomaduro/larastan#7]
```
'.' is not recognized as an internal or external command, operable program or batch file.
```

Looks like it's to do with `Console\CodeAnalyseCommand` line 42.

**Comment by jameslkingsley** [comment]
I did that, and it solved the issue. However I am now getting this printed out in the console:
```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../phpstan/phpstan/bin" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

"${dir}/phpstan" "$@"
```

**Comment by nunomaduro** [comment]
@jameslkingsley Ok. I need to take a deeper look on this. Thanks.

**Comment by ChristopheB** [comment]
Removing `php` from `php phpstan` [here](https://github.com/nunomaduro/laravel-code-analyse/blob/6b81ad2a79035065a54df134665a70308458dfa1/src/Console/CodeAnalyseCommand.php#L45) does the trick for me (so the line would be just `'phpstan',`).

Not sure how it would impact other platforms though.

**Comment by nunomaduro** [comment]
@ChristopheB @jameslkingsley Can you test now? Just used the solution that exists on laravel.

**Comment by jameslkingsley** [comment]
Same error as before:
```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../phpstan/phpstan/bin" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

"${dir}/phpstan" "$@"
```

**Comment by nunomaduro** [comment]
@jameslkingsley Have you made `composer update nunomaduro/laravel-code-analyse`?

**Comment by ChristopheB** [comment]
I confirm that it does not work using the full path from `Artisan::phpBinary()`.

Please note that there are some special .bat files for Windows in vendor/bin, which can be used directly, so maybe there is no need to prefix the command with `php` at all.

**Comment by jameslkingsley** [comment]
I did @nunomaduro

**Comment by nunomaduro** [comment]
@jameslkingsley @ChristopheB How about now? Just made the solution you both proposed.

**Comment by ChristopheB** [comment]
It works thanks! :ok_hand:

**Comment by jameslkingsley** [comment]
Works for me too!

**Comment by ChristopheB** [comment]
Just to say, I use Laragon (I dropped Homestead and VMs).
