### ISSUE TITLE
lockForUpdate() is not supported in Query Builder

### ISSUE THREAD

**Issue by gitetsu** [nunomaduro/larastan#700]
- Larastan Version: v0.6.8
- `--level` used: 2

### Description

When I call `firstOrFail()` after `lockForUpdate()`, I get the error.

> Call to an undefined method Illuminate\Database\Query\Builder::firstOrFail()

Neither `first()` nor `get()` occurs the problem.

### Laravel code where the issue was found

```php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    public function test()
    {
        return $this
            ->where('id', 1)
            ->lockForUpdate()
            ->firstOrFail();
    }
}

```

Last but not least, thank you very much for creating this product!

**Comment by szepeviktor** [comment]
What is the situation when you remove `lockForUpdate`?

**Comment by gitetsu** [comment]
Thank you for quick response.

> What is the situation when you remove lockForUpdate?

Error has gone.

**Comment by szepeviktor** [comment]
Maybe related: https://github.com/nunomaduro/larastan/issues/487#issuecomment-598030138

**Comment by canvural** [comment]
Hi,

Thank you for reporting. This looks like a false positive. I'll check it :+1:
