### ISSUE TITLE
Larastan not callig initialize{Trait}?

### ISSUE THREAD

**Issue by TheOddler** [nunomaduro/larastan#707]
- Larastan Version: v0.6.9
- `--level` used: 5

### Description

We have a trait that, for each attribute on a model, adds the `camelCase` version of it to the `fillable` list and overwrite `get`- and `setAttribute` so they work too (code below).

However, Larastan now complains the camelCase versions of the attributes don't exist.

When putting a `dd` in the `initializeCamelAttributes` of the trait (called `CamelAttributes`), it's clear this method is never called. Which explains why the camel case version aren't being found.

In an older project we do the same, and there is works fine. However, there we use Larastan version 0.3.17.

I know it would be possible to add all these camelCase versions of the attributes in a comment above each model, however, larastan should be able to do this, as older versions were it seems. In the old version the `dd` does trigger.

### Laravel code where the issue was found

```php
<?php
namespace App\Models\Traits;

use Illuminate\Support\Str;

trait CamelAttributes
{

    public function initializeCamelAttributes()
    {
        dd("initializeCamelAttributes");
        $fillable = $this->getFillable();
        foreach ($fillable as $attr){
            if ( ! in_array(Str::camel($attr), $fillable) ) $fillable[] = Str::camel($attr);
        }

        $this->fillable($fillable);
    }

    public function getAttribute($key)
    {
        if ( ! method_exists($this, $key) ){
            return parent::getAttribute(Str::snake($key));
        } else {
            return parent::getAttribute($key);
        }
    }

    public function setAttribute($key, $value)
    {
        return parent::setAttribute(Str::snake($key), $value);
    }

}
```

**Comment by szepeviktor** [comment]
PHPStan analyzes only used traits. Unused trait do not get analyzed 😿

**Comment by TheOddler** [comment]
But it is used, because it overwrites `getAttribute`, and thus is used a lot really. But I guess it's not directly obvious to larastan that it's used.

Is there a way to force it to check it too?

**Comment by TheOddler** [comment]
I tried "using" the trait, by just calling `getAttribute` somewhere directly in the code. But doesn't seem to trigger it either.

**Comment by szepeviktor** [comment]
"used" means you hav `use CamelAttributes;` in another class.

**Comment by TheOddler** [comment]
Ah ok, I wasn't clear then, I do do that.

```
class AggregatedQuoteLine extends Model implements QuoteLineInterface
{
    use CamelAttributes;

    protected $fillable = [
        'id',
        'name',

        'count',

        'material_cost',
        'material_margin',

        'installation_workhours',
        'installation_hourly_wage',
        'installation_margin',

        'tax',

        'overwritten',
        'parent_overwritten',

        // Extras that are calculated on the quote lines, but should be merged here because things they depend on might not be mergeable
        'material_total',
        'material_total_with_tax',
        'installation_total',
        'installation_total_with_tax',
        'total',
        'total_without_tax',
        'tax_value',
    ];

...
```

Larastan complains the attribute `materialCost` doesn't exist, but does know `material_cost`.

It makes sense it knows about `material_cost`. Because it's in the `fillable` list.

However, `materialCost` is also in there, but only after the trait adds it in `initializeCamelAttributes`. Which isn't being called it seems.

**Comment by szepeviktor** [comment]
> Larastan complains the attribute `materialCost` doesn't exist,

Yes, Larastan does static analysis thus methods in `CamelAttributes` are ignored when detecting properties.
You have to write a PHPStan extension (a single class) to support that.

**Comment by canvural** [comment]
Hi,

Larastan and PHPStan statically analyze your code. We don't execute your code to understand it. (except a couple of situations)

If it was working in previous versions, I'd guess it was by "mistake" and actual type was not inferred.

For this situation I advise you to use `@property` above the class like you mentioned.

**Comment by szepeviktor** [comment]
> (except a couple of situations)

# 🤣
