### ISSUE TITLE
 Call to an undefined method Illuminate\Support\Fluent::onDelete()

### ISSUE THREAD

**Issue by nelson6e65** [nunomaduro/larastan#708]
- Larastan Version: 0.6.9
- `--level` 5:
- Laravel: 8.12.3
### Laravel code where the issue was found

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateBooksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('books', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->foreignId('author_id')->constrained()->onDelete('cascade'); // <-- HERE
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('books', function (Blueprint $table) {
            $table->dropForeign(['author_id']);
            $table->drop();
        });
    }
}

```

Result of runing `./vendor/bin/phpstan analyse`:
```sh
 ------ --------------------------------------------------------------------
  Line   database\migrations\2020_11_02_133706_create_books_table.php
 ------ --------------------------------------------------------------------
  19     Call to an undefined method Illuminate\Support\Fluent::onDelete().
 ------ --------------------------------------------------------------------
```

**How can I override that the return type of method [`foreignId()->constrained()`](https://laravel.com/api/8.x/Illuminate/Database/Schema/ForeignIdColumnDefinition.html#method_constrained) is not `Fluent`, but `ForeignIdColumnDefinition`  instead?**

**Comment by szepeviktor** [comment]
Yes, this is a known thing.

**Comment by szepeviktor** [comment]
> **How can I override that the return type of method [`foreignId()->constrained()`](https://laravel.com/api/8.x/Illuminate/Database/Schema/ForeignIdColumnDefinition.html#method_constrained) is not `Fluent`, but `ForeignIdColumnDefinition` instead?**

```php
/** @var ForeignIdColumnDefinition $definition */
$definition = $table->foreignId('author_id')->constrained();
$definition->onDelete('cascade'); 
```

**Comment by nelson6e65** [comment]
Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@canvural Do we plan to support the `constrained()` method?

**Comment by canvural** [comment]
I think it's more about adding support for `Illuminate\Support\Fluent` 

I don't have any plans, but if someone wants to implement it I will accept a PR! :+1:

**Comment by PHLAK** [comment]
Is this the same thing causing errors on relationships?

Call to an undefined method Illuminate\Database\Eloquent\Relations\HasMany::count().  
Call to an undefined method Illuminate\Database\Eloquent\Relations\HasMany::where().

**Comment by canvural** [comment]
@PHLAK Your issue unrelated to the OP. Yours is related to issues like #824 #804  I think you can find the solution there, if not open a new issue.

**Comment by PHLAK** [comment]
Thanks @canvural, that was what I needed.

**Comment by nunomaduro** [comment]
Fixed here: https://github.com/laravel/framework/pull/37918.

**Comment by nelson6e65** [comment]
Nice! Thanks!
