### ISSUE TITLE
"Access to an undefined property" errors after pruning migrations

### ISSUE THREAD

**Issue by WillyReyno** [nunomaduro/larastan#711]
- Larastan Version: 0.6.9
- `--level` used:7

### Description

After upgrading to Laravel 8 I wanted to clean my migrations with `php artisan schema:dump --prune` but now Larastan returns hundreds of `Access to an undefined property` errors due to all migrations being removed.

Is there a way to avoid that like ignoring migration scan?

**Comment by szepeviktor** [comment]
> `Access to an undefined property`

Larastan knows model properties from migrations. Without those you may get that error.

**Comment by szepeviktor** [comment]
On a second thought, you may add `/** @property ... */` to all models.

**Comment by canvural** [comment]
Hi,

You can,
- Add `@property` to your model files. https://github.com/barryvdh/laravel-ide-helper can help you with that.
- Again using https://github.com/barryvdh/laravel-ide-helper you can generate `_ide_helper_models.php` and then add that to PHPStan stubs.
- [Ignore](https://phpstan.org/user-guide/ignoring-errors) the error. But you will lose the benefit of analysis.

**Comment by mortenscheel** [comment]
I may have found a workaround.

In stead of purging migration files after running schema:dump, move the files to a subfolder called archive. This way Larastan can see the migrations, but Laravel can't.

**Comment by canvural** [comment]
@mortenscheel Since version 2.1.0 Larastan can infer model properties from schema dumps. You don't need a workaround.

**Comment by robjensen82** [comment]
This doesn't work for postgres, getting a lot of `Access to an undefined property`

**Comment by CalebDW** [comment]
> This doesn't work for postgres, getting a lot of `Access to an undefined property`

Same here, is there a solution yet?

I'd rather not use ide_helper to bloat my models with PHPdocs (and from my understanding they don't mix well together), or create a bunch of migrations with the [kitloong/laravel-migrations-generator](https://github.com/kitloong/laravel-migrations-generator) package.

**Comment by canvural** [comment]
@CalebDW Yes, the parser we use is tested only on MySQL. 

If you know a parser that can parse both MySQL and PostgreSQL syntax, you can make a PR 👍🏽

**Comment by CalebDW** [comment]
@canvural,

Thanks for the response, I'll look around. But perhaps this should be something that's noted in [the docs](https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-parameters.md#squashedmigrationspath)? Laravel supports several different formats so one would expect this to as well.

**Comment by CalebDW** [comment]
So after some more digging, it looks like `sql-parser` *might* be able to parse Postgres dumps but they need to be in the plain text format. It seems Laravel just recently moved away from the 'custom' format ([#45805](https://github.com/laravel/framework/pull/45805)).
