### ISSUE TITLE
Error when passing array<string, Closure> to Model::with()

### ISSUE THREAD

**Issue by kvas-damian** [nunomaduro/larastan#712]
- Larastan Version: 0.6.9
- `--level` used: 5

### Description
According to docs Laravel it's possible to pass Closure in array of params for `Model::with()`: https://laravel.com/docs/8.x/eloquent-relationships#constraining-eager-loads

Larastan reports the following error:
`Parameter #1 $relations of static method Illuminate\Database\Eloquent\Model::with() expects array<string>|string, array<int|string, (Closure(mixed): mixed)|string> given.`

### Laravel code where the issue was found

```php
Taxonomy::with([
	'taxonomyTerms' => function ($relation) {
		return $relation->orderBy('_lft');
	},
	'taxonomyTerms.tag',
])

```

**Comment by canvural** [comment]
Hi,

Thanks for reporting. Looks like or stub [here](https://github.com/nunomaduro/larastan/blob/master/stubs/Model.stub#L22) is wrong. I'd accept a PR changing this and adding a test for this case [here.](https://github.com/nunomaduro/larastan/blob/master/tests/Features/Methods/ModelExtension.php)

**Comment by szepeviktor** [comment]
`     * @param  string|array<int|string, (Closure(mixed): mixed)|string>  $relations`

**Comment by canvural** [comment]
Released: https://github.com/nunomaduro/larastan/releases/tag/v0.6.10
