### ISSUE TITLE
Support contract binding in a Laravel ecommerce package

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#714]
- Larastan Version: 0.6.9
- `--level` used: 2

### Description

Contracts are bound to actual Models.
https://github.com/conedevelopment/bazar/blob/master/src/BazarServiceProvider.php#L26-L38
but Larastan keeps complaining about missing properties and methods of Contracts.

```
Access to an undefined property Bazar\Contracts\Models\User::$password.
```

### Laravel code where the issue was found

https://github.com/conedevelopment/bazar/blob/8e00660fa9579d4ec0459848b886449af171a10d/src/Rules/MatchingPassword.php#L38

**Comment by szepeviktor** [comment]
Do I fail to configure something?

**Comment by szepeviktor** [comment]
@nunomaduro Could you help with some directions?

**Comment by nunomaduro** [comment]
Abstracts or interfaces in PHP can't have properties.
