### ISSUE TITLE
Multiple databaseMigrationsPath

### ISSUE THREAD

**Issue by tiagof** [nunomaduro/larastan#715]
- Larastan Version: 0.6.1
- `--level` used: 5

### Description
In a project that follows DDD, there are usually multiple directories where migration files exist:

`database/migrations/*`
`domains/<domain>/Database/Migrations/*`

In these cases it is not possible to configure larastan to scan all the migrations, since the databaseMigrationsPath only accepts a string.

Is there any way to achieve this behaviour through configuration?

**Comment by szepeviktor** [comment]
Thank you for your report!
Currently not.
You have to place/copy all of them to one directory.
