### ISSUE TITLE
False positive on decrement/increment functions

### ISSUE THREAD

**Issue by JJCLane** [nunomaduro/larastan#72]
They are protected so they can be called statically (see [relevant issue](https://github.com/laravel/framework/issues/6006)), but Larastan reports an error: 

> Call to protected method decrement() of class Illuminate\Database\Eloquent\Model.

**Comment by canvural** [comment]
This is fixed in the latest releases.

**Comment by edwinvdpol** [comment]
Got a `increment` report within an observer with the latest version:

`Call to protected method increment() of class Illuminate\Database\Eloquent\Model`

**Comment by szepeviktor** [comment]
Thank you for your report.

Please open a complete issue.

**Comment by nekooee** [comment]
yes in the last version (9.47.0), I get an error for increment:
 Member has protected visibility but can be accessed via '__call' magic method

Article::find(1)->increment('views');

**Comment by canvural** [comment]
@nekooee I don't think that error comes from PHPStan. But if so, please open a new issue, with more details.
