### ISSUE TITLE
PHPStan assumes that model's relation is nullable

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/larastan#720]
- Larastan Version: 0.6.10
- `--level` used: max

### Description
PHPStan assumes that a model's relation is nullable but it's not.

> Cannot access property $email_verified_at on App\Models\User|null.

Code example:
```php
class PostController extends Controller
{
    public function show(Post $post): JsonResponse
    {
        $user = $post->user;

        abort_if((bool) $user->email_verified_at, 422, "User isn't verified"); // <-- the issue occurs here
        
        // ...
    }
}
```

```php
// Post.php
public function user(): BelongsTo
{
    return $this->belongsTo(User::class);
}
```

```php
// _ide_helper_models.php
namespace App\Models{
/**
 * App\Models\Post
 * ...
 * @property int $user_id
 * ...
 * @property-read \App\Models\User $user
 * ...
 * @mixin \Eloquent
 */
	class IdeHelperPost extends \Eloquent {}
}
```

It happens in many places in the app. Any idea why it happens? How to fix it?

**Comment by canvural** [comment]
Hi,

`BelongsTo` relationship does not guarantee that there will be a related model. If the foreign key is null there is no relation.

You can override this in `Post` model by putting `@property-read \App\Models\User $user`

**Comment by MatanYadaev** [comment]
@canvural Thanks for the comment. The foreign key column is not nullable, it should always have a relation. As you can see, `laravel-ide-helper` marked this property as `User` and not `User|null`. I mean, the override you suggested me, is already implemented, and still PHPStan assumes the relation might be null.
Any idea why it assumes that?

**Comment by canvural** [comment]
How is my suggested fix is already implemented? Did you add it on top of the `Post` model?

**Comment by MatanYadaev** [comment]
@canvural I found the cause for the issue. I'm using `laravel-ide-helper` feature: `--write-mixin` (instead of `--write`) https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models

This doesn't work as expected.
```php
/**
 * @mixin IdeHelperPost
 */
class Post extends Model
{
    // ...
}}
```
```php
// _ide_helper_models.php
namespace App\Models{
/**
 * App\Models\Post
 * ...
 * @property int $user_id
 * ...
 * @property-read \App\Models\User $user
 * ...
 * @mixin \Eloquent
 */
    class IdeHelperPost extends \Eloquent {}
}
```

This works:
```php
/**
 * App\Models\Post
 * ...
 * @property int $user_id
 * ...
 * @property-read \App\Models\User $user
 * ...
 * @mixin \Eloquent
 */
class Post extends Model
{
    // ...
}}
```

I prefer these phpDocs to remain in the `_ide_helper_models.php`. Any idea why Larastan doesn't read the `IdeHelperPost` mixin correctly?

**Comment by canvural** [comment]
Try putting `_ide_helper_models.php` to the [`scanFiles` array](https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies) in your PHPStan config

**Comment by MatanYadaev** [comment]
Amazing! Thanks
