### ISSUE TITLE
Doesn't work when autoloading multiple directories into a single namespace

### ISSUE THREAD

**Issue by stancl** [nunomaduro/larastan#724]
- Larastan Version: Latest
- `--level` used: any

### Description

When you use:
```json
"autoload-dev": {
    "psr-4": {
        "Lean\\Tests\\": ["tests/"]
    }
},
```

Larastan will try to get all files in that namespace.

However, it won't loop through the `["tests/"]` array, so it will pass `["tests/"]` as a path to `ClassMapGenerator::createMap()`, when the method expects a string.

![Screen Shot 2020-11-28 at 17 24 10](https://user-images.githubusercontent.com/33033094/100520544-8cb1fa00-319e-11eb-94cf-d65cf1896972.png)

This results in:
```
Error thrown in /Users/samuel/Projects/lean/lean/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php on line 86 while loading bootstrap file /Users/samuel/Projects/lean/lean/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php: Call to a member function getPathname() on string
```

### Code where the issue was found

ApplicationResolver line ~103

### Solution

Loop through the paths, not just through the namespaces.

**Comment by szepeviktor** [comment]
Would you send a one-liner PR?

**Comment by szepeviktor** [comment]
BTW Using the same namespace in two different paths is risky.

**Comment by stancl** [comment]
Yup, I just had the array syntax for a single path by default because my VSCode plugin generated it.

Will send a bug fix shortly.
