### ISSUE TITLE
Property check on dynamic wheres not entirely working

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#726]
- Larastan Version: 0.6.10
- `--level` used: 6

### Description
Replicating what I wrote in https://github.com/nunomaduro/larastan/pull/686#issuecomment-737501518

✔️ This works / no error, because there is a column `profiles.type`:
```php
Profile::whereType('test');
```
✔️ This generates an error now in *stan (correctly 👍 ) because there's no `profiles.yolo`:
```php
Profile::whereYolo('test');
```
produces
```
  57     Call to an undefined static method App\Profile::whereYolo().
```

❌ But this does not generate an error (although there's no `profiles.yolo` column):
```php
Profile::whereType('test')->whereYolo('test');
```

Thank you!

**Comment by canvural** [comment]
Tried something here https://github.com/nunomaduro/larastan/commit/2581f3b255a6ad3f38301d088557a0ddc598dbf8 Can you test again with `master` branch? It should give you the error now.

**Comment by mfn** [comment]
It works 🎉 
```php
  42     Call to an undefined method Illuminate\Database\Eloquent\Builder<App\Profile>::whereYolo().
```
(btw, is there a way to not make phpstan wrap the lines in the terminal ? This drives me crazy)

Ran it over my whole (private) code base, found one other error but that was because I override the return result of a builder (for unknown reason) and thus lost the generics information of the model => removed the superfluous typehint => worked as expected.

Thank you!

**Comment by mfn** [comment]
(not sure if you want to close it now or when released, I'm fine with closing)

**Comment by canvural** [comment]
> (btw, is there a way to not make phpstan wrap the lines in the terminal ? This drives me crazy)

PHPStan uses Symfony Console for commands, outputs and stuff I believe. So if you can do it with Symfony Console, you can do it with PHPStan :smile: 

If it's fixed I will close it now, and release a new version.
