### ISSUE TITLE
Throwing errors on Facade that previously worked fine

### ISSUE THREAD

**Issue by MJTheOne** [nunomaduro/larastan#730]
- Larastan Version: 0.6.11
- `--level` used: 5

### Description
Before the update to 0.6.11 (0.6.10) I had no issues with (for example) Cache::delete() (Cache being the Facade class).
Since updating this throws an error.
Is this supposed to be like this (larastan is being more strict) or is something broken?

### Laravel code where the issue was found

```php
private function clearAbilitiesCache(): void
{
    try {
        Cache::delete(config('cache.user-abilities-key'));
    } catch (InvalidArgumentException $e) {
        Log::error('Cache for abilities could not be cleared', $e->getTrace());
    }
 }
```

**Comment by szepeviktor** [comment]
Could you share the error message with us?

**Comment by MJTheOne** [comment]
```
------ --------------------------------------------------------------------------------
  Line   Observers/AbilityObserver.php
 ------ --------------------------------------------------------------------------------
  30     Call to an undefined static method Illuminate\Support\Facades\Cache::delete().
 ------ --------------------------------------------------------------------------------
```

**Comment by nunomaduro** [comment]
@MJTheOne Shouldn't you be using "forget" instead?

**Comment by szepeviktor** [comment]
> Shouldn't you be using "forget" instead?

I've read about it in Laravel Docs but my developer routine is _near_ 0️⃣

**Comment by MJTheOne** [comment]
> @MJTheOne Shouldn't you be using "forget" instead?

"delete" can be used just as well. Looking at the `laravel/framework/src/Illuminate/Cache/Repository.php` you see there is a public function that's called "delete". (which calls forget, so yes it would be better to use "forget", but laravel *does* support "delete")

**Comment by szepeviktor** [comment]
What does Larastan say about `forget`?

**Comment by MJTheOne** [comment]
No errors. Still feels like 0.6.11 has made *something* more strict because on 0.6.10 the entire application passed on level 5. Since 0.6.11 it doesn't pass. The error's I'm getting are very logical and I know a lot needs to be fixed because eventually I want to pass level 8, but doing a minor update and having to start fixing again is a bit weird imo.

**Comment by szepeviktor** [comment]
> doing a minor update and having to start fixing again is a bit weird imo

Everyone agrees with you providing Larastan v1.0.0 is released :)

**Comment by nunomaduro** [comment]
@MJTheOne I don't think we should release a new major version every time we improve this tool to detect new bugs. You can always pin this dependency to a specific version.

**Comment by szepeviktor** [comment]
> You can always

... improve your code.

The doctor advises to spend 5% of your resource on [technical debt](https://www.monkeyuser.com/2018/tech-debt/).

**Comment by MJTheOne** [comment]
> 
> 
> @MJTheOne I don't think we should release a new major version every time we improve this tool to detect new bugs. You can always pin this dependency to a specific version.

I get that. And I know I need to fix the code base I'm working on. Just wanted to give my two cents on semver.

Really like this package because one of the first things I demanded when I joined this project was: I want static analysis. Then I discovered all the Laravel magic stuff and was getting worried until I found this.

Keep up the good work!
