### ISSUE TITLE
Fatal error on Laravel 6 - seems to be related to orchestra testbench update

### ISSUE THREAD

**Issue by paras-malhotra** [nunomaduro/larastan#732]
- Larastan Version: 6.20.7
- `--level` used: Any level

### Description
I'm getting this error when running Larastan on my code. It was working prior to an update:

> PHP Fatal error:  Class NunoMaduro\Larastan\ApplicationResolver contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (NunoMaduro\Larastan\ApplicationResolver::parseTestMethodAnnotations) in /home/runner/work/enlightn/enlightn/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 16

### Temporary Solution
If I restrict orchestra/testbench-core to 4.10.0 it works again. An update to testbench-core 4.11.0 breaks it.

**Comment by szepeviktor** [comment]
Thank you for your report.
Resolved in here https://github.com/nunomaduro/larastan/pull/731/files

Does it work for you?

**Comment by szepeviktor** [comment]
Please also so https://github.com/orchestral/testbench-core/compare/v4.11.0...v4.11.1

**Comment by paras-malhotra** [comment]
Thanks so much! 👍
