### ISSUE TITLE
->where()->withTrashed() throws Call to an undefined method

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#733]
- Larastan Version: https://github.com/nunomaduro/larastan/compare/v0.6.10...v0.6.11#diff-3109910cd674cea144c1c7aee5a0cb8de4197b417c9ac1b2e739a60586508391
- `--level` used: **5**

### Description

After upgrading to 0.6.11 I get `Call to an undefined method Eloquent\Builder<App\Models\User>::withTrashed()`

### Laravel code where the issue was found

![kép](https://user-images.githubusercontent.com/952007/101764414-5484b280-3ae0-11eb-95c4-289af9201871.png)

**Comment by szepeviktor** [comment]
Thank you for your report, Viktor, but I cannot help you!

**Comment by mgkimsal** [comment]
I was noticing this last night, upgrading to 0.6.11.  I *think* the issue may stem from https://github.com/nunomaduro/larastan/commit/2581f3b255a6ad3f38301d088557a0ddc598dbf8 in the getMethod() call changes, but that's just a first reading.

**Comment by szepeviktor** [comment]
@canvural Could you look around? What went wrong?
