### ISSUE TITLE
Support custom Contracts

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#735]
I've found `Illuminate\Contracts` hardcoded in

https://github.com/nunomaduro/larastan/blob/ca98347313e20fe84daf22c08a31a550153f3be9/src/Methods/Pipes/Contracts.php#L47

What should I do to support a [Laravel package's own contracts](https://github.com/conedevelopment/bazar/tree/master/src/Contracts)?

Modifying Contracts.php works but touching a file is for script-kiddies :)

```php
         if (
             $classReflection->isInterface()
             && Str::startsWith($classReflection->getName(), ['Illuminate\\Contracts\\', 'Bazar\\Contracts\\'])
         ) {
```

Please advise.

**Comment by canvural** [comment]
Hi,

Can you share the piece of code you are getting an error from?

The file you mentioned is there because Laravel uses inheritance kinda wrong. Classes implementing the interface also defines custom methods on their own. And in other places interface is typehinted but that other custom methods are called on it.

**Comment by szepeviktor** [comment]
> Can you share the piece of code you are getting an error from?

Here is the Contract https://github.com/conedevelopment/bazar/blob/master/src/Contracts/Models/Product.php

Example error No1
`Call to an undefined method Bazar\Contracts\Models\Variation::setRelation().` on line 160
https://github.com/conedevelopment/bazar/blob/e8c2ddc5ac82bbbff921bdd77d4cd30d12896aba/src/Models/Product.php#L158-L162

No2
`Call to an undefined method Bazar\Contracts\Models\Order::loadMissing().` on line 60
https://github.com/conedevelopment/bazar/blob/e8c2ddc5ac82bbbff921bdd77d4cd30d12896aba/src/Jobs/PerformConversions.php#L58-L62

💡 This is due to this Laravel package being flexible and users may bind *any* custom implementation of those contracts in the container.
Please do not respond with ["methods cannot be called on interfaces"](https://github.com/nunomaduro/larastan/issues/714#issuecomment-730620630). Thank you.

**Comment by szepeviktor** [comment]
After pre-loading a modified version of Larastan's Contracts.php it Works!

https://github.com/szepeviktor/bazar/blob/eb5dad895c094064740cb39206f02f95b32827d2/tests/phpstan/override-larastan-Contracts.php#L49

**Comment by szepeviktor** [comment]
@canvural Could  `Illuminate\\Contracts\\`  be moved to an option in the neon file?
