### ISSUE TITLE
PHPStan Internal error

### ISSUE THREAD

**Issue by jrmajor** [nunomaduro/larastan#749]
- Larastan Version: 0.6.11
- `--level` used: 2

### Description

```
Internal error: App\Services\Discogs::__construct(): Argument #1 ($token) must be of type string, null given, called in /home/runner/work/bajki-muza/bajki-muza/app/Providers/ServicesServiceProvider.php on line 16 in file /home/runner/work/bajki-muza/bajki-muza/app/Models/Artist.php
```

I'm unable to recreate this error locally, analysis fails only in GitHub action.

`App\Services\Discogs` is registered in the service container and resolved as a real-time facade.

```php
$this->app->singleton(Discogs::class, function ($app) {
    return new Discogs($app->config->get('services.discogs.token')); // here it receives null
});
```

[(full source code)](https://github.com/jrmajor/bajki-muza/blob/ed2133b51fd8866f06cd92050744a65d8864bca3/app/Providers/ServicesServiceProvider.php#L15-L17)

I had submitted an [issue](https://github.com/phpstan/phpstan/issues/4310) in PHPStan repository, but was redirected here.

### PHPStan logs:
Without `--debug`: https://github.com/jrmajor/bajki-muza/runs/1640519092
With `--debug`: https://github.com/jrmajor/bajki-muza/runs/1640542986

**Comment by nunomaduro** [comment]
Seems that `$app->config->get('services.discogs.token')` is returning `null` in your GitHub action.

**Comment by canvural** [comment]
Hi,

Like @nunomaduro said your config value is returning null. This can actually be a bug in production also. Either specify a default value for the config, or make it available with .env,if your config uses env variables.

**Comment by jrmajor** [comment]
Thanks, @canvural!

I thought, that the problem must be somewhere else, because after removing this value from `.env` and even from config files analysis was still passing. It turned out I had to run `clear-result-cache` to reproduce results from CI. `cp .env.example .env` fixed it.
