### ISSUE TITLE
Access to an undefined property REFRESH in Models 

### ISSUE THREAD

**Issue by SHELA** [nunomaduro/larastan#750]
- Larastan Version: 0.6.12
- `--level` used: dev

### Laravel code where the issue was found

```php
src/Illuminate/Database/Eloquent/Model.php refresh method
 return $model->refresh()->categories->pluck('id')->toArray();
Access to an undefined property App\Models\Tip::$categories.  

```

**Comment by szepeviktor** [comment]
Thank you for your report!
Please fix the PHPStan level and share your class with 1 method only.

**Comment by szepeviktor** [comment]
Does it work without `->refresh()`?

**Comment by canvural** [comment]
Hi,

Please create a new issue with more information (model definitions, relations etc.). Because `refresh` works normally in our tests. and many other projects.
