### ISSUE TITLE
Crypt::decrypt and No application encryption key has been specified.

### ISSUE THREAD

**Issue by arxeiss** [nunomaduro/larastan#752]
- Larastan Version: 0.6.11
- `--level` used: 6

### Description

In one controller I have this piece of code:

```php
$folder = Crypt::decrypt($request->input('f'))
```
If I run phpstan on my local machine, it works. But if I run it in Gitlab CI I'm getting error below. This was not happening in previous versions of Larastan. If I remove `.env` file locally, I got the same error on my machine.

I know what is the problem, missing app key, but I don't know why I should need that for static analysis. And in previous versions it wasn't needed. I updated from `0.6.10` to `0.6.11`.

```
 Illuminate\Encryption\MissingAppKeyException 

  No application encryption key has been specified.

  at vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79
     75▕     protected function key(array $config)
     76▕     {
     77▕         return tap($config['key'], function ($key) {
     78▕             if (empty($key)) {
  ➜  79▕                 throw new MissingAppKeyException;
     80▕             }
     81▕         });
     82▕     }
     83▕ }

```
// EDIT: fix partially saved issue and copy full text from #753

**Comment by szepeviktor** [comment]
Do you have `APP_ENV=...` in your `.env` file?

**Comment by szepeviktor** [comment]
Simply add `echo 'APP_ENV=testing' >>.env` to your CI.

**Comment by szepeviktor** [comment]
I've just struggled with the very same problem yesterday.

**Comment by arxeiss** [comment]
OK, That is not hard to add `APP_KEY` before running Larastan in CI. However

1. It wasn't needed before 
2.This is written: Larastan focuses on finding errors in your code **without actually running**.

So why it needs APP_KEY when it is not executing? So maybe it is expected because of something. And you will need that. Or it is some bug in the Larastan/PHPStan which should be reported. That's why I created this issue.

**Comment by szepeviktor** [comment]
> So why it needs APP_KEY when it is not executing?

We boot Laravel.
We are working on replacing all Laravel convenience with static analysis.
