### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Facades\DB::query().

### ISSUE THREAD

**Issue by mrsamse** [nunomaduro/larastan#754]
Laravel version: 8.21.0
phpstan version: 0.12.65
phpstan level: 3

### Description
I have updated larastan from version 0.6.9 to version 0.6.12. Now I get the following error message in the console: 

```
Call to an undefined static method Illuminate\Support\Facades\DB::query().
```

When I downgrade larastan back to version 0.6.9, everything works as usual. With version 0.6.10 everything also works, but with version 0.6.11 the same error occurs as described above. So there must be an error somewhere in the commits between 0.6.10 and 0.6.11.

### Laravel code where the issue was found

```php
$mainQuery = DB::query();
```

**Comment by canvural** [comment]
Hi,

Thanks for the report. Will take a look.

**Comment by szepeviktor** [comment]
Do you have `use Illuminate\Support\Facades\DB;` ?

**Comment by canvural** [comment]
Fixed by: https://github.com/nunomaduro/larastan/commit/8aa4b6dc3407fad6ced8115da02f610aad55366f
