### ISSUE TITLE
Incorrect return type belongsTo

### ISSUE THREAD

**Issue by Ignas2526** [nunomaduro/larastan#758]
- Larastan Version: 0.6.12
- phpstan version: 0.12.66
- `--level` used: 8

### Description

The return type for belongsTo is wrong.
I get following error:
```
Method App\Models\Comment::article() should return Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Article, \App\Models\Comment> but returns Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Article, \App\Models\Comment>.
```

### Laravel code where the issue was found

```php
class Comment extends Model
{
    /**
     * @phpstan-return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\Article, \App\Models\Comment>
    */
    public function article()
    {
        return $this->belongsTo(\App\Models\Article::class, 'article_id');
    }
}
```
### More description

I tired to debug the code and I believe that issue is in the ModelRelationsDynamicMethodReturnTypeExtension class. It looks like it should provide type hints for HasRelationships, but it contains two statements that make the isMethodSupported always return false for them.

Following two conditions look really wrong. If I understand it correctly, the `$variants->getParameters()` would be the belongsTo method parameter count. It will never be zero, meaning that the first statement will always fail. The next statement excludes all of the HasRelationships methods. It should be `!in_array(...)`.
```
        if (count($variants->getParameters()) !== 0) {
            return false;
        }

        if (in_array($methodReflection->getName(), [
            'hasOne', 'hasOneThrough', 'morphOne',
            'belongsTo', 'morphTo',
            'hasMany', 'hasManyThrough', 'morphMany',
            'belongsToMany', 'morphToMany', 'morphedByMany',
        ], true)) {
            return false;
        }
```
After fixing above two functions, `findRelatedModelInRelationMethod` returns null. I've no idea how to fix it.

**Comment by canvural** [comment]
Hi,

That error message looks weird. The expected and the actual ones are the exact same.

Anyway, why do you need the `@phpstan-return`?
```php
public function article(): BelongsTo
{
    return $this->belongsTo(\App\Models\Article::class, 'article_id');
}
```

should work jsut fine.

**Comment by Ignas2526** [comment]
BelongsTo stub specifies two template models. The whole point of `@phpstan-return` and me writing type like that is so that I could get further hints when I call `get` for example.

**Comment by canvural** [comment]
Larastan already recognizes that and returns generic return type. Just try with:
```php
public function article(): BelongsTo
{
    return $this->belongsTo(\App\Models\Article::class, 'article_id');
}
```

**Comment by Oreolek** [comment]
This throws a `missingType.generics` error on level 6 right now, because `BelongsTo` does not specify the types. Trying to specify the types leads back to the problem described above.

**Comment by calebdw** [comment]
@Oreolek, please open a new issue with a complete code example
