### ISSUE TITLE
Call to undefined method PHPStan\Type\MixedType::getClassName()

### ISSUE THREAD

**Issue by stayallive** [nunomaduro/larastan#761]
- Larastan Version: 0.6.12
- `--level` used: 1

### Description

I am getting a similar error since upgrading from phpstan 0.6.11 to 0.6.12, I am running on PHP 8.

```
  Call to undefined method PHPStan\Type\MixedType::getClassName()

  at vendor/nunomaduro/larastan/src/Methods/Pipes/BuilderLocalMacros.php:45
     41▕         if (($classReflection->isSubclassOf(Builder::class) || $classReflection->getName() === Builder::class) && $classReflection->getActiveTemplateTypeMap()->getType('TModelClass') !== null) {
     42▕             /** @var ObjectType $modelType */
     43▕             $modelType = $classReflection->getActiveTemplateTypeMap()->getType('TModelClass');
     44▕ 
  ➜  45▕             $classReflection = $passable->getBroker()->getClass($modelType->getClassName());
     46▕         }
     47▕ 
     48▕         if ($classReflection->isSubclassOf(Model::class) && in_array(SoftDeletes::class,
     49▕                 trait_uses_recursive($classReflection->getName()), true)) {
```

### Laravel code where the issue was found

```php
// $entity being a Eloquent model
$entity->authors()->updateExistingPivot(123, []);
```

And the relation definition from the `$entity` model:

```php
    /** @return \Illuminate\Database\Eloquent\Relations\BelongsToMany|\App\Models\QueryBuilders\UserBuilder|\Illuminate\Database\Query\Builder */
    public function authors()
    {
        return $this->belongsToMany(User::class);
    }
```

The `\App\Models\QueryBuilders\UserBuilder` in the relation comment seems to cause the issue, replacing it with `\Illuminate\Database\Eloquent\Builder` as I would with relations without custom query builders make the error go away.

The query builder class:

```php
/**
 * @template TModelClass
 * @extends \Illuminate\Database\Eloquent\Builder<TModelClass>
 */
class UserBuilder extends Builder
```

I am not sure what is wrong with this code and why it breaks on 0.6.12. But if I need to provide more info let me know!

---

This might be the same issue as #755 but since the error is different I created a new issue to be safe.

**Comment by canvural** [comment]
Hi,

You probably don't need that comment on the `authors` relationship. Just doing
```php
public function authors(): BelongsToMany
{
    return $this->belongsToMany(User::class);
}
```

should work.

**Comment by stayallive** [comment]
Not if I want PhpStorm to have correct autocompletion, that is why we have that comment there.

But regardless, I would not expect a comment crashing phpstan even if it thinks it's redundant?

**Comment by canvural** [comment]
That's right, it shouldn't crash. Will look into that.

But also I noticed that you are using `\App\Models\QueryBuilders\UserBuilder` in the type. That class is generic so you need something like `\App\Models\QueryBuilders\UserBuilder<User::class>` I think this should fix it.

**Comment by canvural** [comment]
Fixed with: https://github.com/nunomaduro/larastan/commit/8bde1898779bd14f28f95241582a6fec4a9b0910

But to really solve the issue, you need to add the type I wrote above.

**Comment by stayallive** [comment]
I appreciate that. 

Just out of curiousity. I'm not to familiar with the code blocks added to the custom QueryResolver but why does it needs to be generic? Can't I set the user model there already so I don't have to add it to the comments every time?

**Comment by canvural** [comment]
For Larastan it's not neccessary. 

```php
public function authors(): BelongsToMany
{
    return $this->belongsToMany(User::class);
}
```

should be enough in your case.

And `Builder` is generic, because type system needs to know which model does the builder operates on. So if you extend from the `Builder` your custom builder should also be generic.
