### ISSUE TITLE
Conflict with deprecated excludes_analyse parameter

### ISSUE THREAD

**Issue by marcospmsantos** [nunomaduro/larastan#762]
- Larastan Version: 0.6.12
- `--level` used: 1

### Description
Error using the "excludePaths" parameter in phpstan.neon
In the file ./vendor/nunomaduro/larastan/extension.neon there is a use of the parameter "excludes_analyse", deprecated, that conflicts with the parameter "excludePaths".
Below is the error that appears on the console.

Configuration parameters "excludes_analyse" and "excludePaths" cannot be used at the same time.

Parameter "excludes_analyse" has been deprecated so use "excludePaths" only from now on.

**Comment by szepeviktor** [comment]
Thank you for opening this issue.
It is resolved in #759
Not yet released.

**Comment by szepeviktor** [comment]
You may try `composer require --dev nunomaduro/larastan:dev-master`
