### ISSUE TITLE
Collection generics break as a result of using dedicated query builder

### ISSUE THREAD

**Issue by AdirYad** [nunomaduro/larastan#763]
- Larastan Version: 0.6.12
- `--level` used: max
 
### Description
 
When using [Dedicated Query Builders](https://timacdonald.me/dedicated-eloquent-model-query-builders/) the collection generics get broken.
 
 
### Laravel code where the issue was found
 
```php
class Post extends Model
{
  public function query(): PostBuilder
  {
    return parent::query();
  }
 
  public function newEloquentBuilder($query)
  {
    return new PostBuilder($query);
  }
}
```
```php
class PostBuilder extends Builder
{
  public function published(): self
  {
    return $this->whereNotNull('published_at');
  }
}
```
 
```php
// This piece of code throws an exception:
// Parameter #1 $callback of method Illuminate\Support\Collection<int,Illuminate\Database\Eloquent\Model>::each() expects callable(Illuminate\Database\Eloquent\Model, int): bool|void, Closure(App\Models\Transaction): mixed given.
Post::query()->published()->each(function (Post $post) {
  $post->doSomething();
});
```
 
```php
// This piece of code works as expected.
Post::each(function (Post $post) {
  $post->doSomething();
});
```

**Comment by szepeviktor** [comment]
In one of the chained methods the specific model (Transation) is lost.
Try removing the method calls one by one and retest.

**Comment by AdirYad** [comment]
@szepeviktor, I've edited the issue, you better read it again.
The issue happens because of the builder.

**Comment by canvural** [comment]
@AdirYad You need docblocks to describe your custom builder correctly. You can read it [here.](https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders)
