### ISSUE TITLE
How to correctly import ide-helper in phpstan.neon

### ISSUE THREAD

**Issue by aaronflorey** [nunomaduro/larastan#764]
- Larastan Version: 0.6.12
- `--level` used: 1

### Description

I keep getting the usual errors about properties not existing on models. I'm wondering how i properly import ide-helper to remove these errors?

- phpstan.neon https://dl.dropboxusercontent.com/s/81432susubrapkr/Screenshot%20at%2010-28-55.png
- Model https://dl.dropboxusercontent.com/s/1fah1jr2rzirx1i/Screenshot%20at%2010-29-25.png
- PHPStan output https://dl.dropboxusercontent.com/s/0e9tc9a7c1qmfez/Screenshot%20at%2010-37-35.png

I've seen issues where people say to use ide-helper, but i'm not sure on the correct way to use it.

Thanks

**Comment by szepeviktor** [comment]
Larastan recognizes your migrations :)
https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md#databasemigrationspath

**Comment by canvural** [comment]
Hi,

As far as I can see, you have the migrations correctly setup. The only issue is the relationships. For that you have to define the return type for your relationship methods. For example:

```php
public function user(): BelongsTo
{
	return $this->belongsTo(User::class);
}
```


You can import the generated ide helper file as a [PHPStan stub](https://phpstan.org/user-guide/stub-files), if you want. But I don't recommend doing that together with Larastan. So you have to choose one.

**Comment by aaronflorey** [comment]
Ah, return types, that's what I'm missing. Thank you @canvural 

Is it possible to add that to the docs somewhere? I never thought of adding return types.

**Comment by canvural** [comment]
No problem :+1: 

Yeah, that is a commonly opened issue. I thought if developers are using static analysis, they are for sure using types everywhere :smile: 

Anyway maybe we can have a new `faq.md` file in [docs](https://github.com/nunomaduro/larastan/tree/master/docs). Then in one of the sections, we can explain that you need to define your relationship methods with a return type in order for Larastan to recognize the relationship property access. Feel free to send a PR that adds that :+1:
