### ISSUE TITLE
Overriding Eloquent\Builder's where method's return type

### ISSUE THREAD

**Issue by genesiscz** [nunomaduro/larastan#765]
- Larastan Version: 0.6.12
- `--level` used: 5

### Description

So I use a custom EloquentBuilder to ease my migration from another framework which allowed `->where("column_id", [1, 2, 3])` to build an IN query block. 

```php
/**
 * Class EloquentBuilder
 *
 * @package App\Builders
 * @template TModelClass of \App\Models\BaseModel
 * @extends Builder<TModelClass>
 * @implements \IteratorAggregate<TModelClass>
 */
class EloquentBuilder extends Builder implements ArrayAccess, IteratorAggregate,Countable
{
	/**
	 * Add a basic where clause to the query.
	 *
	 * @param  Closure|string|array|Expression  $column
	 * @param  mixed  $operator
	 * @param  mixed  $value
	 * @param  string  $boolean
	 * @return $this
	 */
	public function where($column, $operator = null, $value = null, $boolean = 'and')
	{
		if ($operator instanceof Selection || $operator instanceof Collection || is_array($operator)) {
			return parent::whereIn($column, $operator); // 
		}

		if ($operator instanceof BaseModel) {
			return parent::where($column, $operator->getKey());
		}

		if ($operator instanceof EloquentBuilder) {
			return parent::whereIn($column, $operator->pluck("id")->keys());
		}

		return parent::where($column, $operator, $value, $boolean);
	}
}
```

I needed to override the possible return type of overriden `where()` because if I don't, Laravel is screaming on line `return parent::whereIn($column, $operator);`:

```
phpstan: Method App\Builders\EloquentBuilder::where() should return $this(App\Builders\EloquentBuilder) but returns Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>.
```

So when I change the return type hint, 

```
 * @return $this|EloquentBuilder<TModelClass>|\Illuminate\Database\Query\Builder
```

it screams

`phpstan: Return type (App\Builders\EloquentBuilder<TModelClass of App\Models\BaseModel>|Illuminate\Database\Query\Builder) of method App\Builders\EloquentBuilder::where() should be compatible with return type ($this(Illuminate\Database\Eloquent\Builder)) of method Illuminate\Database\Eloquent\Builder<TModelClass of App\Models\BaseModel>::where()`

How do I override the return type correctly?

**Comment by canvural** [comment]
Hi,

Can you share the piece of code that produces the error?

**Comment by genesiscz** [comment]
This line
```
	public function where($column, $operator = null, $value = null, $boolean = 'and')
```

**Comment by canvural** [comment]
Can you try with `@return $this<TModelClass>` or `@return self<TModelClass>`?

**Comment by genesiscz** [comment]
`@return $this<TModelClass>` was probably enough! Thanks!

**Comment by szepeviktor** [comment]
We are very happy to help you :)
