### ISSUE TITLE
Incorrect type hinting in Collection Map method

### ISSUE THREAD

**Issue by caster977** [nunomaduro/larastan#773]
- Larastan Version: 0.6.13
- `--level` used: 6

### Description
Collection map callback function expecting Illuminate\Database\Eloquent\Model instance. Instance which extending this Model Class is not pass

### Laravel code where the issue was found
` Parameter #1 $callback of method Illuminate\Database\Eloquent\Collection<Illuminate\Database\Eloquent\Model>::map() expects callable(Illuminate\Database\Eloquent\Model, int): array(), Closure(App\Models\History): array() given.`

History class extends Illuminate\Database\Eloquent\Model class. So expectation behaviour should not trigger an error.

```php
 $result = $model->history()
            ->select($columns)
            ->orderByDesc('created_at')
            ->get()
            ->map(function (History $item) {
                return [

                ];
            });



use Illuminate\Database\Eloquent\Model;

class History extends Model
{
}
```

**Comment by canvural** [comment]
Hi,

Can you show the definition of the `history` method used in `$model->history()`?

**Comment by caster977** [comment]
> Hi,
> 
> Can you show the definition of the `history` method used in `$model->history()`?

Hello, of course.

```php
<?php

namespace App\Contracts;

use Illuminate\Database\Eloquent\Relations\MorphMany;

interface HistoryContract
{
    /**
     * Model history
     *
     * @return MorphMany
     */
    public function history(): MorphMany;
}
```

**Comment by canvural** [comment]
Larastan scans your model files for relations, and converts return types of relations to generics on the fly. Since the definition of the `history` is not in the model, it does not know `$model->history()` returns `MorphMany<History>`

You can either use `@return MorphMany<History>` or `@phpstan-return MorphMany<History>` in the definition. This should solve it.

**Comment by caster977** [comment]
Solved. Thank you for help.

**Comment by szepeviktor** [comment]
@canvural This has been asked ~5× recently. Could we add it to one of the existing docs?

**Comment by canvural** [comment]
> @canvural This has been asked ~5× recently. Could we add it to one of the existing docs?

Yeah, we definitely should do :+1:
