### ISSUE TITLE
`Family::query()->paginate(10)` result can not be used in a `foreach`

### ISSUE THREAD

**Issue by zarunet** [nunomaduro/larastan#776]
- Larastan Version: 0.6.13
- `--level` used: 3

### Description

Running a foreach on paginators raises this error :
> Argument of an invalid type Illuminate\Contracts\Pagination\LengthAwarePaginator supplied for foreach, only iterables are supported.

This is a false positive as both `Illuminate\Pagination\Paginator` and `Illuminate\Pagination\LengthAwarePaginator` classes implements `IteratorAggregate`, which is iterable.  
However, their respective interfaces `Illuminate\Contracts\Pagination\Paginator` and `Illuminate\Contracts\Pagination\LengthAwarePaginator` do not, which may be where the false positive is coming from.

### Laravel code where the issue was found

```php
// Family is an Eloquent model
$families = Family::query()->paginate(10);
foreach ($families as $family) {
    // loop contents
}
```

**Comment by szepeviktor** [comment]
https://github.com/laravel/framework/blob/c26c78cf3bcbaf39e63dcb4a410905c62cb1d282/src/Illuminate/Contracts/Pagination/LengthAwarePaginator.php#L3-L5

It should be caught by https://github.com/nunomaduro/larastan/blob/03a7c131a5f784561e4e1f0bca6e232e00fa4531/src/Methods/Pipes/Contracts.php#L47

**Comment by szepeviktor** [comment]
Could you try using `->each()` or similar in place of the for loop?

**Comment by zarunet** [comment]
Replacing the `foreach` by a `->each()` seems to satisfy PHPStan as no error is reported.

Interestingly enough, PhpStorm is complaining instead that `each()` doesn't exist, but the code does run.

**Comment by szepeviktor** [comment]
Laravel seem OOP to me, so actually `foreach` could be banned :)

**Comment by zarunet** [comment]
Honestly, either rewriting those `foreach` to `->each()` calls or plonking a new ignore in the config file is OK to me :)

Feel free to close this if you think it shouldn't be adressed.

**Comment by szepeviktor** [comment]
Let's wait a bit for @canvural

**Comment by canvural** [comment]
You can send a PR to Laravel that changes the return type of `paginate` method on `Builder` to `\Illuminate\Pagination\LengthAwarePaginator` This seems more correct since the `paginator` in `BuildsQueries` already has return typehint of `\Illuminate\Pagination\LengthAwarePaginator`

**Comment by szepeviktor** [comment]
> You can send a PR to Laravel

I do weird things in CI modifying Laravel's and Larastan's source code with `sed`.

**Comment by zarunet** [comment]
Alternatively, would adding an override to `paginate()` and `simplePaginate()` in [`stubs/EloquentBuilder.stub`](https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub) be acceptable? If so, i can open a PR for that.

**Comment by szepeviktor** [comment]
@zarunet First try sending a PR to Laravel, if rejected then send one here.
