### ISSUE TITLE
TAble ID could be a non-integer UUID

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#779]
- Larastan Version: 0.6.13
- `--level` used: 4

### Description

`Cannot cast Ramsey\Uuid\UuidInterface to int.`

### Laravel code where the issue was found

https://github.com/conedevelopment/bazar/blob/2fa9b9c820294e328ee879dbb9c3a5f04e3eb253/src/Models/Item.php#L95-L99

The migration:
https://github.com/conedevelopment/bazar/blob/2fa9b9c820294e328ee879dbb9c3a5f04e3eb253/database/migrations/2020_01_01_000300_create_bazar_items_table.php#L14-L17

**Comment by canvural** [comment]
Hi,

On top of the model file you can add `/** @property Uuid $id */` to overwrite it.

**Comment by szepeviktor** [comment]
I know - I know :)

How could one solve it in Larastan?

**Comment by szepeviktor** [comment]
Somehow resolved in v0.7.0
