### ISSUE TITLE
OutOfBoundsException thrown

### ISSUE THREAD

**Issue by onally01** [nunomaduro/larastan#782]
- Larastan Version: 0.7.0
- `--level` used: 5

### Description
Note: Using configuration file /phpstan.neon.
OutOfBoundsException thrown in phar://vendor/phpstan/phpstan/phpstan.phar/vendor/composer/InstalledVersions.php on line 1081 while loading bootstrap file /vendor/nunomaduro/larastan/bootstrap.php: Package "sentry/sentry" is not installed

### Laravel code where the issue was found

```php
```

**Comment by canvural** [comment]
Hi,

Please upgrade Composer to 2.0.9. I believe this will fix your error.
