### ISSUE TITLE
Parameter #1 $values of method Illuminate\Database\Eloquent\Builder<App\Models\Model>::update() expects array<string, mixed>, array<int|string, string|null> given.

### ISSUE THREAD

**Issue by ttomdewit** [nunomaduro/larastan#787]
- Larastan Version: 0.7.0
- `--level` used: 5
- PHPStan Version: 0.12.75
- Laravel Framework 7.30.4

### Description

When on level 7, the `update()` method on `Illuminate\Database\Eloquent\Builder<App\Models\Model>::update()` fails on array contents.

### Laravel code where the issue was found

~It's a customized version of the `runSoftDelete()`-method I'm not at liberty to fully share at this point.~

Update: please (re)view https://github.com/nunomaduro/larastan/issues/787#issuecomment-783440795.

### Full error:

```json
{
    "description": "Parameter #1 $values of method Illuminate\\Database\\Eloquent\\Builder<App\\Models\\Model>::update() expects array<string, mixed>, array<int|string, string|null> given.",
    "fingerprint": "fa3f062d5b609e361979fc64a94f6e669c829de4f16a865aa8b66d167ec3d372",
    "location": {
        "path": "app/Traits/SoftDeletesTrait.php (in context of class App\\Models\\Model)",
        "lines": {
            "begin": 47
        }
    }
}
```
### Potential fix

Since I'm working on PR #785 I figured I'd take a stab at overruling the stub in the codebase:

**Original**:

```php
/**
 * @param  array<model-property<TModelClass>, mixed>  $values
 * @return int
 */
public function update(array $values);
```

**My changes**:

```php
/**
 * @param  array<int|model-property<TModelClass>, string|null>  $values
 * @return int
 */
public function update(array $values);
```

**Comment by canvural** [comment]
Hi,

How does `update` method work with integer keyed arrays? `User::first()->update(['email'])` for example would give error like `No such column 0`

**Comment by ttomdewit** [comment]
> Hi,
> 
> How does `update` method work with integer keyed arrays? `User::first()->update(['email'])` for example would give error like `No such column 0`

I'll try and access and share as much as I'm allowed to in a bit.

**Comment by ttomdewit** [comment]
The code we've added in the past:

```php
if (
    property_exists($this, 'uniqueOnSoftDelete')
    && is_array($this->uniqueOnSoftDelete)
) {
    foreach ($this->uniqueOnSoftDelete as $key) {
        $columns[$key] = $this->getAttribute($key) . '-' . $this->getKey();
    }
}
```

We have a `uniqueOnSoftDelete` array property on our User class. It can contain a list of column names that will be altered during soft deleting said model entry.

When I have `email` listed as a column, the following output comes from `var_dump`:

```
array(3) {
  ["deleted_at"]=>
  string(19) "2021-02-22 15:05:42"
  ["updated_at"]=>
  string(19) "2021-02-22 15:05:42"
  ["email"]=>
  string(20) "ldicki@example.com-3"
}
```

This array will be forwarded to `$query->update($columns);`.

**Comment by canvural** [comment]
So `$columns` is always an associative array. No need to change the signature of `update` Probably you need to typehint `uniqueOnSoftDelete` as `array<string, mixed>` or something.

**Comment by ttomdewit** [comment]
> So `$columns` is always an associative array. No need to change the signature of `update` Probably you need to typehint `uniqueOnSoftDelete` as `array<string, mixed>` or something.

Appreciate the feedback, I'll give this a whirl and close this issue when it works!

**Comment by canvural** [comment]
Or just before the `foreach` you can say `@var string $key` to let PHPStan know `$key` is always a string

**Comment by ttomdewit** [comment]
> Or just before the `foreach` you can say `@var string $key` to let PHPStan know `$key` is always a string

I'm happy to report this works. Easy fix.
