### ISSUE TITLE
Missing intentional typo

### ISSUE THREAD

**Issue by netpok** [nunomaduro/larastan#788]
- Larastan Version: current master

### Description
I was just looking around and there is an "intentional typo" comment in [this test file](https://github.com/nunomaduro/larastan/blob/master/tests/Features/Methods/HigherOrderCollectionProxyMethods.php#L190) but I can't seem to find the mentioned typo.

If I missed it I'm sorry.

**Comment by szepeviktor** [comment]
@canvural It is really identical to the method above thus no typo.
Could you add that typo?
