### ISSUE TITLE
TrustProxies::$headers does not accept default value of type int.

### ISSUE THREAD

**Issue by brendt** [nunomaduro/larastan#79]
This happens in 0.2.0

```
Property App\Http\Middleware\TrustProxies::$headers (string) does not accept default value of type int.
```

**Comment by brendt** [comment]
I haven't changed the file, no. And it seems to be back in this 0.2.0. Maybe should have re-opened to old issue?

**Comment by bhulsman** [comment]
Also getting this one with the 0.2.0 release.

**Comment by nunomaduro** [comment]
@brendt @bhulsman That was already fixed on the framework itself: https://github.com/laravel/laravel/commit/2683de70828e6c4dcf8613a60fc7304ff90e6acc.

I think I gonna just ignore this error *for now* on the larastan configuration itself.

Thanks @brendt for reporting! ☺️

**Comment by szepeviktor** [comment]
> @brendt @bhulsman That was already fixed on the framework itself: laravel/laravel@2683de7.

That is my commit :)

**Comment by nunomaduro** [comment]
@brendt @bhulsman Thanks for reporting this issue.

Is now fixed on the version v0.2.3. Do you mind of performing a quick test?

**Comment by brendt** [comment]
Thanks, it works!

**Comment by bhulsman** [comment]
Works indeed, thanks! ^^
