### ISSUE TITLE
Method should return Model A but returns Model B - error if query uses "withTrashed"

### ISSUE THREAD

**Issue by bearpeta** [nunomaduro/larastan#792]
- Larastan Version: 0.6.13
- `--level` used: 6

### Description
If we use the static method "withTrashed" of the SoftDeletes trait in a Eloquent query, Phpstan throws an error because according to Phpstan the returning model class doesn't match the return type.

> Method App\Users\Customers\Repositories\EloquentCustomerRepository::findByRecommendationCode() 
should return `App\Users\Customers\Customer`
but returns `App\Portfolio\Portfolio`

Both model classes are using the SoftDeletes trait.
If we use "::query()" instead, the error doesn't get thrown.

### Laravel code where the issue was found

```php
    use SoftDeletes;

    public function findByRecommendationCode(string $code): Customer
    {
        return Customer::withTrashed()->where('recommendation_code', $code)->firstOrFail();
    }
```

**Comment by szepeviktor** [comment]
Thank you.
Could you tell us your Larastan version and level?

**Comment by bearpeta** [comment]
Sorry forgot that. I updated my initial comment.

**Comment by canvural** [comment]
Hi,

Can you share the whole file where the error comes from? I don't know why would it think the return type is `Portfolio`

**Comment by nunomaduro** [comment]
Can't reproduce this issue with the code you've provided.
