### ISSUE TITLE
using Collection::macro means the context is not set correctly

### ISSUE THREAD

**Issue by mintbridge** [nunomaduro/larastan#794]
- Larastan Version: 0.6.13
- `--level` used: max

### Description
Using the Collection::macro method to extend the collection means that larastan doesn't pick up that the context of `$this` is Collection not the (in this case) surrounding AnyServiceProvider

```
 ------ --------------------------------------------------------------------------
  Line   Site/SiteServiceProvider.php
 ------ --------------------------------------------------------------------------
  64     Call to an undefined method App\AnyServiceProvider::mapWithKeys().
 ------ --------------------------------------------------------------------------
 ```
 
### Laravel code where the issue was found

```php
class AnyServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Collection::macro('flattenWithKeys', function ($prefix = '') {
            return $this->mapWithKeys(function ($value, $key) use ($prefix) {
                $new_key = $prefix . (empty($prefix) ? '' : '.') . $key;

                if (is_array($value)) {
                    return (new Collection($value))
                        ->flattenWithKeys($new_key)
                        ->toArray();
                }

                return [$new_key => $value];
            });
        });
    }
}
```

**Comment by canvural** [comment]
Hi,

Can you try to typehinting `$this` with something like `/** @var Collection $this */`?

**Comment by mintbridge** [comment]
yeah that works

**Comment by canvural** [comment]
Currently, this is the only way. And in PHPStan there is no way to tell this programmatically, as far as I know.

**Comment by mintbridge** [comment]
ok, thanks for the quick reply

**Comment by szepeviktor** [comment]
Hello @ondrejmirtes! I also struggle with macros mentioned above. Is there really no way to set the type of Closure's `$this`?

**Comment by ondrejmirtes** [comment]
@szepeviktor No, it's not.

**Comment by szepeviktor** [comment]
@ondrejmirtes Thank you. Maybe in the future we will be able to resolve this issue.
