### ISSUE TITLE
PHPStan 0.12.82 compatibility

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#796]
In [PHPStan v0.12.82](https://github.com/phpstan/phpstan/releases/tag/0.12.82) release there were changes related to how `static` keyword is resolved. This caused some issues in Larastan. Need to investigate and fix.

**Comment by szepeviktor** [comment]
Was it this PR? https://github.com/phpstan/phpstan-src/pull/474

**Comment by canvural** [comment]
> Was it this PR? [phpstan/phpstan-src#474](https://github.com/phpstan/phpstan-src/pull/474)

Probably.

**Comment by shaffe-fr** [comment]
Most of the errors in my project can be summed up to the following snippet:
```php
$this->userOrNull = $office->user()->active()->first();
```

* Model scopes Builder parameter is not ignored
`Method Illuminate\Database\Query\Builder::active()  invoked with 0 parameters, at least 1 required.`
* Model type is lost on relations Builder: `Property \MyClass::$userOrNull (App\User|null) does not accept Illuminate\Database\Eloquent\Model|null.`

Hope it helps.

**Comment by canvural** [comment]
@shaffe-fr Thank you for the information!

I also changed the `master` branch so we can see which tests are failing. [Here](https://github.com/nunomaduro/larastan/runs/2201088920?check_suite_focus=true) is the failing tests from the actions.

**Comment by canvural** [comment]
I spent a little bit of time on this. But couldn't come up with a good solution. So if anyone else is interested, we can collaborate on a solution!

**Comment by szepeviktor** [comment]
Should I dare to mention Ondřej Mirtes? What if he will points out bad design in Larastan??

**Comment by szepeviktor** [comment]
First one being

```
Method Tests\\Features\\Methods\\ModelExtension::testLockForUpdate() should return
Illuminate\\Database\\Eloquent\\Builder<App\\User> but returns
Illuminate\\Database\\Eloquent\\Builder<Illuminate\\Database\\Eloquent\\Model>.
```

in

https://github.com/nunomaduro/larastan/blob/f74befd87b7278285cbf6f1597509cbfaca46bf8/tests/Features/Methods/ModelExtension.php#L284-L288

**Comment by ondrejmirtes** [comment]
Don't hesitate to reach out to me as I'm probably the only person that can help you here :) it would be great if you could isolate what Larastan extensions started behaving differently between PHPStan 0.12.81 and 0.12.82 then we can move on to a solution.

**Comment by ondrejmirtes** [comment]
One side-effect of 0.12.82 changes is that generics + MethodsClassReflectionExtension/PropertiesClassReflectionExtension behave a bit differently. If you introduce new methods based on a template type variable (like `@template T`), the extension isn't going to work unless you introduce the `object` (or more specific) bound - `@template T of object`.

But of course the problem can be something completely different. For example if you have some custom types that override `getProperty` or `getMethod`, it now looks differently: https://github.com/phpstan/phpstan-src/blob/ed1736c045a29da4673ccbbbce7e9305841b00f9/src/Type/ObjectType.php#L512-L551

**Comment by canvural** [comment]
I didn't have much time to really dive into it. But from a short look previously, the problem appears to be like this:

- In `Builder` we have template like [this](https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L6)
- Then in [`EloquentBuilderForwardsCallsExtension`](https://github.com/nunomaduro/larastan/blob/master/src/Methods/EloquentBuilderForwardsCallsExtension.php) when we [get](https://github.com/nunomaduro/larastan/blob/master/src/Methods/EloquentBuilderForwardsCallsExtension.php#L94) the `TModelClass` from the active template type map sometimes it's a child model (`\App\User` for example) and sometimes it's the `\Illuminate\Database\Eloquent\Model` (the template bound)

And when it's the latter, we ge the errors like `should return
Illuminate\\Database\\Eloquent\\Builder<App\\User> but returns
Illuminate\\Database\\Eloquent\\Builder<Illuminate\\Database\\Eloquent\\Model>.`

So maybe the solution can be as simple as checking if `TModelClass` is not `Illuminate\Database\Eloquent\Model` after [this line](https://github.com/nunomaduro/larastan/blob/master/src/Methods/EloquentBuilderForwardsCallsExtension.php#L94)? Didn't try this yet, so don't know if it can cause other issues.

**Comment by szepeviktor** [comment]
> So maybe the solution can be as simple as checking if `TModelClass` is not `Illuminate\Database\Eloquent\Model` after [this line](https://github.com/nunomaduro/larastan/blob/master/src/Methods/EloquentBuilderForwardsCallsExtension.php?rgh-link-date=2021-03-30T16%3A47%3A40Z#L94)

Go for it!

**Comment by ondrejmirtes** [comment]
> So maybe the solution can be as simple as checking if TModelClass is not Illuminate\Database\Eloquent\Model after this line? 

Yeah, try to return `null` in that case.
