### ISSUE TITLE
When & Unless Validations

### ISSUE THREAD

**Issue by bogdankharchenko** [nunomaduro/larastan#799]
- Larastan Version: 0.7.1
- `--level` used: 5

### Description

```
Parameter #2 $callback of method Illuminate\Database\Eloquent\Builder<App\Resource>::when() expects
(callable(Illuminate\Database\Eloquent\Builder<App\Resource>, mixed): null)|Illuminate\Database\Eloquent\Builder<App\Resource>,
Closure(Illuminate\Database\Eloquent\Builder): void given.
```

### Laravel code where the issue was found

```php
Resource::query()
    ->when($request->filled('stuff'), function ($query) use ($request) {
        $query->where('stuff', $request->input('stuff'));
    });
```

I believe instead of `null` return we should also return `void`
https://github.com/nunomaduro/larastan/commit/3b32c74a63ce36f85d5b0434725a59e0dcd74292#diff-cda4a8378b7ebd0f5aa8a5a9ae53a08e48d436e67928064bf28963f969dd93e0R192

**Comment by szepeviktor** [comment]
Thank you.
What is your Larastan (this project) version?

**Comment by bogdankharchenko** [comment]
Latest version

**Comment by psprokofiev** [comment]
So what about this bug?

**Comment by szepeviktor** [comment]
We welcome contributors.
