### ISSUE TITLE
Memory leak in 0.7.2

### ISSUE THREAD

**Issue by bytestream** [nunomaduro/larastan#805]
- Larastan Version: 0.7.2
- `--level` used: 8

### Description

Following release of `0.7.2` there are now severe memory leaks. `0.7.1` did not have these issues so it can be assumed that these issues relate to https://github.com/nunomaduro/larastan/pull/801

```
Reached internal errors count limit of 50, exiting...                      
     Internal error: Child process timed out after 300.0 seconds. Try making it longer with parallel.processTimeout setting.                            
     Child process error (exit code 255):                                       
     In NodeScopeResolver.php line 574:                                         
                                                                                
       Out of memory (allocated 9297731584) (tried to allocate 8589934600 bytes)                                                                     
                                                                                
     mmap() failed: [12] Cannot allocate memory                                 
                                                                                
     mmap() failed: [12] Cannot allocate memory                                 
     Fatal error: Out of memory (allocated 9297731584) (tried to allocate 8589934600 bytes) in                                                       
     phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php on line 574  
```

### Laravel code where the issue was found

Needs more work to establish the issue in 2300+ files...

**Comment by szepeviktor** [comment]
> Larastan Version: 6.20.22

Is this your *Laravel* version?

**Comment by bytestream** [comment]
My bad... yes. Updated

**Comment by szepeviktor** [comment]
Thank you.

**Comment by canvural** [comment]
Hi,

I don't think this is necessarily related to Larastan itself. With 0.7.2 we also require PHPStan 0.12.83, which had some [memory issues](https://github.com/phpstan/phpstan/issues/4815). But seems like it's fixed in `master` branch. 

You can test it with doing `composer require --dev phpstan/phpstan:dev-master --prefer-dist`

**Comment by bytestream** [comment]
Thanks for looking into this @canvural. The code mentioned in the linked issue is pretty much identical to what I narrowed this down to. I've retested with `dev-master` and the issue is resolved.

I'll close and wait for PHPStan 0.12.84
