### ISSUE TITLE
Specifying property as a result from a raw select

### ISSUE THREAD

**Issue by ju5t** [nunomaduro/larastan#810]
- Larastan Version: 0.7.3
- `--level` used: 5

### Description

I'm using raw queries to get some statistics from a model. This returns:

```  
  39     Access to an undefined property App\Models\Quote::$month.  
  41     Access to an undefined property App\Models\Quote::$count.
```

Both are true. As both `$month` and `$count` are raw selects and will not exist in any other scope apart from this select. I think using `DB::table` can probably circumvent this, as there will be no reference to Quote. I am still in doubt if this would be the right choice, as we lose all of the cool stuff Eloquent has (and we use in other statistics queries that also have raw selects).

What would be a good solution to this problem?

Ps. thanks for making larastan. It has been very, very useful to us!

### Laravel code where the issue was found

```php
$quotes = Quote::select([
    DB::raw('MONTH(created_at) as month'),
    DB::raw('COUNT(id) as count')
])
    ->groupByRaw('month')
    ->where('created_at', '>=', Carbon::now()->subDays(365))
    ->get();

$quotes->map(function ($month) {
    $monthName = DateTime::createFromFormat('!m', $month->month)->format('F'); // Line 39
    $this->quotePerMonthLabels[] = $monthName;
    $this->quotePerMonthValues[] = $month->count; // Line 41
});
```

**Comment by szepeviktor** [comment]
PHPStan is not able add arbitrary properties to an object.
Please use a baseline file, `ignoreErrors` or `/** @phpstan-ignore-next-line */`
https://phpstan.org/user-guide/ignoring-errors

**Comment by szepeviktor** [comment]
I struggle with it too!

**Comment by canvural** [comment]
Hi,

Like @szepeviktor said, there is really no good way to tell PHPStan about those properties. Feel free to ignore the error. Or you can add them to `Quote` class docblocks like so:

```php
/**
 * @property-read int $month
 * @property-read int $count
 */
class Quote
{
    //
}
```

**Comment by szepeviktor** [comment]
Don't do as @canvural say! :)
All Quote instance throughout your codebase will seemingly have those properties.

**Comment by ju5t** [comment]
@szepeviktor yea I didn't want to add them to add them globally. I'm fairly new to PHPStan so I'm trying to do things the right way, but in this case I will ignore them :)

Thanks for the lightning fast responses!

**Comment by timacdonald** [comment]
Although I understand the concern of the docblock approach, I feel that the docblock solution proposed here is actually valid - it would just need to make the values `nullable`.

```php
/**
 * These properties are dynamically added to the model via `SELECT x AS y`.
 * 
 * @property-read ?int $month
 * @property-read ?int $count
 */
class Quote extends Model
{
    //
}
```

This has the benefit of actually typing these potentially available attributes - but indicates that they in fact be `null` and thus need to have runtime type checks performed if you expect them to actually contain an `int`.

We've done this with success in our projects without issue.

**Comment by ju5t** [comment]
@timacdonald that's cool. I always forget that there's more then just `@property` out there :)

We decided to move this query into a method, ignore it there, and have it return a DTO.

**Comment by timacdonald** [comment]
That sounds like a sensible way to keep type issue isolated!
