### ISSUE TITLE
Custom Session Manager breaks larastan

### ISSUE THREAD

**Issue by mfn** [nunomaduro/larastan#813]
- Larastan Version: 0.7.4
- `--level` used: 6
- Pull request with failing test: n/a

### Description
I'm using a custom session manager for compatibility with other legacy apps.

Larastan breaks in this code:
```php
…
app('session');
…
```
with this error:
```
   Error

  Call to a member function driver() on null

  at vendor/nunomaduro/larastan/src/Methods/Pipes/Managers.php:40
     36▕                 $classReflection->getName()
     37▕             );
     38▕
     39▕             try {
  ➜  40▕                 $driver = $concrete->driver();
     41▕             } catch (InvalidArgumentException $exception) {
     42▕                 // ..
     43▕             }
     44▕
```
Upon inspecting this part, I can see that in `var_dump($classReflection->getName());` yields my custom session manager `App\Service\SessionManager` which extends the one from Laravel and overrides the `buildSession` method.

When it tries to get the concrete instance, it receives back only `null`:
```php
            $concrete = $this->resolve(
                $classReflection->getName()
            );
```

**Comment by mfn** [comment]
Ok, found it, seems to be a non-issue and entirely my problem: I've overriden `\Illuminate\Foundation\Application::make` due to some custom requirements and it does not allow instanciating _my_ SessionManager directly (which is usually a non-requirement for our app code).

Larastan tries to look inside the box and triggers this. I found two ways to avoid this problem:
- exclude the rigorous checks in my `::make`
- give an explicit type hint in phpoc, solving this issue too
  ```php
  /** @var \Illuminate\Session\Store $session */
  $session = app('session');
  ```

I'm going with the latter for now.

(mildly related: larastan seems to thing `app('session')` return the Manager. Which it probably does, but in fact the `Store` methods are called here)

**Comment by szepeviktor** [comment]
You can look around with PHPStan's eye: `\PHPStan\dumpType($something)`
