### ISSUE TITLE
Trait function alias is not recognized

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#817]
- Larastan Version: 0.7.2
- `--level` used: 5

### Laravel code where the issue was found

```php
class ...
{
    use HasFactory, HasMedia, Filterable {
        filters as defaultFilters;
    }
```

then `static::defaultFilters()` calls are unknown.

```
 ------ --------------------------------------------- 
  Line   app/Models/Sheet.php                         
 ------ --------------------------------------------- 
  81     Call to an undefined static method           
         static(App\Models\Sheet)::defaultFilters().  
 ------ --------------------------------------------- 
```

If you write three `use ...;` lines it works!

**Comment by canvural** [comment]
Hi,

This most probably related to PHPStan itself. Static reflection for trait aliases might not be supported. Can you open an issue there?

**Comment by szepeviktor** [comment]
> Static reflection for trait aliases might not be supported.

@canvural Could it be that they are supported when writing them one per line?

> If you write three use ...; lines it works!

**Comment by szepeviktor** [comment]
> Can you open an issue there?

Done.
https://github.com/phpstan/phpstan/issues/4886

**Comment by canvural** [comment]
I'm gonna close this as this appears to be indeed a bug in PHPStan.
