### ISSUE TITLE
Internal error: No application encryption key has been specified.

### ISSUE THREAD

**Issue by Ferikl** [nunomaduro/larastan#819]
- Larastan Version: 0.6.13
- `--level` used: 5
- Pull request with failing test:

### Description
Hi guys, find strange behavior in my CI.
Of cause pipeline is under testing env. So I dont have `.env` file but I have `.env.testing`

I suppose I should somehow specify config file in `phpstan.neon` Not sure how I can solve this issue.

### Laravel code where the issue was found

```php
./vendor/bin/phpstan analyse --debug
Note: Using configuration file /builds/xxx/xxx/phpstan.neon.
/builds/xxx/xxx/app/Console/Kernel.php
/builds/xxx/xxx/app/GraphQL/Builders/AbstractFilterableBuilder.php
/builds/xxx/xxx/app/GraphQL/Builders/OneBuilder.php
/builds/xxx/xxx/app/GraphQL/Builders/TwoBuilder.php
/builds/xxx/xxx/app/GraphQL/Builders/ThreeBuilder.php
/builds/xxx/xxx/app/GraphQL/Mutations/FourMutation.php
/builds/xxx/xxx/app/GraphQL/Mutations/OneMutation.php
/builds/xxx/xxx/app/GraphQL/Mutations/TwoMutation.php
/builds/xxx/xxx/app/GraphQL/Queries/OneQuery.php
/builds/xxx/xxx/app/GraphQL/Queries/SecondQuery.php
/builds/xxx/xxx/app/GraphQL/Resolvers/OneResolver.php
/builds/xxx/xxx/app/GraphQL/Resolvers/TwoResolver.php
   Illuminate\Encryption\MissingAppKeyException 
  No application encryption key has been specified.
  at vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79
     75▕     protected function key(array $config)
     76▕     {
     77▕         return tap($config['key'], function ($key) {
     78▕             if (empty($key)) {
  ➜  79▕                 throw new MissingAppKeyException;
     80▕             }
     81▕         });
     82▕     }
     83▕ }
  • Your app key is missing:  
    https://laravel.com/docs/master/installation#configuration

```

**Comment by canvural** [comment]
Hi,

Larastan boots the application to do a better analysis of your app. So you need to define `APP_KEY` in your `.env.testing`

**Comment by Ferikl** [comment]
> Hi,
> 
> Larastan boots the application to do a better analysis of your app. So you need to define `APP_KEY` in your `.env.testing`

Sure I have this `APP_KEY` variable in my `.env.testing`, but since I just run `./vendor/bin/phpstan analyse --debug`
phpstan boot Laravel app and I want to set in what mode(env) it should be booted. Cause now I have `.env.testing` but phpstan runs app in normal mode ( and laravel is looking for `.env` file as main config)

**Comment by BertvanHoekelen** [comment]
I think you can run `APP_ENV=testing ./vendor/bin/phpstan analyse --debug`.

**Comment by Ferikl** [comment]
> I think you can run `APP_ENV=testing ./vendor/bin/phpstan analyse --debug`.

will check, thanks for idea!
