### ISSUE TITLE
`Illuminate\Support\Collection::pluck` should return `Illuminate\Support\Collection<array-key, mixed>` if second parameter is passed

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#823]
- Larastan Version: 0.7.4
- `--level` used: 6

### Description

Currently  return type of `$collection->pluck('value', 'key')` inferred as `Collection<int, mixed>` but that's not true. When the second argument is given to `pluck` it'll create the collection with keys as that argument's value. So the more correct type would be `Collection<array-key, mixed>` I guess.

**Comment by miszczu** [comment]
I have noticed the same issue in version 0.7.15 and level 8
