### ISSUE TITLE
Call to method Model::increment() on a separate line has no effect

### ISSUE THREAD

**Issue by genesiscz** [nunomaduro/larastan#825]
- Larastan Version: dev-master#66b4ca1ed512de0bb4195573a04968ef3a941b7b
- `--level` used: 5

### Description

I am getting many `Call to method App\Models\Driver::increment() on a separate line has no effect.` errors 

### Laravel code where the issue was found

basically both
```php
		$ticket->driver?->increment("ticket_races_left", $count);
```

and 
```php
if ($ticket->driver) {
	$ticket->driver?->increment("ticket_races_left", $count);
}
```

**Comment by szepeviktor** [comment]
You must have some PHP 8 thingy :)

**Comment by canvural** [comment]
Hi,

It's possible we have to tell PHPStan that increment/decrement has side effects. I'll take a look :+1: Thanks.

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/commit/5f18e5068910fb61ac5df2e57512fde8f2bedbdc
