### ISSUE TITLE
Question: Is it possible to detect unused/dead code?

### ISSUE THREAD

**Issue by Nizari** [nunomaduro/larastan#826]
Dear Larastan,

First of thank you for this amazing tool (besides phpstan). This makes for me debugging a very fun game like Bruce Lee that fights a thougher boss the higher he goes into the tower (I refer to the `level`).

I was wondering: Is it possible to use this at least give an educated guess regarding if a method (private/protected/public) is used?

I have a way I would want to do it, I'm only stuck at the following: When I know a method is used and I see it linked to a specific variable. How can I determine the class of that variable?

The workflow would be:
- Use reflection class to loop over all methods from a class (e.g. `User` class - method `getName()`)
- Use `grep` to quickly find all references of the method.
- Generate the AST for all target classes
- Get all variables that use `getName()`
- Determine is that variable is an instance of `User` *
- If found someplace, then method is used, skip
- If no results, report and 'suggest' to developer to manually also verify it's probably not used

* It would be gratefull if you could point me in the right direction for how to do this.

**Comment by szepeviktor** [comment]
> When I know a method is used and I see it linked to a specific variable. How can I determine the class of that variable?

Try `\PHPStan\dumpType($variable);`

And see https://phpstan.org/blog/detecting-unused-private-properties-methods-constants
I think this is all I have.

**Comment by canvural** [comment]
Hi,

This doesn't sound like it's related to Larastan itself. Larastan is just an extension for PHPStan. It's better to ask there.

**Comment by szepeviktor** [comment]
@canvural Please don't say _just_ :)
