### ISSUE TITLE
Getting stuck at 75%

### ISSUE THREAD

**Issue by 4nik3t** [nunomaduro/larastan#827]
While running the analyse command it is getting stuck at 75 %

![image](https://user-images.githubusercontent.com/48653948/116804228-d088a100-ab3a-11eb-810b-58d7c38ed766.png)

PHP Version : 8.0.3
Laravel Version: 8.40.0
OS: Windows

**Comment by szepeviktor** [comment]
Thank you for your report.
Try the `--debug` option and remove the "stuck" file to prove it causes a problem.
