### ISSUE TITLE
Cannot access xxx on App\Models\User|null

### ISSUE THREAD

**Issue by Androlax2** [nunomaduro/larastan#828]
- Larastan Version: 0.7.4
- `--level` used: 8
- Pull request with failing test:

### Description

I have a problem, larastan gives me an error about the user model. For example, when I do Auth::user()-> it will give me an error like this:

```php
Cannot access property $id on App\Models\User|null. 
```

or of this type 

```php
Cannot call method trainings() on App\Models|null.
```

I know it comes from the fact that Auth::user() can return null.
However, this code is in the auth middleware, so there is no chance that the user is not defined, is there any way to work around this? By adding a doc block that specifies which middleware I use in which controller?

If you have any ideas, I'm interested. I searched on the internet, but I didn't find any answer

### Laravel code where the issue was found

```php
    /**
	 * Determine if the user is authorized to make this request.
	 *
	 * @return bool
	 */
	public function authorize(): bool
	{
		return (bool) Auth::user()->trainings()->find($this->training_id);
	}
```

```php
$training->trainer_id = Auth::user()->id;
```

**Comment by szepeviktor** [comment]
Nice to see someone riding on Level 8!

**Comment by canvural** [comment]
Hi,

From the type point of view, this is normal. And expected in level 8.

You can do something like
```php
/** @var User */
$user = Auth::user();
$user->...
```

or feel free to ignore the error.

**Comment by diadal** [comment]
> Hi,
> 
> From the type point of view, this is normal. And expected in level 8.
> 
> You can do something like
> 
> ```
> /** @var User */
> $user = Auth::user();
> $user->...
> ```
> 
> or feel free to ignore the error.

$user = Auth::user();
# $user->...

$id = $user['id'];

**Comment by JohnnyWalkerDigital** [comment]
> Hi,
> 
> From the type point of view, this is normal. And expected in level 8.
> 
> You can do something like
> 
> ```
> /** @var User */
> $user = Auth::user();
> $user->...
> ```
> 
> or feel free to ignore the error.

Can you explain a little as to what's going on here? Thanks.

**Comment by canvural** [comment]
@JohnnyWalkerDigital The type system cannot know if `$request->user()` returns a `User` object or not. In runtime you can be sure it returns `User` because you might have a middleware that makes sure only authenticated users are allowed for this route for example. But type system cannot know that because it doesn't run the code, or which middlewares are applied at this point. Is that clear?

> How would it work with something like:

Again you can do:
```php
/** @var App\Models\User $user */
$user = $request->user();

$user->email;
```

**Comment by pintend** [comment]
Another option is to add global ignore errors in your phpstan.neon file

```yaml
parameters:
    ignoreErrors:
        - '#Cannot access property \$[a-zA-Z0-9\\_]+ on App\\Models\\User\|null#'
        - '#Cannot call method [a-zA-Z0-9\\_]+\(\) on App\\Models\\User\|null#'
```

But be aware this won't catch errors if you have code using the user object without authentication.

I still prefer this method as I don't want random "type comments" or `user()?->` everywhere
