### ISSUE TITLE
Any way to register service providers?

### ISSUE THREAD

**Issue by nasyrov** [nunomaduro/larastan#831]
Hi there,

I'm working on a custom Laravel package, which uses quite a few other packages as dependencies. For instance, Livewire. When I try to run phpstan against my codebase it complains that classes haven't been registered in the container:

```
Note: Using configuration file /home/runner/work/laravel-custom/laravel-custom/phpstan.neon.dist.
Illuminate\Contracts\Container\BindingResolutionException thrown in /home/runner/work/laravel-custom/laravel-custom/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 838 while loading bootstrap file /home/runner/work/laravel-custom/laravel-custom/vendor/nunomaduro/larastan/bootstrap.php: Target class [livewire] does not exist.
```

Is there any way we can register additional service providers when developing a custom package?

Cheers,
E

**Comment by canvural** [comment]
Hello,

Do you have `orchestra/testbench` installed? If not, installing this will probably help you.

**Comment by szepeviktor** [comment]
You may also want to see this.

https://github.com/szepeviktor/bazar/blob/467466c6300c4fb07eafebd020e13dd580c31e0a/.github/workflows/static-analysis.yml#L30-L32

**Comment by nasyrov** [comment]
@canvural I got `orchestra/testbench` installed, doesn't help.

@szepeviktor thanks, saw it, but this one is migration-related, isn't it?

I think the problem might be here: https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php#L46

When we bootstrap the application for the package we only register the actual package service provider and the rest got ignored, hence we have an error related to missing bindings in the container...

**Comment by BertvanHoekelen** [comment]
I think [enabling package](https://packages.tools/testbench/basic/testcase.html#package-auto-discovery) auto-discovery in testbench should do the trick.

**Comment by wijourdil** [comment]
Hi, I have the same issue (except it's with the package `nWidart/laravel-modules` and not Livewire), and I don't know how to fix it 😞 

> I think enabling package auto-discovery in testbench should do the trick.

Are you sure ? I have tried but it still does not work :/ 
But it seems logical to me, the method `ignorePackageDiscoveriesFrom` must be overrided in the `TestCase` class, which phpstan does not load or include 🤔

**Comment by szepeviktor** [comment]
I'm am very curious of your findings.

**Comment by wijourdil** [comment]
I think I have found a workaround using the testbench bootstrap file.

The issue is when you enter in the `else` at this point : 
https://github.com/nunomaduro/larastan/blob/master/bootstrap.php#L9

So I have created a file `bootstrap/app.php` containing :

```php
<?php

return include getcwd()."/vendor/orchestra/testbench-core/laravel/bootstrap/app.php";
```

And it seems to work now, I don't have the `Target class ['modules'] does not exist` error no more 🤷

**Comment by szepeviktor** [comment]
Thank you.

@canvural Please consider automating this.

**Comment by nunomaduro** [comment]
This is not an issue, but an possible improvement. Feel free to make a pull request with your proposal.
