### ISSUE TITLE
`Model::::withTrashed()->where('id', $id)->restore()` returns `Builder<Model>`

### ISSUE THREAD

**Issue by PiousVenom** [nunomaduro/larastan#833]
- Larastan Version: 0.7.6
- `--level` used: 5

### Description
When running phpstan, the error comes back:

```
Strict comparison using === between Illuminate\Database\Eloquent\Builder<App\Models\Developer> and false will always evaluate to false.
```

### Laravel code where the issue was found

```php
// PlatformController

public function restore(int $id): RedirectResponse
{
  $response = Platform::withTrashed()->where('id', $id)->restore();

  if ($response === false) { // 👈 
      return redirect()->route('showDeletedPlatforms')
          ->with('success', false)
          ->with('message', 'Failed to restore platform.')
      ;
  }

  return redirect()->route('showPlatform', $id)
      ->with('success', true)
      ->with('message', 'Platform successfully restored.')
  ;
}
```

Aside from the fact that `$response` should be a `bool` ([I believe that issue was fixed](https://github.com/nunomaduro/larastan/issues/832)), it's not even the right model.

**Comment by szepeviktor** [comment]
> Larastan Version: 0.7.6

Could you try it with master?

**Comment by PiousVenom** [comment]
> > Larastan Version: 0.7.6
> 
> Could you try it with master?

I have just done so, and I'm actually not sure if I did it correctly, since I still have the same error I posted in my last message. I copied the files from master to the vendor folder. Am I missing something?

**Comment by szepeviktor** [comment]
It goes like this: `composer require --dev nunomaduro/larastan:dev-master`

**Comment by szepeviktor** [comment]
Do you have `@method static bool restore()` in vendor/nunomaduro/larastan/stubs/EloquentBuilder.stub ?

**Comment by PiousVenom** [comment]
> Do you have `@method static bool restore()` in vendor/nunomaduro/larastan/stubs/EloquentBuilder.stub ?

Yes.

**Comment by szepeviktor** [comment]
🤷

**Comment by PiousVenom** [comment]
![larastan](https://user-images.githubusercontent.com/4548799/119371429-09202400-bc7c-11eb-9197-0b6b12e7d4ae.PNG)

**Comment by PiousVenom** [comment]
I was finally able to solve this by declaring the `restore()` return type and changing my `if`:

```php
    public function restore(int $id): JsonResponse
    {
        /**
         * @var bool|null $response
         */
        $response = Platform::withTrashed()->where('id', $id)->restore();

        if ($response ) {
            return new JsonResponse([
                'success' => true,
                'message' => 'Platform undeleted successfully!',
            ]);
        }

        return new JsonResponse([
            'success' => false,
            'message' => 'Failed to undelete platform!',
        ]);
    }
```

**Comment by szepeviktor** [comment]
```php
        if ($response === true) {
```

Please consider avoiding type juggling, be brave and explicit!

**Comment by szepeviktor** [comment]
And one more thing: put errors in conditionals and expected operation at the beginning of the line.

```php
        if ($response !== true) {
	        return new JsonResponse([
	            'success' => false,
	            'message' => 'Failed to undelete platform!',
	        ]);
        }

        return new JsonResponse([
            'success' => true,
            'message' => 'Platform undeleted successfully!',
        ]);
```

**Comment by canvural** [comment]
Looks like the original issue is solved. And I can't reproduce this on my own.
