### ISSUE TITLE
A little confused as to how to handle Repository return type.

### ISSUE THREAD

**Issue by FlickerBean** [nunomaduro/larastan#835]
- Larastan Version: 0.7.6
- `--level` used: 5

### Description

I have a `User` model which extends `Illuminate\Database\Eloquent\Model` with an associated UserRepository:

```php
<?php

namespace App\Repositories;

use App\Models\User;

class UserRepository extends BaseRepository
{

    /**
     * User Repository constructor.
     *
     * @param User $model - User Model
     */
    public function __construct(User $model)
    {
        parent::__construct($model);
    }

    /**
     * @return User
     */
    public function whereEmailFirst($email): User
    {
        return $this->model->where('email', $email)->first();
    }
}
```

The BaseRepository just assigns the $model parameter to the $model property in the constructor.

Phpstan will throw an error at this:

Method App\Repositories\UserRepository::whereEmailFirst() should return App\Models\User but returns Illuminate\Database\Eloquent\Model.

I'm new to Generics, but i've read various articles etc and am still not understanding exactly how I should handle this situation.

I could add something like `@phpstan-return Illuminate\Database\Eloquent\Model` But this doesn't feel right, as this method will only ever return an Employee.

What would be the correct way of going about this please?

**Comment by canvural** [comment]
Hi,

I think you can solve this with the generics as follows:

`BaseRepository`:
```php
/**
 * @template T of Model
 */
class BaseRepository
{
	/** @var T */
	public $model;
}
```

`UserRepository`:

```php
/**
 * @extends BaseRepository<User>
 */
class UserRepository extends BaseRepository
{
}
```

Then PHPStan would know `$this->model` would refer to `User` in `UserRepository`

**Comment by FlickerBean** [comment]
Wow, it works. Thanks...

Now all I need is to understand how/why.
I think the extends BaseRepository<User> is what I don't fully grasp.

I think i'll have to do some more reading up! Appreciate your fast response though. <3

**Comment by canvural** [comment]
No problem!

You can read these articles:
https://phpstan.org/blog/generics-in-php-using-phpdocs
https://arnaud.le-blanc.net/post/phpstan-generics.html
https://tomasvotruba.com/blog/2021/01/04/phpstan-abstract-parent-generics-dummies/
https://tomasvotruba.com/blog/phpstan-generics-for-dummies-with-two-parents/

I think especially the last two one will help you understand the `@extends BaseRepository<User>` syntax 👍🏽
