### ISSUE TITLE
Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail issue

### ISSUE THREAD

**Issue by Asifkrishaweb** [nunomaduro/larastan#836]
- Larastan Version: 0.7.6
- `--level` used:8

in verified Listener of a event i got error 
  
```
  31     Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail::$role.      
  32     Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail::$email.     
  32     Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail::$email.     
  32     Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail::$name.      
  32     Access to an undefined property Illuminate\Contracts\Auth\MustVerifyEmail::$password.
```

```php
 public function handle(Verified $event)
 {
     if ($event->user->role == 'student') {
         Mail::to($event->user->email)->send(new WelcomeStudent($event->user->name, $event->user->email, $event->user->password));
     }
 }
```

**Comment by szepeviktor** [comment]
Thank you for opening a separate issue!

**Comment by canvural** [comment]
Hi,

This is kind of expected. `user` has a type of `Illuminate\Contracts\Auth\MustVerifyEmail`, but in runtime actually the user model that implements this interface is passed.

So the solution would be to do this:
```php
/** @var \App\Models\User $user`
$user = $event->user;
```

Then use `$user` instead of `$event->user` in the rest of the code.

**Comment by szepeviktor** [comment]
@canvural I've met this 1 zillion times.
Is there a pure programmatical solution for this?

**Comment by szepeviktor** [comment]
Maybe a stub for `vendor/laravel/framework/src/Illuminate/Auth/Events/Verified.php`?

**Comment by canvural** [comment]
@szepeviktor Don't use Laravel 😂 

I think there is no solution for it. Ideally you should always just use the methods available on the interface.

In some cases you can try to use the methods of the interface. Like, instead of `$event->user->email` you can use `$event->user->getEmailForVerification()`

**Comment by canvural** [comment]
You can create your own PHPStan stubs, sure. I think it can't be in Larastan because it's just too specific. And class can implement `MustVerifyEmail`, so we can't just assume it's a user model.
