### ISSUE TITLE
Nested SoftDelete not detected since 0.7.5 

### ISSUE THREAD

**Issue by IAmRGroot** [nunomaduro/larastan#837]
- Larastan Version: ^0.7.5
- `--level` used: 8
- Pull request with failing test: #838 

### Description
Larastan does not detect a nested SoftDeletes trait after updating from 0.7.4 to 0.7.5 or higher. 

### Laravel code where the issue was found
```php
class User extends Authenticatable
{
    public function group(): BelongsTo
    {
        return $this->belongsTo(Group::class)->withTrashed(); // Call to an undefined method Illuminate\\Database\\Eloquent\\Relations\\BelongsTo<App\\Group, App\\User>::withoutTrashed().
    }
}

class Group extends Model
{
    use NestedSoftDeletes;
}

trait NestedSoftDeletes
{
    use SoftDeletes;
}
```

**Comment by canvural** [comment]
Hi,

We are using the PHPStan's MethodReflection method `hasTraitUse` [here](https://github.com/nunomaduro/larastan/blob/master/src/Methods/EloquentBuilderForwardsCallsExtension.php#L103-L106) to determine if a class uses the given trait. Looks like this needs to recursive. But I don't know it's possible.

Please feel free to create a PR that fixes it in the code I pointed out. Also you can ask in PHPStan if you need help with how to solve this.

**Comment by szepeviktor** [comment]
@ondrejmirtes Could you help us whether `hasTraitUse` is recursive?

**Comment by ondrejmirtes** [comment]
Try using `ClassReflection::getTraits()` instead, or send a fix to PHPStan :)

**Comment by IAmRGroot** [comment]
@canvural I've added a function in #838 that collects nested traits as the PHPStan's `collectTraits` function is private. Let me know if this is acceptable.

**Comment by canvural** [comment]
@IAmRGroot Did you try `ClassReflection::getTraits()` first as @ondrejmirtes suggested?

**Comment by IAmRGroot** [comment]
@canvural Yes!

`ClassReflection::getTraits` gives  `App\Group: {"App\\Traits\\NestedSoftDeletes":{}}`

(new) `collectTraitNames` gives `App\Group: ["App\\Traits\\NestedSoftDeletes","Illuminate\\Database\\Eloquent\\SoftDeletes"]`

See the [`ClassReflection::collectTraits` private function](https://github.com/phpstan/phpstan-src/blob/443f980d310c19868ac6b50a734716c22bd481c9/src/Reflection/ClassReflection.php#L342). One could send a PR to make it public, but until then you would need to use your own function.

**Comment by canvural** [comment]
I'm not sure if it's the best thing to duplicate `collectTraits` method in Larastan. @ondrejmirtes `ClassReflection::getTraits()` does not look like it's recursive, as @IAmRGroot pointed out. Would you be fine with a PR that is making `collectTraits` public, or making `hasTraitUse` use `collectTraits`, or do you have any other idea for a solution?

**Comment by ondrejmirtes** [comment]
I'm fine with changing `getTraits()` to be recursive, as getInterfaces already are...

**Comment by canvural** [comment]
@IAmRGroot You can send a PR to PHPStan repo first that changes `getTraits` to be recursive. Then we can use it here, to solve the issue.

**Comment by szepeviktor** [comment]
Is it Done now?

**Comment by ondrejmirtes** [comment]
PHPStan 0.12.90 has just been released - you can now call `ClassReflection::getTraits(true)` and get traits recursively.

**Comment by canvural** [comment]
Closed with https://github.com/nunomaduro/larastan/pull/838
