### ISSUE TITLE
Illuminate\Database\Eloquent\Relations\Relation doesn't have mixin

### ISSUE THREAD

**Issue by nsetyo** [nunomaduro/larastan#840]
- Larastan Version: 0.7.6
- `--level` used: 8

### Description
This is my first git issue and English is not my daily language so I apologize for any mistake in this issue.
I made a method that should return `Illuminate\Database\Eloquent\Builder|Illuminate\Database\Eloquent\Relations\Relation` but chaining that method with builder method is invalid because there is no `@mixin` in larastan stub

![image_2021-06-11_09-55-53](https://user-images.githubusercontent.com/4555074/121624273-c07caf00-ca60-11eb-8322-a7f08256504f.png)

Add `@mixin \Illuminate\Database\Eloquent\Builder` to Relation stub file fixes the issue

**Comment by canvural** [comment]
Hi,

This should not be necessary. We have extensions that are handling that.

Can you show me the code that you get the error from?

**Comment by nsetyo** [comment]
@canvural Thank you for your response

```php

/**
     * @phpstan-return Builder<TModelClass>|Builder<Model>|Relation
     */
    public function query()
    {
        return $this->getModelInstance()->query();
    }

    /**
     * @param string|int $primaryKey
     *
     * @phpstan-return TModelClass
     */
    public function getByPrimaryKey($primaryKey)
    {
        /** @phpstan-var TModelClass $model */
        $model = $this->query()->whereKey($primaryKey)->firstOrFail();

        return $model;
    }
```

I allow child class to override query method to return relation

**Comment by canvural** [comment]
> ```
> /**
>  * @phpstan-return Builder<TModelClass>|Builder<Model>|Relation
>  */
> ```

This return type does not make much sense to me.

What is the class you are extending? Eloquent model?

**Comment by nsetyo** [comment]
> > ```
> > /**
> >  * @phpstan-return Builder<TModelClass>|Builder<Model>|Relation
> >  */
> > ```
> 
> This return type does not make much sense to me.
> 
> What is the class you are extending? Eloquent model?

I create my own class in which that method return Eloquent query or relation query if the parent is set, any better suggestion?

**Comment by canvural** [comment]
```php
    /**
     * @phpstan-return Builder<TModelClass>
     */
    public function query()
    {
        return $this->getModelInstance()->query();
    }
```

this should be enough. If `TModelClass` resolves correctly.

**Comment by nsetyo** [comment]
Thanks, i'll try. let me close this issue then.
