### ISSUE TITLE
BelongsTo relation produces Model|null type

### ISSUE THREAD

**Issue by bramceulemans** [nunomaduro/larastan#842]
- Larastan Version: 0.7.6
- `--level` used: 8
- Failing CI job: https://gitlab.com/rijnijssel/sdxam/-/jobs/1338632111

### Description

I have a non-nullable database column, but it reports as being nullable by phpstan.

```
Parameter #1 $task of method App\Models\ExecutionStudent::getExaminerRole() expects App\Models\Task,
App\Models\Task|null given.
```

### Laravel code where the issue was found

```php
// models are pseudo-code, hopefully it is understandable
class Task {
  int $id
}

class Process {
  int $task_id;

  public function task(): BelongsTo
  {
    return $this->belongsTo(Task::class, 'task_id');
  }
}

$process->task // gives phpstan error
```

**Comment by szepeviktor** [comment]
Thank you for your report.

So you thing there cannot be a process that has no task?

**Comment by bramceulemans** [comment]
Exactly, the migration for the `processes` table is as follows:

```php
Schema::create('processes', function (Blueprint $table): void {
    $table->id();
    $table->timestamps();
    $table->string('name', 100);
    $table->string('description', 255);
    $table->foreignIdFor(Task::class, 'task_id')->constrained();
});
```

**Comment by bramceulemans** [comment]
For now I just added `'#App\\Models\\Task\|null given#'` to the `ignoreErrors` in `phpstan.neon`, but ideally this wouldn't be necessary.

**Comment by szepeviktor** [comment]
If you are looking for a _proper_ :) work-around.

```php
/** @var \App\Models\Task $task */
$task = $process->task;
```

**Comment by szepeviktor** [comment]
I hope @canvural will chime in.

**Comment by bramceulemans** [comment]
> If you are looking for a _proper_ :) work-around.
> 
> ```
> /** @var \App\Models\Task $task */
> $task = $process->task;
> ```

Oh right, yea that's an even better work-around (something only a programmer would say ;p).

**Comment by canvural** [comment]
Hi,

I thought about this a little bit. At first it made sense. But then I thought what if the `Task` is soft deleted, or is there some other scope preventing it to be returned. In that case the relation can still return `null`.

So I don't think we can change this in Larastan. But it's easy to overwrite in your code. You can do:
```php
/**
 * @property-read Task $task
 */
class Process
{
	//...
}
```

and this would do the trick.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by bramceulemans** [comment]
The thing is, `Task` is not soft-deletable, I think it would be better to check for the existence of that trait and then make it return non-null.

For now I will add the suggestion you added. Thank you.

**Comment by canvural** [comment]
> The thing is, `Task` is not soft-deletable, I think it would be better to check for the existence of that trait and then make it return non-null.
> 

Soft delete was just an example. It can be any other constraint. So this is out of scope of a static analysis tool.

**Comment by bramceulemans** [comment]
Alright, thanks for the quick response man!

**Comment by MJTheOne** [comment]
Why is this closed? This is still an issue. Adding `@property-read` is NOT a solution. This opens a whole other can of worms for junior developers.

I've set up an extensive test to try out every angle and larastan does not recognise (even though barryvdh/laravel-ide-helper does) the relation is constrained and therefor should not ever be able to return `null`

**Comment by canvural** [comment]
@MJTheOne From the type perspective we can't know that it never contains `null`

**Comment by MJTheOne** [comment]
@canvural By rereading everything I kinda understand what you are getting at, but the fact remains I determined that I trust the migrations. But now my static analysis tool does not adhere to my stance and I have to do a potentially "dangerous" change to the docblocks of my classes.
Would it be an idea to add a configuration option (a boolean) to "enforce" trusting the migration and "assuming" the type?

**Comment by bram-pkg** [comment]
The explanation makes a lot of sense. Scopes can affect the outcome, for
example and null can be returned.

**Comment by EngHell** [comment]
Larastan is wrong at doing this because of the following:

Static analysis tools, are supposed to help by knowing what's happening, not by making assumptions like what if there's a scope, if Larastan is not capable of realizing if there's a scope active or not that can make a relationship nullable, when indeed it's not then it should not make any assumptions about that.

Making asumptions will only lead to bad results, and if Larastan's devs are so fixated in thinking this is right, there should be a config that turns this off.

**Comment by bram-pkg** [comment]
You're right that it might be nice if configuration allowed for changing this behaviour, but I can't say I agree with the rest of your take on this. The static analysis tool has to make a choice here, and making it nullable is safer than not making it nullable. It's better to have false positives and have some extra null assertions in your code (which should be covered by tests anyway) than to blindly trust a relationship can never be null and have it throw an error on runtime.

**Comment by mad-briller** [comment]
Would a `@property` annotation not suffice to override the behaviour? That's better than enabling or disabling it globally

**Comment by EngHell** [comment]
Can anyone give me an example of a scope or trait that makes a non nullable fk column become null apart from the soft deletable trait?

> Would a `@property` annotation not suffice to override the behaviour? That's better than enabling or disabling it globally

We use a static analysis tool to automate work, if we suddenly start tagging things manually it becomes even more error-prone, I'm not sure what kind of code you usually write, but I end using 4+ relationships in a lot of the business logic and having to check if they are null in each function because of this is becoming crazy, our dev team is thinking of just dropping Larastan in all our projects just because of this.

**Comment by szepeviktor** [comment]
> if we suddenly start tagging things manually

You could use Rector to add a tag to millions of files.

**Comment by bram-pkg** [comment]
Adding a `@property-read` is really a one-time kind of ordeal, also I can imagine quite a few scopes:

```php
public function scopeWhereStatusLive(Builder $query)
{
    return $query->where('status', '=', Status::LIVE);
}
```

And there you've got a scope that could be inside a relationship which suddenly makes a non-null column nullable.

It's a free and open source package, if it's causing you more work than it's saving you - you should simply not be using this. However, personally I do believe that the value this provides to the codebase is bigger than just having to write some `@property-read`'s.

**Comment by Roardom** [comment]
Just ran into this. There also exists this alternative:

```php
// $process->task;
$process->task()->sole();

// Or

// $process->task->name;
$process->task()->soleValue('name');
```

It's also still possible for a task and its process to be deleted between the fetching of both of them.
