### ISSUE TITLE
Should Larastan recognize as() in Relations?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#843]
- Larastan Version: 0.7.6
- `--level` used: 5

### Description

Access to an undefined property App\Models\Sheet::$attachment.

Adding `/** @property \App\Models\Attachment $attachment */` is highly abnormal.

### Laravel code where the issue was found

```php
    /**
     * Get the media for the model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function media(): MorphToMany
    {
        return $this->morphToMany(Medium::class, 'mediable')
                    ->withPivot('meta')
                    ->as('attachment') 👈 
                    ->using(Attachment::class);
    }
```

**Comment by canvural** [comment]
Hi,

It might be possible to infer this. But I see it as a low priority issue, cause you can easily add PHPDoc for it for now, and probably wouldn't implement myself. But of course open to any contributions.

**Comment by nunomaduro** [comment]
This is an edge case. Feel free to make a contribution with this feature.

**Comment by szepeviktor** [comment]
@nunomaduro This is really an edge case and I feel so free but I cannot send a PR :(
