### ISSUE TITLE
ErrorException thrown in /app/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 37 while loading bootstrap file /app/vendor/nunomaduro/larastan/bootstrap.php: Undefined index: psr-4

### ISSUE THREAD

**Issue by MarcinOrlowski** [nunomaduro/larastan#848]
I am trying to make PHPStan happy with Laravel facade while using Github Actions, but my current  attempts to use your library as the bridge failed so far with:

> ErrorException thrown in /app/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 37 while loading bootstrap file /app/vendor/nunomaduro/larastan/bootstrap.php: Undefined index: psr-4

The repository is here: https://github.com/MarcinOrlowski/laravel-api-response-builder
My github workflow is here: https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/.github/workflows/phpstan.yml

I'd appreciate any hints on what I am doing wrong here (if this is my fault)

**Comment by szepeviktor** [comment]
Hello! Very nice library you have there.

"ErrorException thrown" is not the nicest error message!
Try following PSR-4 with all your PHP files and Larastan will run.

On my machine it says: _[ERROR] Found 31 errors_

One more thing, please allow higher versions of Testbench.

**Comment by MarcinOrlowski** [comment]
It was working fine but now it just returned for some odd reasons? Is there anything I can do about that?

https://github.com/MarcinOrlowski/laravel-api-response-builder/runs/2868472473?check_suite_focus=true
