### ISSUE TITLE
Include the Model type within its Factory

### ISSUE THREAD

**Issue by spawnia** [nunomaduro/larastan#855]
- Larastan Version: 0.7.7
- `--level` used: `max`
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/554 https://github.com/nunomaduro/larastan/pull/678

### Description

With a recent Laravel update in Laravel 8.48.2, the return types of some methods in `Factory` were tightened: https://github.com/laravel/framework/pull/37794.

After updating our project, static analyis now shows >300 errors related to the usage of models created through those methods. Switching from `Factory::make()` to `Factory::makeOne()` where appropriate reduced the error count to ~250. There is a multitude of resulting kinds of errors, which I can not simply ignore with a few rules. The underlying reason is that the `Factory` methods return generic `Model` instances, but the following test code assumes a specific `Model` subclass.

Because of this, I find it increasingly more important for Larastan to support the specific `Model` type within factories. Two previous attempts at this were had and stalled:
- https://github.com/nunomaduro/larastan/pull/554 (pre-Laravel 8 factories only https://github.com/nunomaduro/larastan/pull/854#issuecomment-872102555)
- https://github.com/nunomaduro/larastan/pull/678 (compatibility problems with pre-Laravel 8)

### Laravel code where the issue was found

```php
class Foo extends Model {
  public function bar() {}
}

$foo = Foo::factory()->makeOne();
$foo->bar(); // Call to an undefined method Illuminate\Database\Eloquent\Model::bar().
```

**Comment by spawnia** [comment]
Thank you @canvural for your consideration of this issue, following my attempt to revive your PR. I agree that pre-Laravel 8 support is decreasingly less important, so focusing on Laravel 8 seems like a great idea. Major version updates are a breeze anyways with Larastan at your side ✨

**Comment by canvural** [comment]
Hi,

I think we can use #661 to track the progress for Laravel 8 factories support.
