### ISSUE TITLE
Fail to bootstrap application with bamarni/composer-bin-plugin

### ISSUE THREAD

**Issue by bastien-phi** [nunomaduro/larastan#856]
- Larastan Version: 0.7.7
- `--level` used: 8
- Pull request with failing test:

### Description

Phpstan analysis fails  with 
```
Trait "Orchestra\Testbench\Concerns\CreatesApplication" not found 
in vendor-bin/phpstan/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 16
```

Problem was introduced in https://github.com/nunomaduro/larastan/pull/852

My setup is a classic laravel application with vendor-bin composer plugin and larastan installed via vendor-bin

In fact, in `bootstrap.php`, 
```php
if (file_exists($applicationPath = dirname(__DIR__, 3) . '/bootstrap/app.php')) { // Applications and Local Dev
    $app = require $applicationPath;
} else { // Packages
    $app = ApplicationResolver::resolve();
}
```
the app is tried to be resolved from ApplicationResolver::resolve because `$applicationPath` does not exist.

The `bootstrap/app.php` does exist but not at the right place,  relatively to `bootstrap.php`.

The folders look like this :

- app
- bootstrap
  - app.php
- ...
- vendor
- vendor-bin
  - phpstan
    - vendor
      - nunomaduro
        - larastan
          - bootstrap.php
          
`dirname(__DIR__, 3)` does not give project root here

**Comment by szepeviktor** [comment]
Do you have `bamarni/composer-bin-plugin` installed?

**Comment by bastien-phi** [comment]
Yes

Le jeu. 1 juil. 2021 à 17:59, Viktor Szépe ***@***.***> a
écrit :

**Comment by szepeviktor** [comment]
Why do you have Testbench installed?

**Comment by bastien-phi** [comment]
I don't. That's why the trait `Orchestra\Testbench\Concerns\CreatesApplication` is not found :sweat_smile: 

I think something like this should do fix the issue
```
if (file_exists($applicationPath = dirname(__DIR__, 3) . '/bootstrap/app.php')) { // Applications and Local Dev
    $app = require $applicationPath;
}
elseif (file_exists($applicationPath = dirname(__DIR__, 5) . '/bootstrap/app.php')) { // larastan installed via bamarni/composer-bin-plugin
    $app = require $applicationPath;
} else { // Packages
    $app = ApplicationResolver::resolve();
}
```

**Comment by rajyan** [comment]
Sorry I wasn’t aware of this kind of use case.
It might have been better to leave
```php
if (file_exists($applicationPath = getcwd().'/bootstrap/app.php)
```
to make sure about existing use cases…

I’ll make a PR.

**Comment by bastien-phi** [comment]
Thanks !
