### ISSUE TITLE
Recommend making this pretty :-)

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/larastan#86]
Not sure if this progress bar is your doing, or the core extension, but thinking it could be improved with some color and perhaps a different step pattern

![image](https://user-images.githubusercontent.com/183153/43106081-039a70ec-8e8c-11e8-9544-2538920c2388.png)

**Comment by ondrejmirtes** [comment]
Next major version of PHPStan (0.11) will have a progress bar similar to PHPUnit's one. See: https://github.com/phpstan/phpstan/pull/1238 It will also be possible to implement a custom one, which right now isn't so @nunomaduro cannot fullful this request in any way.

**Comment by nunomaduro** [comment]
@mikeerickson No plans for this at the moment. Thanks for your proposal @mikeerickson.

**Comment by mikeerickson** [comment]
@ondrejmirtes assuming you are talking about internally so @nunomaduro does need to implement. I will be happy to make it pretty if you’d all like (seeing as I have a little experience in that avenue)
