### ISSUE TITLE
Feature: Make possible to use custom bootstrap files (Don't throw fatal errors in bootstrap.php)

### ISSUE THREAD

**Issue by rajyan** [nunomaduro/larastan#863]
- Larastan Version: 0.7.8
- `--level` used: 5

I created this issue to know if this feature is acceptable or not.

### Description

For now, if we have a Laravel application that doesn't satisfy
```php
if (file_exists($applicationPath = getcwd().'/bootstrap/app.php'))
```
in https://github.com/nunomaduro/larastan/blob/master/bootstrap.php#L9

larastan would throw an fatal error
```
Fatal error: Trait 'Orchestra\Testbench\Concerns\CreatesApplication' not found in /var/source/app/laravel/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 16
```

I want to configure bootstrap files by my own, and not installing `orchestra\testbench` because it's not a package.

### Feature

Check if class `Orchestra\Testbench\Concerns\CreatesApplication` exists and add a notice if larastan is called without bootstrapping.
For example,
```php
elseif (class_exists('Orchestra\Testbench\Concerns\CreatesApplication')){ // Packages
    $app = ApplicationResolver::resolve();
}
else {
    // add a notice here
    return;
}
```
https://github.com/nunomaduro/larastan/blob/master/bootstrap.php#L11

The notice should be like,
"Install orchestra\testbench for Laravel packages or add bootstrapFiles to phpstan.neon to boot Laravel application"

I thought about making bootstrapFile configurable in larastan, but I think it is too much and this is a simpler and cleaner solution.

### Note

I think this feature would help solving issues like 
https://github.com/nunomaduro/larastan/issues/831
and the notice would be helpful for people who wants to use larastan on Laravel packages like 
https://github.com/nunomaduro/larastan/pull/847

**Comment by nunomaduro** [comment]
Feel free to make a pull request with your proposal.
