### ISSUE TITLE
Unexpected token "|", expected type at offset 0

### ISSUE THREAD

**Issue by cbaconnier** [nunomaduro/larastan#864]
- Larastan Version: 0.7.8
- `--level` used: 5

### Description
When running `./vendor/bin/phpstan analyse --debug` I'm getting the error 

> PHPStan\PhpDocParser\Parser\ParserException 
> Unexpected token "|", expected type at offset 0
**at phar://vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php:87**
```
     83▕         } else {
     84▕             $tokens->dropSavePoint();
     85▕             // because of ConstFetchNode
     86▕         }
  ➜  87▕         $exception = new \PHPStan\PhpDocParser\Parser\ParserException($tokens->currentTokenValue(), $tokens->currentTokenType(), $tokens->currentTokenOffset(), \PHPStan\PhpDocParser\Lexer\Lexer::TOKEN_IDENTIFIER);
     88▕         if ($this->constExprParser === null) {
     89▕             throw $exception;
     90▕         }
     91▕         try {
```

### Laravel code where the issue was found

migration: 

```php

 Schema::create('premiums', function (Blueprint $table)
        {
        
            // ...
            $table->date('date')->nullable();
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();

```

Model: 

```php
class Premium extends Model
{
    use HasPresentation, HasFactory;

    protected $table = 'premiums';

    protected $casts = [
        'date'       => 'date',
        'start_date' => 'date',
        'end_date'   => 'date',
    ];

    public function newPresenter(): PremiumPresenter
    {
        return new PremiumPresenter($this);
    }

```
PremiumPresenter (where I get the error)
```php
class PremiumPresenter extends Presenter
{

    public function __construct(public Premium $premium)
    {
    }

    public function startDate(): string
    {

        if ($this->premium->start_date) { // I get the error here
            return $this->premium->start_date->toUserTimezone()->isoFormat('Ll');
        }

        return '';
    }
}

```

### Debugging details
When `ModelPropertyExtension` cast the property `start_date`, the propery `$this->dateClass` has never been initialized. (And I don't know the reason)

So when it reaches the following switch case, `$realType` will be `null`
https://github.com/nunomaduro/larastan/blob/v0.7.8/src/Properties/ModelPropertyExtension.php#L242

```php
switch ($type) {
    case 'date':
    case 'datetime':
        $realType = $this->dateClass; // null
        break;

```

Then, in this following, line `$realType` will be set to `|null` resulting with the error 
> Unexpected token "|", expected type at offset 0
https://github.com/nunomaduro/larastan/blob/v0.7.8/src/Properties/ModelPropertyExtension.php#L257

```php
if ($this->tables[$modelInstance->getTable()]->columns[$name]->nullable) {
    $realType .= '|null';
}
```

**Comment by szepeviktor** [comment]
Thank you for the report!
Try discovering types in your code

```php
\PHPStan\dumpType($this->premium);
\PHPStan\dumpType($this->premium->start_date);
```

**Comment by canvural** [comment]
Hi,

Thanks for the bug report. I think we can fix this by using `getDateClass` method instead of accessing `dateClass` directly.

**Comment by cbaconnier** [comment]
@szepeviktor Unfortunately I can't dump `$this->premium->start_date` without having a crash.

@canvural Thanks! It indeed fixed the issue by changing locally and could dump afterwards.

In case it's still relevant:

```
  46     Dumped type: Domain\Premium\Models\Premium                                 
  47     Dumped type: Carbon\Carbon|null   
```

Thank you very much for the quickest replies / fix I have ever seen ! 🥰

**Comment by canvural** [comment]
Released in https://github.com/nunomaduro/larastan/releases/tag/v0.7.9
