### ISSUE TITLE
Model factory output does not identify exact model

### ISSUE THREAD

**Issue by erikroznbeker** [nunomaduro/larastan#874]
- Larastan Version: v0.7.10
- `--level` used: 2
- Pull request with failing test:

### Description
- I am working on PHP 8.0.6
- On "laravel/framework": "v8.48.1" all work ok
- On "laravel/framework" versions 8.48.2 and later is failing
- My phpstan.neon includes "- tests"

### Laravel code where the issue was found
My .neon file
```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - app
        - tests
    level: 2
```
My file /tests/Feature/ExampleTest.php
```php
<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_example()
    {
        $user = User::factory()->create();
        $userId = $user->id;
        self::assertNotNull($userId);
    }
}
```

Running:
`./vendor/bin/phpstan analyse`

is throwing error:
```
Note: Using configuration file /Users/eroznbeker/www/example-app/phpstan.neon.
 22/22 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------------------------------ 
  Line   tests/Feature/ExampleTest.php                                                                                     
 ------ ------------------------------------------------------------------------------------------------------------------ 
  13     Access to an undefined property Illuminate\Database\Eloquent\Collection|Illuminate\Database\Eloquent\Model::$id.  
 ------ ------------------------------------------------------------------------------------------------------------------ 

                                                                                                                        
 [ERROR] Found 1 error
```

More info:
it seems that laravel version 8.48.2 and newer have some changes in Factories. What I can see is that Factory::create method in older versions (8.48.1) returns
`     * @return \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
`
and versions after that returns
`     * @return \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model
`
without `mixed`. But rabbit hole goes deeper than that.

Thanks for great job!

**Comment by canvural** [comment]
Hi,

Laravel 8 factory support is not released yet. It's implemented in #861  It's currently in `master` branch. You can try it if you want.
