### ISSUE TITLE
Access to an undefined property Illuminate\Contracts\Auth\Authenticatable

### ISSUE THREAD

**Issue by rognales** [nunomaduro/larastan#878]
- Larastan Version: v0.7.10
- `--level` used: 5

### Description

I have a listener attached to ````Illuminate\Auth\Events\Authenticated```` where I logged the requests to ````App\Models\User::class```` properties

Here's the error

````
  32     Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$timestamps.
  33     Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$last_login_at.
  34     Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$last_login_ip.
  35     Access to an undefined property Illuminate\Contracts\Auth\Authenticatable::$last_login_agent.
````

### Laravel code where the issue was found

```php
/**
* Handle the event.
*
* @param  Authenticated  $event
* @return void
*/
public function handle(Authenticated $event)
{
  $user = $event->user;

  $user->timestamps = false;
  $user->last_login_at = now();
  $user->last_login_ip = $this->request->ip();
  $user->last_login_agent = $this->request->header('user-agent');
  $user->save();
}
```

**Comment by szepeviktor** [comment]
As far as I know `$event->user` not being the type `User` is a known problem.
I search past issues for you...

**Comment by szepeviktor** [comment]
Please see https://github.com/nunomaduro/larastan/issues/836#issuecomment-848637431

**Comment by rognales** [comment]
hi @szepeviktor, thank for the reply.

This [code](https://github.com/nunomaduro/larastan/issues/836#issuecomment-848637431) from that discussion solved it.
