### ISSUE TITLE
How can we learn that AsArrayObject is Countable

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#881]
- Larastan Version: latest
- `--level` used: 5

### Description

When a JSON attribute is cast to `AsArrayObject` Larastan fails to recognize it is countable when using it in PHP function `count()`.

```
Parameter #1 $var of function count expects array|Countable, Illuminate\Database\Eloquent\Casts\AsArrayObject given.
```

Can we do this?

**Comment by canvural** [comment]
Hi,

Can you share the code where the error comes from?

**Comment by szepeviktor** [comment]
`count($review->comments)`

**Comment by szepeviktor** [comment]
It needs no code. Attribute cast to AsArrayObject, count() produces the above error.

**Comment by canvural** [comment]
I've never used that before. So I didn't know. Now read [here](https://laravel.com/docs/8.x/eloquent-mutators#array-object-and-collection-casting), I understand the issue.

I think this needs to be handled [here.](https://github.com/nunomaduro/larastan/blob/master/src/Properties/ModelPropertyExtension.php#L211)

**Comment by szepeviktor** [comment]
Thank you for your investigation.

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/commit/bf1a22ffcc6ea35afc644c07cdc180198a58801b

**Comment by szepeviktor** [comment]
Thank you.
