### ISSUE TITLE
No application encryption key has been specified.

### ISSUE THREAD

**Issue by Jamesking56** [nunomaduro/larastan#882]
- Larastan Version: v0.6.13
- `--level` used: `max`
- Pull request with failing test: Only seems to happen on GitHub Actions

### Description

I've been running Larastan in GitHub actions for a while now and all of a sudden in one of my projects I'm now getting:

```
Error: Internal error: No application encryption key has been specified. Run PHPStan with --debug option and post the stack trace to: phpstan/phpstan/issues/new?template=Bug_report.md
```

Which is really odd, its almost like it has started running Laravel? I'm investigating but have no idea how I'm going to reproduce it, it does not happen locally.

**Comment by szepeviktor** [comment]
Oh noooooooo! We were nabbed.

Larastan starts up Laravel :(

Please define `APP_KEY`
e.g. https://github.com/szepeviktor/bazar/blob/53d0fc4a82eec75d14a220e8fdba18d21510941e/.github/workflows/static-analysis.yml#L34-L38

**Comment by szepeviktor** [comment]
> it does not happen locally

Because :) you have `APP_KEY` in your `.env` file.

**Comment by Jamesking56** [comment]
Is that a recent change?

**Comment by szepeviktor** [comment]
Nope.

**Comment by Jamesking56** [comment]
So how come I haven't needed one for over a year at this point?

**Comment by szepeviktor** [comment]
Please see https://github.com/nunomaduro/larastan/search?q=encryption+is%3Aissue&type=issues
Your application contains a call to `Crypt`

**Comment by Jamesking56** [comment]
Ah that would explain it, I used `Crypt` for the first time in this PR 👍

**Comment by enricodelazzari** [comment]
I use Crypt in a package.
how can I fix it?
