### ISSUE TITLE
Access to an undefined property App\Models\Action::$pivot

### ISSUE THREAD

**Issue by kalizi** [nunomaduro/larastan#883]
- Larastan Version: 0.7.10
- `--level` used: 5

### Description

The command `phpstan analyse` throws an error on a Model instance fetch using an m <-> n relationship with another table.

The error:

```
 ------ ----------------------------------------------------------------------------------------------- 
  Line   Traits/EmbeddableActions.php (in context of class App\Http\Controllers\Auth\LoginController)  
 ------ ----------------------------------------------------------------------------------------------- 
  122    Access to an undefined property App\Models\Action::$pivot.                                     
  131    Access to an undefined property App\Models\Action::$pivot.                                     
  132    Access to an undefined property App\Models\Action::$pivot.                                     
  133    Access to an undefined property App\Models\Action::$pivot.                                     
  134    Access to an undefined property App\Models\Action::$pivot.                                     
 ------ ----------------------------------------------------------------------------------------------- 

```

### Laravel code where the issue was found

EmbeddableActions.php:
```php
$actions = $campaign
            ->actions()
            ->with('action_group')
            ->orderBy('code')
            ->get();

$transformedActions = array();

/**
 * @var Action $action
 */
foreach ($actions as $action) {
    $campaignActions[$action->action_group->code . "." . $action->code] =
        CampaignAction::hydrate([$action->pivot->toArray()])->first();
    // ...
}
```

I'm using `barryvdh/laravel-ide-helper` (v.2.9.1). The model code (i omitted the `where*` of the PHPDoc) is:

```php
/**
 * App\Models\Campaign
 *
 * @property int $id
 * @property int $company_id
 * @property int $gem_id
 * @property \Illuminate\Support\Carbon|null $starts_at
 * @property \Illuminate\Support\Carbon|null $ends_at
 * @property string $slug
 * @property string $name
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Action[] $actions
 * @method static \Illuminate\Database\Eloquent\Builder|Campaign newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Campaign newQuery()
 * @method static \Illuminate\Database\Query\Builder|Campaign onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Campaign query()
 * @method static \Illuminate\Database\Query\Builder|Campaign withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Campaign withoutTrashed()
 * @mixin \Eloquent
 */
class Campaign extends Model
{

    public function actions(): BelongsToMany
    {
        return $this->belongsToMany(Action::class, 'campaign_actions')
            ->withPivot(
                'id',
                'sorting',
                'start_at',
                'ends_at',
            );
    }
}
```

**Comment by szepeviktor** [comment]
> The command `larastan analyse`

Thank you! But there is only `phpstan analyze` :)

**Comment by szepeviktor** [comment]
> I'm using `barryvdh/laravel-ide-helper`

There should not be a need for another tool.
Larastan should be able to recognize who is _on the other end_ of `BelongsToMany`.

BTW Larastan is the superior tool.

**Comment by szepeviktor** [comment]
You can hint Larastan:

```php
    /** @return BelongsToMany<Action> */
    public function actions(): BelongsToMany
```

**Comment by kalizi** [comment]
> > The command `larastan analyse`
> 
> Thank you! But there is only `phpstan analyze` :)

You're right, I didn't notice the error, I'll Fix



> > I'm using `barryvdh/laravel-ide-helper`
> 
> There should not be a need for another tool.
> Larastan should be able to recognize who is _on the other end_ of `BelongsToMany`.
> 
> BTW Larastan is the superior tool.

This was just to say that PHPDoc was autogenerated, I started using larastan after ide-helper, it's a fantastic tool, you're right!

**Comment by kalizi** [comment]
> You can [hint Larastan](https://github.com/nunomaduro/larastan/blob/6a03ad7899f5b71133c459df0260e19491dc5ed4/stubs/BelongsToMany.stub#L7):
> 
> ```
>     /** @return BelongsToMany<Action> */
>     public function actions(): BelongsToMany
> ```

Tried but this doesn't fix the issue

**Comment by szepeviktor** [comment]
Do you have proper migrations? At least for `Action`.

**Comment by kalizi** [comment]
> Do you have proper migrations? At least for `Action` and `Campaign`.
> Larastan reads properties from DB fields.

Yeah sure, DB is created via migrations

**Comment by szepeviktor** [comment]
Have you read #515?

**Comment by kalizi** [comment]
> Have you read #515?

Yes, I tried adding the Pivot class to the `universalObjectCratesClasses` as in the issue but didn't work so I opened this issue.

Is my `phpstan.neon` wrong maybe?

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app

    # The level 8 is the highest level
    level: 5

    universalObjectCratesClasses:
        - Illuminate\Database\Eloquent\Relations\Pivot

    ignoreErrors:
        - '#Unsafe usage of new static#'

    excludePaths:
        - ./tests/**.php

    checkMissingIterableValueType: false
```

**Comment by szepeviktor** [comment]
> Is my `phpstan.neon` wrong maybe?

No.

Does `CampaignAction::hydrate([$action->getRelationValue('pivot')->toArray()])->first();` silence the error?

**Comment by kalizi** [comment]
> > Is my `phpstan.neon` wrong maybe?
> 
> No.
> 
> Does `CampaignAction::hydrate([$action->getRelationValue('pivot')->toArray()])->first();` silence the error?

This did the trick! Thanks a lot!

**Comment by szepeviktor** [comment]
"did the trick" === "dirty work-around"
