### ISSUE TITLE
Magic `orWhere` HigherOrderBuilderProxy not supported

### ISSUE THREAD

**Issue by shaffe-fr** [nunomaduro/larastan#885]
- Larastan Version: 0.7.10
- `--level` used: 2
- Pull request with failing test: #884

### Description

Builder have a magic `orWhere` property that makes easier to do orWhere with scopes.
This feature is not yet supported by Larastan.

### Laravel code where the issue was found

```php

class User extends Models
{
    public function scopeVerified(Builder $query): void
    {
        $query->where('verified', true);
    }
}


User::query()->whereKey(1)->orWhere->verified();
```

I'll try to add support to this in the PR.

**Comment by canvural** [comment]
Hi,

Thank you for reporting the issue, and especially for the failing test case.

I think this can be fixed easily by adding `/** @property-read static<TModelClass> $orWhere */` to  `Builder`  stub [here.](https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L7)

**Comment by shaffe-fr** [comment]
Hi @canvural, 
I'm not (yet) familiar with the internals of the project and was looking into a way more complex solution. I'll update the PR.
Thanks !
