### ISSUE TITLE
Missing support for inbound casting

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/larastan#890]
- Larastan Version: latest
- `--level` used: 6

### Description

Using inbound casting: https://laravel.com/docs/8.x/eloquent-mutators#inbound-casting.

```php
    protected $casts = [
        'bio' => Markdown::class, // sets the attribute value to a `string`
    ];
```

Larastan thinks that `$model->bio` is a `Markdown` instance instead of a string.

**Comment by szepeviktor** [comment]
Thank you for your report!

This is so highly invalid/non-fix that I have to close this issue and remove you from GitHub :)

**Comment by osteel** [comment]
Hi, I think I've got the same issue:

```
 ------ ---------------------------------------------------------------------
  Line   Models/Contractor/Activity/TimeEntry.php
 ------ ---------------------------------------------------------------------
  144    Call to an undefined method App\Casts\DateTimeUtc::diffInMinutes().
 ------ ---------------------------------------------------------------------
```

Here's the cast:

```php
<?php

namespace App\Casts;

use Carbon\Carbon;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

class DateTimeUtc implements CastsAttributes
{
    /**
     * Cast the given value.
     *
     * @param  \Illuminate\Database\Eloquent\Model $model
     * @param  string                              $key
     * @param  mixed                               $value
     * @param  array<string, mixed>                $attributes
     * @return Carbon|null
     */
    public function get($model, $key, $value, $attributes)
    {
        return $value ? Carbon::parse($value) : null;
    }

    /**
     * Prepare the given value for storage.
     *
     * @param  \Illuminate\Database\Eloquent\Model $model
     * @param  string                              $key
     * @param  mixed                               $value
     * @param  array<string, mixed>                $attributes
     * @return Carbon|null
     */
    public function set($model, $key, $value, $attributes)
    {
        return $value ? Carbon::parse($value)->setTimezone('UTC') : null;
    }
}
```

The behaviour started from version `0.7.7` it seems.

**Comment by MatanYadaev** [comment]
Same here.

**Comment by yeganemehr** [comment]
Hi @nunomaduro 

I've got same issue and did some digging about it.
My suggestion is make some improvement here [ModelPropertyExtension.php:254](https://github.com/nunomaduro/larastan/blob/9fa5822057b4e74f3d27c837c09305884ea64c32/src/Properties/ModelPropertyExtension.php#L254) without using stubs and generics to keep it simple for developers.
It can find `readableType` from return type of [CastsAttributes::get()](https://github.com/laravel/framework/blob/aa2853e6cd4e9fd40cea2588cedc84b99cc7ce2a/src/Illuminate/Contracts/Database/Eloquent/CastsAttributes.php#L16) and `writableType` from type of `$value` in [CastsAttributes::set()](https://github.com/laravel/framework/blob/aa2853e6cd4e9fd40cea2588cedc84b99cc7ce2a/src/Illuminate/Contracts/Database/Eloquent/CastsAttributes.php#L27)

It's ok with you that I send a PR for this?
