### ISSUE TITLE
Application not found when running from outside of application root

### ISSUE THREAD

**Issue by AJenbo** [nunomaduro/larastan#895]
- Larastan Version: 0.7.11
- `--level` used: 0

### Description

Running PHPStan from outside the project root causes a load failure when larastan is enabled in phpstan.neon.

Note that this is not a package but a project (using `laravel/framework`)

```
monorepo$ projects/admin/vendor/bin/phpstan analyze -c projects/admin/phpstan.neon -a projects/admin/vendor/autoload.php 
PHP Fatal error:  Trait 'Orchestra\Testbench\Concerns\CreatesApplication' not found in monorepo/projects/admin/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 16
Fatal error: Trait 'Orchestra\Testbench\Concerns\CreatesApplication' not found in monorepo/projects/admin/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 16
```

The issue seam to be that Larastan is not taking the config path in to consideration when auto detecting if what is being scanned is a package or project:

https://github.com/nunomaduro/larastan/blob/master/bootstrap.php#L9

Would it be possible to wither check the path relative to the config path, or to add a parameter for setting the application path?

**Comment by szepeviktor** [comment]
> to add a parameter for setting the application path

👍

**Comment by szepeviktor** [comment]
I hope changing directory works

```sh
cd projects/admin/
vendor/bin/phpstan analyze
```

**Comment by AJenbo** [comment]
> I hope changing directory works
> 
> ```shell
> cd projects/admin/
> vendor/bin/phpstan analyze
> ```

This does not work as the error messages produced are relative to the `projects/admin/` and so errors will not be shown inline in the GitHub ui.

**Comment by AJenbo** [comment]
Without this option is impossible to full integrate with GitHub Actions if the application is not in the root of the repository, the only other alternative would be to have an option for prefixing all error messages with the CWD.

**Comment by canvural** [comment]
This has been discussed many times before. And every time there was a PR to change it, something else broke.

Recommended way is to run PHPStan from the root of the project.

**Comment by szepeviktor** [comment]
@canvural A new option for app root would put an end to this saga.

**Comment by AJenbo** [comment]
> Recommended way is to run PHPStan from the root of the project.

That just isn't an option if you project does not live in the root of the repo, since the errors printed by PHPStan are relative to where it is being run it leaving GitHub clueless of what file the error is for.

There are only 3 option:

A: Add option for app root to Larastan
B: Add path prefix to PHPStan errors
C: Larastan does not work with projects that do not live in the root of there repo

B does not seam a reasonable solution as this issue only happens with Larastan.
C Looks like failure

**Comment by szepeviktor** [comment]
D: There may be a very simple solution: use `sed` on PHPStan's output.

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message

**Comment by AJenbo** [comment]
Thanks, that is a usable workaround, though a bit of a hack. It also feels rather inconsistent this this is needed for projects, but not for packages.

**Comment by AJenbo** [comment]
> D: There may be a very simple solution: use `sed` on PHPStan's output.

A sever issue with this is that it masks the exit code from PHPStan meaning failed runs are allowed to be merged...

**Comment by szepeviktor** [comment]
You tell Bash to exit on PHPStan failures: `set -o pipefail`

**Comment by AJenbo** [comment]
Slight correction here, once you hit level 5 and start validating `view-string` this workaround is also needed for packages in order for TestBench to find the package provider and set the template path. It doesn't seam PHPUnit has the same issue though.
