### ISSUE TITLE
Custom Eloquent Builder not resolved after relation builder methods

### ISSUE THREAD

**Issue by fragkp** [nunomaduro/larastan#897]
- Larastan Version: 0.7.11
- `--level` used: 5
- Pull request with failing test: https://github.com/nunomaduro/larastan/pull/896

### Description

On my project, I rely heavily on custom eloquent builders. To also take advantage of auto completion in phpstorm,  all model calls starting with the `query()` method.

**Example:**
```php
User::query()
    ->whereHas('') // 'normal' builder method
    ->admin() // custom eloquent builder method
    ->first()
```

**Bug:**
After calling `whereHas()` (maybe on other relation methods as well) the custom eloquent builder is not resolved and an error is thrown.

```
Call to an undefined method Illuminate\Database\Eloquent\Builder<App\Models\User>::admin().
```

This bug only appears when combining `query()`, `whereHas()` and `customBuilderMethod()` in this particual order.

**Comment by szepeviktor** [comment]
Thank you for your report.
It'll be resolved in a very short time. ⏳

**Comment by canvural** [comment]
Hi,

Did you setup your custom builders correctly? Like it's described here: https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders

I tested your PR locally, and it works as expected.

**Comment by fragkp** [comment]
I hope I've setup them correctly. Here are my model, custom builder and method call:

```php
class User extends Model
{
    /**
     * @return UserBuilder<User>
     */
    public static function query(): UserBuilder
    {
        return parent::query();
    }

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return UserBuilder<User>
     */
    public function newEloquentBuilder($query): UserBuilder
    {
        return new UserBuilder($query);
    }
}
```

```php
/**
 * @template TModelClass
 * @extends Builder<User>
 */
class UserBuilder extends Builder
{
    public function public(): self
    {
        return $this->where('public', 1);
    }
}
```

```php
class HomeController
{
    public function index()
    {
        $user = User::query()
            ->where('id', 1)
            ->whereHas('relation')
            ->public()
            ->first();

        return $user->not_found;
    }
}
```

If you want, I can also create a test repo.

**Comment by szepeviktor** [comment]
> If you are taking advantage of custom Eloquent Builders for your models, you have to mark your custom builder class as generic

Please consider this.
Now `TModelClass` defined but not used, thus the builder class is not generic.

**Comment by fragkp** [comment]
Mh.. I'm not sure what you mean by 'thus the builder class is not generic.'.

I've added `@template TModelClass of User` to my UserBuilder (as in these tests https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/CustomEloquentBuilderTest.php#L146), but that does not change anything.

**Comment by szepeviktor** [comment]
Does it look like this now?

```php
/**
 * @template TModelClass of User
 * @extends Builder<TModelClass>
 */
class UserBuilder extends Builder
```

**Comment by fragkp** [comment]
Yes, same error happening.

**Comment by canvural** [comment]
I think this might be because of a faulty stub. Can you change [here](https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub#L194) to just `static` locally (in your `vendor` folder) and try again?

**Comment by fragkp** [comment]
This fixed my issue! Should I update the PR or will you create a patch?

**Comment by canvural** [comment]
Yes please update the PR. And I think we just need the `testModelWithCustomBuilderReturnsCustomEloquentBuilderAfterCustomBuilderMethodRelationChainedWithExplicitQueryMethod` test. You can delete others.
