### ISSUE TITLE
Issue with Casted DateTime fields

### ISSUE THREAD

**Issue by jamespavett** [nunomaduro/larastan#902]
- Larastan Version: 0.7.10
- `--level` used: 6

### Description

I have a couple of laravel models which use casting to convert the database dates into different formats:

```php
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'time'  => 'datetime:H:i',
        'ddate' => 'datetime:d/m/Y',
    ];
```

IDE Helper then generated the relevant doc blocks:

```
 * @property \datetime $ddate
 * @property \datetime|null $time
```

However I get the follow errors when running on Level 6:

```
 146   Property App\Models\Day::$ddate (DateTime) does not accept string.
 218   Property App\Models\Day::$time (DateTime) does not accept string.
```

### Laravel code where the issue was found

As two points in my code I am doing the following, essentially setting both fields to their relevant string values.

```php
 $day->ddate   = $this->ddate;  // Value is 26/06/2021
 $day->time    = $this->time;   // Value is 10:00
```

This seems to be conflicting with with the casting. Originally I only meant to use the casting to read the values, but the error is coming from me trying to assign the properties.

Is there anything I can do, or am I making a fundamental mistake? I feel like I need to be converting this back to DateTime objects, however that seems like a lot of unnecessary overhead.

**Comment by szepeviktor** [comment]
Do you mean its type is "string on write" and "DateTime on read"?

**Comment by jamespavett** [comment]
Yea basically that's what I am trying to achieve I think. It all works through Laravel by default but I do get the above errors.

Right now I have changed it to use createFromFormat to get around this issue. Not sure if that is the best way though.

**Comment by szepeviktor** [comment]
> I do get the above errors when running PHPStan.

Have you tried [the above form](https://github.com/nunomaduro/larastan/issues/902#issuecomment-886944403)?

**Comment by jamespavett** [comment]
Oh sorry @szepeviktor I completely missed the bit @property-read about @property-write, that will probably work perfectly.

Is that an acceptable way of doing it? I'm not sure if I should just continue converting the values back to the expected type or use the above suggestion.

**Comment by szepeviktor** [comment]
AFAIK As I know Larastan supports `datetime` casting.
https://github.com/nunomaduro/larastan/blob/206d005cb500d3bc61e1936f5ce06a96d2116aaa/src/Properties/ModelPropertyExtension.php#L246

1. Remove all `@property` tags
2. Use Carbon for dates

This string-in DataTime-out is not supported.
I think it is "anti-static analysis" to use strings as date.

**Comment by canvural** [comment]
`@property-read` and `@property-write` is wrong thing to use. It's not related to this issue.

If IDE helper adds those PHPDocs, then Larastan will use them. And as far as I know there is no way to describe different types for read and write type in PHPDocs.

But if you remove those PHPDocs generated by IDE helper, then Larastan can help.

We support different types for read and write. All you need to do is add your properties to `protected $dates` instead of `$casts`
