### ISSUE TITLE
Errors on HasMany relationship methods

### ISSUE THREAD

**Issue by osteel** [nunomaduro/larastan#909]
- Larastan Version: 0.7.5+
- `--level` used: 6

### Description

Hi, I get errors on some method calls for `HasMany` relationships, from version 0.7.5 onwards:

```
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Apis/Main/V1/GlobalActivities/Policies/Delete.php
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  32     Call to private method count() of parent class Illuminate\Database\Eloquent\Relations\HasOneOrMany<TRelatedModel of Illuminate\Database\Eloquent\Model>.
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
```

### Laravel code where the issue was found

Here is the definition of the `timeEntries` method, defined on the `GlobalActivity` model, on which `count()` is called:

```php
    /**
     * The model's time entries.
     *
     * @return HasMany<TimeEntry>
     */
    public function timeEntries(): HasMany
    {
        return $this->hasMany(TimeEntry::class, 'activity_id', 'id');
    }
```

As you can see I specified the model in the docblock, like mentioned [here](https://github.com/nunomaduro/larastan/issues/824#issuecomment-826089099), for instance.

And here is the actual call of the `count()` method, causing the error:

```php
<?php

namespace App\Apis\Main\V1\GlobalActivities\Policies;

use App\Apis\Policy;
use App\Models\Contractor\Activity\GlobalActivity;
use App\Models\User\User;

class Delete extends Policy
{
    /**
     * {@inheritdoc}
     *
     * @param  User           $user
     * @param  GlobalActivity $activity
     * @return void
     */
    public function __construct(
        protected User $user,
        protected GlobalActivity $activity,
    ) {
    }

    /**
     * {@inheritdoc}
     *
     * @return bool
     */
    public function granted(): bool
    {
        if ($this->activity->timeEntries()->count()) {
            return false;
        }

        // ... other irrelevant code ...
    }
}
```

**Comment by canvural** [comment]
Hi,

I think the issue is `$this->activity` What is the type of `activity`?

**Comment by osteel** [comment]
@canvural updated original post for clarity. `activity` is of type `GlobalActivity`, where the `timeEntries` method is defined

**Comment by osteel** [comment]
@canvural updated again so you can see the whole calling class

**Comment by canvural** [comment]
Ah ok. I see.

Can you try and write the output of `\PHPStan\dumpType($this->activity->timeEntries());` And try once again with `@return HasMany<TimeEntry>` removed from the PHPDocs.

**Comment by szepeviktor** [comment]
@canvural You were faster then me :)

**Comment by szepeviktor** [comment]
BTW @osteel `{@inheritdoc}` is something that is long time deprecated. At least in PHPStan World.

**Comment by osteel** [comment]
@canvural here's the dump with the `@return` statement:

```
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Apis/Main/V1/GlobalActivities/Policies/Delete.php
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  31     Dumped type: Illuminate\Database\Eloquent\Relations\HasMany<App\Models\Contractor\Activity\TimeEntry>
  33     Call to private method count() of parent class Illuminate\Database\Eloquent\Relations\HasOneOrMany<TRelatedModel of Illuminate\Database\Eloquent\Model>.
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
```

And after removing the statement:


```
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Apis/Main/V1/GlobalActivities/Policies/Delete.php
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
  31     Dumped type: Illuminate\Database\Eloquent\Relations\HasMany<App\Models\Contractor\Activity\TimeEntry>
  33     Call to private method count() of parent class Illuminate\Database\Eloquent\Relations\HasOneOrMany<TRelatedModel of Illuminate\Database\Eloquent\Model>.
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------
```

They're the same.

@szepeviktor I don't use it in the context of PHPStan specifically, if that's your point?

**Comment by szepeviktor** [comment]
BTW2 Try to stay away from type juggling

```diff
- if ($this->activity->timeEntries()->count()) {
+ if ($this->activity->timeEntries()->count() !== 0) {
```

**Comment by osteel** [comment]
@szepeviktor err yeah, I know. Old habits die hard 😅

**Comment by canvural** [comment]
I tried to reproduce this but I couldn't.

So I guess you need to debug more. There is something wrong with your setup maybe.

**Comment by osteel** [comment]
Hmm I'll see what I can do but this is a fairly simple setup to be honest, I'm not sure what I could be doing wrong. It may be related to `HasMany` specifically, as I have a very similar setup with a `BelongsToMany` relationship (calling `count()` on the relationship directly) and Larastan doesn't flag anything.

**Comment by szepeviktor** [comment]
I've done a theoretical research and found nothing wrong.
Maybe `App\Apis\Policy` has something in it.

**Comment by szepeviktor** [comment]
Try debugging your HasMany and BelongsToMany and compare types.

**Comment by osteel** [comment]
Here are both types:

```
Dumped type: Illuminate\Database\Eloquent\Relations\HasMany<App\Models\Contractor\Activity\TimeEntry>
Dumped type: Illuminate\Database\Eloquent\Relations\BelongsToMany<App\Models\User\User>
```

They both look fine to me, only that the `HasMany` one causes an error when `count()` is called on it, while `BelongsToMany` doesn't.

Also, here's the content of `Policy`:

```php
<?php

namespace App\Apis;

use App\Models\User\User;

abstract class Policy
{
    /**
     * Constructor. The user is the one whose right to perform the action is checked by the policy.
     *
     * @return void
     */
    public function __construct(
        protected User $user,
    ) {
    }

    /**
     * Whether the user is allowed to perform the action.
     *
     * @return bool
     */
    abstract public function granted(): bool;
}
```

Nothing out of the ordinary, I'd say?

Out of curiosity, what version of Laravel are you using for your test? I'm `8.48.1`.

**Comment by szepeviktor** [comment]
> what version of Laravel are you using for your test? I'm `8.48.1`.

I don't have Laravel installed.

**Comment by szepeviktor** [comment]
In Larastan's CI:

https://github.com/nunomaduro/larastan/blob/9b13f0f94f71d1ae3f794a99e22c0ad1484a737e/.github/workflows/tests.yml#L18

**Comment by osteel** [comment]
Wild guess as I honestly don't know what this code is doing, but could it come from [this](https://github.com/nunomaduro/larastan/compare/v0.7.4...v0.7.5#diff-d60fcc424da8b0730617982f9bc4d24ca70f3019ecff6e43b1be82bd1b1fac94R41)?

The above is a line taken from the diff between 0.7.4 and 0.7.5. As a matter of fact, I've got the exact same issue with a call to `exists` on a `HasMany` relationship too (haven't mentioned it so far because I didn't want to clutter this GitHub issue). `exists` is also in the array, although then again I've got no idea what the change is actually doing.

> In Larastan's CI:

Ok cool, this was probably irrelevant anyway.

**Comment by osteel** [comment]
I've unfortunately run out of time I can spend on this for now. Will try and give it another go when I get the chance. Thanks for the help!

**Comment by szepeviktor** [comment]
> Wild guess as I honestly don't know what this code is doing, but could it come from [this](https://github.com/nunomaduro/larastan/compare/v0.7.4...v0.7.5#diff-d60fcc424da8b0730617982f9bc4d24ca70f3019ecff6e43b1be82bd1b1fac94R41)?

@osteel Try removing that line in your copy of Larastan!

**Comment by osteel** [comment]
@szepeviktor just did that and not only the errors are still there, I've got a slew of new errors too 😅 

Might not be a good lead to follow.

**Comment by canvural** [comment]
I can't reproduce this.

Please try to prepare a small repository that can reproduce this. Or a failing test case in a PR.

Thank you.

**Comment by osteel** [comment]
For reference – I left this aside for a while, and looked into it again today while trying to upgrade to Larastan 1.0. I still have the issue (albeit worded differently), and it turns it comes from [this package](https://github.com/grimzy/laravel-mysql-spatial) I'm using on the model having problems. It seems that [this trait](https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/Eloquent/SpatialTrait.php) in particular is messing something up.

**Comment by szepeviktor** [comment]
Could this help? https://github.com/nunomaduro/larastan/issues/1001#issuecomment-958312062

**Comment by osteel** [comment]
@szepeviktor thanks for the pointer. There's probably a way to go around it, yes; that being said, the truth is I should get rid of this package altogether. It's unmaintained, and also [interferes with parallel testing](https://github.com/grimzy/laravel-mysql-spatial/issues/169)
