### ISSUE TITLE
Question: is \Illuminate\Contracts\Pagination\Paginator generic?

### ISSUE THREAD

**Issue by lptn** [nunomaduro/larastan#910]
### Description

On our project I use larastan + psalm + phpcs (slevomat coding standard) and we use syntax like `Illuminate\Contracts\Pagination\LengthAwarePaginator<App\Models\Users\User>` to describe content of iterable types, slevomat has an awersome rule:
```xml
<rule ref="SlevomatCodingStandard.TypeHints.ReturnTypeHint">
    <properties>
        <property name="traversableTypeHints" type="array">
            <element value="\Illuminate\Database\Eloquent\Collection"/>
            <element value="\Illuminate\Support\Collection"/>
            <element value="\Illuminate\Contracts\Pagination\Paginator"/>
            <element value="\Illuminate\Contracts\Pagination\CursorPaginator"/>
            <element value="\Illuminate\Contracts\Pagination\LengthAwarePaginator"/>
            <element value="\Illuminate\Pagination\AbstractCursorPaginator"/>
            <element value="\Illuminate\Pagination\AbstractPaginator"/>
            <element value="\Illuminate\Pagination\CursorPaginator"/>
            <element value="\Illuminate\Pagination\LengthAwarePaginator"/>
            <element value="\Illuminate\Pagination\Paginator"/>
        </property>
    </properties>
</rule>
```

But larastan doesn't treat Paginator instances as Generics:

```
PHPDoc tag @return contains generic type Illuminate\Contracts\Pagination\LengthAwarePaginator<App\Models\Users\User> but class Illuminate\Contracts\Pagination\LengthAwarePaginator is not generic.
```

Do we have any reasons for that?

**Comment by szepeviktor** [comment]
We have the stub file for it: https://github.com/nunomaduro/larastan/blob/9b13f0f94f71d1ae3f794a99e22c0ad1484a737e/stubs/Contracts/Pagination.stub#L12-L17

`LengthAwarePaginator` is an interface. I think you should use generics on the implementation.
@canvural How is this thing?

**Comment by canvural** [comment]
No, `LengthAwarePaginator` and `Paginator` contracts are not generic. They don't extend `Iterable` or `ArrayAccess` so there is no point to make them generic.

But the concrete class `Illuminate\Pagination\LengthAwarePaginator` does implement `IteratorAggregate` and `ArrayAccess`. And it's markes as generic here: https://github.com/nunomaduro/larastan/blob/master/stubs/Pagination.stub
