### ISSUE TITLE
`when` on `EloquentBuilder` returns `mixed`

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#915]
https://github.com/nunomaduro/larastan/blob/ab50705bd46b9a7f4306a50d9a507b0e418173d4/stubs/EloquentBuilder.stub#L423

I think we can do better than `mixed|$this` here. This was also discussed [here.](https://github.com/laravel/framework/pull/38018)

Main issue is `$callback` and `$default` can return anything. But maybe we can solve this with generics.

*Also, `when` method is now in the `Conditionable` trait. So we can make this solution more generic. But that's a separate issue.*

**Comment by szepeviktor** [comment]
BTW `mixed|anything` is just `mixed` :)
