### ISSUE TITLE
PHPDoc tag @extends contains generic type PostBuilder<MyModel> but class PostBuilder is not generic.

### ISSUE THREAD

**Issue by trascent** [nunomaduro/larastan#919]
- Larastan Version: 0.7.12
- `--level` used: 6

### Description

Hello. I'm trying to use Custom Eloquent Builders together the [Corcel Library](https://github.com/corcel/corcel) (Connection with WordPress). I have a builder class that extends from PostBuilder (Corcel class) and in turn extends from Builder. Both larastan shows: 

```
PHPDoc tag @extends contains generic type Corcel\Model\Builder\PostBuilder<MyModel> but class Corcel\Model\Builder\PostBuilder is not generic.
```

### Laravel code where the issue was found

```php
/**
 * @template TModelClass of MyModel
 * @extends \Corcel\Model\Builder\PostBuilder<TModelClass>
 */
class MyBuilder extends PostBuilder {}

// ---

class MyModel extends Corcel {}
```

**Comment by szepeviktor** [comment]
Hello! Thank you for your report.

Try adding a stub for `PostBuilder` similar to https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub
