### ISSUE TITLE
Illuminate\Database\Query\Builder: Call to an undefined method

### ISSUE THREAD

**Issue by helloiamlukas** [nunomaduro/larastan#922]
- Larastan Version: 0.7.12
- `--level` used: 2

### Description

```
Call to an undefined method Illuminate\Database\Query\Builder::whereEmail().
```

I get this error when I try to call

```php
$user = \App\Models\User::query()->whereEmail('test@test.test')->first()
```

This is the docblock I have within my User model:

```php
/**
 * App\Models\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string|null $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Database\Factories\UserFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @mixin \Eloquent
 */
```

But it seems like this docblock doesn't have any influence on the error. I deleted it and it still had the same result.

**Comment by szepeviktor** [comment]
@helloiamlukas !
Thank you for your report.

We have a passing test: https://github.com/nunomaduro/larastan/blob/884b7014141ab7c4552aa8d73823c7db4882742f/tests/Features/Methods/Builder.php#L32

**Comment by helloiamlukas** [comment]
That's strange indeed 🤔 

Any idea why it doesn't work for me?

**Comment by szepeviktor** [comment]
> Any idea why it doesn't work for me?

Your model must cause it.

**Comment by helloiamlukas** [comment]
Sorry, I found the reason for the error now.

It was not `\App\Models\User::query()->whereEmail('test@test.test')->first()`
The actual problem was some lines after that:

```php
DB::table('users')->whereEmail('test@test.test')->first()
```

I changed it to

```php
DB::table('users')->where('email', 'test@test.test')->first()
```

Now it works 🎉

Thank you for the fast reply though :)

**Comment by szepeviktor** [comment]
You're welcome.
