### ISSUE TITLE
Pulling Model properties from Migrations

### ISSUE THREAD

**Issue by brachycera** [nunomaduro/larastan#923]
- Larastan Version: `"nunomaduro/larastan": "^0.7.12"`
- `--level` 5:
- Pull request with failing test: --

### Description

First of thanks for your effort and the Larastan package. It is super helpful. I had some Problems fixing the  `Access to an undefined property App\Models\XXXX`.

- Model classes don't have their properties defined 
- `_ide_helper.php` and `_ide_helper_models.php` files from `"barryvdh/laravel-ide-helper": "^2.8",` are used

After a little digging I found out Larastan uses the Migration files to learn about the Model/Table structure. (Maybe it would be helpful to add this information in the description :wink:)

Since I had a little change in my Migrations where I defined a `var` for the second `Schema::create()` parameter and didn't put the callback directly in the `Schema::create()` function call. Larastan was not able to pick up the Model properties.

### Laravel code where the issue was found

Migration File where Larastan **didn't** pickup up the Model properties.
```php
$blueprint = function (Blueprint $table) {
     $table->bigIncrements('id');
     $table->string('firstname');
     $table->string('lastname');
     ...
     ...
     ...
};

Schema::create('customers',  $blueprint);

```
Error Messages:
```bash
Access to an undefined property App\Models\Customer::$firstname.
Access to an undefined property App\Models\Customer::$lastname.
```

Migration File where Larastan **did** pickup up the Model properties.
```php
Schema::create('customers', function (Blueprint $table) {
     $table->bigIncrements('id');
     $table->string('firstname');
     $table->string('lastname');
     ...
     ...
     ...
});
```
No Error Messages.

Model `customer`

```php
    /**
     * Accessors to the customers fullname.
     *
     * @return String
     */
    public function getFullNameAttribute()
    {

        return "{$this->firstname} {$this->lastname}";

    }
```

**Comment by szepeviktor** [comment]
> Migration File where Larastan **did** pickup up the Model properties.

Hello @brachycera! That is good news.

This is **static** analysis, it works by reading your code.

**Comment by szepeviktor** [comment]
Removing a temporary variable looks very nice!

**Comment by brachycera** [comment]
Wow, thanks for this lightning fast response  :thumbsup: :astonished:

Took me while to figure this out!
