### ISSUE TITLE
Recognise scopes from `@method` tags on a model

### ISSUE THREAD

**Issue by stayallive** [nunomaduro/larastan#925]
- Larastan Version: 0.7.12
- `--level` used: 3

### Description

I am not sure if this a limitation of PHPStan or Larastan, but I'll check here first.

I am trying to get the `notArchived` scope to work for this model:

```php
use Illuminate\Database\Eloquent\Builder;

/**
 * @method Builder scopeNotArchived(Builder $query)
 */
class User extends Model {}
```

The above is unable to find the scope, changing it to an actual method works as expected:

```php
use Illuminate\Database\Eloquent\Builder;

class User extends Model
{
	public function scopeNotArchived(Builder $query): Builder
	{
		return $query;
	}
}
```

Browsing through the code I came across this line: 

https://github.com/nunomaduro/larastan/blob/99e7aec53075882ef3c254a2671baa994b89b188/src/Methods/BuilderHelper.php#L143

It seems to be (partially) responsible for not finding the method when it's in a docbloc.

I have been trying to change that or figure out why not but was unsuccessful 😄 

Is there a way to get scopes recognized using docbloc `@method` definitions?

**Comment by szepeviktor** [comment]
Thank you for your question!

When you add a `@method` where is that method defined?

**Comment by stayallive** [comment]
The method is defined in a similar way like the SoftDeletes trait works. So it's kinda magic which why it's not picked up in the first place. 

So I hoped the docbloc could "trick" (or teach) Larastan in believing the method exists since the code works fine.

**Comment by szepeviktor** [comment]
The word _Archived_ cannot be found in Laravel framework's source code.
Are you using a package for "Archived"?

**Comment by stayallive** [comment]
It is my own code and the scope name was just an example.

My question is how I can teach Larastan using a `@method` doc annotation a "magic" scope exists. 

I want my first example from the original question to work the same as the last. Currently they don't.

**Comment by szepeviktor** [comment]
If your Models are having scope - possible through traits - I think Larastan will recognize them.
Make sure you have the proper docblocks.

@canvural Could you chime in?

**Comment by szepeviktor** [comment]
If you get errors during analysis please share your error message and corresponding source code.

**Comment by stayallive** [comment]
Code:

```php
<?php

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @method Builder scopeSomeOtherScope(Builder $builder)
 */
class MyModel extends Model
{
    public function scopeSomeScope(Builder $query): Builder
    {
        return $query->whereNull('some_column');
    }
}

MyModel::query()->someScope()->get();

MyModel::query()->someOtherScope()->get();
```

Error:

```
 ------ ---------------------------------------------------------------------------------------------- 
  Line   test.php                                                                                      
 ------ ---------------------------------------------------------------------------------------------- 
  19     Call to an undefined method Illuminate\Database\Eloquent\Builder<MyModel>::someOtherScope().  
 ------ ---------------------------------------------------------------------------------------------- 
```

**Comment by szepeviktor** [comment]
Laravel doesn't discover scopes from `@method` tags.
Where is your `scopeSomeOtherScope` method coming from? Larastan will surely understand that!

**Comment by szepeviktor** [comment]
:) It is a secret? :)

**Comment by stayallive** [comment]
The scope comes the same way `SoftDeletes` registers it's scopes. Larastan has special cases for that on every corner and I am trying the prevent having the need for it.

I'm not here to discuss my way of defining / registering my scopes. I know Larastan is perfectly capable of discovering scopes defined the regular way. This is unfortunately not always an option.

I am just requesting how I can get it to discover the scopes from a `@method` tag which should be the exact same thing as having the real method defined. The `@method` tag is able to solve many other PHPStan error for magic methods so I don't see why it would not work for scopes too 😄

**Comment by szepeviktor** [comment]
> I know Larastan is perfectly capable of discovering scopes defined the regular way. This is unfortunately not always an option.

I see. I'm not in charge of the direction Larastan goes.
Let's see what future holds.

**Comment by ryangjchandler** [comment]
@stayallive Shouldn't your `@method` tag remove the `scope` part of the method name? Since the method you actually call would be something like `MyModel::someScope()`.

Your `@method` declaration would end up being:

```php
/**
 * @method Builder someOtherScope(Builder $builder)
 */
class MyModel extends Model
{
    public function scopeSomeScope(Builder $query): Builder
    {
        return $query->whereNull('some_column');
    }
}
```

**Comment by stayallive** [comment]
No that won't work since it won't be recognized as a method on the builder:

```php
<?php

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @method Builder someScope(Builder $builder)
 */
class MyModel extends Model
{
}

MyModel::query()->someScope()->get();
```

```
 ------ ----------------------------------------------------------------------------------------- 
  Line   test.php                                                                                 
 ------ ----------------------------------------------------------------------------------------- 
  13     Call to an undefined method Illuminate\Database\Eloquent\Builder<MyModel>::someScope().  
 ------ ----------------------------------------------------------------------------------------- 
```

It is very important to note that the `scopeSomeScope` method does not exist anywhere and that is why I want to define it with a `@method` tag to learn Larastan it is there :)

What you are doing in your example works because you have the `scopeSomeScope` method on the model which is perfectly recognized by Larastan already, the `@method` tag does nothing for the builder and if it would it already would've worked anyway.

**Comment by ryangjchandler** [comment]
Oh sorry, I just saw the `Builder` part. I thought you were struggling with `@method` declarations on the model directly.

**Comment by canvural** [comment]
Hi,

Yeah it looks like this is not supported. I'll check this next week 👍🏽

**Comment by canvural** [comment]
Implemented in https://github.com/nunomaduro/larastan/commit/88422fb90e85385245fb1badcaf5fbd8e0a1530d

**Comment by canvural** [comment]
No problem 👍🏽 One thing to note, you need `Builder<static>` or `Builder<ModelName` in your `@method` tag as the return value.

**Comment by stayallive** [comment]
I can certainly live with that, thanks! 👍
