### ISSUE TITLE
[Feature Request] validate Job::dispatch() args 

### ISSUE THREAD

**Issue by dianfishekqi** [nunomaduro/larastan#927]
### Description
Currently the only way to make sure  larastan validates Job arguments correctly is to use `dispatch(new Job(...$args))`
calling `Job::dispatch(...$args)` fails to catch missing arguments/argument types

**Comment by szepeviktor** [comment]
Hello @dianfishekqi! Thank you for your report.

PR-s are welcome.

**Comment by szepeviktor** [comment]
Actually this is a PHPStan feature: detecting constructor parameters.

`Job::dispatch` needs a new extension (PHP code in Larastan)

**Comment by canvural** [comment]
Hi,

I'm not sure if this is even possible with PHPStan.

@ondrejmirtes Is it possible to write some kind of extension or something to say that a method should have the same signature as the constructor? [Here](https://phpstan.org/r/05b49eb6-ff9c-470d-9233-7baab9245861) is an example. A string is passed to `make`, and this will [fail in runtime](https://3v4l.org/3dbZY).

**Comment by ondrejmirtes** [comment]
@canvural You can definitely write a custom rule for this :) Feel free to check out the new guide if you don't know where to start: https://phpstan.org/developing-extensions/rules

**Comment by szepeviktor** [comment]
Thank you.

@ondrejmirtes I always wanted to ask: what are _extensions_ and _rules_? Is one the subset of the other?

**Comment by ondrejmirtes** [comment]
@szepeviktor See: https://phpstan.org/developing-extensions/extension-types

**Comment by canvural** [comment]
Implemented in #991
