### ISSUE TITLE
Error for undefined properties that exist

### ISSUE THREAD

**Issue by FunctionDJ** [nunomaduro/larastan#928]
- Larastan Version: 0.7.12
- `--level` used: 2

### Description

There are a few model properties where Intelephense knows about it (thanks to laravel-ide-helper), but phpstan/larastan doesn't.
Example: (i'm using a [problem matcher for phpstan](https://gist.github.com/FunctionDJ/5a9cae80511a2a24202386347cb55286))
![image](https://user-images.githubusercontent.com/34871211/132701996-2db323b1-edec-4959-8880-27effd1c15cf.png)

There are a few more, this is just the parsed output from a scan with level 2:
![image](https://user-images.githubusercontent.com/34871211/132702097-69a450c0-b15c-497d-8690-8441a25958e0.png)

I assumed that that way because i didn't have my generated ide-helper files configured as stubs, but [according to this post](https://github.com/nunomaduro/larastan/issues/764#issuecomment-764034946) i shouldn't do that, and i also got like a thousand more errors when i added my two ide-helper files as stubs.

So i don't really know how to fix these. All of the properties in the error messages exist, and Intelephense also picks them up. I just need to figure out how to tell phpstan/larastan :)

**Comment by szepeviktor** [comment]
Thank you for bringing this up!

Could you share your source code, also the Model and the error message of PHPStan?

**Comment by FunctionDJ** [comment]
This is what i can share: https://gist.github.com/FunctionDJ/b76fcd4692a9837765bffb500eeac973
The error is: `Access to an undefined property App\\Models\\ItemProfile::$warehouse.`

I know that ide-helper gets the information about the properties that exist by inspecting the database. How does larastan achieve this normally? I'd guess that's where the issue lies.

**Comment by szepeviktor** [comment]
Very nice. Thank you!

If you have proper migrations in place Larastan will recognize the property.

**Comment by szepeviktor** [comment]
You can make Larastan read inactive migration by setting an arbitrary path
https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-paramaters.md#databasemigrationspath

**Comment by FunctionDJ** [comment]
@szepeviktor I have non-collapsed migrations in place... default path. Also Larastan should then also raise an error with all the other occurrences where i access a model property, but it only has an issue with a few select properties - seemingly random.
How does Larastan evaluate migration files? Does it run them using a virtual DB, or does it do static code inspection? Because in that case the issue might be that i'm not using string literals like `Schema::create("mytable")` but instead i use variables `Schema::create($tableName)`.

**Comment by szepeviktor** [comment]
> Does it run them using a virtual DB, or does it do static code inspection?

Of course static analysis.

Please avoid using variables in migrations.
e.g. like in these files https://github.com/nunomaduro/larastan/tree/master/tests/Unit/data

**Comment by FunctionDJ** [comment]
> Please avoid using variables in migrations.

That's where the issue lies most likely then. I'll try to check tomorrow and report back.
