### ISSUE TITLE
withTrashed() not recognized for relation when newEloquentBuilder() is overridden

### ISSUE THREAD

**Issue by brogier** [nunomaduro/larastan#929]
- Larastan Version: 0.7.12
- `--level` used: 2

### Description
So ive been pulling my hair out because in the code below

```php
// OrderRow.php

public function order(): BelongsTo
{
    return $this->belongsTo(Order::class)->withTrashed();
}
```

results in `Call to an undefined method Illuminate\Database\Eloquent\Relations\BelongsTo<App\Models\Order>::withTrashed().` The order is using soft deletes btw.

After trial and error if narrowed it down to my newEloquentBuilder() overwrite in my order.php file. If i remove my custom eloquent builder below everything is fine.

```php
public function newEloquentBuilder($query): OrderQueryBuilder
{
    return new OrderQueryBuilder($query);
}
```

My question is, how do I change my code that larastan knows that I use the custom eloquent builder and also SoftDeletes?

Ive tried to add the `@method withTrashed()` etc to the docblock but without success.

Hope someone can point me in the correct direction.

**Comment by szepeviktor** [comment]
Hello @brogier!
I'm sorry for your loss of hair :)

Please use generics in your builder.
e.g. https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub

**Comment by szepeviktor** [comment]
I think we check here whether the Model uses `SoftDeletes`
https://github.com/nunomaduro/larastan/blob/a51374ecc64c47ab02782a60365f7054466aae4f/src/Methods/EloquentBuilderForwardsCallsExtension.php#L115

**Comment by brogier** [comment]
> Hello @brogier!
> I'm sorry for your loss of hair :)
> 
> Please use generics in your code.
> https://github.com/nunomaduro/larastan/blob/master/UPGRADE.md#custom-eloquent-builders
> and maybe https://github.com/nunomaduro/larastan/blob/master/stubs/EloquentBuilder.stub

Thanks that fixed the issue!

There is still an issue in the same file but with morphTo() and withTrashed(). Tinkered around with the EloquentBuilderForwardsCallsExtension.php and the model reflection defaults to eloquent\model. Tried to typehint the morphTo method but without any luck.

```php
// OrderRow.php

public function itemable(): MorphTo
{
    return $this->morphTo()->withTrashed();
}
```

**Comment by brogier** [comment]
When i pass the Product::class to the morphTo instead of the database reference 'itemable' phpstan passes. 
```php
/**
 * @return MorphTo<Product, OrderRow>
 */
public function itemable(): MorphTo
{
    return $this->morphTo(Product::class)->withTrashed();
}
```

It fails with 
```php
return $this->morphTo('itemable')->withTrashed();
```

and
```php
return $this->morphTo()->withTrashed();
```

Ill investigate some further.

**Comment by szepeviktor** [comment]
> When i pass the Product::class to the morphTo instead of the database reference 'itemable' phpstan passes.

All right!
When you add the typehint you have to add the generics in the PHPDoc block also.

**Comment by szepeviktor** [comment]
> Tinkered around with the EloquentBuilderForwardsCallsExtension.php

You have the `\PHPStan\dumpType()` function to debug types.

**Comment by brogier** [comment]
> > When i pass the Product::class to the morphTo instead of the database reference 'itemable' phpstan passes.
> 
> All right!
> When you add the return typehint you also need generics in the PHPDoc block.

Could you by any change give me an example for a generics for the morphTo as i'm unable to get this one working.

**Comment by szepeviktor** [comment]
> Could you by any change give me an example for a generics for the morphTo as i'm unable to get this one working.

You find source code, tests and stubs in this repo: https://github.com/nunomaduro/larastan/search?q=morphTo
