### ISSUE TITLE
getting error with using  tucker-eric eloquentFilter.

### ISSUE THREAD

**Issue by harrisdt15f** [nunomaduro/larastan#931]
- Larastan Version: v0.7.12 
- `--level` used: max
- Pull request with failing test:

### Description
package link  : https://github.com/Tucker-Eric/EloquentFilter
need help , when I use the feature in this filter package. I got errors

```
Method App\ModelFilters\Systems\SystemUsersHelpCenterFilter::dataId() should return 
            App\ModelFilters\Systems\SystemUsersHelpCenterFilter  
but returns Illuminate\Database\Eloquent\Builder.
```

### Laravel code where the issue was found

```php
class SystemUsersHelpCenterFilter extends ModelFilter
{
    /**
     * ID
     *
     * @param  integer $dataId ID.
     * @return SystemUsersHelpCenterFilter
     */
    public function dataId(int $dataId): SystemUsersHelpCenterFilter
    {
        return $this->where('id', $dataId);
    }
}
```

**Comment by szepeviktor** [comment]
Hello 👋 
Try `@return SystemUsersHelpCenterFilter<\Illuminate\Database\Eloquent\Builder>`

**Comment by szepeviktor** [comment]
[off] Try getting the author of that package use Larastan and PHP generics.

**Comment by harrisdt15f** [comment]
@szepeviktor  then I got these 
------ ----------------------------------------------------------------------- 
  Line   SystemUsersHelpCenterFilter.php                                        
 ------ ----------------------------------------------------------------------- 
  27     PHPDoc tag @return with type                                           
         Illuminate\Database\Eloquent\Builder<App\ModelFilters\Systems\SystemU  
         sersHelpCenterFilter> is incompatible with native type                 
         App\ModelFilters\Systems\SystemUsersHelpCenterFilter.                  
  27     Type App\ModelFilters\Systems\SystemUsersHelpCenterFilter in generic   
         type                                                                   
         Illuminate\Database\Eloquent\Builder<App\ModelFilters\Systems\SystemU  
         sersHelpCenterFilter> in PHPDoc tag @return is not subtype of          
         template type TModelClass of Illuminate\Database\Eloquent\Model of     
         class Illuminate\Database\Eloquent\Builder.                            
  29     Method App\ModelFilters\Systems\SystemUsersHelpCenterFilter::dataId()  
         should return App\ModelFilters\Systems\SystemUsersHelpCenterFilter     
         but returns Illuminate\Database\Eloquent\Builder.

**Comment by canvural** [comment]
Hi,

This is not related to Larastan or PHPStan.

The package you are using has `__call` method in the `ModelFilter` class. That is responsible for the return type.

You can either write an extension for that (see this guide [here)](https://phpstan.org/developing-extensions/class-reflection-extensions#methods-class-reflection-extensions) or you can ignore this error.
