### ISSUE TITLE
A question about stubs

### ISSUE THREAD

**Issue by roni-estein** [nunomaduro/larastan#935]
Hey, sorry to make an issue of this, there is no discussion on the repo. Is there a way to use the eloquent stubs in a laravel project in phpstorm?  to enable things like better code completion in tests with relationships and scopes?

Thanks!

**Comment by szepeviktor** [comment]
Hello Roni!

This is [Larastan's repo](https://github.com/nunomaduro/larastan/blob/6191f5c1ba70f269e54bd635ea77d5fed21fcf83/extension.neon#L1-L34).
Are you looking for support on using phpstorm?

**Comment by roni-estein** [comment]
Wow, I can't thank you enough for pointing to that post!!! It was so complete! Perhaps a link and a quick sentence in the docs is worth while. 😁

**Comment by szepeviktor** [comment]
It is enough to be the first result for `phpstorm sutb` in Google Search.
