### ISSUE TITLE
Call to an undefined method Illuminate\Database\Eloquent\Relations\MorphTo::withTrashed()

### ISSUE THREAD

**Issue by alecpl** [nunomaduro/larastan#942]
- Larastan Version: 0.7.12
- `--level` used: 4

### Description

The issue is similar to #225 and it was mentioned in the comments, but it is still not fixed therefor the new ticket.

`Call to an undefined method Illuminate\Database\Eloquent\Relations\MorphTo::withTrashed()`

### Laravel code where the issue was found

```
public function loggableUser()
{
     return $this->morphTo()->withTrashed();
}
```

**Comment by canvural** [comment]
Hi,

There is no way to know what model does `$this->morphTo()` refers by static analysis. So this issue will not be fixed. Feel free to ignore the error.

Or you can rewrite it as
```php
public function loggableUser()
{
	/** @var MorphTo<ModelItResolvesTo, ThisModel> */
    $relation = $this->morphTo();

    return $relation->withTrashed();
}
```
if you know what model it resolves to.

**Comment by szepeviktor** [comment]
Few like `@var`. I do.

**Comment by MatanYadaev** [comment]
@canvural There's an option to define multiple models under the `ModelItResolvesTo` generic type?

**Comment by canvural** [comment]
> @canvural There's an option to define multiple models under the `ModelItResolvesTo` generic type?

Do you mean `MorphTo<ModelA|ModelB, ThisModel>` ? I'm not sure if that will work, you can try.
