### ISSUE TITLE
Wrong type on MorphToMany::when

### ISSUE THREAD

**Issue by netpok** [nunomaduro/larastan#944]
- Larastan Version: 0.7.12
- `--level` used: 8

### Description
Given: a `Group` model with a MorphToMany realation to a `User` model
The code below results in the error message:   
```
Parameter #2 $callback of method Illuminate\Database\Eloquent\Relations\MorphToMany<App\Models\User>::when() expects                                                         
callable(Illuminate\Database\Eloquent\Relations\MorphToMany<App\Models\User>, mixed): Illuminate\Database\Eloquent\Builder<App\Models\User>|void,
Closure(Illuminate\Database\Eloquent\Builder, string): void given.
```
But the first parameter is a Builder instance in reality so the relation one is wrong.

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder;

        Group::make()->users()->when('search', function (Builder $query, string $search): void {
            dd(get_class($query)); // dumps: "Illuminate\Database\Eloquent\Builder"
        });
```

**Comment by szepeviktor** [comment]
Just happened to me too.

**Comment by szepeviktor** [comment]
The problem may come from our stubs.
https://github.com/nunomaduro/larastan/blob/a09b4d4d24d39be5a569e52c238ef5347d186b56/stubs/EloquentBuilder.stub#L417-L425

**Comment by szepeviktor** [comment]
@canvural Hello! 👋 What do we have to do here? Please advise.

**Comment by canvural** [comment]
This is a PHPStan limitation, and currently there is no way to fix. Since `when` is called on a relation, it expects the first argument of the closure to be `MorphToMany` not `Builder`

Subscribe to #1110 for updates.

**Comment by szepeviktor** [comment]
😿 😿 😿 
😿 😿 😿 
😿 😿 😿
