### ISSUE TITLE
Cannot install in a v8.62.0 Laravel project

### ISSUE THREAD

**Issue by mdavis1982** [nunomaduro/larastan#952]
- Laravel installer version: 4.2.8
- Laravel version: 8.62.0
- Composer version: 2.1.8

### Description
I cannot install Larastan in a brand new Laravel project.

I'm getting the following error when running `composer require nunomaduro/larastan --dev`:

![image](https://user-images.githubusercontent.com/199807/135900620-fc144369-5748-4fc2-9b43-72d3cd35e311.png)

The error message suggests using the `--with-all-dependencies` option, but that gives the following error:

![image](https://user-images.githubusercontent.com/199807/135900795-bd6af4fc-df64-4b19-b3b0-23bf7c382652.png)

I've tried this on a number of machines with various PHP, Composer and Laravel installer versions.

@jbrooksuk Has also experienced this issue today.

### Steps to Reproduce
1. `laravel new testing`
2. `cd testing`
3. `composer require nunomaduro/larastan --dev`

**Comment by szepeviktor** [comment]
How about adding `--prefer-stable`?

**Comment by szepeviktor** [comment]
[off] When I maintain a Laravel project the first commit **must be** a tagged release of `laravel/laravel`.
This prevents a lot of errors saving countless hours of ddebugging!

**Comment by mdavis1982** [comment]
@szepeviktor Adding `--prefer-stable` doesn't solve this issue.

This problem still persists today using a fresh install of Laravel.

@nunomaduro I've narrowed this down a little...

If I do the following, I can get Larastan installed:

```bash
composer require psr/log:^1.0
composer require nrunomaduro/larastan --dev
```

This downgrades the version of `psr/log` from 2.0.0 to 1.1.4.

I'm not comfortable doing this in a fresh Laravel project as I don't know if Laravel is relying on any v2.0 features of the `psr/log` package?

**Comment by mdavis1982** [comment]
@canvural I think this may be related to Larastan. 

Being unable to install this in a fresh Laravel project seems like it could be an issue. 

I asked Jordi on Twitter and this isn't a Composer issue.

The current situation is that without constraining the `psr/log` package manually (which isn't in the documentation) the given installation steps fail.

That seems less than ideal and something that could be investigated.

**Comment by mdavis1982** [comment]
@szepeviktor I understand this isn't a support forum. 

I'm not installing ANY packages before trying this. The steps to reproduce in my original comment are all that is required to reproduce the issue.

I've replicated this on multiple machines and had a Laravel core team member reproduce it too.

There's definitely something amiss somewhere. 

barryvdh/laravel-debugbar is also facing the same issue.

**Comment by canvural** [comment]
We don't even require `psr/log` package. We require `composer/composer` which requires `psr/log:1.0` And Laravel requires `"psr/log": "^1.0 || ^2.0"` So when installing larastan Composer should be able to determine to install `psr/log:^1.0`

So this looks like a Composer issue to me still. I don't even know what we can do here.

**Comment by szepeviktor** [comment]
> So this looks like a Composer

Maybe!

> We don't even require `psr/log` package.

This is about the latest development version of Larastan + Laravel + Composer.

**Comment by szepeviktor** [comment]
Here is the timeline.

- first you install `laravel/laravel` is brings `psr/log` v2 with it
- then you install `nunomaduro/larastan` it depends on `composer/composer` which can work only with `psr/log` v1
- so while installing Larastan you need to tell Composer to update `psr/log` too

It can be seen in #955

**Comment by canvural** [comment]
A workaround here would be running `composer require nunomaduro/larastan --dev --no-update` followed by `composer update`

**Comment by szepeviktor** [comment]
This seems to be a problem only on PHP 8. On PHP 7 there is no such conflict.

**Comment by mdavis1982** [comment]
> I hope this is the good answer.

@szepeviktor I'm not sure that this is sufficient, to be honest. The current installation instructions in the README will fail for anyone using PHP 8 and v8.62.0+ of Laravel.

I understand what the issue is, but I'm not sure that pushing the responsibility of a fix to `composer/composer` is a good idea.

I think the installation instructions at least need to be updated with a set of commands that will work. 😄
