### ISSUE TITLE
Call to undefined method on HasMany relation

### ISSUE THREAD

**Issue by DanielMalmgren** [nunomaduro/larastan#954]
- Larastan Version: 0.7.12
- `--level` used: 2

### Description
I feel a bit stupid needing to ask this, but if I have an Eloquent model returning HasMany, how do I get Larastan to understand that this is not a collection of Model but something else?

### Laravel code where the issue was found

```php
// From my model
    public function contents(): HasMany
    {
        return $this->hasMany('App\Content');
    }

// From the code calling it
        foreach($lesson->contents as $content) {
            logger($content->filepath());
        }
```

This gives me `Call to an undefined method Illuminate\Database\Eloquent\Model::filepath().` which seems logical if you think $content is of type Model, but it is really of type App\Content, which has this method. The code works fine. I've tried finding some way of adding typehints that would solve this, but with no result.

**Comment by canvural** [comment]
Hi,

This is working as expected normally. There must be something weird in your setup maybe. Can you give more complete example?

**Comment by szepeviktor** [comment]
Try `return $this->hasMany(Content::class);`
or `/** @phpstan-return HasMany<Content> */`

**Comment by DanielMalmgren** [comment]
> Try `return $this->hasMany(Content::class);` or `/** @phpstan-return HasMany<Content> */`

Nope, none of those made any difference.

> This is working as expected normally. There must be something weird in your setup maybe. Can you give more complete example?

Ah! I'm getting closer. Pasting some more code than before:

```php
        $newLesson = $lesson->replicateWithTranslations();
        $newLesson->times_started = 0;
        $newLesson->active = 0;
        $newLesson->push();

        foreach($lesson->contents as $content) {
            $newContent = $content->replicateWithTranslations();
            $newContent->lesson_id = $newLesson->id;
            $newContent->push();
            Storage::copy($content->filepath().$content->filename(), $newContent->filepath().$newContent->filename());
        }
```

The replicateWithTranslations() method comes from the [laravel-translatable](https://github.com/Astrotomic/laravel-translatable). I tried replacing it with a simple translate() instead and the warning disappeared (though of course it doesn't do what I want). So I guess it's that method that somehow messes with my $content? Should I file a bug there instead?

**Comment by canvural** [comment]
[Looks like](https://github.com/Astrotomic/laravel-translatable/blob/main/src/Translatable/Contracts/Translatable.php#L37) `replicateWithTranslations` returns a `Model` That's the problem.

You have couple of options:

- Use `@var above $newLesson` Like `/** @var Lesson $newLesson`
- Use [stub files](https://phpstan.org/user-guide/stub-files) to add generics to `laravel-translatable` package
- Or send a PR/issue to that repo asking for generics support.
