### ISSUE TITLE
Entry not found exception with laravel validator

### ISSUE THREAD

**Issue by ConorWright** [nunomaduro/larastan#96]
- Larastan Version: 0.2.4
- `--level` used: 0

### Description:

Internal error:                                               
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new  

### Laravel code where the issue was found:

Offending line of code in a custom register method in the laravel `app/Http/Controllers/Auth/RegisterController.php`:

`$this->validator($data)->validate();`

/vendor/laravel/framework/src/Illuminate/Container/Container.php:613

```
 609|         if ($this->has($id)) {
 610|             return $this->resolve($id);
 611|         }
 612| 
  > 613|         throw new EntryNotFoundException;
 614|     }
 615| 
 616|     /**
 617|      * Resolve the given type from the container.

### Exception Trace:

```
1   Illuminate\Container\Container::get("Illuminate\Contracts\Validation\Validator")
/vendor/nunomaduro/larastan/src/Concerns/HasContainer.php:64

2  NunoMaduro\Larastan\Methods\Pipes\Macros::resolve("Illuminate\Contracts\Validation\Validator")
/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php:41
```

**Comment by nunomaduro** [comment]
@ConorWright Are you sure that you are using the version `v0.2.4`? That issue got fixed exactly on that version..

**Comment by ConorWright** [comment]
Just installed this today, this is what's in my `composer.json` after using the `composer require` line from the home page.

`"nunomaduro/larastan": "^0.2.4",`

**Comment by DenzoNL** [comment]
Exact same issue here as @ConorWright. Same version, same error.

**Comment by nunomaduro** [comment]
This issue should be fixed, can you guys make a quick test?

**Comment by psafarcik** [comment]
Hello @nunomaduro,

Ive just tested it with `"nunomaduro/larastan": "^0.2.7"` and still got the same result:
   
```
Illuminate\Container\EntryNotFoundException  :

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:613
    609|         if ($this->has($id)) {
    610|             return $this->resolve($id);
    611|         }
    612|
  > 613|         throw new EntryNotFoundException;
    614|     }
    615|
    616|     /**
    617|      * Resolve the given type from the container.

  Exception trace:
```

**Comment by nunomaduro** [comment]
@psafarcik Please update your Larastan version, and re-run your test.

**Comment by psafarcik** [comment]
Hello @nunomaduro,

its working now with version `"nunomaduro/larastan": "^0.2.7"`:
`php artisan code:analyse -l 0
 131/131 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [OK] No errors`

thanks for fix :-)

**Comment by nunomaduro** [comment]
No problem, enjoy!

**Comment by Sanguigui** [comment]
Everything's working thanks !
