### ISSUE TITLE
Extending eloquent builder to recognise scopes

### ISSUE THREAD

**Issue by faustbrian** [nunomaduro/larastan#963]
- Larastan Version: dev-master
- `--level` used: 8
- Pull request with failing test: n/a

### Description

Since commit https://github.com/nunomaduro/larastan/commit/88422fb90e85385245fb1badcaf5fbd8e0a1530d it is possible to properly discover scopes from models via `@method` DocBlocks but is there an equivalent to that for the `Illuminate\Database\Eloquent\Builder`? The reason for this is that Larastan currently doesn't seem to discover scopes from traits and add them to the `Illuminate\Database\Eloquent\Builder` when interacting directly with the `Illuminate\Database\Eloquent\Builder` inside of the scope functions.

- https://github.com/spatie/laravel-model-status/blob/master/src/HasStatuses.php#L103
- https://github.com/spatie/laravel-model-status/blob/master/src/HasStatuses.php#L75

These methods for example are not being recognised as scopes and as such will result in "Call to undefined method" exceptions being thrown. With the previously linked commit this can be resolved for calls from outside of classes that allow the use of those scopes but when calling these methods directly on an instance of `Illuminate\Database\Eloquent\Builder` they'll be unrecognised.

The obvious solution would be a stub that contains those scopes, similar to how Larastan itself exposes a stub for the Builder and another alternative would be an annotated custom builder by overwriting the `newEloquentBuilder` but I'm wondering if there is a less intrusive solution through some DocBlocks or PHPStan configuration file?

### Laravel code where the issue was found

```php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Spatie\ModelStatus\HasStatuses;

class User
{
    use HasStatuses;

    final public function scopeStandard(Builder $query): Builder
    {
    	// Larastan currently doesn't discover the "scopeOtherCurrentStatus" method from the "Spatie\ModelStatus\HasStatuses" trait so this blows up as "Call to undefined method"
        return $query->otherCurrentStatus("featured");
    }

    final public function scopeFeatured(Builder $query): Builder
    {
    	// Larastan currently doesn't discover the "scopeCurrentStatus" method from the "Spatie\ModelStatus\HasStatuses" trait so this blows up as "Call to undefined method"
        return $query->currentStatus("featured");
    }
}

```

**Comment by canvural** [comment]
Hi,

I believe this should work:
```php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Spatie\ModelStatus\HasStatuses;

class User
{
    use HasStatuses;

	/** @param Builder<User> $query */
    final public function scopeStandard(Builder $query): Builder
    {
    	// Larastan currently doesn't discover the "scopeOtherCurrentStatus" method from the "Spatie\ModelStatus\HasStatuses" trait so this blows up as "Call to undefined method"
        return $query->otherCurrentStatus("featured");
    }

	/** @param Builder<User> $query */
    final public function scopeFeatured(Builder $query): Builder
    {
    	// Larastan currently doesn't discover the "scopeCurrentStatus" method from the "Spatie\ModelStatus\HasStatuses" trait so this blows up as "Call to undefined method"
        return $query->currentStatus("featured");
    }
}
```
