### ISSUE TITLE
collect()->push() expects string-keyed arrays

### ISSUE THREAD

**Issue by Outsidaz** [nunomaduro/larastan#975]
- Larastan Version: 0.7.13
- `--level` used: 5

### Description
Creating multidimensional collection by using collect helper. After that pushing another array into this collection. Everything works fine from the Laravel side, but when after running PHPStan tests received an error for the line `$collection->push($data);`
```
Parameter #1 ...$values of method Illuminate\Support\Collection<int,array<string, array|string|null>>::push() expects array<string, array|string|null>&nonEmpty, array('x', 'x', 'x') given. 
```
Something goes wrong right?

### Laravel code where the issue was found
```php
$collection = collect([
 ['a', 'b', 'c']
]);
$data = array_fill(0, 3, 'x');
$collection->push($data); // <---
```

**Comment by canvural** [comment]
Hi,

Please open a new issue with the code that we can reproduce, if you still have this error.
