### ISSUE TITLE
Request#validate method incorrectly marked as static

### ISSUE THREAD

**Issue by bram-pkg** [nunomaduro/larastan#995]
- Larastan Version: v0.7.15
- `--level` used: 8
- Pull request with failing test: https://gitlab.com/rijnijssel/sdxam/-/merge_requests/79

### Description

Larastan (I think) marks the validate function on the Request object as static, making it impossible to use:

```php
$request->validate([
    'name' => 'User Name',
]);
```

without generating errors.

Even thought on the Request class, this docblock is found:

```php
/**
 * @method array validate(array $rules, ...$params)
 * @method array validateWithBag(string $errorBag, array $rules, ...$params)
 * @method bool hasValidSignature(bool $absolute = true)
 */
```

### Laravel code where the issue was found

```php
protected function validateLogin(Request $request)
{
    $request->validate([
        $this->username() => ['required', 'string'],
        'password'        => ['required', 'string'],
    ]);
}
```

**Comment by bram-pkg** [comment]
Yes, it gives an error on the line of `$request->validate()`. See this MR: https://gitlab.com/rijnijssel/sdxam/-/pipelines/399430651/test_report

```
Dynamic call to static method Illuminate\\Http\\Request::validate().
```

**Comment by szepeviktor** [comment]
Only on PHP 8, not on PHP 7.4.

**Comment by szepeviktor** [comment]
It is mysterious. After disabling all `@Xmethod static array validate` I still get the error in your codebase.
BTW Pipelines are not public.

**Comment by bram-pkg** [comment]
Oops, I will make pipelines public for you!

**Comment by szepeviktor** [comment]
The `phpstan-strict-rules` emits it through `DynamicCallOnStaticMethodsRule`.

**Comment by bram-pkg** [comment]
Ah, weird. Wouldn't a stub be a solution to this perhaps?

**Comment by szepeviktor** [comment]
I hope not!
Please consider opening an issue in `phpstan-strict-rules`
https://github.com/phpstan/phpstan-strict-rules/issues/new

**Comment by szepeviktor** [comment]
Opened https://github.com/phpstan/phpstan-strict-rules/issues/140
