### ISSUE TITLE
Issue upgrading from 0.7.15 to 1.0.0

### ISSUE THREAD

**Issue by u01jmg3** [nunomaduro/larastan#999]
- Larastan Version: `1.0.0`
- `--level` used: `8`

### Description

Since making the switch from `0.7.15` to `1.0.0` I'm now getting the following error. Just wondered what I'm missing? Thanks for all your hard work.

```
In Resolver.php line 288:

  Service of type NunoMaduro\Larastan\Types\RelationParserHelper: Reference to missing service 'currentPhpVersionSimpleDirectParser'. (used in __construct())
```

**Comment by szepeviktor** [comment]
Hello @u01jmg3!
Are you sure you have v1.0 of PHPStan and Larastan too?
https://github.com/phpstan/phpstan-src/blob/f28c7e9d06f65fff2ebcb954a581989078929a90/conf/config.neon#L1536

**Comment by u01jmg3** [comment]
```
C:>composer show
...
nunomaduro/larastan                1.0.0    Larastan - Discover bugs in your code without running it. A phpstan/phpstan wrapper for Laravel
phpstan/phpstan                    1.0.1    PHPStan - PHP Static Analysis Tool
...
```

**Comment by szepeviktor** [comment]
Have you read https://github.com/nunomaduro/larastan/issues/606#issuecomment-646643958 ?

**Comment by u01jmg3** [comment]
What a numpty - thank you
